### ISSUE TITLE
改变provider中链接，节点没全部更新

### ISSUE THREAD

**Issue by Zhaowei-Yu** [Kr328/ClashForAndroid#101]
在provider链接中增加设定参数去除部分节点，刷新后应被去除的节点仍然存在。
![IMG_20200213_124529_004](https://user-images.githubusercontent.com/48342561/74402317-d83d2680-4e5e-11ea-9008-a072a1964e29.jpg)
加入lv=2去除标准节点
但标准节点仍然存在
![Screenshot_2020-02-13-12-38-55-933_Clash](https://user-images.githubusercontent.com/48342561/74402336-e68b4280-4e5e-11ea-947c-bf1b5f4d2d72.png)

**Comment by Zhaowei-Yu** [comment]
但如果是直接使用托管链接加参数，则可去除标准节点

**Comment by Kr328** [comment]
是目前版本的 **预期行为**
接下来的版本将会改善

**Comment by Kr328** [comment]
FIXED in 1.1.0
