### ISSUE TITLE
[BUG] 流量统计有误，部分 Direct 流量被计入

### ISSUE THREAD

**Issue by zoi50a6j** [Kr328/ClashForAndroid#1011]
**描述出现的错误**
流量统计有误，部分 `Direct` 流量被计入。

**如何复现该错误**
复现步骤:
1. 打开酷安，下载任意应用。
2. 通知栏中有流量计入，日志中 `dl.coolapk.com using DIRECT` 。

**预期行为**
不计 `Direct` 流量。

**应用信息**
 - 版本:  v2.3.22 
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: Github

**附加信息**
至少从 v2.3.17 开始问题已存在。

**Comment by akw5454521** [comment]
分应用代理，绕开酷安

**Comment by zoi50a6j** [comment]
举例酷安是便于复现，肯定不止这个。这里 https://github.com/Kr328/ClashForAndroid/issues/505#issuecomment-841793831 也有人报告类似情况。

**Comment by AkariiinMKII** [comment]
cfa统计经过core的流量 ，direct经过core，并没有问题
上面那个是回环

**Comment by akw5454521** [comment]
不对，我又看了下，你说“至少从 v2.3.17 开始问题已存在。”，你得说一下哪个版本没有这个问题

**Comment by xgdgsc** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1013 跟这个有关吗
