### ISSUE TITLE
[Feature Request] 更新配置可以选择不代理

### ISSUE THREAD

**Issue by ckaak** [Kr328/ClashForAndroid#1017]
**功能描述**
如果当前是运行中，且节点不可用，那么配置将无法更新，需要关掉再更新。

**描述你希望的实现方式**
clash可以先尝试不经过代理更新，如果失败自动再代理重试。

**附加信息**
如果已配置自动更新，能返回节点增减结果就更好了。

**Comment by Kr328** [comment]
1. 关掉代理
2. 自行添加规则
