### ISSUE TITLE
[Feature Request] 自动关闭系统DoH或劫持DoH数据包

### ISSUE THREAD

**Issue by HolgerHuo** [Kr328/ClashForAndroid#1019]
**功能描述**
在启动Clash服务后，切换系统dns服务器为非DoH或解析DoH的数据包并就此进行分流

**描述你希望的实现方式**
检测DNS数据包并解析

**附加信息**
在启用DoH服务后 Clash获取到的连接信息全部为IP，但现有规则多为依靠域名来分流，所以需要临时关闭DoH或使用Clash内置Dns来解析

**Comment by Kr328** [comment]
你认为我一个代理应用有权限去改动你的系统设置吗

**Comment by HolgerHuo** [comment]
都能开VPN代理了 
你认为在系统开一个VPN服务器和改DNS设置哪个权限风险更高呢？

**Comment by Kr328** [comment]
你要想清楚 Android 写入设置的权限 是针对全局系统设置的 **任意在 API 里的设置都能修改**

何况还没有修改 DoH/DoT 的 API

再者 VPN 你说说 在现在几乎都是 https 的现代网络环境 有什么很高的风险?

**Comment by HolgerHuo** [comment]
这个方法可能确实不太可行

但使用DoH后 通过DOMAIN匹配的规则完全失效

logcat可以看到所有的连接都是以ip连接 无法匹配到任何域名相关的规则

传统的在VPN配置文件中指定DNS服务器对于配置了DoH的设备好像都会失效

而且系统在解析DoH时仿佛根本不会通过代理渠道

我也没有想到特别好的办法去解决

希望作者或者其他有别的方法的朋友能够提供一些思路w
