### ISSUE TITLE
感觉比老版本耗电量大

### ISSUE THREAD

**Issue by tenclr** [Kr328/ClashForAndroid#102]
老版本可以24小时挂着，现在挂24小时绝对是耗电最多的app。

**Comment by aplixy** [comment]
![Screenshot_2020-02-25-15-10-31-626_com miui securitycenter](https://user-images.githubusercontent.com/5989299/75223317-23e9bb80-57e1-11ea-84e4-b35ec25acb0e.jpg)
谁说不是呢

**Comment by aplixy** [comment]
一晚耗电50%，没法用了，先弃坑了，期待将来能出个稳定点的版本
![Screenshot_2020-02-26-06-38-52-349_com miui securitycenter](https://user-images.githubusercontent.com/5989299/75294569-bdf24800-5863-11ea-8c69-af6bfb0812a4.jpg)

**Comment by TY-LIU** [comment]
@aplixy 我也是这样，但是没你这么凶，有百分之三十多

**Comment by TY-LIU** [comment]
我也希望能够优化下电量消耗的问题

**Comment by jzl2163** [comment]
这个版本（1.1.10）的确有耗电的问题，而且貌似只出现在MIUI上

我只要一打开Clash电量就会断崖下降。关闭后立刻恢复正常
这是我的耗电曲线（80％开启，71％关闭）

**Comment by jzl2163** [comment]
> 这个版本（1.1.10）的确有耗电的问题，而且貌似只出现在MIUI上
> 
> 我只要一打开Clash电量就会断崖下降。关闭后立刻恢复正常
> 这是我的耗电曲线（80％开启，71％关闭）

咦为什么贴不上图啊..

**Comment by aplixy** [comment]
> @aplixy 我也是这样，但是没你这么凶，有百分之三十多

早期版本耗电没这么恐怖，有空对照一下代码看看问题出在哪

**Comment by fengwei23** [comment]
我也感觉新版的耗电有所增加

**Comment by wjfyxk1231** [comment]
> ![Screenshot_2020-02-25-15-10-31-626_com MIUI安全中心](https://user-images.githubusercontent.com/5989299/75223317-23e9bb80-57e1-11ea-84e4-b35ec25acb0e.jpg)
> 谁说不是呢

> ![Screenshot_2020-02-25-15-10-31-626_com MIUI安全中心](https://user-images.githubusercontent.com/5989299/75223317-23e9bb80-57e1-11ea-84e4-b35ec25acb0e.jpg)
> 谁说不是呢

😄你这个也是MIUI吧，我原来也是24小时挂机现在不行喽，兜不住啊😯

**Comment by shuyoucai** [comment]
所有走代理流量应用的耗电都会算在clash上统计，，，你可以使用访问控制模式

**Comment by jzl2163** [comment]
> 所有走代理流量应用的耗电都会算在clash上统计，，，你可以使用访问控制模式

这个我知道啦..VPN应用都是这样的..
但是的确我开Clash整个设备就是更耗电..

**Comment by fgprodigal** [comment]
发热也有点严重

**Comment by shuyoucai** [comment]
> > 所有走代理流量应用的耗电都会算在clash上统计，，，你可以使用访问控制模式
> 
> 这个我知道啦..VPN应用都是这样的..
> 但是的确我开Clash整个设备就是更耗电..

我倒真没觉得耶

**Comment by jzl2163** [comment]
> > > 所有走代理流量应用的耗电都会算在clash上统计，，，你可以使用访问控制模式
> > 
> > 
> > 这个我知道啦..VPN应用都是这样的..
> > 但是的确我开Clash整个设备就是更耗电..
> 
> 我倒真没觉得耶

就这么说吧。
我用Clash和SSR 同样是看1080P的视频半小时，Clash掉了大概12％的电，而SSR只掉了8％，9％左右。
我这个寒假都在对比SSR和Clash的耗电，开Clash在后台分流听国内的网课最多只能亮屏3.5小时，但是SSR可以亮4小时甚至最多一次到了5小时..

**Comment by aplixy** [comment]
> > > > 所有走代理流量应用的耗电都会算在clash上统计，，，你可以使用访问控制模式
> > > 
> > > 
> > > 这个我知道啦..VPN应用都是这样的..
> > > 但是的确我开Clash整个设备就是更耗电..
> > 
> > 
> > 我倒真没觉得耶
> 
> 就这么说吧。
> 我用Clash和SSR 同样是看1080P的视频半小时，Clash掉了大概12％的电，而SSR只掉了8％，9％左右。
> 我这个寒假都在对比SSR和Clash的耗电，开Clash在后台分流听国内的网课最多只能亮屏3.5小时，但是SSR可以亮4小时甚至最多一次到了5小时..

哈哈，大家不必讨论了，想必这个APP不会再更新了

**Comment by cuifua** [comment]
十分赞成，太吃电了，我遭不住了，求下一个版本一定要解决啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复

**Comment by aplixy** [comment]
> 十分赞成，太吃电了，我遭不住了，求下一个版本一定要解决啊啊啊啊啊啊啊啊啊啊啊啊啊

用Surfboard吧，那边团队成熟一点

**Comment by Kr328** [comment]
@aplixy 确实更建议使用已经成熟并且 Release 的 Surfboard

**Comment by fgprodigal** [comment]
> > 十分赞成，太吃电了，我遭不住了，求下一个版本一定要解决啊啊啊啊啊啊啊啊啊啊啊啊啊
> 
> 用Surfboard吧，那边团队成熟一点

你这来捣乱不太讲究吧

**Comment by aplixy** [comment]
> > > 十分赞成，太吃电了，我遭不住了，求下一个版本一定要解决啊啊啊啊啊啊啊啊啊啊啊啊啊
> > 
> > 
> > 用Surfboard吧，那边团队成熟一点
> 
> 你这来捣乱不太讲究吧

哈哈，你看作者都建议用了，我只是一个普通用户😂
