### ISSUE TITLE
[BUG] CFA2.4.2-premium打开speedtest客户端导致CFA崩溃

### ISSUE THREAD

**Issue by MFYDev** [Kr328/ClashForAndroid#1023]
**描述出现的错误**
CFA2.4.2premium连接代理时打开speedtest客户端崩溃

**如何复现该错误**
复现步骤:
1. 使用CFA 2.4.2premium连接代理
2. 打开speedtest客户端
3. CFA崩溃

**预期行为**
不应出现此情况，2.4.1正常

**屏幕截图**
![IMG_20210523_231759](https://user-images.githubusercontent.com/53750381/119266382-2c67b680-bc1d-11eb-8e89-676db295fca9.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米11 Ultra
 - 系统/ROM:  MIUI 12.5最新开发版
 - Android 版本: 11
 - ROM版本: 21.5.20

**应用信息**
 - 版本: 2.4.2
 - 安装包文件名: app-release-univeraal-premium.apk
 - 应用来源: github release

**Comment by opojin** [comment]
已复现

**Comment by FanhuaCloud** [comment]
![Screenshot_20210523_231849_com github kr328 clash](https://user-images.githubusercontent.com/19590243/119267013-a13bf000-bc1f-11eb-8128-ab241c901d51.jpg)
同样复现

**Comment by 22hello** [comment]
foss版也出现此问题

**Comment by MFYDev** [comment]
Bug fixed. Thanks for @Kr328 's hard working. Issue closed.
