### ISSUE TITLE
希望安卓版本增加自定义规则配置，与windows的Parser保持相同功能

### ISSUE THREAD

**Issue by yootor** [Kr328/ClashForAndroid#1048]
希望安卓可以增加自定义规则接口，在更新订阅之后不会覆盖自己的规则，非常感谢~

**Comment by EKyero** [comment]
@yootor https://github.com/tindy2013/subconverter/blob/master/README-cn.md
用subconverter不好吗？
被bot自动删了一遍一遍又一遍还继续发是头铁吗

**Comment by AkariiinMKII** [comment]
@yootor 隆重介绍三样好东西：subconverter、provider、脑子
