### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by villagerpimin** [Kr328/ClashForAndroid#105]
似乎对多线程下载的支持不是很好，比如我在p*rn上下载单个学习资料时，网速可以跑满。但当我同时下载2>个学习资料时，网速就会变得很慢（网速总和相加也没有跑满），甚至断连

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
