### ISSUE TITLE
[Feature Request] “新配置”的名称与文件名保持一致

### ISSUE THREAD

**Issue by 1457384613gh** [Kr328/ClashForAndroid#1050]
**功能描述**
请清晰的描述你想要的功能:

正如Clash for Windows 那样，希望Clash for Android 从文件导入新配置时，配置名称可以与yml/yaml文件名保持一致，以免清楚数据后用户反复手动编辑配置名称。

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能：

先选择导入文件，再编辑配置名称，默认的配置名称为yml/yaml文件名。

**附加信息**
其他的与改功能相关的附加信息:

如果能够添加此Feature，我将不胜感激。

**Comment by Kr328** [comment]
Clash for Android 是 先 **输入配置信息**  再 **下载文件** 输入信息前应该怎么知道要下载的文件名称呢

**Comment by 1457384613gh** [comment]
> Clash for Android 是 先 **输入配置信息**  再 **下载文件** 输入信息前应该怎么知道要下载的文件名称呢

但是clash for windows 做到了。选择本地文件导入后，配置名称与文件名保持一致

**Comment by Kr328** [comment]
我填好名称之后 再保存 回头一看 名称和我之前填上的不一致 你觉得这样合理吗

再者 Android 自从使用 SAF 来 pick 本地文件之后 几乎所有的实现文件名都是 ID 号 是不是我也我也帮你填上一个 0 或者 1000000

还有 不要拿什么 Windows 和 Android 比较 这是两个完全不同的平台 系统的系统 API 完全不一样 相关的项目结构完全不一样 直接比较 和 问 "apk 能在 Windows 上运行吗" 有什么区别
