### ISSUE TITLE
[BUG] 配置文件中节点并未标明UDP可用的情况下代理了UDP流量

### ISSUE THREAD

**Issue by NagaseYami** [Kr328/ClashForAndroid#1051]
### 描述出现的错误
使用Telegram**语音**的时候发现无法连接到Teletram的服务器。
于是便使用Clash for Android自带的Logcat捕捉后发现Telegram发起的UDP链接也被代理了，而我购买的这个机场的SSR节点是不支持UDP的（配置文件里也没有关于UDP的记述，那么默认应该是关闭）

### 如何复现该错误
复现步骤:
1. 准备任意一个不支持UDP的SSR节点
2. 启动Clash for Android
3. 启动Telegram并发起任意语音通话（group或者private皆可）
4. group通话会一直卡在Connecting，private通话20秒后自动被挂断

### 预期行为
配置文件中未写明支持UDP的节点应不被用作UDP代理
当前节点不支持UDP时，UDP流量应该直连（至少Clash for **Windows**的日志上我看到了UDP直连Telegram服务器的记录）

### 屏幕截图
![image](https://user-images.githubusercontent.com/23649435/120933361-690ed400-c72c-11eb-83eb-d9e0e1973227.png)

### 设备信息 (请完成以下信息):
 - 机型: 三星S10
 - 系统/ROM: One UI
 - Android 版本: 11
 - ROM版本: 3.1

### 应用信息
 - 版本: 2.3.22
 - 安装包文件名: 未知
 - 应用来源: Google Play

### 附加信息
虽然和本项目无关，不过经过我的测试，Surfboard也有相同的问题

### 配置文件
```yaml
配置文件太长且本问题和配置文件应该无关所以就不贴了
```

**Comment by NagaseYami** [comment]
### 日志
```text
# Capture on 2021-06-07 01:47:43.039
01:47:43.040    Info: [APP] Logcat level: info
01:47:43.041    Info: [APP] request force GC
01:47:47.557    Info: [TCP] 172.31.255.253:55270 --> 91.108.56.108 match IPCIDR(91.108.0.0/16) using 📲 Telegram电报[*Ultimate|广港|05]
01:47:47.607    Info: [TCP] 172.31.255.253:38014 --> vortex.data.microsoft.com match Match() using 🕹 规则之外[*Ultimate|广港|05]
01:47:50.890    Info: [TCP] 172.31.255.253:60568 --> 149.154.175.57 match IPCIDR(149.154.160.0/20) using 📲 Telegram电报[*Ultimate|广港|05]
01:47:50.899    Info: [TCP] 172.31.255.253:60570 --> 149.154.175.57 match IPCIDR(149.154.160.0/20) using 📲 Telegram电报[*Ultimate|广港|05]
01:47:51.497    Info: [TCP] 172.31.255.253:55286 --> 91.108.56.108 match IPCIDR(91.108.0.0/16) using 📲 Telegram电报[*Ultimate|广港|05]
01:47:54.610    Info: [UDP] 192.168.1.106:50816 --> 91.108.17.22 match IPCIDR(91.108.0.0/16) using 📲 Telegram电报[*Ultimate|广港|05]
01:47:54.656    Info: [UDP] 172.31.255.253:47868 --> 91.108.17.22 match IPCIDR(91.108.0.0/16) using 📲 Telegram电报[*Ultimate|广港|05]
01:47:55.645    Info: [TCP] 172.31.255.253:47020 --> 106.11.43.242 match IPCIDR(106.11.0.0/16) using 🌏 国内媒体[DIRECT]
```

**Comment by akw5454521** [comment]
走direct应该也连不上吧

**Comment by NagaseYami** [comment]
> 走direct应该也连不上吧

我一开始也是这么想的，可还真就连上了（使用Clash for Windows），我也没搞懂
![Snipaste_2021-06-07_01-29-00](https://user-images.githubusercontent.com/23649435/120945158-9b3f2680-c76a-11eb-837b-c1a43a6db11d.png)

**Comment by Kr328** [comment]
所以 为什么不发配置文件呢 开关都在配置上

**Comment by NagaseYami** [comment]
> 所以 为什么不发配置文件呢 开关都在配置上
> 
> 记得把配置上的 server port password obfs-host uuid psk 抹掉

好吧抱歉其实是因为配置文件太大超出了github最大字数限制，弄得我有点烦就犯懒了没贴（（
[配置.txt](https://github.com/Kr328/ClashForAndroid/files/6609749/default.txt)
上传成TXT了，github只能传部分指定后缀名的文件，麻烦您手动更改成ymal了。(((m -__-)m

**Comment by Kr328** [comment]
这个文件是从 Clash for Android 里导出的吗

可以从 配置 -> 编辑 -> 浏览文件 -> 配置文件.yml -> 导出

**Comment by NagaseYami** [comment]
> 这个文件是从 Clash for Android 里导出的吗
> 
> 可以从 配置 -> 编辑 -> 浏览文件 -> 配置文件.yml -> 导出

原来如此，我操作一下，稍等

**Comment by NagaseYami** [comment]
我日。我怎么看到了udp:true。。。。
什么毛病。。。
我自己排查一下。。。

**Comment by NagaseYami** [comment]
我服了。。。。是我的问题，对不住。
是这样的。我买的这个机场能在官网上找到clash订阅链接，而且还有telegram机器人，也可以从机器人处获得订阅链接。。
我手机上为了图方便我就用了telegram机器人给的订阅链接。
但是官网上的订阅链接和telegram机器人给的订阅链接居然有微妙的不同。下载下来的文件内容差距很大。。服了。。。可能是机场那边根本就没更新telegram机器人这边的订阅吧。。。。
好吧没事了，真的对不住。
