### ISSUE TITLE
[BUG] 夸克浏览器访问维基百科异常

### ISSUE THREAD

**Issue by pseadev** [Kr328/ClashForAndroid#1052]
**描述出现的错误**
使用夸克浏览器，访问维基百科页面，平均耗时15秒以上。
使用其它浏览器访问维基，平均只需一两秒。
打开CFA日志，发现出现大量 warning.

**如何复现该错误**
复现步骤:
1. 下载安装夸克
2. 使用clash
3. 访问维基百科

**预期行为**
正常应该在两秒内完成访问。

**屏幕截图**
![Screenshot_2021-06-07-05-26-26-601_com.github.kr328.clash.jpg](https://user-images.githubusercontent.com/25172023/120941146-b0f52180-c753-11eb-81ed-d84c30a8732d.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Redmi k30u
 - 系统/ROM: MIUI
 - Android 版本: 11
 - ROM版本: 12.5.3

**应用信息**
 - 版本: 5.1.0.180
 - 安装包文件名: 不重要
 - 应用来源: 小米应用商店

**附加信息**
无

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
```
HTTP Connection closed: read tcp 127.26.136.180:34109->127.0.0.1:59238: i/o timeout
HTTP Connection closed: read tcp 127.26.136.180:34109->127.0.0.1:59236: i/o timeout
HTTP Connection closed: read tcp 127.26.136.180:34109->127.0.0.1:59234: i/o timeout
HTTP Connection closed: read tcp 127.26.136.180:34109->127.0.0.1:59232: i/o timeout
HTTP Connection closed: read tcp 127.26.136.180:34109->127.0.0.1:59230: i/o timeout
```

**Comment by Kr328** [comment]
务必使用来自 Releases 或者 Google Play 的版本
