### ISSUE TITLE
[Feature Request] 请求使用xumng123/clash XTLS/WS-0rtt内核发布一个版本

### ISSUE THREAD

**Issue by xianren78** [Kr328/ClashForAndroid#1056]
**功能描述**
https://github.com/xumng123/clash/releases

这个fork实现了vless XTLS和Websocket 0-rtt。

**描述你希望的实现方式**
能否以上面那个fork为基础发布一个支持vless XTLS和Websocket 0-rtt的版本。

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
自行编译请
