### ISSUE TITLE
[BUG] 开热点共享之后无法访问网络

### ISSUE THREAD

**Issue by matianhe3** [Kr328/ClashForAndroid#1057]
**Describe the bug**
开热点共享之后无法访问网络
![11623211130_ pic_hd](https://user-images.githubusercontent.com/24929062/121291486-ed26ae80-c91a-11eb-8d5a-6ce9fd1a08a1.jpg)
![21623211131_ pic_hd](https://user-images.githubusercontent.com/24929062/121291494-f0ba3580-c91a-11eb-8fe2-387f0a46d2eb.jpg)
![31623211138_ pic_hd](https://user-images.githubusercontent.com/24929062/121291505-f4e65300-c91a-11eb-8d0d-4e5acd3e518f.jpg)

连上热点之后 国内外网站都无法访问

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: Pixel 4
 - ROM:  lineage
 - ROM Version: latest
 - Android Version 10

**Application Info (please complete the following information):**

 - Version: 2.3.22
 - Apk File Name: [e.g. app-release-arm64-v8a.apk]
 - Distribution Channel: Google Play

**Additional context**

**Configure**
Paste configure file which **removed server info** 
```yaml
# paste here
```

**Logs**
Paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
热点功能并不是应用能控制的 这个问题应该反馈给 ROM 开发者
