### ISSUE TITLE
[BUG] 索尼电视上tls加密的http无法识别

### ISSUE THREAD

**Issue by bestfearless** [Kr328/ClashForAndroid#1059]
**描述出现的错误**
最新相同版本的CFA，在手机上可以使用tls加密的http，但是索尼电视上却无法识别，因而配置文件不能通用

**如何复现该错误**
复现步骤:
1. 在配置文件中加入tls加密的http，可以复现

**预期行为**
预期电视版的CFA也能支持tls加密的http，这样也方便配置文件的通用性

**屏幕截图**

**设备信息 (请完成以下信息):**
 - 机型:索尼X91J

**应用信息**
 - 版本: 2.4.6
 - 安装包文件名: app-premium-universal-release.apk
 - 应用来源: github

**附加信息**
如果大佬需要什么信息，我再补充

**Comment by Kr328** [comment]
截图呢

**Comment by Kr328** [comment]
应用没有区分手机和 TV 只要是个 Android Runtime 虽有功能都一致

**Comment by bestfearless** [comment]
https://share.icloud.com/photos/0IbaiFKWiClmzQQlCQ7Y2dS1A

**Comment by bestfearless** [comment]
额，在Safari浏览器直接上传照片无反应，就发了iCloud的照片分享，大佬您凑合看

**Comment by bestfearless** [comment]
你若需要其他资料，我随时在这边把测试结果或截图发您

**Comment by Kr328** [comment]
配置文件 username 字段值加引号请

**Comment by bestfearless** [comment]
加完以后成功了，非常非常感谢大佬的帮助。
