### ISSUE TITLE
[Feature Request]Dark mode support

### ISSUE THREAD

**Issue by noncharacter** [Kr328/ClashForAndroid#106]
跟随系统模式切换或单独切换

**Comment by comzyh** [comment]
现在就有吧，我这里看已经是跟随系统了。

omniverse <notifications@github.com> 于 2020年2月14日周五 20:39写道：

**Comment by noncharacter** [comment]
> 现在就有吧，我这里看已经是跟随系统了。

老哥你是魅族手机吧？
我这除非去开发者设置里强制启用全局暗色，不然这个不会变色，不过强制启用会让有些图标颜色不对。
另，Google全家桶现在都是跟随系统的

**Comment by Kr328** [comment]
1.1.0 已实现
