### ISSUE TITLE
[BUG] MIUI手机分身中不能正常代理

### ISSUE THREAD

**Issue by misaka-h** [Kr328/ClashForAndroid#1060]
**描述出现的错误**
开启后，手机（分身）系统设置中出现VPN选项，但进入后显示未添加任何VPN，状态栏也没有相应图标。（原空间中没有此问题）此时可以代理浏览器，但是无法从playstore下载软件（可以登陆与搜索）

**如何复现该错误**
复现步骤:上一条中应该已经描述清楚了。

**预期行为**
可以在分身空间中正常使用

**屏幕截图**

**设备信息 (请完成以下信息):**
 - 机型: [例如: Redmi Note 9]
 - 系统/ROM: [例如: MIUI 12]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 12.0.12]

**应用信息**
 - 版本: [例如: 2.4.6.foss]
 - 安装包文件名: [例如: app-foss-release-arm64-v8a.apk]
 - 应用来源: [例如: github releases]

**附加信息**
以下日志是在开启抓取后打开play商店并立即请求下载后产生的，如果将play放在后台，开启抓取后直接请求下载软件，则日志中未新增任何条目。

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
```

**日志**
粘贴日志以帮助侦测错误
```
# Capture on 2021-06-12 23:18:32.990
23:18:32.996    Info: [APP] Logcat level: debug
23:18:33.005    Info: [APP] request force GC
23:18:36.388    Info: [TCP] 172.19.0.1:38232 --> play.googleapis.com match Match() using 🔰模式[49396 2]
23:18:36.549    Info: [TCP] 172.19.0.1:44466 --> connectivitycheck.gstatic.com match GeoIP(CN) using 🎯直连[DIRECT]
23:18:37.093 Warning: [TCP] dial 🎯直连 (match GeoIP/CN) to 114.114.114.114 error: dial tcp4 114.114.114.114:853: i/o timeout
23:18:37.116    Info: [TCP] 172.19.0.1:42066 --> play-fe.googleapis.com match Match() using 🔰模式[49396 2]
23:18:37.156    Info: [TCP] 172.19.0.1:42070 --> play-fe.googleapis.com match Match() using 🔰模式[49396 2]
23:18:37.196    Info: [TCP] 172.19.0.1:40730 --> play-lh.googleusercontent.com match Match() using 🔰模式[49396 2]
23:18:37.201    Info: [TCP] 172.19.0.1:40728 --> play-lh.googleusercontent.com match Match() using 🔰模式[49396 2]
```

**Comment by Kr328** [comment]
分身是另一个用户 Android 每个用户的 VPN 相互独立

换句话说就是分身里也许要安装一个 Clash for Androdi

**Comment by misaka-h** [comment]
> 分身是另一个用户
> 
> Android 每个用户的 VPN 相互独立
> 
> 换句话说就是分身里也需要安装一个 Clash for Android

正是安装在分身中的clash无法正常工作，主空间内正常的

**Comment by Kr328** [comment]
那就不知道了 在 AOSP 中是正常的

**Comment by misaka-h** [comment]
增加一条新发现的问题：分身控制中心中也无法添加clash，具体表现为：添加后退出编辑模式即消失

**Comment by Kia678** [comment]
> > 分身是另一个用户
> > Android 每个用户的 VPN 相互独立
> > 换句话说就是分身里也需要安装一个 Clash for Android
> 
> 正是安装在分身中的clash无法正常工作，主空间内正常的

是你自己的问题

我MIUI 12, Android 10, 在分身里安装cfa使用没有任何问题

**Comment by padbbss** [comment]
我的小米MIUI提示安装包与系统不兼容，大佬了解什么情况吗？
![image](https://user-images.githubusercontent.com/108036002/178134142-9d341d16-5d8a-4867-a459-6926ed0b2ab7.png)

**Comment by misaka-h** [comment]
> 我的小米MIUI提示安装包与系统不兼容，大佬了解什么情况吗？ ![image](https://user-images.githubusercontent.com/108036002/178134142-9d341d16-5d8a-4867-a459-6926ed0b2ab7.png)

查找你手机架构（现在一般是armv8）再选择对应包下载，那么多包不是随便下的。实在不会查就下20多m的整合包，自动根据手机安装。

**Comment by misaka-h** [comment]
> 是你自己的问题
> 
> 我MIUI 12, Android 10, 在分身里安装cfa使用没有任何问题

解决了，系统更新后一切正常。

**Comment by padbbss** [comment]
> 我的小米MIUI提示安装包与系统不兼容，大佬了解什么情况吗？ ![image](https://user-images.githubusercontent.com/108036002/178134142-9d341d16-5d8a-4867-a459-6926ed0b2ab7.png)

已经解决，下载最大的那个包可以安装，之前下载的不对，感谢。
