### ISSUE TITLE
[Feature Request] 希望能够添加一个快捷的开启全局代理的开关

### ISSUE THREAD

**Issue by Void-zack** [Kr328/ClashForAndroid#1061]
**功能描述**
希望能够添加一个快捷的开启全局代理的开关

**描述你希望的实现方式**
感觉目前的代理规则选项不是很直观（也可能是我规则设计不好或者我不太会用的原因，但是还是感觉使用不够方便）

**附加信息**
如果能设计成类似桌面版那种 右菜单键->规则->全局 就挺好的，这样的话临时使用时调整和恢复都挺直观

**Comment by Kr328** [comment]
全局代理本来就不应该是常用功能 

如果需要频繁使用的话 

建议使用 shadowsocks-android 类代理应用
