### ISSUE TITLE
[Feature Request] 有没有方式可以添加自定义规则

### ISSUE THREAD

**Issue by yorks-wong** [Kr328/ClashForAndroid#1062]
**功能描述**
请清晰的描述你想要的功能
URL方式向机场获取节点和规则，有几条规则想要自己加上去，有没有什么方式可以自定义规则，而不会每次更新节点都被重置掉？
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
自己写yaml也行，能自定义就好了
**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
https://github.com/tindy2013/subconverter
