### ISSUE TITLE
Logs选项里面一直空白

### ISSUE THREAD

**Issue by sensen1** [Kr328/ClashForAndroid#107]
版本32，其他都很正常，就是日志logs，里面一直是空白的，不知道是什么原因。 系统Miui10， 权限里面 没有看到 存储，附图。

![IMG_20200216_170624](https://user-images.githubusercontent.com/16550427/74602013-51e34780-50df-11ea-85ba-1185adbdae7a.jpg)

**Comment by Kr328** [comment]
打开日志界面才开始记录
这个不需要存储权限

**Comment by sensen1** [comment]
> 打开日志界面才开始记录
> 这个不需要存储权限

打开了，依然看不到有任何记录，全局模式。logs里面 能看到 访问了哪些远端服务器吗？ Logs记录什么信息呢？

**Comment by Kr328** [comment]
@sensen1 1. 打开这个界面才会开始记录日志
2. 日志记录等级取决于配置文件

**Comment by sensen1** [comment]
> @sensen1 1. 打开这个界面才会开始记录日志
> 2. 日志记录等级取决于配置文件

配置文件 在哪里能设置呢？ 节点来自订阅方式，节点信息里面定义了日志记录方式？

**Comment by Kr328** [comment]
@sensen1 订阅下来的就是配置文件 订阅文件不允许修改

**Comment by sensen1** [comment]
> @sensen1 订阅下来的就是配置文件 订阅文件不允许修改

好的，谢谢，清楚一些了，知道问题在哪里了，需要的话 可以自己定义文件的方式来添加节点，可能就可以看到需要的记录了，主要是有时候想看一下哪些远端需要走代理，方便设置规则，谢谢
