### ISSUE TITLE
[BUG] 自动选择总会选择第一个不可用节点

### ISSUE THREAD

**Issue by Fo0o0oX** [Kr328/ClashForAndroid#1077]
**描述出现的错误**
某机场前两个节点为公告节点，不可使用，即测试不通。机场配置带自动选择，手动测试的情况下，前两个节点不出结果，app会自动选择ping较低的其他结果，但使用一段时间后，app后台测试会默认跳回第一个测试不通的，导致断网。
Windows版本clash会显示前两个节点Timeout，自动选择正常，App手动测前两个无显示，自动选正常，进后台用一段时间就崩，会自动选择第一个不通的。希望修复。

**Comment by Kr328** [comment]
反馈上游请
