### ISSUE TITLE
[BUG] 耗电过多（使用数据时）

### ISSUE THREAD

**Issue by wocala** [Kr328/ClashForAndroid#1078]
**描述出现的错误**
使用数据流量时一天耗电量高达30％，使用WiFi时不到10％，均为轻度使用状态

**预期行为**
耗电量低

**屏幕截图**
手机版无法上传照片

**设备信息 (请完成以下信息):**
 - 机型: 三星s20
 - 系统/ROM: One ui 3.1
 - Android 版本 11

**应用信息**
 - 版本: play版 2.3.21 2.3.22，github 2.4.8
 - 安装包文件名: [例如: app-release-universal.apk]
 - 应用来源: [例如: Google Play]

**Comment by Kr328** [comment]
#505
