### ISSUE TITLE
[Feature Request] 优化电视盒子等非触摸屏设备的操作支持

### ISSUE THREAD

**Issue by Lighsark** [Kr328/ClashForAndroid#1085]
**功能描述**
![20210622_143221](https://user-images.githubusercontent.com/40225316/122875856-671d5580-d367-11eb-9dfd-ea14c0e0d37a.jpg)

电视盒子一般使用遥控操作。
Log 保存操作无法使用遥控操作，必须用鼠标。
保存时无法使用遥控的上下左右按键定位到Save按键，只能选取文件夹。
红圈内的按键无法操作

**描述你希望的实现方式**
可以使用上下左右按键定位到Save按键

**附加信息**

**Comment by Kr328** [comment]
这个界面是系统的 Document/文档 应用 的 自己联系 ROM 提供商
