### ISSUE TITLE
[Feature Request] 旁路由的可行性

### ISSUE THREAD

**Issue by wmyfelix** [Kr328/ClashForAndroid#1090]
Clash For Android运行在openwrt路由局域网下，能否将Clash For Android作openwrt的旁路网关。
换句话说，Android下clash的支持tun网关么

**Comment by Kr328** [comment]
不可以

路由规则和路由表由系统控制 应用无法干涉这个过程

AOSP 默认的实现会只让本机流量进入 tun

**Comment by wmyfelix** [comment]
感谢答复。
