### ISSUE TITLE
[BUG] 状态栏图标有轻微锯齿

### ISSUE THREAD

**Issue by GitHubNeko** [Kr328/ClashForAndroid#1093]
是否重新绘制状态栏Clash图标优化一下？
![IMG_20210701_165631](https://user-images.githubusercontent.com/83487691/124096773-7b5f0200-da8d-11eb-8782-fe0a4a982851.jpg)
![IMG_20210701_165652](https://user-images.githubusercontent.com/83487691/124096784-7d28c580-da8d-11eb-8a44-accc4c88734e.jpg)

**Comment by AkariiinMKII** [comment]
请提供app版本 机器型号 系统版本 DPI
在原生Android上是没有这个问题的
![Screenshot_20210701-170335.png](https://user-images.githubusercontent.com/6019344/124098393-186e6a80-da8f-11eb-98b6-2f4a957fbf07.png)

**Comment by Microbiosis** [comment]
是

来自 ProtonMail 移动端

--------原始邮件--------
在 2021年7月1日 16:58, GitHubNeko 来信：

**Comment by Microbiosis** [comment]
来自 ProtonMail 移动端

--------原始邮件--------
在 2021年7月1日 17:10, AkariiinMKII 来信：

**Comment by GitHubNeko** [comment]
> 请提供app版本机器型号系统版本DPI问题
> 在Android上是没有这个的
> ![Screenshot_20210701-170335.png](https://user-images.githubusercontent.com/6019344/124098393-186e6a80-da8f-11eb-98b6-2f4a957fbf07.png)

Android 9
最新版Clash

**Comment by Kr328** [comment]
填表 设备信息 + 应用信息 请

**Comment by Dabrit** [comment]
好耶 炸毛猫咪
