### ISSUE TITLE
[BUG] 默认开启的“绕过私有网络”功能导致的小bug

### ISSUE THREAD

**Issue by BlademasterQAQ** [Kr328/ClashForAndroid#1100]
**描述出现的错误**
手机1开启热点，手机2连接热点。
手机1是pixel experience系统，开启“允许热点客户端使用此设备的VPN连接”的功能，并开启 Clash For Android VPN。
手机1在开启Clash For Android的时候，手机2会出现断网，关闭手机1的Clash For Android后恢复正常。
热点使用的网段是 192.168.110.0/24

在下图所示的地方关闭“绕过私有网络”功能后恢复正常，手机2可以使用手机1的VPN
![CopyQ iQLdaW](https://user-images.githubusercontent.com/36795725/124378895-8bbde980-dce6-11eb-828a-663b350cbc57.png)

是否不默认开启此功能比较好？

**Comment by Kr328** [comment]
在 AOSP 该选项行为正确 而你是一个特例 一般来说 不应该是特例才需要手动关闭的吗

而对于绝大部分行为正常的机器来说 这个选项能带来局域网应用的体验巨幅提升

**Comment by BlademasterQAQ** [comment]
> 在 AOSP 该选项行为正确 而你是一个特例 一般来说 不应该是特例才需要手动关闭的吗
> 
> 而对于绝大部分行为正常的机器来说 这个选项能带来局域网应用的体验巨幅提升

我不太懂 AOSP 的规范，但是对比其他软件的行为，感觉挺困惑为什么要默认绕过局域网。
Clash For Windows 貌似没有绕过局域网；手机端的VPN我目前只使用了wireguard，其仅提供排除局域网的选项而非默认勾选。

**Comment by Kr328** [comment]
@BlademasterQAQ Clash for Windows 的 tun 实现就是会绕过局域网 这个行为不可更改

默认启用是因为经过 Clash 即使直连 也还是需要至少两次额外的数据复制 以及 经过 Clash 后广播会有异常行为

纯局域网应用几乎都依赖广播发现其他对等设备
某些局域网应用有流量传输功能 经过 Clash 后流量带宽会额外受到 tun 性能 和 内存复制性能 的限制

再者 在对大多数情况下 局域网流量都不会被代理 为什么还要让它们流入增加 Clash 的处理负担呢

最后对于极少数的特例也留了一个选项允许调整 默认选项应当适用于大部分人

**Comment by Kr328** [comment]
@Kr328 WireGuard 是真正意义上的 VPN 

用于多个不同的终端组建一个虚拟的局域网 以此相互通信 如果默认关掉路由局域网的选项 不就相当于自废手脚

对于 WireGuard 的 用户来说 虚拟的局域网通信 才是真正的主流 用作代理才是小众需求

类似 Clash 只是代理应用 本身无法承担 VPN 构建虚拟局域网的作用 自然也就不希望去处理局域网流量

**Comment by BlademasterQAQ** [comment]
明白了，感谢作者的耐心讲解😊
