### ISSUE TITLE
[Feature Request] 导入配置文件步骤繁琐 逻辑不清晰

### ISSUE THREAD

**Issue by jojoxl01** [Kr328/ClashForAndroid#1108]
导入配置文件yaml或者yml文件，点击“点击浏览外部文件”后，就直接跳转到手机的资源管理器即可，然后再选择要导入的文件。 这么明了的操作，也不知道是什么逻辑或者是什么骚操作， “点击浏览外部文件”后又跳出一个“配置文件.yaml"窗口，还需要点击三个点，跳出对话框，然后再点击导入，此时才跳转到手机的资源管理器。跳转打开的这个资源管理器，默认直接打开内部存储或者”文件管理“不就行了，还在左边给分类，用的着 “图库" 用的着 "音乐"吗？？?用的着"录音机"吗？？？用的着"视频"吗？？？这么明了的操作，也不知道是什么逻辑或者是什么骚操作，
导入配置文件后，也不显示导入的文件名称！
![1](https://user-images.githubusercontent.com/32757337/125501229-fefc1b1d-06d0-46d6-8fca-8688d84e914e.jpg)
![2](https://user-images.githubusercontent.com/32757337/125501248-cbddb996-d531-4326-bd4c-28dca1a998ab.jpg)
![3](https://user-images.githubusercontent.com/32757337/125501262-ebbfe6fd-59fa-4730-a76c-6aac721ad9a6.jpg)
![4](https://user-images.githubusercontent.com/32757337/125501272-8166d174-e87d-4782-ab78-76c6a1802ba5.jpg)

**功能描述**
请清晰的描述你想要的功能
返回到早期版本逻辑清晰的文件导入操作
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
返回到早期版本逻辑清晰的文件导入操作
**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
@jojoxl01 点击导入按钮之后就完全是系统自己的界面 你觉得应用能干涉系统界面如何展示内容吗

再者 你不需要导入 provider 不意味着 别人不需要额外导入自己的 provider

**Comment by jojoxl01** [comment]
> @jojoxl01 点击导入按钮之后就完全是系统自己的界面 你觉得应用能干涉系统界面如何展示内容吗
> 
> 再者 你不需要导入 provider 不意味着 别人不需要额外导入自己的 provider
好吧，谢谢你的解答！
