### ISSUE TITLE
[BUG] 请问最新Play商店版本是 Premium 还是 Foss

### ISSUE THREAD

**Issue by phlinhng** [Kr328/ClashForAndroid#1109]
Play 商店描述中并未注明是 Premium 还是 Foss。

**Comment by Kr328** [comment]
Play 商店的版本有 premium 吗

**Comment by Kr328** [comment]
为了向后兼容 未来当然还是 premium

**Comment by phlinhng** [comment]
感谢回应，因为朋友说最新版 rule-set 不能用（也有可能是他获取规则文件失败的原因，但是他给的信息太少无法判断），所以问问。我记得以前有注明兼容 clash premium 特性，现在看找不到了。

**Comment by phlinhng** [comment]
看到了，最后一点写着 Remote providers, allowing users to get proxy/rule lists remotely instead of hardcoding in config
