### ISSUE TITLE
名称合并不支持emoji，默认也不再滚动，检测节点变慢

### ISSUE THREAD

**Issue by gang4399** [Kr328/ClashForAndroid#111]
如题；
如图：（上下为启用节点名称合并区别）
[点击查看图片](https://i.loli.net/2020/02/20/2dIZAfN4LxEmJ8G.jpg)

**Comment by Kr328** [comment]
1. 已知
2. 预期
3. 预期

**Comment by gang4399** [comment]
如策略组名称 emoji 相同也会被合并，可能不需要处理，但版面会变丑。

**Comment by gang4399** [comment]
> 如策略组名称 emoji 相同也会被合并，可能不需要处理，但版面会变丑。比如下图我只能将港澳和台湾的国旗分开表示。如果是一样的，会显示到下一行，并挤占掉URL-test的显示 

![Screenshot_20200307201334](https://user-images.githubusercontent.com/28175410/76143190-32e82d80-606d-11ea-83d4-51ff8ffe1cd6.jpg)

**Comment by Kr328** [comment]
预期行为
