### ISSUE TITLE
[BUG] 249版本添加配置总是失败

### ISSUE THREAD

**Issue by Dylanweiys** [Kr328/ClashForAndroid#1113]
**描述出现的错误**
安装249版本后，添加配置总是失败，配置文件下载不下来，直接把链接贴到浏览器也不行

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [小米10]
 - 系统/ROM: [MIUI 12.0.11]
 - Android 版本 [10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [2.4.9]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [Github]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
直接粘到浏览器都不行 不去检查链接是否有效 你来这里问我有什么用 浏览器是我写的吗
