### ISSUE TITLE
[Feature Request] 希望可以增加修改policy中的配置文件

### ISSUE THREAD

**Issue by 13426231912** [Kr328/ClashForAndroid#1115]
**功能描述**
希望可以增加修改policy中的配置文件，安卓11中不允许修改，可否提供其他方式覆盖配置中的选项

**描述你希望的实现方式**
可以直接在【配置】中【编辑】修改配置文件

**附加信息**

**Comment by Kr328** [comment]
没看懂是什意思

**Comment by 13426231912** [comment]
指的就是订阅文件中的配置项 有一些订阅可能需要本地进行一下修改

**Comment by Kr328** [comment]
把配置文件复制成本地文件就能直接编辑了

URL 类型的不允许编辑是因为我不想看到 "为什么更新配置之后修改消失"之类的问题

至于非得要修改 URL 类型的话 建议 subconverter

**Comment by 13426231912** [comment]
我手动修改了订阅配置，其中PROXY组的类型为url-test，但是在启动后，看不到对应的代理组

**Comment by xuhaoyang** [comment]
@13426231912 ….代理 -  右上角 - 过滤 - 关闭 不可选择

**Comment by 13426231912** [comment]
十分感谢 原来是自己开了过滤
