### ISSUE TITLE
[Feature Request] 添加intent捷径或桌面shortcut开关以供开启或关闭代理

### ISSUE THREAD

**Issue by TodayNoLunch** [Kr328/ClashForAndroid#1123]
**功能描述**
 添加代理的打开关闭方式，例如intent捷径或桌面shortcut捷径

**描述你希望的实现方式**
类似下图酷安这种![Screenshot_20210728-083512_One UI Home.png](https://user-images.githubusercontent.com/69380335/127246005-076067f7-79a9-4d4e-90c0-e9cc6f27182d.png)

**附加信息**
如果可行，可以增强与其他自动化App联动性

**Comment by EKyero** [comment]
@TodayNoLunch https://github.com/Kr328/ClashForAndroid/issues/326

**Comment by TodayNoLunch** [comment]
> @TodayNoLunch https://github.com/Kr328/ClashForAndroid/issues/326

好像咕了好久了😂
