### ISSUE TITLE
Play商店和youtube代理不了

### ISSUE THREAD

**Issue by LeslieLee0420** [Kr328/ClashForAndroid#113]
用clash之后play商店和youtube连接不了，网页版能正常连接。access  control用的是黑名单模式，切成全部模式也是一样的问题。用v2rayng没这个问题，手机是三星s10，不知道是哪里的问题。

**Comment by Kr328** [comment]
@LeslieLee0420 打开日志 检查你的规则如何控制 Google 的流量

**Comment by LeslieLee0420** [comment]
> @LeslieLee0420 打开日志 检查你的规则如何控制 Google 的流量

重新测试开日志看了之后，当我设置里选用全代理或者白名单模式勾选play商店的话，会走代理，而用黑名单不勾选play商店的话就不走代理，连接不上。其他谷歌系应用正常，只有play商店一个app这样。是我clash节点转换的规则有问题吗？

**Comment by Kr328** [comment]
@LeslieLee0420 系统问题

**Comment by LeslieLee0420** [comment]
> @LeslieLee0420 系统问题

感谢开发者。

**Comment by chenweiyu** [comment]
国行三星是有这个问题，我也是间歇性谷歌系app不能联网

**Comment by poemsiu** [comment]
分应用代理要把play服务 谷歌框架 都代理上 如果还不行把bixby 服务/service也代理了

**Comment by taken7** [comment]
同样是国行s10，已放弃分应用代理，否则谷歌系的play，YouTube，云端控制台等等app都连不上。

**Comment by Quzard** [comment]
我也这样。黑名单有问题  华为

**Comment by TiAmo-chen** [comment]
在名典里把Android系统加上就可以了  我的是这么解决的

**Comment by wk989898** [comment]
分应用代理中搜索`time`将他们全部设为代理(中文版好像可以不加) 应该可以解决问题

**Comment by ds119** [comment]
一样的问题，一加手机，不能让谷歌框架走代理，商店，服务要走代理

**Comment by fangsss6** [comment]
华为，一样的问题。

**Comment by OrangeGeeker** [comment]
> 华为，一样的问题。

我的情况，EMUI11，【Android 系统】，【系统服务】这俩勾上，就可以用了

**Comment by pc10201** [comment]
添加这个规则就可以了
  - DOMAIN,services.googleapis.cn,PROXY

**Comment by Bingmang** [comment]
一加 8T，遇到同样的问题，上面的方法都试了一遍，不管用。我的解决办法是：关掉clash，用shadowsocks连一下，打开Play商店和YouTube后，再关掉用clash，就没问题了，很迷 😂

**Comment by xuhaoyang** [comment]
@Bingmang 手持8t 没有你这个问题

**Comment by yan2035** [comment]
> 添加这个规则就可以了
> 
> * DOMAIN,services.googleapis.cn,PROXY

怎么添加

**Comment by tony1016** [comment]
我在Pixel上，白名单模式，是要将服务框架也代理上youtube就正常了

**Comment by bbly0413** [comment]
我是三星s21u，我也发现了有这个问题，但是我刚刚在研究的时候发现，应用列表左上角，有显示系统应用的选项，只要把Google搜索结果全部勾选上，就能连上Google服务以及YouTube了🙏

**Comment by xbbccx** [comment]
我之前也遇到同样的问题，原因是设置白名单的时候系统应用被过滤了，需要在选择app页面，点开右上角的选项，在”过滤“选项中，把系统选项释放出来，就可以勾选系统项进行代理了，然后就能看到很多谷歌服务出现在列表里，把这些勾选上，就可以解决谷歌paly和youtube不能代理的问题了。

**Comment by Nie2048** [comment]
解决方法：将包含gvt1.com的地址设置为proxy即可。

问题解决描述：通过clsah的日志捕捉功能，查看到通过play商店下载app时会访问rr1---sn-oguesn6k.gvt1.com，rr2---sn-oguelnlz.gvt1.com等网址，因此将包含gvt1.com的地址设置为proxy。   问题得到解决

机型：荣耀30s

**Comment by liaodongd** [comment]
一加手机参考解决方法：
打开clash-设置-网络  
1、修改访问控制模式（仅允许已选择的应用）
2、修改访问控制应用包列表-右上角三个点-过滤-取消勾选系统应用，然后在列表里勾选上所有google相关的服务、Android系统、一加系统服务

**Comment by liaodongd** [comment]
一加手机参考解决方法：
打开clash-设置-网络  
1、修改访问控制模式（仅允许已选择的应用）
2、修改访问控制应用包列表-右上角三个点-过滤-取消勾选系统应用，然后在列表里勾选上所有google相关的服务、Android系统、一加系统服务

**Comment by wbdhr** [comment]
我是三星S23U（备用机） 昨晚遇到了连接家里的网络的时候 可以打开YouTube 但是不能观看的情况 其他需要扶墙条件的APP都工作一切正常 唯独youtube可以打开 刷新很慢 但是就是不能看一直转圈圈  注：家中软路由用的是OPEN CLASH 可是切换到5G挂CLASH就可以正常使用和观看 但是在苹果手机的时候工作一切正常 逻辑上应该是网络设置问题，准确的说是open clash设置的问题 如果不能用就都不能用 不可能一个可以 另一个不可以的情况 打开openclash后就在 fake-ip和redir-host两个模式下相互切换测试 我一直用的是fake-ip模式  后来发现fake-IP模式下 我打开的是增强，改成混合模式就一切OK了 现在所有手机上需要扶墙的APP都是正常使用的  希望能帮到大家！
