### ISSUE TITLE
[Feature Request] bug太多了还不修复吗

### ISSUE THREAD

**Issue by luodehua321** [Kr328/ClashForAndroid#1134]
时不时不能开启服务。
时不时登录不上google play
现在不能看推特详情页。。
这到底是“我的问题还是app的问题

**Comment by movitecc** [comment]
发问前看一看提问的智慧，线路有没有问题？推对一些IP有限制，更换ip后尝试刷新；登录不上Google play，Google一下看看解决办法，是不是系统问题？您的问题还是app的问题---99%是您的问题
