### ISSUE TITLE
[BUG] 手机同时运行clash与抓包工具后代理冲突问题

### ISSUE THREAD

**Issue by YFTX2015** [Kr328/ClashForAndroid#1135]
**描述出现的错误**
请简洁的描述你遇到的错误
同时运行cfa与httpcanary造成手机唯一的vpn通道被占用，导致代理冲突，必然强制使一边断开连接，从而抓包中断。
**如何复现该错误**
复现步骤:
1. ...运行cfa并选择全局模式，开启泰国节点。此时手机顶端出现vpn图标，查看vpn状态，按钮已打开。
2. ...运行哔哩哔哩泰国版app，点开其中一部番剧播放。
3. ...打开小黄鸟进行抓包，几秒后播放中断，开始缓冲，此时查看手机vpn状态，发现按钮已关闭，确认cfa代理中断。
4. ...检查抓包数据，不再继续抓包，确认中断。

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
抓包数据流畅不中断。
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![QQ图片20210807000059](https://user-images.githubusercontent.com/12757305/128538916-f38d70d7-2e3a-4831-bc98-29c65c0cc4cc.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米11青春版
 - 系统/ROM: MIUI 12
 - Android 版本 11
 - ROM版本12.5.3

**应用信息**
 - 版本: 2.4.9.premium
 - 
 - 安装包文件名: app-premium--universal-release.apk
 - 应用来源: github release

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
那不然呢

**Comment by YFTX2015** [comment]
谷歌要是能给我解决我早就去找了，也不得专门跑过来问你了

**Comment by Kr328** [comment]
@YFTX2015 那你认为我一个应用还能改变系统行为不成？

**Comment by YFTX2015** [comment]
我是不晓得你有没得那个本事，毕竟我不是搞这个的，我到这儿是来问你有没得解决办法，你要是觉得只有改变系统才能解决问题那我也没必要在你这儿浪费时间了
