### ISSUE TITLE
[BUG] 2.4.9创建访问控制应用列表无法读取到小米自带浏览器

### ISSUE THREAD

**Issue by fangweilong** [Kr328/ClashForAndroid#1143]
**描述出现的错误**
2.4.9创建访问控制应用列表无法读取到小米自带浏览器，导致无法添加

**如何复现该错误**
复现步骤:
1. 设置
2. 网络
3. 访问控制应用包列表表

**预期行为**
勾选小米自带的浏览器。包名为：com.android.browser

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 小米11
 - 系统/ROM: miui12.5
 - Android 版本 11
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: 2.4.9
 - 安装包文件名: com.github.kr328.clash
 - 应用来源: github
**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
#971
