### ISSUE TITLE
[BUG] 2.4.9导入dler的规则报错，提示rule set是不支持的类型

### ISSUE THREAD

**Issue by spartawhy117** [Kr328/ClashForAndroid#1155]
**描述出现的错误**
我切换到2.3.22版本后同样的规则就能解析，不知道是软件的bug还是规则文件的问题

**Comment by AkariiinMKII** [comment]
@spartawhy117 premium版 请

**Comment by spartawhy117** [comment]
> remium版 请

意思是dler必须要开高级版？

**Comment by NevadaCities** [comment]
@spartawhy117 RULE-SET即Rule Provider是Clash Premium内核才有的功能，你可以安装 .premium 后缀的安装包

**Comment by spartawhy117** [comment]
> @spartawhy117 RULE-SET即Rule Provider是Clash Premium内核才有的功能，你可以安装 .premium 后缀的安装包

ok, 谢谢了
