### ISSUE TITLE
[BUG] MIUI最新版，配置导入无法选择无法保存配置，无法选择，逻辑搞不清楚。

### ISSUE THREAD

**Issue by iseeyou** [Kr328/ClashForAndroid#1157]
**描述出现的错误**
MIUI最新版，配置导入无法选择无法保存配置
请看视频，根本无法选择配置导入
奶牛：https://cowtransfer.com/s/8080948a085f4e
取件码：929044

**如何复现该错误**
复现步骤:
1. ...配置
2. ...点击 +
3. 从文件导入

**预期行为**
请看视频，搞的太晕了。

**屏幕截图**

**设备信息 (请完成以下信息):**
 - 机型: mix4
 - 系统/ROM: MIUI 12
 - Android 11
 - ROM版本 11

**应用信息**
 - 版本: 最新版本
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源:  Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
1. 填完 配置 日志 具体版本
2. 录屏直接拖动到输入框 不要用网盘
