### ISSUE TITLE
[Feature Request]增加协议支持

### ISSUE THREAD

**Issue by Happiness-in-Danger** [Kr328/ClashForAndroid#1162]
**功能描述**
希望可以增加对协议vless的支持

**描述你希望的实现方式**
在导入射手.ymal文件对vless的支持

**附加信息**
其他的与改功能相关的附加信息

**Comment by EKyero** [comment]
@Happiness-in-Danger https://github.com/Dreamacro/clash/pull/946
等上游合并pr，你这这里发没用

**Comment by akw5454521** [comment]
可以先用gRPC解馋
