### ISSUE TITLE
[BUG] 同链接订阅的trojan启动后无法连网

### ISSUE THREAD

**Issue by clincy123** [Kr328/ClashForAndroid#1165]
**Describe the bug**
同链接下的v2ray可以正常使用，联网谷歌等.trojan类型的节点无法联网，微信都无法连

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: [e.g. Pixel 4]红米k30pro
 - ROM: [e.g: AOSP]miui12.5
 - ROM Version:
 - Android Version [e.g. 10]安卓11

**Application Info (please complete the following information):**

 - Version: [e.g. 1.1.10]2.4.9prem版本
 - Apk File Name: [e.g. app-release-arm64-v8a.apk]
 - Distribution Channel: [e.g. Google Play]github

**Additional context**

**Configure**
Paste configure file which **removed server info** 
```yaml
# paste here
```

**Logs**
Paste logs to help detect problem
# Capture on 2021-09-02 14:43:20.822
14:43:20.824    Info: [APP] Logcat level: info
14:43:22.766    Info: [TCP] 127.0.0.1:44320 --> alive.github.com match DomainSuffix(github.com) using 馃敯 鑺傜偣閫夋嫨[馃嚡馃嚨 IEPL路鏃ユ湰JP路62路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:23.605    Info: [TCP] 127.0.0.1:44328 --> alive.github.com match DomainSuffix(github.com) using 馃敯 鑺傜偣閫夋嫨[馃嚡馃嚨 IEPL路鏃ユ湰JP路62路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.288    Info: [TCP] 127.0.0.1:44334 --> www.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚡馃嚨 IEPL路鏃ユ湰JP路62路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.292    Info: [TCP] 127.0.0.1:44340 --> optimizationguide-pa.googleapis.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚡馃嚨 IEPL路鏃ユ湰JP路62路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.292    Info: [TCP] 127.0.0.1:44332 --> www.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚡馃嚨 IEPL路鏃ユ湰JP路62路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.299    Info: [TCP] 127.0.0.1:44342 --> donate.kr328.app match Match() using 馃悷 婕忕綉涔嬮奔[馃嚡馃嚨 IEPL路鏃ユ湰JP路62路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.320    Info: [TCP] 127.0.0.1:44346 --> donate.kr328.app match Match() using 馃悷 婕忕綉涔嬮奔[馃嚡馃嚨 IEPL路鏃ユ湰JP路62路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.668    Info: [TCP] 127.0.0.1:44352 --> optimizationguide-pa.googleapis.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.668    Info: [TCP] 127.0.0.1:44354 --> www.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.668    Info: [TCP] 127.0.0.1:44356 --> www.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.668    Info: [TCP] 127.0.0.1:44360 --> donate.kr328.app match Match() using 馃悷 婕忕綉涔嬮奔[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:29.682    Info: [TCP] 127.0.0.1:44358 --> donate.kr328.app match Match() using 馃悷 婕忕綉涔嬮奔[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:31.982    Info: [TCP] 127.0.0.1:44372 --> clientservices.googleapis.com match Domain(clientservices.googleapis.com) using 馃幆 鍏ㄧ悆鐩磋繛[DIRECT]
14:43:32.562    Info: [TCP] 127.0.0.1:44376 --> www.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:32.564    Info: [TCP] 127.0.0.1:44380 --> www.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:32.663    Info: [TCP] 127.0.0.1:44386 --> alive.github.com match DomainSuffix(github.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:35.284    Info: [TCP] 127.0.0.1:44390 --> clientservices.googleapis.com match Domain(clientservices.googleapis.com) using 馃幆 鍏ㄧ悆鐩磋繛[DIRECT]
14:43:46.989    Info: [TCP] 172.19.0.1:47586 --> 149.154.175.54 match IPCIDR(149.154.160.0/20) using 馃摬 鐢垫姤淇℃伅[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:43:47.673    Info: [TCP] 127.0.0.1:44402 --> diagnosis.ad.xiaomi.com match DomainSuffix(ad.xiaomi.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:43:47.952    Info: [TCP] 172.19.0.1:47590 --> 149.154.175.54 match IPCIDR(149.154.160.0/20) using 馃摬 鐢垫姤淇℃伅[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:01.244    Info: [TCP] 127.0.0.1:44404 --> github.com match DomainSuffix(github.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:01.385    Info: [TCP] 127.0.0.1:44408 --> api.github.com match DomainSuffix(github.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:15.101    Info: [TCP] 127.0.0.1:44412 --> optimizationguide-pa.googleapis.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:15.104    Info: [TCP] 127.0.0.1:44414 --> github.githubassets.com match Match() using 馃悷 婕忕綉涔嬮奔[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:16.925    Info: [TCP] 127.0.0.1:44420 --> github.githubassets.com match Match() using 馃悷 婕忕綉涔嬮奔[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:17.177    Info: [TCP] 127.0.0.1:44428 --> alive.github.com match DomainSuffix(github.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:17.296    Info: [TCP] 127.0.0.1:44432 --> avatars.githubusercontent.com match DomainSuffix(githubusercontent.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:17.332    Info: [TCP] 127.0.0.1:44442 --> avatars.githubusercontent.com match DomainSuffix(githubusercontent.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:17.338    Info: [TCP] 127.0.0.1:44434 --> avatars.githubusercontent.com match DomainSuffix(githubusercontent.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:17.369    Info: [TCP] 127.0.0.1:44440 --> avatars.githubusercontent.com match DomainSuffix(githubusercontent.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:17.627    Info: [TCP] 127.0.0.1:44448 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:44:17.636    Info: [TCP] 127.0.0.1:44450 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:44:17.638    Info: [TCP] 127.0.0.1:44452 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:44:17.646    Info: [TCP] 127.0.0.1:44454 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:44:17.925    Info: [TCP] 127.0.0.1:44422 --> avatars.githubusercontent.com match DomainSuffix(githubusercontent.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:17.966    Info: [TCP] 127.0.0.1:44456 --> play-fe.googleapis.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:28.047    Info: [TCP] 127.0.0.1:44460 --> clients4.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:28.165    Info: [TCP] 127.0.0.1:44464 --> api.ad.xiaomi.com match DomainSuffix(ad.xiaomi.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:44:32.646    Info: [TCP] 127.0.0.1:44466 --> www.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:33.686    Info: [TCP] 127.0.0.1:44468 --> www.google.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:44:48.666    Info: [TCP] 127.0.0.1:44474 --> tracking.miui.com match DomainSuffix(tracking.miui.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:44:48.755    Info: [TCP] 172.19.0.1:48448 --> tracking.miui.com match DomainSuffix(tracking.miui.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:44:48.766    Info: [TCP] 172.19.0.1:40704 --> tracking.miui.com match DomainSuffix(tracking.miui.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:44:56.005    Info: [TCP] 127.0.0.1:44480 --> content-autofill.googleapis.com match DomainKeyword(google) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:45:04.474    Info: [TCP] 127.0.0.1:44488 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:04.480    Info: [TCP] 127.0.0.1:44492 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:04.481    Info: [TCP] 127.0.0.1:44490 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:04.487    Info: [TCP] 127.0.0.1:44494 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:05.023    Info: [TCP] 127.0.0.1:44484 --> alive.github.com match DomainSuffix(github.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:45:10.563    Info: [TCP] 127.0.0.1:44496 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:10.652    Info: [TCP] 172.19.0.1:40298 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:10.660    Info: [TCP] 172.19.0.1:38930 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:10.667    Info: [TCP] 172.19.0.1:41458 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:18.775    Info: [TCP] 127.0.0.1:44520 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:18.781    Info: [TCP] 127.0.0.1:44524 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:18.782    Info: [TCP] 127.0.0.1:44522 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:18.790    Info: [TCP] 127.0.0.1:44526 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:20.986    Info: [TCP] 127.0.0.1:44504 --> github.githubassets.com match Match() using 馃悷 婕忕綉涔嬮奔[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:45:22.017    Info: [TCP] 127.0.0.1:44532 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:22.023    Info: [TCP] 127.0.0.1:44534 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:22.024    Info: [TCP] 127.0.0.1:44536 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:22.028    Info: [TCP] 127.0.0.1:44538 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:24.331    Info: [TCP] 127.0.0.1:44510 --> avatars.githubusercontent.com match DomainSuffix(githubusercontent.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:45:24.335    Info: [TCP] 127.0.0.1:44508 --> github.githubassets.com match Match() using 馃悷 婕忕綉涔嬮奔[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:45:24.341    Info: [TCP] 127.0.0.1:44516 --> alive.github.com match DomainSuffix(github.com) using 馃敯 鑺傜偣閫夋嫨[馃嚟馃嚢 IEPL路棣欐腐HK路D183路绌洪棽路2x路IEPL涓撶嚎路1000M]
14:45:24.902    Info: [TCP] 127.0.0.1:44548 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃 鍏ㄧ悆鎷︽埅[REJECT]
14:45:24.908    Info: [TCP] 127.0.0.1:44550 --> collector.githubapp.com match DomainSuffix(collector.githubapp.com) using 馃洃
```
<paste here>
```

**Comment by Kr328** [comment]
反馈上游请
