### ISSUE TITLE
[BUG] 长链接时间长之后不通

### ISSUE THREAD

**Issue by alexlee728** [Kr328/ClashForAndroid#1166]
**描述出现的错误**
长链接时间长了之后会出现不发送数据问题。例如：将FCM的域名走了代理后，明明显示是连接成功状态，但是搜不到推送，关闭代理重新打开，让FCM重新连接就立马收到推送。
看到一段Core修改，不知道和这个是否有关系：
![image](https://user-images.githubusercontent.com/3183748/131947313-6eb093fa-4ce8-4014-8437-592cd97c5ea0.png)

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Mate 40 Pro
 - 系统/ROM: Harmony OS 2
 - Android 版本 10
 - ROM版本 2.0.0.165

**应用信息**
 - 版本: 2.4.9.foss
 - 安装包文件名: app-foss-arm64-v8a-release.apk
 - 应用来源: GitHub

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
日志配置请
