### ISSUE TITLE
[Feature Request] 增加下载上传速度测试

### ISSUE THREAD

**Issue by MIAIONE** [Kr328/ClashForAndroid#1169]
**功能描述**
希望可以像v2rayN电脑上测速一样
**描述你希望的实现方式**
虽然有的节点延时900ms、1600ms，但是速度却能达到7MB/s，希望调整排序策略，先测ping和tcp连接，然后从小到大在测速，这样可以兼得速度和延时，另外在后台设置一个watchdog，定时连接当前地区封锁的网站，如果连接不了自动切到下一个可以用的优质节点

**附加信息**
最好是手机版和电脑版都增加，如果有必要，可以在电脑上更新tap驱动实现全局代理（all socket，include 底层传输的数据的应用，比如 游戏、非http应用）

**Comment by Kr328** [comment]
反馈上游请
