### ISSUE TITLE
[BUG] 经常出现链接报错

### ISSUE THREAD

**Issue by FAST0888** [Kr328/ClashForAndroid#1173]
![photo_2021-09-11_01-03-31](https://user-images.githubusercontent.com/60876405/132890914-ab104e99-984e-41f8-bb4d-64d312f8952e.jpg)

**描述出现的错误**
[请简洁的描述你遇到的错误]([url]

**如何复现该错误**
复现步骤:
1. ...
2. ...![photo_2021-09-11_01-03-31](https://user-images.githubusercontent.com/60876405/132890914-ab104e99-984e-41f8-bb4d-64d312f8952e.jpg)3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4A]
 - Android 版本 [例如: 11]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by xuhaoyang** [comment]
@FAST0888 不如查查你的节点问题

**Comment by FAST0888** [comment]
> @FAST0888 不如查查你的节点问题

直连呀……

**Comment by Kr328** [comment]
这个我管不了 系统返回一个连接失败 我能怎么办呢
