### ISSUE TITLE
1.1.0导致gcm不断重连

### ISSUE THREAD

**Issue by poemsiu** [Kr328/ClashForAndroid#118]
使用1.1.0新版本会导致gcm每隔600s或900重连，导致gcm推送通知（比如telegram）延迟很久以及耗电。
换用play商店的旧版后恢复正常，可持续连接几小时不出现重连。
使用的配置文件都是一模一样的。

**Comment by Forty-nine** [comment]
你可以试试

`  - DOMAIN,mtalk.google.com,DIRECT` 

是否可以

**Comment by Love4Taylor** [comment]
建议 `- DOMAIN-KEYWORD,mtalk.google.com,DIRECT`

**Comment by poemsiu** [comment]
> 建议 `- DOMAIN-KEYWORD,mtalk.google.com,DIRECT`

经尝试，添加此规则后问题无改善，但在关闭ipv6支持后恢复正常，也许是我开了ipv6支持的缘故？

**Comment by poemsiu** [comment]
> 建议 `- DOMAIN-KEYWORD,mtalk.google.com,DIRECT`

https://github.com/Kr328/ClashForAndroid/issues/118#issuecomment-589900858

**Comment by poemsiu** [comment]
> 你可以试试
> 
> ` - DOMAIN,mtalk.google.com,DIRECT`
> 
> 是否可以

https://github.com/Kr328/ClashForAndroid/issues/118#issuecomment-589900858

**Comment by TheAutomatic** [comment]
请问负责推送的是哪个应用？我怀疑我的推送进程被手机系统杀掉了

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
