### ISSUE TITLE
[Feature Request] Add some possibility to custom the rules in profiles

### ISSUE THREAD

**Issue by lcdlyxrqy** [Kr328/ClashForAndroid#1180]
**Is your feature request related to a problem? Please describe.**
Sometimes the profile downloaded from URLs doesn't work well because of outdated rules, causing some websites unable to be visited properly. However I don't find a way to modify the rules without being reversed by every update.

**Describe the solution you'd like**
Provide something to custom the rules a little bit. Something like the parsers or the profile mixin in the Clash for Windows app is good. Perhaps provide this feature in settings - override?

**Comment by EKyero** [comment]
You need [subconverter](https://github.com/tindy2013/subconverter) and [termux](https://f-droid.org/packages/com.termux/) .
