### ISSUE TITLE
[BUG] App时不时测定全部节点的延迟；另外日志中出现的连接目标IP为节点IP

### ISSUE THREAD

**Issue by akw5454521** [Kr328/ClashForAndroid#1181]
**描述出现的错误**
之前用的是很老版本的CFA，升级到了最新版，发现开启代理后，App会马上测试所有节点的延迟，之前是只会测包含于url-test和load-balance这种group里的节点，但现在是测所有节点了，感觉并无此必要。以及，之前是只有在启动代理或者切换网络的情况下才会测，现在并不是这样了，为了观察我专门把interval设得特别长，并且保持网络始终为移动数据连接，发现App在不到一个小时后就重新测了(所有节点的)延迟，虽然测了也没什么损失，但是有增加耗电的可能，而且也不是core的预期特性。为了发现问题是哪个版本出现的，我专门一个版本一个版本的往前测试，发现是2.4.8开始这样的，也就是说2.4.7以及之前的版本都是一样的，不会测所有节点。我专门看了下2.4.8的release note，未发现相关说明，同时期core的更新note也没有相关项，同期core在其他平台的Clash也不会测所有节点的延迟，所以应该是CFA的问题

**如何复现该错误**
复现步骤:
1. 打开CFA并开启代理
2. 每过一会儿观察下节点页面

**预期行为**
只有在url-test和load-balance组里的节点才会按照interval时间来测延迟

**屏幕截图**
暂无

**设备信息 (请完成以下信息):**
 - 机型: [三星S10]
 - 系统/ROM: [One UI]
 - Android 版本 [9]
 - ROM版本 [1.1]

**应用信息**
 - 版本: [2.4.9.foss]
 - 安装包文件名: [app-foss-arm64-v8a-release.apk]
 - 应用来源: [GitHub]

**附加信息**
无

**配置文件**

<details>
<summary>Config</summary>

port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
ipv6: false
external-controller: '0.0.0.0:9090'
secret: ''

dns:
  enable: false (覆写中改为强制启用，相当于true)
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 1.2.4.8
    - 114.114.114.114
    - 223.5.5.5

</details>

**日志**
因为测延迟不涉及日志，所以上边的问题就不贴日志了，但是2.4.9版本使用中发现了日志里有奇怪的内容，就是标题中的后半句问题，因此贴出日志请大佬看看

<details>
<summary>Log</summary>

20:30:10.932    Info: HTTP proxy listening at: :7890
20:30:10.933    Info: SOCKS5 proxy listening at: :7891
20:30:10.934   Error: Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied
20:30:10.935    Info: Patch selector Proxy -> BWG
20:30:10.963    Info: [ATUN] Device tx started
20:30:10.964    Info: [ATUN] UDP receiver started
20:30:10.964    Info: [ATUN] TCP listener started
20:30:10.965    Info: [ATUN] Device rx started
20:30:11.222    Info: [UDP] 172.19.0.1:16745 --> 123.123.123.123 match GeoIP(CN) using DIRECT
20:30:13.737    Info: [TCP] 172.19.0.1:34670 --> 149.154.175.55 match IPCIDR(149.154.160.0/20) using Proxy[BWG]
20:30:14.002    Info: [TCP] 10.236.51.233:53074 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:14.010    Info: [TCP] 10.236.51.233:53070 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:14.015    Info: [TCP] 10.236.51.233:38962 --> a.b.c.d match Match() using Gotcha[BWG]
20:30:14.016    Info: [TCP] 10.236.51.233:38954 --> a.b.c.d match Match() using Gotcha[BWG]
20:30:14.016    Info: [TCP] 10.236.51.233:38946 --> a.b.c.d match Match() using Gotcha[BWG]
20:30:14.027    Info: [TCP] 10.236.51.233:53090 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:14.028    Info: [TCP] 10.236.51.233:40438 --> e.f.g.h match Match() using Gotcha[BWG]
20:30:14.437    Info: [TCP] 10.236.51.233:38958 --> a.b.c.d match Match() using Gotcha[BWG]
20:30:15.039    Info: [TCP] 172.19.0.1:54940 --> mobile.twitter.com match DomainKeyword(twitter) using Proxy[BWG]
20:30:15.105    Info: [TCP] 10.236.51.233:53100 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:15.106    Info: [TCP] 10.236.51.233:53098 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:15.108    Info: [TCP] 10.236.51.233:48650 --> i.j.k.l match Match() using Gotcha[BWG]
20:30:15.108    Info: [TCP] 10.236.51.233:38960 --> a.b.c.d match Match() using Gotcha[BWG]
20:30:15.129    Info: [TCP] 10.236.51.233:53096 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:15.130    Info: [TCP] 10.236.51.233:53086 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:15.131    Info: [TCP] 10.236.51.233:53072 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:15.133    Info: [TCP] 10.236.51.233:53088 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:15.133    Info: [TCP] 10.236.51.233:53094 --> 1.1.1.1 match Match() using Gotcha[BWG]
20:30:15.137    Info: [TCP] 10.236.51.233:38956 --> a.b.c.d match Match() using Gotcha[BWG]
20:30:15.228    Info: [TCP] 172.19.0.1:48644 --> video.twimg.com match DomainSuffix(twimg.com) using Proxy[BWG]
20:30:15.231    Info: [TCP] 172.19.0.1:60830 --> abs.twimg.com match DomainSuffix(twimg.com) using Proxy[BWG]
20:30:15.239    Info: [TCP] 172.19.0.1:52644 --> api.twitter.com match DomainKeyword(twitter) using Proxy[BWG]

</details>

这里出现了我从没见过的内容，那些10.236发起的连接，目标要么是1.1.1.1，要么是我配置文件中节点的IP(已替换为字母)，感觉很奇怪，我DNS里也没有1.1.1.1，不知道日志中为何要(通过代理)访问它，以及为何要(通过代理)访问我的节点？这个行为跟我上边提的测延迟的问题不会有关系吧

**Comment by Kr328** [comment]
1. 重测发生在网络变更 更准确的说是 **重新载入配置** 因为这样能在切换网络后迅速找到适合新网络的节点 不过下版本会改变这个逻辑
2. 那个 10/8 的地址 不是 cfa 的 tun 的地址 也不知道是什么的地址 自己检查设备网络
