### ISSUE TITLE
[BUG] 在布局中，多列 无法显示节点的全部名称，单列 没有问题。

### ISSUE THREAD

**Issue by hans822418** [Kr328/ClashForAndroid#1185]
![QQ图片20210912234649](https://user-images.githubusercontent.com/67779256/132994178-4f2c0914-08db-4e9d-8596-0bbf4ed245c3.jpg)
![QQ图片20210912234654](https://user-images.githubusercontent.com/67779256/132994184-50516365-6984-4613-ab44-eedc35d77f9b.jpg)

**Comment by hans822418** [comment]
好几个版本一直都有这样的问题

**Comment by Kr328** [comment]
不然为什么要区分多列单列
