### ISSUE TITLE
[Feature Request]  添加切换Clash开关的【快捷方式】以便支持自动化

### ISSUE THREAD

**Issue by kenvix** [Kr328/ClashForAndroid#1194]
**功能描述**          
我需要在某个特定事件发生时，由 MacroAndroid 或 Tasker 自动控制 Clash 的开关。          
目前，实现自动化开关的效果只能通过 Shell 模拟执行通知栏快捷设置磁贴：
```
cmd statusbar click-tile com.github.kr328.clash/.TileService
```
这样不仅使用不便，而且需要 root 权限，还和代码强耦合。          
如果能像 Shadowsocks 那样增加【快捷方式】，则可以很方便地自动化切换 Clash 的开关

**描述你希望的实现方式**            
对应的 Android 开发文档 [应该是这篇](https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts?hl=zh-cn)     
实现一个和通知栏快捷设置磁贴类似的切换开关【快捷方式】即可

**附加信息**          
Shadowsocks 的实现：
![image](https://user-images.githubusercontent.com/4546175/133249403-ccb51a85-8632-4ac2-a80a-56151ebe6846.png)

**Comment by EKyero** [comment]
https://github.com/Kr328/ClashForAndroid/issues/326

**Comment by zyc63959** [comment]
一年里面有10多个此类请求被关闭

**Comment by zyc63959** [comment]
这个命令不需要root，是未来2年能用的唯一方法

**Comment by malagebidi** [comment]
`cmd statusbar click-tile com.github.kr328.clash/.TileService`
这个命名我测试是需要root，后来就改用AutoInput来点击了

**Comment by xdtxAM** [comment]
为什么不适用v2ray是支持安卓小部件的
