### ISSUE TITLE
自动断开连接

### ISSUE THREAD

**Issue by YunTKo0** [Kr328/ClashForAndroid#120]
目前还不能准确判断是否是因为WiFi切换移动数据,或是切换另一个WiFi连接时导致断开.
断开后无法再次连接成功(点击start提示:Clash Start Failure  启动失败),需手动停止Clash
![photo_2020-02-21_14-27-33](https://user-images.githubusercontent.com/45587919/75009761-64ca9300-54b6-11ea-9839-3472d88944ba.jpg)

进程,后重新进行连接,
手机系统:荣耀V10 EMUI Android 10

**Comment by Kr328** [comment]
@YunTKo0 你的 DHCP 会分配 IPv6 的 DNS ?

**Comment by YunTKo0** [comment]
1.1.2版本已经修复…👍多谢大佬，辛苦了

Kr328 <notifications@github.com> 于 2020年2月21日周五 14:37写道：
