### ISSUE TITLE
[Feature Request] can modify let support "kotlin multiplatform"

### ISSUE THREAD

**Issue by CMingTseng** [Kr328/ClashForAndroid#1207]
**Is your feature request related to a problem? Please describe.**
Dear Sir

can modify let all module support "kotlin multiplatform"

commonMain/androidMain/desktopMain / iosMain/jsMain

THX

**Describe the solution you'd like**
"kotlin multiplatform"  can support multiplatform 

can let library module support  multiplatform ? 

let  kotlin mix go ?

**Comment by Kr328** [comment]
nope

it should be a new project not just "modify"
