### ISSUE TITLE
Load profile failure报错

### ISSUE THREAD

**Issue by satrom** [Kr328/ClashForAndroid#121]
使用过程中，会出现已选择了配置文件，打开Clash报错 Load profile failure

**Comment by Kr328** [comment]
你的 DHCP 会分配 IPv6 的 DNS ?

**Comment by satrom** [comment]
不会分配，不过新版这问题还没出现

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
