### ISSUE TITLE
[BUG] 关闭wifi和移动数据后，软件中配置文件设置的定时自动更新依然会执行。

### ISSUE THREAD

**Issue by fangxingweiai** [Kr328/ClashForAndroid#1212]
**描述出现的错误**
关闭wifi和移动数据后，软件中配置文件设置的定时自动更新依然会执行。

**如何复现该错误**
复现步骤:
1. 设置配置文件自动更新时间间隔。
2. 关闭wifi和移动数据，等待触发更新操作。

**预期行为**
关闭wifi和移动数据后，不再执行定时更新操作。

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 魅蓝 note5
 - 系统/ROM: Flyme
 - Android 版本: 7.0
 - ROM版本: 8.0.5.0A

**应用信息**
 - 版本: 2.4.13
 - 安装包文件名: cfa-2.4.13-foss-arm64-v8a-release.apk
 - 应用来源: github releases

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
是预期的
