### ISSUE TITLE
[Feature Request] 希望能添加快捷开关代理/切换代理规则等功能

### ISSUE THREAD

**Issue by PenguinCaptain** [Kr328/ClashForAndroid#1215]
**功能描述**
希望添加快捷方式进行vpn的开关，也希望可以通过通知栏进行快速的关闭vpn或切换节点

**描述你希望的实现方式**
使用Android的Shortcuts功能实现长按桌面图标进行交互，比如快速开启代理，或者切换代理规则
也建议对通知进行自定义交互，来实现无需进入应用即可开关代理

****以SSR安卓客户端为例****
快捷方式：
![bc7b193dca27c3409cf77ad27c8fa43](https://user-images.githubusercontent.com/35358684/135497578-da9e2f4b-ca63-4629-9e3b-69ad539b271a.jpg)
通知栏交互：
![43f6b61fb3845ab4370cb948db8ac9d](https://user-images.githubusercontent.com/35358684/135497549-68477c9b-03c6-4af7-abf7-6140c918ebed.jpg)

**Comment by Kr328** [comment]
#326
