### ISSUE TITLE
[Feature Request]  配合AdGuard使用，DNS Hijacking应该怎么选？

### ISSUE THREAD

**Issue by offferu** [Kr328/ClashForAndroid#1221]
**功能描述**
cfa和adguard搭配使用时，DNS Hijacking如何选？

**描述你希望的实现方式**
cfat选项中的DNS Hijacking该不该关掉（如Adguard能实现更好的去广告等）

**附加信息**
见附图

<img src="https://i.ibb.co/VpcqxQ2/Screenshot-20211004-214555936-1.png"></img>
<img src="https://i.ibb.co/9htK87M/Screenshot-20211004-214623966-1.png"></img>

**Comment by Kr328** [comment]
我不知道
