### ISSUE TITLE
[Feature Request] 软件非常简洁美观。希望添加 自动识别 从剪贴板复制的VMess开头的链接进行提示是否导入

### ISSUE THREAD

**Issue by Goog686ii** [Kr328/ClashForAndroid#1223]
**功能描述**
希望添加 自动识别 从剪贴板复制的VMess开头的链接进行提示是否导入

**描述你希望的实现方式**
希望添加 自动识别 从剪贴板复制的VMess开头的链接进行提示是否导入

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
那是其他应用的规范 

clash 只接受 clash 专有的配置文件
