### ISSUE TITLE
[Feature Request] 希望增加桌面小组件的功能

### ISSUE THREAD

**Issue by APushingBoy** [Kr328/ClashForAndroid#1226]
**功能描述**
现在的clash有通知栏开关，但有时候我还需要选择具体的节点，相比打开app，我希望可以提供桌面小组件的方式，直接选择节点

**描述你希望的实现方式**
在桌面小组件中，可以提供最简单的功能，比如切换规则模式或全局模式、选择节点

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/108
