### ISSUE TITLE
滚动动画需要优化

### ISSUE THREAD

**Issue by JAMLEEblr** [Kr328/ClashForAndroid#123]
1.切换分组时的滚动速度太慢，需要加速，或者借鉴Telegram转到最新消息的动画。
2.两种分组模式投票人数基本持平，可以考虑放到设置里，改成可切换的。
3.只要软件失焦，再打开软件就一定是主界面，有点不方便操作：比如出去复制一下订阅链接，回来就得重新操作，同时也不方便切换节点。

**Comment by JAMLEEblr** [comment]
更正 切换到多任务返回后不会回到主界面

**Comment by Kr328** [comment]
FIXED in 1.1.1
