### ISSUE TITLE
[Feature Request] 什么时候实现clashx pro中的enhanced mode？

### ISSUE THREAD

**Issue by dutry** [Kr328/ClashForAndroid#1233]
**功能描述**
clashx pro中实现enhanced mode，使得一些更底层的应用也可以翻墙。在安卓中也会出现一些底层需求无法实现，如共享wifi？

**描述你希望的实现方式**
走TUN

**Comment by EKyero** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1100
有时，应该先看看issues，这样就不用麻烦的打一大段字了，不是吗？
