### ISSUE TITLE
[Bug] 1.1.0 版部分界面元素无法在 TV 上使用遥控器选择

### ISSUE THREAD

**Issue by itspig** [Kr328/ClashForAndroid#124]
感谢作者辛苦编码，新版超级好用👍

有几个控件可否改进下，无法使用遥控器操作，改版前是可以的，目前有点不方便
包括

Profile 右侧按钮 -> 无法更新配置文件
Interface 所有选项的下拉菜单 -> 无法切换夜间模式和语言 
Logs 中 History 下的 log 右侧按钮 -> 无法查看删除日志

万分感谢 🙏

**Comment by Kr328** [comment]
#58
