### ISSUE TITLE
[Feature Request] 请问是否有通过应用包名分流的功能

### ISSUE THREAD

**Issue by 1219099256** [Kr328/ClashForAndroid#1245]
**功能描述**
通过应用包名分流

**描述你希望的实现方式**
在配置文件中填入包名选择规则

**附加信息**
刚刚开始接触clash，发现cfw可以通过进程名选择规则，想问一下cfa是否有类似的功能，也不算是功能请求，就是问问

**Comment by Kr328** [comment]
PROCESS-NAME 请

**Comment by akw5454521** [comment]
> PROCESS-NAME 请

大佬借楼问一下，当存在Process name规则时日志里会有相关的PKG项，如果没有这种规则的话日志里就没有PKG项，请问用这个规则会耗更多的资源和电池吗
