### ISSUE TITLE
clash可以使用acl4ssr的规则吗

### ISSUE THREAD

**Issue by bupt2017** [Kr328/ClashForAndroid#125]
实现不代理手机浏览器，但是却可以通过规则来进行代理国外网站，同时国内网站走直连
ssr安卓端maying有类似功能。电脑端switchomega也有类似功能。

开发大佬您好，这个功能不知道是否在考虑范围内。

**Comment by Kr328** [comment]
@bupt2017

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/75040029-e17c6200-54f4-11ea-8819-2e8775e94e0e.png)
顶部注释抄写一万遍

**Comment by LeslieLee0420** [comment]
可以用转换之后的订阅链接实现。下面是acl4ssr作者开发的，把你机场订阅链接放进去就可以一键转换规则了

Clash在线ACL4SSR规则订阅转换：https://acl4ssr.netlify.com
