### ISSUE TITLE
[Feature Request] 求添加开关external-controller

### ISSUE THREAD

**Issue by AoEiuV020** [Kr328/ClashForAndroid#1266]
**功能描述**
希望支持启动external-controller监听端口浏览器打开远程切换clash节点，

**描述你希望的实现方式**
开关默认关闭也好，可以在设置打开以便远程切换节点比较好，

**附加信息**
如果不打算支持的话是否有办法fork简单修改恢复external-controller的支持？
可以的话大概指个路我自己看也行，虽然不懂go lang，
我想在电视盒子上24小时挂着，想要能远程切换节点，

**Comment by Kr328** [comment]
cfa 不会提供这个功能 会有数据同步问题 

external-controller 直通 core 而 cfa 不能记录其中产生的变更
