### ISSUE TITLE
1.1.1版前缀合并括号识别强迫症瑕疵，及建议非合并时保留滚动

### ISSUE THREAD

**Issue by gang4399** [Kr328/ClashForAndroid#127]
如题；
如图：
![Screenshot_20200222020850](https://user-images.githubusercontent.com/28175410/75060073-162cf100-54d6-11ea-824e-47860c7d6972.jpg)

建议：保留非前缀合并状态下的滚动显示或双层展示，长名节点很难伺候

谢谢你将美丽进行到底！

**Comment by Kr328** [comment]
预期行为

**Comment by gang4399** [comment]
> 预期行为

请注意上面是新加坡实际是17 ，18，19嗷

**Comment by Kr328** [comment]
对呀 算法就这样啊 没错

**Comment by gang4399** [comment]
> 对呀 算法就这样啊 没错

怎么可能，18被断成（1 & 8）？ 然后8）显示到头部 （1 散落在原地 ？

**Comment by Kr328** [comment]
@gang4399 你告诉我这三个节点 从开头开始 相同前缀 有哪些
注意 18 不要看成整体 
计算机中 是 1 和 8

**Comment by gang4399** [comment]
> @gang4399 你告诉我这三个节点 从开头开始 相同前缀 有哪些
> 注意 18 不要看成整体
> 计算机中 是 1 和 8

明白了。接受这种的确科学的不美丽。

**Comment by gang4399** [comment]
> > @gang4399 你告诉我这三个节点 从开头开始 相同前缀 有哪些
> > 注意 18 不要看成整体
> > 计算机中 是 1 和 8
> 
> 明白了。接受这种的确科学的不美丽。

要能忽略括号就好。

**Comment by Kr328** [comment]
@gang4399 你这个节点这样 万一其他人的节点 括号是前缀怎么办

**Comment by gang4399** [comment]
> @gang4399 你这个节点这样 万一其他人的节点 括号是前缀怎么办

双括号识别，排除分-析-断。直接放最前。一般不是数字序列就是特别说明或是品牌名，不需断。遇到神坑，打机场主屁股。

**Comment by Kr328** [comment]
@gang4399 你这都快赶上 NLP 和 机器学习 了
一个代理应用完全没必要

**Comment by gang4399** [comment]
> @gang4399 你这都快赶上 NLP 和 机器学习 了
> 一个代理应用完全没必要

我觉得你说的对。我是强迫症冒泡，压得住，勿忧。TKS

**Comment by gang4399** [comment]
> **可我确实跟其他人一样认同这是一个美丽的代理应用。**

**Comment by Kr328** [comment]
@gang4399 算法就是这样的残酷 冰冷而无情

**Comment by gang4399** [comment]
> @gang4399 算法就是这样的残酷 冰冷而无情

👌晚上别光喝冰可乐。也别空腹喝咖啡。

**Comment by gang4399** [comment]
> @gang4399 你告诉我这三个节点 从开头开始 相同前缀 有哪些
> 注意 18 不要看成整体
> 计算机中 是 1 和 8

大佬，我忽略了。为啥我前后不一样呢，上面自动选择分组那前缀10-23又全部 切割对了的？ 到国家节点才是你说的 18 和17 只从8，7开始不同……
![Screenshot_20200222095310](https://user-images.githubusercontent.com/28175410/75084211-85c2d080-5516-11ea-8a73-83f838badaa9.jpg)

**Comment by Kr328** [comment]
@gang4399 每个组单独判定

**Comment by gang4399** [comment]
> @gang4399 每个组单独判定

判断逻辑是针对序列规则，跟Excel统计规则相似？这些节点名称完全一样的呢。

**Comment by Kr328** [comment]
@gang4399 https://github.com/Kr328/ClashForAndroid/blob/dev/app/src/main/java/com/github/kr328/clash/utils/PrefixMerger.kt

**Comment by gang4399** [comment]
> @gang4399 https://github.com/Kr328/ClashForAndroid/blob/dev/app/src/main/java/com/github/kr328/clash/utils/PrefixMerger.kt



> @gang4399 https://github.com/Kr328/ClashForAndroid/blob/dev/app/src/main/java/com/github/kr328/clash/utils/PrefixMerger.kt

看了。手动流下没有技术的泪水。
要会的话我会试着帮您码一些代码出来。不至于在这醒来又开始纠结呢😅
