### ISSUE TITLE
[BUG] 用了clash导致OneNote没法登录同步。

### ISSUE THREAD

**Issue by blacfff** [Kr328/ClashForAndroid#1270]
![Screenshot_20211107_104410](https://user-images.githubusercontent.com/68760101/140630409-399c92d8-b93a-48ed-8573-7817b1be250c.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
