### ISSUE TITLE
[Feature Request] 恳请增加tasker支持或者shortcut service

### ISSUE THREAD

**Issue by Christopher-Songs** [Kr328/ClashForAndroid#1271]
**功能描述**
恳请增加tasker的控制开关，看了一下issues，之前有人提过这个需求，但不知道出于什么原因被unplan了。
如果支持tasker工作量比较大，那么能不能增加一个shortcut service，这样也能通过tasker调用。感谢。

**描述你希望的实现方式**

**附加信息**

**Comment by Kr328** [comment]
#326

**Comment by zyc63959** [comment]
不需要，Tasker自带此功能
