### ISSUE TITLE
[BUG] Can't use on Twitter

### ISSUE THREAD

**Issue by xmha97** [Kr328/ClashForAndroid#1275]
Hi, i want to use Twitter with Clash proxy because Twitter blocked on my country.

# Twitter
![Screenshot_2021-11-11-08-04-08-383_com.twitter.android.jpg](https://user-images.githubusercontent.com/23485114/141237804-f84e0737-8b1d-425a-9979-464f26c798ed.jpg)

# Clash
![Screenshot_2021-11-11-08-05-44-384_com.github.kr328.clash.jpg](https://user-images.githubusercontent.com/23485114/141237842-5b9542d4-6f94-434d-a03a-13352f5f1e8a.jpg)

Why I can't use Twitter with Clash proxy?

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
