### ISSUE TITLE
[Feature Request] Support trojan over websocket

### ISSUE THREAD

**Issue by fr-guoqing** [Kr328/ClashForAndroid#1276]
**功能描述**
Clash v1.8.0 已经支持了 trojan + ws，麻烦 Clash for Android 能否也支持一下，感谢

**Comment by Kr328** [comment]
上游

**Comment by zhgqthomas** [comment]
上游最新的 clash core v1.8.0 已经支持了，是不是下一个版本 update clash core 之后就会同样会有此功能了?

**Comment by Kr328** [comment]
@zhgqthomas 是的

**Comment by alexlee728** [comment]
是不是快要更新了，😄

**Comment by Kr328** [comment]
@alexlee728 调整好 target 31 和 tun2socket 应该能下版本了
