### ISSUE TITLE
请问有没有客服，安卓手机出去了，但是查id还是中国，win电脑，重装系统后重新安装也用不了，麻烦安排个客服吧，谢谢了

### ISSUE THREAD

**Issue by HML18753410522** [Kr328/ClashForAndroid#1277]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by alexlee728** [comment]
如何查询IP的？你可以用https://www.ip138.com 试试

**Comment by HML18753410522** [comment]
总算找到有人回复了，谢谢，辛苦看下安卓和win的问提




win电脑无法导入，提示这个
















在 2021-11-12 10:39:04，"Alex Lee" ***@***.***> 写道：

如何查询IP的？你可以用https://www.ip138.com 试试

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EKyero** [comment]
![Screenshot_20211112-104941](https://user-images.githubusercontent.com/29628846/141400632-dbf01309-c017-4ad5-9cd0-b023e8f3e11c.jpg)
你找错地方了

**Comment by HML18753410522** [comment]
那我该找哪里呀，麻烦给我个联系方式，谢谢。







在 2021-11-12 10:50:12，"EKyero" ***@***.***> 写道：


你找错地方了

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kr328** [comment]
@HML18753410522 自己去找你的服务提供商 除了你自己没人知道你在哪里得到的服务

**Comment by liberal-boy** [comment]
这是 Android 应用，你用 windows 为啥来这问

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by yaott2020-666** [comment]
好心提醒一下，最好不要把手机号做用户名

**Comment by MarksonHon** [comment]
@yaott2020-666 你好，这里是中国国家安全局，建议您立即停止使用非法信道访问国际互联网的行为，否则可能被处以 3000 元的罚款以及 15 天的行政拘留。

**Comment by yaott2020-666** [comment]
@MarksonHon  请赶紧拘留我，我等不及了
