### ISSUE TITLE
[Feature Request] 希望能有手动添加域名/IP实现强制(直连/代理)的功能

### ISSUE THREAD

**Issue by aliveday** [Kr328/ClashForAndroid#1278]
**功能描述**
希望能像设置里覆写DNS那样，手动添加域名或IP来实现对所有订阅都生效的，针对指定网站的(强制直连/代理)功能。

**Comment by Kr328** [comment]
Clash 的 代理 代理组 规则 三个 相互绑定 

修改其内容可靠性太差 需要自己文本编辑

**Comment by EKyero** [comment]
@aliveday 有修改规则的需求建议用 rule-provider
或者用subconverter（需搭配termux）

**Comment by aliveday** [comment]
求教程，是要找到订阅下载的配置文件手动更改么，更新订阅是不是会覆盖掉啊。还是自己写规则导入到外部资源，优先级比配置文件高么。对于那些把“DIRECT”改成“全球直连”的订阅，像DOMAIN-SUFFIX,baidu.com,DIRECT这样默认格式是不是就不起作用了。我只搜到nitter.net/i/status/1439983755834187779 这个人提了一下，但是他的规则我导入用着没效果。麻烦你了。

**Comment by aliveday** [comment]
> @aliveday 有修改规则的需求建议用 rule-provider 或者用subconverter（需搭配termux）

谢谢，我去搜搜这俩是啥😅。

**Comment by Lucio-0408** [comment]
@EKyero 安卓端也可以使用吗？具体如何操作呢？
