### ISSUE TITLE
软件关闭问题

### ISSUE THREAD

**Issue by LeslieLee0420** [Kr328/ClashForAndroid#128]
从通知栏点击断开连接之后，软件并没有关闭，还要进软件点关闭。是点击通知栏关闭之后进入了旧版本的仅代理模式，而不是关闭吗？
![20200222_083830](https://user-images.githubusercontent.com/46532123/75082524-ee2da400-554e-11ea-9456-f909643da416.gif)

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/1.1.7
