### ISSUE TITLE
[BUG] 疑似内存泄露

### ISSUE THREAD

**Issue by GodHelios** [Kr328/ClashForAndroid#1281]
**描述出现的错误**
疑似内存泄露

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![Screenshot_20211119-192149_Scene4](https://user-images.githubusercontent.com/50237436/142615798-ad47f4a0-65b1-44e7-ae5a-a9fcc63c784c.png)
![Screenshot_20211119-192237_Clash for Android](https://user-images.githubusercontent.com/50237436/142615806-efcdacf8-5e45-4db0-aede-f775c0a5cf47.png)

**设备信息 (请完成以下信息):**
 - 机型: Xiaomi 10 Ultra (M2007J1SC)
 - 系统/ROM: Arrow OS
 - Android 版本 12
 - ROM版本 SD1A.210817.036.A8

**应用信息**
 - 版本: 
 - 安装包文件名: cfa-2.4.14-premium-arm64-v8a-release.apk
 - 应用来源: github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
