### ISSUE TITLE
[BUG] 2.5.2版如果一直后台开着，会过段时间就出现无法联网的情况

### ISSUE THREAD

**Issue by mpamxl** [Kr328/ClashForAndroid#1285]
Clash挂载后台后过一些时间（具体时间没算，大概一天之内甚至半天内），就会出现应用无法联网的问题，重新关闭Clash后再打开就正常了。上个版本都没这个问题。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
