### ISSUE TITLE
[Feature Request] 在配置页面增加每个配置的已用流量、总流量和剩余日期

### ISSUE THREAD

**Issue by Marukon** [Kr328/ClashForAndroid#1288]
**功能描述**
目前，Clash for Windows已经可以显示配置的已用流量、总流量和剩余日期：
![1](https://user-images.githubusercontent.com/6285343/142766554-58556f58-af55-436e-9c27-5cbdab496fae.png)
希望，在Clash for Android的配置界面中画圈部分，新增已用流量、总流量和剩余日期
![2](https://user-images.githubusercontent.com/6285343/142766647-5e98a933-fd21-45f1-ac1d-a101f10a9c5a.jpg)

**描述你希望的实现方式**
希望Clash for Android可以从配置文件的header中获取这些信息，并显示在配置页面

**附加信息**
其他的与改功能相关的附加信息
无

**Comment by shikkoku** [comment]
https://github.com/crossutility/Quantumult/blob/master/extra-subscription-feature.md

也许能做个资料参考。

**Comment by zhengzavan** [comment]
https://raw.githubusercontent.com/Peng-YM/QuanX/master/Tasks/flow.js
quanx获取剩余流量的方法，参考
@Kr328

**Comment by cyx7777** [comment]
为什么我CFW也没有显示？
