### ISSUE TITLE
[BUG] 从2.5.2版本开始狂野飙车9多人游戏无法连接服务器

### ISSUE THREAD

**Issue by chrisvorer6** [Kr328/ClashForAndroid#1289]
**描述出现的错误**
从2.5.2版本开始狂野飙车9国际版多人游戏无法连接服务器，无论是规则模式还是全局模式，版本恢复2.4.14一切正常
可以确认和订阅节点无关

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]MI11
 - 系统/ROM: [例如: MIUI 11]MIUI 12.5
 - Android 版本 [例如: 10]11
 - ROM版本 [例如: 20.3.19]15.5.0

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
