### ISSUE TITLE
[BUG] 小米平板5pro疑似内存泄露

### ISSUE THREAD

**Issue by huanzhou-sama** [Kr328/ClashForAndroid#1290]
**描述出现的错误**
只挂了clash，什么都不做，状态栏流量检测一直持续1MB/S以上，但是打开Clash，主页面流量也没有增加，打开系统的网络诊断，也找不到是什么在跑流量，进程中Clash占了500多MB运行内存，这显然不正常，使用了clash的日志功能也检测不到问题。

**如何复现该错误**
复现步骤:
1. 打开clash，静置一会儿，流量就开始跑，虽然不是一直是这样，但是经常出现

**预期行为**
正常应该运行内存占用在几十兆

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 小米平板5pro
 - 系统/ROM:  MIUI 12.5.14
 - Android 版本 11
 - ROM版本 12.5.14

**应用信息**
 - 版本: 2.5.3
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: github play商店 两种内核都有这个问题

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
