### ISSUE TITLE
[BUG] 小米平板5Pro疑似内存泄露

### ISSUE THREAD

**Issue by huanzhou-sama** [Kr328/ClashForAndroid#1291]
描述出现的错误
只挂了clash，什么都不做，状态栏流量检测一直持续1MB/S以上，但是打开Clash，主页面流量也没有增加，打开系统的网络诊断，也找不到是什么在跑流量，进程中Clash占了500多MB运行内存，这显然不正常，使用了clash的日志功能也检测不到问题。

如何复现该错误
复现步骤:
打开clash，静置一会儿，流量就开始跑，关闭clash，就恢复正常。虽然不是一直是这样，但是经常出出现

预期行为
正常应该运行内存占用在几十兆

屏幕截图
如果适用, 上传屏幕截图以帮助描述错误

设备信息 (请完成以下信息):

机型: 小米平板5pro
系统/ROM: MIUI 12.5.14
Android 版本 11
ROM版本 12.5.14
应用信息

版本: 2.5.3
安装包文件名: [例如: app-release-arm64-v8a.apk]
应用来源: github play商店 两种内核都有这个问题

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
日志 配置 请

你这样写 我只能告诉你 Mi 11 上没有问题

**Comment by huanzhou-sama** [comment]
> 配置请
> 
> 你这样写我只能告诉你 Mi 11 上没有问题
日志只有两行
[APP] Logcat level: silent
[APP] request force GC
![Screenshot_2021-11-22-11-24-01-044_com.github.kr328.clash.foss](https://tva2.sinaimg.cn/large/006ttJiJgy1gwnrrf0pojj31z418ge81.jpg)
![2021-11-22-11-28-47](https://tvax3.sinaimg.cn/large/006ttJiJgy1gwnrrebevkj31ij03xacs.jpg)

**Comment by Kr328** [comment]
> Logcat level: silent

日志级别调高

**Comment by huanzhou-sama** [comment]
感谢，找到了
![Screenshot_2021-11-22-11-38-51-861_com.github.kr328.clash.foss](https://tva3.sinaimg.cn/large/006ttJiJgy1gwns0v1ot5j31z418gkjl.jpg)
疯狂这个，请问是什么原因
日志文件https://huangzhen123.lanzoui.com/iUs1hwrlwvi
内存占用![Screenshot_2021-11-22-11-42-24-642_com.miui.securitycenter](https://tvax1.sinaimg.cn/large/006ttJiJgy1gwns2ld2x9j31z418ghdt.jpg)

**Comment by Kr328** [comment]
@huanzhou-sama 配置 请

**Comment by huanzhou-sama** [comment]
> @huanzhou-sama 配置 请

是一个机场订阅，可以私发您邮箱吗

**Comment by Kr328** [comment]
@huanzhou-sama 不能 你下载下来把 proxies 和 proxy-providers 删干净不就完了

**Comment by huanzhou-sama** [comment]
https://huangzhen123.lanzoui.com/iN6LFwrmg7e
这个订阅，我在手机上使用就没有这个问题

**Comment by Kr328** [comment]
@Kr328 去把 redir-port 关了

**Comment by huanzhou-sama** [comment]
> @Kr328 去把 redir-port 关了

![Screenshot_2021-11-22-12-01-55-165_com.github.kr328.clash.foss](https://tva2.sinaimg.cn/large/006ttJiJgy1gwnsmtvvs7j31z418ge81.jpg)
是这里吗，请问如何关闭

**Comment by Kr328** [comment]
@huanzhou-sama 填 0

**Comment by huanzhou-sama** [comment]
> @huanzhou-sama 填 0

好的，感谢！
