### ISSUE TITLE
[Feature Request] 有没有可能在本地统一订阅规则

### ISSUE THREAD

**Issue by aliveday** [Kr328/ClashForAndroid#1292]
每次在配置文件里添加的规则一更新订阅就被覆盖没了。有没有可能添加这样一种运行模式，只从订阅连接里读取节点列表然后添加进同一个分组，默认所有连接都走代理，再从本地配置文件读取直连和去广告规则，这样牺牲多分组的优势换取手动管理上的方便呢。

**Comment by Kr328** [comment]
@aliveday cfa 可不支持本地修改订阅配置文件 你在其他地方得到的应用或者不是本应用就不要在这里反馈了

当然你这个需求可以用 subconverter 实现

**Comment by aliveday** [comment]
> 

外部资源里的不算配置文件么？为了一两个不在规则里的域名要费多大的劲，有个手动添加直连规则的功能在你眼里就这么没必要么，我提了也没用算我多嘴了。

**Comment by EKyero** [comment]
@aliveday 外部资源即proxy-provider和rule-provider是上游提出的，cfa支持很正常
很多个人，非商业的开发者都不喜欢加无太大作用的功能，这个只能说要不尊重其想法，要不用键盘投票（自己fork一份来做这个功能）
