### ISSUE TITLE
[BUG] 网络连接请求无法确认

### ISSUE THREAD

**Issue by UnknownMother-Goose** [Kr328/ClashForAndroid#1294]
**描述出现的错误**
请简洁的描述你遇到的错误
更新配置后，点击启动弹出网络连接请求，但是无法点击确认只能点击取消回到主界面
**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
点击确认开始使用
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![Screenshot_2021-11-25-09-44-23-727_com android vpndialogs](https://user-images.githubusercontent.com/95004711/143358609-4b9064ce-a4e2-4985-a5b9-bf77f893886b.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Redmi K40
 - 系统/ROM: MIUI 12.5.18
 - Android 版本 11
 - ROM版本 不知道

**应用信息**
 - 版本: 2.3.22
 - 安装包文件名: app-universal-release.apk
 - 应用来源: 

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
#817 
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>Logcat level: info
```

**Comment by XyLyXyRR** [comment]
@UnknownMother-Goose ?

**Comment by UnknownMother-Goose** [comment]
> **描述出现的错误** 请简洁的描述你遇到的错误 更新配置后，点击启动弹出网络连接请求，但是无法点击确认只能点击取消回到主界面 **如何复现该错误** 复现步骤:
> 
> 1. ...
> 2. ...
> 3. ...
> 4. ...
> 
> **预期行为** 清晰简单的描述你预期的应用应该表现的行为 点击确认开始使用 **屏幕截图** 如果适用, 上传屏幕截图以帮助描述错误 ![Screenshot_2021-11-25-09-44-23-727_com android vpndialogs](https://user-images.githubusercontent.com/95004711/143358609-4b9064ce-a4e2-4985-a5b9-bf77f893886b.jpg)
> 
> **设备信息 (请完成以下信息):**
> 
> * 机型: Redmi K40
> * 系统/ROM: MIUI 12.5.18
> * Android 版本 11
> * ROM版本 不知道
> 
> **应用信息**
> 
> * 版本: 2.3.22
> * 安装包文件名: app-universal-release.apk
> * 应用来源:
> 
> **附加信息** 其他的可能与改错误相关的信息
> 
> **配置文件** 在此粘贴 **去除服务器信息的** 的 **配置文件**
> 
> ```yaml
> # 
> ```
> 
> **日志** 粘贴日志以帮助侦测错误
> 
> ```
> <在此粘贴>Logcat level: info
> ```



> @UnknownMother-Goose 重置订阅连接，不然别人会盗用。

**Comment by UnknownMother-Goose** [comment]
> @UnknownMother-Goose 重置订阅连接，不然别人会盗用。

多谢！问题已经解决了，顺便问问怎么删掉这个贴子orz

**Comment by UnknownMother-Goose** [comment]
> **描述出现的错误** 请简洁的描述你遇到的错误 更新配置后，点击启动弹出网络连接请求，但是无法点击确认只能点击取消回到主界面 **如何复现该错误** 复现步骤:
> 
> 1. ...
> 2. ...
> 3. ...
> 4. ...
> 
> **预期行为** 清晰简单的描述你预期的应用应该表现的行为 点击确认开始使用 **屏幕截图** 如果适用, 上传屏幕截图以帮助描述错误 ![Screenshot_2021-11-25-09-44-23-727_com android vpndialogs](https://user-images.githubusercontent.com/95004711/143358609-4b9064ce-a4e2-4985-a5b9-bf77f893886b.jpg)
> 
> **设备信息 (请完成以下信息):**
> 
> * 机型: Redmi K40
> * 系统/ROM: MIUI 12.5.18
> * Android 版本 11
> * ROM版本 不知道
> 
> **应用信息**
> 
> * 版本: 2.3.22
> * 安装包文件名: app-universal-release.apk
> * 应用来源:
> 
> **附加信息** 其他的可能与改错误相关的信息
> 
> **配置文件** 在此粘贴 **去除服务器信息的** 的 **配置文件**
> 
> ```yaml
> # iUDrfIN7lLAIMuPr?clash=1
> ```
> 
> **日志** 粘贴日志以帮助侦测错误
> 
> ```
> <在此粘贴>Logcat level: info
> ```
