### ISSUE TITLE
[BUG] 关掉”配置文件处理结果“”配置文件处理状态“通知后，配置文件不再自动更新。

### ISSUE THREAD

**Issue by Marukon** [Kr328/ClashForAndroid#1298]
**描述出现的错误**
关掉”配置文件处理结果“”配置文件处理状态“通知后，配置文件不再自动更新。

**如何复现该错误**
复现步骤:
1. 进入Android系统的通知设置，禁止cfa发送”配置文件处理结果“”配置文件处理状态“通知
2. 设置cfa的配置文件自动更新
3. 无论过多久，配置文件都不会如期自动更新
4. 恢复第一步中被禁用的通知，自动更新恢复正常

**预期行为**

禁用通知后仍能按时自动更新。
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [一加8T]
 - 系统/ROM: [氢11和ColorOS12都试过]
 - Android 版本 [例如: 11/12]
 - ROM版本 [例如: 11.11]

 - 机型: [一加5T]
 - 系统/ROM: [Pixel Experience]
 - Android 版本 [例如: 11]
 - ROM版本 [例如: 2021.11.15]
**应用信息**
 - 版本: [最近几个版本都不行，包括2.5.3]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Github Release]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
你是如何判断 "配置文件没有更新" 的

以及会使用 adb 的话 提供一下 `adb logcat` 和 `adb shell dumpsys alarm` 的日志

**Comment by Marukon** [comment]
> 你是如何判断 "配置文件没有更新" 的
> 
> 以及会使用 adb 的话 提供一下 `adb logcat` 和 `adb shell dumpsys alarm` 的日志

比如我设置了自动更新周期为24h，那么等待72小时都不会更新。。。
好的，我去抓

**Comment by Marukon** [comment]
[log_2021-12-05-22_44_19.txt](https://github.com/Kr328/ClashForAndroid/files/7656110/log_2021-12-05-22_44_19.txt)
[log_2021-12-05-22_20_30.txt](https://github.com/Kr328/ClashForAndroid/files/7656112/log_2021-12-05-22_20_30.txt)
![Screenshot_20211205-214150_Clash_for_Android](https://user-images.githubusercontent.com/6285343/144751531-ff06c857-0fd3-43d0-8e13-1c635e587bac.png)
![Screenshot_20211205-214158_Clash_for_Android](https://user-images.githubusercontent.com/6285343/144751535-6680a0e1-16f7-49c6-b971-6e18994b85a3.png)

**Comment by Kr328** [comment]
`adb shell dumpsys alarm` 是导出定时服务的信息 需要这个信息

用终端输入 `adb shell dumpsys alarm` > dumpsys.txt 也不行吗

**Comment by Marukon** [comment]
> `adb shell dumpsys alarm` 是导出定时服务的信息 需要这个信息
> 
> 用终端输入 `adb shell dumpsys alarm > dumpsys.txt` 再获取 dumpsys.txt 也不行吗

是使用的这条命令，但一直0kb

**Comment by Kr328** [comment]
那就只能 help wanted 了

一般来说关闭通知并不影响 定时和通知服务的行为 但是系统可能会因为通知被关闭而将应用休眠 所以这里猜测是系统将应用休眠了而无法正确接受到定时消息

**Comment by Marukon** [comment]
> 那就只能 help wanted 了
> 
> 一般来说关闭通知并不影响 定时和通知服务的行为 但是系统可能会因为通知被关闭而将应用休眠 所以这里猜测是系统将应用休眠了而无法正确接受到定时消息

明白，今天我在抓取试试

**Comment by Marukon** [comment]
> adb shell dumpsys alarm > dumpsys.txt

[dumpsys.txt](https://github.com/Kr328/ClashForAndroid/files/7657183/dumpsys.txt)
[logcat.txt](https://github.com/Kr328/ClashForAndroid/files/7657190/logcat.txt)

**Comment by Microbiosis** [comment]
The feedback about your Bug has caused me trouble.

来自 ProtonMail 移动端

Please don't send bug feedback to my mailbox again.

--------原始邮件--------
在 2021年12月6日 08:54, Maruko 来信：

**Comment by xgdgsc** [comment]
我也遇到了，但休眠了vpn还能正常使用吗
