### ISSUE TITLE
[Feature Request] 建议在UI上加一个是否允许QUIC流量的开关

### ISSUE THREAD

**Issue by Y32Gcnte8z** [Kr328/ClashForAndroid#1299]
**功能描述**
在UI层面增加一个开关，可以选择是否直接禁止所有的QUIC协议的数据

**描述你希望的实现方式**
虽然说这个功能可以用Script实现，可以考虑到开源内核不支持Script，或许可以在Android的VPN接口层面实现这个功能。
如果没有这个功能，foss版要么允许udp流量走代理，但quic协议走代理时效果很不好。要么不允许udp走代理，udp会直连，但有些浏览器或者app会尝试quic，导致DNS泄露。

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
CFA 只是 UI 所有网络功能基于 core 实现 core 有的功能 cfa 才会有 其他额外的网络功能不做自定义实现
