### ISSUE TITLE
[BUG] 应用崩溃

### ISSUE THREAD

**Issue by youling257** [Kr328/ClashForAndroid#1301]
**描述出现的错误**
请简洁的描述你遇到的错误

2.5点击启动应用崩溃

**如何复现该错误**
复现步骤:
1. ...点击启动
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
Androidx86 cm14.1

**应用信息**
 - 版本: [2.5.3]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [github]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>

```

日志 [clash.txt](https://github.com/Kr328/ClashForAndroid/files/7670375/clash.txt)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@youling257 系统信息填完 包括 CPU 信息
