### ISSUE TITLE
[Feature Request] 加入代理play商店和谷歌框架

### ISSUE THREAD

**Issue by TGich** [Kr328/ClashForAndroid#1303]
v2ray和ss都可以在分应用代理中显示所有应用包括谷歌商店和框架，不知道clash不显示的原因

**Comment by AkariiinMKII** [comment]
![Screenshot_20211210-081957.png](https://user-images.githubusercontent.com/6019344/145496080-cdc9809c-5121-4963-a287-522c3590bc23.png)
