### ISSUE TITLE
请问大佬，2.4.14能不能支持kcptun协议

### ISSUE THREAD

**Issue by klyyi137** [Kr328/ClashForAndroid#1308]
请问大佬，clash for android 是否有内置kcptun协议，kcptun for ss 现在不好用。特转来clash学习。
如果没内置，后期是否可以增加内置kcptun协议。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
