### ISSUE TITLE
现在想把clahs加入到安卓  APP中，一起打包发布。单独使用太麻烦了。 

### ISSUE THREAD

**Issue by thisnamehasbeenusedbysomebody** [Kr328/ClashForAndroid#1311]
**功能描述**
现在想把clahs加入到APP中，一起打包发布。单独使用太麻烦了。 

**描述你希望的实现方式**
直接编译成APP的一部分

请作者邮箱回复以下。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
