### ISSUE TITLE
想把该应用集成到APP中

### ISSUE THREAD

**Issue by thisnamehasbeenusedbysomebody** [Kr328/ClashForAndroid#1312]
**功能描述**
希望把该用集成到APP中，方便小白使用

**描述你希望的实现方式**
自动选择代理服务器而不是自己手动选择

**附加信息**
希望作者回复下邮箱。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@thisnamehasbeenusedbysomebody 这里不接任何定制 请自行寻找其他开发者

**Comment by akw5454521** [comment]
没技术开个X的机场

**Comment by thisnamehasbeenusedbysomebody** [comment]
非常感谢您的回信，我会认真考虑。

akw5454521 ***@***.***> 於 2021年12月20日 週一 下午6:46寫道：
