### ISSUE TITLE
[Feature Request] 自定义内核求助

### ISSUE THREAD

**Issue by 363137946** [Kr328/ClashForAndroid#1313]
**功能描述**
请清晰的描述你想要的功能

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

clone了您仓库的clash和CFA
想修改clash代码来自定义内核，在我的仓库clash修改了代码，编译出来的可执行的clash自定义功能生效了
然后修改了我仓库CFA的子模块指向了我仓库的clash，用github的action编译出来的app，修改的内核功能好像没生效，是哪里的问题？还需要改什么东西？
我的仓库363167946/ClashForAndroid

**Comment by Kr328** [comment]
与开发相关的任何问题请自行解决
