### ISSUE TITLE
[BUG] Trojan/Vmess+gRPC断连(不是断流)严重

### ISSUE THREAD

**Issue by Kia678** [Kr328/ClashForAndroid#1318]
**Describe the bug**
在使用Trojan/Vmess+gRPC节点时，经常断连，特别是在关闭Proxy开关，再重新打开Proxy开关之后，Trojan/Vmess+gRPC断连现象严重，同节点服务器的Trojan(原生)节点没有断连现象.
这个断连不是断流的意思，断连是指某次打开Trojan+gRPC节点后，会永久无法连通该节点，除非反复点击Proxy开关或许能连通改节点.

**Expected behavior**

**Device Info (please complete the following information):**

 - Device: [Xiaomi]
 - ROM: [MIX2S]
 - ROM Version:
 - Android Version [10]

**Application Info (please complete the following information):**

 - Version: [2.5.3]
 - Apk File Name: [2.5.3.app-release-arm64-v8a.apk]
 - Distribution Channel: [github]

**Comment by Kr328** [comment]
反馈上游 请

**Comment by Kia678** [comment]
经过反复测试，CFW没这个问题，应该不是core的问题

**Comment by Kia678** [comment]
> 反馈上游 请

经过反复测试，CFW没这个问题，应该不是core的问题

**Comment by Kr328** [comment]
cfa 没有对协议部分进行任何修改

**Comment by Kia678** [comment]
> cfa 没有对协议部分进行任何修改

经过反复测试，2.4.14的包没有这个断连问题，并且延迟测试相应挺快的，可能是最近两个pre版本引入的新功能或修改导致的bug，需要导出日志给你一下吗？

**Comment by Kia678** [comment]
> cfa 没有对协议部分进行任何修改

经过反复测试，cfa2.4.14的包以及CFW、ClashX没有这个gRPC断连问题，可能是最近两个pre版本引入的新功能或修改导致的bug

**Comment by Kr328** [comment]
@Kia678 那也应该反馈上游

**Comment by Kia678** [comment]
> @Kia678 那也应该反馈上游

可能是因为2.5.3改成了fake-dns的问题

**Comment by Kia678** [comment]
> cfa 没有对协议部分进行任何修改

我知道，我说的是2.5.3的某些设置变动，导致对gRPC的断连，可能是fake-ip
