### ISSUE TITLE
[Feature Request] 希望更新预处理配置编辑

### ISSUE THREAD

**Issue by Lucio-0408** [Kr328/ClashForAndroid#1319]
**功能描述**
可创建能够自定义访问规则的配置文件，如DOMAIN,test.com,DIRECT，更新订阅时将自定义规则自动加入到规则前。

**描述你希望的实现方式**
在配置里新增“预处理配置编辑”，可以导入现成的yaml文件，也可以自己编辑，自己编辑的情况下，订阅链接可以直接导入配置里的，还可以提供一些基础模板、基础词汇之类的。

**附加信息**
CFW上已实现，官方文档链接https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by Kr328** [comment]
代理 代理组 和 规则 是 强关联 
cfa 不会提供任何方式单独修改其中某一项以避免一些低级问题
