### ISSUE TITLE
[BUG] 网络设置里启用私密DNS（DoT)后，Trojan协议的代理全部失效，这是cfa的问题还是Trojan协议的缘故

### ISSUE THREAD

**Issue by YirunFantasy** [Kr328/ClashForAndroid#1323]
Android设备，在启用私密DNS后，填入`dot-我的id脱敏.dot.pub`，提供商是腾讯，属于DoT加密类型，相同机场的代理在电脑端运行正常（cfw），能够代理，手机端却打不开外网，日志里大多都是明文IP，比如`[TCP] dial Proxy (match DomainKeyword/google) to www.google.com:443 error: tw1.chuqianglai.com:443 connect error: dial tcp4 60.249.2.239:443: i/o timeout`，直接timeout，折腾了半天，无意间在日志里看到有`dot-我的id脱敏.dot.pub`的信息，就尝试着去手机设置里关闭私密DNS选项，用路由器自动下发的，此时所有代理瞬间恢复正常，而日志里的连接也从IP类型变为域名，比如`[TCP] 172.19.0.1:58638 --> www.googleadservices.com:443 match DomainKeyword(google) using Proxy[英国-UK3-流量倍率:1.0]`

想请教下，出现这种问题，是Trojan和DoT (TLS加密）有什么冲突吗，还是说就是DoT不安全，被腾讯看到我的请求内容给污染了，还是可以从cfa应用里升级迭代解决呢？

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
国内 DoT/DoH 自带污染

**Comment by YirunFantasy** [comment]
> 国内 DoT/DoH 自带污染

谢谢，辛苦了
