### ISSUE TITLE
一键导入配置报错

### ISSUE THREAD

**Issue by androiddk1** [Kr328/ClashForAndroid#1325]
![Screenshot_2022-01-01-11-08-13-349_com github kr328 clash](https://user-images.githubusercontent.com/5069404/147843333-3f688669-d846-4706-9ab9-76bc6797bf33.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by EKyero** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1224
