### ISSUE TITLE
应该下载哪个版本？

### ISSUE THREAD

**Issue by mingyoucao** [Kr328/ClashForAndroid#1327]
![Screenshot_20220101_161407_com android browser](https://user-images.githubusercontent.com/96685208/147846775-5003a911-80e8-422e-90a2-a64e6de89dba.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
