### ISSUE TITLE
[Feature Request]  请问如何添加自定义网站规则呢？

### ISSUE THREAD

**Issue by funnybones2015** [Kr328/ClashForAndroid#1328]
**功能描述**
添加自定义网站规则功能

**描述你希望的实现方式**
希望增加添加自定义网站规则功能

**附加信息**
目前clash for windows可以通过parser添加一些自定义网站规则，clash for android 不知如何添加预置规则呢？

**Comment by Kr328** [comment]
subconverter 或者手动写配置文件

**Comment by funnybones2015** [comment]
> subconverter 或者手动写配置文件

subconverter只是转换不同格式的订阅链接，我的意思是如何针对某个网址（比如linkedin.com目前国内ip访问会被限制，需要单独添加一个规则，让linkedin.com走代理）定制分流规则。Windows版可以通过parser添加一条DOMAIN-SUFFIX,linkedin.com,GLOBAL，就可以强制该网站走代理，而且每次订阅规则更新也不会被覆盖。

**Comment by Kr328** [comment]
@funnybones2015 subconverter 有追加规则的功能

还有不要拿 Windows 来说事 那个不是我开发的 我接受不了在 Android 上用掉大量的存储和内存

**Comment by funnybones2015** [comment]
> subconverter

嗯嗯  好的，有没有比较简单的添加自定义网站分流的方法？用subconverter好像有些复杂
