### ISSUE TITLE
[BUG] 小米12无法从通知栏冷启动连接

### ISSUE THREAD

**Issue by Mr-Tim-CN** [Kr328/ClashForAndroid#1329]
**描述出现的错误**
下拉通知栏，在通知栏点击Clash图标快捷开关，Clash并没有启动。多次点击还是没反应。长按开启APP后，才可以从通知栏使用快捷开关。

**如何复现该错误**
复现步骤:
1. 小米12 使用出厂MIUI版本13.0.10
2. 小米系统设置里使用旧版控制中心
3. 在通知栏添加Clash快捷方式
4. 清理后台，锁屏，一段时间后在通知栏点击Clash，无法启动

**预期行为**
预期情况下应该后台启动Clash并按照上一次的配置连接

**屏幕截图**
录屏：
https://user-images.githubusercontent.com/53875091/148040865-e2b299bf-b114-49a8-951e-357ba5ff5a27.mp4

**设备信息 (请完成以下信息):**
 - 机型: 小米12
 - 系统/ROM: MIUI
 - Android 版本 12
 - ROM版本 MIUI 13.0.10

**应用信息**
 - 版本: 2.5.3.premium
 - 安装包文件名: cfa-2.5.3-premium-arm64-v8a-release.apk
 - 应用来源: GitHub Release

**附加信息**
之前的设备是小米8SE，MIUI 12，安卓10，这个功能是正常的。觉得可能是安卓12或者MIUI13带来的影响。希望能确认一下bug的成因。

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
不适用
```

**日志**
粘贴日志以帮助侦测错误
```
不适用
```

**Comment by Kr328** [comment]
本应用不关注在 beta 系统上出现的任何问题 请自行回退到稳定版本

**Comment by Mr-Tim-CN** [comment]
我的MIUI是稳定版😓
问了一下同学，安卓11+MIUI12.5稳定版的组合也有这个bug。复现的关键是杀后台之后过几分钟（比如锁屏等两分钟），再拉通知栏。在应用设置里打开自启动也没用。

https://user-images.githubusercontent.com/53875091/148055668-68485912-0ad5-484f-b83a-964e9bc5be7d.mp4

**Comment by Pandaver** [comment]
打开应用权限自启动和省电策略无限制就可以了 @Mr-Tim-CN

**Comment by robin0323** [comment]
> 打开应用权限自启动和省电策略无限制就可以了 @Mr-Tim-CN
+1
