### ISSUE TITLE
[Feature Request] URL配置下为什么不能上传自定义的配置文件

### ISSUE THREAD

**Issue by l1ng-c** [Kr328/ClashForAndroid#1330]
**功能描述**
URL订阅模式下，无法修改配置yaml文件，只能导出yaml不能上传自定义yaml

**描述你希望的实现方式**
希望在URL模式下增加配置yaml上传功能，更新URL时，只更新节点部分的信息

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
会出现大量不可预期的行为 所以不做
