### ISSUE TITLE
[BUG] 通知栏点击Clash图标快捷开关无法冷启动

### ISSUE THREAD

**Issue by Mr-Tim-CN** [Kr328/ClashForAndroid#1331]
**描述出现的错误**
下拉通知栏，在通知栏点击Clash图标快捷开关，Clash并没有启动。多次点击还是没反应。长按开启APP后，才可以从通知栏使用快捷开关。

**如何复现该错误**
复现步骤:
1. 小米12 使用出厂MIUI版本13.0.10 安卓12
2. 小米系统设置里使用旧版控制中心
3. 在通知栏添加Clash快捷方式
4. 清理后台，锁屏，一段时间后在通知栏点击Clash，无法冷启动

**预期行为**
预期情况下应该后台启动Clash并按照上一次的配置连接

**屏幕截图**
录屏：
https://user-images.githubusercontent.com/53875091/148048907-faa466e3-92ff-4a21-9db6-f1874008e39c.mp4

**设备信息 (请完成以下信息):**
 - 机型: 小米12
 - 系统/ROM: MIUI
 - Android 版本 12
 - ROM版本 MIUI 13.0.10

**应用信息**
 - 版本: 2.4.14.premium
 - 安装包文件名: cfa-2.4.14-premium-arm64-v8a-release.apk
 - 应用来源: GitHub Releases

**附加信息**
之前的设备是小米8SE，MIUI 12，安卓10，这个功能是正常的。觉得可能是安卓12或者MIUI13带来的影响。希望能确认一下bug的成因。

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
不适用
```

**日志**
粘贴日志以帮助侦测错误
```
不适用
```

**Comment by Kr328** [comment]
#1329

**Comment by ShichimiyaMizu** [comment]
我是Mi 11 pro，miui13.0.9，也有这个情况，我感觉应该是miui的隐私权限限制了clash在通知栏启动。于是我在应用信息中允许了权限管理和通知管理里的所有选项，依然无法打开。之后又尝试了在安装应用未知来源中，找到clash→允许此来源的应用，该问题解决。希望可以帮到你

**Comment by Mr-Tim-CN** [comment]
试了一下，并没有解决。确认杀灭后台之后锁屏静置2分钟，再解锁从通知栏启动，依然打不开。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月17日(周日) 下午4:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kr328/ClashForAndroid] [BUG] 通知栏点击Clash图标快捷开关无法冷启动 (Issue #1331)




 
我是Mi 11 pro，miui13.0.9，也有这个情况，我感觉应该是miui的隐私权限限制了clash在通知栏启动。于是我在应用信息中允许了权限管理和通知管理里的所有选项，依然无法打开。之后又尝试了在安装应用未知来源中，找到clash→允许此来源的应用，该问题解决。希望可以帮到你
 
&mdash;

**Comment by zhamdoctor** [comment]
> 

10pro表示无效

**Comment by GregAMO** [comment]
> > 
> 
> 10pro表示无效

点击无效就是后台被杀进程了，此时，请尝试长按快捷面板磁贴图标，能够直接弹出clash主界面，无视电池或后台策略，只要不是被冻结了都能拉起来。

**Comment by zhamdoctor** [comment]
> 

试了下可以了，省电策略的问题

**Comment by TinyLi** [comment]
> > > 
> > 
> > 
> > 10pro表示无效
> 
> 点击无效就是后台被杀进程了，此时，请尝试长按快捷面板磁贴图标，能够直接弹出clash主界面，无视电池或后台策略，只要不是被冻结了都能拉起来。

感谢，参考可行，MI11 操作流程，长按应用按钮，选择应用信息，选择省点策略，点击无限制，就可以了

**Comment by wsyangzy** [comment]
省电策略设置为无限制即可

**Comment by xdtxAM** [comment]
> > > > 
> > > 
> > > 
> > > 10pro表示无效
> > 
> > 
> > 点击无效就是后台被杀进程了，此时，请尝试长按快捷面板磁贴图标，能够直接弹出clash主界面，无视电池或后台策略，只要不是被冻结了都能拉起来。
> 
> 感谢，参考可行，MI11 操作流程，长按桌面Clash图标，选择应用信息，选择省电策略，点击无限制，就可以了

长按桌面Clash图标，选择应用信息，选择省电策略，点击无限制，就可以了。可以
