### ISSUE TITLE
[BUG] 概率性无法使用快捷开关来启动Clash

### ISSUE THREAD

**Issue by zhouym233** [Kr328/ClashForAndroid#1332]
**描述出现的错误**
一个很久很久之前持续到现在的问题：
在数小时不使用Clash后，尝试点击下拉菜单的快捷开关来启用Clash时，没有任何反应
已经给予自启动权限，系统显示应用在后台运行；长按快捷开关可正常跳转到Clash界面，在进入过Clash主界面后开关恢复正常。

**如何复现该错误**
复现步骤:
1. 一段时间不使用Clash
2. 点击下拉菜单中的Clash图标，Clash无响应

**预期行为**
点击快捷开关即开启Clash开关

**屏幕截图**
![Screenshot_2022-01-05-00-31-46-649_com miui secur](https://user-images.githubusercontent.com/26868483/148091788-38cb879a-31e9-418c-82ef-7161c0db9014.jpg)
![Screenshot_2022-01-05-00-31-59-419_com miui secur](https://user-images.githubusercontent.com/26868483/148091972-4eae3d1e-18ec-48d4-a5aa-5d28ec75b6bb.jpg)
即使应用正在运行，也无法通过快捷菜单启用。

**设备信息 (请完成以下信息):**
 - 机型: Redmi K40
 - 系统/ROM: MIUI12.5/MIUI13均出现
 - Android 版本: Android11/Android12均出现
 - ROM版本: 21.9.x-21.12.30均出现

**应用信息**
 - 版本: 2.5.3.premium
 - 安装包文件名: cfa-2.5.3-premium-arm64-v8a-release.apk
 - 应用来源: GitHub

**附加信息**
由```logcat | grep clash```得出的部分系统日志
![Screenshot_2022-01-05-00-18-01-618_com termux](https://user-images.githubusercontent.com/26868483/148091478-eb29386e-0e17-4932-8d36-c7178f59f07a.jpg)

**配置文件**
目测与配置文件无关，如有需要我会补充
```yaml
# 暂无
```

**日志**
暂无APP日志
```
<暂无>
```

**Comment by zhouym233** [comment]
将“省电策略”设置为“无限制”后已解决。

**Comment by Mr-Tim-CN** [comment]
😥这个应该是bug，需要修复

**Comment by xuhaoyang** [comment]
在保持,忽略电池，允许自启后不行，那这是miui bug，应该找miui。
