### ISSUE TITLE
[BUG] 在后台缓存中被清理的话就无法用 ADB shell startserivce 命令唤醒。

### ISSUE THREAD

**Issue by 921j** [Kr328/ClashForAndroid#1333]
**描述出现的错误**
如果 Clash for Android 的后台进程被清理，则无法使用以下命令启动服务
adb shell am startservice -n com.github.kr328.clash/com.github.kr328.clash.service.TunService

**如何复现该错误**
复现步骤:
1. 任何能查看并关闭缓存进程的系统工具或第三发工具，或不将 cfa 加入后台清理白名单；
2. 关闭 cfa 的进程，或直接使用 adb shell am force-stop com.github.kr328.clash
3. 尝试以 adb shell am startservice -n com.github.kr328.clash/com.github.kr328.clash.service.TunService 启动服务
4. 提示 error not found no service started

**预期行为**
想把 cfa 的启动与关闭加入到 xposed edge pro 的手势和应用触发中

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: 2.4.13-2.5.3
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: github

**附加信息**
可以通过快速设置中的 cfa 图标开启服务，哪怕只是把快速设置全部展开不点击 cfa 图标，这时 cfa 的后台缓存进程就会被唤醒，但用
ADB shell startservice -n com.github.kr328.clash/com.github.kr328.clash.service.TitleService 却不行

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
应用不对任何非常规使用方式进行支持
