### ISSUE TITLE
[Feature Request] 是否可以在app端加入新增规则功能

### ISSUE THREAD

**Issue by bingar21** [Kr328/ClashForAndroid#1334]
**功能描述**
是否可以在app端加入新增规则功能，现在是不是只能在配置文件中更改代理规则。需求来自LinkedIn近期调整了用户策略，国内用户只能使用求职版，完整版本需要境外IP，但是大多机场主的规则都还是按原来linkedin国内即可访问不走代理数据，但是修改本地配置，服务器更新时还是要再做一次修改？

**描述你希望的实现方式**
是否可以在app端加入新增代理规则功能，将域名前缀、关键词等规则方便修改。

**Comment by Kr328** [comment]
本地创建文件类型直接编辑即可
