### ISSUE TITLE
希望添加geoip、geosite自动分流功能

### ISSUE THREAD

**Issue by TheThreeBodyProblems** [Kr328/ClashForAndroid#1335]
**功能描述**
可以从外部添加geoip、geosite文件，然后调用里面的标签来判断走代理或者直连。例：geosite:gfw ，geosite:greatfire，这两个可以proxy

**描述你希望的实现方式**
1、增加导入geo文件的选项。2、增加可以编辑简单的代码界面，来实现代理或直连。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by TheThreeBodyProblems** [comment]
这是QQ邮箱的自动回复，邮件已收到！
