### ISSUE TITLE
[Feature Request] 需求澳大利亚线路

### ISSUE THREAD

**Issue by holic-xyz** [Kr328/ClashForAndroid#1337]
**功能描述**
请清晰的描述你想要的功能

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
应用不提供任何代理服务器

**Comment by LiVanJam** [comment]
ss://YWVzLTI1Ni1nY206WTZSOXBBdHZ4eHptR0NAMTcyLjEwNS4xODAuMjI3OjMzODk=#%F0%9F%87%A6%F0%9F%87%BA_AU_%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A
