### ISSUE TITLE
你好，我们的CLASH 安卓版是不是扫黄版本？Porn\草榴、18、91等网站都无法浏览。[BUG] 

### ISSUE THREAD

**Issue by anpanpanp521** [Kr328/ClashForAndroid#1338]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: [e.g. Pixel 4]
 - ROM: [e.g: AOSP]
 - ROM Version:
 - Android Version [e.g. 10]

**Application Info (please complete the following information):**

 - Version: [e.g. 1.1.10]
 - Apk File Name: [e.g. app-release-arm64-v8a.apk]
 - Distribution Channel: [e.g. Google Play]

**Additional context**

**Configure**
Paste configure file which **removed server info** 
```yaml
# paste here
```

**Logs**
Paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by zm24120** [comment]
天那~我以为就我一个人遇到了呢~


不过我捐款后就解锁了~你也试试？

**Comment by zm24120** [comment]
天那~我以为就我一个人遇到了呢~


不过我捐款后就解锁了~你也试试？

**Comment by Kr328** [comment]
@zm24120 应用不提供任何代理服务器 相关问题自行询问代理服务提供商
