### ISSUE TITLE
198.18.0.× 走代理

### ISSUE THREAD

**Issue by Olivercoco** [Kr328/ClashForAndroid#134]
![photo_2020-02-22_17-56-18](https://user-images.githubusercontent.com/39828052/75090365-1e039880-559d-11ea-8082-3b0ac4c379c9.jpg)
clash 1.1.1 Android 10   fakeip走代理了，请问这是预期行为吗？

**Comment by Kr328** [comment]
丢映射 不规范应用可能存在这个问题 Clash 无法解决
