### ISSUE TITLE
[BUG] CFA wrecks network speed display in status bar

### ISSUE THREAD

**Issue by codafi21** [Kr328/ClashForAndroid#1343]
**Describe the bug**
as per the pic, the network speed nearly doubles in status bar while the real speed is far cry from that speed.
![image](https://user-images.githubusercontent.com/93474348/149558832-5bd30589-71b3-46c1-9a3c-f11252f2c49a.png)

**To Reproduce**
as per the pic above

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: [e.g. Pixel 4]
 - ROM: [e.g: AOSP]
 - ROM Version:
 - Android Version [e.g. 10]

**Application Info (please complete the following information):**

 - Version: [e.g. 1.1.10]
 - Apk File Name: [e.g. app-release-arm64-v8a.apk]
 - Distribution Channel: [e.g. Google Play]

**Additional context**

**Configure**
Paste configure file which **removed server info** 
```yaml
# paste here
```

**Logs**
Paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
feedback to your rom manufacturer pls

**Comment by akw5454521** [comment]
This is intented

**Comment by codafi21** [comment]
Why
