### ISSUE TITLE
[Feature Request] 延迟显示改下位置

### ISSUE THREAD

**Issue by Kia678** [Kr328/ClashForAndroid#1345]
**功能描述**
双列布局时，延迟的显示区对节点名称有遮挡

**描述你希望的实现方式**
建议将延迟显示挪移到下方，与协议名并排

**Comment by Kr328** [comment]
设计单列是为了解决这个问题的 移到下方短代理名称不平衡

**Comment by Kia678** [comment]
> 设计单列是为了解决这个问题的 移到下方短代理名称不平衡

跟协议名称同一位置，显示在协议名称旁边可解吗？

**Comment by Kr328** [comment]
@Kia678 会不平衡 曾经内部设计过 不合适
