### ISSUE TITLE
[BUG] 网络选项里读取应用列表读不到谷歌应用商店应用

### ISSUE THREAD

**Issue by zhoufenfens** [Kr328/ClashForAndroid#1350]
**描述出现的错误**
请简洁的描述你遇到的错误
在设置-网络-访问控制模式里选择“仅允许已选择的应用”选项时，访问控制应用宝列表里没有谷歌 Play商店应用，其实我的app里是有安装的。

**如何复现该错误**
复现步骤:
1. 设置-网络-访问控制模式里选择“仅允许已选择的应用”
2. 点击 访问控制应用宝列表

**预期行为**
应用列表里应该有谷歌应用商店

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型:  Redmi k20 pro
 - 系统/ROM: MIUI 12
 - Android 版本 11
 - ROM版本

**应用信息**
 - 版本:  2.5.3 premium
 - 安装包文件名: cfa-2.5.3-premium-universal-release.apk
 - 应用来源: github release页面

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/971
