### ISSUE TITLE
[Feature Request]  support  "kcptun" ?

### ISSUE THREAD

**Issue by Guang1234567** [Kr328/ClashForAndroid#1351]
Hello dev:

Could you support "kcptun" ? Thanks.

**Comment by Kr328** [comment]
feedback to upstream pls

**Comment by Guang1234567** [comment]
> feedback to upstream pls

Get it. Thanks your reply.

**Comment by Guang1234567** [comment]
The feedback of upstream : https://github.com/Dreamacro/clash/issues/16#issuecomment-431641444
