### ISSUE TITLE
[BUG] i can't use vmess in version 2.5.4 but in versions below that version the vmess can be used

### ISSUE THREAD

**Issue by Bimasingkong** [Kr328/ClashForAndroid#1353]
**Screenshots**
![Screenshot_2022-01-20-23-01-24-944_com github kr328 clash](https://user-images.githubusercontent.com/98108857/150376579-13e70845-da75-48bd-9768-bd67afa77017.jpg)
![Screenshot_2022-01-20-23-01-20-349_com github kr328 clash](https://user-images.githubusercontent.com/98108857/150376588-386d12f3-06ed-40dd-8feb-e3fbc229ed50.jpg)
![Screenshot_2022-01-20-22-49-00-506_com github kr328 clash](https://user-images.githubusercontent.com/98108857/150376594-c5b8e5bf-cdf1-4ec4-8395-de902a1ea8d7.jpg)
![Screenshot_2022-01-20-22-48-50-334_com github kr328 clash](https://user-images.githubusercontent.com/98108857/150376596-0b890463-6d61-48bb-ad18-afd93edcbaf8.jpg)

**Device Info (please complete the following information):**

 - Device: redmi 8
 - ROM: miui 12
 - ROM Version:
 - Android Version [10]

**Application Info (please complete the following information):**

 - Version: [v2.5.4]
 - Apk File Name: [cfa-2.5.4-premium-universal-release.apk]
 - Distribution Channel: [github]

**Comment by Bimasingkong** [comment]
i can't use vmess in version 2.5.4 but in versions below that version the vmess can be used
Please fixed

**Comment by Kr328** [comment]
feedback to upstream pls

**Comment by Bimasingkong** [comment]
Whare the upstream

**Comment by Kr328** [comment]
@Bimasingkong Dreamacro/clash

**Comment by Bimasingkong** [comment]
I am use clash for android not openclash

**Comment by Kr328** [comment]
@Bimasingkong It is all clash-based client's core. ALLLLLLLLLLL protocols implement by it

**Comment by Bimasingkong** [comment]
Thanks for your reply

**Comment by imyhxy** [comment]
@Bimasingkong Clash after v1.9.4 requires a new config format for vmess protocal
Change from
```yaml
ws-path: xxx
ws-headers: {Host: xxx}
```
to
```yaml
ws-opts: {path: xxx, headers: {Host: xxx}}
```
