### ISSUE TITLE
[BUG] 更新MIUI13后  添加url出现了EOF错误，一直添加不了

### ISSUE THREAD

**Issue by yangzhenkui** [Kr328/ClashForAndroid#1355]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
![image](https://user-images.githubusercontent.com/54930846/150537269-c69fb88c-2f8d-4871-88cc-08098e8e0cb0.png)

**屏幕截图**
![image](https://user-images.githubusercontent.com/54930846/150537299-68d1ace3-f619-4b53-8d3d-9c08f0626569.png)

如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 小米 10pro
 - 系统/ROM: MIUI 13
 - Android 版本 12

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
