### ISSUE TITLE
更新MIUI13后  添加url出现了EOF错误，一直添加不了[BUG] 

### ISSUE THREAD

**Issue by yangzhenkui** [Kr328/ClashForAndroid#1356]
**描述出现的错误**
更新MIUI13后  添加url出现了EOF错误，一直添加不了

**如何复现该错误**
复现步骤:
在配置哪儿添加url后，点击保存的时候，出现了 get “url” EOF错误，导致配置不了

**预期行为**
没有更新系统之前可以正常的使用的

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![image](https://user-images.githubusercontent.com/54930846/150538194-19124313-8a3b-49ab-9607-7284f7fb8330.png)

**设备信息 (请完成以下信息):**
 - 机型: 小米10 Pro
 - 系统/ROM: MIUI 13
 - Android 版本 12
 - ROM版本 22.1.19

**应用信息**
 - 版本: [例如: 1.1.10] 2.5.4
 - 安装包文件名: [例如: app-release-arm64-v8a.apk] cfa-2.5.4-premium-universal-release
 - 应用来源: [例如: Google Play] Github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
