### ISSUE TITLE
[BUG] 应用列表无法读取到工作沙盒中的应用

### ISSUE THREAD

**Issue by happyeggchen** [Kr328/ClashForAndroid#1361]
**描述出现的错误**
请简洁的描述你遇到的错误
如题
**如何复现该错误**
复现步骤:
安装炼妖壶等类应用，安装应用，在主系统中的clash for Android 无法找到

**预期行为**
沙盒中应用应该也要可以显示

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: ginkgo
 - 系统/ROM arrowOS12
 - Android 版本 12
 - ROM版本 12

**应用信息**
 - 版本: 最新
 - 安装包文件名: release-arm64-v8a.apk
 - 应用来源: GitHub release

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
那不然呢

要不你去让 Google 给普通应用读取其他用户数据的权限?

**Comment by happyeggchen** [comment]
Sagernet可以，不知道为什么
