### ISSUE TITLE
[BUG] fire stick tv max上安装最新版本Clash问题

### ISSUE THREAD

**Issue by spirytuslove** [Kr328/ClashForAndroid#1364]
fire stick tv max上安装最新版本Clash可以运行但是图标不显示
![Uploading image.jpg…]()

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
