### ISSUE TITLE
Snell version 3 support for snell client

### ISSUE THREAD

**Issue by sevvian** [Kr328/ClashForAndroid#1368]
Hi Team,

I see that Snell server by surge team has released Snell version for both server and client . could you please add support for Snell v3 in the client side within clash for android . 

As I could not see release note mentioning v3 support in the latest 2.5.4 clash for android. 

Thanks for the great tool and thanks for the entire team.

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
