### ISSUE TITLE
希望能记忆代理模式

### ISSUE THREAD

**Issue by wyzsfxy** [Kr328/ClashForAndroid#137]
如果关闭之后再次开启cfa开关，代理会自动换回规则模式，希望能记忆一下

**Comment by Xxurc** [comment]
+1，不过怎么是low-priority😂

**Comment by yzhhh2212** [comment]
+1！！！！

**Comment by jiangyiUI** [comment]
+1

**Comment by byzod** [comment]
原来是个bug！

**Comment by Kr328** [comment]
This issue has been resolved
此问题已得到解决

**Comment by shenghan97** [comment]
我在android tv上面修改代理模式到global，修改完之后看到了一个toast notification说 only valid for current session. 然后重启之后就确实变回来 rule based模式。这个issue难道只在手机端被修复了吗？

**Comment by EKyero** [comment]
@shenghan97 想保存模式在覆写里面改
