### ISSUE TITLE
[Feature Request] 默认开启DoH

### ISSUE THREAD

**Issue by junjieyuan** [Kr328/ClashForAndroid#1373]
**功能描述**
目前CFA默认使用了[多个未加密的域名服务器](https://github.com/Kr328/ClashForAndroid/blob/791794f59da4bcc4862967917ef50295e3991372/core/src/main/golang/native/config/defaults.go#L5-L8)，代理节点入口仍会受到投毒污染。虽然可以使用覆写功能修改域名服务器，但是默认状况下可能不可用，建议改为对应域名服务器的加密服务。

**描述你希望的实现方式**
将默认域名服务器由明文改为DoH。

**附加信息**
无。

**Comment by Kr328** [comment]
在国内的网络环境下使用 DoH 大概率会影响直连体验 而用户使用的大多数场景均为直连 

况且大部分的代理服务提供商都有应对 DNS 污染的能力 在仍然需要使用 DoH 的情况下 cfa 也提供了该能力
