### ISSUE TITLE
[BUG] 创建配置错误：YAML

### ISSUE THREAD

**Issue by Logic530** [Kr328/ClashForAndroid#1379]
**描述出现的错误**
尝试创建某家机场的订阅时报错 `yaml: invalid leading UTF-8 octet`，但同样的订阅在 clash for windows 就没问题……
订阅是经过 subconverter 转换的，没转换的就没问题

**如何复现该错误**
复现步骤:
1. 创建配置
2. 填写订阅 URL
3. 点击保存按钮
4. 下载完成后报错

**预期行为**
能正常用吧，毕竟同样的订阅在 CFW 能用？

**屏幕截图**
![image](https://user-images.githubusercontent.com/22793670/153713771-87a80a9d-4db6-42a3-bde8-25b7caa5174e.png)

**设备信息 (请完成以下信息):**
 - 机型: 小米 CC9 Pro
 - 系统/ROM: MIUI 12
 - Android 版本 11
 - ROM版本 12.5.9

**应用信息**
 - 版本: 2.5.4.premium
 - 安装包文件名: 谷歌 play 下的
 - 应用来源: 谷歌 play

**附加信息**
上传到 issue 的配置文件毕竟删过东西，不知道有没有可能把导致问题的地方删掉了……

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
规则有亿点长，放入 gist
```
https://gist.github.com/Logic530/e690e3151f1e722519c901403b6afa56

**日志**
粘贴日志以帮助侦测错误
```
尝试抓取了一下……但什么都没有？
```

**Comment by Logic530** [comment]
破案了……是因为 subconverter 弄了一个 � 出来，删掉这个 � 就能正常使用
![image](https://user-images.githubusercontent.com/22793670/153715464-aeb42461-2f93-4b28-9c10-9d62311c86e2.png)

**Comment by sun2ot** [comment]
> 破案了……是因为 subconverter 弄了一个 � 出来，删掉这个 � 就能正常使用 ![image](https://user-images.githubusercontent.com/22793670/153715464-aeb42461-2f93-4b28-9c10-9d62311c86e2.png)

你好，我看你在subconverter里也提过这个issue，想请教下你最后是咋把它滤掉的？
我也碰到一家机场在节点里加转义字符，但是我在sub里怎么设置`exclude`都不过滤不掉。。。
