### ISSUE TITLE
[Android端创建配置错误] 

### ISSUE THREAD

**Issue by zfy68** [Kr328/ClashForAndroid#1380]
**描述出现的错误**
创建配置错误，见截图

**屏幕截图**
![Screenshot_20220213_084420_com.github.kr328.clash.jpg](https://user-images.githubusercontent.com/37278360/153733655-8d365f52-2731-4130-88ee-cb5bb9f315c0.jpg)

**设备信息 (请完成以下信息):**
 - Android 版本 [2.4.9]

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by zfy68** [comment]
现在正常了
