### ISSUE TITLE
[BUG] 添加订阅链接显示管道关闭

### ISSUE THREAD

**Issue by 368573607** [Kr328/ClashForAndroid#1381]
**Describe the bug**
我刚刚安装了clash for android，但当我尝试添加订阅链接的时候，却提示类似io:read/write on closed pipe

**To Reproduce**
1. 安装最新版的clash for android
2. 尝试导入一个url配置（经测试大陆可以访问的url）
3. 保存

**Expected behavior**
软件能够正常导入配置

**Screenshots**
![image](https://user-images.githubusercontent.com/60562136/153735878-f626a56c-68a2-4f15-a616-f0f2bf1f9f3f.png)

**Device Info (please complete the following information):**

 - Device: 老华为
 - Android Version:  7.0

**Application Info (please complete the following information):**

 - Version: latest
 - Apk File Name: cfa-2.5.4-foss-universal-release.apk
 - Distribution Channel: github release

**Additional context**
无

**Configure**
from url `https://cdn.jsdelivr.net/gh/ermaozi/get_subscribe/subscribe/clash.yml`

**Logs**
见上截图

**Comment by Mammoth777** [comment]
> 

请问你降级到哪个版本了?

**Comment by Schwarze-Katze** [comment]
刚刚通过取消系统wifi的代理解决了这个问题
