### ISSUE TITLE
[BUG]  新版本在三星s10上面 不能成功使用 

### ISSUE THREAD

**Issue by xiaospace1028** [Kr328/ClashForAndroid#1382]
新版本(2.5.4) premium版本在 三星手机s10上无法使用，但是2.5.3可以使用，查看日志就是展示 403应该是跳转了什么地址，麻烦看一下

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
