### ISSUE TITLE
[BUG] 无法使用

### ISSUE THREAD

**Issue by BTSLee** [Kr328/ClashForAndroid#1384]
**描述出现的错误**
连接后无法像以前一样使用

**如何复现该错误**
复现步骤:
1. ...[TCP] dial Teacat (match DomainKeyword/youtube) to m.youtube.com error: SH.teacat1.xyz:50056 connect error: dial tcp4 58.32.26.127:50056: i/o timeout
2. ...[TCP] dial Teacat (match DomainKeyword/github) to alive.github.com error: SH.teacat1.xyz:50056 connect error: dial tcp4 58.32.26.127:50056: i/o timeout[TCP] 127.0.0.1:44770 --> static.tieba.baidu.com match DomainKeyword(baidu) using DIRECT[TCP] 127.0.0.1:44774 --> m.hao123.com match GeoIP(CN) using DIRECT[TCP] 127.0.0.1:44760 --> static.tieba.baidu.com match DomainKeyword(baidu) using DIRECT[TCP] 127.0.0.1:44762 --> static.tieba.baidu.com match DomainKeyword(baidu) using DIRECT[TCP] 127.0.0.1:44756 --> static.tieba.baidu.com match DomainKeyword(baidu) using DIRECT[TCP] 127.0.0.1:44752 --> m.hao123.com match GeoIP(CN) using DIRECT[TCP] 127.0.0.1:44736 --> hdj.baidu.com match DomainKeyword(baidu) using DIRECT[TCP] 127.0.0.1:44746 --> shield.hao123.com match GeoIP(CN) using DIRECT[TCP] 127.0.0.1:44730 --> gss0.bdstatic.com match DomainSuffix(bdstatic.com) using DIRECT[TCP] 127.0.0.1:44724 --> dgss0.bdstatic.com match DomainSuffix(bdstatic.com) using DIRECT[TCP] 127.0.0.1:44734 --> m.hao123.com match GeoIP(CN) using DIRECT[TCP] 127.0.0.1:44714 --> hm.baidu.com match DomainKeyword(baidu) using DIRECT[TCP] 127.0.0.1:44712 --> hao123.baidu.com match DomainKeyword(baidu) using DIRECT[TCP] 127.0.0.1:44706 --> m.hao123.com match GeoIP(CN) using DIRECT[TCP] dial Teacat (match DomainKeyword/google) to geomobileservices-pa.googleapis.com error: SH.teacat1.xyz:50056 connect error: dial tcp4 58.32.26.127:50056: i/o timeout[TCP] dial Teacat (match DomainKeyword/google) to www.google.com error: SH.teacat1.xyz:50056 connect error: dial tcp4 58.32.26.127:50056: i/o timeout[TCP] 127.0.0.1:44698 --> www.hao123.com match GeoIP(CN) using DIRECT[APP] Logcat level: info
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```

![Screenshot_20220214-025545_Samsung Internet](https://user-images.githubusercontent.com/96232204/153770292-95051b1f-febb-4719-97dd-60b2802f18e0.jpg)
![Screenshot_20220214-025607_Clash for Android](https://user-images.githubusercontent.com/96232204/153770302-0caaa582-73b1-47fa-bf72-5b07eb10acac.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by BTSLee** [comment]
邮件已收到，谢谢
