### ISSUE TITLE
Updated ru (Russian) translation

### ISSUE THREAD

**Issue by forksus** [Kr328/ClashForAndroid#1385]
I have translated your application into `ru` (*Russian*). Here is the xml:[String123](https://www.upload.ee/files/13886024/Strings123.zip.html)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
