### ISSUE TITLE
[Feature Request] 开启app后自动更新订阅

### ISSUE THREAD

**Issue by wpzzz** [Kr328/ClashForAndroid#1387]
**功能描述**
请清晰的描述你想要的功能

目前只能设置每间隔多久更新订阅，但是时间短了影响服务器负载，时间长了导致数据更新不及时，建议添加一个默认推荐值，开启app后自动更新订阅

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
并不好界定 “启动 App" 时

1. 在进程创建时更新的话 在 Android 设计规范中 应用进程近会在系统启动后第一次启动时创建
2. 在主界面创建时更新 在魔改 ROM 中 应用的主界面几乎不会被销毁 因为在这些 ROM 中 应用的 Activity 从 所有 Task 中移除后会杀死进程
3. 在主界面显示时更新 在应用切换到后台后再切换回前台也会触发更新
