### ISSUE TITLE
1.1.2还是会掉vpn

### ISSUE THREAD

**Issue by poemsiu** [Kr328/ClashForAndroid#139]
具体表现为正常使用半天到一天左右，突然发现vpn掉了，cfa却还在运行中。

**Comment by poemsiu** [comment]
已经将cfa各种白名单和特赦了，手机是三星S9+系统10.0

**Comment by Kr328** [comment]
典型的被系统调度关闭 需要检查系统配置

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
