### ISSUE TITLE
[bug] clash(2.5.4) can not work with the same config file

### ISSUE THREAD

**Issue by flowercow** [Kr328/ClashForAndroid#1391]
**Describe the bug**
after upgrade to 2.5.4, clash can not work. while the same config file works fine with clash whose version below 2.5.4, such as 2.5.3

**To Reproduce**
1. upgrade to 2.5.4
2. run clash, the traffic can not be forward.

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
