### ISSUE TITLE
[BUG] same config file can not work with 2.5.4 version

### ISSUE THREAD

**Issue by flowercow** [Kr328/ClashForAndroid#1392]
**Describe the bug**
after upgrade to 2.5.4, clash can not work. while the same config file works fine with clash whose version below 2.5.4, such as 2.5.3

**To Reproduce**
1. upgrade to 2.5.4 version
2. run clash, and the traffic can not be forward as before.
3. 
4. 

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: [e.g. Pixel 4]
 - ROM: [e.g: AOSP]
 - ROM Version:
 - Android Version [e.g. 10]

**Application Info (please complete the following information):**

 - Version: [e.g. 1.1.10]
 - Apk File Name: [e.g. app-release-arm64-v8a.apk]
 - Distribution Channel: [e.g. Google Play]

**Additional context**

**Configure**
Paste configure file which **removed server info** 
```yaml
# paste here
```

**Logs**
Paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
