### ISSUE TITLE
[Feature Request] 希望可以对一些金融软件进行屏蔽

### ISSUE THREAD

**Issue by BayMRX** [Kr328/ClashForAndroid#1398]
**功能描述**
目前在Clash代理处于运行状态并打开“自动路由系统流量”开关时，部分银行金融软件不能使用，比如“建行生活”APP直接无法打开，会提示不提示使用VPN访问，再比如“数字人民币”APP，无法进行登录，会要求关闭代理十分钟后在操作。并且 尽管在 设置-网络访问控制模式 选择“仅允许已选择的应用”，“访问应用控制包列表”没有选中相关APP，还是会有这些提示。
![S20219-22200874](https://user-images.githubusercontent.com/41069495/154805793-0a0aeee3-82a3-4670-b69c-f528dc6bb771.png)
![-5aaf7be8020bd6e4(1) (1)](https://user-images.githubusercontent.com/41069495/154805792-123b1fa4-d658-4918-bae8-57795abfd6f8.png)

**描述你希望的实现方式**
我希望可以通过列表选择访问控制，实现真正意义上的VPN访问控制

**附加信息**
目前我使用的是魅族手机，在它的VPN设置里面有一个“VPN智能联网”，在这里对VPN访问进行控制可以实现上述功能（这与Clash里面的“自动路由系统流量”开关相冲突）。但美中不足的是在系统内的这个应用列表并不全面，很多如Google Play等应用不会显示，google的相关系统服务也不会显示，造成很多应用没法正常代理。
最后希望这个问题可以得到良好解决（来回开关Clash服务太痛苦辣，还要干等十分钟🥺）

**Comment by Kr328** [comment]
做不到

这些应用通过系统 API 获取当前设备网络连接 VPN 并不能改变这些 API 的行为

**Comment by jwstaceyOvO** [comment]
@Kr328 应该可以实现，v2rayNG路由设置绕过局域网和大陆时打开银行app都不会出现弹窗，而Clash即使域名走直连也会弹窗
