### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Rhskyy** [Kr328/ClashForAndroid#1399]
**描述出现的错误**
输入新的订阅链接显示下载错误
以前的官网也用不了了

**如何复现该错误**
复现步骤:
1. 复制此链接https://api.ikuuu.science/link/KeCjnsqqNqXEDBKY?sub=3&extend=1
2. 配置中导入
3. 保存

**预期行为**
希望能解决此问题，我新手也不知道该说什么

**屏幕截图**

https://user-images.githubusercontent.com/100061128/154830983-47d060c1-3c4c-4a65-b9b8-31b6862e80d6.mp4

**设备信息 (请完成以下信息):**
 - 机型: [OPPO k7]
 - 系统/ROM: [COLOR OS ]
 - Android 版本 [11]
 - ROM版本 [v11.1]

**应用信息**
 - 版本: [2.1.6]
 - 安装包文件名称[没存]
 - 应用来源: [别人发给我的]

**附加信息**
以前的香港节点不能用了

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**

<
[2021-11-27 17_18_00.log.txt](https://github.com/Kr328/ClashForAndroid/files/8103506/2021-11-27.17_18_00.log.txt)
>
```

#

**Comment by Rhskyy** [comment]
小白用户，不太知道该怎么说

**Comment by Kr328** [comment]
我也不知道该怎么说 自己找你的卖家去

**Comment by MreDiaos** [comment]
看错误提示貌似显示的是你的订阅链接里包含的配置代码有问题

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Rhskyy** [comment]
明白了明白了，谢谢啊



| |
猴王
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月20日 14:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Kr328/ClashForAndroid] [BUG] (Issue #1399) |

Closed #1399.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
