### ISSUE TITLE
'Compiler not found' while building

### ISSUE THREAD

**Issue by nncy** [Kr328/ClashForAndroid#14]
按照readme 安装了 SDK,NDK,Golang, 执行`./gradlew build`后， 有如下error:
`Execution failed for task ':core:golangBuildForarm64v8a'.`
`> Compiler not found`

系统：Arch Linux
Go version: go1.13.4 linux/amd64

**Comment by Kr328** [comment]
认真读一遍 README

**Comment by nncy** [comment]
我有按照 README 来进行构建：
先更新子模块==>安装SDK NDK Golang ==> 指定SDK NDK的目录 ==> cp google-service.json ==> 最后build
是按照这个顺序来的
