### ISSUE TITLE
几点使用习惯修改想法

### ISSUE THREAD

**Issue by ODBLK** [Kr328/ClashForAndroid#140]
1：上传下载的顺序：能不能把下载放在前面，每次都会优先看前面的
2：通知栏提醒：可不可以显示代理名而不是配置名
3：通知栏快捷键：类似SSR可以快速切换线路
4：自启动：这个我还没成功过

可能比较没用，麻烦作者大大了

**Comment by Kr328** [comment]
1. 没意义
2. https://github.com/Kr328/ClashForAndroid/issues/138#issuecomment-589962295
3. https://github.com/Kr328/ClashForAndroid/issues/138#issuecomment-589962295
4. 检查你自己的系统限制
