### ISSUE TITLE
建议添加显示剩余流量以及能够排序订阅的功能。

### ISSUE THREAD

**Issue by kongkongl** [Kr328/ClashForAndroid#1400]
### 功能描述

你好，请问是否可以添加以下两个功能:
1.clash安卓端不可以显示剩余流量，只能自己去机场官网或者电报里面查，是否可以像电脑端一样，增加流量显示功能。
2.订阅的节点不可以自由的排序，有时整理起来很麻烦，希望可以改动为可以拖拽节点订阅，进行自由排序。
十分感谢开发者，谢谢。

**Comment by kongkongl** [comment]
> ### 功能描述
> 你好，请问是否可以添加以下两个功能: 1.clash安卓端不可以显示剩余流量，只能自己去机场官网或者电报里面查，是否可以像电脑端一样，增加流量显示功能。 2.订阅的节点不可以自由的排序，有时整理起来很麻烦，希望可以改动为可以拖拽节点订阅，进行自由排序。 十分感谢开发者，谢谢。
> 
> ### 附加信息
> _No response_

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
