### ISSUE TITLE
[Feature Request] 安卓12系统无法正常代理

### ISSUE THREAD

**Issue by Frankenstein528** [Kr328/ClashForAndroid#1407]
### 功能描述

安卓12无法正常代理

**Comment by xuhaoyang** [comment]
请google一些提问的艺术。同时反馈问题的模板都有了，为何不填？

![Screenshot_2022-02-28-00-01-43-260_com.android.settings.jpg](https://user-images.githubusercontent.com/1927125/155889926-96c6181c-1e34-44d6-a57c-2eb26bcce77d.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
