### ISSUE TITLE
无法使用google play市场更新下载[BUG] 

### ISSUE THREAD

**Issue by FrankCreen** [Kr328/ClashForAndroid#1408]
### 描述此错误

无法使用google play市场更新下载

### 如何复现该错误

步骤 1: 启动clash服务
步骤 2: 打开google play
步骤 3: 下载任意软件。长时间进度条旋转无反应。切换至v2rayNG可以正常下载更新。
...

### 设备信息

- 机型:oppo r17
- 系统类型:android
- Android 版本:10

### 应用信息

- 版本:17.9.17
- 安装包文件名:
- 应用来源:

### 配置文件

[rules.txt](https://github.com/Kr328/ClashForAndroid/files/8150732/rules.txt)

### 日志

# Logcat on 2022-02-28 13:03:49
13:03:49 |INFO| [TCP] 172.31.255.253:40164 --> alt4-mtalk.google.com match DomainKeyword(google) using 代理[🇹🇼 台湾II]
13:03:50 |INFO| [TCP] 172.31.255.253:41854 --> android.apis.google.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:52 |INFO| [TCP] 172.31.255.253:45210 --> tools.3g.qq.com match IPCIDR(111.0.0.0/10) using DIRECT
13:03:52 |INFO| [TCP] 172.31.255.253:45218 --> tools.3g.qq.com match IPCIDR(111.0.0.0/10) using DIRECT
13:03:57 |INFO| [TCP] 172.31.255.253:49070 --> 120.241.190.109 match IPCIDR(120.192.0.0/10) using DIRECT
13:03:58 |INFO| [TCP] 172.31.255.253:45902 --> play-fe.googleapis.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:58 |INFO| [TCP] 172.31.255.253:45908 --> play-fe.googleapis.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:58 |INFO| [TCP] 172.31.255.253:41036 --> update.googleapis.com match DomainKeyword(google) using 代理[🇹🇼 台湾II]
13:03:59 |INFO| [TCP] 172.31.255.253:41040 --> update.googleapis.com match DomainKeyword(google) using 代理[🇹🇼 台湾II]
13:03:59 |INFO| [TCP] 172.31.255.253:45922 --> play-fe.googleapis.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:59 |INFO| [UDP] 172.31.255.253:37472 --> play-fe.googleapis.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:59 |INFO| [UDP] 172.31.255.253:37472 --> play-fe.googleapis.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:59 |INFO| [TCP] 172.31.255.253:43662 --> lh3.ggpht.com match DomainSuffix(ggpht.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:59 |INFO| [TCP] 172.31.255.253:40226 --> edgedl.me.gvt1.com match DomainSuffix(gvt1.com) using 代理[🇹🇼 台湾II]
13:03:59 |INFO| [TCP] 172.31.255.253:43668 --> lh3.ggpht.com match DomainSuffix(ggpht.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:59 |INFO| [TCP] 172.31.255.253:43672 --> lh3.ggpht.com match DomainSuffix(ggpht.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:03:59 |INFO| [TCP] 172.31.255.253:43666 --> lh3.ggpht.com match DomainSuffix(ggpht.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:00 |INFO| [TCP] 172.31.255.253:43682 --> lh3.ggpht.com match DomainSuffix(ggpht.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:00 |INFO| [TCP] 172.31.255.253:43686 --> lh3.ggpht.com match DomainSuffix(ggpht.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:00 |INFO| [UDP] 172.31.255.253:41186 --> lh3.ggpht.com match DomainSuffix(ggpht.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:00 |INFO| [UDP] 172.31.255.253:37472 --> play-fe.googleapis.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:00 |INFO| [UDP] 172.31.255.253:41186 --> lh3.ggpht.com match DomainSuffix(ggpht.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:00 |INFO| [UDP] 172.31.255.253:44360 --> update.googleapis.com match DomainKeyword(google) using 代理[🇹🇼 台湾II]
13:04:00 |INFO| [UDP] 172.31.255.253:44360 --> update.googleapis.com match DomainKeyword(google) using 代理[🇹🇼 台湾II]
13:04:00 |INFO| [UDP] 172.31.255.253:41221 --> play-lh.googleusercontent.com match IPCIDR(216.58.192.0/18) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:00 |INFO| [UDP] 172.31.255.253:37472 --> play-fe.googleapis.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:01 |INFO| [UDP] 172.31.255.253:44360 --> update.googleapis.com match DomainKeyword(google) using 代理[🇹🇼 台湾II]
13:04:02 |INFO| [TCP] 172.31.255.253:46134 --> l1.xfinfr.com match IPCIDR(114.118.0.0/16) using DIRECT
13:04:11 |INFO| [TCP] 172.31.255.253:46240 --> beacons.gvt2.com match DomainSuffix(gvt2.com) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:14 |INFO| [TCP] 172.31.255.253:49668 --> play.googleapis.com match IPCIDR(142.250.0.0/15) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:15 |INFO| [TCP] 172.31.255.253:39740 --> connectivitycheck.gstatic.com match DomainSuffix(gstatic.com) using 代理[🇹🇼 台湾II]
13:04:16 |INFO| [TCP] 172.31.255.253:46264 --> services.googleapis.cn match DomainKeyword(google) using 代理[🇹🇼 台湾II]
13:04:16 |INFO| [TCP] 172.31.255.253:38822 --> 172.217.160.74 match IPCIDR(172.217.0.0/16) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:16 |INFO| [TCP] 172.31.255.253:37418 --> rr4---sn-ipoxu-un5y.xn--ngstr-lra8j.com match DomainSuffix(xn--ngstr-lra8j.com) using 代理[🇹🇼 台湾II]
13:04:17 |INFO| [TCP] 172.31.255.253:48646 --> infinitedata-pa.googleapis.com match IPCIDR(172.217.0.0/16) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:18 |INFO| [TCP] 172.31.255.253:45104 --> 203.119.144.239 match IPCIDR(203.119.128.0/17) using DIRECT
13:04:18 |INFO| [TCP] <nil>: --> sub.wallless.cloud match Match() using 规则外路由选择[🇹🇼 台湾II]
13:04:19 |INFO| [TCP] 172.31.255.253:48660 --> infinitedata-pa.googleapis.com match IPCIDR(172.217.0.0/16) using 油管[🇭🇰 香港II 支持Netflix非自制]
13:04:19 |INFO| [TCP] 172.31.255.253:46302 --> services.googleapis.cn match DomainKeyword(google) using 代理[🇹🇼 台湾II]
13:04:26 |INFO| [TCP] 172.31.255.253:45368 --> 221.181.99.20 match IPCIDR(221.180.0.0/14) using DIRECT
13:04:30 |INFO| [TCP] 172.31.255.253:44098 --> 120.204.207.26 match IPCIDR(120.192.0.0/10) using DIRECT
13:04:30 |INFO| [TCP] 172.31.255.253:38566 --> 183.192.169.17 match IPCIDR(183.192.0.0/10) using DIRECT
13:04:30 |INFO| [TCP] 172.31.255.253:38570 --> 183.192.169.17 match IPCIDR(183.192.0.0/10) using DIRECT
13:04:31 |INFO| [TCP] 172.31.255.253:38574 --> 183.192.169.17 match IPCIDR(183.192.0.0/10) using DIRECT
13:04:31 |INFO| [TCP] 172.31.255.253:38578 --> 183.192.169.17 match IPCIDR(183.192.0.0/10) using DIRECT

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
