### ISSUE TITLE
Import From URL 挂了

### ISSUE THREAD

**Issue by jmireles7** [Kr328/ClashForAndroid#141]
1.0.32 是可以的。
1.1.1 和 1.1.2 都无法从URL导入了。

**Comment by Kr328** [comment]
1. 日志?
2. 错误提示?

**Comment by jmireles7** [comment]
@Kr328 日志捕捉没有任何东西
网页点击链接就像没有安装app一样，app没有任何反应
换装1.0.36点一下就会弹出app

**Comment by Kr328** [comment]
@jmireles7 当前版本还没有添加快速导入功能

**Comment by jmireles7** [comment]
@Kr328 
好吧，感谢大佬的付出！关于节点名字，我只想说：一行一个解决所有问题～～不如加个布局选择😂

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
