### ISSUE TITLE
[BUG] 不支持multi user

### ISSUE THREAD

**Issue by w3AD4y-r5** [Kr328/ClashForAndroid#1410]
### 描述此错误

无法代理系统多开的应用（微信、Google Play等）

### 如何复现该错误

步骤 1: 多开微信、Google Play(系统自带多开功能，原理大概为工作资料，adb发现2个user，id分别为0和128)
步骤 2: Clash仅允许已选择的应用，勾选微信、Google Play(只能看到user_id为0的原应用，没有发现多开应用)
步骤 3: 只有原应用能使用代理，多开的应用无法使用代理

### 设备信息

- 机型:Mate 10
- 系统类型:Harmony
- Android 版本:10

### 应用信息

- 版本:2.5.4-premium
- 安装包文件名: cfa-2.5.4-premium-arm64-v8a-release.apk
- 应用来源:Google Play

### 配置文件

与配置文件无关

### 日志

log level为info，多开应用联网，未捕获到任何日志。

**Comment by Kr328** [comment]
Google 就是这样设计的 每个用户独立 VPN

**Comment by Kr328** [comment]
@llwwbb 我只能说我做不到跨越用户开 VPN

如果你有办法欢迎开启 Pull Request
