### ISSUE TITLE
添加首页的当前线路显示功能。

### ISSUE THREAD

**Issue by oopsea** [Kr328/ClashForAndroid#1411]
### 功能描述

能否在首页这个位置，显示当前使用的线路。
![Uploading IMG_20220301_161538.jpg…]()

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
