### ISSUE TITLE
[Feature Request] 添加首页的当前线路显示

### ISSUE THREAD

**Issue by oopsea** [Kr328/ClashForAndroid#1412]
### 功能描述

希望能在首页这个位置，显示当前使用的线路。
![IMG_20220301_161538](https://user-images.githubusercontent.com/25172023/156131483-1121925e-b58b-4bf6-b3f1-d41a5f68d14f.jpg)

**Comment by Kr328** [comment]
输出节点根据规则决定 而没有明确的 "出口路线"
