### ISSUE TITLE
[BUG]  这可能不是bug 但是我的手机不断向某个地址发起请求

### ISSUE THREAD

**Issue by TianYa-Q** [Kr328/ClashForAndroid#1413]
### 描述此错误

当我启动代理后 在日志当中 显示不断向此地址发送大流量请求 abq88188.com
但是奇怪的是 当我关闭代理 或使用其他代理软件时 并不会出现大流量请求
手机是小米 这个域名似乎不隶属于某个公司 不知道大家有没有遇到过这个问题

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型: 小米11ultra
- 系统类型:
- Android 版本:

### 应用信息

- 版本: 2.5.4-premium
- 安装包文件名:
- 应用来源: Google Play

### 配置文件

null

### 日志

[TCP] 104.37.172.18:44274 --> www.abq88188.net:80 match Match() using

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
