### ISSUE TITLE
[Feature Request] hope to add Parser function same like the CFW

### ISSUE THREAD

**Issue by alonginwind** [Kr328/ClashForAndroid#1416]
### Feature Description

In CFW, we can add self rules through Parser, with which self rules won't be covered when reflesh the sub.

**Comment by Kr328** [comment]
parser require a script runtime. it is toooooooooooooo huge for clash for android

**Comment by yebingo** [comment]
@Kr328 Or is there any other way to achieve this functionality?

**Comment by zjplab** [comment]
https://github.com/zjplab/ext-clash-parser 我的项目可以部署在Google Cloud Function上, 用url调用方式可以获取parsed的结果,前提是自己写的js parser保存在一个固定的github链接上

**Comment by zjplab** [comment]
每个月的费用大概是$0.01~$0.02甚至更低

**Comment by amorphobia** [comment]
> parser require a script runtime. it is toooooooooooooo huge for clash for android

Why not just generate a local static yaml config file on saving parsers? There's no necessary to actual parse it unless updating profile or changing parsers.

**Comment by Kr328** [comment]
@amorphobia It is require embed a nodejs runtime in Clash for Android with 13.2M compressed size and 55.3M installed size in arch linux. It is tooooooooooooooo huge for a Android App.

**Comment by amorphobia** [comment]
> @amorphobia It is require embed a nodejs runtime with 13.2M compressed size and 55.3M installed size in arch linux. It is tooooooooooooooo huge for a Android App.

Thanks. Got your point. Then a web app might be a workaround.
