### ISSUE TITLE
[Feature Request] 希望hosts规则优先级比match DomainSuffix高

### ISSUE THREAD

**Issue by HITers2018** [Kr328/ClashForAndroid#1418]
### 功能描述

例如，订阅的规则文件通过match DomainSuffix使qq.com走direct，此时用户通过覆写，增添的127.0.0.1 wsa.wxs.qq.com无法起到拦截功能，所以希望能提高用户host规则的优先级，即使订阅的规则里面选择放行qq.com，但是用户的host仍能发挥作用。

**Comment by Kr328** [comment]
hosts 并不是规则

hosts 本身仅仅是在发生域名解析时将解析结果修改为某个 IP

hosts 并没有和规则有优先级之说

**Comment by HITers2018** [comment]
> hosts 并不是规则
> 
> hosts 本身仅仅是在发生域名解析时将解析结果修改为某个 IP
> 
> hosts 并没有和规则有优先级之说

我的意思是，如果订阅文件中对域名放行了(direct)，我希望，clash覆写加了的对该域名的拦截规则(127.0.0.1无效，等于拦截)，只是希望把host当广告拦截用，现在的clash，订阅文件只要放行，就拦不住。

**Comment by EKyero** [comment]
@HITers2018 你这用法有点扭曲，明明可以把需要拦截的写入规则

**Comment by Kr328** [comment]
@HITers2018 应用的某项功能仅仅保证与它的实现目标(在这里是改变 dns 解析器行为)的用例行为正确 
其他非实现目标的用例不予支持

**Comment by HITers2018** [comment]
> @HITers2018 你这用法有点扭曲，明明可以把需要拦截的写入规则

但是我订阅了服务商的自带的规则(经常更新)，那边放行了整个qq.com，把wxs.qq.com这个广告域也放行了，我自己不方便改，除非变成本地文件，但是这样每次都得改，所以我希望用户覆写的host拦截优先级高于订阅规则。

**Comment by Kr328** [comment]
@HITers2018 你完全可以手写配置文件使用 proxy providers 来订阅远程配置

就能有自己的规则策略和远程配置
