### ISSUE TITLE
各个版本什么区别，有没说明？[Feature Request] 

### ISSUE THREAD

**Issue by vaguetock** [Kr328/ClashForAndroid#1419]
### 功能描述

3q.

### 附加信息

![screenshot-github com-2022 03 06-02_00_44](https://user-images.githubusercontent.com/101015778/156894958-1d28f7c9-4b8b-41e8-9629-10d97cb71e90.png)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
