### ISSUE TITLE
[BUG] 讯飞输入法提示连接被拒绝

### ISSUE THREAD

**Issue by wanglongbiao** [Kr328/ClashForAndroid#1421]
### 描述此错误

你好，我的版本是从 google play 上安装的最新版，我用的规则是网上找到一个白名单，规则应该没问题，我用了两三年了，当我在手机上使用这个白名单的时候，使用讯飞输入法的语音输入有以下错误日志：

`[TCP] dial DIRECT (match RuleSet/cncidr) to 120.92.238.23:42301 error: dial tcp4 120.92.238.23:42301: connect: connection refused`

我看这个规则也走了 direct 没问题啊，不知道为啥最后连接被拒绝，难道是因为应该是 udp？

### 如何复现该错误

步骤 1: 使用规则 https://github.com/Loyalsoldier/clash-rules
步骤 2: 将规则应用到 Android 版本，开启全局代理
步骤 3: 使用讯飞输入法的语音输入，结果报错
...

### 设备信息

- 机型: 红米 k40
- 系统类型: miui
- Android 版本: 12

### 应用信息

- 版本:最新版
- 应用来源: Google Play

### 配置文件

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - DOMAIN-SUFFIX,googleapis.cn,PROXY
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  #- RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

### 日志

[TCP] dial DIRECT (match RuleSet/cncidr) to 120.92.238.23:42301 error: dial tcp4 120.92.238.23:42301: connect: connection refused

**Comment by Kr328** [comment]
@wanglongbiao 日志填全部 版本不要所谓最新版 没意义

**Comment by akw5454521** [comment]
为什么不排除这个app呢
