### ISSUE TITLE
[Feature Request] 更新订阅逻辑优化

### ISSUE THREAD

**Issue by PeterHgg** [Kr328/ClashForAndroid#1423]
### 功能描述

若节点全部失效，而配置文件规则里使订阅链接走代理，则无法更新订阅。若将更新订阅的行为单独设置为：先走直连再尝试走能用的代理（可以考虑根据延迟排序节点，依次尝试更新订阅），无视clash配置文件规则对订阅链接的影响，则提高了更新订阅成功率

### 附加信息

还一点想问，若自动更新设置为30分钟，是指的clash连续运行30分钟，则更新订阅，还是距离上次更新时间超过30分钟则更新订阅。我设置未24h一更新，然后一直没管更新，后台没保活，结果去看配置文件显示“4天前更新”。所以有点疑惑。

**Comment by Kr328** [comment]
@PeterHgg 请自行关闭代理更新

**Comment by Kr328** [comment]
@PeterHgg 自动更新根据上次更新时间确定 且由 Android 系统计时 应用在被 Android 系统限制后也不会完成更新

**Comment by PeterHgg** [comment]
> @PeterHgg 请自行关闭代理更新

现在是这么弄的，就是想自动更新订阅和多路线更新订阅结合，更能无感使用，无脑打开开关就能用的体验

**Comment by Kr328** [comment]
@PeterHgg 在使用 ClashForAndroid 时请带上脑子 我不想为次付出太多的维护成本

你也可以用规则决定某个订阅地址是否使用代理

**Comment by PeterHgg** [comment]
> @PeterHgg 在使用 ClashForAndroid 时请带上脑子 我不想为次付出太多的维护成本
> 
> 你也可以用规则决定某个订阅地址是否使用代理

因为使用公共订阅转换的人不在少数，他们控制不了规则，且每次更新都会覆盖规则。所以提此需求，其实简化一下，加一个东西就行：更新前先走直连，其余不动，没有想给您增加很多维护成本。

**Comment by Kr328** [comment]
@PeterHgg 你知道在现有架构下实现这个功能的难度吗 如果你认为很简单 请使用 Pull Request 帮助我完成这个功能

**Comment by PeterHgg** [comment]
> @PeterHgg 你知道在现有架构下实现这个功能的难度吗 如果你认为很简单 请使用 Pull Request 帮助我完成这个功能

用户角度提的优化建议，现在知道情况了，不再打扰。若有冒犯，我表示抱歉。

**Comment by EKyero** [comment]
@PeterHgg 如果你说得订阅转换是subconverter，怎么可能控制不了规则？
写一个适合自己的文件并不难

**Comment by PeterHgg** [comment]
> @PeterHgg 如果你说得订阅转换是subconverter，怎么可能控制不了规则？ 写一个适合自己的文件并不难

自建可以，公用的subconverter不行吧

**Comment by EKyero** [comment]
> > @PeterHgg 如果你说得订阅转换是subconverter，怎么可能控制不了规则？ 写一个适合自己的文件并不难
> 
> 自建可以，公用的subconverter不行吧

为什么不行？

**Comment by PeterHgg** [comment]
> > > @PeterHgg 如果你说得订阅转换是subconverter，怎么可能控制不了规则？ 写一个适合自己的文件并不难
> > 
> > 
> > 自建可以，公用的subconverter不行吧
> 
> 为什么不行？

感谢提醒，一直是无脑用的公共的sub-web可选的那几个固定的，没看subconverter的文档

**Comment by xgdgsc** [comment]
想问下这个难度在哪，更新当前订阅失败后自动关闭代理尝试更新不行吗？

**Comment by xgdgsc** [comment]
是的, 我是一直用的仅选中的应用通过vpn的, 这个逻辑对我毫无影响, 反而老更新失败对我影响很大. 大多数人是用的默认的全局代理吗?

**Comment by MXS2514** [comment]
安卓是不是不能实现类似windows那种：不通过代理更新

**Comment by EKyero** [comment]
> 安卓是不是不能实现类似windows那种：不通过代理更新

不清楚你用的具体什么软件，但 Clash for Windows 和 ClashX Pro 在开启 System Proxy 或 TUN 的时候均会通过代理更新。
唯一有特例的情况是，Provider。因为 Provider 的更新是由 Clash Core 控制的。

**Comment by xgdgsc** [comment]
Windows 我一般不开系统代理只用浏览器插件, 所以体验就是Windows没更新失败过,android老失败
