### ISSUE TITLE
[Feature Request] 请问如何在Assets中根据自己的手机幸好选取一个合适的版本啊

### ISSUE THREAD

**Issue by EricKani** [Kr328/ClashForAndroid#1424]
### 功能描述

相同版本下有很多安装包，请问有哪些区别呀

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
