### ISSUE TITLE
短链接失效怎么处理？

### ISSUE THREAD

**Issue by zL6634** [Kr328/ClashForAndroid#1427]
### 功能描述

你好！2.1.6版本clash for andriod，原来的节点托管地址短链接失效了，但是手机上节点还能使用，请问这些节点保存在手机什么位置？还能转移到其它设备上吗？谢谢

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
