### ISSUE TITLE
[Feature Request] 短链接失效

### ISSUE THREAD

**Issue by zL6634** [Kr328/ClashForAndroid#1428]
### 功能描述

你好！2.1.6版本clash for andriod，原来的节点托管地址短链接失效了，但是手机上节点还能使用，请问这些节点保存在手机什么位置？还能转移到其它设备上吗？谢谢

**Comment by AkariiinMKII** [comment]
export plz

**Comment by zL6634** [comment]
>？？？

**Comment by zL6634** [comment]
> 出口请
这些节点是别人给的，现在托管地址链接失效了，手机上还正常使用。clash版本是2.1.6，没有导出功能。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
