### ISSUE TITLE
想了解目前 1.1.2 版本是如何修改配置文件的？

### ISSUE THREAD

**Issue by ShadowLyin** [Kr328/ClashForAndroid#143]
目前最新版我看到开启 VPN Service 后有两个选项，分别是`追加系统 DNS` 与 `DNS 配置覆盖`，我想问下修改之后的 Clash 配置文件中的 DNS 字段是怎么样的？
另外在使用仅代理模式时，Clash for Android 是否会修改配置文件？

**Comment by Kr328** [comment]
@ShadowLyin 1. 不改动文件 仅仅在内存中修改 改的东西具体读源码
2. 放在 VpnService 下的 东西 当然只在 VPN 下生效

**Comment by ShadowLyin** [comment]
了解了，谢谢解答
