### ISSUE TITLE
[BUG] rules貌似不支持通配符

### ISSUE THREAD

**Issue by d6jrsj22** [Kr328/ClashForAndroid#1430]
### 描述此错误

我在rules里，尝试匹配
 alt1-mtalk.google.com
 alt2-mtalk.google.com
 alt3-mtalk.google.com
 alt4-mtalk.google.com
 alt5-mtalk.google.com
 alt6-mtalk.google.com
  xyz.gvt1.com
  zyx.gvt2.com

填写以下规则
  \- DOMAIN-KEYWORD,mtalk.google.com
  \- DOMAIN, *mtalk.google.com
  \- DOMAIN, \*.gvt\*.com

均匹配不到

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型: huawei p50
- 系统类型:  emui
- Android 版本: android 11

### 应用信息

- 版本: 2.5.4-premium
- 安装包文件名: cfa-2.5.4-premium-arm64-v8a-release.apk
- 应用来源: Google Play

### 配置文件

rules:
  - DOMAIN-KEYWORD,mtalk.google.com
  - DOMAIN, alt*-mtalk.google.com  

### 日志

none

**Comment by Kr328** [comment]
上游请

**Comment by akw5454521** [comment]
FCM网址不就10来个嘛，复制粘贴几下完事了

**Comment by akw5454521** [comment]
FCM一共就10个地址吧
