### ISSUE TITLE
[BUG]不当电源管理,导致不能使用clash

### ISSUE THREAD

**Issue by 57SSG** [Kr328/ClashForAndroid#1431]
### 描述此错误

在应用耗电管理中,关闭了clash的后台活动.导致在开启clash后,只能使用几秒,随后提示无网络

### 如何复现该错误

步骤 1: 打开设置
步骤 2: 进入电源管理
步骤 3: 进入clash应用耗电详情,运行后台活动

### 设备信息

- 机型:HONOR X20SE
- 系统类型:Magic UI
- Android 版本:4.1

### 应用信息

- 版本:2.5.4
- 安装包文件名:cfa-2.5. 4-premium-universal-release
- 应用来源:https://github.com/Kr328/ClashForAndroid/releases/tag/v2.5.4

### 配置文件

无

### 日志

无

**Comment by AkariiinMKII** [comment]
@57SSG 建议冲进荣耀开发部把刀架主管脖子上

**Comment by Kr328** [comment]
那不然呢
