### ISSUE TITLE
[BUG] 关于foss和premium版本的区别

### ISSUE THREAD

**Issue by Tesoro1116** [Kr328/ClashForAndroid#1432]
### 描述此错误

用了很久了，我一直很好奇foss版本和premium版本有什么区别。

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:LG V30
- 系统类型:MIUI 12.2
- Android 版本:10

### 应用信息

- 版本:2.5.4.foss
- 安装包文件名:cfa-2.5.4-foss-universal-release.apk
- 应用来源:Releases

### 配置文件

None

### 日志

None

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
