### ISSUE TITLE
[BUG] 账号失效

### ISSUE THREAD

**Issue by M-Tis** [Kr328/ClashForAndroid#1435]

**Comment by M-Tis** [comment]
我的账号还有2个月左右的基础套餐

**Comment by EKyero** [comment]
@M-Tis

**Comment by EKyero** [comment]
![](https://i.imgur.com/QDd9N44.jpg)

**Comment by M-Tis** [comment]
> ![](https://camo.githubusercontent.com/99f4e420bc6dc428a42dc2c9d55988f5071bdc5bbfd373eb5ec380423e9c35fa/68747470733a2f2f692e696d6775722e636f6d2f514464394e34342e6a7067)

抱歉，已编辑
