### ISSUE TITLE
Request Support VPN hotspot and SNI or request host support 

### ISSUE THREAD

**Issue by Jeffeditae** [Kr328/ClashForAndroid#1437]
### Feature Description

Hi Clash For Android i have a AOSP rom support VPN hotspot 
![Screenshot_20220321-224408_Cài đặt](https://user-images.githubusercontent.com/39546317/159406075-79504543-97c5-499e-944a-1588459226e1.png)
And i don't know why V2rayN work but Clash For Android not work i wish clash for support this.
And Clash with support add Sni snd request host manual to us can custom the thing

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
