### ISSUE TITLE
[Feature Request] Request Support VPN hotspot and SNI or request host support

### ISSUE THREAD

**Issue by Jeffeditae** [Kr328/ClashForAndroid#1438]
### Feature Description

Hi Clash For Android i have a AOSP rom support VPN hotspot
![Screenshot_20220321-224408_Cài đặt](https://user-images.githubusercontent.com/39546317/159406506-be1f93a4-f243-4e37-9be1-1154388cabad.png)

And i don't know why V2rayN work but Clash For Android not work i wish clash for support this.
And Clash can support add Sni and request host manual to us can custom the things please 🥺.

**Comment by Kr328** [comment]
it not a basic aosp feature

**Comment by EKyero** [comment]
![](https://i.imgur.com/9Pxn2Nu.png)
