### ISSUE TITLE
Clash For Android 能否提供了 Web Dashboard 接口

### ISSUE THREAD

**Issue by HYBB-rash** [Kr328/ClashForAndroid#1441]
### 功能描述

# Web Dashboard 管理面板

起因是我想把一个闲置不用的旧安卓机作为一个代理服务器，上面挂一个 clash ，我的所有设备指向这个手机的 clash 端口。

局域网内的链接是没有问题的，但是我希望我能够通过 web 界面直接管理手机上的连接配置，现阶段 clash for android 是否提供了这样的功能？

如果有，能否指一下北，我去自己配置一下，如果没有，未来有考虑加上这个 web 控制功能么？

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
