### ISSUE TITLE
[BUG] libclash.h' file not found

### ISSUE THREAD

**Issue by gmingrui** [Kr328/ClashForAndroid#1442]
### 描述此错误

打包时报标题写出的错误，求大佬提供下解决方案。。。

### 如何复现该错误

as正常打包时报错  libclash.h file not found

### 设备信息

- 机型: none
- 系统类型:none
- Android 版本:none

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

 libclash.h file not found

### 日志

111

**Comment by Kr328** [comment]
#1268

**Comment by gmingrui** [comment]
@Kr328 看过了。。但是还是没解决，我有给你发邮件，可以回复下解决方案吗

**Comment by gmingrui** [comment]
Hi,i just checked the +1268 but also cloud not fix. Could u pls send me any
plan? Thank you.

Kr328 ***@***.***> 于2022年3月26日周六 21:37写道：

**Comment by Kr328** [comment]
@gmingrui 请自行解决 我不对任何编译提供帮助 因为 Github Action 里存在能够正确编译的脚本

**Comment by gmingrui** [comment]
@Kr328 好的，我再研究一下，但是想确认下这个 libclash.h 的库确定可以导入吗？
