### ISSUE TITLE
[BUG] log 信息中显示来源为 "by -1[]"

### ISSUE THREAD

**Issue by Konano** [Kr328/ClashForAndroid#1445]
### 描述此错误

一开 ClashAndroud 就疯狂访问某些奇怪的网站，还是一秒 n 次的那种，想通过看 log 排查问题发现来源居然是 -1，不知道是什么情况……

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型: Honor 20 Pro
- 系统类型: HarmonyOS
- Android 版本: 10

### 应用信息

- 版本: 2.5.4-premium
- 安装包文件名:
- 应用来源: Google Play

### 配置文件

https://pastebin.ubuntu.com/p/r7rNnkf97F/

### 日志

日志过于巨大……

### 屏幕截图

![image](https://user-images.githubusercontent.com/22500116/160326733-d1bdd301-1d39-4b1b-a644-c294f1eb5b3a.png)

**Comment by Kr328** [comment]
配置文件请

**Comment by Konano** [comment]
配置文件已经更新

**Comment by Kr328** [comment]
去到 覆写 把 mixed-port 关掉试试

**Comment by Konano** [comment]
> 去到 覆写 把 mixed-port 关掉试试

不知道怎么关闭，所以在 覆写 那里把 mixed-port 改成 7891，情况有所好转

所以这些访问都是来自公网吗？（连了学校的 WiFi 的情况下的确有公网 IP 来着）

**Comment by Kr328** [comment]
填 0 是关闭

不一定来自公网 也可能是华为设备的网络协议栈存在问题 如果可以 使用 ROOT 运行 `tcpdump -i tun0 -w /sdcard/dump.pcap` 来捕获与 clash 的 tun 有关的数据包

**Comment by Konano** [comment]
了解，我目前把 allow-lan 给关了，mixed-port 恢复到 7890 也没问题了，请求的确来自公网。目测是被扫端口并被滥用了。

机场给的默认配置文件有毒……
