### ISSUE TITLE
[BUG]  Wechat connect with PROXY always

### ISSUE THREAD

**Issue by bobby091983** [Kr328/ClashForAndroid#1449]
### 描述此错误

I have set the mode to RULE , but I notice Wechat is connecting via PROXY instead of DIRECT. Is there any way to fix it?

### 如何复现该错误

Step 1: Connect the Proxy
Step 2: Set the Mode to RULE
Step 3: Play the video or photo on wechat or make the voice call you will notice a very slow speed or no connectivity.But if you disconnect the Clash it will work fine.

### 设备信息

Device:Samsun S21 Ultra
ROM:Stock original
Android Version:11

### 应用信息

Version:v2.5.5
APK filename:[cfa-2.5.5-premium-arm64-v8a-release.apk](https://github.com/Kr328/ClashForAndroid/releases/download/v2.5.5/cfa-2.5.5-premium-arm64-v8a-release.apk)
Distribution Channel:GitHub

### 配置文件

[1648787812510.txt](https://github.com/Kr328/ClashForAndroid/files/8396475/1648787812510.txt)

### 日志

[clash-1648805029325.log](https://github.com/Kr328/ClashForAndroid/files/8396474/clash-1648805029325.log)

**Comment by Kr328** [comment]
Inspect your configuration please
