### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by wannaw1** [Kr328/ClashForAndroid#1451]
### Feature Description

从2.5.3版本更换到2.5.5版本后，每次我切换成全局模式就什么网址都代理不了，只用规则模式才能代理[BUG]

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
