### ISSUE TITLE
开启ipv6支持之后，手机ipv4开放的端口被filtered

### ISSUE THREAD

**Issue by huyizheng** [Kr328/ClashForAndroid#146]
手机和电脑在同一个局域网内，手机用termux开启sshd，电脑也开，在断开连接或不开启ipv6支持时，手机电脑可以互相ssh连接，但开启ipv6支持之后，手机可以ssh到电脑上，但电脑不能ssh到手机上。“绕过私有网络”选项是开着的。

termux的sshd开在8022端口上，如果在电脑上用`nmap`扫描手机ip的端口，则在断开连接或不开启ipv6支持时，能扫描到开放的8022端口：
```
Nmap scan report for 192.168.0.101
Host is up (0.0036s latency).
Not shown: 999 closed ports
PORT     STATE SERVICE
8022/tcp open  oa-system
```
但如果开启ipv6支持之后，电脑上再次用`nmap`扫描手机ip的端口，则扫描到8022端口显示filtered：
```
Nmap scan report for 192.168.0.101
Host is up (0.0042s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
8022/tcp filtered oa-system
```
无论是否开启ipv6支持，手机上用`termux` `nmap localhost`，均显示8022端口open。

安卓10，从releases里下载的1.1.4版的apk。

**Comment by Kr328** [comment]
预期行为

TCP 连接数据包未能正确返回

过程如下
1. 外部设备向手机发送 TCP-SYN (因系统路由特性 这个流量不会被 Clash 劫持)
2. 手机上的 sshd 做出响应 TCP-SYN-ACK (这个流量被 Clash 劫持 同样也是系统路由特性
3. Clash 内置的 协议栈检测到 TCP 连接不正常 对来源 和 目的端口 发送 TCP-RESET
4. TCP 连接被断开

这个是 由于系统路由表配置不正确 导致的 TCP 连接往返 路由设备 选择 的问题
路由表配置完全由系统进行 应用没有权限修改

IPv4 下因为有 `绕过私有网段` 所以流量怎么样都不会经过 Clash
IPv6 的 `绕过私有网段` 数据量过于庞大 会被系统拒绝
