### ISSUE TITLE
[BUG] 无法订阅，出现proxy8错误

### ISSUE THREAD

**Issue by yu-steven** [Kr328/ClashForAndroid#1461]
### 描述此错误

我以确保yaml的语法没有错误，在Clash上订阅链接时，部分安卓手机会出现订阅不了的错误

不明所以，前来请教！

### 如何复现该错误

步骤 1: 正常安装2022.1.15发布的v2.5.4版本 Clash for Android(安装包安装)
步骤 2: 打开Clash，不开启代理
步骤 3: 点击配置，输入订阅
步骤 4: 点击右上角
不过是部分手机出现的问题
无法全部复现！

### 设备信息

- 机型:
- 系统类型:
- Android 版本:

### 应用信息

- 版本: 2.5.4
- 安装包文件名: 
- 应用来源:

### 配置文件

[Clash.zip](https://github.com/Kr328/ClashForAndroid/files/8477928/Clash.zip)
只能上传zip文件……
解压就是yaml文件，怕毒可以先查一下毒😊

### 日志

🈚️

### 屏幕截图

![CCAD1E1D-F754-4599-B245-0CFF0CCD2237](https://user-images.githubusercontent.com/78414278/163093169-26a75781-ea45-42c2-a1ca-c6c382d01b0c.jpeg)

**Comment by Kr328** [comment]
配置里 username 和 password 全部用 引号 包起来

**Comment by yu-steven** [comment]
OK，知道啦
