### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Bimasingkong** [Kr328/ClashForAndroid#1469]
### Feature Description

Please add core meta too I want use vless protocol like new openclash version thanks

### Additional

![Screenshot_2022-04-15-11-50-36-472_com github kr328 clash](https://user-images.githubusercontent.com/98108857/163593380-c4485fe1-3b99-4ee6-bd36-727e0a4f2c14.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
