### ISSUE TITLE
能否提几个建议

### ISSUE THREAD

**Issue by neo16ye** [Kr328/ClashForAndroid#147]
1.这几个新版本在代理连接的时候不能修改设置了，不太方便。
2.从机场网址下载的配置文件复制为一个本地副本后，还是不能对其进行编辑。
3.延迟测试功能不太完善，测试的很慢，节点几十个，往往点很多次才能全部测出。

**Comment by Kr328** [comment]
1. 系统行为决定
2. 可能是 Bug
3. 新的 Clash Core 决定

**Comment by Kr328** [comment]
2. https://github.com/Kr328/ClashForAndroid/releases/tag/1.1.7
