### ISSUE TITLE
[Feature Request] 访问控制应用能不能对每一个应用采取具体的模式？

### ISSUE THREAD

**Issue by censujiang** [Kr328/ClashForAndroid#1477]
### 功能描述

如题，比如说我想单独为领英或者哔哩哔哩设置全局模式，其他的APP则为默认模式

**Comment by EKyero** [comment]
访问控制只能决定应用流量进不进入clash core，怎么处理还得看配置文件怎么写的。
这个问题直接写两个process-name就行了。
