### ISSUE TITLE
[Feature Request] 请添加对 Clash.Meta 内核版本的支持

### ISSUE THREAD

**Issue by Miroxyz** [Kr328/ClashForAndroid#1481]
### 功能描述

Clash.Meta 内核，项目地址：
https://github.com/MetaCubeX/Clash.Meta

请添加对 Clash.Meta 内核版本的支持，在 releases 中提供多一个内核版本的支持。

**Comment by EKyero** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1473#issuecomment-1100514887
