### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Khf20** [Kr328/ClashForAndroid#1486]
### Feature Description

please add vless xtls mode

### Additional

![Screenshot_2022-04-19-09-36-07-84_fb9683381e7bc023e44079fdae6a5002](https://user-images.githubusercontent.com/103437271/165182375-2619546d-1b65-486d-816c-bb745164b572.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
