### ISSUE TITLE
[Feature Request] vless xtls feature

### ISSUE THREAD

**Issue by Khf20** [Kr328/ClashForAndroid#1487]
### Feature Description

please add the vless xtls feature for foss meta

### Additional

![Screenshot_2022-04-19-09-36-07-84_fb9683381e7bc023e44079fdae6a5002](https://user-images.githubusercontent.com/103437271/165182646-bc72e0b0-0ca2-45fc-97fd-4aba08d60e4a.jpg)

**Comment by Kr328** [comment]
feedback to upstream pls
