### ISSUE TITLE
[Feature Request] 请问是否有计划支持 Clash Meta 内核

### ISSUE THREAD

**Issue by gcphym** [Kr328/ClashForAndroid#1491]
### 功能描述

请问是否有计划支持 Clash Meta 内核？
https://github.com/MetaCubeX/Clash.Meta

### 附加信息

从现有的几个关于此问题的issue中都没有找到明确信息

**Comment by Kr328** [comment]
没有

这里只提供 Dreamacro/clash 支持 

应用除了 premium 内核外其他部分均开源 你可以自行修改编译 

但是 修改的版本不会在这里得到支持
