### ISSUE TITLE
[Feature Request] 分应用代理这点希望学习一下SagerNet的“扫描中国应用”这种智能选择方式

### ISSUE THREAD

**Issue by redstoneleo** [Kr328/ClashForAndroid#1493]
### Feature Description

分应用代理这点希望学习一下SagerNet的“扫描中国应用”这种智能选择方式，比目前的选择方式更准确更方便，可说是一键搞定。

![image](https://user-images.githubusercontent.com/5896180/164891918-73e2425b-3efc-4617-bb97-7c339625a909.png)

**Comment by Kr328** [comment]
不做 我不想应用针对任何国家或区域构建 

而且 应用访问控制并不是核心功能
