### ISSUE TITLE
[疑问] Global 模式下，CFA DNS 设置为 built-in，程序还会在与服务器通信前，执行”本地解析域名用于判断“这一步吗？

### ISSUE THREAD

**Issue by GrilledPear** [Kr328/ClashForAndroid#1495]
### 功能描述

如题，关于 Global 模式下 DNS 行为的疑问

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
