### ISSUE TITLE
[Feature Request] 疑问：Global 模式下，CFA DNS 设置为 built-in，程序还会在与服务器通信前，执行”本地解析域名用于判断“这一步吗？

### ISSUE THREAD

**Issue by GrilledPear** [Kr328/ClashForAndroid#1496]
### 功能描述

如题

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@GrilledPear 不会

**Comment by GrilledPear** [comment]
明白了，谢谢解答
