### ISSUE TITLE
[BUG]  导入trojan订阅链接错误

### ISSUE THREAD

**Issue by JianYuhaha** [Kr328/ClashForAndroid#1497]
### 描述此错误

订阅trojan链接出现错误
![IMG_20220503_002605](https://user-images.githubusercontent.com/87753376/166270399-dfcc9913-d164-4f8d-992b-83796ba4a697.jpg)

clash for Android 已经是2.5.8版本

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
无

### 设备信息

- 机型:小米 10s
- 系统类型:MIUI
- Android 版本:12

### 应用信息

- 版本:2.5.8-premium
- 安装包文件名:2.5.8-premium universe 33m大小
- 应用来源:github

### 配置文件

```yml
无配置文件
```

### 日志

```raw
无
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by JianYuhaha** [comment]
> @JianYuhahaClash for Android 仅支持 Clash 的配置文件

但是...之前不是说clash for andriod 不是可以导入trojan的链接了吗...而且其他人也用谷歌商店新版本clash订阅成功了。

**Comment by EKyero** [comment]
你确定你的链接和别人的订阅是一回事？
**Clash for Android 仅支持 Clash 的配置文件** 
如果你分不清两者区别，就去问你的机场主
