### ISSUE TITLE
能否增加“允许来自局域网的连接”

### ISSUE THREAD

**Issue by aplixy** [Kr328/ClashForAndroid#150]
希望能有一个“允许来自局域网的连接”的功能，像v2ray那样，方便我给其它手机开热点时他们可以通过我的热点连外网
![IMG_20200224_163632](https://user-images.githubusercontent.com/5989299/75138008-19b5b780-5724-11ea-867f-a9947c0327af.jpg)

**Comment by Kr328** [comment]
自己修改 配置文件

**Comment by aplixy** [comment]
> 自己修改 配置文件

从URL导入的，Windows版好像有个Allow LAN选项，Android版没找到

**Comment by Kr328** [comment]
@aplixy 那个就是编辑配置文件实现的

**Comment by aplixy** [comment]
> @aplixy 那个就是编辑配置文件实现的

😂
