### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yuluodf** [Kr328/ClashForAndroid#1501]
### 描述此错误

youtube安卓客户端，在后台播放切换回前台时(有youtube高级会员)，大概率回卡主转圈圈而不能缓冲视频，我测试了surf board，没有这个问题，因此，我确定是软件的问题，请尽快解决这个问题，谢谢

### 如何复现该错误

youtube安卓客户端，在后台播放切换回前台时(有youtube高级会员)，大概率会卡主转圈圈而不能缓冲视频，我测试了surf board，没有这个问题，因此，我确定是软件的问题，请尽快解决这个问题，谢谢

### 设备信息

- 机型:小米10 pro
- 系统类型: miui13
- Android 版本:12

### 应用信息

- 版本:2.5.8. foss
- 安装包文件名:com.github.kr328.clash.foss
- 应用来源: github

### 配置文件

```yml
无
```

### 日志

```raw
无
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by yuluodf** [comment]
都是在相同的条件下测试的结果，相同的时间，同网络。同节点，只有代理工具不同
