### ISSUE TITLE
[BUG] youtube安卓客户端，在后台播放切换回前台时(有youtube高级会员)，大概率会卡主转圈圈而不能缓冲视频，我测试了surf board，没有这个问题，因此，我确定是软件的问题，请尽快解决这个问题，谢谢

### ISSUE THREAD

**Issue by yuluodf** [Kr328/ClashForAndroid#1502]
### 描述此错误

youtube安卓客户端，在后台播放切换回前台时(有youtube高级会员)，大概率会卡主转圈圈而不能缓冲视频，我测试了surf board，没有这个问题，因此，我确定是软件的问题，请尽快解决这个问题，谢谢

### 如何复现该错误

youtube安卓客户端，在后台播放切换回前台时(有youtube高级会员)，大概率会卡主转圈圈而不能缓冲视频，我测试了surf board，没有这个问题，因此，我确定是软件的问题，请尽快解决这个问题，谢谢

### 设备信息

机型:小米10 pro
系统类型: miui13
Android 版本:12

### 应用信息

版本:2.5.8. foss
安装包文件名:com.github.kr328.clash.foss
应用来源: github

### 配置文件

```yml
不需要配置文件
```

### 日志

```raw
[TCP] 127.0.0.1:37458 --> app-measurement.com:443 match GeoIP(CN) using DIRECT
```

**Comment by Kr328** [comment]
日志配置请

**Comment by Kr328** [comment]
应用开源免费允许修改 请自行解决 谢谢

**Comment by yuluodf** [comment]
这？我反馈bug呢，这回复我看不懂

**Comment by yuluodf** [comment]
这就给关闭了？关闭速度倒是挺快
