### ISSUE TITLE
[BUG] Clash can not start

### ISSUE THREAD

**Issue by DebuggingLiu** [Kr328/ClashForAndroid#1503]
### Describe the bug

I run Clash on a Android 7.1 device whose hardware platform is RK3399,
configuration is activated after I configure the right URL,
then I click start, Clash popup says: there is no VPN component in the system.
which component I need to  add? the device Ethernet and Wi-Fi both are  worked.

### To Reproduce

I run Clash on a Android 7.1 device whose hardware platform is RK3399,
configuration is activated after I configure the right URL,
then I click start, Clash popup says: there is no VPN component in the system.
which component I need to  add? the device Ethernet and Wi-Fi both are  worked.

### Device Info

- Device: Customized private device  which used RK3399
- ROM: Customized AOSP
- Android Version: Android 7.1

### Application Info

- Version: 1.2.11
- APK filename: app-universal-release.apk
- Distribution Channel: 

### Configure File

```yml
URL: https://subscript.hkssapi.xyz/link/VNst3s7sRzhP433N?mu=4
```

### Logs

```raw
05-07 09:31:11.641  1177  1177 D LaunchPadFragment: 启动app:Clash
05-07 09:31:11.793  2133  2133 D ClashForAndroid: Remote Connection State = true
05-07 09:31:11.794  2133  2133 D ClashForAndroid: Global Broadcast Receiver State = true
05-07 09:41:45.921   464   485 I ActivityManager: START u0 {cmp=com.github.kr328.clash/.SupportActivity} from uid 10058 on display 0
05-07 09:41:46.617   464   551 I ActivityManager: Displayed com.github.kr328.clash/.SupportActivity: +675ms
05-07 09:45:36.010  2133  2142 W JavaBinder: BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.github.kr328.clash.remote.Remote$ClashConnection$onServiceConnected$1
05-07 09:45:36.010  2133  2142 W JavaBinder: BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.github.kr328.clash.remote.Remote$ProfileConnection$onServiceConnected$1
```

**Comment by Kr328** [comment]
Clash cannot request VPN permission from system, feedback to ROM developer pls

Related:
1. https://developer.android.com/reference/android/net/VpnService#prepare(android.content.Context)
2. https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/VpnDialogs/

**Comment by DebuggingLiu** [comment]
Clash worked after VpnDialogs added, ths so much for your help.
