### ISSUE TITLE
[Bug]: 安卓过一段时间用Allow LAN就需要先用Clash For Android连通一下然后关闭后才能上墙外的网

### ISSUE THREAD

**Issue by gzyguo** [Kr328/ClashForAndroid#1505]
### 描述此错误

就是第过比如2个小时，我也不知道具体，就一天中过一阵子，涉及涉及到关机、重连wifi，但刚试了一下，这2不会在测试时候触发问题，就不能翻墙了，但100%能通过连通Clash for Android解决，连通后关掉CFA就正常用了。1年有了吧，多个安卓、WIFI、Windows 10/11都这样

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
不知道，但非要说的话就是使用30分钟到几个小时，肯定会出现，也不是说就是CFW的问题，但实在不知道该怎么解决了。安卓和Windows是一家吗，需要在哪边也提交一下吗？

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
Oneplus 7 Pro lineageOS 18.1/Unofficial 19999.1
Mi Pad 4: Mokee ROM 100/Unofficial LineageOS 19
Oneplus 5: LineageOS 18.1/Unofficial 19.1

### 应用信息

- 版本: 2.5.4.premium
- 安装包文件名:
- 应用来源: Google Play Store

### 配置文件

```yml
这个怎么弄啊
```

### 日志

```raw
这个怎么弄啊
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@gzyguo 这种问题一般建议问代理提供商
