### ISSUE TITLE
在代理页更改代理排序后点击节点会错乱

### ISSUE THREAD

**Issue by aplixy** [Kr328/ClashForAndroid#151]
连接成功代理之后进“代理 规则模式”页，点右上角三个点，更改代理排序方式，不退出页面直接切换节点，选中状态显示错乱，退出页面重进恢复正常

**Comment by Kr328** [comment]
@aplixy 无法复现

**Comment by BurningWS** [comment]
@aplixy 只勾选代理排序就好了，不要勾选代理组排序

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
