### ISSUE TITLE
[Feature Request] url导入请求内容成功，解析失败时，保存配置到本地，提供编辑修改

### ISSUE THREAD

**Issue by lldacing** [Kr328/ClashForAndroid#1512]
### 功能描述

我从url导入订阅地址，但有个节点配置有问题，tls配的false，使用的h2，导致报错H2/grpc必须tls为true，由于内容并没有下载保存成配置，无法编辑修改；由于订阅地址返回内容太多（30万+字），我在浏览器中全选复制内容到剪切板也失败了，所以手动复制内容常见本地文件再导入的方案也行不通，希望可以像CFW那样，导入有问题但文件已下载，可以编辑修正

**Comment by Kr328** [comment]
使用 subconverter 或者 文件 类型的配置文件

**Comment by lldacing** [comment]
> 使用 subconverter 或者 文件 类型的配置文件
> 
> 文件类型的配置文件可以从文件导入

我就是无法保存订阅内容到本地，从文件导入，文字太多了，复制不了；subconverter没用过，能把内容下载下来修改？我就是一个使用者，不是我搭建服务

**Comment by Kr328** [comment]
> > 使用 subconverter 或者 文件 类型的配置文件
> > 文件类型的配置文件可以从文件导入
> 
> 我就是无法保存订阅内容到本地，从文件导入，文字太多了，复制不了；subconverter没用过，能把内容下载下来修改？我就是一个使用者，不是我搭建服务

善用浏览器的保存到本地功能
