### ISSUE TITLE
[Feature Request] 类似于UU加速器安卓端开热点给游戏主机加速功能

### ISSUE THREAD

**Issue by Rakau** [Kr328/ClashForAndroid#1515]
### 功能描述

偶然在安卓端的UU加速器上看到了能对游戏主机进行加速，于是乎下载进行体验。这个加速器能做到不ROOT的情况下热点分享代理给游戏机加速。

测试环境：MIUI13+安卓12+任天堂 Switch+wifi & 移动网络+UU主机加速器安卓端+CFA v2.5.9

测试1（UU加速器+wifi网络 & 移动网络）：手机开启UU加速器选择加速后会建立VPN连接，然后开启无线热点分享，Switch根据附加信息设置后连接手机热点，提示成功。进入主机网络测试，测得IP为代理IP，NAT类型为A。进入主机游戏（锁IP）联机测得正常连接，TCP+UDP均走代理

测试2（CFA+混合端口+移动网络）：手机开启CFA连接后会建立VPN连接，然后开启无线热点分享，Switch根据热点网关信息填写IP和混合端口，提示成功。进入主机网络测试，测得IP为代理IP，NAT类型为D（无公网）。进入主机游戏（锁IP）联机无法连接，TCP+UDP均未走代理，可得代理仅走了HTTP

测试3（CFA+混合端口+wifi网络）：手机开启CFA连接后会建立VPN连接，然后开启无线热点分享，Switch根据热点网关信息填写IP和混合端口，提示成功。进入主机网络测试，测得IP为代理IP，NAT类型为B（无公网）。进入主机游戏（锁IP）联机无法连接，TCP+UDP均未走代理，可得代理仅走了HTTP

测试4（CFA+HTTP端口+移动网络）：手机开启CFA连接后会建立VPN连接，然后开启无线热点分享，Switch根据热点网关信息填写IP和混合端口，提示成功。进入主机网络测试，测得IP为代理IP，NAT类型为D（无公网）。进入主机游戏（锁IP）联机无法连接，TCP+UDP均未走代理，可得代理仅走了HTTP

测试5（CFA+HTTP端口+wifi网络）：手机开启CFA连接后会建立VPN连接，然后开启无线热点分享，Switch根据热点网关信息填写IP和混合端口，提示成功。进入主机网络测试，测得IP为代理IP，NAT类型为B（无公网）。进入主机游戏（锁IP）联机无法连接，TCP+UDP均未走代理，可得代理仅走了HTTP

测试6（CFA+socks端口+移动网络 & wifi网络）：手机开启CFA连接后会建立VPN连接，然后开启无线热点分享，Switch根据热点网关信息填写IP和socks端口，无法连接。可得Swtich不支持socks

不清楚加速器是如何做到的，不知道CFA能不能做到相似的连接。是否有其余的方法来实现相关的连接

### 附加信息
![IMG_20220515_110023_看图王](https://user-images.githubusercontent.com/33389179/168457143-53b2b035-3f4b-4237-a1bb-5fc3900c00c6.jpg)

**Comment by Kr328** [comment]
在我的印象中热点除非通过 root 修改路由表 否则流量不会经过 VpnService 的网络接口

如果你知道如何实现 欢迎在这里写下实现方式会开启 Pull Request

**Comment by Rakau** [comment]
> 在我的印象中热点除非通过 root 修改路由表 否则流量不会经过 VpnService 的网络接口
> 
> 如果你知道如何实现 欢迎在这里写下实现方式或开启 Pull Request

确实不知道如何实现的，如果大家有思路我可以配合测试，这边有ROOT环境

**Comment by Kr328** [comment]
@Rakau 

在开启加速后 使用 tcpdump 抓取 wlan0 和 tun0 的数据包可能会有帮助

`tcpdump -i wlan0 -w /sdcard/wlan0.pcap`
`tcpdump -i tun0 -w /sdcard/tun0.pcap`

然后上传 `/sdcard/wlan0.pcap` 和 `/sdcard/tun0.pcap`

**Comment by Rakau** [comment]
> @Rakau
> 
> 在开启加速后 使用 tcpdump 抓取 wlan0 和 tun0 的数据包可能会有帮助
> 
> `tcpdump -i wlan0 -w /sdcard/wlan0.pcap` `tcpdump -i tun0 -w /sdcard/tun0.pcap`
> 
> 然后上传 `/sdcard/wlan0.pcap` 和 `/sdcard/tun0.pcap`

这个是在移动网下测还是WIFI下？

**Comment by Kr328** [comment]
@Rakau 都行

wlan0 换成 热点的 接口名称 一般有 wlan0 或者 wlan1

**Comment by Rakau** [comment]
> @Rakau 都行
> 
> wlan0 换成 热点的 接口名称 一般有 wlan0 或者 wlan1
[pcap.zip](https://github.com/Kr328/ClashForAndroid/files/8694648/pcap.zip)

**Comment by Kr328** [comment]
@Rakau 运行 tcpdump 之后需要进行一些操作来让 Switch 的流量经过加速器 才能抓取到数据包

还有 开发者选项里的 网络共享硬件加速 也需要关闭

**Comment by Rakau** [comment]
> @Rakau 运行 tcpdump 之后需要进行一些操作来让 Switch 的流量经过加速器 才能抓取到数据包
> 
> 还有 开发者选项里的 网络共享硬件加速 也需要关闭
[tun0.zip](https://github.com/Kr328/ClashForAndroid/files/8694721/tun0.zip)

wlan0没有数据，只有这个

**Comment by Rakau** [comment]
我用ifconfig看了下，加速开启后，有19个tun0的连接，我这热点的叫ap0，其中19里有6.6.6.6，需要再抓吗？

**Comment by Kr328** [comment]
@Rakau 为什么会有 19 个

用 ip addr 替代 ifconfig

如果可以的话可以试试再抓包

**Comment by Rakau** [comment]
> @Rakau 为什么会有 19 个
> 
> 用 ip addr 替代 ifconfig
> 
> 如果可以的话可以试试再抓包

47: tun0: <POINTOPOINT,UP,LOWER_UP> mtu 20000 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 26.26.26.1/24 scope global tun0
       valid_lft forever preferred_lft forever
    inet 13.112.35.82/32 scope global tun0:1
       valid_lft forever preferred_lft forever
    inet 52.199.66.160/32 scope global tun0:2
       valid_lft forever preferred_lft forever
    inet 52.39.4.152/32 scope global tun0:3
       valid_lft forever preferred_lft forever
    inet 34.208.146.66/32 scope global tun0:4
       valid_lft forever preferred_lft forever
    inet 35.158.74.61/32 scope global tun0:5
       valid_lft forever preferred_lft forever
    inet 35.158.20.233/32 scope global tun0:6
       valid_lft forever preferred_lft forever
    inet 52.14.207.28/32 scope global tun0:7
       valid_lft forever preferred_lft forever
    inet 52.14.47.244/32 scope global tun0:8
       valid_lft forever preferred_lft forever
    inet 54.64.157.221/32 scope global tun0:9
       valid_lft forever preferred_lft forever
    inet 52.193.120.207/32 scope global tun0:10
       valid_lft forever preferred_lft forever
    inet 34.208.151.98/32 scope global tun0:11
       valid_lft forever preferred_lft forever
    inet 52.38.9.124/32 scope global tun0:12
       valid_lft forever preferred_lft forever
    inet 35.156.146.223/32 scope global tun0:13
       valid_lft forever preferred_lft forever
    inet 52.14.237.148/32 scope global tun0:14
       valid_lft forever preferred_lft forever
    inet 35.157.230.202/32 scope global tun0:15
       valid_lft forever preferred_lft forever
    inet 52.14.237.96/32 scope global tun0:16
       valid_lft forever preferred_lft forever
    inet 52.10.205.177/32 scope global tun0:17
       valid_lft forever preferred_lft forever
    inet 6.6.6.6/32 scope global tun0:18

**Comment by Kr328** [comment]
@Rakau netstat -lnp 呢

**Comment by Rakau** [comment]
> @Rakau 为什么会有 19 个
> 
> 用 ip addr 替代 ifconfig
> 
> 如果可以的话可以试试再抓包

热点的抓包，包含NS连接后测试UDP网络到进入游戏后1分钟
[ap0.zip](https://github.com/Kr328/ClashForAndroid/files/8695066/ap0.zip)

**Comment by Rakau** [comment]
> netstat -lnp
[netstat -lnp.txt](https://github.com/Kr328/ClashForAndroid/files/8695072/netstat.-lnp.txt)

**Comment by Rakau** [comment]
> > netstat -lnp
> > [netstat -lnp.txt](https://github.com/Kr328/ClashForAndroid/files/8695072/netstat.-lnp.txt)

里面的202.67是游戏服务器的ip

**Comment by Kr328** [comment]
那我知道基本上的实现原理 并且方案并不是通用方案

UU 利用 VpnService 为本机添加全部的 Switch 服务器 IP 地址 并监听这些地址的高位端口 转发数据

这个方案并不能处理除了 Switch 之外的流量 并且为本机需要添加大量的地址 同时监听大量的端口

ClashForAndroid 并不合适实现这个方案

**Comment by Rakau** [comment]
> 那我知道基本上的实现原理 并且方案并不是通用方案
> 
> UU 利用 VpnService 为本机添加全部的 Switch 服务器 IP 地址 并监听这些地址的高位端口 转发数据
> 
> 这个方案并不能处理除了 Switch 之外的流量 并且为本机需要添加大量的地址 同时监听大量的端口
> 
> ClashForAndroid 并不合适实现这个方案

比较丧病的方式，~~用cfm唯一的选择~~
