### ISSUE TITLE
增加节点端口显示[Feature Request] 

### ISSUE THREAD

**Issue by shandonghezecaoxianwuhujichang** [Kr328/ClashForAndroid#1516]
### 功能描述

如图
![Uploading Screenshot_20220515_141820_edit_293702128587908.png…]()

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
