### ISSUE TITLE
[Feature Request] 节点选着界面，显示节点的端口。

### ISSUE THREAD

**Issue by shandonghezecaoxianwuhujichang** [Kr328/ClashForAndroid#1517]
### 功能描述

节点选着界面，显示节点的端口。

### 附加信息

![Screenshot_20220515_141820_edit_293702128587908](https://user-images.githubusercontent.com/86088968/168460221-b11be24a-2ed8-469c-90dd-1928aaeb0ee8.png)

**Comment by Kr328** [comment]
clash core 没有获取节点基本信息的接口
