### ISSUE TITLE
[BUG] It seem that trojan speedtest will not timeout as expect

### ISSUE THREAD

**Issue by thank243** [Kr328/ClashForAndroid#1518]
### Describe the bug

when use speedtest in ui, the thunder icon is still loops and not response a correct timeout. But the core url-test work perfect. The same bug appeared in pre veriosn clash core. When you pass a ctx into the connection, the ctx not work as expect. So is there the same bug in the ui?

### To Reproduce

Step 1: a server only recv packets and not responese any thing
Step 2: open the software and clikc the speed test.
Step 3: the test will not finish as expect

### Device Info

- Device:Mate 20 pro
- ROM:
- Android Version:

### Application Info

- Version: latest verison
- APK filename:
- Distribution Channel:

### Configure File

```yml
just use common trojan configure.
```

### Logs

```raw
the speed test will not craete any logs.
```

**Comment by Kr328** [comment]
protocol implement by core, feedback to upstream pls
