### ISSUE TITLE
新版返回键退出后进程就会关闭

### ISSUE THREAD

**Issue by Jacky486** [Kr328/ClashForAndroid#152]
新UI初版无问题，从前两个版本出现问题。 proxy only 模式

**Comment by Kr328** [comment]
详细表述 请

如何复现 和 具体行文

**Comment by Jacky486** [comment]
连接后点返回键进程关闭，点home键没有问题，但过一段时间后虽然显示连接但无网络。

**Comment by Jacky486** [comment]
应该不需要开自启动和电池不优化吧

**Comment by Kr328** [comment]
看起来是 你自己 或者 系统 限制了 应用的 **前台服务**

这样的行为 与 启动后台服务 一致

**Comment by Jacky486** [comment]
有关服务在这两个版本与之前做过变化？

**Comment by Jacky486** [comment]
所以我需要开自启？

**Comment by Kr328** [comment]
对于 VPN 服务 有变化
对于 Proxy Only 没有

**Comment by Jacky486** [comment]
那可是有点奇怪了

**Comment by Jacky486** [comment]
刚刚发现两个模式都一样的，home键没事，返回键就会停止进程。
