### ISSUE TITLE
[Feature Request] 支持扫码导入Clash订阅连接

### ISSUE THREAD

**Issue by honeyjuice** [Kr328/ClashForAndroid#1522]
### 功能描述

背景：
目前使用CFA首次导入订阅连接时，需要手动输入/复制粘贴进文本框，这样通常需要使用微信或者tg等通讯软件发到手机，再从这些软件复制到CFA中

期望的功能：
在URL输入框的右侧，能展示一个二维码扫描入口，点击进入后打开相机进行扫码链接二维码，扫码完成后直接填写到订阅链接输入框中。

使用场景：
将PC端制作好的订阅链接由草料二维码等网站转成二维码，用CFA扫描二维码获取配置链接。

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/964

**Comment by Kr328** [comment]
@honeyjuice 什么时候 Android 本身提供扫码 API 的话 还是可以考虑加一加的

**Comment by GregAMO** [comment]
你会发现 clash for Windows 现在就可以帮你做到…一半。
对配置文件右键选 QR code，然后 include scheme。就会在url前面增加一段 “ clash://install-config?url= ”
手机上面的通用二维码扫描器，应当是可以跳到 clash for Android 的，甚至支持二维码扫描的相机也可以试试。

如果要跳过clash for Windows，你可以找个二维码生成器，浏览器扩展或者ditto之类的剪贴板历史软件自带，把订阅链接复制后前面加上这段字，手机就能扫完跳clash for Android了。
