### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by 7aGiven** [Kr328/ClashForAndroid#1523]
### 功能描述

在更新配置文件时添加HTTP/2支持

### 附加信息

![Screenshot_20220519_183417](https://user-images.githubusercontent.com/77519196/169274110-99179c60-0306-4905-b730-4581d433d586.jpg)
自建了一个只支持HTTP/2的服务器，用浏览器可以直接访问，用clash就是无法更新。
希望添加HTTP/2的支持

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
