### ISSUE TITLE
[Feature Request] 请增加一个ShortcutManager(应用快捷方式)用以快速地切换代理开关状态

### ISSUE THREAD

**Issue by pudgelee** [Kr328/ClashForAndroid#1527]
### 功能描述

作者好，本人手机有个一键到达APP的功能，如果cfa有应用快捷方式就可以可以方便的切换代理连接or关闭，下拉菜单中的开关并没有太满意，于是乎修改项目增加一条`动态ShortcutManager Item`，通过Item开关Service，用以一键切换代理连接or关闭的效果。修改后如图：

![2022-05-23_09-31-57](https://user-images.githubusercontent.com/20744065/169727080-df9ce61a-4511-4d1d-ab5d-153fab47862e.png)
![2022-05-23_09-32-40](https://user-images.githubusercontent.com/20744065/169727093-78890fd6-50f7-49bf-91af-7d18d5bf0687.png)

修改满意后才发现编译的只有`foss版本`，`premium版本` 并没有出现（无论是debug版本或者release都是如此），如图：
![2022-05-23_09-15-29](https://user-images.githubusercontent.com/20744065/169725826-743dd50d-e521-46c8-a6d2-76f709265d79.png)
![2022-05-23_09-14-33](https://user-images.githubusercontent.com/20744065/169725831-3800529a-2d64-44e3-b99d-fdf116c749da.png)

针对以上请问：
1.`premium` 版本需要特殊的配置吗，如果是那么具体的配置是否可以告知
2.如果可以的话，请考虑增加一条动态ShortcutManager用以切换代理连接状态或者开关APP（静态貌似不能唤起）

**Comment by Kr328** [comment]
#326

**Comment by EKyero** [comment]
premium是使用premium core
premium版是闭源的
premium版的features可以参照clash wiki

**Comment by Lovest20018** [comment]
熟悉的326.不过终于有人动手来修改了。lz后续是否会公开代码呢？虽然现在surfboard已经支持shortcuts了。不过cfa这个叫了3年有了。能用上也是好的。

**Comment by steve1145114** [comment]
请问能否详细说明一下文中shortcut是怎没实现的呢，现在非常需要这个功能

**Comment by steve1145114** [comment]
请问能否详细说明一下文中shortcut是怎么实现的呢，现在非常需要这个功能

**Comment by pudgelee** [comment]
> 熟悉的326.不过终于有人动手来修改了。lz后续是否会公开代码呢？虽然现在surfboard已经支持shortcuts了。不过cfa这个叫了3年有了。能用上也是好的。

修改了一个可用 [Shortcuts ](https://github.com/pudgelee/ClashForAndroid)的项目，需要的自行编译。
