### ISSUE TITLE
[BUG] 访问控制应用包列表找不到play商店

### ISSUE THREAD

**Issue by felix-git-hub** [Kr328/ClashForAndroid#1529]
### 描述此错误

问控制应用包列表找不到play商店（就是谷歌商店），v2rayng的分应用代理可以正常找到；

### 如何复现该错误

设置
网络
访问控制应用包列表
搜索 - play/商店/vendor

### 设备信息

- 机型:小米k40 pro
- 系统类型:miui13
- Android 版本:安卓12

### 应用信息

- 版本: 2.5.9 premium
- 安装包文件名:
- 应用来源:google play store

### 配置文件

```yml
无
```

### 日志

```raw
无
```

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/971

**Comment by Owen-Deng** [comment]
+1

**Comment by felix-git-hub** [comment]
> 

as kr328 addressed in the 
[https://github.com/Kr328/ClashForAndroid/issues/971](url)
过滤 -> 系统应用 -> 关闭
the clash hide system apps by default
