### ISSUE TITLE
后台耗电问题

### ISSUE THREAD

**Issue by LIUH0961** [Kr328/ClashForAndroid#1532]
### 功能描述

建议能减少clash后台耗电问题！今天测试发现把clash关掉之后，后台还在运行clash，造成电池电量流失过快！希望能修复一下！

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
