### ISSUE TITLE
请求如何使用cash forAndroid [Feature Request] 

### ISSUE THREAD

**Issue by xiantingxingbu** [Kr328/ClashForAndroid#1533]
### Feature Description

之前一直在使用ikuuu  现在不会使用了  请求使用方法  谢谢

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
