### ISSUE TITLE
[Feature Request] 访问控制应用包列表不能添加google服务框架应用

### ISSUE THREAD

**Issue by ab503044120** [Kr328/ClashForAndroid#1535]
### Feature Description

设置-网络-访问控制应用包列表 无法添加google框架应用，造成把访问控制模式设置为仅允许已选择的应用时无法登陆谷歌账号，可以参考v2rayNG Android端源码 
https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/AppManagerUtil.kt

_No response_

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
