### ISSUE TITLE
前缀合并时合并了策略组名称

### ISSUE THREAD

**Issue by Zhaowei-Yu** [Kr328/ClashForAndroid#154]
![Screenshot_2020-02-25-23-23-36-299_Clash](https://user-images.githubusercontent.com/48342561/75261644-54077d80-5826-11ea-8ce3-52181786e5b1.png)
![Screenshot_2020-02-25-23-23-49-493_Clash](https://user-images.githubusercontent.com/48342561/75261700-671a4d80-5826-11ea-8327-ae948bcaf71a.png)
direct与domestic此处被前缀合并

**Comment by Kr328** [comment]
预期行为
