### ISSUE TITLE
安卓快速启动功能卡

### ISSUE THREAD

**Issue by ZctLuck** [Kr328/ClashForAndroid#1544]
### 功能描述

建议增加应用卡片快速启动的功能，非常需要，特别是安卓版本

### 附加信息

就我截图的这种，增加链接和断开功能。
万分感谢工程师的付出

![Screenshot_20220604-010042_One UI Home](https://user-images.githubusercontent.com/106831352/171911621-8b085d59-40e9-4dba-8ae6-d4c5e3ab0b68.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
