### ISSUE TITLE
[Feature Request] 希望修改添加profile时初始化rule providers的逻辑

### ISSUE THREAD

**Issue by nguzlp** [Kr328/ClashForAndroid#1546]
### 功能描述

在现行版本中添加使用rule provider的profile时，需要先初始化（下载）rule providers，但是由于国内的DNS污染或者严重干扰rule provider的托管网站，在保存配置时会因为无法完成初始化rule provider而无法添加profile。
希望修改添加profile时的逻辑，将初始化rule providers放在保存添加profile后，这样可开启代理解决providers无法初始化的问题。

**Comment by Kr328** [comment]
初始化逻辑均由 clash core 提供 反馈上游请
