### ISSUE TITLE
[BUG] 点击启动之后无网络

### ISSUE THREAD

**Issue by sanyue911** [Kr328/ClashForAndroid#1547]
### 描述此错误

可以正常点击启动，但是无信号。无法连接到网络

### 如何复现该错误

步骤 1: 点击启动
步骤 2: 运行中
步骤 3: 点开网页无信号，无法连接到网络

### 设备信息

- 机型:华为
- 系统类型:p30
- Android 版本:最新版

### 应用信息

无

### 配置文件

```yml
无
```

### 日志

```raw
无
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
