### ISSUE TITLE
[Feature Request] 在使用Rule mode时显示GLOBAL分组

### ISSUE THREAD

**Issue by whenov** [Kr328/ClashForAndroid#1549]
### 功能描述

由于Clash rule的最后一行可以写成`MATCH,GLOBAL`，因此希望使用Rule mode时可以显示GLOBAL分组以方便切换outbound。

**Comment by xuhaoyang** [comment]
@whenov 上游反馈？

**Comment by whenov** [comment]
@xuhaoyang yacd是支持的，所以我觉得应该只是UI的问题？

**Comment by AkariiinMKII** [comment]
> @xuhaoyang yacd是支持的，所以我觉得应该只是UI的问题？

写一个跑起来试试看 如果只是UI问题的话log里面应该有记录
