### ISSUE TITLE
clash for android更新订阅时出现x509:  certificate signed by unknown authority，应该怎么解决

### ISSUE THREAD

**Issue by zhengzheng4646** [Kr328/ClashForAndroid#1552]
### 描述此错误

clash for android更新订阅时出现x509:  certificate signed by unknown authority，应该怎么解决

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
clash for android更新订阅时出现x509:  certificate signed by unknown authority，应该怎么解决

### 设备信息

- 机型:mate30 pro
- 系统类型:鸿蒙
- Android 版本:

### 应用信息

- 版本:2.4.9
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
clash for android更新订阅时出现x509:  certificate signed by unknown authority，应该怎么解决
```

### 日志

```raw
无
```

### 屏幕截图

![Uploading Screenshot_20220611_151152.jpg…]()

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
