### ISSUE TITLE
[Feature Request] QR码分享配置文件

### ISSUE THREAD

**Issue by AngelofMe** [Kr328/ClashForAndroid#1554]
### 功能描述

我要把配置分享给家人，可是Clash没有分享功能，只能让他输入URL或者到网站下载配置，但是家里网络不好
我的Wifi都能用LineageOS自带的设置展示或扫描连网手机的QR码
能不能加上分享配置的功能，跟V2RayNG那种类似的
1.QR Code
2.Export to Clipboard
3.Export full Configuration to Clipboard

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1522
