### ISSUE TITLE
[BUG] 小米9下拉控制中心的clash快捷开关在程序不运行时无法开启

### ISSUE THREAD

**Issue by justbelieveyourself** [Kr328/ClashForAndroid#1555]
### 描述此错误

小米9下拉控制中心的clash快捷开关在程序不运行时无法开启，点击后没有反应

### 如何复现该错误

步骤 1: 下拉控制中心
步骤 2: 点击clash快捷图标，没有反应
步骤 3: ...
...

### 设备信息

- 机型: 小米9
- 系统类型: MIUI12.5.6
- Android 版本: 11

### 应用信息

- 版本: 2.5.9-premium
- 安装包文件名: cfa-2.5.9-premium-arm64-v8a-release.apk
- 应用来源: github

### 配置文件

```yml
无
```

### 日志

```raw
无
```

**Comment by flyalpaca** [comment]
miui的问题，你把clash加自启白名单，权限都打开，后台设置无限制并且多任务界面锁住就好了
