### ISSUE TITLE
[Feature Request]  Force Enable UDP

### ISSUE THREAD

**Issue by solirf** [Kr328/ClashForAndroid#1556]
### Feature Description

Is there any way to force enable udp to all ss proxy or specified group proxy

**Comment by solirf** [comment]
I use proxy providers so i cant edit whole proxy's every 15 minutes, it would be great if set it as default in app or main config

**Comment by xuhaoyang** [comment]
@solirf try https://github.com/tindy2013/subconverter ？

**Comment by solirf** [comment]
It works , thanks

**Comment by solirf** [comment]
I use proxy providers so i cant edit whole proxy's every 15 minutes, it
would be great if set it as default in app or main config

**Comment by solirf** [comment]
I will try
