### ISSUE TITLE
[BUG] 下载配置错误判断为超时，并且连接错误

### ISSUE THREAD

**Issue by 4RAILS** [Kr328/ClashForAndroid#1557]
### 描述此错误

配置无问题在PC上可用，Android版无法下载导入URL，超时限制过短，最终只能手动导入文件。之后无法建立任何连接，同样的配置在Clash for Windows上一切正常，报错码tcp dial如图

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:三星S20
- 系统类型:ONE UI 3.1
- Android 版本:11

### 应用信息

- 版本:2.4.9
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
rt
```

### 日志

```raw
如图
```

### 屏幕截图

![image](https://user-images.githubusercontent.com/107554960/173823862-a5bf4105-1696-4cfc-aea8-52a932f16e39.png)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1342#issuecomment-1013581105
