### ISSUE TITLE
[Feature Request] Premium version local provider without renaming file name

### ISSUE THREAD

**Issue by djoeni** [Kr328/ClashForAndroid#1558]
### Feature Description

Using Foss version when importing proxy provider it will automatically use file name, but when using Premium version it will generate random name causing error not found when saving.

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@djoeni Please use BUG template
