### ISSUE TITLE
导入订阅之后，启动报错，DNS名称服务转换错误，GP版，使用Clash订阅链接导入

### ISSUE THREAD

**Issue by Mosblue** [Kr328/ClashForAndroid#156]
![b5eb9ff595d21731168777caa80d856](https://user-images.githubusercontent.com/33258624/75274689-3fcf7a80-583e-11ea-9d25-e19ea96aaa73.jpg)
启动失败，手动导入文件和URL导入都不行

**Comment by Mosblue** [comment]
更新一下，我关掉wifi就可以正常启动服务，但是开着wifi就会启动失败，不知道为什么

**Comment by Kr328** [comment]
1.Google Play 有 两个版本 不知道你说的哪个
2. 你的路由器是否会分配 IPv6 的 DNS
3. 尝试 Releases 的 1.1.4

**Comment by Mosblue** [comment]
厉害了大佬，我试试1.1.4去，不清楚是否分配IPv6的DNS，稍后我确认下

**Comment by Mosblue** [comment]
1.1.4版本启动正常了，多谢
