### ISSUE TITLE
[BUG] 最近打开后，节点几乎全部消失，并且连接出错

### ISSUE THREAD

**Issue by wfn2111** [Kr328/ClashForAndroid#1562]
### 描述此错误

前几天正常使用，昨天连接后突然无法上网，节点几乎全部消失，提示我去shadowsocksR官网重新下载

### 如何复现该错误

步骤 1: ...打开cfa
步骤 2: ...连接
步骤 3: ...
...

### 设备信息

- 机型:one plus 8T
- 系统类型:Hydrogen OS
- Android 版本:11

### 应用信息

- 版本:2.5.9-premium-universal-release
- 安装包文件名:cfa-2.5.9-premium-universal-release
- 应用来源:github

### 配置文件

```yml
https://n2.urltosub.com/link/9cKV5rW9dFauDqhX?clash=1
```

### 日志

```raw
[APP] Logcat level: info
```

### 屏幕截图

![Uploading Screenshot_20220630-155507.jpg…]()

### 附加信息

我不太懂怎么用手机打开yaml配置文件，所以上传了订阅链接

**Comment by Kr328** [comment]
请联系你的代理提供商
