### ISSUE TITLE
[Feature Request] DNS策略默认[不修改]

### ISSUE THREAD

**Issue by Kia678** [Kr328/ClashForAndroid#1565]
### 功能描述

DNS策略默认[不修改], 首选使用配置文件的DNS比较好

**Comment by Kr328** [comment]
大多数配置文件默认的 DNS 并不好

**Comment by Kia678** [comment]
> 大多数配置文件默认的 DNS 并不好

现在鸡场的配置文件的DNS都挺好了, 不像以前那样了
另外, 想问下内置DNS是什么?

**Comment by Kr328** [comment]
**不想以前那样**  请证明你的观点 数据说话 同时请注意 **不要使用少量样例推广到全部用户**

我的观点可以在早期没有这项设置的时候的 cfa 的 issue 里找到

内置 DNS 可以自行阅读源码和日志
