### ISSUE TITLE
[BUG] 耗电问题

### ISSUE THREAD

**Issue by Syz200604** [Kr328/ClashForAndroid#1572]
### 描述此错误

耗电太快了，好多天都这样，每天24小时翻墙耗电比屏幕还耗的厉害，要不是隔壁surfboard速度不行，我早都不用clash了，每次看电池用量都是第一名

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:小米12x
- 系统类型:miui 13.0.5
- Android 版本:12

### 应用信息

- 版本:2.5.11-premium
- 安装包文件名:cfa-2.5.11premium-arm64-v8a-release.apk
- 应用来源:github

### 配置文件

```yml
没有
```

### 日志

```raw
没有
```

### 屏幕截图

![Screenshot_2022-07-06-08-35-16-452_com miui securitycenter](https://user-images.githubusercontent.com/104953788/177439975-f4b4a4aa-b861-4f77-99a2-4559aa49d232.jpg)

### 附加信息

耗电必须解决掉

**Comment by Syz200604** [comment]
还有，我没有开自启动，电量设置智能限制还是没用，一直开着就一直耗，耗的比屏幕都厉害，最早以前是没有的

**Comment by Syz200604** [comment]
真是电老虎

**Comment by Kr328** [comment]
#505
