### ISSUE TITLE
[BUG]无法完成编译 flag provided but not defined: -trimpath 

### ISSUE THREAD

**Issue by dream0407** [Kr328/ClashForAndroid#1573]
### 描述此错误

你好，我想在打开CLASH的时候自动启动代理，打算通过修改编译来解决此问题，我的PC运行环境是debian10 安装了open-jdk11 、android sdk、cmake、golang 开始编译后出错，如下> Task :core:externalGolangBuildFossReleaseArm64V8a FAILED
flag provided but not defined: -trimpath
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
FAILURE: Build failed with an exception.

不知道是否是因为我的golang版本不匹配，请指点。

### 如何复现该错误

./gradlew app:assembleFossRelease

### 设备信息

系统：debian10
jdk:   open-jdk11
cmake: 3.24.0-rc2
golang: go1.11.6

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
无
```

### 日志

```raw
./gradlew app:assembleFossRelease

> Task :core:externalGolangBuildFossReleaseArm64V8a FAILED
flag provided but not defined: -trimpath
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:externalGolangBuildFossReleaseArm64V8a'.
> Process 'command 'go'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
66 actionable tasks: 5 executed, 61 up-to-date
```

**Comment by Kr328** [comment]
编译问题参见 github action 脚本 这里不会提供编译帮助
