### ISSUE TITLE
[BUG] android clash 全局模式无效

### ISSUE THREAD

**Issue by gitmuyang** [Kr328/ClashForAndroid#1574]
### Describe the bug

1. Proxy --- mode --- Global Mode 
2. Settings --- Override --- Mode --- Global Mode

The global mode is invalid. when I use global mode, I can't open youtube.com

### To Reproduce

1. Proxy --- mode --- Global Mode 
2. Settings --- Override --- Mode --- Global Mode

### Device Info

It has nothing to do with device. I tried on 3 devices, all of them have the same issue.

### Application Info

- Version: 2.5.4.premium 
- APK filename: Clash
- Distribution Channel: google play

### Configure File

```yml
1
```

### Logs

```raw
1
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
