### ISSUE TITLE
[Feature Request] 小米MIUI提示“该安装包与您的系统不兼容”

### ISSUE THREAD

**Issue by padbbss** [Kr328/ClashForAndroid#1576]
### 功能描述

我的小米MIUI提示安装包与系统不兼容，大佬了解什么情况吗？

![image](https://user-images.githubusercontent.com/108036002/178134142-9d341d16-5d8a-4867-a459-6926ed0b2ab7.png)

### 附加信息

MIUI 12.0.1
Android 9

**Comment by EKyero** [comment]
@padbbss https://github.com/Kr328/ClashForAndroid/releases/tag/v2.5.9
下最大的

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
