### ISSUE TITLE
[BUG] 无法进入游戏王 duel links 国际版

### ISSUE THREAD

**Issue by hamberluo** [Kr328/ClashForAndroid#1580]
### 描述此错误

biubiu 加速器可以加速
clash 就会卡在 loading 页面

但如果 biubiu 加速器进入游戏后再切换到 clash，是可以玩的

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型: 一加 9
- 系统类型: ColorOS
- Android 版本: 12

### 应用信息

- 版本: 2.5.11-premium
- 安装包文件名: cfa-2.5.11-premium-arm64-v8a-release.apk
- 应用来源: github

### 配置文件

```yml
暂无
```

### 日志

```raw
暂无
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
