### ISSUE TITLE
[BUG] 耗电异常 | Draining batteries over 25% usage

### ISSUE THREAD

**Issue by bamboo512** [Kr328/ClashForAndroid#1583]
### 描述此错误

耗电异常，最高消耗占比超过 28%，而且一直在 25% 以上。
Clash for Android is draining battery over 25% usage.

甚至没有使用任何 Reject 策略（用的是 https://acl4ssr-sub.github.io/ 提供的 ACL4SSR NoReject 规则）。

### 如何复现该错误

开启代理后，正常使用手机。
过一段时间到设置查看 App 耗电量。

### 设备信息

- 机型: 小米 12X
- 系统类型: MIUI 13
- Android 版本: 12

### 应用信息

- 版本: 2.5.11
- 安装包文件名:  cfa-2.5.11-premium-arm64-v8a-release.apk
- 应用来源: GitHub Releases

### 配置文件

```yml
https://drive.google.com/file/d/10Oe3uJKKig9y_hmiKO-e2XcEIblWT0qU/view?usp=drivesdk

文件在谷歌云盘。
```

### 日志

```raw
https://drive.google.com/file/d/10r3ng1cuD-Fxikue_cFBtKo5QDBn0wBA/view?usp=drivesdk

文件在谷歌云盘。
```

### 屏幕截图

截图中小于 25% 是因为停止使用 Clash for Android，而改用了一段时间 V2rayNG，且期间未执行 logcat。
![截图](https://s3.bmp.ovh/imgs/2022/07/21/097aa9ba80b8dba0.jpg)

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/505
