### ISSUE TITLE
[Feature Request] Layer is too terrific to interact!

### ISSUE THREAD

**Issue by AzukiAtsui** [Kr328/ClashForAndroid#1585]
### Feature Description

With the ClashForAndroid, I can easily click here and there then find the usually functions just like searching around the beach then get one sand stone. Confusing All-in-One proxy setting make the APP similar to a chaos kid toy box. Mans would like a book library style, which means each function should be placed intuitively at a clear prioritization. Directly, edge and dock are indispensable to improve UI effectiveness.

**Comment by Kr328** [comment]
Please provide specific improvements
