### ISSUE TITLE
节点中特殊字符的问题[Feature Request] 

### ISSUE THREAD

**Issue by xiaoxiongwn** [Kr328/ClashForAndroid#1586]
### 功能描述

clash软件有android、windows、还有openclash这几个版本，同一个节点，如果节点里面有特殊字符，比如“@”，则这个节点在windows版本可以使用，而android和open版本中就不能用，请问一下，原因何在？有办法解决吗？现在的节点里面好多都有这个@的特殊字符。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
