### ISSUE TITLE
[Feature Request] 节点中的特殊字符问题

### ISSUE THREAD

**Issue by xiaoxiongwn** [Kr328/ClashForAndroid#1587]
### 功能描述

clash软件有android、windows、还有openclash这几个版本，同一个节点，如果节点里面有特殊字符，比如“@”，则这个节点在windows版本可以使用，而android和open版本中就不能用，请问一下，原因何在？有办法解决吗？现在的节点里面好多都有这个@的特殊字符。

### 附加信息

比如ss://YWVzLTI1Ni1nY206a0RXdlhZWm9UQmNHa0M0@85.208.108.60:8882#%f0%9f%87%af%f0%9f%87%b5%3a%e6%97%a5这种节点，因为包括了@字符，所以无法更新使用。

**Comment by Kr328** [comment]
请使用 BUG 模板

**Comment by Kr328** [comment]
以及 ss:// 开头的链接并不被 clash 接受
