### ISSUE TITLE
Your project is included in awesome-vpn/wiki/Clients

### ISSUE THREAD

**Issue by hugetiny** [Kr328/ClashForAndroid#1590]
### 功能描述

Open WIKI for VPNs

https://github.com/awesome-vpn/awesome-vpn/wiki/Clients

Please feel free to edit, add, and correct

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
