### ISSUE TITLE
增加一个开关按钮／接口，让用户通过第三方实现自动化

### ISSUE THREAD

**Issue by collinsqq** [Kr328/ClashForAndroid#1591]
### 功能描述

增加一个开启vpn的快捷按钮A
增加一个关闭vpn的快捷按钮B
这个功能可以实现一些自动化，例如打开a软件时则自动启用快捷按钮A，自动打开VPN。
打开某国内软件时，自动打开快捷按钮b关闭vpn，好处的是省事,节省后台。希望作者能提供开关这两个接口，好让有需求的用户可按需开启

以上建议只供参考

### 附加信息

附录
若加入这两个按钮希望作者加个按钮检测状态。如果使用按钮a检测到vpn处于打开状态则不执行任何操作。如果使用按钮b检测到vpn处于关闭状态同样也不执行任何状态。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
