### ISSUE TITLE
[Feature Request] 不把浏览器设为排除 APP 的情况下让浏览器正常使用 QUIC

### ISSUE THREAD

**Issue by slusludy** [Kr328/ClashForAndroid#1592]
### 功能描述

在 Windows Clash Premium TUN 模式下，Chrome 访问 Bilibili 视频 CDN 的请求命中直连规则后，对电脑物理网卡抓包显示请求都基于 QUIC。
用同一个配置文件（`proxies` 显式 `udp: true`，`proxy-groups` 显式 `disable-udp: false`），但在 Clash for Android （premium、foss 和 Google Play 版都试了） 下 Chrome 对 Bilibili 的墙内 CDN 的请求命中直连规则后，抓包显示都基于 TCP。关掉 Clash for Android 或者在 Clash for Android 设置排除 APP后，抓包显示都基于 QUIC 。在不把微信设为排除 APP 时，抓包显示微信电话都基于 TCP，关掉 Clash for Android 或把微信设为排除应用后，微信电话都基于 UDP。
在 Android 用墙外网络电话 APP 打电话时，在 VPS 抓包，显示都基于 UDP。这说明在当前配置下 Clash for Android 能代理 UDP。在 Android 看 YouTube 时，在 VPS 抓包，显示都基于 TCP。
确实没必要让微信使用 Clash for Android 的 VPN，但有必要让 Chrome 使用。如果我是运营商，可以怀疑不基于 QUIC 而基于 TCP 访问 Bilibili 的墙内 CDN 的用户在用 Clash for Android。因此希望新增在不设置排除应用的情况下让 APP 正常使用 UDP。
|编号|设备|场景|Clash设置|翻墙/直连|应该基于|实际基于|符合预期|在哪抓包|
|---|---|---|---|---|---|---|---|---|
|1|Android|Bilibili|不排除APP|直连|QUIC|TCP||路由器|
|2|Android|Bilibili|排除APP或关闭|直连|QUIC|QUIC|√|路由器|
|3|Android|微信电话|不排除APP|直连|UDP|TCP||路由器|
|4|Android|微信电话|排除APP或关闭|直连|UDP|UDP|√|路由器|
|5|Android|墙外网络电话|不排除APP|翻墙|UDP|UDP|√|VPS|
|6|Android|YouTube|不排除APP|翻墙|QUIC|TCP||VPS|
|7|Windows|YouTube|TUN|翻墙|QUIC|QUIC|√|电脑物理网卡和VPS|
|8|Windows|Bilibili|TUN|直连|QUIC|QUIC|√|电脑物理网卡|

**Comment by Kr328** [comment]
设置 -> 网络 -> 系统代理 -> 关

**Comment by slusludy** [comment]
> 设置 -> 网络 -> 系统代理 -> 关

不愧是大佬，一眼找出问题的本质👍，多谢
