### ISSUE TITLE
[Feature Request]希望增加webdav

### ISSUE THREAD

**Issue by LIUH0961** [Kr328/ClashForAndroid#1596]
### 功能描述

希望增加webdav用于备份节点

**Comment by Kr328** [comment]
这个有什么必须由 Clash for Android 来实现的理由吗 

未来支持导出备份之后自己上传 或者通过 https://github.com/alexbakker/webdav-provider 保存文件不行吗

**Comment by LIUH0961** [comment]
这样比较方便，比如换手机的时候，有webdav就很方便只需要填入账号和密码就能实现节点快速导入！如果是自己上传备份的话感觉比较麻烦！

**Comment by LIUH0961** [comment]
就像surfboard一样，方便快捷

**Comment by Kr328** [comment]
要支持类似云同步的特性太麻烦了

不支持云同步的话 还不如使用 https://github.com/alexbakker/webdav-provider
