### ISSUE TITLE
[Feature Request] 节点链接带特殊字符时，节点就无法更新

### ISSUE THREAD

**Issue by xiaoxiongwn** [Kr328/ClashForAndroid#1597]
### 功能描述

节点中如果有特殊字符“@”花a，则节点链接无法更新。clash for  windows不存在这个问题，带有特殊字符的链接也是可以更新的。请问原因是什么，有什么办法解决吗？

### 附加信息

openclash和clash for android都有这个问题，但clash for windows没有影响，不知道是什么原因

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
