### ISSUE TITLE
[Feature Request] 配置文件在哪里下载

### ISSUE THREAD

**Issue by liudongbo** [Kr328/ClashForAndroid#1598]
### 功能描述

配置文件在哪里下载

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by liudongbo** [comment]
Thank you. Your email is received and will be handled  as soon as possible.
