### ISSUE TITLE
[Feature Request] android开发问题想咨询一下

### ISSUE THREAD

**Issue by wustwg** [Kr328/ClashForAndroid#1599]
### 功能描述

你好，我和你一样使用了vpnservice ,然后使用detachFd取出fd放到native层去使用，但是当我的应用创建的虚拟网卡被clash抢占之后，我的vpnservice并没调用onDestroy方法，导致我这边不知道应该什么时候去关闭fd.
而我测试calsh, clash的虚拟网卡被其他应用抢占之后，vpnservice 会被立即调用 onDestroy方法，立即停止代理。

我想问下 你知道这是为什么吗？明明是很相近的代码，表现却不一样。
我测试过：如果不用detachFd， 可以在虚拟网卡被抢占之后收到onDestroy方法的调用；用了 detachFd之后基本上就不行了。

**Comment by Kr328** [comment]
我不知道，我只知道 Clash 现在的实现是能用的，而且是一开始就这样，没有踩过其他坑。
