### ISSUE TITLE
顶部状态栏不出现vpn标示

### ISSUE THREAD

**Issue by sensen1** [Kr328/ClashForAndroid#160]
从14版本升级到16的，小米k20p
miui10系统
universal版和arm版都出现类似的问题，开启后顶部状态栏不出现clash的图标也不出现vpn的图标，但是好像是不影响工作。
手动进入vpn设置那里，点开启vpn提示需要先添加一个vpn，但clash明显已经在下面。

**Comment by Kr328** [comment]
系统问题
