### ISSUE TITLE
http请求转成了https

### ISSUE THREAD

**Issue by XianRenn** [Kr328/ClashForAndroid#1600]
### Describe the bug

我使用clash做前置代理，转发到charles代理上，，如果手机端安装配置了charles的证书后，手机内请求http的应用经过clash代理之后转发到charles的全部成了https请求

### To Reproduce

...
我使用clash做前置代理，转发到charles代理上，，如果手机端安装配置了charles的证书后，手机内请求http的应用经过clash代理之后转发到charles的全部成了https请求

### Device Info

- Device:
- ROM:
- Android Version:
11

### Application Info

- Version:
- APK filename:
- Distribution Channel:
11

### Configure File

```yml
11
```

### Logs

```raw
11
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by XianRenn** [comment]
clash是根据代理远端的地址去判断的是否https吗，而不是应用本身发出的请求
