### ISSUE TITLE
http转https

### ISSUE THREAD

**Issue by XianRenn** [Kr328/ClashForAndroid#1601]
### 功能描述

场景：通过clash作为前置，代理至电脑里面的charles,.手机端安装了证书之后，会导致所有经过clashz转发的http请求重定向为https请求。

### 附加信息

场景：通过clash作为前置，代理至电脑里面的charles,.手机端安装了证书之后，会导致所有经过clashz转发的http请求重定向为https请求。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
