### ISSUE TITLE
请求能够自行添加geoip文件

### ISSUE THREAD

**Issue by WuYang09661** [Kr328/ClashForAndroid#1604]
### 功能描述

内置的geoip使用geoip,cn,direct时观看台湾地区tiktok直播时会直连，（应为内容偏好台湾所以选择台湾地区的tiktok）希望能够增加这一功能，这真的很难受！！！希望作者采纳，作者大大辛苦啦！

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
