### ISSUE TITLE
[Feature Request] 添加手动添加或选择geoip的功能

### ISSUE THREAD

**Issue by WuYang09661** [Kr328/ClashForAndroid#1606]
### 功能描述

内置的geoip使用geoip,cn,direct时观看台湾地区tiktok直播时会直连，希望能够增加这一功能，这真的很难受！！！希望作者采纳，作者大大辛苦啦！

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1307
