### ISSUE TITLE
[BUG] io: read/write on close pipe

### ISSUE THREAD

**Issue by yu-steven** [Kr328/ClashForAndroid#1607]
### 描述此错误

io问题

### 如何复现该错误

触发此事件需要特定设备，但是一旦可以触发，就一直可以触发

### 设备信息

- 机型: 华为手机
- 系统类型: 鸿蒙 2.0
- Android 版本: 鸿蒙系统不显示安卓版本(我不知道)

### 应用信息

- 版本: 2.5.11.premium
- 安装包文件名: Google Play 安装包
- 应用来源: Google Play

### 配置文件

```yml
🈚️
```

### 日志

```raw
🈚️
```

### 屏幕截图

![D7C3C0BD-AD9C-407D-A1D6-8A20C67DEC9E](https://user-images.githubusercontent.com/78414278/182079993-0c9dd3d3-b2a0-4538-9e64-6ddcd27d292f.jpeg)
![E1CE66B5-F41E-4F9E-9E47-4406BAD0F04B](https://user-images.githubusercontent.com/78414278/182079998-b2d940cc-ba02-4e26-9291-92e784125624.jpeg)

### 附加信息

发生概率不大，但是存在

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by yu-steven** [comment]
？
那我提的问题呢？

**Comment by Kr328** [comment]
日志没有，配置没有，我又不会算命，怎么知道为什么。

**Comment by yu-steven** [comment]
> 日志没有，配置没有，我又不会算命，怎么知道为什么。

哦，那确实没办法
