### ISSUE TITLE
[BUG] Samsung Galaxy Z Fold 3 5G 无法链接 VPN

### ISSUE THREAD

**Issue by haikouwang** [Kr328/ClashForAndroid#1608]
### 描述此错误

Samsung Galaxy Z Fold 3 5G 无法链接 VPN
安卓12 - OneUI 4.1
打开 cfa 主界面后，点顶部的 “已停止” 链接 无法创建 VPN 链接，cfa 主界面无反应（但是界面并没有卡死，就是点不开 VPN）
订阅是已经导入的，并且订阅确定是正常的。

### 如何复现该错误

步骤 1: 打开 cfa 导入并且选中订阅配置；
步骤 2: cfa 首页试图打开 VPN 链接；
步骤 3: 没反应 ... 
...

### 设备信息

- 机型:Samsung Galaxy Z Fold 3 5G
- 系统类型:OneUI 4.1
- Android 版本:12

### 应用信息

- 版本: 2.5.11
- 安装包文件名: [cfa-2.5.11-premium-arm64-v8a-release.apk](https://github.com/Kr328/ClashForAndroid/releases/download/v2.5.11/cfa-2.5.11-premium-arm64-v8a-release.apk)
- 应用来源: https://github.com/Kr328/ClashForAndroid/releases/download/v2.5.11/cfa-2.5.11-premium-arm64-v8a-release.apk

### 配置文件

```yml
没有
```

### 日志

```raw
没有
```

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/342
