### ISSUE TITLE
chrome中网页版YouTube可以看，但是用APP就进不去

### ISSUE THREAD

**Issue by hxy649779199** [Kr328/ClashForAndroid#161]
用chrome网页可以进去YouTube，但是APP进不去。这个问题我用V2RayNG试过了，V2RayNG没有什么问题APP和网页都行   但是用了clash外网APP除了YouTube其他都没啥问题  另外clash中的设置和规则我已经搞好了 应该不是我设置问题

**Comment by hxy649779199** [comment]
日志也很正常  难道是我手机有问题?

**Comment by xiaogouxo** [comment]
很多rom中把Google play服务gms和 Google服务框架gsf 把这两个也走代理可破

**Comment by hxy649779199** [comment]
> 很多rom中把Google play服务gms和 Google服务框架gsf 把这两个也走代理可破

添加到白名单里面还是不行

**Comment by hxy649779199** [comment]
> 很多rom中把Google play服务gms和 Google服务框架gsf当作系统服务， 勾选显示系统程序把这两个跟youtube 一块走代理可破，Gmail也是同理，只勾gmail 也会打不开。不过gms gsf这两个走代理了，如果服务器配置不正确，会出现err fin120 每两分钟自动断开重试现象，引起耗电

刚刚我又试着把Android系统勾选了  现在好了  谢谢

**Comment by xiaogouxo** [comment]
可能就是传说中的googleapis.cn问题，国内rom走gms上的是国内的地址而非.com ，大多数规则cn走直连，所以需要规则中强制这个域名走代理，不然Google的服务接口都连不上

**Comment by xiaogouxo** [comment]
@hxy649779199 OK:smile:

**Comment by flyhunterl** [comment]
> > 很多rom中把Google play服务gms和 Google服务框架gsf当作系统服务， 勾选显示系统程序把这两个跟youtube 一块走代理可破，Gmail也是同理，只勾gmail 也会打不开。不过gms gsf这两个走代理了，如果服务器配置不正确，会出现err fin120 每两分钟自动断开重试现象，引起耗电
> 
> 刚刚我又试着把Android系统勾选了 现在好了 谢谢

我的问题和你差不多  不过我是能打开APP 但是不能登录 请问你是在哪勾选的 clash没找到分应用代理啊

**Comment by SpikerA** [comment]
很奇怪，按照上述的操作了，但是更新应用进度条一直在滚动.关闭clash之后才更新完成。

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复

**Comment by xjnotxj** [comment]
> 很多rom中把Google play服务gms和 Google服务框架gsf当作系统服务， 勾选显示系统程序把这两个跟youtube 一块走代理可破，Gmail也是同理，只勾gmail 也会打不开。不过gms gsf这两个走代理了，如果服务器配置不正确，会出现err fin120 每两分钟自动断开重试现象，引起耗电

没懂什么意思？app 里要怎么操作呢？？

**Comment by tsrjwss** [comment]
> > 很多rom中把Google play服务gms和 Google服务框架gsf当作系统服务， 勾选显示系统程序把这两个跟youtube 一块走代理可破，Gmail也是同理，只勾gmail 也会打不开。不过gms gsf这两个走代理了，如果服务器配置不正确，会出现err fin120 每两分钟自动断开重试现象，引起耗电
> 
> 刚刚我又试着把Android系统勾选了 现在好了 谢谢

在哪儿设置啊

**Comment by tsrjwss** [comment]
https://www.right.com.cn/forum/thread-1998362-5-1.html 这里有讲。大部分人反映，是小米手机的问题，亲测重启可以解决

**Comment by georgez1379** [comment]
在clash把网络＞控制应用 将系统应用里Google和Android相关的app都勾选，再次打开clash就没问题了。

**Comment by VELON** [comment]
googleapis.cn被识别为CN没有走代理的问题，在规则中添加一条，我这里立即修复了问题。
