### ISSUE TITLE
[设置-网络-访问控制应用包列表]里面为什么没有{play商城]?

### ISSUE THREAD

**Issue by hannburglar** [Kr328/ClashForAndroid#1613]
### 功能描述

[设置-网络-访问控制应用包列表]里面为什么没有{play商城]?

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
