### ISSUE TITLE
[BUG] 华为手机病毒查杀报毒

### ISSUE THREAD

**Issue by xiaomuhun** [Kr328/ClashForAndroid#1615]
### 描述此错误

我从GitHub下载并安装clash后，华为手机管家的病毒查杀就开始报毒。
显示的是
感染病毒：          Evo-gen
危险等级 ：         高
详情 ：                 无

### 如何复现该错误

步骤 1: 从GitHub下载并安装clash后使用就开始报毒
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:JNY-LX1
- 系统类型:MIUI
- Android 版本:10

### 应用信息

- 版本:2.5.9.foss
- 安装包文件名:
- 应用来源:GitHub

### 配置文件

```yml
https://1drv.ms/u/s!Ap2wf13kWX0oghc2h-7N8deIqbRz
```

### 日志

```raw
[TCP] 127.0.0.1:57142 --> translate.googleapis.com:443 match DomainKeyword(google) using 🌏 国外网站[🇭🇰 香港 05]
[TCP] 127.0.0.1:57112 --> github.githubassets.com:443 match DomainKeyword(github) using 🌏 国外网站[🇭🇰 香港 05]
```

### 屏幕截图

![Screenshot_20220810_153738_com huawei systemmanager](https://user-images.githubusercontent.com/69281659/183875940-800edbdc-21e0-4333-9964-10e7be330715.jpg)

**Comment by AkariiinMKII** [comment]
点卸载

**Comment by xuhaoyang** [comment]
@xiaomuhun 建议不要用

**Comment by Kr328** [comment]
如果信不过 请换用 shadowsocks-android 或其他

**Comment by xiaomuhun** [comment]
我只是想询问一下，有没有什么解决办法，这个显示太碍眼了 😂
