### ISSUE TITLE
[Feature Request] 2.5.11 foss切换到全局规则不能记忆

### ISSUE THREAD

**Issue by likaifenkeng** [Kr328/ClashForAndroid#1617]
### 功能描述

2.5.11 foss切换到全局规则不能记忆.
切换规则时，提示仅当前会话有效。断开连接再重新链接，自动使用规则模式。
希望能保存当前选择的规则。
redmi k20
MIUI V12.5.2.0.RFJCNXM

**Comment by Kr328** [comment]
没错 就是这样设计的
