### ISSUE TITLE
[Feature Request] GooglePlay版请求更新

### ISSUE THREAD

**Issue by iMarschen** [Kr328/ClashForAndroid#1619]
### 功能描述

GooglePlay上的版本还停留在2.5.4。为什么不更新了呢？

**Comment by EKyero** [comment]
**实验性版本** 和 **不稳定版本** 都只是在github上发, **较稳定版本** 才会在play上发

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
