### ISSUE TITLE
[Feature Request] 希望简化添加、更新配置的功能

### ISSUE THREAD

**Issue by f2sky** [Kr328/ClashForAndroid#1620]
### 功能描述

**建议：降低配置文件使用门槛**

**1、提供默认初始化配置文件**
需要自己提供`yaml`配置文件，并且把对应的协议参数填入正确的位置。这对于大多数非软件行业的用户来说，门槛过高。
建议默认提供一个通用型的配置模板，满足基本的网络连接需求。

**2、降低配置参数难度**
在提供通用的模板之后，可以通过`扫码`的方式，将对应的网络协议（如shadowsocks、Vmess、Trojan等）配置参数加入模板配置文件，实现快速上网。

很多新手都是从网络上找别人分享的个性化配置文件，或者在线转化工具，这必然带来隐私和安全性的问题。
建议能够像其它的客户端一样，适当简化使用门槛和难度。

**Comment by Kr328** [comment]
1. 默认配置文件就是空的，在 Clash for Android 除了代理、代理组和规则之外，其他的任何配置都不重要，这已经是最简化的配置了。
2. 如上一点所述，用户仍需要提供代理、代理组和规则，且这三者不可分割互相依赖，无法经过简单程序符合意图的增删任何附属内容。
