### ISSUE TITLE
[BUG]  qq邮箱，spotify.等无法登录谷歌账号

### ISSUE THREAD

**Issue by GWLCZY** [Kr328/ClashForAndroid#1624]
### 描述此错误

qq邮箱和spotify都不能登录谷歌账号。

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
无

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
无

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

所有版本

### 配置文件

```yml
无
```

### 日志

```raw
无
```

### 屏幕截图

无

### 附加信息

无

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
