### ISSUE TITLE
希望可以添加cfw一样的parser

### ISSUE THREAD

**Issue by 2487163254** [Kr328/ClashForAndroid#1630]
### 功能描述

因为机场提供的订阅连接里有一个proxy-group是广告。希望可以用parser删除。
同时也可以用来自定义规则

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
