### ISSUE TITLE
[Feature Request] 可否加入修改测速地址的功能?

### ISSUE THREAD

**Issue by FairyWorld** [Kr328/ClashForAndroid#1632]
### 功能描述

晚上测速经常会全部节点都联不通导致以为节点挂了, 但是实际节点是可以使用的而且速度页很快, v2ray的测速是正常的, 应该是内置测速地址有问题, window版的clash也有这个问题, 但是修改测速地址后就很少出现全部节点测速联不通实际正常的情况。

**Comment by Kr328** [comment]
测试地址也是由你的配置文件提供
