### ISSUE TITLE
[Feature Request] 希望增加用来预处理的 parser 编辑入口

### ISSUE THREAD

**Issue by intMojIBakE** [Kr328/ClashForAndroid#1634]
### 功能描述

在 clash for windows 中，可以对 profiles 增加 parsers 以进行预处理。
该功能在 cfw 中的入口是：`Settings -> Profiles -> Parsers`
cfw 对此功能的文档在[此页](https://docs.cfw.lbyczf.com/contents/parser.html)

**Comment by EKyero** [comment]
@intMojIBakE https://github.com/Kr328/ClashForAndroid/issues/1416#issuecomment-1058838990

**Comment by intMojIBakE** [comment]
> @intMojIBakE [#1416 (comment)](https://github.com/Kr328/ClashForAndroid/issues/1416#issuecomment-1058838990)

got it
