### ISSUE TITLE
[Feature Request] 请问有没有大佬请教一下，图中的端口怎么使用啊

### ISSUE THREAD

**Issue by motian16** [Kr328/ClashForAndroid#1635]
### 功能描述

[上面的允许来自局域网的连接，是指一台手机订阅结点，然后共享给其他手机使用吗，然后就是一些奇奇怪怪的端口，具体是什么意思啊

### 附加信息

![Screenshot_2022-08-29-19-32-57-58_1ed813789000d97ac1c6fc69779c1198](https://user-images.githubusercontent.com/89713447/187192709-62e17647-ae96-4183-bda8-eb4d18b4df32.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
