### ISSUE TITLE
[Feature Request] rocketcloud. xyz网站进不去了

### ISSUE THREAD

**Issue by Anlonekrly** [Kr328/ClashForAndroid#1638]
### 功能描述

现在无法进入rocketcloud网站不能充值了

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
ClashForAndroid 项目没有任何网站
