### ISSUE TITLE
[BUG] 无论我换什么新节点，连接总能成功几秒后面就得刷新，已排除节点问题

### ISSUE THREAD

**Issue by kksj3** [Kr328/ClashForAndroid#1639]
### 描述此错误

连接节点后
使用外网一下，成功后，clash仍然链接，但网连不上了，已排除节点问题
只能使用一秒外网

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
打开clash
点击连接
打开电报

### 设备信息

- 机型:
- 系统类型:
- Android 版本:

### 应用信息

- 版本:2.5.9.foss
- 安装包文件名:com.github.kr328.clash.foss
- 应用来源:

### 配置文件

```yml
不会
```

### 日志

```raw
[APP] Logcat level: info
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
