### ISSUE TITLE
fcm代理推送问题

### ISSUE THREAD

**Issue by QingKongBaiYu** [Kr328/ClashForAndroid#164]
之前打开代理后fcm每隔130s就会重连，之后在其他issue下找到方法，通过不代理Google play services可以解决但是会导致部分功能异常（比如部分游戏无法登录）。
能否通过内置规则绕过fcm和gcm网址解决？

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/125#issuecomment-589662672
