### ISSUE TITLE
[Feature Request] 在安卓上有没有办法设置绕过ipv6网站？

### ISSUE THREAD

**Issue by zeuszc** [Kr328/ClashForAndroid#1641]
### 功能描述

有很多机场本身不支持ipv6,在这种情况下开启clash无论设置里是否开ipv6,实际上都无法打开任何ipv6的网站,我甚至连ipv6test都打不开.

但手机本身网络对ipv6支持没有问题.所以想请教一下在手机上该如何设置将某几个国内的纯ipv6网站绕过呢？

**Comment by Kr328** [comment]
自己写 IPCIDR 规则

**Comment by zeuszc** [comment]
> 自己写 IPCIDR 规则

感谢大佬回复啊。我不太懂，再请教一下啊，电脑上写个比如   test-ipv6.com dierct我知道，手机里覆盖的话应该写哪一栏？是ipcidr fallback里直接写上要绕开的域名么？

**Comment by Kr328** [comment]
@zeuszc 直接换成文件类型配置 直接改文件

**Comment by zeuszc** [comment]
> @zeuszc 直接换成文件类型配置 直接改文件

感谢大佬回复！

是现成的没有地方直接写？

有没有可能加一个这个功能呢？因为机场都是订阅的，隔三岔五的需要更新，如果不能直接覆写的话就意味着每次出门在外的时候订阅一更新就要折腾一下了。

**Comment by Kr328** [comment]
@zeuszc https://github.com/Kr328/ClashForAndroid/issues/295#issuecomment-616258969

**Comment by zeuszc** [comment]
> @zeuszc [#295 (comment)](https://github.com/Kr328/ClashForAndroid/issues/295#issuecomment-616258969)

谢谢解答！
