### ISSUE TITLE
【推荐】稳定高速安全的机场节点

### ISSUE THREAD

**Issue by hejiezhongxin** [Kr328/ClashForAndroid#1642]
### 功能描述

稳定安全快速的机场节点：[稳定快速机场](https://github.com/hejiezhongxin/FreePAC)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
