### ISSUE TITLE
[Feature Request] 你好，安卓包有那么多个，能否在md注明一下各个包的使用范围

### ISSUE THREAD

**Issue by tzbob888** [Kr328/ClashForAndroid#1643]
### 功能描述

大佬能否照顾一下小白啊,不知道选择哪个包呀 都是APK 有premium_arm 有premium_x86_64   还有foss

**Comment by Kr328** [comment]
你既然这都看不明白 我在 md 里写

cfa-version-arm64-premium 是 arm64 指令集的 premium 内核 你能看明白吗

有时间来写这个 Google 一下每个分词早解决了

**Comment by Kr328** [comment]
不会选就选最大的

**Comment by tzbob888** [comment]
好的，谢谢
