### ISSUE TITLE
[QUESTION] 请问下 “Allow Bypass” 的作用是什么？ 

### ISSUE THREAD

**Issue by dunmorogher** [Kr328/ClashForAndroid#1645]
### 功能描述

![image](https://user-images.githubusercontent.com/41850822/188808438-c4ecff8e-0349-4531-bbfe-c50353314d2d.png)

想请问下上面 “Allow Bypass” 的作用是什么呢？按照描述，是否选了这个过后所有的 app 流量就都不会经过 Clash for Android 来代理了？那这个开启过后是不是界面上选择的 Global Mode 全局模式也没有用了呢？

谢谢！

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
