### ISSUE TITLE
[BUG] - QUESTION：请问下 “Allow Bypass” 的作用是什么？ 

### ISSUE THREAD

**Issue by dunmorogher** [Kr328/ClashForAndroid#1646]
### 描述此错误

![image](https://user-images.githubusercontent.com/41850822/188809055-cfe07515-6e3e-4f92-8da7-4d0c2ee0563e.png)

想请问下上面 “Allow Bypass” 的作用是什么呢？按照描述，是否选了这个过后所有的 app 流量就都不会经过 Clash for Android 来代理了？那这个开启过后是不是界面上选择的 Global Mode 全局模式也没有用了呢？

谢谢！

### 如何复现该错误

None.

### 设备信息

- 机型:
- 系统类型:
- Android 版本:

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
None.
```

### 日志

```raw
None.
```

**Comment by Kr328** [comment]
https://developer.android.com/reference/android/net/VpnService.Builder#allowBypass()
