### ISSUE TITLE
2.4.14以后的版本，和adguard同时开启时不能正常代理工作

### ISSUE THREAD

**Issue by AndyandAndy00** [Kr328/ClashForAndroid#1649]
### 功能描述

手机非root状态下，使用2.4.14版本的clash和adguard同时开启，可以正常代理访问Google。自从更新2.4.14以后的版本，代理功能就失效了，不确定是软件的bug，还是新版本需要额外的参数设置。2.4.14这个版本虽然可以正常与adguard共存使用，但是不支持识别配置文件中proxy-providers下的filter参数，无法实现节点过滤。希望作者能给解决方案

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
