### ISSUE TITLE
1.1.7从文件导入配置失败

### ISSUE THREAD

**Issue by Daibogit** [Kr328/ClashForAndroid#165]
同一个配置文件，1.1.7从文件导入配置失败，但1.1.6可以。
这个模板
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/GeneralClashConfig.yml
是我编码格式问题？在1.1.6中先导入再qe中编辑将节点信息最后另存为新文件导入后可以了！原始文件1.1.7确实不可以导入。

**Comment by Kr328** [comment]
你倒是贴错误啊

**Comment by gang4399** [comment]
> 同一个配置文件，1.1.7从文件导入配置失败，但1.1.6可以。
> 这个模板
> https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/GeneralClashConfig.yml
> 是我编码格式问题？在1.1.6中先导入再qe中编辑将节点信息最后另存为新文件导入后可以了！原始文件1.1.7确实不可以导入。

这个文档有注释，近期做了少量改动。你需要把错误截图出来

**Comment by zhibaogoo** [comment]
1.1.8已经可以导入了！

**Comment by zhibaogoo** [comment]
网站转换的链接一直可以正常导入的，1.1.8与1.1.9不论是本地配置还是链接都可以正常使用了！

**Comment by taken7** [comment]
> 网站转换的链接一直可以正常导入的，1.1.8与1.1.9不论是本地配置还是链接都可以正常使用了！

怎么导入

**Comment by gang4399** [comment]
这个问题已经在新版不存在了。
