### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by WangHuimin520** [Kr328/ClashForAndroid#1653]
### 功能描述

修改模式的时候只在本次有效，不能一直保持，希望可以一直保持着

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by EKyero** [comment]
@WangHuimin520 覆写
