### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xiaosw** [Kr328/ClashForAndroid#1654]
### 描述此错误

Windows 下编译报错：ClashForAndroid\core\src\main\cpp\main.c:7:10: fatal error: 'libclash.h' file not found

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
ClashForAndroid/core/src/main/cpp/main.c:7:10: fatal error: 'libclash.h' file not found
#include "libclash.h"
         ^~~~~~~~~~~~
1 error generated.
[3/4] Building C object CMakeFiles/bridge.dir/jni_helper.c.o
ninja: build stopped: subcommand failed.
```

### 日志

```raw
ClashForAndroid/core/src/main/cpp/main.c:7:10: fatal error: 'libclash.h' file not found
#include "libclash.h"
         ^~~~~~~~~~~~
1 error generated.
[3/4] Building C object CMakeFiles/bridge.dir/jni_helper.c.o
ninja: build stopped: subcommand failed.
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
