### ISSUE TITLE
Proxy chain, and support so ls proxy in setting 

### ISSUE THREAD

**Issue by zeptola20** [Kr328/ClashForAndroid#1659]
### Feature Description

I want Clash to be able to proxy chain like Matsuri.
I want all traffic to pass through the proxy that we entered in the settings, proxies like socks or http

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
