### ISSUE TITLE
希望能添加对android tv的支持

### ISSUE THREAD

**Issue by easyinplay** [Kr328/ClashForAndroid#166]
很感谢开发者开发这么好用的软件，最近更新也越来越好用。目前国内很多电视都是android系统，但是安装的时候总是提示安装失败，试了家里的几个电视都是同样的情况，希望能够添加对android tv的支持，祝越来越好

**Comment by Kr328** [comment]
#58

**Comment by Kr328** [comment]
你认为你的 TV 满足以下条件吗
1. Android 7.0+
2. arm64/arm32/x86/x64
