### ISSUE TITLE
[Feature Request] support socks and http proxy 

### ISSUE THREAD

**Issue by zeptola20** [Kr328/ClashForAndroid#1661]
### Feature Description

I want to set a proxy in the settings and all the traffic of Clash goes through that proxy

**Comment by Kr328** [comment]
it is already supprted

**Comment by zeptola20** [comment]
Please tell me where i can find that

**Comment by Kr328** [comment]
@zeptola20 https://github.com/Dreamacro/clash/wiki/Configuration
