### ISSUE TITLE
[Feature Request] 开机自动连接？

### ISSUE THREAD

**Issue by tylerlamp** [Kr328/ClashForAndroid#1662]
### Feature Description

我装到了我的小米box上，每次开机都要手动进行连接，能否添加一个自动连接的功能？

**Comment by Kr328** [comment]
@tylerlamp 设置 - 应用 - 自动重启

**Comment by tylerlamp** [comment]
奥，原来这个就是。但是这个名字有点模糊，重启我以为是已经在运行然后再restart，会不会改为开机启动之类的比较好？

**Comment by Kr328** [comment]
@tylerlamp 这里包含了多个重启行为

1. 应用更新后按需启动
2. 系统启动后按需启动

按需启动
1. 根据应用死亡前的状态决定是否启动

**Comment by tylerlamp** [comment]
做了下测试，我不确定有没有自动启动，但是可以肯定并没有连接，还是要手动连接

**Comment by xuhaoyang** [comment]
@tylerlamp 不如看看你的系统是不是默认不给自动启动
