### ISSUE TITLE
[BUG] self signed certificate error in import

### ISSUE THREAD

**Issue by hiddify** [Kr328/ClashForAndroid#1663]
### Describe the bug

In the url section in profiles when we enter a url with self signed certificate it will show network error but it should show an error to save the certificate.

### To Reproduce

use https://self-signed.badssl.com/ as the url in Download from URL section to see the error

### Device Info

All devices

### Application Info

all

### Configure File

```yml
it is before the configuration
```

### Logs

```raw
not related
```

**Comment by Kr328** [comment]
https://developer.android.com/about/versions/nougat/android-7.0#default_trusted_ca

**Comment by hiddify** [comment]
But how we can have self signed urls in proxy, chrome, etc.?

**Comment by Kr328** [comment]
it is impossible this major version

We will add built-in trust manager next major version

**Comment by hiddify** [comment]
Thank you
