### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by sysonetg** [Kr328/ClashForAndroid#1665]
### 功能描述

现在内置更新配置的时候我发现用的是HTTP/1.1，一个是对服务器压力大，第二就是效率不高，请求把软件内置的更新配置方式升级到HTTP/2.0协议

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
