### ISSUE TITLE
Google pixel 3 无法安装apk

### ISSUE THREAD

**Issue by JalynKar** [Kr328/ClashForAndroid#167]
1.1.6、1.1.7版本都试过，无法安装apk。

**Comment by Kr328** [comment]
你安装的哪个文件

**Comment by JalynKar** [comment]
> 你安装的哪个文件

app-x86_64-release.apk

**Comment by JalynKar** [comment]
> > 你安装的哪个文件
> 
> app-x86_64-release.apk

16.3M，体积最大的那个

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/75444217-0150d180-599e-11ea-81e1-f110d2a2c9e5.png)
你觉得哪个是最大的

**Comment by JalynKar** [comment]
> ![image](https://user-images.githubusercontent.com/39107975/75444217-0150d180-599e-11ea-81e1-f110d2a2c9e5.png)
> 你觉得哪个是最大的

看走眼了……非要让我这么尴尬吗
