### ISSUE TITLE
[BUG]  Handshake error

### ISSUE THREAD

**Issue by hiddify** [Kr328/ClashForAndroid#1674]
### Describe the bug

In very restricted internet like Iran when we want to use url for connecting to server it shows the following error.
![image](https://user-images.githubusercontent.com/114227601/194718016-bbbf7483-7084-4686-b0e9-464eff44f0bf.png)

Outside Clash it works, in chrome, windows, clash for windows all work but in clash for android it won't work

It is interesting that outside Iran we don't encountered with such issue
Would you please help me

### To Reproduce

i can not you should live in Iran

### Device Info

all androids

### Application Info

- Version:
- APK filename:
- Distribution Channel:

### Configure File

```yml
befoer config
```

### Logs

```raw
,
```

**Comment by Kr328** [comment]
fill device info & app info form pls

**Comment by hiddify** [comment]
I have seen this issue in several client in Iran. It happens only for CFA and CFW works well

App info: 2.5.9 permium
Android 12
Device: Poxo X3 GT

**Comment by hiddify** [comment]
Can you repeat the request multiple time if one of them fails?  Maybe it resolves the problem
