### ISSUE TITLE
[BUG] profile not selected after adding new profile

### ISSUE THREAD

**Issue by hiddify** [Kr328/ClashForAndroid#1676]
### Describe the bug

When we add a profile, the profile is unselected by default. However, similar to clash for windows, it should select the newly added profile.

### To Reproduce

Step 1: add a new profile
Step 2: click save
Step 3: you will see that it will not be selected

### Device Info

- Device:
- ROM:
- Android Version:

### Application Info

- Version:
- APK filename:
- Distribution Channel:

### Configure File

```yml
general
```

### Logs

```raw
-
```

**Comment by Kr328** [comment]
It is intended.

Clash allow hot reload, change active profile after added may cause unexpected behaviour.
