### ISSUE TITLE
【推荐】稳定安全的机场节点

### ISSUE THREAD

**Issue by streewin** [Kr328/ClashForAndroid#1683]
### 功能描述

稳定安全的机场节点：[https://github.com/streewin/FreePAC](https://github.com/streewin/FreePAC)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
