### ISSUE TITLE
官网不在了嘛？[Feature Request] 

### ISSUE THREAD

**Issue by mmxxfff** [Kr328/ClashForAndroid#1684]
### 功能描述

现在软件更新了，但是配置文件更新失败呀？没法用了，能否给个官网？或者如何连接成功的教程

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
