### ISSUE TITLE
[Feature Request] 官网不在了嘛？？

### ISSUE THREAD

**Issue by mmxxfff** [Kr328/ClashForAndroid#1685]
### 功能描述

软件用不了了，更新了，但是配置文件无法更新，能否给个官网或者教程呀？

**Comment by EKyero** [comment]
@mmxxfff

**Comment by EKyero** [comment]
![Uploading Screenshot_20221015-102040_Clash for Android.png…]()

**Comment by EKyero** [comment]
![Screenshot_20221015-102040_Clash for Android](https://user-images.githubusercontent.com/29628846/195964594-925fcb05-70ec-4c5d-a413-626ed0ddb806.png)

**Comment by mmxxfff** [comment]
？？？什么意思？

**Comment by Kr328** [comment]
Clash for Android 是免费软件 没有官网 不提供配置 谢谢
