### ISSUE TITLE
希望能够额外配置网址规则。[Feature Request] 

### ISSUE THREAD

**Issue by yamazakitouma** [Kr328/ClashForAndroid#1687]
### 功能描述

有一个网址在规则模式下不能直接访问，必须得切全局模式才可以正常访问。能否增加一个额外的规则配置功能？让我把这个网址配置进去之后，实现在规则模式下的正常访问。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
