### ISSUE TITLE
[Feature Request] 希望增加额外的网址配置功能。

### ISSUE THREAD

**Issue by yamazakitouma** [Kr328/ClashForAndroid#1688]
### 功能描述

嗯，有一个网址。在规则模式下无法正常访问。必须给切换为全局模式才可以正常访问。这种情况下，能否提供一种配置功能，让我将这个网址配置进去之后，实现在规则模式下的正常访问。

**Comment by Kr328** [comment]
自己编写配置文件 即可

用 provider 可以引入其他外部的代理或规则源
