### ISSUE TITLE
[Feature Request] 请问要下载Releases里哪个版本？

### ISSUE THREAD

**Issue by pangfeiyo** [Kr328/ClashForAndroid#1696]
### 功能描述

一直用google play更新的，才发现github上也有项目了，现在谷歌那边是2.5.9.premium，请问在Releases里下载哪个版本？
还想问一下这些版本有啥区别，谢谢作者
![Q7~%CO~~D6T V~BZTGPNA%J](https://user-images.githubusercontent.com/35551631/196587451-89f0e741-fd06-4092-bb6b-23461f75eea9.png)

**Comment by 2455DD** [comment]
premium 和 foss版的区别是前者是闭源的而后者是开源的，具体区别参见[Clash 的 Wiki](https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features)
关于架构的选择，请参见自己的设备CPU架构选择

**Comment by pangfeiyo** [comment]
> Premium 版本的区别和是闭源的开源的，具体区别参见[Wiki](https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features) 关于架构的选择，请查看自己的设备 CPU 架构选择

谢谢
