### ISSUE TITLE
网络信号差的环境下存在一些问题

### ISSUE THREAD

**Issue by TragicLifeHu** [Kr328/ClashForAndroid#17]
软件版本: 1.0.13 Alpha
节点信息: 日本，使用 VMSS
网络环境: 2.4GHz WIFI，信号强度 -80dB
系统版本: Android 10
软件 Log: 无内容，软件可能存在 Bug
系统语言: 繁体中文(台湾)
应用设置: 全部默认
问题详情:
Google Feed 无法刷新，显示登录账户错误，但 Chrome 和 Google Play 商店正常工作
所有节点 Ping 值大于 3000ms，甚至 N/A，国内 Ping 值结果相同，也大于 2000ms
相同网络条件下 V2RayNG 使用同一节点不存在此问题

**Comment by Kr328** [comment]
反馈上游 请
