### ISSUE TITLE
修复一键拉起

### ISSUE THREAD

**Issue by Tmpeople** [Kr328/ClashForAndroid#170]
修复一键拉起clash订阅导入 一键导入功能

**Comment by Kr328** [comment]
@Tmpeople 你知道 Markdown 是啥吗

**Comment by Tmpeople** [comment]
不太了解只知道1.1.9依旧不能一键导入。。。。

**Comment by Kr328** [comment]
@Tmpeople Markdown 和你说的这个 一点关系都没有

**Comment by Tmpeople** [comment]
好的  已经修改问题  谢谢大佬指导

**Comment by gang4399** [comment]
他说的可能是从类似这种站点一键拉起，早期版本里面是可以的。现在的都调不起来。

**Comment by wt054175** [comment]
强烈请求修复一键订阅，没有这个太痛苦了

**Comment by Kr328** [comment]
#35
