### ISSUE TITLE
[BUG] 订阅链接无法正常导入/更新

### ISSUE THREAD

**Issue by ECeternalcat** [Kr328/ClashForAndroid#1703]
### 描述此错误

在导入链接后点击保存会提示x509:certificate signed by unknown authority，已经换过多个链接尝试。在windows的clash以及路由器的clash使用时都正可以正常导入。

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:小米10 Pro/索尼xperia xz1c
- 系统类型:miui/aosp
- Android 版本:12/11

### 应用信息

- 版本:2.5.11-premium
- 安装包文件名:cfa-2.5.11-premium-arm64-v8a-release.apk
- 应用来源:Github

### 配置文件

```yml
https://getnode.dksb.store/subscribe/130028/0xz6CkttBCYB
由于是导入链接时的问题，我在此贴上订阅链接，该链接即将过期，无需担心
```

### 日志

```raw
[TCP] 127.0.0.1:65535 --> update.glados-config.com:443 doesn't match any rule using DIRECT
```

### 屏幕截图

![IMG_20221023_105942](https://user-images.githubusercontent.com/61441336/197372062-a8036fae-af67-436d-860e-e9f40e975607.jpg)

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/355

**Comment by ECeternalcat** [comment]
抱歉，填漏了步骤
步骤 1: 复制链接，打开clash
步骤 2：点击配置--＋--从url导入
步骤 3： 点击保存，会出现该错误

**Comment by ECeternalcat** [comment]
> 

好的，已经了解了
