### ISSUE TITLE
怎么样能让某个应用的所有流量都通过VPN。

### ISSUE THREAD

**Issue by unclefive55** [Kr328/ClashForAndroid#1707]
### 功能描述

比如说知乎。
![197198596-b91a0965-7a98-4fa5-862f-4c1bc15072ea](https://user-images.githubusercontent.com/80865701/197587862-83e0a2fe-2903-431f-beee-896614f08912.jpg)
![Uploading 197198608-e5d37084-dc37-4d14-82db-6e1350d5bb36.jpg…]()
我开了全局代理，允许了所有应用。都不行。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
