### ISSUE TITLE
[Feature Request] 近期每天都在大规模的精准阻断golang tls指纹，考虑支持uTLS，改变tls client hello指纹

### ISSUE THREAD

**Issue by Kia678** [Kr328/ClashForAndroid#1711]
### Description

近期出现了大规模的精准阻断Trojan端口

经过测试之后，确认是根据客户端的tls指纹进行的trojan-tls流量识别

希望大佬支持一下uTLS，改变tls client hello指纹

uTLS项目链接：https://github.com/refraction-networking/utls

![194044424-94aba3d4-3963-4162-8fdb-f87ea0b94342](https://user-images.githubusercontent.com/85081567/197681323-74449872-06c0-441e-9527-e4fcf77b0eaf.png)
![194549442-4a6b013d-ce6b-45b8-85e2-9e546f0c9159](https://user-images.githubusercontent.com/85081567/197681345-f0954665-7b96-49ec-a778-8e1fee6967e9.png)

**Comment by Kr328** [comment]
上游请

**Comment by Kia678** [comment]
> 上游请

D大说最近身体抱恙。。

**Comment by Kr328** [comment]
> > 上游请
> 
> D大说最近身体抱恙。。

我的 PR 已经完成了 现在就在 premium 里等合并而已

**Comment by Kia678** [comment]
> > > 上游请
> > 
> > 
> > D大说最近身体抱恙。。
> 
> 我的 PR 已经完成了 现在就在 premium 里等合并而已

现在合并好了吗？

**Comment by Thoxvi** [comment]
痛苦，家里的内网穿透被精准掐掉了

**Comment by Kia678** [comment]
> 同样遇到这个问题，家里的内网穿透被精准掐掉了 😢

内网穿透都被掐断了？内网穿透这一段的流量，用了加密吗？

**Comment by Kia678** [comment]
Announce a message of greeting from the Iranian people:
after using uTLS, Trojan unscathed.

**Comment by Thoxvi** [comment]
> > 同样遇到这个问题，家里的内网穿透被精准掐掉了 cry
> 
> 内网穿透都被掐断了？内网穿透这一段的流量，用了加密吗？

实在不好意思，我在搜 `frp` 相关错误的时候不小心进入了此条 Issue，误以为这是 `frp` 的项目，然后回复了一下 :crying_cat_face:
