### ISSUE TITLE
[Feature Request] How to build with premium core?

### ISSUE THREAD

**Issue by SainoNamkho** [Kr328/ClashForAndroid#1712]
### 功能描述

There are only fossRelease and fossDebug in the project.

**Comment by Kr328** [comment]
It is close-source branch

**Comment by xuhaoyang** [comment]
@SainoNamkho P core is closed source

**Comment by SainoNamkho** [comment]
> It is close-source branch

Thank you Kr328. I see that the P core is proprietary, but whether is it a closed source branch of the upstream https://github.com/Dreamacro/clash or of gfa itself?

With regard to the premium binaries provided by the upstream, does it mean premium branch of gfa (or as well gfw ...), is built with the source code of premium core?

**Comment by Kr328** [comment]
@SainoNamkho cfa built with source of premium core, it also is closed-source.

**Comment by SainoNamkho** [comment]
Thanks a lot!
