### ISSUE TITLE
[Feature Request] 关闭流量嗅探来连接Tor

### ISSUE THREAD

**Issue by ghost** [Kr328/ClashForAndroid#1715]
### 功能描述

之前用V2RayNG，可以关闭sniffing（流量嗅探）再连接Tor（洋葱路由，是匿名网络），但是在Clash安卓版中找不到关闭sniffing的选项，V2RayNG都提供这个选项。如果不关，就连不上Tor。Clash安卓版版本号：2.5.9.foss

**Comment by xuhaoyang** [comment]
![image](https://user-images.githubusercontent.com/1927125/197997044-babaa8ea-5920-4910-87f6-0b661451804b.png)
