### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by Dark-Existed** [Kr328/ClashForAndroid#172]
[GolangBindTask.kt](https://github.com/Kr328/ClashForAndroid/blob/master/buildSrc/src/main/java/GolangBindTask.kt)
 ```kotlin
    private fun buildStubGoModule(source: File): String {
        val replaces = source.walk()
            .filter { it.name == "go.mod" }
            .flatMap { file ->
                file.readLines()
                    .asSequence()
                    .filter { line -> line.startsWith("replace") }
                    .map { replace ->
                        replace.replace(REGEX_REPLACE_TARGET_LOCAL, "=> " + file.parentFile.absolutePath + "/")
                    }
                    .map { replace ->
                        replace.replace(REGEX_REPLACE_SOURCE_VERSION, " =>")
                    }
            }
            .joinToString("\n")

        return STUB_GO_MOD_CONTENT.replace("{SOURCE_PATH}", source.absolutePath) +
                "\n\n" + replaces
    } 
``` 
这部分有点问题
```kotlin
replace.replace(REGEX_REPLACE_TARGET_LOCAL, "=> " + file.parentFile.absolutePath + "/")
``` 
举个例子
file.parentFile.absolutePath 获取到的值是 E:\GitHub\ClashForAndroid\core\src\main\golang
上面正则匹配到了 .\clash
但是经过上部分会变成
E:GitHubClashForAndroidcoresrcmaingolang/clash
分隔符不知道为什么被吃了...
![图片](https://user-images.githubusercontent.com/24956657/75557505-194a5300-5a7b-11ea-8867-d1f0673fcf56.png)

看了一段时间没看出为什么...有点玄学 感觉....

**Comment by Kr328** [comment]
@Dark-Existed 我只使用 Linux 只保证 Linux 能够正常编译

**Comment by Kr328** [comment]
@Dark-Existed 当然 也欢迎 PR

**Comment by Dark-Existed** [comment]
> @Dark-Existed 当然 也欢迎 PR
😂 行 我有空看看怎么回事 今天看懵了...

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/commit/253d465d3265cba907fc1790cb536ffa50091622

**Comment by Dark-Existed** [comment]
> [253d465](https://github.com/Kr328/ClashForAndroid/commit/253d465d3265cba907fc1790cb536ffa50091622)
