### ISSUE TITLE
[Feature Request] proxy-providers下更新提示connection rest by peer

### ISSUE THREAD

**Issue by Yik0o** [Kr328/ClashForAndroid#1720]
### 功能描述

proxy-providers以前都是可以更新的，我也试过提取出proxy-providers下的url单独更新，是没有问题的。就是在外部资源更新提示这个前面是tcp4 加ip地址如图。
还有一个问题就是rule-set有时会混乱，无法进行正确的识别
![Screenshot_2022-10-29-14-49-20-38_1ed813789000d97](https://user-images.githubusercontent.com/116111609/198818598-23b8f153-002c-4dcb-a594-3caa9bb82b5e.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
网络问题 以前的网络不是现在的网络

**Comment by Yik0o** [comment]
> 

那请问这怎么解决呢？

**Comment by Kr328** [comment]
@Yik0o 换网络/换链接/出国

**Comment by Yik0o** [comment]
> @Yik0o 换网络/换链接/出国

这就是问题所在了，同个网络同个配置文件，cfw更新没有问题；提取proxy-providers下的url单独在cfa中也是可以更新的；我全局也还是不能更新

**Comment by Kr328** [comment]
@Yik0o 那我也不能怎么办呀 这个错误操作是系统给出来的 要不你问问你的系统
