### ISSUE TITLE
[BUG] 不知道怎么回事

### ISSUE THREAD

**Issue by jjshaoeat** [Kr328/ClashForAndroid#1723]
### 描述此错误

Get "https:// api.ikuuu. science/link/02ZNoJJvkUsMXqEy?clash=3": readtcp 192.168. 43.61:59562->1 72.67.209.137:443: read: connection reset bypeer

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
就是上面那样子

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
vivos6

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:
2.3.22版本

### 配置文件

```yml
https://api.ikuuu.science/link/O2ZNoJJvkUsMXqEy?clash=3
```

### 日志

```raw
无
```

### 屏幕截图

![Screenshot_20221030_205819](https://user-images.githubusercontent.com/101331981/198882222-0a229fc8-1860-4212-8156-71c51e5329b8.jpg)

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1720

**Comment by jjshaoeat** [comment]
what is mean












摆渡人
***@***.***

浙江万里学院
学生
16670376445
湖南益阳

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月30日(周日) 晚上10:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kr328/ClashForAndroid] [BUG] 不知道怎么回事 (Issue #1723)




 
Closed #1723 as completed.
