### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jjshaoeat** [Kr328/ClashForAndroid#1724]
### 描述此错误

![Screenshot_20221030_205819](https://user-images.githubusercontent.com/101331981/198883668-90e8d882-fc15-4b2b-8765-79567a92cb68.jpg)

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
。

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
vivos6

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:
2.3.22

### 配置文件

```yml
https://api.ikuuu.science/link/O2ZNoJJvkUsMXqEy?clash=3
```

### 日志

```raw
no
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by jjshaoeat** [comment]
what ismeaning
