### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by lizyends** [Kr328/ClashForAndroid#1725]
### 功能描述

很多节点都不能使用了，两年前还有台湾节点现在也没有了。最近香港节点也不能使用，美国节点也是。只剩下几个意大利节点。用户体验很差。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by lizyends** [comment]
sorry，是只剩下几个澳大利亚节点。。。

**Comment by xuhaoyang** [comment]
这是个免费的 开源的 软件，你找错地方

**Comment by sakura503** [comment]
这只是个代理工具....
