### ISSUE TITLE
[Feature Request] 测延迟优先采用配置文件的链接

### ISSUE THREAD

**Issue by SakuraSakuraSakuraChan** [Kr328/ClashForAndroid#1726]
### 功能描述

关联issue： https://github.com/Kr328/ClashForAndroid/issues/98

上述issue说未来将按照配置文件的链接来。但近期版本中实测，结果应该还是https的测试。现在的网站几乎都是https了，本身来讲测试用https确实没毛病，但是现在问题起了一些变化，墙在2022年10月初突然增高了一截，具备了TLS in TLS的检测能力 ( https://github.com/net4people/bbs/issues/129 )，根据供应商内鬼的说法，这种检测只能检测出用TLS类代理访问https网站，http网站访问无法检测(大概因为握手少)，这样一来如果配置文件里本身是http链接但CFA都按照https测，就相当于增加了被检测到的风险。

当然被墙肯定是多种因素，肯定不能说是代理app测延迟的问题。只是现在封的越来越厉害，我们需要在各方面减少被检测的风险。我有几个负载均衡的group，每次开启CFA或切换网络的话都要测一下https延迟（是上游的设定），要是能按照我配置文件的来(http)，那咱就放心多啦。因此希望能在未来版本中按照配置文件的链接来测。如果一定要坚持https，那希望能在覆写里增加“不修改”设定。

**Comment by Kr328** [comment]
1. 就是按照配置文件进行测试 是采用的 provider 配置中的 health-check
2. 现在的策略已经不是切换网络时重测了
3. 如果第一条没有正确实现 请按照 Bug 填写

**Comment by SakuraSakuraSakuraChan** [comment]
> 1. 就是按照配置文件进行测试 是采用的 provider 配置中的 health-check
> 
>     2. 现在的策略已经不是切换网络时重测了
> 
>     3. 如果第一条没有正确实现 请按照 Bug 填写

我的配置文件没有任何provider (或url-test、fallback)，只有load-balance，请问这种是会按照load-balance组里的url来测试吗还是按照一个app内置的链接呢？

**Comment by SakuraSakuraSakuraChan** [comment]
因为我不会抓包，是通过测试同一份配置文件里同一load-balance组的延迟（对比CFW和CFA），发现CFA的结果比CFW的多了一个TCP ping，应该是https的结果（配置文件的url是http），这是不是算bug了？

**Comment by Kr328** [comment]
1. 如果是使用的 provider 那就采用 provider 的 health-check
2. 如果不使用 provider 按照应用定义的 https://www.gstatic.com/generate_204

这样设计是因为早期的传统代理可以隶属于多个组，组与组之间的 url 可以不同，就可能会导致在多个组的同个节点因为测试顺序不同导致的延迟不确定。

**Comment by SakuraSakuraSakuraChan** [comment]
那能考虑在覆写里增加个选项吗？

**Comment by Kr328** [comment]
> 因为我不会抓包，是通过测试同一份配置文件里同一load-balance组的延迟（对比CFW和CFA），发现CFA的结果比CFW的多了一个TCP ping，应该是https的结果（配置文件的url是http），这是不是算bug了？

不是哦 不确定的时候 回滚到默认的 https 测试是符合设计预期的
从实际体验出发 https 更能代表实际访问现代网站的性能 (2022 年了纯 http 的主流网站不多了

**Comment by Kr328** [comment]
> 那能考虑在覆写里增加个选项吗？

当前版本不考虑
