### ISSUE TITLE
某知名客户端严重违背GPL开源协议，附逆向代码

### ISSUE THREAD

**Issue by leadxeon** [Kr328/ClashForAndroid#1727]
### 描述此错误

Kr328作者大大你好，
我是ClashForAndoird客户端和开源科学上网工具圈的忠实拥护者，最近使用自己购买的一个基于v2board搭建的机场时，好奇他的定制客户端是如何开发的，于是在网上寻找源码，过程中发现这是一个闭源商业化项目，于是进行了逆向分析，结果发现其中使用了大量了ClashForAndroid代码，包括许多类名和日志代码都未删除，全局搜索ClashForAndroid能够发现大量相关代码。app内甚至连一个LICENSE都没有，这严重违背了GPL开源协议（他人修改代码后不可闭源，新增代码需采用同样协议），将造成深远的不良影响。

下面附上了逆向源码的git仓库链接：
[GitHub - leadxeon/tidalab-android](https://github.com/leadxeon/tidalab-android)

（为避免找茬，我使用了新创建的GitHub小号，为避免找茬，部分去除了我用的机场关键词）下载代码后，全局搜索ClashForAndroid可见大量相关代码。

查看sources/com/tidalab/v2board/clash/目录中可见大量ClashForAndroid同名同内容文件，可看下面截图：
![demo](https://user-images.githubusercontent.com/117038352/199298547-eae6c66e-c06e-48b3-999b-76c54ccaabdb.png)
如需获取机场定制app安装包，请进一步联系我的邮箱。我不知道机场主会不会不爽。

这件事情让我对机场的商业生态有点失望，我是一个经常通过ClashForAndroid上外网的重度用户，如果这样下去恐怕会腐化科学工具开发圈子。今年的墙越来越高了，tls in tls检测技术发展的很快，trojan都能被精准识别了，希望这个领域的开源生态不要继续恶化下去，不然大家都玩完。我感觉目前科学上网开源圈子中，开发者都没有收获到什么实质上的支持，用爱发电了多年，结果还遇到这类事件，我一想到这些就十分沮丧又愤怒。希望作者能够积极跟进这件事情，让开源氛围良性发展。

### 如何复现该错误

步骤 1: `git clone `
步骤 2: 查看sources/com/tidalab/v2board/clash/目录中可见大量ClashForAndroid同名同内容文件，全局搜索ClashForAndroid可发现大量相关代码。

### 设备信息

- 机型: Pixel 4
- 系统类型: MIUI/AOSP
- Android 版本: 10

### 应用信息

- 版本: 4.1.7
- 安装包文件名: tidalab
- 应用来源: 机场下载链接

### 配置文件

```yml
大量相关ClashForAndroid代码，比如：

<string name="github_issues_url">https://github.com/Kr328/ClashForAndroid/issues</string>
    <string name="github_releases">Github Releases</string>
    <string name="github_releases_url">https://github.com/kr328/clashforandroid/releases</string>
    <string name="github_url">https://github.com/Kr328/ClashForAndroid</string>


又比如：
```kotlin
Log.d("ClashForAndroid", "Process " + currentProcessName + " started", null);
```
```


### 日志

```raw
许多ClashForAndroid相关日志输出
```

### 屏幕截图

目录中含大量同名同内容文件：
![demo](https://user-images.githubusercontent.com/117038352/199299429-b1fa1e39-ebe2-47e9-aca2-8057039debb5.png)

全局搜索ClashForAndroid发现大量相关代码：

### 附加信息

今年墙越来越高了，这件事情让我对目前科学上网的开源生态更加悲观，回想当年刚开始用fqrouter\ss\v2ray\I2P的时候，技术跟进积极，行业发展日新月异，百花齐放。时至今日，大量科学上网开发者都没有从开源项目中获得实质性的支持，出现了一堆违背开源协议，那开源项目贴牌变现，或者软件内给机场打广告的开发者。开源生态被蚕食，这个情况真是令人失望。请众多开发者认真对待此事，使开源生态良性发展。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
