### ISSUE TITLE
miui10   9.8.15 挂一两天clash，整个手机就会非常卡

### ISSUE THREAD

**Issue by lazlo95152** [Kr328/ClashForAndroid#1731]
miui10   
9.8.15 挂一两天clash，整个手机就会非常卡，用v2ray没有此现象。clash是google商店最新版2.5.4，手机已装magisk21.0，riru23.9，riru-lsposed1.6.5

_Sent from my MIX 2S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
