### ISSUE TITLE
root下与adguard共存

### ISSUE THREAD

**Issue by xxsz** [Kr328/ClashForAndroid#175]
root下adguard只能启用http代理模式，clash该如何设置呢？

**Comment by Kr328** [comment]
请自行查阅相关文档

**Comment by xxsz** [comment]
Google搜过了，issue也看完了，一般是adg工作在vpn模式下，相关文档能给点关键词吗，实在搜不到方向

**Comment by Kr328** [comment]
我又不会用 这里开 Issue 干嘛 Issue 
只为了 Clash for Android 本身的问题设立 而不会提供对外部应用的支持
