### ISSUE TITLE
Some proxies give errors

### ISSUE THREAD

**Issue by Airuop** [Kr328/ClashForAndroid#1755]
### Describe the bug

Some proxies give errors when selected

### To Reproduce

1.select proxy
2.see error in logs

### Device Info

- Device:honor8
- ROM:emui 9
- Android Version: 9

### Application Info

Version: 2.5.12.premium
APK filename: app-release-arm64-v8a.apk
Distribution Channel: playstore

### Configure File

```yml
- {"type":"vmess","name":"(test)_1","ws-opts":{"path":"/"},"server":"130.61.187.26","port":"443","uuid":"81d93f62-15a2-4994-adb9-0b5d906aac7e","alterId":"0","cipher":"auto","network":"ws","tls":true}
```

### Logs

```raw
[TCP] dial All (match Match/) to 149.154.xxx.xxx:5222 error: dial 130.61.187.26:443 error: x509: cannot validate certificate for 130.61.187.26 because it doesn't contain any IP SANs
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
