### ISSUE TITLE
为什么我已经是2.5.12premium版本了，Google play还提示我更新？

### ISSUE THREAD

**Issue by CSF28** [Kr328/ClashForAndroid#1759]
### 功能描述

![Screenshot_2022-11-23-08-32-55-82_1ed813789000d97ac1c6fc69779c1198](https://user-images.githubusercontent.com/106500334/203448604-962e9817-fbe9-45aa-904b-bfca290c9de7.jpg)
这是我2.5.12premium版本
![Screenshot_2022-11-23-08-32-49-30_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/106500334/203448656-7754d4f9-4713-4c5f-8ed4-a27443e27721.jpg)
然后Google还提示我更新

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
