### ISSUE TITLE
麻烦把在线订阅更新频率那锁定在per hour

### ISSUE THREAD

**Issue by gang4399** [Kr328/ClashForAndroid#176]
默认按秒有很多用别人api订阅的造成别人资源的巨大浪费，苦不堪言
![IMG_20200229_171804_731](https://user-images.githubusercontent.com/28175410/75604784-70c8dd00-5ad4-11ea-844b-eda33a4a0df3.jpg)

**Comment by Forty-nine** [comment]
你可以设置成 86400s

**Comment by stormrise** [comment]
输入了自动更新时间，保存一直转圈圈（

**Comment by Kr328** [comment]
This issue has been resolved
此问题已得到解决
