### ISSUE TITLE
[Feature Request] HTTP/1.0>>>>>>update >>>>HTTP/2.0 更安全，效率更高

### ISSUE THREAD

**Issue by sysonetg** [Kr328/ClashForAndroid#1766]
### 功能描述

HTTP/1.0>>>>>>update >>>>HTTP/2.0 更安全，效率更高

![1670114518877](https://user-images.githubusercontent.com/43629100/205468380-c4a9c2de-67b8-44fc-80c1-7f5a8d2dee7f.png)

**Comment by ShinnXing** [comment]
现在购买的网站是哪个？之前的打不开了

**Comment by AkariiinMKII** [comment]
> 现在购买的网站是哪个？之前的打不开了

> `Clash for Android`是免费软件

**Comment by SilenceXK** [comment]
我就是冤种用的v2ray订阅的bigairport节点每一个都deadline，这才来试clash

**Comment by slimeyizhi** [comment]
wow

**Comment by Kr328** [comment]
你能给出在更新配置文件的用例中，HTTP/2 相对于 HTTP/1 更具有优势的部分吗。

**Comment by sysonetg** [comment]
> 你能给出在更新配置文件的用例中，HTTP/2 相对于 HTTP/1 更具有优势的部分吗。

yaml文件更新订阅的时候走的http/1.0 我观察过的

**Comment by Kr328** [comment]
> > 你能给出在更新配置文件的用例中，HTTP/2 相对于 HTTP/1 更具有优势的部分吗。
> 
> yaml文件更新订阅的时候走的http/1.0 我观察过的

问的是在**更新订阅的场景下**，HTTP/2 对于 HTTP/1 的**优势(它为什么优秀)**，不是问的**纸面参数(它用了什么)**。

**Comment by sysonetg** [comment]
> 

避免多次请求，http/1.1会发生多次请求错误，http/2.0可以减少请求时间，安全性方面加密性能更好，速度更快，服务器统计起来不至于发生错误统，http/1.1发生一次错误会频繁请求 服务器压力骤升

**Comment by Kr328** [comment]
> > 
> 
> 避免多次请求，http/1.1会发生多次请求错误，http/2.0可以减少请求时间，安全性方面加密性能更好，速度更快，服务器统计起来不至于发生错误统，http/1.1发生一次错误会频繁请求 服务器压力骤升

1. 避免多次请求：可是实际上 HTTP/1 和 HTTP/2 都是只进行一个请求。
2. 发生多次错误请求：如何发生的呢，为什么呢。
3. 减少请求时间：在只进行一次请求的时候如何减少的呢。
4. 安全性：在都是 TLS 1.3 的情况下，HTTP/2 相对于 HTTP/1 有什么安全性的改进呢。
5. 速度更快：具体是哪方面更快。
6. 服务端方面：clash 在一次请求出错之后就不再进行第二次请求，如果出现多次重复的统计，是否应该考虑是服务端的问题。

**Comment by sysonetg** [comment]
> > > 
> > 
> > 
> > 避免多次请求，http/1.1会发生多次请求错误，http/2.0可以减少请求时间，安全性方面加密性能更好，速度更快，服务器统计起来不至于发生错误统，http/1.1发生一次错误会频繁请求 服务器压力骤升
> 
> **在更新配置这个用例下**：
> 
> 1. 避免多次请求：可是实际上 HTTP/1 和 HTTP/2 都是只进行一个请求。
> 2. 发生多次错误请求：如何发生的呢，为什么呢。
> 3. 减少请求时间：在只进行一次请求的时候如何减少的呢。
> 4. 安全性：在都是 TLS 1.3 的情况下，HTTP/2 相对于 HTTP/1 有什么安全性的改进呢。
> 5. 速度更快：具体是哪方面更快，指的带宽的话，HTTP/2 如何突破运营商设下的上限。
> 6. 服务端方面：clash 在一次请求出错之后就不再进行第二次请求，如果出现多次重复的统计，是否应该考虑是服务端的问题。

tls1.3现在只有部分老手机不支持，新手机都已经支持了，我给服务端弄的是tls1.3,因为客户基本都是新设备，tls1.3效率确实高，但是我觉得现在采用http/1.1是否有点过时了，其它任何VPN客户端都是http/2.0了，只有这个安卓的clash还停留在http/1.1，希望能改进下

**Comment by Kr328** [comment]
> > > > 
> > > 
> > > 
> > > 避免多次请求，http/1.1会发生多次请求错误，http/2.0可以减少请求时间，安全性方面加密性能更好，速度更快，服务器统计起来不至于发生错误统，http/1.1发生一次错误会频繁请求 服务器压力骤升
> > 
> > 
> > **在更新配置这个用例下**：
> > 
> > 1. 避免多次请求：可是实际上 HTTP/1 和 HTTP/2 都是只进行一个请求。
> > 2. 发生多次错误请求：如何发生的呢，为什么呢。
> > 3. 减少请求时间：在只进行一次请求的时候如何减少的呢。
> > 4. 安全性：在都是 TLS 1.3 的情况下，HTTP/2 相对于 HTTP/1 有什么安全性的改进呢。
> > 5. 速度更快：具体是哪方面更快，指的带宽的话，HTTP/2 如何突破运营商设下的上限。
> > 6. 服务端方面：clash 在一次请求出错之后就不再进行第二次请求，如果出现多次重复的统计，是否应该考虑是服务端的问题。
> 
> tls1.3现在只有部分老手机不支持，新手机都已经支持了，我给服务端弄的是tls1.3,因为客户基本都是新设备，tls1.3效率确实高，但是我觉得现在采用http/1.1是否有点过时了，其它任何VPN客户端都是http/2.0了，只有这个安卓的clash还停留在http/1.1，希望能改进下

我问的是具体的**细节**，而不是其他的东西，更不是市场调查，不是其他客户端都使用某种协议，我这里就必须要使用的。TLS 1.3 无论新老设备在 clash 这里都是启用的。

下一版本的 clash multiplatform 会使用 HTTP/2，但是在这里我还是想要你明白，**谈优势的时候不能抛开场景**，在更新配置这个用例下 HTTP/2 和 HTTP/1 的差距几乎没有，完全没有必要为了加上 HTTP/2 而加上。而且一般的提起涉及具体实现细节的建议，都需要提供很详细的技术上的优势，而不是简单的**更快更安全**，有时候甚至需要提供相应的 benchmark。
