### ISSUE TITLE
[Feature Request] 能否增加自定义添加负载均衡等功能？

### ISSUE THREAD

**Issue by EzSync** [Kr328/ClashForAndroid#1767]
### 功能描述

 能否增加自定义添加负载均衡等功能？
有的yaml文件里面没有“负载均衡”、“故障转移”等策略组，能否增加自定义功能？
“不良林”曾给Clash For Windows做过这样的脚本，就是在“配置文件预处理”里加上了parsers脚本，可以参考：
"使用CFW的parsers功能自动插入负载均衡策略组......": https://bulianglin.com/archives/lb.html

**Comment by xuhaoyang** [comment]
https://github.com/tindy2013/subconverter/ 
pls
