### ISSUE TITLE
访问控制应用列表

### ISSUE THREAD

**Issue by KeSaite** [Kr328/ClashForAndroid#177]
访问控制应用列表的反选功能没了？上一个稳定版是有的，方便很多，不用一个一个选

**Comment by Rainningme** [comment]
> 访问控制应用列表的反选功能没了？上一个稳定版是有的，方便很多，不用一个一个选

我觉得是有的，你在仔细看看选项

**Comment by bupt2017** [comment]
还有能不能将已经选择的应用列表给导出或者导入

**Comment by zhixuans** [comment]
还有为什么clash分应用列表比shadowsocks的分应用列表的应用多很多？

**Comment by Supremewoman** [comment]
和v2rayng选一样多会无法连接fcm，有些不知道干嘛用的，只能反选国产了

**Comment by Kr328** [comment]
This issue has been resolved
此问题已得到解决
