### ISSUE TITLE
[BUG] 设置-网络-应用包列表不全, 缺少很多已安装应用

### ISSUE THREAD

**Issue by pkulijie** [Kr328/ClashForAndroid#1770]
### 描述此错误

你好，如果比较clash与其他socket，v2ray安卓应用，可以明显发现在您的应用包列表中缺失了很多应用程序，包括YouTube, Google store， chome 等等，下面有张图是来自另一款同类型应用的，希望能改进。

### 如何复现该错误

步骤 1: 设置
步骤 2: 网络
步骤 3: 允许控制应用包列表
...

### 设备信息

- 机型:samsung s10 5g
- 系统类型:android 12
- Android 版本:android 12

### 应用信息

- 版本:2.5.12
- 安装包文件名:cfa-2.5.12-premium-universal-release
- 应用来源:github

### 配置文件

```yml
不相关
```

### 日志

```raw
不相关
```

**Comment by Kr328** [comment]
@pkulijie 为什么不翻翻过往的 issue 呢

**Comment by pkulijie** [comment]
![Screenshot_20221206_033229_v2rayNG](https://user-images.githubusercontent.com/30856053/205727270-4c92d9d7-f6b9-42a3-9923-e6cd07dc9e85.jpg)
Like these app lists from another similar application

**Comment by pkulijie** [comment]
> @pkulijie 为什么不翻翻过往的 issue 呢

是我看的不仔细吗？已经找了没看到，麻烦您如果可以解释一下

**Comment by pkulijie** [comment]
> @pkulijie 为什么不翻翻过往的 issue 呢

抱歉，实在没有找到解释。可否解释一下问题在哪里？感谢！

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/1529

**Comment by pkulijie** [comment]
> #1529

Sorry, get it. 谢谢
