### ISSUE TITLE
[Bug] 通过通知栏开关clash，主界面还停留在线路选择

### ISSUE THREAD

**Issue by byxiaorun** [Kr328/ClashForAndroid#1771]
### Describe the bug

也许是bug:
通过通知栏开关clash
clash那边如果之前在选择线路的界面
打开clash就还会在线路的界面
打开clash看到这个界面，选线路，然后没反应会很疑惑

### To Reproduce

Step 1: 通知栏添加clash开关
Step 2: 打开clash ，并停留在线路选择界面
Step 3: 通过通知栏关闭clash
Step 4:打开clash APP

### Device Info

- Device:realme
- ROM:
- Android Version:

### Application Info

- Version: 2.5.12-premium
- APK filename: cfa-2.5.12-premium-arm64-v8a-release.apk
- Distribution Channel: github

### Configure File

```yml
null
```

### Logs

```raw
null
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
