### ISSUE TITLE
[Feature Request] When there're vless nodes in profile file, file won't be imported.

### ISSUE THREAD

**Issue by Retia-Adolf** [Kr328/ClashForAndroid#1774]
### Feature Description

If CFA could ignore vless nodes and import the left nodes, that would be better. Manually editing profile file is rather cumbersome.

**Comment by Kr328** [comment]
IT NOT BETTER, IT CAN CAUSE UNEXPECTED BEHAVIOR.

**Comment by Retia-Adolf** [comment]
Sorry, but what would be unexpected, would you mind to explain?
