### ISSUE TITLE
[BUG] 无法在国行索尼电视上正常运行

### ISSUE THREAD

**Issue by EarthPretender** [Kr328/ClashForAndroid#1775]
### 描述此错误

将谷歌中下载的版本从u盘安装进索尼电视后，先是显示一会儿安装包不完整，然后点击下就会进入正常页面。但是页面全英文，而且没有任何一个按钮点击后有反应。

### 如何复现该错误

步骤 1: 从谷歌上下载cfa
步骤 2: 将上述cfa导入u盘
步骤 3: 将u盘插入索尼电视并安装打开
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
（太过于小白以至于只知道这是索尼电视……大概是七八年前买的）

### 应用信息

- 版本:2.5.12premium
- 安装包文件名:（就是谷歌最新版的那个）
- 应用来源:谷歌商店

### 配置文件

```yml
（安装并打开后无法进行任何除退出外的操作）
```

### 日志

```raw
（无法操作）
```

### 屏幕截图

无

**Comment by Kr328** [comment]
Google Play 的版本是由多个 apk 共同构成 不能简单提取
