### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Glow-Shimmering** [Kr328/ClashForAndroid#1780]
### 描述此错误

提示错误：
yaml: unmarshal errors: line 1: connot un marshal !!str'dm1lc3M...'into config.RawConfig

### 如何复现该错误

步骤 1: 配置
步骤 2: 输入URL
步骤 3: 点击保存
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
小米10S，MIUI13

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:
cfa-2.5.12-premium-universal-release

### 配置文件

```yml
https://ghelper.me/clash/83aafd4cd59e29b2b7bd271856598707
```

### 日志

```raw
zanw
```

### 屏幕截图

![f1414518fb56e4e02bcf6cb2c7f28bd](https://user-images.githubusercontent.com/120736864/208133463-020e8fac-f2c6-4adb-b7db-4fc986df9bb7.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
