### ISSUE TITLE
手机代理不可以更新提示解组错误[BUG] 

### ISSUE THREAD

**Issue by EOGpy** [Kr328/ClashForAndroid#1781]
### 描述此错误

软件突然无法更新
重新创建配置提示
yaml：unmarsha lerrors line 1:cannot unmarshal !!str'<html>...' into config.RawConfig
卸载重装均无用
配置文件无法打开
配置文件.yaml 显示 0 Byest

### 如何复现该错误

软件突然无法更新
重新创建配置提示
yaml：unmarsha lerrors line 1:cannot unmarshal !!str'<html>...' into config.RawConfig
卸载重装均无用
配置文件无法打开
配置文件.yaml 显示 0 Byest

### 设备信息

- 机型:小米12
- 系统类型:miui13.2.6
- Android 版本:13

### 应用信息

- 版本:2.5.12
- 安装包文件名:[cfa-2.5.12-premium-arm64-v8a-release.apk]
- 应用来源:GitHub

### 配置文件

```yml
配置文件无法打开
配置文件.yaml 显示 0 Byest
```

### 日志

```raw
无日志
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by liyiyi421** [comment]
你解决了吗？我遇到同样的问题了
