### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by EOGpy** [Kr328/ClashForAndroid#1784]
### 功能描述

无法更新
重新配置url后提示
yaml：unmarsha lerrors line 1:cannot unmarshal !!str'<html>...' into config.RawConfig
卸载重装后无变化

配置文件显示0B且无法打开
![Screenshot_2022-12-18-00-02-11-952_com github kr3](https://user-images.githubusercontent.com/45909469/208250946-8eaa968a-43da-4f29-a4b8-3b4c498988e9.jpg)
![Screenshot_2022-12-18-00-01-48-772_com github kr3](https://user-images.githubusercontent.com/45909469/208250947-55861aca-b251-462b-8ce1-6c012b18d080.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
