### ISSUE TITLE
[Feature Request] 无法更新配置

### ISSUE THREAD

**Issue by EOGpy** [Kr328/ClashForAndroid#1785]
### 功能描述

无法更新
重新配置url后提示
yaml：unmarsha lerrors line 1:cannot unmarshal !!str'...' into config.RawConfig
卸载重装后无变化

配置文件显示0B且无法打开
![Screenshot_2022-12-18-00-02-11-952_com github kr3](https://user-images.githubusercontent.com/45909469/208250978-4be41274-26f4-495e-8726-cce8bddf6c7b.jpg)
![Screenshot_2022-12-18-00-01-48-772_com github kr3](https://user-images.githubusercontent.com/45909469/208250981-b014e6c3-b9fd-4c55-a480-942ae7bb6067.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
