### ISSUE TITLE
[BUG] 无法更新配置

### ISSUE THREAD

**Issue by EOGpy** [Kr328/ClashForAndroid#1786]
### 描述此错误

无法更新
重新配置url后提示
yaml：unmarsha lerrors line 1:cannot unmarshal !!str'...' into config.RawConfig
卸载重装后无变化

配置文件显示0B且无法打开

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
配置文件显示0B且无法打开
```

### 日志

```raw
无日志
```

### 屏幕截图

![Screenshot_2022-12-18-00-02-11-952_com github kr3](https://user-images.githubusercontent.com/45909469/208251075-4ab97ce0-62bc-414d-a6b2-283b4b099acd.jpg)
![Screenshot_2022-12-18-00-01-48-772_com github kr3](https://user-images.githubusercontent.com/45909469/208251077-74ee8676-202c-44ce-8633-772274b54a78.jpg)

**Comment by Kr328** [comment]
你把这个链接放浏览器里

**Comment by EOGpy** [comment]
URL的那个链接吗 它显示404 Not Found

**Comment by EOGpy** [comment]
我的Clash 订阅的链接是404，通用订阅链接是一行字母串

**Comment by EOGpy** [comment]
Surfboard专用配制URL 打开后是有IP右节点的

**Comment by EKyero** [comment]
@EOGpy 向你的机场反馈

**Comment by EOGpy** [comment]
机场反馈是什么

**Comment by Kr328** [comment]
> URL的那个链接吗 它显示404 Not Found

那就和本应用没有关系了，自己去找给你链接的人。

**Comment by EOGpy** [comment]
我是谷歌上网助手里给的链接与你们不是一起的吗

**Comment by Kr328** [comment]
¿

应用里没看到字吗

**Clash for Android 是一个免费软件并且我们不为其提供任何服务, 请务必不要反馈非应用自身引起的问题**

**Comment by BIGMONK** [comment]
同一个订阅地址，放到v2rayNG里面是可以的，放到clash里面报这个错
