### ISSUE TITLE
[BUG] 无法保存URL配置，显示unmarshal error

### ISSUE THREAD

**Issue by shenwuxie** [Kr328/ClashForAndroid#1787]
### 描述此错误

无法保存url配置

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
右上角＋号，选择url配置，配置完成后，保存

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
小米10s

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:1

### 配置文件

```yml
1
```

### 日志

```raw
1
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
