### ISSUE TITLE
[Feature Request] 请求删除\n \r \s 等特殊字符

### ISSUE THREAD

**Issue by tysonair** [Kr328/ClashForAndroid#1789]
### 功能描述

windows客户端 上面 不会有这个问题， 安卓客户端经常会出现\n 相关报错 。建议直接排除掉这类特殊字符。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@tysonair 没遇到过 按照 BUG 模板上传复现方法
