### ISSUE TITLE
[BUG] clash app开全局没有作用

### ISSUE THREAD

**Issue by yatmiml** [Kr328/ClashForAndroid#1790]
### 描述此错误

clash开全局没有效果，即使有效果也没有办法修改ip属地，但是这一点如果是电脑的clash就可以，请问这是为什么呢？这个问题该如何去解决？

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
1 开clash
2 开全局
3 错误出现

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
k40
miui13
12

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:
2.5.4-premium
cfa-2.5.4-premium
官网

### 配置文件

```yml
没有的。。。
```

### 日志

```raw
[APP] Logcat level: info
```

**Comment by Kr328** [comment]
1. 我们没有官网
2. clash 运行需要一个配置文件
3. 日志需要 
   i) 打开日志记录器 
   ii) 重现问题
   iii) 关闭记录器

**Comment by caiysmy** [comment]
> 1. 我们没有官网
> 2. clash 运行需要一个配置文件
> 3. 日志需要 
>    i) 打开日志记录器 
>    ii) 重现问题
>    iii) 关闭记录器

作者还会继续更新吗？

**Comment by helloworld10010** [comment]
从 设置 -> 覆写 里改全局好用，直接三个点改没啥用
