### ISSUE TITLE
[BUG] 使用账号下载iOS系统软件出现验证码验证iPad账号问题

### ISSUE THREAD

**Issue by mayealalalal** [Kr328/ClashForAndroid#1791]
### 描述此错误

[BUG] 利用VIP获取iPad的iOS系统的账号密码，登录下载sockboom相关软件时，登录账号时显示该账号会发送手机验证码进行账号验证，导致不能登录账号下载iOS系统使用的软件。

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
iPad iOS系统

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:
APP store

### 配置文件

```yml
iOS系统，登录账号时出现问题
```

### 日志

```raw
无
```

### 屏幕截图

![IMG_20221229_001457](https://user-images.githubusercontent.com/103431519/209844819-869106b9-4495-4a89-9f00-d1755f0caf8a.jpg)
![IMG_20221229_001750](https://user-images.githubusercontent.com/103431519/209844775-39e15f8f-af5b-4037-b439-b740997e31fb.jpg)
![IMG_20221229_001457](https://user-images.githubusercontent.com/103431519/209844790-1bc01668-991d-4165-a9f1-dcac28c20218.jpg)

**Comment by Kr328** [comment]
¿

这里是 Clash for **Android** 项目，不提供任何服务，只关注 Clash for **Android** 自身问题。
