### ISSUE TITLE
为什么无法订阅？

### ISSUE THREAD

**Issue by antoniosuen** [Kr328/ClashForAndroid#1795]
### Feature Description

yaml: unmarshal errors:
Sline 1: cannot unmarshal !!str
U1RBVFV..
. into config.RawConfig

每次订阅都弹出这个窗口呢？

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
