### ISSUE TITLE
[BUG]  无法订阅机场 有人遇到相同的问题吗？

### ISSUE THREAD

**Issue by antoniosuen** [Kr328/ClashForAndroid#1796]
### Describe the bug

订阅弹出窗口 错误

安卓设备有Root过

### To Reproduce

yaml: unmarshal errors:
Sline 1: cannot unmarshal !!str
U1RBVFV..
. into config.RawConfig

### Device Info

- Device:HTC 5 G HUB
- ROM:
- Android Version:

### Application Info

- Version:
- APK filename:[cfa-2.5.12-foss-arm64-v8a-release.apk]
- Distribution Channel:

### Configure File

```yml
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.5.12
```

### Logs

```raw
？
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
