### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by WuYang09661** [Kr328/ClashForAndroid#1797]
### 描述此错误

Clash在非高负载使用的情况下在后台占用大量cpu资源。

### 如何复现该错误

我暂时并未找到能够复现该错误的方式，但是值得一提的是，曾经有多次手机在夜间的待机电量消耗严重，打开电池记录后发现clash占据了其中大部分的电量使用。

### 设备信息

- 机型:Realme GT 高通骁龙888 
- 系统类型:Realme UI 4.0 （Color OS13换皮）
- Android 版本:Android 13

### 应用信息

- 版本:2.5.12-premium
- 安装包文件名:cfa-2.5.12-premium-arm64-v8a-release.apk
- 应用来源:Git Hub

### 配置文件

```yml
我将其上传至屏幕截图处
```

### 日志

```raw
无
```

### 屏幕截图

https://user-images.githubusercontent.com/81788651/211176104-01328169-2537-4fad-89a6-ee53bb7d13ed.mp4

[配置文件.txt](https://github.com/Kr328/ClashForAndroid/files/10367506/default.txt)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
换一套规则吧，每条连接都遍历一遍 4w 条规则开销还是很大的。

顺便把 allow-lan 关了
