### ISSUE TITLE
[Feature request] Add search function for Access Control 为分应用代理添加搜索功能

### ISSUE THREAD

**Issue by liuhuoz** [Kr328/ClashForAndroid#18]
Right now, it‘s inefficient to locate the apps which would be added into the black or white list.

Please add a keyword filter. It will directly display the apps and it's easier to modify the list.
Besides, some people also suggested using a fast scrolling bar.
 
p.s. This issue is just for backup, because many people mentioned it but none of them submitted it.

**Comment by liuhuoz** [comment]
仅翻译，避免重复提交。

现在，分应用代理中的应用列表过长，导致添加应用到黑/白效率较低。

请添加一个关键词搜索功能，这样可以直接显示特定app，并更好地修改黑/白名单
此外，还有人建议添加快速滚动条。

p.s. 这个issue仅用于备份，因为很多人提到但没有人提交issue

**Comment by onlyistranger** [comment]
+1

**Comment by Quackgrass** [comment]
建议添加“从剪贴板导入”和“导出到剪贴板”。V2RayNG，Kitsunebi，SSR 等支持导入导出应用列表。上手时，一键导入会方便。

**Comment by Kr328** [comment]
1.1.0 已实现
