### ISSUE TITLE
Google TV 使用时出现间歇性断流

### ISSUE THREAD

**Issue by Doraemon2020** [Kr328/ClashForAndroid#1807]
### 描述此错误

Chromecast with Google TV （Android TV 12）使用2.5.15版本时会出现网络间歇性断流

### 如何复现该错误

开启代理就会出现

### 设备信息

- 机型：Chromecast with Google TV
- 系统类型：Android TV
- Android 版本：12

### 应用信息

- 版本:2.5.15
- 安装包文件名:cfa-2.5.12-foss-universal-release
- 应用来源:GitHub

### 配置文件

```yml
太长了传不上来
```

### 日志

```raw
未找到提取方法
```

### 屏幕截图

![photo_2023-01-26_00-59-17](https://user-images.githubusercontent.com/59880367/214632707-e885053f-6083-4cc2-82fd-a73d0bb522d4.jpg)
![photo_2023-01-26_00-59-14](https://user-images.githubusercontent.com/59880367/214632850-91fb3f94-e059-40bd-8189-8dca9959bb09.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
