### ISSUE TITLE
[Feature Request] 启动代理时对url test和fallback策略组进行测速

### ISSUE THREAD

**Issue by leftcausedit** [Kr328/ClashForAndroid#1810]
### 功能描述

2.5.12版本的clash在代理启动后不会立刻对url test和fallback策略组进行可用性检测，而是要在一个间隔（通常设置为5分钟）后进行，在这5分钟内无法保证代理可用性。

**Comment by ksync1** [comment]
@leftcausedit 请问这个BUG修复了吗? 看最新的release版本仍然是2.5.12, 是否有workaround?
