### ISSUE TITLE
[BUG] 在手机安卓端无法使用

### ISSUE THREAD

**Issue by ZzZqr** [Kr328/ClashForAndroid#1815]
### 描述此错误

今天早上之前都能用，下午就不能用了（详见屏幕截图），点击加速之后也没有一个能用的负载均衡器。然后我检查了我的账户还有7天才到期，我的流量还很多，我用电脑使用clash也没问题，可以正常使用，但是就是手机不行。我试过更新配置、把clash删掉重装，都没用，还是不能用。这个情况已经持续了一个下午了。

### 如何复现该错误

用不了

### 设备信息

- 机型:华为mate 30 pro
- 系统类型:11.0.0.176
- Android 版本:

### 应用信息

- 版本:安卓最新（官网最新）
- 安装包文件名:clash-for-android_20230205_121734
- 应用来源:biteb.cc

### 配置文件

```yml
123
```

### 日志

```raw
1
```

### 屏幕截图

![Screenshot_20230205_151420_com github kr328 clash](https://user-images.githubusercontent.com/71776709/216806772-71727415-b08d-43cd-9567-e91993b6aca2.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
这里是 ClashForAndroid 项目，在本项目渠道外获取的应用请到获取的渠道处反馈。

**Comment by ZzZqr** [comment]
> 这里是 ClashForAndroid 项目，在本项目渠道外获取的应用请到获取的渠道处反馈。


我不明白你这是什么意思，你的软件里的反馈渠道就是这个git网址，难道这个clash for android不是你们做的吗

**Comment by Kr328** [comment]
@ZzZqr ClashForAndroid 项目是这里 但是我只接收使用 Google Play 和 Github Releases 渠道安装的反馈
