### ISSUE TITLE
长节点名称问题

### ISSUE THREAD

**Issue by lidoworld** [Kr328/ClashForAndroid#182]
以往滚动的话 虽然要等几秒才能看全节点名
现在不滚动了 如果机场给出的节点名前面有较长的统一格式 那么节点列表里看过去全一模一样 不知道哪个是哪个了

**Comment by Kr328** [comment]
前缀合并 请

**Comment by rodrigueez** [comment]
可以加一个长按弹出toast显示全名

**Comment by planetarian10** [comment]
也可以添加一个选项，可以设置节点为双列显示或单列显示，单列显示就可以显示完整的节点名

**Comment by JasperWong** [comment]
> 前缀合并 请

有些前缀并不一样,而且即使前缀合并了还是会存在过长的情况

**Comment by jmireles7** [comment]
> 也可以添加一个选项，可以设置节点为双列显示或单列显示，单列显示就可以显示完整的节点名

同感，小屏幕长名称双列怎么玩都没有单列利索。

**Comment by Crayon-ShinChan** [comment]
前缀合并之后还是过长，还是建议添加一行显示一个节点的选项吧吧。不然真的看不全，前面名字长到一摸一样。

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.1
