### ISSUE TITLE
[BUG] addDisallowedApplication(packageName)导致telegram等很多应用无法使用

### ISSUE THREAD

**Issue by nocodefree** [Kr328/ClashForAndroid#1822]
### 描述此错误

addDisallowedApplication(packageName)导致telegram等很多应用无法使用
我想在app里调用一些其他接口，不想代理clash for android本身，但是这样的话就会导致telegram等一些应用无法连接，请问有什么好的办法吗？

### 如何复现该错误

步骤 1: ...TunService.kt添加addDisallowedApplication(packageName)
步骤 2: ...打开telegram
步骤 3: ...无法连接
...

**Comment by Kr328** [comment]
这里不对开发及修改问题提供支持
