### ISSUE TITLE
[Issue] 忘记网站登录密码，邮箱收不到code，怎么找回？

### ISSUE THREAD

**Issue by henbell2** [Kr328/ClashForAndroid#1825]
### 描述此错误

[Issue] 忘记网站登录密码，邮箱收不到code，怎么找回？

### 如何复现该错误

[Issue] 忘记网站登录密码，邮箱收不到code，怎么找回？

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
[Issue] 忘记网站登录密码，邮箱收不到code，怎么找回？

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
[Issue] 忘记网站登录密码，邮箱收不到code，怎么找回？
```

### 日志

```raw
[Issue] 忘记网站登录密码，邮箱收不到code，怎么找回？
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@henbell2 这里是 Clash for Android 项目，我们没有网站也不提供服务。
