### ISSUE TITLE
[BUG] 后台频繁自启动

### ISSUE THREAD

**Issue by Sostay** [Kr328/ClashForAndroid#1828]
### 描述此错误

![Screenshot_2023-02-21-22-41-31-032_com miui powerkeeper](https://user-images.githubusercontent.com/6897274/220375812-77f1ad16-8d8b-41f6-8086-5d449a56905d.jpg)
最新版本2.5.12，设置禁止后台运行都不管用，没有使用VPN的情况下总是隔一段时间就在后台启动，主要是增加了耗电，有办法解决这个问题吗？

### 设备信息

- 机型:小米MIX 4
- 系统类型:MIUI 14
- Android 版本:Android 13

### 应用信息

- 版本:2.5.12
- 安装包文件名:2.5.12-premium
- 应用来源:GitHub

**Comment by Sostay** [comment]
![Screenshot_2023-02-21-22-45-27-274_com miui securitycenter](https://user-images.githubusercontent.com/6897274/220377244-683bc969-1dcb-417a-95ad-6008adf6bf3b.jpg)

**Comment by sceraser** [comment]
黑人问号？这类软件不就该保活以确保你的VPN连接稳定吗？这是软件的feature，如果你不需要稳定的VPN连接那自行寻找禁止自启动的方法

**Comment by Sostay** [comment]
> 黑人问号？这类软件不就该保活以确保你的VPN连接稳定吗？这是软件的feature，如果你不需要稳定的VPN连接那自行寻找禁止自启动的方法

我也黑人问号。。。。你不会是觉得我想要在使用VPN的时候让clash停止运行吧？？？（GitHub啥时候变成这种抬杠氛围了😓）

**Comment by xuhaoyang** [comment]
被系统界面启动，你有没有想过是什么。你觉得有问题，建议去看源码做了什么。

**Comment by xuhaoyang** [comment]
1.在锁定后台，允许自启动，关闭VPN的情况下，MIUI13 清空app运行，下拉任务栏里面有tileService是clash，一下拉看记录被系统界面启动。
2.在一的基础上，开着VPN，做清空，清空的瞬间，记录显示自启动。

有洁癖建议别用哦。

**Comment by Sostay** [comment]
> 1.在锁定后台，允许自启动，省电策略无限制，关闭VPN的情况下，MIUI13 清空app运行，下拉任务栏里面有tileService是clash，一下拉，看记录，是被系统界面启动。 2.在1的基础上，开着VPN，做清空，清空的瞬间，记录显示自启动。
> 
> 有洁癖建议别用哦。

我来问有没有解决方案，你没有可以不说话，还建议我别用？莫名其妙。。。
说一大堆，也不知道你在说什么
（今天什么情况，都是不能好好说话的

**Comment by xuhaoyang** [comment]
你想解决，找MIUI。

https://user-images.githubusercontent.com/1927125/220499437-61f2fe3d-79f4-44dc-8107-c83882cdc448.mp4

**Comment by AkariiinMKII** [comment]
@Sostay 解决方案？卸载cfa算不算

**Comment by AoEiuV020** [comment]
miui这个自启动还是挺靠谱的，你把自启动关了就不会自已启动自己了，
被“系统界面”启动那是“系统界面”的问题，

**Comment by Sostay** [comment]
> @Sostay 解决方案？卸载cfa算不算

不会说话可以闭嘴。。。像个正常人一样那么难？

**Comment by Sostay** [comment]
> miui这个自启动还是挺靠谱的，你把自启动关了就不会自已启动自己了， 被“系统界面”启动那是“系统界面”的问题，

是 我感觉主要是添加到通知栏磁贴导致被系统界面启动吧 但是磁贴的功能有很需要…… 可能确实有点冲突
