### ISSUE TITLE
[BUG] 配置错误

### ISSUE THREAD

**Issue by gqoai** [Kr328/ClashForAndroid#1832]
### 描述此错误

在配置时出错

### 如何复现该错误

步骤 1: ...配置
步骤 2: ...URL
步骤 3: ...输入配置文件网站
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
点击配置

### 应用信息

- 版本:
- 安装包文件名:Clash for Android
- 应用来源:网页

### 配置文件

```yml
https://sub.pmsub.me/clash.yaml
```

### 日志

```raw
无
```

### 屏幕截图

![Screenshot_20230223_223143_com github kr328 clash](https://user-images.githubusercontent.com/126177578/220941105-32e1fe03-3999-49b1-b947-35adfa0acb9a.jpg)

### 附加信息

没有

**Comment by Kr328** [comment]
@gqoai 你先看看你这个链接是什么

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by gqoai** [comment]
哪一个链接？配置文件那个吗。？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月23日(周四) 晚上11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kr328/ClashForAndroid] [BUG] 配置错误 (Issue #1832)




 
@gqoai 你先看看你这个链接是什么

**Comment by gqoai** [comment]
为什么会出现截图那种情况呢，突然就这样了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月23日(周四) 晚上11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kr328/ClashForAndroid] [BUG] 配置错误 (Issue #1832)




 
@gqoai 你先看看你这个链接是什么

**Comment by EKyero** [comment]
![Uploading Screenshot_20230223-233504_Clash_for_Android.png…]()

**Comment by EKyero** [comment]
![Screenshot_20230223-233504_Clash_for_Android](https://user-images.githubusercontent.com/29628846/220962351-96c88069-f3c6-4697-afd8-e688aaf7d879.png)
