### ISSUE TITLE
[希望增加一个DNS防泄露功能目前大部分机场都没办法解决] 

### ISSUE THREAD

**Issue by wzry623090** [Kr328/ClashForAndroid#1837]
### 功能描述

我希望是可以解决DNS泄露问题，防止被运商知道你在科学上网，要么就跟v2客户端一样，启动本地DNS和虚拟DNS 这个DNS泄露问题，必须要得到解决，不然你科学上网感觉明显不安全，

### 附加信息

嗯，这是不良林提供的，应该是防泄漏的规则之类的东西吧https://cf.buliang0.cf/clash-rules/nodnsleak.ini

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
