### ISSUE TITLE
可以添加一个一键启动的桌面小部件吗？

### ISSUE THREAD

**Issue by myotsuki** [Kr328/ClashForAndroid#1838]
### 功能描述

我注意到v2rayNG有一个添加到桌面的安卓小部件可以实现一键运行的功能，clash什么时候可以增加此快捷功能呢？

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
