### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 55457** [Kr328/ClashForAndroid#1846]
### 描述此错误

没办法导入

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:Xiaomi
- 系统类型:MIUI 
- Android 版本:13

### 应用信息

- 版本:2.5.12
- 安装包文件名:
- 应用来源:Google play

### 配置文件

```yml
https://v2yun.pro/link/xxYRnOETowQmeQHQ?clash=1
```

### 日志

```raw
[APP] Logcat level: info
```

### 屏幕截图

![Screenshot_2023-03-05-07-31-53-135_com github kr328 clash foss](https://user-images.githubusercontent.com/126993091/222934433-2533828d-3a8a-43cc-b830-18879192b367.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
