### ISSUE TITLE
[BUG] 软件网站打不开了

### ISSUE THREAD

**Issue by 332272** [Kr328/ClashForAndroid#1847]
### Describe the bug

网站tizidi.net打不开了

### To Reproduce

Step 1: ...
Step 2: ...
Step 3: ...
...

### Device Info

- Device:
- ROM:
- Android Version:

### Application Info

- Version:
- APK filename:
- Distribution Channel:

### Configure File

```yml
网站tizidi.net打不开
```

### Logs

```raw
网站tizidi.net打不开
```

### Additional

网站tizidi.net打不开

**Comment by Kr328** [comment]
这里是 Clash for Android 项目仓库，不提供任何服务，没有任何网站。
