### ISSUE TITLE
如何在全局模式下，跳过特定几个网站，使这几个网址走直连

### ISSUE THREAD

**Issue by 9276** [Kr328/ClashForAndroid#1849]
### 功能描述

使用了全局模式，但是想跳过特定几个网站，使这几个网址走直连，请问有什么方法吗

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
