### ISSUE TITLE
判断为病毒软件

### ISSUE THREAD

**Issue by Sakura0512** [Kr328/ClashForAndroid#1855]
### 描述此错误

使用荣耀手机下载clash for Android,在下载界面会将应用判定为病毒应用，会被自动管控，无法正常使用.估计是缺少安全文件

### 如何复现该错误

步骤 1: github下载任意版本clash
步骤 2: 安装提示为病毒软件
步骤 3: 手机管家自动管控
...

### 设备信息

- 机型:honor 70 pro
- 系统类型:magicOS
- Android 版本:12

### 应用信息

- 版本:2.5.12-premium
- 安装包文件名:cfa-2.5.12-premium-arm64-v8a-release.apk
- 应用来源:github

### 配置文件

```yml
无
```

### 日志

```raw
无
```

### 屏幕截图

![Screenshot_20230309_090902](https://user-images.githubusercontent.com/127274758/223889292-34e3494b-c4a4-4846-915a-b8b7b6114fca.jpg)

![Screenshot_20230309_090850](https://user-images.githubusercontent.com/127274758/223889286-478519b5-bd25-402b-bb77-da36ad08d340.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
