### ISSUE TITLE
Judge as virus application

### ISSUE THREAD

**Issue by Sakura0512** [Kr328/ClashForAndroid#1856]
### Feature Description

When using the mobile phone to download clash for Android, the application will be judged as a virus application in the download interface, which will be automatically controlled and cannot be used normally. It is estimated that the security file is missing

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
