### ISSUE TITLE
[Feature Request] 我的配置文件没用了，为啥啊

### ISSUE THREAD

**Issue by bigsea-ui** [Kr328/ClashForAndroid#1859]
### 功能描述

填入之前的配置文件后显示配置错误，不知道为什么，求一个有用的😭

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
