### ISSUE TITLE
[BUG] 安装不上怎么办？

### ISSUE THREAD

**Issue by rehack** [Kr328/ClashForAndroid#1863]
### 描述此错误

foss和premium版本都在huawei手机中安装不上

### 如何复现该错误

尝试了cfa-2.5.12-foss-arm64-v8a和cfa-2.5.12-premium-arm64-v8a这两个版本都安装不上?

### 设备信息

- 机型:huawei P30
- 系统类型:Harmony OS
- Android 版本:2.0

### 应用信息

- 版本:2.5.12
- 安装包文件名:cfa-2.5.12-foss-arm64-v8a-release.apk和cfa-2.5.12-premium-arm64-v8a-release.apk
- 应用来源:github release

### 配置文件

```yml
未安装
```

### 日志

```raw
未安装
```

### 屏幕截图

![Screenshot_20230312_100148_com huawei appmarket](https://user-images.githubusercontent.com/9047357/224520140-18b51b77-92d1-40cc-bb42-86328bcfa0e1.jpg)

**Comment by Yu-Xiao-CN** [comment]
把纯净模式关了

**Comment by rehack** [comment]
> 把纯净模式关了

关了就可以安装了，非常感谢
