### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yzy716** [Kr328/ClashForAndroid#1875]
### 描述此错误

用nvidia shield tv 下载了clash，保存订阅设置时总是提示这个x509证书过期问题，请问有什么解决办法吗，谢谢！

具体
get "https://sub.....订阅地址....": x509: certificate has expired or is not yet valid: current time 2022-10-17T04:4507Z is before 2023-02-06T23:28:54Z

### 如何复现该错误

步骤 1: 安装apk
步骤 2: 新的配置url
步骤 3: 保存配置
...

### 设备信息

- 机型: nvidia shield ANDROID tv p3430
- 系统类型: shield android tv SW version
- Android 版本: 9.1.1(33.2.0.157)

### 应用信息

- 版本: 2.5.4-premium
- 安装包文件名: cfa-2.5.4-premium-arm64-v8a-release.apk
- 应用来源: Google Play

### 配置文件

```yml
NA
```

### 日志

```raw
NA
```

**Comment by EKyero** [comment]
@yzy716 https://github.com/Kr328/ClashForAndroid/issues/1224
