### ISSUE TITLE
配置文件自动更新的问题

### ISSUE THREAD

**Issue by wzw1997007** [Kr328/ClashForAndroid#188]
目前最新版本的Clash for Android发现有时配置文件会在没有到你规定的时间就自动更新，并且可能会在短时间内多次重复更新同一个配置文件。

另外在另一个[issue](https://github.com/Kr328/ClashForAndroid/issues/176) 中提到的这种造成api资源消耗的现象我不认为是因为单位为秒导致的，而是我上述的这个bug导致的。
![IMG_20200305_011203_912](https://user-images.githubusercontent.com/24762710/75904554-62851300-5e7e-11ea-9a1d-ce35c78b4243.jpg)

**Comment by Kr328** [comment]
1. 没有精确按照时间更新更新 是 **预期行为**
Android 自 4.4 起 开始限制 精确计时行为 
虽然现在也能够设置精确计时
但是我不认为应该让一个非即时性服务唤醒休眠的设备以提升功耗

2. 重复更新 是 实现上的问题

**Comment by honbolau** [comment]
能否添加个开关开关闭这个自动更新提醒。否则短时间内出发错误。状态栏都是提示更新@Kr328

**Comment by Kr328** [comment]
@honbolau 不能 否则 系统会限制 App 在后台运行

**Comment by honbolau** [comment]
> @honbolau 不能 否则 系统会限制 App 在后台运行

手动添加白名单也不行吗😂😂😂

**Comment by Kr328** [comment]
@honbolau 不行

**Comment by honbolau** [comment]
> @honbolau 不行

那不发通知，， 显示流量的还在应该可以吧😂😂😂

**Comment by txyyh** [comment]
> > @honbolau 不行
> 
> 那不发通知，， 显示流量的还在应该可以吧

这个可以设呀，通知设置界面分开来的
![Screenshot_20200321-152656.jpg](https://i.loli.net/2020/03/21/gm4Vw7ds1NpMyLC.jpg)

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
