### ISSUE TITLE
Android TV, when the VPN is connected, the Internet is completely disconnected [BUG] 

### ISSUE THREAD

**Issue by mehdiiikeb** [Kr328/ClashForAndroid#1880]
### Describe the bug

On Android TV, when the VPN is connected, the Internet is completely disconnected, and when the VPN is turned off, the Internet status again says that the Internet is connected.

### To Reproduce

------------

### Device Info

SONY TV 85J

### Application Info

 Version: 2.5.4-premium

### Configure File

```yml
...........
```

### Logs

```raw
...........
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
