### ISSUE TITLE
[增加默认全局代理功能] 

### ISSUE THREAD

**Issue by zdghf** [Kr328/ClashForAndroid#1884]
### 功能描述

请增加默认开启全局代理功能。每次都要点进去手动开启全局代理真的挺麻烦的。
或者增加一个选择指定app全局代理功能会更好！这样一些本地的app连接速度也可以得到保证！

### 附加信息

万分感谢！

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by zdghf** [comment]
我就是用Issue Template创建的啊
