### ISSUE TITLE
URLTest测试了所有节点

### ISSUE THREAD

**Issue by alexlee728** [Kr328/ClashForAndroid#190]
当前选中的URLTest组可能只有几个，但是所有节点有几十个。这时候定时检查连通性时候是测试所有节点，而不是当前组包含的节点？

**Comment by Kr328** [comment]
@alexlee728 检查当前节点 刷新全部节点

**Comment by alexlee728** [comment]
> @alexlee728 检查当前代理组节点 刷新全部代理组节点信息

谢谢！

**Comment by alexlee728** [comment]
> @alexlee728 检查当前代理组节点 刷新全部代理组节点信息

谢谢！
