### ISSUE TITLE
怎么样删除我不想要的节点啊

### ISSUE THREAD

**Issue by laoshir233** [Kr328/ClashForAndroid#1904]
### 功能描述

有些节点 不想要怎么删除

### 附加信息

![Screenshot_2023-04-17-12-40-29-19_fb9683381e7bc023e44079fdae6a5002](https://user-images.githubusercontent.com/129805458/232379902-f956f674-24bc-4e6f-9e03-cb62b3410a31.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
