### ISSUE TITLE
[BUG] 访问控制应用包列表识别不了手机系统自带应用

### ISSUE THREAD

**Issue by Jasonanywhere** [Kr328/ClashForAndroid#1911]
### 描述此错误

访问控制应用包列表识别不了手机系统自带应用，比如手机设置，我想使用设置里的谷歌服务，用来验证账户，开全局太耗费机场流量

### 如何复现该错误

步骤 1: 打开clash设置
步骤 2: 点击网络
步骤 3: 找到访问控制应用包列表
...

### 设备信息

- 机型:Redmi k50pro
- 系统类型:
- Android 版本:

### 应用信息

- 版本: 2.5.12-permium
- 安装包文件名:cfa-2.5.12-premium-arm64-v8a-release.apk
- 应用来源:Google Play

### 配置文件

```yml
抱歉，不知道改如何下载，用浏览器打开是一大串英文字幕
```

### 日志

```raw
# Capture on 2023-04-26 19:32:01.060
19:32:01.061    Info: [APP] Logcat level: info
```

**Comment by EKyero** [comment]
@Jasonanywhere https://github.com/Kr328/ClashForAndroid/issues/971#issuecomment-826326458

**Comment by Jasonanywhere** [comment]
好的，谢谢
