### ISSUE TITLE
问一个问题算不上bug也不是功能请求，就是一用cfa就光猫断网 

### ISSUE THREAD

**Issue by GrimmYun** [Kr328/ClashForAndroid#1914]
### 功能描述

近期发现这么个问题，一用clashfor android，全剧模式，用了没一会儿，光猫宽带就会断一下自己重连，宽带灯直接不亮了，宽带是电信的，是不是电信设置了什么不让用梯子的设置，挺不明白的。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
