### ISSUE TITLE
[Feature Request] windows如何设置应用隔离

### ISSUE THREAD

**Issue by sansejin1206** [Kr328/ClashForAndroid#1930]
### 功能描述

windows如何设置只允许一部分的软件使用vpn服务。怎么做隔离呢？

### 附加信息

windows版本

**Comment by Kr328** [comment]
![图片](https://github.com/Kr328/ClashForAndroid/assets/39107975/df146ef6-3090-4256-9607-1fca485ff886)

你问我?
