### ISSUE TITLE
[BUG] 证书问题

### ISSUE THREAD

**Issue by rioufbi** [Kr328/ClashForAndroid#1936]
### 描述此错误

在更新配置文件的时候提示：x509: certificate has expired or is not yet valid 当前时间是2023 过期时间是2021。
配置文件是我自己写的。
配置文件位置是放在CDN上，具体情况是之前可以正常下载，现在提示证书过期。

有问题的点应该就是CDN之前都是用的Cloudflare自有证书，现在变成了Let’s Encrypt证书。

然后我用安卓的Chrome 跟VIA浏览器都可以正常访问，没有提示证书问题。
用Clash就提示，后面尝试导入ISRG证书，但是没用，还是提示证书过期，现在没办法确认Clash获取的请求的证书到底是哪个证书。
安卓是5.1 虽然是比较老了，不过我这边用的频率还是挺高的，每天都会用到，所以想看看这个问题是否能够解决。

### 如何复现该错误

步骤 1: 安卓5.1的Remix平板 打开CFA
步骤 2: 配置-新增-URL-输入URL-保存
步骤 3: 报错

### 设备信息

- 机型:Remix
- 系统类型:RemixOS
- Android 版本:5.1

### 应用信息

- 版本:2.5.12，2.5.9，2.5.3
- 安装包文件名:cfa-2.5.12-premium-armeabi-v7a-release.apk
- 应用来源:github

### 配置文件

```yml
与配置文件无关
```

### 日志

```raw
暂无日志，提示如描述所示
```

**Comment by rioufbi** [comment]
有问题的点应该就是CDN之前都是用的Cloudflare自有证书，现在变成了Let’s Encrypt证书。
之前是正常的，应该就是Cloudflare自有证书，现在不正常的，应该就是Let’s Encrypt证书。
但是实际上用浏览器打开我自己的网站是没有问题的，没有提示证书错误。
就CFA下载配置时提示x509: certificate has expired or is not yet valid 当前时间是2023 过期时间是2021。

**Comment by imldy** [comment]
Let’s Encrypt旧根证书DST Root CA X3 在2020.9.30到期了，老安卓机没有新证书ISRG Root X1，官网说DST Root CA X3特殊交叉签名了ISRG Root X1可以让老安卓继续工作，但是好像得在服务器端配置。

https://letsencrypt.org/zh-cn/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by rioufbi** [comment]
> Let’s Encrypt旧根证书DST Root CA X3 在2021.9.30到期了，老安卓机没有新证书ISRG Root X1，官网说DST Root CA X3特殊交叉签名了ISRG Root X1可以让老安卓继续工作，但我实测不行，具体行不行取决于应用层软件。
> 
> https://letsencrypt.org/zh-cn/docs/dst-root-ca-x3-expiration-september-2021/

应该是这个问题了，我用VIA浏览器是可以正常打开我的那个用新ISRG证书的网站，而且也显示是证书安全的，就是clash就会提示证书过期，我一开始还在想是不是劫持什么的，但是仔细一想应该可能性不大。
之前是可以正常更新的，我之前是有注意网站证书这方面的事情，看了是用的Cloudflare自有证书，这个的根证书应该在安卓里面有，所以就没提示，然后前段时间我大改了下配置，准备更新一下，发现提示证书过期了，导入ISRG的证书也用不了。
所以来这里发个issue看看开发组那边能不能新增个功能支持下用户新增的证书，或者将证书导入APP里。

**Comment by Samuellee1986** [comment]
在电视端安装遇到同样的问题，这个目前还没有解决方法么？个人编译的话需要在哪里修改？用啥接口可以兼容老的认证，哪位大佬给个明路

**Comment by imldy** [comment]
可以尝试使用订阅转换服务，因为这是个天然的反代，使用后APP接触到的是订阅转换服务器的证书，如果订阅转换服务器证书没问题，就可以。

**Comment by rioufbi** [comment]
我的平板root了，准备看看这个方法：https://github.com/Kr328/ClashForAndroid/issues/1224
直接修改系统底层的根证书。

**Comment by rioufbi** [comment]
通过上面1224的方法，已经可以正常添加了。

**Comment by rioufbi** [comment]
> 在电视端安装遇到同样的问题，这个目前还没有解决方法么？个人编译的话需要在哪里修改？用啥接口可以兼容老的认证，哪位大佬给个明路

根据 Kr328 的说法
Clash for Android just trust certs in /system/etc/security/cacerts

It is built with Android ROM
以后如果有证书上的问题，ROOT情况下可以将证书放进/system/etc/security/cacerts（目前确认安卓5.1是这个位置，其他如果没有的，还得自行查找） 644权限，重启后就可以了。

**Comment by Samuellee1986** [comment]
嗯嗯，谢谢了！我后续按照rioufbi提供的1224方法解决了！

李德银 ***@***.***> 于2023年6月17日周六 16:33写道：

**Comment by Samuellee1986** [comment]
的确按照1224方法，我在电视端也解决此问题了，谢谢

rioufbi ***@***.***> 于2023年6月17日周六 19:53写道：
