### ISSUE TITLE
移动4G无法通过clash访问youtube

### ISSUE THREAD

**Issue by BOBANDJOB** [Kr328/ClashForAndroid#194]
手机端可以通过wifi正常访问Youtube，而使用4G网络就无法访问。

**Comment by Kr328** [comment]
贴上你的规则和DNS
以及应用的 `网络`(`Network`) 部分的设置

**Comment by BOBANDJOB** [comment]
type: ss
            "server": "sz-vip12.ss4663.com",
            "server_port": 60679,
            "local_port": 1080,
            "method": "chacha20-ietf-poly1305",
            cipher: chacha20-ietf-poly1305

**Comment by Kr328** [comment]
??? 你这代理数据全都暴露了

你知道 Clash 是什么吗
你知道 Clash 的 规则 是什么吗
你知道 Clash 的 DNS 是什么吗

不知道的话 去 Google

**Comment by BOBANDJOB** [comment]
谢谢提醒。（更正：不是无法访问，而是用4G运行相比wifi使用十分卡顿）
规则：DomainKeyword
DNS：www.youtube.com
Network: 通过vpnservice路由所有系统流量
关闭ipv6
绕过私有网络地址
处理所有DNS数据包
强制使用内置DNS配置
自动追加系统DNS到clash

**Comment by BOBANDJOB** [comment]
谢谢提醒。（更正：不是无法访问，还是用4G运行clash相比wifi来说十分卡顿）
规则：DomainKeywords
DNS：www.youtube.com
网络：通过vpnservice路由所有系统流量
关闭ipv6
绕过过私有网络地址
处理所有DNS数据包
强制使用内置DNS配置
自动追加系统DNS到冲突

**Comment by BOBANDJOB** [comment]
谢谢提醒。（更正：不是无法访问，还是用4G运行clash相比wifi来说十分卡顿）
规则：DomainKeywords
DNS：www.youtube.com
网络：通过vpnservice路由所有系统流量
关闭ipv6
绕过过私有网络地址
处理所有DNS数据包
强制使用内置DNS配置
自动追加系统DNS到clash

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复

**Comment by dskajfdlsaj6453** [comment]
手机上，设置--->网络和互联网--->找到移动网络--->找到：接入点名称  APN (ACCESS POINT NAMES)  ，把里面的IPv6关闭，如果不能修改，新建一个APN，不要IPv6. 就能解决

**Comment by ga0xia0b0** [comment]
> 手机上，设置--->网络和互联网--->找到移动网络--->找到：接入点名称 APN (ACCESS POINT NAMES) ，把里面的IPv6关闭，如果不能修改，新建一个APN，不要IPv6. 就能解决

谢谢大佬！同样的问题，已解决
