### ISSUE TITLE
Ambiguous feature list

### ISSUE THREAD

**Issue by rektpartyaftermath** [Kr328/ClashForAndroid#1940]
# Ambiguous feature list
Why the text exclude external-controller got strikethrough "~~exclude external-controller~~" , it make me think this app support external controller.

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
