### ISSUE TITLE
设置订阅地址的时候line15错误 

### ISSUE THREAD

**Issue by Nicole9256** [Kr328/ClashForAndroid#1943]
### 描述此错误

按照安卓的安装教程下载了软件，在第二步设置订阅地址的时候出现这样的问题

### 如何复现该错误

步骤 1: 官网上下载安卓软件
步骤 2: 设置订阅地址，一键导入clash和复制clash订阅都出现这样的问题

### 设备信息

- 机型:iqoo neo5 v2055A
- 系统类型:ORIAINOS原系统
- Android 版本:PD2055B_A_6.12.3

### 应用信息

- 版本:2.5.12.premium
- 安装包文件名:cfa-2.5.12-premium-universal-release.apk
- 应用来源:软件官网

### 配置文件

```yml
https://gkd.itjustasub.top/link/TlYi3JKmvyN72ZqZ?clash=1
```

### 日志

```raw
第一次下载的
```

### 屏幕截图

![21a49b496bb4a3fe44866b80efad9f9](https://github.com/Kr328/ClashForAndroid/assets/135047593/6de9228e-234f-445a-b38f-ad0b5606cb1a)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
自行联系你的配置提供商并重置订阅

![图片](https://github.com/Kr328/ClashForAndroid/assets/39107975/3ec7966b-9de3-4788-a2f3-a164d64c2c26)
