### ISSUE TITLE
配置文件不支持shadowsocks一位数字密码[BUG] 

### ISSUE THREAD

**Issue by ktownag** [Kr328/ClashForAndroid#1946]
### 描述此错误

保存配置文件时报错，无法解析

### 如何复现该错误

步骤 1: 修改配置文件，将shadowsocks密码修改为一位数密码
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:13

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
略
```

### 日志

```raw
略
```

### 屏幕截图

![Screenshot_2023_0603_150743](https://github.com/Kr328/ClashForAndroid/assets/42381296/597d55f9-8d9d-4a9c-ace4-4a06f1740924)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
