### ISSUE TITLE
MIUI11 已设置分应用代理，但是淘宝还是不能领券，提示系统休息，关闭VPN后正常了。

### ISSUE THREAD

**Issue by douzicao** [Kr328/ClashForAndroid#195]
MIUI11 已设置分应用代理，但是淘宝还是不能领券，提示系统休息，关闭VPN后正常了。

**Comment by Kr328** [comment]
抓点日志

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
