### ISSUE TITLE
有没有好兄弟来敢来试试水

### ISSUE THREAD

**Issue by NianBroken** [Kr328/ClashForAndroid#1951]
### 功能描述

今天逛谷歌发现了一个叫`欧盟全球网络加速协会`的东西
第一次听这个名字
链接是这个：https://eugnaa.eu-gov.eu.org/

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
