### ISSUE TITLE
[BUG] 鸿蒙3.0无法运行

### ISSUE THREAD

**Issue by insOs** [Kr328/ClashForAndroid#1954]
### 描述此错误

安装完毕后打开提示“好像获取配置失败了 请检查网络并重试手机” 无法正常打开

### 如何复现该错误

软件是第一次下载

### 设备信息

手机系统：鸿蒙3.0

### 应用信息

版本：2.5.12

### 配置文件

```yml
无
```

### 日志

```raw
无
```

**Comment by zeu33** [comment]
同鸿蒙，我之前就用这个，昨天突然不好使了，可以启动但是一直显示0bytes/s，只能看普通网页

**Comment by zeu33** [comment]
解决了吗

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
