### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ximenson** [Kr328/ClashForAndroid#1956]
### Feature Description

请问下现在是不是只剩下美国和英国节点？日本和香港的都消失了

### Additional

请问下现在是不是只剩下美国和英国节点？日本和香港的都消失了

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@ximenson 这里是 ClashForAndroid 项目，不提供任何服务，没有任何节点谢谢
