### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zeu33** [Kr328/ClashForAndroid#1957]
### 描述此错误

可以启动但是无法使用

### 如何复现该错误

步骤 1: 点击启动
步骤 2: 运行中，但是一直是0bytes/s，网页也打不开

### 设备信息

- 机型:华为mate40pro
- 系统类型:鸿蒙
- 版本:3.0.0.215

### 应用信息

- 版本:2.5.12[TCP] dial 🏆 Flyint飞数 (match Match/) to data.flurry.com:443 error: alibaba.cdn.01.servers.aliyunikunlunaq.com:45903 connect error: dial tcp4 157.122.96.32:45903: i/o timeout
- 应用来源:飞数官网

### 配置文件

```yml
无
```

### 日志

```raw
[TCP] dial 🏆 Flyint飞数 (match Match/) to data.flurry.com:443 error: alibaba.cdn.01.servers.aliyunikunlunaq.com:45903 connect error: dial tcp4 157.122.96.32:45903: i/o timeout
```

### 屏幕截图

![Screenshot_20230613_005047_com github kr328 clash foss](https://github.com/Kr328/ClashForAndroid/assets/136304844/de4ec233-8655-4ad8-a8ab-469ea5779670)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by zeu33** [comment]
> Please use Issue Template to create issue 请务必使用 Issue Template 创建 Issue
> 
> [Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

我怎么解决我这个问题呢

**Comment by Aurelia333** [comment]
我的也是这样😭😭😭还是刚续的

**Comment by zeu33** [comment]
我那时候也是剩三天到期我就续了然后出问题了，但是我今天试了一下突然好使了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月14日(周三) 晚上11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kr328/ClashForAndroid] [BUG] 可以启动无法使用 (Issue #1957)




 
我的也是这样😭😭😭还是刚续的

**Comment by zeu33** [comment]
我把clash重新安装一遍当时也没好使，不知道怎么的昨天试一下突然就好使了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月15日(周四) 凌晨0:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kr328/ClashForAndroid] [BUG] 可以启动无法使用 (Issue #1957)




 
所以到底是哪里出了问题😭我的要不也在过几天看看？
