### ISSUE TITLE
error: websocket: duplicate header not allowed: Connection

### ISSUE THREAD

**Issue by ls148478** [Kr328/ClashForAndroid#196]
header里面加入Connection参数就会提示这个 如果重复的话 这个值默认的参数是什么呢 是keep-alive还是close 由于是拿来免流混淆 所以这个参数不得不写 求开发大大支招

**Comment by Kr328** [comment]
去上游提

**Comment by ls148478** [comment]
上游在哪啊

**Comment by naicfeng** [comment]
> 上游在哪啊

https://github.com/Dreamacro/clash

**Comment by ls148478** [comment]
> > 上游在哪啊
> 
> https://github.com/Dreamacro/clash

已得到回答 谢谢哥
