### ISSUE TITLE
[Feature Request] 建议使用『1像素悬浮窗』保持后台不被杀

### ISSUE THREAD

**Issue by starryspace** [Kr328/ClashForAndroid#1965]
### 功能描述

手机是MIUI 13，老是被杀后台。最近想到可以使用使用『1像素悬浮窗』保持后台不被杀。各位觉得如何？

**Comment by THR-hub** [comment]
vpn类不会轻易被系统杀掉，能被杀说明你该更换设备了。

**Comment by xuhaoyang** [comment]
@starryspace 1像素是好多年前的保活方案，现在需要引导用户开启浮动权限，这不合理

**Comment by starryspace** [comment]
> 



> vpn类不会轻易被系统杀掉，能被杀说明你该更换设备了。

为了一个缺点就否定整个设备，不至于，不至于

**Comment by starryspace** [comment]
> @starryspace 1像素是好多年前的保活方案，现在需要引导用户开启浮动权限，这不合理。
> 
> 且国产系统，绝大多数都能"正确识别＂这种操作的应用

这种方法，虽然有点不干净的感觉，但起码是有用的。而且也不是强制用户开启，而是用户按自己需要开启。

我手机上的李跳跳就很稳定，也不知道是哪里的问题。

**Comment by xuhaoyang** [comment]
不符合kr的设计思想不会支持。新版有了shizhiku sui的特权模式发自我的 iPhone在 2023年7月6日，12:08，starryspace ***@***.***> 写道：﻿

@starryspace 1像素是好多年前的保活方案，现在需要引导用户开启浮动权限，这不合理。
且国产系统，绝大多数都能"正确识别＂这种操作的应用

这种方法，虽然有点不干净的感觉，但起码是有用的。而且也不是强制用户开启，而是用户按自己需要开启。
我手机上的李跳跳就很稳定，也不知道是哪里的问题。

**Comment by starryspace** [comment]
@xuhaoyang 
> 不符合kr的设计思想不会支持。新版有了shizhiku sui的特权模式
不知道你所谓的『设计思想』是啥，连功能都不能保证，还拿什么『设计思想』出来唬人。

**Comment by xuhaoyang** [comment]
qs？

**Comment by dragove** [comment]
我的设备是MIUI14,并不存在你说的杀vpn类app的情况，为了防止自己误操作清空后台需要在后台锁定cfa，检查是否自己误操作引起的后台被清理。

**Comment by ExcellentHzj** [comment]
> @xuhaoyang
> 
> > 不符合kr的设计思想不会支持。新版有了shizhiku sui的特权模式
> 
> 不知道你所谓的『设计思想』是啥，连功能都不能保证，还拿什么『设计思想』出来唬人。

你的枪不小心走火把人杀了，到头来怪人家为什么不穿防弹衣。

**Comment by JerryWn12** [comment]
槽点太多。。
首先，一像素悬浮窗保活是完全违反 Android 开发规范的，这像是一个绿色开源的软件该有的样子吗？
其次，后台被杀完完全全 100% 是因为你用的国产 UI 或者是你的设置的问题，和这个软件没任何关系，你应该做的是去搜索 MIUI13 怎么防止杀后台。
最后，别人耐心解答你的问题，你就这么高的攻击性，说别人 “否定设备”、”唬人“。我劝劝你，你不要想着解决了，回国内局域网刷刷短视频看看乐子，别出来给别人添麻烦行吗？

**Comment by starryspace** [comment]
@JerryWn12
> 槽点太多。。 首先，一像素悬浮窗保活是完全违反 Android 开发规范的，这像是一个绿色开源的软件该有的样子吗？ 其次，后台被杀完完全全 100% 是因为你用的国产 UI 或者是你的设置的问题，和这个软件没任何关系，你应该做的是去搜索 MIUI13 怎么防止杀后台。 最后，别人耐心解答你的问题，你就这么高的攻击性，说别人 “否定设备”、”唬人“。我劝劝你，你不要想着解决了，回国内局域网刷刷短视频看看乐子，别出来给别人添麻烦行吗？

* 设置没问题，前面其他人的回复我只是忘了回复。保活本来就是一个难题，其他MIUI或者其他Android手机都会遇到这类问题，即使内存再大也可能出现该问题，你可以说是手机后台机制不合理，使用悬浮窗保活只是不得已而为之的办法而已。
* 前面有回复说『该换设备』，我只是『因为一个缺点就否定整个设备』，不是各自提出各自的观点吗，怎么在你眼里就『充满攻击性』，你是不是太敏感了？这个帖子里最具攻击性的回复是你的上一个回复。我只是希望要拿出事实和逻辑理性讨论。
* 你会上外网、你不刷短视频，这都能让你产生优越感是吗，你以为你很高级吗？
* 软件开源出来，我不能提出意见和问题吗？提出问题就是在浪费别人的时间？我提出的问题是随便提出来的吗？

**Comment by hustler-not-chatty** [comment]
换个系统吧，能随便杀 VpnService 的系统就是辣鸡不解释。

**Comment by nasheep** [comment]
还以为你在说淘宝...

**Comment by helloworld10010** [comment]
一个应用是抗衡不了rom的，主动给了所有rom提供的保活措施还是被杀你只能考虑rom的问题。既然是开源的你自己拿着改呗

**Comment by SainoNamkho** [comment]
> 一个应用是抗衡不了rom的，主动给了所有rom提供的保活措施还是被杀你只能考虑rom的问题。既然你觉得1像素能解决问题，是开源的你自己拿着改呗

这不是一个完全开源的项目，自己修改编译是拿不到premium core的。

**Comment by xtmfd** [comment]
那就成榴芒软件了

**Comment by helloworld10010** [comment]
> 
没那么简单，现在rom开发者也不是傻子
