### ISSUE TITLE
[BUG] 提示特价机场更新失败

### ISSUE THREAD

**Issue by zxcv866** [Kr328/ClashForAndroid#1967]
### 描述此错误

![Screenshot_20230706_064808](https://github.com/Kr328/ClashForAndroid/assets/138735986/0e94c94e-7b97-454c-9c10-8d2f34537529)
目前无法。使用流量。

### 如何复现该错误

步骤 1: ...打开VPN
步骤 2: ...打开浏览器
步骤 3: ...
...

### 设备信息

- 机型:IQOO10
- 系统类型:Oriainos 3

- Android 版本:13

### 应用信息

- 版本:2.5.7.foss
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
https://sub.372372.xyz/api/v1/client/subscribe?token=6695f56f2c719b423606d470f8e8bd7f
```

### 日志

```raw
[TCP] 127.0.0.1:39988 --> api.twitter.com:443 match DomainKeyword(twitter) using 特价机场[剩余流量：998.48 GB]
```

**Comment by zxcv866** [comment]
![Uploading Screenshot_20230706_065156.jpg…]()

**Comment by Kr328** [comment]
自行联系你的代理提供商。
