### ISSUE TITLE
APP排版和功能说明错别字

### ISSUE THREAD

**Issue by MreDiaos** [Kr328/ClashForAndroid#1973]
### 功能描述

因为不算bug的反馈，也不知道发在cfa这里合不合适。这里先感谢大佬的辛苦工作，给我们带来clash multplatform这样好看好用的APP。正在使用最新测试版3.0.3.premium，安卓和Windows平台的。
![Screenshot_20230709_111315_Clash for Android](https://github.com/Kr328/ClashForAndroid/assets/94931475/41c6e9e7-761b-4ee4-abb1-5fa68c7d3890)
个人建议：配置和代理这两个板块是否可以换一下位置，相对来说（可能是个人习惯）更习惯---“概览→代理→配置→设置”这样的APP排版，因为代理这个点开的概率远高于配置，个人觉得换个位置可能更顺手些。
![Screenshot_20230709_111350_Clash for Android](https://github.com/Kr328/ClashForAndroid/assets/94931475/99cb0c31-9822-4ca0-864e-ddde477495bd)
发现一个功能开关说明里的错别字？这个错别字没记错貌似从第一个测试版到最新的一直存在。（这个错别字如果我理解正确就算，理解错误请忽略）在“设置→入站→DNS服务器→IPv6”位置，在开关打开是功能说明里“不在 DNS 相应中筛除 IPv6 地址。”，这里的说明“相应”应该是“响应”吧，个人觉得属于说明错别字？当开关关闭时的功能说明应该是没有错别字的“在 DNS 响应中筛除 IPv6 地址。”结合开关对比说明文字应该“相应”属于错别字。
这个错别字在我使用APP的安卓和Windows平台上都有，其他平台不清楚，因为没有相应设备做试验。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
