### ISSUE TITLE
用华为和oppo手机时，clash在访问控制应用包列表中找不到找不到clash自己，怎么办，求教[Feature Request] 

### ISSUE THREAD

**Issue by hualuoshuijia** [Kr328/ClashForAndroid#1975]
### 功能描述

 用华为和oppo手机时，clash在访问控制应用包列表中找不到找不到clash自己，怎么办，求教

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
