### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by i8s301a** [Kr328/ClashForAndroid#198]
尝试了各种设置组合（包括：打开/关闭DNS Hijacking选项，打开/关闭DNS Config Override选项，在配置文件中使用redir-host模式），使用Chrome访问 [这个DNS泄漏测试](https://www.expressvpn.com/dns-leak-test) ，都会显示本地运营商的DNS服务器。

Append System DNS选项已关闭。

如需要提供配置文件或者log的话，请回帖告知。

版本：1.1.10

**Comment by Kr328** [comment]
**预期行为**

Clash 的 DNS 查询 均为 **本地查询**
之后会通过 redir-host 或者 fake-ip 反推域名 匹配规则
