### ISSUE TITLE
有没有大佬打包最新的Clash内核发布一下更新的？

### ISSUE THREAD

**Issue by f2sky** [Kr328/ClashForAndroid#1981]
### 功能描述

有没有会 Android 开发的大佬？仅更新 Clash 内核发布一下更新。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
