### ISSUE TITLE
[BUG] Clash 的 Meta 内核最近听说报了高危漏洞，可以被人远程执行命令，请问 ClashForAndroid 也有这个问题吗？

### ISSUE THREAD

**Issue by ashuralyk** [Kr328/ClashForAndroid#1985]
### 描述此错误

https://youtu.be/4AnapDDMlyI

### 如何复现该错误

参看 Youtube 视频演示方式

### 设备信息

- 机型: Galaxy S23
- 系统类型: One UI 5.1
- Android 版本: 13

### 应用信息

- 版本: 2.5.12.premium
- 安装包文件名:
- 应用来源: Google Play

### 配置文件

```yml
N/A
```

### 日志

```raw
N/A
```

**Comment by linghengqian** [comment]
- Just to remind you that the Clash Premium used in this project is a closed-source kernel, which has nothing to do with the Clash specification implementation of the open-source Clash Meta.
- This issue should be closed and marked as invalid.
