### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SolitaryEgo** [Kr328/ClashForAndroid#1986]
### 描述此错误

前景提要：https://github.com/Kr328/ClashForAndroid/issues/1860
和他的问题一模一样

自启动、锁后台、电池无限制都试过了，还是一样没效果。

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:12

### 应用信息

- 版本:2.5.12-premium
- 安装包文件名:cfa-2.5.12-premium-arm64-v8a-release.apk
- 应用来源:Github

### 配置文件

```yml
.
```

### 日志

```raw
.
```

### 屏幕截图

![image](https://github.com/Kr328/ClashForAndroid/assets/115763944/7c851062-690a-4f14-b5a2-684118bef1d9)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
