### ISSUE TITLE
设置分应用代理: Youtube, Playstore不能正常使用。[BUG] 

### ISSUE THREAD

**Issue by yonsanjohnson** [Kr328/ClashForAndroid#1997]
### 描述此错误

设置分应用代理: Youtube, Playstore不能正常使用。
小米13Ultra手机，除非通过其他VPN软件打开一次YOUTUBE, PLAYSTORE
目前这两个软件是无法打开的，只有通过其他VPN打开一次后，才能用。但是过一会又不行了。

### 如何复现该错误

步骤 1: ... 分应用设置 Youtube，Playstore走代理
步骤 2: ... 打开Clash上网，发现两个软件无法正常浏览
 

### 设备信息

- 机型: 小米13Ultra
- 系统类型: MIUI14
- Android 版本: 13

### 应用信息

- 版本: 18.30.36
- 安装包文件名: com.google.android.youtube
- 应用来源: Playstore

### 配置文件

```yml
不方便上传，抱歉。
```

### 日志

```raw
不方便上传，抱歉。
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
