### ISSUE TITLE
[BUG] 设置分应用代理: Youtube, Playstore不能正常使用。

### ISSUE THREAD

**Issue by yonsanjohnson** [Kr328/ClashForAndroid#1998]
### 描述此错误

设置分应用代理: Youtube, Playstore不能正常使用。
小米13Ultra手机，除非通过其他VPN软件打开一次YOUTUBE, PLAYSTORE
目前这两个软件是无法打开的，只有通过其他VPN打开一次后，才能用。但是过一会又不行了。

### 如何复现该错误

步骤 1: ...分应用设置 Youtube，Playstore走代理
步骤 2: ...打开Clash上网，发现两个软件无法正常浏览
步骤 3: ...
...

### 设备信息

- 机型: 小米13Ultra
- 系统类型: MIUI14
- Android 版本: 13

### 应用信息

- 版本: 18.30.36
- 安装包文件名: com.google.android.youtube
- 应用来源: Playstore

### 配置文件

```yml
不方便上传，抱歉。
```

### 日志

```raw
不方便上传，抱歉。
```

**Comment by MOldtime** [comment]
这个属于自己的问题，你找下其它原因吧

**Comment by MOldtime** [comment]
> 我也遇到了，不是单个vpn应用的问题，是所有vpn，连公司的vpn都无法在youtube等app联网，但用浏览器访问youtube网站却正常

测试app依然正常 请排查其他原因

**Comment by yonsanjohnson** [comment]
> 这个属于自己的问题，你找下其它原因吧

你好！我三台不同小米手机，在联通的宽带或者联通的5G网络下试过很多次，存在同样的现象。YOUTUBE和商店绝对无法打开。
除非用SSR之类的代理全局开一次之后才有用。而这两个软件不管设置分代理应用或者不设置 都是同样的现象。

**Comment by yonsanjohnson** [comment]
> 
你好！我三台不同小米手机，在联通的宽带或者联通的5G网络下试过很多次，存在同样的现象。YOUTUBE和商店绝对无法打开。
除非用SSR之类的代理全局开一次之后才有用。而这两个软件不管设置分代理应用或者不设置 都是同样的现象。

**Comment by MOldtime** [comment]
> > 这个属于自己的问题，你找下其它原因吧
> 
> 你好！我三台不同小米手机，在联通的宽带或者联通的5G网络下试过很多次，存在同样的现象。YOUTUBE和商店绝对无法打开。 除非用SSR之类的代理全局开一次之后才有用。而这两个软件不管设置分代理应用或者不设置 都是同样的现象。

你说的也许是真实情况 但无法获得验证 我在电信网络下依然无法复现
在无法提供日志的情况下 希望你可以主动排查 Youtube 与 Google Play 是否走了对应的规则，节点是否异常，某些节点使用其它网站没问题 但是打开Play商店就会出现一些问题

**Comment by zhuji-fudan** [comment]
打开`访问控制应用包列表`, 点击右上角`过滤`, 取消`系统应用`的勾勾.

检查一下 `Dynamic System Updates` 和 google相关服务有没有选上.

我之前也遇到这种情况, 而且只有google家的应用连不了vpn; 这是因为他们依赖某些隐藏的系统应用, 他们同样需要使用vpn

![191693461171_ pic](https://github.com/Kr328/ClashForAndroid/assets/44150636/b17f3e94-5f29-43bc-9b28-aa8e2b7a5401)
