### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wangyuxiao20002237** [Kr328/ClashForAndroid#1999]
### 描述此错误

导入配置时提示yaml：do not find expected key，无法正常通过url方式导入配置

### 如何复现该错误

步骤 1: 创建配置
步骤 2: 从URL导入
步骤 3: 填写URL，并保存

出现错误信息

### 设备信息

- 机型:
- 系统类型:
- Android 版本: 12

### 应用信息

- 版本: 2.5.12
- 安装包文件名:
- 应用来源: 官网

### 配置文件

```yml
https://s1.qingyun.today/api/v1/client/subscribe?token=df533257e37b3e526285eb2f495d3e12
```

### 日志

```raw
[TCP] 127.0.0.1:65535 --> s1.qingyun.today:443 doesn't match any rule using DIRECT
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
