### ISSUE TITLE
配置更新失败[BUG] 

### ISSUE THREAD

**Issue by cxqdid** [Kr328/ClashForAndroid#2002]
### 描述此错误

连接不上，配置更新失败。
显示新配置:profile does not contain proxies or proxy-providers

### 如何复现该错误

步骤 1: 更新配置
步骤 2: .出现bug
步骤 3: ...
...

### 设备信息

- 机型:华为mate40e
- 系统类型:安卓
- Android 版本:

### 应用信息

- 版本:2.5.11.foss
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
https://s.52zm.cloud/api/v1/client/subscribe?token=08f608927f8aff48fece066e0f49e99a
```

### 日志

```raw
[TCP] 127.0.0.1:65535 --> s.52zm.cloud:443 doesn't match any rule using DIRECT
```

### 屏幕截图

![Screenshot_20230815_181337_com github kr328 clash foss](https://github.com/Kr328/ClashForAndroid/assets/34983060/33001505-14a5-47a5-b56d-d93f5d846ed1)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by cxqdid** [comment]
我是用issue template创建的啊

**Comment by cxqdid** [comment]
> Please use Issue Template to create issue 请务必使用 Issue Template 创建 Issue
> 
> [Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

我是用issue template创建的
