### ISSUE TITLE
Play版和github版有什么区别？

### ISSUE THREAD

**Issue by xtmfd** [Kr328/ClashForAndroid#2005]
### 描述此错误

如题

### 如何复现该错误

步骤 1: 这不是bug
...

### 设备信息

- 机型:HUAWEI P20
- 系统类型:HarmonyOS 3.0
- Android 版本:Android 10

### 应用信息

- 版本:2.5.12
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
配置文件
```

### 日志

```raw
日志
```

### 屏幕截图

截图

### 附加信息

信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
