### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by gitHubDujianfeng** [Kr328/ClashForAndroid#2009]
### 功能描述

请问、怎么将该项目打包成aar、或者如何能把build.gradle.kts 格式的 、改成默认的build.gradle

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
