### ISSUE TITLE
在 [设置] 面板点击 [网络] 按钮后应用闪退

### ISSUE THREAD

**Issue by Jenichia** [Kr328/ClashForAndroid#2012]
### 描述此错误

配置 Fallback 网段时，原先设定网段 `240.0.0.0/4` 并确认后，退出应用并重新打开，把该网段删除时应用闪退，此后无论是强制退出应用还是重启设备都无法打开 [设置] 面板中的 [网络] 按钮，只要点击 [网络] 按钮应用就会闪退。

### 如何复现该错误

如错误简介所描述之。

### 设备信息

- 机型: Honor 50
- 系统类型: MagicOS 7.0
- Android 版本: 12

### 应用信息

- 版本: 3.0.3-premium
- 安装包文件名: cfa-3.0.3-premium-arm64-v8a-release.apk
- 应用来源: Telegram Channel

### 配置文件

```yml
无。
```

### 日志

```raw
见附件。
```

### 附加信息

[clash-bugreport.zip](https://github.com/Kr328/ClashForAndroid/files/12639710/clash-bugreport.zip)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
