### ISSUE TITLE
Can't open tiktok using clash for Android app [Feature Request] 

### ISSUE THREAD

**Issue by aamir255** [Kr328/ClashForAndroid#2016]
### Feature Description

Hello there,

I'm a yearly subscriber of clash for Android. I'm having issue to open my tiktok account on my mobile. Please help me to access tiktok app.

Thanks

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
