### ISSUE TITLE
Tiktok app not working 

### ISSUE THREAD

**Issue by aamir255** [Kr328/ClashForAndroid#2017]
### Feature Description

Hi there,

I'm yearly subscriber of ure.best. but my tiktok app is not working.

Please help me to get accessible tiktok application.

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
