### ISSUE TITLE
开启ipv6，instagram无法刷新

### ISSUE THREAD

**Issue by liuyunyue** [Kr328/ClashForAndroid#202]
关闭ipv6后instagram就可以刷新了。这个功能难道是强制v2ray服务器出口走ipv6，需要v2ray服务器具有ipv6地址才能用？
=====================

开启cfa，规则跳过局域网和国内地址，访问国内双栈网站好像只能ipv4（网站ipv4无法打开，ipv6可以打开，也不连接ipv6，造成网站无法打开）？？？纯ipv6网站可以访问。
=====================

ipv6功能能否支持ipv6优先，不管经没经过代理，都ipv6优先，ipv6无法访问后才尝试ipv4访问。

**Comment by Kr328** [comment]
关于 IPv6 问题

Clash for Android 的 **IPv6 支持** 选项 
仅仅决定 VPN 服务是否提供 IPv6 支持
不代表 Core 是否会使用 IPv6
Clash Core 现在始终会尝试 IPv6 连接
IPv4 与 IPv6 **同时连接** 取最先连接成功
当然这些指的都是 Clash Core 指向 **服务端** 的连接
服务端到目的服务器的连接行为 **全部由服务端决定**
Clash 只是把 **尝试访问的域名** 发送给服务端 而不是目的地址
即使你想要所谓的 IPv6 优先 也是去上游反馈

Ins 与 Fackbook 的 连接问题
这两个应用存在缺陷
同时 Vmess 和 Shadowsocks 协议也存在缺陷
这两个协议不能正确反馈 TCP 状态
应用一旦尝试连接 VPN 服务立即接受这个连接
会给应用 IPv6 可用的错觉 即使 **IPv6 不可用**
 一般的应用在 IPv6 可用后 仍然尝试 IPv4 选择最先响应的连接
这两个应用不会
一旦认为 IPv6 可用 就只会创建 IPv6 连接 而忽略 IPv4
以上这些 **仅针对** 应用到 Clash Core 的 部分
