### ISSUE TITLE
hosts和doh问题

### ISSUE THREAD

**Issue by GuangYu-yu** [Kr328/ClashForAndroid#2021]
### 描述此错误

hosts只能一条条添加，应该新增直接添加文本和URL功能。dns的协议不能自定义，比如yandex的doh地址被识别为udp协议。

### 如何复现该错误

.

### 设备信息

- 机型:
- 系统类型:
- Android 版本:

### 应用信息

- 版本:cfa-3.0.3-premium
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
.
```

### 日志

```raw
.
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
