### ISSUE TITLE
[Feature Request] 购买节点的网址是什么

### ISSUE THREAD

**Issue by huazhi1234** [Kr328/ClashForAndroid#2024]
### 功能描述

购买节点的网址是什么

**Comment by keke6336** [comment]
没有，弟弟

**Comment by jymr92** [comment]
> ### 功能描述
> 
> 购买节点的网址是什么
> ### 附加信息
> 
> _No response_

https://ktmurl.top/#/register?code=IKdGZZvu

**Comment by AkariiinMKII** [comment]
![image](https://github.com/Kr328/ClashForAndroid/assets/6019344/081329b2-4f17-4592-a403-122b0c61c8cf)
