### ISSUE TITLE
3.0.3测试版增加状态栏快速磁贴

### ISSUE THREAD

**Issue by fzldrain** [Kr328/ClashForAndroid#2028]
### 功能描述

可以在测试版里增加状态栏快速磁贴么，状态栏下拉一键连接真的很方便的，

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
