### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by DONGYO454** [Kr328/ClashForAndroid#2031]
### 功能描述

希望在新版本中加入下滑面板快速打开磁铁，下滑磁铁实在是太方便了，希望后续版本能够延续这个设计

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
