### ISSUE TITLE
Clash for windows 删库跑路了？

### ISSUE THREAD

**Issue by buffcow** [Kr328/ClashForAndroid#2032]
### 描述此错误

突发，怎么个情况

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
none
```

### 日志

```raw
none
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
