### ISSUE TITLE
Can u add chashr Core

### ISSUE THREAD

**Issue by 986244073** [Kr328/ClashForAndroid#206]

**Comment by Kr328** [comment]
Nope

#56

**Comment by 986244073** [comment]
![image](https://user-images.githubusercontent.com/16508677/76504980-a336ea80-6483-11ea-80ca-36be39965797.png)
OK  I'll wait

**Comment by naicfeng** [comment]
整合了sh4的实现在cfa上实现的ssr支持
https://github.com/naicfeng/ClashRForAndroid

等上游合并pr可能需要好几个月，sh4表示现在无空
