### ISSUE TITLE
1.1.10URL导入就下载错误

### ISSUE THREAD

**Issue by ritafishy** [Kr328/ClashForAndroid#207]
之前都好的，今天突然连不上了，然后重新导入就开始连接失败，更新到最新版还是这样

**Comment by Kr328** [comment]
一张错误截图都没有是想让我猜吗

**Comment by ritafishy** [comment]
> 一张错误截图都没有是想让我猜吗
> 
> 那我先猜了你网络炸了
![微信图片_20200312195459](https://user-images.githubusercontent.com/62101165/76519193-7b538100-649b-11ea-9534-0ee3f3a4219c.jpg)
