### ISSUE TITLE
1.1.10URL导入失败

### ISSUE THREAD

**Issue by ritafishy** [Kr328/ClashForAndroid#208]
之前都好的，今天突然连不上了，然后重新引入就开始开始连接失败，更新到最新版还是这样
网络都正常啊
![微信图片_20200312195459](https://user-images.githubusercontent.com/62101165/76520060-1d279d80-649d-11ea-9f6c-604e7b6a2e48.jpg)

**Comment by Kr328** [comment]
典型配置文件问题

**Comment by ritafishy** [comment]
为什么我朋友这个配置文件用着没问题啊 我就下载不下来

**Comment by Kr328** [comment]
URL 贴浏览器上 下载下来文件
两个人的拿来一行行比对

**Comment by sharkman2008cn** [comment]
帅哥：我的红米手机，从文件导入，选择手机本地文件，trojan.yaml,点击“保存”提示下载失败，详情·：Proxy 1 :Unsupport proxy type:trojan, 同样配置文件，在macOS电脑成功。谢谢你的努力！

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
