### ISSUE TITLE
设置为暗黑主题时，重新打开有白色背景闪一下

### ISSUE THREAD

**Issue by koujiangheng** [Kr328/ClashForAndroid#209]
设置为暗黑主题，退出clash清理内存，再次打开时会闪一下白色再变为黑色，求修复！

**Comment by Kr328** [comment]
你得问 Google 为什么会这样

**Comment by koujiangheng** [comment]
感觉可能是默认启动背景为白色，你切换主题以后 可能因为没有设置flag 重新打开的时候系统框架没有判断主题模式，从而还是以白色背景启动。 参考https://stackoverflow.com/questions/4761686/how-to-set-background-color-of-an-activity-to-white-programmatically

**Comment by Kr328** [comment]
@koujiangheng 背景颜色取决于 主题 这玩意由 Google 的库提供 并非手动设置

**Comment by best-gjq** [comment]
> @koujiangheng 背景颜色取决于 主题 这玩意由 Google 的库提供 并非手动设置



> 你得问 Google 为什么会这样

你好请问能增加一个单个节点增加功能吗，有时候遇到散装节点无法添加就很头疼谢谢了（刚用我不会提功能建议对不起😭）

**Comment by Kr328** [comment]
> > @koujiangheng 背景颜色取决于 主题 这玩意由 Google 的库提供 并非手动设置
> 
> > 你得问 Google 为什么会这样
> 
> 你好请问能增加一个单个节点增加功能吗，有时候遇到散装节点无法添加就很头疼谢谢了（刚用我不会提功能建议对不起）

你到底了解过这个软件吗

配置里存在 **代理** **代理组** 和 **规则**

这些东西是强关联的 修改任何一个东西 其他东西都要关联修改 不能有应用来自动完成 

有这功夫还不如 还不如自己文本修改配置文件

**Comment by koujiangheng** [comment]
> > > @koujiangheng 背景颜色取决于 主题 这玩意由 Google 的库提供 并非手动设置
> > 
> > 
> > > 你得问 Google 为什么会这样
> > 
> > 
> > 你好请问能增加一个单个节点增加功能吗，有时候遇到散装节点无法添加就很头疼谢谢了（刚用我不会提功能建议对不起）
> 
> 你到底了解过这个软件吗
> 
> 配置里存在 **代理** **代理组** 和 **规则**
> 
> 这些东西是强关联的 修改任何一个东西 其他东西都要关联修改 不能有应用来自动完成
> 
> 有这功夫还不如 还不如自己文本修改配置文件

I did not ask this question

**Comment by Kr328** [comment]
This issue has been resolved
此问题已得到解决
