### ISSUE TITLE
[Feature request] Add collapsing for multiple proxies groups 为多代理组添加折叠

### ISSUE THREAD

**Issue by liuhuoz** [Kr328/ClashForAndroid#21]
For multiple proxies groups users, they will cost more time to locate the certain group at the bottom in the all expanding mode, right now.
Please add collapsing and expanding for proxies groups, it will reduce the time to locate and it's more pleasure to see.

p.s. This is a backup, for those mentioned it without submitted.
p.s.s. According to the developer, it will  increase the performance consumption when using such mode.

对于代理组非常多的用户来说，全部展开的情况下需要花费一段时间来选择位于列表下方的代理节点。
请添加代理组折叠功能，这样可以使用户更快的定位到特定代理组，并且看起来更美观。

p.s. 这是一个备份，因为很多人提到这个功能但是没有提交issue。
p.s.s 根据开发者的说法，使用折叠后会增加性能消耗。

**Comment by HeronZhang** [comment]
同求 调整底部节点太麻烦了 希望增加折叠

**Comment by Moriarty-989** [comment]
希望可以尽早实现这个功能，对于我这些自写配置，并且分组写的还很多的人挺重要的

**Comment by Kr328** [comment]
@Moriarty-989 放心吧 未来都没有的

**Comment by Moriarty-989** [comment]
> @ Moriarty-989放心吧未来都没有的

![image](https://user-images.githubusercontent.com/69113033/89571064-a6c77580-d859-11ea-9a5d-d65959885ab1.png)
