### ISSUE TITLE
配置好文件后无法启动

### ISSUE THREAD

**Issue by Dfp321** [Kr328/ClashForAndroid#211]
配置好文件后无法启动，一直是停止状态

**Comment by Kr328** [comment]
一张错误截图都没有是想让我猜吗

那我先猜了 你手机该换了

**Comment by Dfp321** [comment]
![涂鸦_Screenshot_2020-03-14-22-19-53-865_Clash](https://user-images.githubusercontent.com/49424552/76683846-15edc480-6642-11ea-9811-a4349c31695a.png)
点击启动一直无效，点了没有反应，一直显示已停止，

**Comment by Kr328** [comment]
@Dfp321 什么机型

**Comment by Dfp321** [comment]
坚果pro2，安卓版本太低了不兼容吗？安卓7.1

**Comment by ttimasdf** [comment]
……老板，你写个Issue template吧，这么下去不是个事。翻了一圈issue，竟然还有编译问题求助的，建议除了feature request和bug report之外，不按模板填的直接close。也给自己节约精力。心疼一秒 😅 
 @Kr328

**Comment by ZeryFroce** [comment]
Samsung S10+，也出现这种情况，订阅配置好后，点击启动无效

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
