### ISSUE TITLE
Clash for Android上传速率问题

### ISSUE THREAD

**Issue by ikelvingo** [Kr328/ClashForAndroid#212]
Clash for Android测试：
下载几乎可以达到150Mbps，上传一直徘徊在5~6Mbps
同样使用该线路，kitsunebi：
下载为80-90Mbps，上传为15-20Mbps
在路由器上使用openClash，
下载为近1,000Mbps，上传150Mbps

因此是否Clash for Android的上传部分的效能存在问题，导致上传速度存在天花板。

**Comment by hongxnc** [comment]
同样的问题，大佬帮帮开发者

**Comment by zincccccc** [comment]
华为P20（Android 10）上存在同样问题，上传徘徊在5~6Mbps。且只要连接vpn，无论app是否走代理，上传均被限速。关闭cfa后即恢复正常。

**Comment by txtyb** [comment]
Redmi K20 Pro，同样的问题，上传被限制在1Mbps左右。

**Comment by Kr328** [comment]
FIXED in 1.2.4
