### ISSUE TITLE
请问 All DNS requests failed 是什么原因呢

### ISSUE THREAD

**Issue by hjthjthjt** [Kr328/ClashForAndroid#216]
![Screenshot_20200316-122158](https://user-images.githubusercontent.com/3889846/76723108-235d9880-6781-11ea-9970-5662eba9ccb1.jpg)

设备中存在 Adguard，但并没有代理 Clash for Android，也并没有开启 Adguard 的 DNS，其通过 Root 权限的方式运行广告过滤。（在关闭 Adguard 的情况下情况没有改善）
同样的节点在其他平台却可以正常连接（同一局域网）

还有一堆有点迷惑的 timeout……

**Comment by Kr328** [comment]
取决于你的网络环境
也可能是查询的某个域名确实不存在

**Comment by hjthjthjt** [comment]
@Kr328 因为觉得很奇怪，一旦出现这种情况大概率节点会跟断开一样，但是在同一局域网下的 Windows 上的 Clash 的同一节点又可以正常使用

**Comment by Kr328** [comment]
@hjthjthjt 机型是 Mi 10 Pro ?

**Comment by hjthjthjt** [comment]
@Kr328 不是，一加7t Pro，官方 氢OS Q

**Comment by Kr328** [comment]
@hjthjthjt 大概是机型相关问题了 我个人管不了

**Comment by hjthjthjt** [comment]
@Kr328 破案了破案了我把整个 Adguard 停了外带卸载了他的 CA 证书就好了……

**Comment by qhfls** [comment]
不一定是Adguard的原因，在网络不好的情况下也可能出现。

**Comment by hjthjthjt** [comment]
@qhfls 之前在用原版 ss 的时候也出现过，只是换 Clash 后情况有点加剧……然后现在停了所有跟 Adguard 有关的之后稳的不行……（

**Comment by aniure** [comment]
> 取决于你的网络环境
> 也可能是查询的某个域名确实不存在

图中的 dial domestic error: dial tcp4 这个错误又是什么原因呢？我这里经常也有这种提示。
