### ISSUE TITLE
夜间模式配置更新时间文字颜色

### ISSUE THREAD

**Issue by cxyzzz** [Kr328/ClashForAndroid#218]
夜间模式配置更新时间文字颜色为黑色，无法看清。

**Comment by Kr328** [comment]
?
![Screenshot_20200316-192722](https://user-images.githubusercontent.com/39107975/76753969-4f4a3f80-67bc-11ea-82ca-06a9d2cf9fee.png)

**Comment by cxyzzz** [comment]
@Kr328 可能MIUI的锅。。。
![](https://i.imgur.com/qmFvC2r.jpg)
