### ISSUE TITLE
能不能把节点和规则分开？

### ISSUE THREAD

**Issue by taowuhan** [Kr328/ClashForAndroid#219]
让规则可自定义编辑，而不是修改配置文件。

**Comment by Kr328** [comment]
**代理组** **代理** 和 **规则** 是 **强关联** 不能拆开

**Comment by taowuhan** [comment]
那GEOIP 是随版本更新吗？能不能提供自更新接口？一键订阅的规则还是不能做到绝大数国内直连分流。

**Comment by Kr328** [comment]
不光随版本更新 还是动态从 apk 里载入的呢
除非能动态修改 apk 内容 否则不做
再一个 GEOIP 的 国家 IP 一年都不会变几条 有什么意义
