### ISSUE TITLE
Clash 运行时连接 WIFI 系统会认为 WIFI 无网络

### ISSUE THREAD

**Issue by NekoInverter** [Kr328/ClashForAndroid#22]
![IMG_20191210_140134_042](https://user-images.githubusercontent.com/42698724/70500118-b3be8880-1b55-11ea-910b-e1336cfecaca.jpg)
系统：Android 10(MIUI)
（ClashA Shadowsocks 都没这毛病

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
