### ISSUE TITLE
请求外置config.yaml文件

### ISSUE THREAD

**Issue by txyyh** [Kr328/ClashForAndroid#222]
如题，请求外置此文件以方便有一定动手能力的人进行配置

**Comment by Kr328** [comment]
这个版本没有请求外部存储权限
未来版本也不会

在不久的将来 应用会完全失去直接操作外部存储的能力 (Android R 已经开始测试
没有必要做一个马上就会被限制的功能

**Comment by txyyh** [comment]
。。。我指放到外置的“Android/data”（无需root权限即可访问那个），而不是现在的data

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/77034335-a03c7c80-69e4-11ea-8c5d-ada052b574cf.png)
你真以为 Android R 没有考虑到吗

**Comment by txyyh** [comment]
。。。我可能还是没表述正确

**Comment by Kr328** [comment]
Android R 后

无论是 /data/*
还是 /sdcard/Android/* 的数据 **都不再能被非本应用访问**

以及 存储在外部存储 会带来 数据库关联 与 配置文件关联 问题
如果外部文件出现变化 数据库不能正确同步 就可能造成 数据丢失
