### ISSUE TITLE
[Feature Request] 提供类似v2rayNG的分应用代理-自动选中需代理应用功能

### ISSUE THREAD

**Issue by lzp4ever** [Kr328/ClashForAndroid#224]
**功能描述**
如v2rayNG，在分应用代理列表添加一个自动选中需代理应用按钮

**描述你希望的实现方式**
v2rayNG维护了一个需代理应用列表
https://github.com/2dust/androidpackagenamelist/blob/master/proxy.txt

**附加信息**

https://github.com/2dust/androidpackagenamelist/

**Comment by Kr328** [comment]
访问控制是完全依照个人习惯配置 而不是一个简单的列表就能解决的

以及 维护工作量大 (要为全世界 各种不同的需求的人各维护一个列表 ?

**Comment by Kr328** [comment]
未来 (应该就在下个版本

会提供 PackageName(ProcessName) 规则
由配置文件决定部分包名的代理
