### ISSUE TITLE
想自己编译代码，后续可以提一些PR， 遇到点问题

### ISSUE THREAD

**Issue by fgprodigal** [Kr328/ClashForAndroid#225]
github.com/kr328/cfa 这个404仓库是什么…… GolangBindTask编译不过去

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/215#issuecomment-599521231

**Comment by fgprodigal** [comment]
> [#215 (comment)](https://github.com/Kr328/ClashForAndroid/issues/215#issuecomment-599521231)

好吧，编译过了，没装jdk
