### ISSUE TITLE
[BUG] ClashCore更改了部分配置命名

### ISSUE THREAD

**Issue by Aceralon** [Kr328/ClashForAndroid#227]
**描述出现的错误**
ClashCore已经更新了配置命名，导致目前无法正常运行
https://github.com/Dreamacro/clash/commit/88d8f937938d7aba774b1af638df6910b1a1a14d

**如何复现该错误**
复现步骤:
使用新的配置格式

**预期行为**
正常运行

**设备信息:**
 - 机型: PCLM10
 - 系统/ROM: ColorOS7
 - Android 版本 Q
 - ROM版本 PCLM10_11_C.21

**应用信息**
 - 版本: 1.1.10
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Github release

**Comment by WhiteBrownBottle** [comment]
请问该怎么改配置?

**Comment by OpaqueArc** [comment]
可以复现 复现症状表现为所有节点和规则均不可见
升级到最新版本系统可以解决#199里的问题 这个问题下的症状依旧存在

**Comment by Kr328** [comment]
FIXED in 1.2.0
