### ISSUE TITLE
[BUG] 没有文件读写权限，无法导入配置文件

### ISSUE THREAD

**Issue by uiGmTaqE1rAS** [Kr328/ClashForAndroid#228]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. pc 端编写规则，传到手机
2. 导入配置，提示无权限，tmp 和 temp 目录都不行，data 也不行。

**预期行为**
按理说导入流程应该顺畅，不会提示没有权限。

**屏幕截图**
配置 xml 中缺少权限：
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

**日志**

如果适用, 上传日志以帮助侦测错误

**设备信息 (请完成一下信息):**
 - 机型: 锤子 R1
 - 系统/ROM: 锤子6.7
 - Android 版本 8.0
 - ROM版本 

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
无

**Comment by Kr328** [comment]
系统问题 无法解决

理论上应该使用 Content Provider 提供文件
该方式为 **Android 规范** 且 不会需要权限
解决方法自便
