### ISSUE TITLE
[BUG] 节点名称显示不全

### ISSUE THREAD

**Issue by Ellean** [Kr328/ClashForAndroid#231]
**描述出现的错误**
在节点名称长度过长时不会自动横向滚动

**如何复现该错误**
复现步骤:
1. 在 Mokee 100 ( Android 10 ) 上会自动滚动
2. 在 JOS ( nubia， Android 9 ) 不会自动滚动

**预期行为**
在节点名称长度过长时自动横向滚动

**设备信息 (请完成一下信息):**
 - 机型: Nubia X
 - 系统/ROM: JOS 
 - Android 版本 P
 - ROM版本 2.0

**应用信息**
 - 版本: 1.1.10
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GitHub Release

**Comment by Kr328** [comment]
预期行为 因为已经移除掉了

未来再做替代的东西
