### ISSUE TITLE
[Feature Request] Clash已支持Trojan协议，Mac端Clash X已支持，希望Android端也适配

### ISSUE THREAD

**Issue by yuanoOo** [Kr328/ClashForAndroid#232]
- 1、Clash经过讨论，已经添加支持Trojan协议。

- 2、Mac端Clash X已支持Trojan协议

- 3、Trojan项目活跃，Clash For Android添加支持Trojan协议，有利于两大开源项目的发展

**Comment by naicfeng** [comment]
可以试一下我fork的版本。 [ClashRForAndroid](https://github.com/naicfeng/ClashRForAndroid) 
作者应该在下次更新core的时候会加上torjan的支持，毕竟上游已经支持了

**Comment by yuanoOo** [comment]
> 好的，谢谢

**Comment by maxfun0** [comment]
> 可以试一下我fork的版本。 [ClashRForAndroid](https://github.com/naicfeng/ClashRForAndroid)
> 作者应该在下次更新core的时候会加上torjan的支持，毕竟上游已经支持了

R2无法匹配规则，R1正常使用

**Comment by onlyJinx** [comment]
@naicfeng 请问R2版本规则匹配是不是有问题？

**Comment by xiandu999-yu** [comment]
> 可以试一下我fork的版本。 [ClashRForAndroid](https://github.com/naicfeng/ClashRForAndroid)
> 作者应该在下次更新core的时候会加上torjan的支持，毕竟上游已经支持了

R2规则不能用...

**Comment by naicfeng** [comment]
@yuanoOo @maxfun0 @onlyJinx @xiandu999-yu 
抱歉，这几天忙，今天看了下，是core更新了配置文件命名规则并默认读取新格式，导致cfa操作bridge切换模式失败。这个要等1.0上线后(强制新格式)，或者Kr328大神修改cfa识别兼容。
目前临时修复了一下
修改core为默认读取老格式配置，默认格式内容为空则读取新格式(与官方相反)

**Comment by onlyJinx** [comment]
@naicfeng thx

**Comment by heham** [comment]
下一版应该就能行了吧

**Comment by hldh214** [comment]
@naicfeng 来提个 pr 呗 😃

**Comment by sunlewuyou** [comment]
我附议！！

**Comment by naicfeng** [comment]
@hldh214 @sunlewuyou   
因为我的fork添加了ssr功能，上游还没有合并，上游认为代码还需要优化。
而cfa的core只同步上游更新，而且本次是上游更新的 trojan 协议，作者下次更新就会支持的，不用pr

**Comment by HougeLangley** [comment]
二楼完美

**Comment by heham** [comment]
今天的1.2版是不是还是不支持trojan？测试了一下不知道是不支持还是我配置文件写的不对

**Comment by onlyJinx** [comment]
支持的，我试过了
![Screenshot_20200414-221340_Clash for Android](https://user-images.githubusercontent.com/21324835/79234713-40c77480-7e9d-11ea-82d8-466a57f99f0a.jpg)

**Comment by onlyJinx** [comment]
顺便问下各位，，这个EOF的错误是怎么回事，我用浏览器把订阅链接下载下来导入可以，但直接添加链接就报这个错误
![SmartSelect_20200414-202106_Gallery](https://user-images.githubusercontent.com/21324835/79234930-8dab4b00-7e9d-11ea-992b-d30c3a9d3ad3.jpg)

**Comment by beckball** [comment]
> 今天的1.2版是不是还是不支持trojan？测试了一下不知道是不支持还是我配置文件写的不对

1.2x均已支持

**Comment by Kr328** [comment]
ADDED in 1.2.0

**Comment by cheneyxx** [comment]
@onlyJinx 我也遇到了EOF的报错 是怎么回事呢？

**Comment by onlyJinx** [comment]
> 事

太久了，忘了，好像是订阅的问题，你在浏览器打开订阅地址看看正常不
