### ISSUE TITLE
我无法绕过大陆

### ISSUE THREAD

**Issue by dandingdeaguan** [Kr328/ClashForAndroid#234]
我不论怎么调试都是全局模式 该怎么办？
版本是安卓10.0 手机是华为P30
PS：我在设置上并没有任何问题 但我不论怎么设置都是走全局而不是绕过大陆 模式也选的是规则

**Comment by Kr328** [comment]
1. 检查日志 是不是 **真的走代理了**
2. 务必使用模板创建 Issue

**Comment by dandingdeaguan** [comment]
> 1. 检查日志是不是**真的走代理了**
> 2. 最终使用模板创建

使用模板创建lssue是啥意思？ 不太懂

**Comment by Kr328** [comment]
Google 请

**Comment by iwantbee** [comment]
learning

Kr328 <notifications@github.com>于2020年3月23日 周一下午11:24写道：
