### ISSUE TITLE
[BUG] 关于「合并前缀」的问题

### ISSUE THREAD

**Issue by Lasovoc** [Kr328/ClashForAndroid#235]
**描述出现的错误**
当代理服务提供商使用 [] 作为节点信息的前缀时，使用「前缀合并」将不能正确合并。

**如何复现该错误**

**预期行为**

**屏幕截图**
clash 介面截图
![Screenshot_20200324-200811_Clash_for_Android](https://user-images.githubusercontent.com/42114763/77424120-8b5c5080-6e0b-11ea-9295-63be26c29026.png)

部分配置文件截图
![Screenshot_20200324-200920_](https://user-images.githubusercontent.com/42114763/77424183-a3cc6b00-6e0b-11ea-9bce-ff6e04121ac0.png)

**日志**

**设备信息 (请完成一下信息):**

**应用信息**
 - 版本: 1.1.10
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Google Play

**附加信息**

**Comment by Kr328** [comment]
预期行为 算法如此 如果你有更好的算法 欢迎提出来

**Comment by Lasovoc** [comment]
> 预期行为 算法如此 如果你有更好的算法 欢迎提出来

如果可行的话，添加以下：
( ) { } [ ] 【 】 「 」 『 』 < > 《 》 （ ） 『 』 〖 〗 ｛ ｝ 「  」 【 】 〔 〕 ［ ］ 「 」 『 』 〈 〉 《 》 等符号作为过滤规则。
