### ISSUE TITLE
考虑下剪切板导入代理应用的配置吗？

### ISSUE THREAD

**Issue by zhullyb** [Kr328/ClashForAndroid#238]
ssr和v2ray的安卓客户端都支持分应用代理，且可以导出配置（甚至两个app的配置可以通用），尽管我知道clash for Android也支持分应用代理，但是没有办法从剪切板导入配置，希望作者能够添加一键导入/导出剪切板的功能，并能够与ssr与v2ray通用

**Comment by Kr328** [comment]
务必按照模板创建 Issue
