### ISSUE TITLE
[Feature request] Add route private lan to different proxy

### ISSUE THREAD

**Issue by panda-mute** [Kr328/ClashForAndroid#24]
# Private Lan
- IP-CIDR,192.168.190.0/24,Node1
- IP-CIDR,192.168.199.0/24,Node2

在不同的路由器上开启了SS server，希望能够路由到不同的节点进行设备管理

**Comment by Kr328** [comment]
反馈到上游 请

**Comment by panda-mute** [comment]
因为这个功能clasha是有的， 所以不太确定是什么问题
![Screenshot_2019-12-10-17-50-26-387_com github ccg clasha](https://user-images.githubusercontent.com/23204415/70519383-cd23fc80-1b76-11ea-9924-4a02a2555dbf.jpg)

**Comment by Kr328** [comment]
Bypass Private Network 关掉

**Comment by panda-mute** [comment]
bypass private network关掉就ok，不好意思打扰了
