### ISSUE TITLE
[Feature Request] 自启动/升级相关的优化

### ISSUE THREAD

**Issue by Love4Taylor** [Kr328/ClashForAndroid#243]
**功能描述**
开机能在不解锁的情况下启动服务 (做成可选项也行) 以及升级 APP 不掉 VPN。

**描述你希望的实现方式**
参照 Shadowsocks-Android，前者应该和那个「允许锁屏时切换」选项有关。

**Comment by Kr328** [comment]
1. 不解锁启动服务 意味着 你的所有配置文件必须是 **不加密的** 我不认为应该为了一个没啥用的功能 放弃 数据安全性
2. 升级 App 意味着要升级编译后的代码 **没有可能** 在保留 Service 的情况下 更新 App
