### ISSUE TITLE
[Feature Request] 关于长节点的显示

### ISSUE THREAD

**Issue by pannnnnnn** [Kr328/ClashForAndroid#246]
**功能描述**
完整的显示较长的节点名

**描述你希望的实现方式**
目前对于长节点名的实现是前缀合并，但是主要有以下问题：
- 节点名不满足前缀合并条件（如订阅状态，网站地址等）
- 不能正确合并（算法问题）
- 合并完仍然过长（一些节点参数的标注）

我个人的想法，对长节点处理最好的是Clash for Windows，长度不变，同一行的宽度以最长节点为准。
![Clash_for_Windows_DXsp7ZAMuQ](https://user-images.githubusercontent.com/62750189/78011978-4aba8500-737f-11ea-8c25-b647969d7326.png)

其次是之前的跑马灯也还可以（1.0.32-alpha）

前缀合并我感觉应当交给Clash配置文件中的Proxy Group（现proxy-groups）来搞定，这样也方便根据自己的节点情况来进行调整。节点起名的规则各有不同，算法不能很好的适应。

（也可把多种显示方式都作为选项？）

**附加信息**
感谢K大对此项目的贡献，个人意见仅供参考。

**Comment by Doraemon2020** [comment]
机场主对前缀合并有免疫

**Comment by Doraemon2020** [comment]
1.动态高度
2.跑马灯
3.一行一个

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.1
