### ISSUE TITLE
Windows上面再次编译报错，Run command go mod vendor failure

### ISSUE THREAD

**Issue by Govien** [Kr328/ClashForAndroid#247]
从Mac折腾到Windows，还是未能成功编译，心态都崩了
windows上面执行命令.\gradlew.bat build之后：

> Task :core:golangBind
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/oschwald/geoip2-golang v1.4.0
go: downloading golang.org/x/net v0.0.0-20200202094626-16171245cfb2
go: downloading gopkg.in/eapache/channels.v1 v1.1.0
go: downloading golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
go: downloading github.com/Dreamacro/go-shadowsocks2 v0.1.5
go: downloading golang.org/x/crypto v0.0.0-20200214034016-1d94cc7ab1c6
go: downloading github.com/oschwald/maxminddb-golang v1.6.0
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/miekg/dns v1.1.27
go: downloading golang.org/x/sys v0.0.0-20191224085550-c709ea063b76
go: downloading github.com/comzyh/netstack v0.0.0-20191217044024-67c27819ada4
go: downloading github.com/gorilla/websocket v1.4.1
go: downloading github.com/gofrs/uuid v3.2.0+incompatible
go: downloading github.com/google/btree v1.0.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go mod vendor: open C:\Users\LICENSE: Access is denied.

> Task :core:golangBind FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:golangBind'.
> Run command go mod vendor failure

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
2 actionable tasks: 2 executed

**Comment by Kr328** [comment]
现在不再在 Issue 中提供编译支持
