### ISSUE TITLE
不支持Anankke的dev/SSPanel-Uim的clash订阅

### ISSUE THREAD

**Issue by ANHR0** [Kr328/ClashForAndroid#248]
dev版的订阅链接，clash电脑版可以导入（导入文件和一键导入），安卓用订阅链接一直提示下载错误，只能导入文件（新版V2RAY
的通用订阅链接是sub=3）

**Comment by Kr328** [comment]
那么请让他们支持 而不是让客户端去适配 

Clash for Android **仅接收 Clash 配置文件**
