### ISSUE TITLE
[Feature Request] clash core更新了tcp+http，能适配一下吗

### ISSUE THREAD

**Issue by Rasta0501** [Kr328/ClashForAndroid#250]
https://github.com/Dreamacro/clash/blob/dev/README.md
如题，希望大佬跟进一下

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/232

**Comment by Rasta0501** [comment]
没有啊，这个是v2ray的tcp+http混淆，与木马没关系啊

**Comment by Kr328** [comment]
@Rasta0501 都是跟进上游
