### ISSUE TITLE
配置文件新旧字段的兼容

### ISSUE THREAD

**Issue by doublewinter0** [Kr328/ClashForAndroid#251]
![clash](https://user-images.githubusercontent.com/22414051/78313566-bc661f00-7589-11ea-9d70-1096cd91bda8.png)

如上图, clash 修改了这两个字段. 我昨天尝试用新字段导入配置文件失败了, 换成旧字段导入成功! 所以能不能把新旧字段都兼容一下?

**Comment by Kr328** [comment]
#232
