### ISSUE TITLE
[BUG] 未正确记住代理设置

### ISSUE THREAD

**Issue by lm902** [Kr328/ClashForAndroid#254]
**描述出现的错误**
每次开启代理，模式都会被重置为“规则”，未正确记住代理设置。

**如何复现该错误**
复现步骤:
1. 启动代理
2. 进入代理选项
3. 将模式设置为“全局”
4. 关闭并重新启动代理

**预期行为**
在启动代理后，应记住上一次关闭时的代理设置。

**日志**
[2020-04-07 08:15:24.log.txt](https://github.com/Kr328/ClashForAndroid/files/4445447/2020-04-07.08.15.24.log.txt)

**设备信息 (请完成一下信息):**
 - 机型: 小米10 Pro
 - 系统/ROM: MIUI 11
 - Android 版本 10
 - ROM版本 20.3.28

**应用信息**
 - 版本: 1.1.10
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: GitHub

**Comment by Kr328** [comment]
预期行为

https://github.com/Kr328/ClashForAndroid/issues/137
