### ISSUE TITLE
[Feature Request] 一些功能请求

### ISSUE THREAD

**Issue by shenwei101623** [Kr328/ClashForAndroid#255]
长节点显示会自动提取公共部分，能支持手动决定公共部分吗，设置公共部分关键词或者汉字数量？
有可能内置测速吗（虽然感觉希望不大）？
知道clash测试延时的方法和正常ping不一样，但是数字看着很大就很难受，有可能测试延时方法和常见的ping一样吗？

**Comment by Kr328** [comment]
1. 现在的前缀合并就是找公共部分
2. 不做 太麻烦 没意义
3. 更没意义 现在的方式(httping) 才是最能代表实际体验的
