### ISSUE TITLE
希望增加对非select策略组折叠的支持

### ISSUE THREAD

**Issue by cccarbondioxide** [Kr328/ClashForAndroid#256]
**功能描述**
希望增添个按钮将urltest和fallback配置组折叠或隐藏

**描述你希望的实现方式**
增添一个按钮或部件

**附加信息**
部分配置文件繁冗复杂，需要大量的urltest和fallback策略组(10-20个)的支持，对视觉的观感不太友好

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

https://github.com/Kr328/ClashForAndroid/issues -> New Issue
