### ISSUE TITLE
[Feature Request] 折叠或隐藏无法主观选择的配置组

### ISSUE THREAD

**Issue by cccarbondioxide** [Kr328/ClashForAndroid#258]
**功能描述**

希望增加对非select策略组折叠的支持
部分配置文件繁冗复杂，
需要大量的urltest和fallback策略组(10-20个)的支持，
对视觉的观感和使用造成一定的困扰.

**描述你希望的实现方式**

希望通过设定一个按钮或选项,将urltest和fallback配置组进行隐藏
(如在目前cfa内实用工具选项中增加,如果可以的话,默认开启状态更佳)

**附加信息**
其他的与改功能相关的附加信息

**Comment by shenwei101623** [comment]
同求，但更希望能控制所有策略组的折叠，类似cfw那样~

**Comment by isArtJay** [comment]
同求，希望添加策略组折叠的功能，这样会一目了然

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.1
