### ISSUE TITLE
节点名称无法完整显示，建议参考surfboard的节点名称显示方式

### ISSUE THREAD

**Issue by coderloverXH** [Kr328/ClashForAndroid#259]
**描述出现的错误**
节点名称只能显示前4个字，无法完整显示。
如下图所示：
![1-2](https://user-images.githubusercontent.com/63088614/79035231-06d14680-7bef-11ea-99a2-1efcdf15b1b9.jpg)

**预期行为**
如果能完整显示节点名称就更好了，可以参考sufboard显示节点名称的方式：
![1-3](https://user-images.githubusercontent.com/63088614/79035253-40a24d00-7bef-11ea-9cd8-7c984b251019.jpg)

**设备信息 (请完成一下信息):**
 - 机型: 荣耀20
 - Android 版本：Android 10

**应用信息**
 - 版本: 1.1.10
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Google Play

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
