### ISSUE TITLE
关于添加Profile后页面跳转建议

### ISSUE THREAD

**Issue by EIVX** [Kr328/ClashForAndroid#26]
现版本中，在添加Profile后页面会跳转至上一页`New Profile`，即`选择proflie添加方式页`。
这一跳转毫无意义，用户通常在使用中会再次点击`返回`跳转至列表页。
所以建议对此改变为在添加Profile后页面直接跳转至`Profiles`页，即`profile配置列表页`。减少一步无意义的交互流程。

**Comment by Kr328** [comment]
1.0.16-alpha
