### ISSUE TITLE
节点名称无法完整显示，建议参考surfboard的节点名称显示方式

### ISSUE THREAD

**Issue by coderloverXH** [Kr328/ClashForAndroid#260]
**描述出现的错误**
节点名称只能显示前4个字，无法完整显示。
如下图所示：
![1-2](https://user-images.githubusercontent.com/63088614/79035427-1b164300-7bf1-11ea-8181-fd1db02798f5.jpg)

**如何复现该错误**
复现步骤:
1. 导入订阅地址后，如果节点名称是长名称，就可以看到节点名称无法完整显示了
2. ...
3. ...
4. ...

**预期行为**
如果能完整显示节点名称就更好了，可以参考sufboard显示节点名称的方式：
![1-3](https://user-images.githubusercontent.com/63088614/79035447-6d576400-7bf1-11ea-8fd9-0d5561e7c551.jpg)

**屏幕截图**
节点名称只能显示前4个字，无法完整显示。
如下图所示：
![1-2](https://user-images.githubusercontent.com/63088614/79035457-7e07da00-7bf1-11ea-80b5-20c3b5858f04.jpg)

**日志**
如果适用, 上传日志以帮助侦测错误

**设备信息 (请完成一下信息):**
 - 机型: 荣耀20
 - 系统/ROM: Magic
 - Android 版本 Android 10
 - ROM版本 20.3.19

**应用信息**
 - 版本: 1.1.10
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源:  Google Play

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
