### ISSUE TITLE
[Feature Request] 节点名称无法完整显示，建议参考surfboard的节点名称显示方式

### ISSUE THREAD

**Issue by coderloverXH** [Kr328/ClashForAndroid#261]
**功能描述**
节点名称只能显示前几个字，无法完整显示，影响用户选择节点，采用了前缀合并依然无法完整显示节点名称。建议参考surfboard的节点名称显示方式。
节点名称无法完整显示，如下图所示：
![1-2](https://user-images.githubusercontent.com/63088614/79035606-d68ba700-7bf2-11ea-8cd3-ad03e92b1609.jpg)
采用了前缀合并依然无法完整显示节点名称：
![1-4](https://user-images.githubusercontent.com/63088614/79035910-66caeb80-7bf5-11ea-9f26-02bbb48788b9.jpg)

**描述你希望的实现方式**
建议参考surfboard的节点名称显示方式，这样可以显示完整的节点名称，如下图所示：
![1-3](https://user-images.githubusercontent.com/63088614/79035619-f1f6b200-7bf2-11ea-83c0-669aa5bad66b.jpg)

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
#246
