### ISSUE TITLE
[BUG] [1.2.0] 'Disallow selected apps' mode does not work

### ISSUE THREAD

**Issue by littlef0x** [Kr328/ClashForAndroid#262]
**Describe the bug**
When using 'Disallow selected apps' mode, unselected apps cannot access the internet. There's neither traffic nor logs. Selected apps can access the internet. 'Only aalow selected apps' and 'Allow all apps' modes work as expected. Only exists on CFA 1.2.0.

**To Reproduce**
1. Settings-Network-Disallow selected apps
2. Unselect apps that you want run with proxy, e.g. Firefox browser, select others
3. Trun on proxy
4. Cannot visit **any** websit in Firefox browser

**Expected behavior**
Unselected apps can use proxy to access the internet. Selected ones use direct connection.

**Screenshots**
No.

**Logs**
No log produces.

**Device Info (please complete the following information):**

 - Device: Oneplus
 - ROM: H2OS
 - ROM Version: 10.0.3
 - Android Version: 10

**Application Info (please complete the following information):**

 - Version: 1.2.0
 - Apk File Name: app-release-arm64-v8a.apk
 - Distribution Channel: github

**Additional context**
No.

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by littlef0x** [comment]
Resolved in 1.2.1.
