### ISSUE TITLE
中文[Feature Request] 

### ISSUE THREAD

**Issue by wx552** [Kr328/ClashForAndroid#264]
**功能描述**
请清晰的描述你想要的功能

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
