### ISSUE TITLE
[BUG] 华为mate20, 使用v1.2.2版本, 手机黑屏重启

### ISSUE THREAD

**Issue by nexply** [Kr328/ClashForAndroid#266]
**描述出现的错误**
华为mate20, 使用v1.2.2版本, 手机黑屏重启, 详情见附件系统日志

**如何复现该错误**
复现步骤:
1. 打开clash
2. 添加配置文件
3. 设置只允许已选择应用
4. 开启代理
5. 打开youtube应用, 可正常访问外网
6. 打开google浏览器, 访问google网站, 手机黑屏自动重启

**预期行为**
不应该在切换应用后手机重启

**屏幕截图**
无

**日志**
[clash.log](https://github.com/Kr328/ClashForAndroid/files/4478837/clash.log)

**设备信息 (请完成一下信息):**
 - 机型: [华为mate20 HMA-AL00]
 - 系统/ROM: [MIUI 10]
 - Android 版本 [10]
 - ROM版本 [4.14.116]

**应用信息**
 - 版本: [1.2.2]
 - 安装包文件名: [app-release-arm64-v8a.apk]
 - 应用来源: [Github]

**附加信息**
无

**Comment by Faramitas** [comment]
同样，mate20pro，也是黑屏重启

**Comment by Kr328** [comment]
这是由 **系统内核崩溃** 引起 应用程序无法解决 只能 由 ROM 厂商修复

或者谁有解决方案 欢迎 PR

**Comment by coderloverXH** [comment]
华为荣耀20使用v1.2.2版本, 同样存在手机黑屏重启的问题

**Comment by ygsk10** [comment]
lineageos 17.1 blueline（不是华为） 也会出现黑屏重启，我也不知道怎么复现

**Comment by Faramitas** [comment]
1.2.3目前使用来看正常，我先试试水

**Comment by FanhuaCloud** [comment]
mate20 1.2.3暂时没有复现

**Comment by ciel3344** [comment]
> mate20 1.2.3暂时没有复现

系统10吗

**Comment by FanhuaCloud** [comment]
> > mate20 1.2.3暂时没有复现
> 
> 系统10吗

是,emui10.1

**Comment by ciel3344** [comment]
> > > mate20 1.2.3暂时没有复现
> > 
> > 
> > 系统10吗
> 
> 是,emui10.1
mate 20 pro
我刚刚更新了1.2.3，暂时也没出现黑屏重启现象

**Comment by nexply** [comment]
更新了1.2.3 , 黑屏重启问题暂时没有再出现了
