### ISSUE TITLE
[BUG] provider获取的trojan协议节点不通

### ISSUE THREAD

**Issue by wqaaammm** [Kr328/ClashForAndroid#269]
如题

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by wqaaammm** [comment]
版本1.12.4
1，使用provider获取list成功，但均不通，如图。
2，配置中的订阅链接原来复制后可以编辑，现在复制出来的订阅不能编辑，只能点击更新。
![Screenshot_20200415-201926_Clash for Android](https://user-images.githubusercontent.com/62083357/79336634-ac214d00-7f56-11ea-9642-9166cc8d4f3a.jpg)
![Screenshot_20200415-201849_Clash for Android](https://user-images.githubusercontent.com/62083357/79336650-b2172e00-7f56-11ea-8d9e-38f7c87a60b3.jpg)

**Comment by Kr328** [comment]
1. 不通请去上游反馈
2. 复制不可编辑 是 BUG
