### ISSUE TITLE
[BUG] 报告两处错误

### ISSUE THREAD

**Issue by wqaaammm** [Kr328/ClashForAndroid#270]
**描述出现的错误**
1，provider获取trojan节点订阅成功但不通
2，配置中复制的订阅不能编辑

**如何复现该错误**
问题1复现步骤:
1. 导入包含provider的yaml配置文件，提示成功
2. ss节点正常链接，trojan协议不通；

问题2复现步骤
1. 在配置中复制通过订阅链接的配置
2. 产生新的配置成功，但不能编辑

**预期行为**
问题1：预期能通能上网
问题2：复制的配置可以编辑

**屏幕截图**
![Screenshot_20200415-201926_Clash for Android](https://user-images.githubusercontent.com/62083357/79337111-89436880-7f57-11ea-86e2-24437ac111b7.jpg)
![Screenshot_20200415-201849_Clash for Android](https://user-images.githubusercontent.com/62083357/79337118-8b0d2c00-7f57-11ea-8ca4-226184b700e6.jpg)

**日志**
无

**设备信息 (请完成一下信息):**
 - 机型:三星 s20u
 - 系统/ROM: oneui
 - Android 版本 Android10
 - ROM版本 2.1

**应用信息**
 - 版本: 1.12.4
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: github

**附加信息**
无

**Comment by Kr328** [comment]
1. 不通请去上游反馈
2. 复制不可编辑 是 BUG

**Comment by wqaaammm** [comment]
是去找d大吗。

**Comment by wqaaammm** [comment]
> 1. 不通请去上游反馈
> 2. 复制不可编辑 是 BUG

是去找d大吗

**Comment by Kr328** [comment]
顺便 你说的不通 完全没法复现

![Screenshot_20200415-211557](https://user-images.githubusercontent.com/39107975/79341705-c9f2b000-7f5e-11ea-9e51-5ef9fe504f9b.png)

**Comment by wqaaammm** [comment]
> 顺便 你说的不通 完全没法复现
> 
> ![Screenshot_20200415-211557](https://user-images.githubusercontent.com/39107975/79341705-c9f2b000-7f5e-11ea-9e51-5ef9fe504f9b.png)

我找到原因了，不是clash问题，是我用的api，api不支持trojan转换
