### ISSUE TITLE
[Feature Request] 是否可以把Dns拉出来做个选项

### ISSUE THREAD

**Issue by YanpengGu** [Kr328/ClashForAndroid#272]
**功能描述**
现在的版本内置了4个dns服务器，是否可以弄成可自定义的

**描述你希望的实现方式**
加个配置框

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
自行修改配置文件

**Comment by Lasovoc** [comment]
> **功能描述**
> 现在的版本内置了4个dns服务器，是否可以弄成可自定义的
> 
> **描述你希望的实现方式**
> 加个配置框
> 
> **附加信息**
> 其他的与改功能相关的附加信息

请问具体 dns ip 地址
