### ISSUE TITLE
Google Play版本问题

### ISSUE THREAD

**Issue by deep-cv-nlp** [Kr328/ClashForAndroid#273]
Hi，
我注意到app的版本已经更新到1.2.4。并且在Play网页上显示的更新日期也是4月15日。
但是打开Play商店，里面显示的版本则是1.1.10。请问这是什么原因呢？
![IMG_20200416_094827](https://user-images.githubusercontent.com/52643326/79405727-c9423400-7fc7-11ea-87a0-039f4cad6222.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
