### ISSUE TITLE
[BUG] Google Play版本问题

### ISSUE THREAD

**Issue by deep-cv-nlp** [Kr328/ClashForAndroid#274]
**描述出现的错误**
我注意到app的版本已经更新到1.2.4。并且在Play网页上显示的更新日期也是4月15日。
但是打开Play商店，里面显示的版本则是1.1.10。请问这是什么原因呢？

**如何复现该错误**
复现步骤:
1. 打开Google Play商店即可复现

**预期行为**
应该可以下载到最新版本

**屏幕截图**
![IMG_20200416_094827](https://user-images.githubusercontent.com/52643326/79405841-07d7ee80-7fc8-11ea-935a-4ffadcf60905.jpg)

**日志**
n/a

**设备信息 (请完成一下信息):**
 - 机型: [例如: MI10 Pro]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [1.1.10]
 - 安装包文件名: [n/a]
 - 应用来源: [Google Play]

**附加信息**
n/a

**Comment by Kr328** [comment]
@deep-cv-nlp 为什么不问问万能的 Google 呢

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by deep-cv-nlp** [comment]
我当然是问过了万能的Google，还在issue里面搜索了，没有搜索到有关的信息，才来这里开issue啊。
还有啊，这个如此specific的问题，我特别想向您请教一下query应该是什么。

**Comment by Kr328** [comment]
因为版本不稳定 仅为 20% 的用户推送新版本

**Comment by deep-cv-nlp** [comment]
知道了。谢谢。
