### ISSUE TITLE
大佬支持下传输协议

### ISSUE THREAD

**Issue by zwtocn** [Kr328/ClashForAndroid#276]
协议: auth_aes128_md5、协议参数 导入提示不支持的ssr，求支持

**Comment by thank243** [comment]
不支持，这一辈子都不可能的。

**Comment by neteroster** [comment]
帮助完成[这个 Pull Request](https://github.com/Dreamacro/clash/pull/519)即可。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by xVzx** [comment]
> 协议: auth_aes128_md5、协议参数 导入提示不支持的ssr，求支持

转弯去找clashr，别在这提了
