### ISSUE TITLE
使用过程会连接不上 

### ISSUE THREAD

**Issue by hunterncern** [Kr328/ClashForAndroid#278]
**描述出现的错误**
请简手机型号OPPO A5 使用过程会断开链接打开APP一看已经启动 但是外网连不了 需要停止在点启动才行

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**日志**
如果适用, 上传日志以帮助侦测错误

**设备信息 (请完成一下信息):**
 - 机型: OPPO A5
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: Oreo]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
