### ISSUE TITLE
[BUG] 重启代理后无法锁定选定的节点

### ISSUE THREAD

**Issue by AzunyanDaisuki** [Kr328/ClashForAndroid#279]
**描述出现的错误**
请简洁的描述你遇到的错误
关闭代理后再打开，会跳到列表中第一个节点，并非在所有组中都有该问题，我使用的配置文件中只有两个 select 组会稳定出现该问题
**如何复现该错误**
复现步骤:
1. 选择一个节点
2. 关闭代理
3. 打开代理
4. 选中的节点变成了列表中第一个

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
重启代理选择的节点不变

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![ezgif com-video-to-apng](https://user-images.githubusercontent.com/18110400/79472144-0f35e100-8036-11ea-9fb7-ebde00ca4d3d.png)

**日志**
如果适用, 上传日志以帮助侦测错误

**设备信息 (请完成一下信息):**
 - 机型: Pixel 3
 - 系统/ROM: Android
 - Android 版本 10
 - ROM版本 QQ2A.200405.005

**应用信息**
 - 版本: 1.2.5
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GitHub Release

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
可以的话 试试清除数据

**Comment by ryuuinc** [comment]
同样的问题，清除数据后恢复正常了。

**Comment by AzunyanDaisuki** [comment]
> 可以的话 试试清除数据



> 同样的问题，清除数据后恢复正常了。

清除数据后恢复正常了，非常感谢

**Comment by Kr328** [comment]
This issue has been resolved
此问题已得到解决
