### ISSUE TITLE
Proxy Only模式开机自启无效

### ISSUE THREAD

**Issue by Umshiro** [Kr328/ClashForAndroid#28]
设备 OnePlus 7 Pro
系统 OxygenOS 10.0.2 / Android 10
版本 1.0.16 Alpha

Proxy Only 模式，自启开关和自启服务的通知均已打开，开机后只有AdGuard可以自启。
补充：VPN模式可以自启。

![result-2019-12-11-03-31-03](https://user-images.githubusercontent.com/5331402/70562253-0ab07600-1bc7-11ea-8a7f-19749c4cebb5.png)

**Comment by Galileo-Bill** [comment]
设备 Oneplus 7 Pro
系统 Oxygen OS 10.0.3.GM21AA Android 10
软件版本 1.0.24-alpha

VPN Mode 在版本更新后可以正常使用

想请教一下,有关Proxy only mode下和Adguard的配置问题.

目前操作如下:
         1.软件调整到 Proxy only mode
         2.adguard在应用管理中关闭相应软件过滤
         3.过滤方式设置为本地VPN
         4.添加代理 配置: sock5 127.0.0.1 1080
         5.重新打开软件, 无法进行正常网络连接

在基础款 ss 4.8.7 中可以和Adguard进行共存,并有正常网络连接.

想定位一下问题, 是adguard配置问题,还是软件端口默认已修改?
能具体说一下您的操作流程嘛,谢谢.

**Comment by Umshiro** [comment]
> 2.adguard在应用管理中关闭相应软件过滤

这里确保你关闭了 Clash For Android 的过滤

> 4.添加代理 配置: sock5 127.0.0.1 1080

这里的端口应为你 Clash 配置文件中的 socks-port

另外，需要在 DNS Filtering 里 Add custom DNS server，端口对应你 Clash 配置文件中的 listen，例
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
```

更新原 issue 
> 系统 OxygenOS 10.0.2 / Android 10
> 版本 1.0.16 Alpha

系统 OxygenOS 10.0.3 / Android 10
版本 1.0.24 Alpha

Proxy Only 模式还是无法自启

**Comment by Kr328** [comment]
FIXED in 1.1.0
