### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Zyears** [Kr328/ClashForAndroid#280]
**功能描述**
建议增加一个v2，ss，ssr转换的功能，现在已经找不到转换的api了，acl4ssr的转换api之前用来转换过虽然显示链接，但是其他应用(需要出墙的应用)没网，新版直接下载不了了

**描述你希望的实现方式**
git有源码项目

**附加信息**

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
