### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by uavana** [Kr328/ClashForAndroid#281]
**功能描述**
Clash 支持独立的DNS配置， 希望 ClashForAndroid支持使用该配置

**描述你希望的实现方式**
Clash 支持独立的DNS配置， 希望 ClashForAndroid支持使用该配置， eg

dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 192.168.1.1
    - 114.114.114.114
  fallback:
    - tcp://8.8.8.8
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

**附加信息**
无

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
难道现在不支持吗?

网络 - VpnService - DNS 配置覆盖 关掉 不就是取决于 配置文件

**Comment by uavana** [comment]
> 难道现在不支持吗?
> 
> 网络 - VpnService - DNS 配置覆盖 关掉 不就是取决于 配置文件

这个新版本新加的选项试了下，用我自己的DNS配置，fake-ip / redir-host模式 DNS都完全不工作了
应该怎么配置呢， 难道端口不是53？

**Comment by Kr328** [comment]
1.Android 上 一般 App 不能使用小于 1024 的端口 这是特权调用
2. Clash for Android 的 VPN 不会使用 Clash 内置的 DNS 服务 而是 使用 DNS 劫持 最终结果仍以配置文件为准
