### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Zyears** [Kr328/ClashForAndroid#282]
**功能描述**
请清晰的描述你想要的功能
添加一个将v2，ss，ssr订阅转换成clash订阅的功能

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
https://github.com/CareyWang/sub-web这个是能实习转换功能的项目源码

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
