### ISSUE TITLE
[Feature Request] 请求配置文件支持RULE-SET

### ISSUE THREAD

**Issue by palese** [Kr328/ClashForAndroid#284]
**功能描述**
请求配置文件支持RULE-SET

**描述你希望的实现方式**
像surge那样子本地代理配置和一些自定义规则再加上直接引用网络上的规则

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
请去上游 Clash 核心翻阅 Issue 和 Pull Request
