### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by JWangX** [Kr328/ClashForAndroid#285]
**功能描述**
Provider更新接口

**描述你希望的实现方式**
希望能有一个能够更新proxy provider的界面，这样就不用每次删掉配置重新更新，并且希望能够保证每个provider能够单独更新。

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
