### ISSUE TITLE
[Feature Request] 有小米电视无法安装apk v1.2.6

### ISSUE THREAD

**Issue by crg520530** [Kr328/ClashForAndroid#286]
**功能描述**
小米电视，小米盒子，无法安装最新版v1.2.6 apk

**描述你希望的实现方式**
小米电视可以实装此apk

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
错误报告 请

**Comment by xuhaoyang** [comment]
@crg520530 提供型号 日志
