### ISSUE TITLE
[BUG] 小米电视5c无法安装v1.2.6 apk

### ISSUE THREAD

**Issue by crg520530** [Kr328/ClashForAndroid#287]
**描述出现的错误**
小米电视显示安装失败，解析软件包时出现问题

**如何复现该错误**
复现步骤:
1. 使用chrome开启网页连线至GitHub
2. 下载v1.2.6版本
3.  安装universal.apk
4. 小米电视显示安装失败，解析屌件包出现问题

**预期行为**
小米电视应该要可以安装此apk

**屏幕截图**

![C68C4645-959E-4563-9635-7BE975D81F60](https://user-images.githubusercontent.com/63923581/79645118-efdab780-81df-11ea-8ea3-077314f46974.jpeg)

**日志**
如果适用, 上传日志以帮助侦测错误

**设备信息 (请完成一下信息):**
 - 机型: 小米电视4c
 - 系统/ROM: MIUI TV 1.3.114
 - Android 版本 NA
 - ROM版本 1.3.114

**应用信息**
 - 版本: 1.2.6
 - 安装包文件名: app-universal6release.apk
 - 应用来源: GitHub

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
请务必检查 Android 版本

本应用仅能在 Android 7.0 及其以上工作

**Comment by crg520530** [comment]
小米电视5c系统为MIUI TV 1.3.114，非Android系统

**Comment by Kr328** [comment]
非 Android 系统就不在支持队列了
