### ISSUE TITLE
1.0.16 节点滚动问题

### ISSUE THREAD

**Issue by TOUKaTOUKa** [Kr328/ClashForAndroid#29]
1.节点滚动其实不是为了滚动而滚动，而是通过滚动可以看到长节点后面的补充信息。

2.在未选中节点时，只需要显示头部信息，这样是为了可以快速找到需要的节点。选中节点后，循环滚动以显示补充信息。

3.目前的问题是全屏一起滚动，且滚动停顿极短，当你在50和节点里面寻找需要的节点时，也许有5个显示的是头部信息，有25个显示的是中间信息，有25显示的是尾部信息，造成识别率大大下降。

当然，可以切换单列模式或许也可以解决这个问题。

**Comment by Kr328** [comment]
#8
