### ISSUE TITLE
[Feature Request] 代理配置的导入应该和 clash 自身配置分开

### ISSUE THREAD

**Issue by douglarek** [Kr328/ClashForAndroid#295]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
希望增加二维码添加 v2ray 的配置，现在麻烦的一点是需要每次编辑整个文件或者 url 才能导入配置
**Describe alternatives you've considered**

**Additional context**

**Comment by Kr328** [comment]
1. 配置的 外部引用 代理 代理组 规则 是 **强关联**

规则 依赖 代理 和 代理组

其中任意部分不匹配 都会导致启动失败

要实现 代理 与 规则代理组 分离 你可以去了解 Clash 的 provider
