### ISSUE TITLE
[Feature Request] 支持Trojan的sni

### ISSUE THREAD

**Issue by Stone-Gate** [Kr328/ClashForAndroid#301]
一个Trojan的配置文件，在cfw上能使用，但在cfa上却不能，对比后发现，当配置文件中有sni参数时，在cfa上不能使用。希望作者能完善一下，谢谢啦。
![批注 2020-04-21 220654](https://user-images.githubusercontent.com/38148840/79875631-7e3b7d00-841c-11ea-855b-cacdbe14fac2.jpg)

**Comment by Kr328** [comment]
去上游反馈
