### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by AzunyanDaisuki** [Kr328/ClashForAndroid#302]
**功能描述**
请清晰的描述你想要的功能
希望考虑将 Proxy 策略分组改为横向滑动在各分组间切换的形式。纵向滑动整个 Proxy 列表的形式与顶部横排的分组名称不太协调，并且当列表较长时，纵向滑动容易滑到后面其它列表中去
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
纵向滑动不会超过一个策略组，通过横向滑动或点击顶部策略组名称在策略组之间切换
**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
