### ISSUE TITLE
[BUG] 1.1.10以后工作空间同时双开ClashForAndroid错误，无法同时双开

### ISSUE THREAD

**Issue by yehoshualee** [Kr328/ClashForAndroid#303]
1.1.10以后工作空间同时双开ClashForAndroid错误，无法同时双开。
昨晚play商店更新1.2.6后出现，主系统开ClashForAndroid时候工作空间也开启ClashForAndroid的话，无法同时使用，主系统会自动掉线，工作空间的ClashForAndroid也会有异常（节点选择排序等问题）。
回退到1.2.5版本依然有这个问题，回退到1.1.10版本问题解决。

**Comment by Kr328** [comment]
把表填完 提供日志 谢谢
