### ISSUE TITLE
[BUG] 1.1.10以后工作空间同时双开ClashForAndroid错误，无法同时双开

### ISSUE THREAD

**Issue by yehoshualee** [Kr328/ClashForAndroid#304]
**描述出现的错误**
1.1.10以后工作空间同时双开ClashForAndroid错误，无法同时双开。
昨晚play商店更新1.2.6后出现，主系统开ClashForAndroid时候工作空间也开启ClashForAndroid的话，无法同时使用，主系统会自动掉线，工作空间的ClashForAndroid也会有异常（节点选择排序等问题）。
回退到1.2.5版本依然有这个问题，回退到1.1.10版本问题解决。

**如何复现该错误**
复现步骤:
1. 主系统开启ClashForAndroid运行
2. ClashForAndroid切换到后台，开启工作空间内ClashForAndroid，启动运行

**预期行为**
主系统和工作空间内的ClashForAndroid均正常运行使用。

**屏幕截图**
只有ClashForAndroid停止的截图。
![Screenshot_20200422-073642109~2](https://user-images.githubusercontent.com/37654896/79925872-0eee7900-846e-11ea-8d19-bd099bcad895.jpg)

**日志**
无日志，工作空间内的ClashForAndroid一旦从已停止选择为运行中，两个ClashForAndroid均出现问题，工作空间ClashForAndroid直接闪退，主系统ClashForAndroid也弹出屡次停止。再次进入两个ClashForAndroid，捕获的日志内容为空。

**设备信息 (请完成以下信息):**
 - 机型: OnePlus 6T
 - 系统/ROM: PixelExperience 10
 - Android 版本 10
 - ROM版本 20200409

**应用信息**
 - 版本: 1.2.6
 - 安装包文件名:com.github.kr328.clash
 - 应用来源: Google Play

**附加信息**
1.2.5 1.2.7均有此问题

**Comment by yehoshualee** [comment]
测试后，1.2.0 1.2.5 1.2.6 1.2.7均有此问题且直接闪退无法抓取app内日志。
1.1.10运行正常无此问题。
下面附件是崩溃的logcat：
[logcat.txt](https://github.com/Kr328/ClashForAndroid/files/4513102/logcat.txt)

**Comment by Kr328** [comment]
试试这个版本

拆开 zip 里面是 apk
[app-arm64-v8a-release.zip](https://github.com/Kr328/ClashForAndroid/files/4513610/app-arm64-v8a-release.zip)

**Comment by yehoshualee** [comment]
> 试试这个版本
> 
> 拆开 zip 里面是 apk
> [app-arm64-v8a-release.zip](https://github.com/Kr328/ClashForAndroid/files/4513610/app-arm64-v8a-release.zip)
> 

这个版本没有问题。
效率高，给大佬点个赞！
