### ISSUE TITLE
希望能用于安卓电视

### ISSUE THREAD

**Issue by ephen** [Kr328/ClashForAndroid#305]
电视上尝试安装时，提示“解析软件包出现问题”，是否可以解决呢？

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by EKyero** [comment]
你的系统版本太低吧
