### ISSUE TITLE
还是会乱跳节点和请增加下拉通知栏节点名称

### ISSUE THREAD

**Issue by jinyiquan** [Kr328/ClashForAndroid#308]
1.重启手机后没多久，已经选择好的节点有时会乱跳到其它节点(希望能增加手动选择是否自由跳动)
2.下拉通知栏目前只有配置名称，例如xxx希望能增加xxx(节点名称)这样的详细名称

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
