### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by breakings** [Kr328/ClashForAndroid#309]
**功能描述**
请清晰的描述你想要的功能
能否提高谷歌商店更新频率?
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
目前的商店版我依然还是1.1.10，快两个月没收到过更新了，毕竟谷歌商店分发还是方便。所以请求作者及时在商店发布，谢谢！
**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
你可以让 Google 快点审核吗

不要一个版本审核 7 天 行吗
