### ISSUE TITLE
[BUG] 访问控制模式BUG

### ISSUE THREAD

**Issue by saeson001** [Kr328/ClashForAndroid#310]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. ...把访问控制模式-仅允许已选择的应用
2. ...访问控制应用包列表-并没有选择QQ
3. ...打开QQ，文字消息没问题，图片显示 不出来，全部都是加载中
4. ...

**预期行为**
正常情况下不应该会影响QQ的使用，

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![image](https://user-images.githubusercontent.com/53417010/80055984-ac70a800-8555-11ea-9d67-c5e31a4de18e.png)

**日志**
如果适用, 上传日志以帮助侦测错误

**设备信息 (请完成以下信息):**
 - 机型: Mi9 Pro 5G
 - 系统/ROM: MIUI 11
 - Android 版本 10
 - ROM版本 

**应用信息**
 - 版本: QQ 8.2.9
 - 安装包文件名: 
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
上传日志 请

**Comment by saeson001** [comment]
> 上传日志 请

https://ws28.cn/f/2ctp8rsd5m0

**Comment by Kr328** [comment]
观察日志 明显没有经过 Clash 的流量

还需要进一步调查

**Comment by comzyh** [comment]
我在MI 10 Pro 上没有复现。可能需要再查查

**Comment by saeson001** [comment]
> 我在MI 10 Pro 上没有复现。可能需要再查查

经测试很可能是我这边的WIFI问题，不好意思，这个反馈结了吧
