### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Apocalypse-QWQ** [Kr328/ClashForAndroid#311]
**描述出现的错误**
按照常规使用后上方VPN图标不出现而且也无法使用。

**如何复现该错误**
复现步骤:
1.导入链接
2.连接即无法使用

**预期行为**
正常可以科学上网

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**日志**
如果适用, 上传日志以帮助侦测错误

**设备信息 (请完成以下信息):**
 - 机型:MI  MAX
 - 系统/ROM:  MIUI 10.2稳定版
 - Android 版本：7.0
 - ROM版本：不清楚

**应用信息**
 - 版本:1.2.10
 - 安装包文件名:app-universal-release.apk
 - 应用来源:作者提供的GitHub下载地址

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@Apocalypse-QWQ 上传日志 请
