### ISSUE TITLE
vpn运行钥匙🔑状态图标的隐藏

### ISSUE THREAD

**Issue by samac08** [Kr328/ClashForAndroid#313]
用1.2.8发现可以自动隐藏状态栏的🔑 ,更新到最新1.2.10发现不能隐藏了，可否保留隐藏的功能 不需要显示出来。
安卓平台10 N10＋

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
