### ISSUE TITLE
[BUG] 疑问？为何编辑本地配置文件时，文件地址链接显示在这个github上？

### ISSUE THREAD

**Issue by troray** [Kr328/ClashForAndroid#314]
如下图1，标题下的url是怎么回事？
该配置文件是我在本地电脑编辑的，文件也是保存在本地的。文件编辑完成后，在本地电脑测试使用没问题后，通过tg（大号）发送给手机（tg小号），手机下载到内部存储后，通过“创建配置—文件”导入到clash APP中。这期间并没有其他上传到网络的动作。
![](https://api.superbed.cn/item/5ea21c69c2a9a83be5c9b1e5.jpg)

![](http://direct.superbed.cn/item/5ea21981c2a9a83be5c65d0b.jpg)
**
APP版本
![](https://api.superbed.cn/item/5ea219c8c2a9a83be5c6ac85.jpg)
![](https://api.superbed.cn/item/5ea219c8c2a9a83be5c6ac81.jpg)

**Comment by Kr328** [comment]
任何修改版本存在的问题 请不要在这里反馈
