### ISSUE TITLE
[Feature Request] proxy group被其他proxy group引用时，建议在列表显示该proxy group当前选择的proxy

### ISSUE THREAD

**Issue by acrosssssss** [Kr328/ClashForAndroid#318]
**功能描述*
proxy group被其他proxy group引用时，建议在列表显示该proxy group当前选择的proxy，类似cfw

**描述你希望的实现方式**
类似cfw

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.1
