### ISSUE TITLE
添加订阅链接无效

### ISSUE THREAD

**Issue by ooohawk** [Kr328/ClashForAndroid#32]
如题，添加订阅链接时显示invalid config:expected an object, but got a scalar value
但是使用同样的链接可以在clashx 和clash for windows上正常使用，不知道此软件的更新链接的机制所以不太清楚要对订阅链接作出怎样的改变，希望作者可以指点迷津。
![photo_2019-12-11_15-06-43](https://user-images.githubusercontent.com/43295730/70599341-e042d500-1c27-11ea-8fe6-18749fd5f3fd.jpg)

**Comment by Kr328** [comment]
不知道 自行检查配置文件
