### ISSUE TITLE
[Feature Request] 希望增加服务器负载均衡

### ISSUE THREAD

**Issue by AnotiaWang** [Kr328/ClashForAndroid#321]
**功能描述**
SSR 和 QuantumultX 拥有的特性，能提高连接稳定性，我的机场只支持v2ray，希望也能支持
_“负载均衡是高可用网络基础架构的关键组件，通常用于将工作负载分布到多个服务器来提高网站、应用、数据库或其他服务的性能和可靠性。”_

**描述你希望的实现方式**
将流量请求分摊到多个服务器上，一定程度提高网络连接速度和稳定性（本人非专业人士，请见谅）
_“使用代理服务器将请求均匀转发给多台服务器，从而达到负载均衡的目的。 web 负载均衡的作用就是把请求均匀的分配给各个节点，它是一种动态均衡，通过一些工具（Nginx好好学习下）实时地分析数据包，掌握网络中的数据流量状况，把请求合理分配出去。”_

**附加信息**
ClashA太棒啦，加油

**Comment by Kr328** [comment]
请仔细阅读上游的 README
