### ISSUE TITLE
[BUG] MEIZU手机无法访问google.com等网站,此问题在所有版本复现

### ISSUE THREAD

**Issue by nonegood** [Kr328/ClashForAndroid#323]
**描述出现的错误**
当我从1.1.x版本升级到1.2.x版本，出现了无法访问google.com和youtube.com的问题，并且之后降级到1.1.x后仍然无法访问，而其他被墙网站则访问正常

**如何复现该错误**
在1.1.x和1.2.x所有版本复现

**预期行为**
正常访问google.com
正常访问youtube.com

**设备信息 (请完成以下信息):**
 - 机型: [MEIZU 16sPro]
 - 系统/ROM: [Flyme]
 - Android 版本 [9]
 - ROM版本 [8.20.4.14 beta]

**应用信息**
 - 版本: [all]
 - 安装包文件名: [all]
 - 应用来源: [Github || Google Play Store]

**附加信息**
当我重置手机后初次使用ClashForAndroid可正常访问google.com,之后问题复现

**Comment by Kr328** [comment]
@nonegood 上传日志 后 用其他代理工具连一次网 清

**Comment by nonegood** [comment]
> @nonegood 上传日志 后 用其他代理工具连一次网 清

使用v2rayNG可正常访问，日志稍等

**Comment by nonegood** [comment]
> @nonegood 上传日志 后 用其他代理工具连一次网 请

![2020-04-26_14-36-15](https://user-images.githubusercontent.com/64347104/80300011-a08e1b80-87cb-11ea-9574-33089316c513.jpg)

**Comment by Kr328** [comment]
1. 设置里 打开 DNS 劫持 和 覆盖 DNS 配置 了吗
2. 用了其他 DNS 工具吗 (包括 私人 DNS 和 Magisk 类工具

**Comment by nonegood** [comment]
> 1. 设置里 打开 DNS 劫持 和 覆盖 DNS 配置 了吗
> 2. 用了其他 DNS 工具吗 (包括 私人 DNS 和 Magisk 类工具

1.打开了
2.没有使用

**Comment by Kr328** [comment]
由日志看 DNS 流量没有经过 Clash 导致被污染

极大概率是因为 第三方 DNS 工具 或者 ROM 自行处理 DNS 流量 而 不让其经过 VpnService

你需要自行查找相关文档 我没有搭载 Flyme 的手机

**Comment by nonegood** [comment]
> 由日志看 DNS 流量没有经过 Clash 导致被污染
> 
> 极大概率是因为 第三方 DNS 工具 或者 ROM 自行处理 DNS 流量 而 不让其经过 VpnService
> 
> 你需要自行查找相关文档 我没有搭载 Flyme 的手机

好的。但我有个疑问，若是第三方DNS工具或者ROM自行处理DNS，那么为什么v2rayNG等其他代理软件却能正常访问，只有ClashForAndroid存在此问题，并且开启全局代理也仍然存在

**Comment by Kr328** [comment]
@nonegood v2ray-core 存在 tls/http 嗅探 以从流量中 提取 域名 而 Clash 需要依赖 DNS 劫持建立映射

**Comment by nonegood** [comment]
> @nonegood v2ray-core 存在 tls/http 嗅探 以从流量中 提取 域名 而 Clash 需要依赖 DNS 劫持建立映射

原来如此。我再试试其他方式，若能解决再提交到此Issue

**Comment by nonegood** [comment]
找到原因了，确实是Flyme系统的缘故。今日更新系统后问题消失

存在此问题的Flyme系统版本:
8.20.4.14 beta
