### ISSUE TITLE
[BUG] FCM调试界面中出现不明ID的网络

### ISSUE THREAD

**Issue by sjdhome** [Kr328/ClashForAndroid#324]
**描述出现的错误**
请简洁的描述你遇到的错误
首先说明一下，FCM连接到的服务器都是Fake IP，所以Clash应该是开启了Fake IP模式的。
在Fake IP模式下，有时（详细触发时间不确定）在FCM调试界面出现不明ID的网络，原本应该是连接到的WiFi名称，而我除了截图中的三个有名称的WiFi之外并没有连接过其他WiFi，已保存WiFi里也没有其他WiFi。
**如何复现该错误**
复现步骤:
1. 在Clash位于Fake IP模式下让Google Play系列套件经过Clash。
2. 等待一段时间（我也不确定是多久）。
3. *#*#426#*#*中出现不明网络。

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
正常情况（如SS、SSR）应该只有连接过的WiFi名称，而没有这种方括号数字ID的网络。
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![IMG_20200426_213535](https://user-images.githubusercontent.com/11871061/80309352-18c60280-8807-11ea-9623-07cae171e40f.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米Max 3
 - 系统/ROM: MIUI 11
 - Android 版本: Android 10
 - ROM版本: 11.0.2

**应用信息**
 - 版本: 1.2.11
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GitHub

**附加信息**
其他的可能与改错误相关的信息

**Comment by sjdhome** [comment]
截图中那个没有ID的网络也是属于这种情况，并不是打码。

**Comment by Kr328** [comment]
最佳答案: 我不知道

我不认为我用一个普通 App 能够影响系统的网络框架

这应该问 ROM 而不是代理 App

**Comment by sjdhome** [comment]
可关闭Fake IP模式后就正常了啊

**Comment by Kr328** [comment]
@sjdhome 那也应该问为什么 ROM 会认为 fake ip 模式不正常

fake ip 模式 真的 仅仅是会返回 fake ip 而且 相对与 非 fake ip 在 Android API 上的调用 没有任何区别
