### ISSUE TITLE
[BUG] 开启clash后nmap结果发生变化

### ISSUE THREAD

**Issue by huyizheng** [Kr328/ClashForAndroid#327]
**描述出现的错误**
开启clash后nmap结果发生变化
具体表现为：在不开启clash之前，nmap baidu.com只扫到80和443端口开放；开启clash后，nmap baidu.com扫出一堆开放端口。
clash配置里只包含一行“mode: Direct”

**如何复现该错误**
复现步骤:
1. 创建一个clash配置，只包含一行“mode: Direct”
2. 手机安装termux，在termux里面安装nmap
3. 关闭clash，执行nmap baidu.com
4. 开启clash，执行nmap baidu.com

**预期行为**
既然clash的配置只有一行“mode: Direct”，即clash把所有流量都直连出去，那么是否开启clash不应该影响任何应用的行为才对吧。

**屏幕截图**
![Screenshot_20200427-115746](https://user-images.githubusercontent.com/22879638/80332789-6af63a80-887e-11ea-9a53-934f3a2235f1.jpg)
![Screenshot_20200427-115919](https://user-images.githubusercontent.com/22879638/80332846-a0028d00-887e-11ea-909a-3e31e92a48ac.jpg)
如图，前一张是开启clash后（状态栏有钥匙）`nmap baidu.com`的结果，后一张是关闭clash后（状态栏没钥匙）`nmap baidu.com`的结果。

**设备信息 (请完成以下信息):**
 - 机型: [MIX 2S]
 - 系统/ROM: [Evolution X]
 - Android 版本 [10]
 - ROM版本 [200205]

**应用信息**
 - 版本: [1.1.10]
 - 安装包文件名: [app-arm64-v8a-release.apk]
 - 应用来源: [Github Releases]

**附加信息**
其他的可能与改错误相关的信息
![Screenshot_20200427-120342](https://user-images.githubusercontent.com/22879638/80333003-2e770e80-887f-11ea-8dcf-4ff489589365.jpg)
在开启clash时，执行`nmap baidu.com`，日志里面出现大量的类似这样的信息。

**Comment by Kr328** [comment]
预期行为
