### ISSUE TITLE
[Feature Request] 希望日志捕获中能调整clash的log-level

### ISSUE THREAD

**Issue by yangon99** [Kr328/ClashForAndroid#329]
**功能描述**
在cfa的“Clash日志捕获工具”中，希望能够增加切换clash的log-level的功能

**描述你希望的实现方式**
在日志捕获界面添加切换log-level的菜单按钮（也许可以顺便把停止记录日志按钮换成fab，菜单里面再塞一些其他奇奇怪怪的东西

**附加信息**
无

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.1
