### ISSUE TITLE
VPN mode下Facebook 加载异常迟缓

### ISSUE THREAD

**Issue by Olivercoco** [Kr328/ClashForAndroid#33]
设备: Galaxy S9 | Android 9
版本:1.0.18-alpha

VPN mode FB加载迟缓 甚至出错，proxy only+adguard 正常。
DNS的部分 有尝试默认，自定义（fake ip/redir host) ，VPNmode  FB加载异常的问题均未见明显改善。IPV6已关。 下图中 VPN图标已隐藏。
![photo_2019-12-12_09-31-28](https://user-images.githubusercontent.com/39828052/70674906-60b61400-1cc2-11ea-8545-4d2f7d9e43d9.jpg)
![photo_2019-12-12_09-31-32](https://user-images.githubusercontent.com/39828052/70674909-63b10480-1cc2-11ea-8f0d-0d0f72e8d06b.jpg)

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复

**Comment by Olivercoco** [comment]
应用版本 2.3.22
手机系统设置 接入点设置 APN协议 仅选择IPV4
用sprict 禁用QUIC
问题已解决。Instagaram有类似问题也可尝试该方案。
