### ISSUE TITLE
[BUG] DOT或DOH导致域名匹配失效

### ISSUE THREAD

**Issue by songee2020** [Kr328/ClashForAndroid#333]
**描述出现的错误**
配置文件中使用DNS over http或DNS over tls后，域名可正常解析但无法针对域名规则进行匹配而只能IP匹配。

**如何复现该错误**
复现步骤:
1. 配置文件的head如下：
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: debug
external-controller: '0.0.0.0:9090'
experimental:
  ignore-resolve-fail: true
secret: ''
dns:
  enable: true
  ipv6: false
  enhaced-mode: fake-ip
  listen: '0.0.0.0:5453'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 1.2.4.8
  fallback:
    - 'tls://dns.google:853'
    - 'https://1.0.0.1/dns-query'
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
2. app网络设置，关闭dns配置覆盖，关闭追加系统dns。
3. 启动日志，启动clash，浏览器打开https://www.google.com，无法访问。
4. 同样配置在clash for Windows可正常访问，将
    - 'tls://dns.google:853'
    - 'https://1.0.0.1/dns-query'
替换为
    - 8.8.8.8
    - 1.0.0.1
在clash for Android下也可正常访问。

**预期行为**
同样配置在clash for Windows下正常，说明此问题不是由clash的core导致。

**屏幕截图**
![SmartSelect_20200429-174431_Clash for Android](https://user-images.githubusercontent.com/61627765/80583561-f15b7980-8a42-11ea-9f84-73ef87a7a117.jpg)
 
![SmartSelect_20200429-175852_Clash for Android](https://user-images.githubusercontent.com/61627765/80583770-3b445f80-8a43-11ea-8199-16a20b79eb8a.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Samsung S9 
 - 系统/ROM: 
 - Android 版本 10
 - ROM版本 G9600ZCU6DTD1

**应用信息**
 - 版本: [ 1.2.12 ]
 - 安装包文件名: []
 - 应用来源: [Google Play]

**附加信息**
网络设置，打开dns配置覆盖，可以正常实现规则内的代理连接，但规则外的dns污染无法解决。

**Comment by Kr328** [comment]
@songee2020 你的 enhanced-mode 打错了 注意单词

**Comment by songee2020** [comment]
> @songee2020 你的 enhanced-mode 打错了 注意单词

经过测试，确实是因为这个低级错误导致的
