### ISSUE TITLE
[BUG] 某个proxy-provider为空后 导入配置失败

### ISSUE THREAD

**Issue by xuhaoyang** [Kr328/ClashForAndroid#334]
**描述出现的错误**
proxy-provider其中某个url配置，无法访问，或者访问结果为空，会出现导入该配置失败

**如何复现该错误**
复现步骤:
1. 编写一个proxy-provider子项必定无法访问或为空的
2. 通过url导入

**预期行为**
应该成功导入。上游说有做fallback

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 所有机型
 - 系统/ROM: 所有系统
 - Android 版本 所有支持的版本
 - ROM版本 无

**应用信息**
 - 版本: 1.2.12含之前

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
预期行为
