### ISSUE TITLE
[BUG]  auto update subscription doesn't work all the time

### ISSUE THREAD

**Issue by messi06** [Kr328/ClashForAndroid#336]
i have set the profile to auo update the subscription every 15 minutes , kept the app running for 8 hrs.
it didn't update after  every 15 minutes.
it updated automatically only after closing the app and opening it again..

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
