### ISSUE TITLE
希望可以增加 自动更新订阅选项

### ISSUE THREAD

**Issue by Borber** [Kr328/ClashForAndroid#34]
由于某种原因 订阅的 yaml 文件每小时整点会更新一次(密码更改) 每次都要手动更新订阅不太方便希望可以所以希望增加自动更新订阅功能

**Comment by Kr328** [comment]
1.1.0 已实现

**Comment by Borber** [comment]
好的 感谢

Kr328 <notifications@github.com> 于 2020年2月22日周六 上午12:08写道：
