### ISSUE TITLE
1.2.12通知栏快捷开关问题

### ISSUE THREAD

**Issue by RudeTheJack** [Kr328/ClashForAndroid#340]
1.2.12更新之后，通知栏快捷开关打开关闭反应变得非常缓慢，小米9，安卓10，MIUI11

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
