### ISSUE TITLE
[BUG] 1.2.12通知栏快捷开关反应迟钝

### ISSUE THREAD

**Issue by RudeTheJack** [Kr328/ClashForAndroid#341]
**描述出现的错误**
更新1.2.12之后，通知栏快捷开关{打开和关闭}都变得非常迟钝

**预期行为**
能像1.2.12之前的版本那样点按之后开关的图标立马就亮起来（或者关闭）

**设备信息 (请完成以下信息):**
 - 机型: 小米9透明尊享版
 - 系统/ROM: MIUI11
 - Android 版本 ：10
 - ROM版本 ：最新稳定版11.0.9.0

**应用信息**
 - 版本: 1.2.12
 - 安装包文件名: 
 - 应用来源:Google Play更新

**Comment by Kr328** [comment]
1. 1.2.12 前后该实现无任何变更
2. 据其他用户报告 此问题一般由于 **系统限制应用启动** 引起 而非应用本身
