### ISSUE TITLE
[BUG] MIUI 12 无法启动代理

### ISSUE THREAD

**Issue by cccClyde** [Kr328/ClashForAndroid#342]
**描述出现的错误**

在 MIUI 12 中，点击「点此启动」后出现的「网络连接请求」弹窗无法选中「确定」。

**如何复现该错误**

复现步骤:

1. 完成节点配置并回到主界面
2. 点击「点此启动」
3. 在弹出的窗口中选择「确定」

**预期行为**

确定可以点击并成功启动 VPN 服务

**屏幕截图**

![Screenshot_2020-05-02-17-22-05-892_com android vpndialogs](https://user-images.githubusercontent.com/34314096/80860378-ddf61b80-8c99-11ea-90d3-f0203f4eb77f.jpg)

**设备信息 (请完成以下信息):**

 - 机型：小米 9
 - 系统/ROM：MIUI 12
 - Android 版本：10
 - ROM版本：20.4.30 内测版

**应用信息**

 - 版本：1.2.12
 - 安装包文件名：app-release-arm64-v8a.apk
 - 应用来源：Play 商店

**附加信息**

无

**Comment by NobeKanai** [comment]
红米k20pro miui12， 出现了同样的问题

**Comment by Kr328** [comment]
这个确认选项框 **完全由系统控制** 应用无法干涉

一般情况下 不能选中仅可能出现在 **有悬浮窗** 的时候

**Comment by NobeKanai** [comment]
遇到了同样的问题，重启解决了

**Comment by gitsang** [comment]
有其他进程限制了VPN的建立,,,,清理后台可以解决,应该是只有第一次会这样

**Comment by fengbo123** [comment]
重启解决

**Comment by githik999** [comment]
> 长按应用信息，在权限管理里面为该应用允许后台弹窗

很有帮助 谢谢 解决了 这小米miui各种小问题太多了 而且还多广告 太恶心了以后再也不买了

**Comment by wujinkui** [comment]
您好，我已经收到您的邮件。
