### ISSUE TITLE
[Feature Request] 使用Android beam通过NFC传输配置

### ISSUE THREAD

**Issue by Mosney** [Kr328/ClashForAndroid#343]
**功能描述**
两台具有NFC硬件的手机可以通过背靠背快速分享配置文件，从而提升某些必须依赖额外的信道传输配置文件/URL情况下的用户体验

**描述你希望的实现方式**
Android beam应该可以实现使用NFC传输文本数据

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
不可能 单个配置文件大小可达 10M+
