### ISSUE TITLE
[BUG] 创建新配置时出现empty profile提示

### ISSUE THREAD

**Issue by Mickyzh** [Kr328/ClashForAndroid#344]
**描述出现的错误**
请简洁的描述你遇到的错误

在订阅SSR节点时，首先用了subconverter将SSR节点配置文件转换为clash配置，添加配置时提示下载失败，详情中显示“empty profile”，同样的配置文件在windows版本的clash上可订阅成功

**如何复现该错误**
![profile](https://user-images.githubusercontent.com/62255751/80907430-ba8aa980-8d49-11ea-9d67-f6fd655ea234.jpg)
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 小米8
 - 系统/ROM: MIUI11
 - Android 版本 10
 - ROM版本 11.0.7.0

**应用信息**
 - 版本: [例如: 1.1.10] 1.2.13
 - 安装包文件名: [例如: app-release-arm64-v8a.apk] app-release-arm64-v8a.apk
 - 应用来源: [例如: Google Play] github

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
没有 SSR 支持
