### ISSUE TITLE
[BUG] 最新1.2.13点击启动无法点击确定连接，取消按钮可以。

### ISSUE THREAD

**Issue by imshell8** [Kr328/ClashForAndroid#346]
**描述出现的错误**
小米8系统MIUI12，最新1.2.13点击启动弹出的VPN连接提示无法点击"确定"连接，点击"取消"按钮可以成功返回。

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: xiaomi8
 - 系统/ROM: MIUI12
 - Android 版本 10
 - ROM版本 20.4.30

**应用信息**
 - 版本:  1.2.13
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源:  Google Play、github

**附加信息**
猜测为UI问题

**Comment by Kr328** [comment]
#342
