### ISSUE TITLE
[Feature Request] 不知道能否出一个类似于在fake-ip模式下让特定域名获取真实IP的功能....

### ISSUE THREAD

**Issue by pikachullk** [Kr328/ClashForAndroid#347]
**功能描述**
针对特定的域名(例如网易云)
可以在fake-ip模式下获取真实IP~
我将网易云解锁服务放在了自己的动态域名下,目前如果用fake-ip的话~会无法获取到动态域名的真实IP~导致无法解锁...可关了fake-ip用redir-host的话加载视频又很慢~不知道能否增加一个对特定域名获取真实IP的选项......

**描述你希望的实现方式**
参考openclash中DNS的高级设置可以添加指定的域名用特定的dns进行解析~返回真实IP

**附加信息**
感谢大佬辛苦开发~

**Comment by Kr328** [comment]
请仔细阅读上游 README.md 自行修改配置文件
