### ISSUE TITLE
[BUG] 1.2.13版本，系统应用Google driver 无法走代理

### ISSUE THREAD

**Issue by Loukky** [Kr328/ClashForAndroid#348]
**描述出现的错误**
请简洁的描述你遇到的错误
Google driver app 提示无法连接网络，查看相关日志，发现改app请求网络的时候，clash无日志，初步判断是该app没有走规则。同时其他自带app如chrome，YouTube能正常使用。已确认并未绕过该app走直连。
**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
如之前版本一样能正常处理该app的数据代理。
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Sony xz3 
 - 系统/ROM: Android 10
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]
港版最新版
**应用信息**
 - 版本: 最新版
 - 安装包文件名: 不清楚
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
别填最新版 填具体的 应用来源填清楚

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Loukky** [comment]
@Kr328 抱歉，问题已解决，发现还是勾选了云端硬盘。我眼睛的问题…
