### ISSUE TITLE
[Feature request] 建议支持clash://install-config?url=http%3A%2F%2Fexample.com&name=example

### ISSUE THREAD

**Issue by xuhaoyang** [Kr328/ClashForAndroid#35]
目前Clash for Android 只支持了clash://install-config?url=http%3A%2F%2Fexample.com，不能再打开地址后，直接save。部分提供订阅，是按照ClashX，支持了name参数。希望能提供支持

**Comment by wordlesswind** [comment]
![Screenshot_20200505-222441](https://user-images.githubusercontent.com/9050713/81077569-b44e2600-8f1f-11ea-8834-f56da004712c.jpg)
刚刚才开始用 CFA ，所以新版本是重构了么？
并不支持 `clash://`。

**Comment by Kr328** [comment]
This issue has been resolved
此问题已得到解决
