### ISSUE TITLE
下载的配置文件修改

### ISSUE THREAD

**Issue by 2287405159** [Kr328/ClashForAndroid#350]
**描述你希望的实现方式**
在安卓文件中查看通过URL下载的文件路径
方便下载的配置文件的规则能够编辑

**附加信息**
通过本地文件添加的文件的文件头应该满足何种规则

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
