### ISSUE TITLE
[Feature Request] 使得程序模式可以覆盖配置模式

### ISSUE THREAD

**Issue by byzod** [Kr328/ClashForAndroid#351]
**功能描述**
购买的机场的trojan订阅仅提供了最基础的规则，无法满足实际使用需求
目前当启动cfa，或者通过通知栏按钮启动cfa时，总是使用订阅的配置文件提供的模式（proxy），但是我需要的是global模式，而这个模式并不会保存。当关闭cfa，再次启动或者通过通知栏按钮启动时，又需要手动进入cfa应用设置里重新更改为global模式，非常麻烦

**描述你希望的实现方式**
建议配置文件只提供rules的设置，应用使用模式（global，proxy，direct）则保存在应用程序级别，覆盖配置文件的默认设置

**附加信息**
如图
![A_1](https://user-images.githubusercontent.com/848607/81035720-c94e9900-8ece-11ea-850a-def74d013bf1.gif)

**Comment by Kr328** [comment]
#137
