### ISSUE TITLE
[BUG] 新版本更新后，选择规则模式则无法上网，改为全局则正常上网。

### ISSUE THREAD

**Issue by wwfussy** [Kr328/ClashForAndroid#353]
**描述出现的错误**
新版本更新后，选择规则模式则无法上网，改为全局则正常上网。

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
规则模式可以翻墙

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型:红米K20
 - 系统/ROM: MIUI 11
 - Android 版本  10
 - ROM版本 

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源:  Google Play

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
那就应该 **检查你的规则** 和 **日志** 而不是 **直接反馈**
