### ISSUE TITLE
[BUG] 无法连接使用AlphaSSL签发证书的Vmess TCP+TLS节点

### ISSUE THREAD

**Issue by chenyang12315** [Kr328/ClashForAndroid#355]
**描述出现的错误**
当Vmess TCP+TLS节点使用Alpha SSL签发的泛域名证书时，CfA无法正确连接。
v2服务端日志：
`[Date] [Time] IP:Port rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > remote error: tls: bad certificate`
Clash for Android客户端日志捕捉工具：
`WARN
dial [Group Name] error: x509: vertificate signed by unknown authority`
手机Chrome访问网站：ERR_CONNECTION_RESET
同配置文件下，CfA使用Let's Encrypt签发的单域名节点没有问题。
同配置文件，Clash for Windows 0.9.X版本连接没有问题。
同节点同配置，Quantumult X没有出现问题。

**预期行为**
应正常握手连接。

**屏幕截图**
稍后上传。

**设备信息 (请完成以下信息):**
 - 机型: Oneplus 6 (A6000)
 - 系统/ROM: H2OS 10.0.3
 - Android 版本: 10

**应用信息**
 - 版本: 1.12.13
 - 安装包文件名: Unknown
 - 应用来源: Google Play

**附加信息**
AlphaSSL 证书信息：https://github.com/MoeClub/AlphaSSL

**Comment by Kr328** [comment]
所有信任证书 **均来源于系统** 应该联系你的系统提供商追加此根证书

**Comment by chenyang12315** [comment]
感谢快速回复/

> 所有信任证书 **均来源于系统** 应该联系你的系统提供商追加信任此根证书

请问使用Chrome访问使用同样证书的网站可以正常访问，证书显示安全，是否意味着根证书已经被信任？

**Comment by Kr328** [comment]
@chenyang12315 你的根证书如果是手动安装 那么第三方应用除非手写代码信任 (Chrome 是 如此) 否则默认不被信任

**Comment by chenyang12315** [comment]
> @chenyang12315 你的根证书如果是手动安装 那么第三方应用除非手写代码信任 (Chrome 是 如此) 否则默认不被信任

该根证书并非手动信任/添加，使用该证书的网站直接被Chrome信任，证书信任链：
域名 --- AlphaSSL CA - SHA256 - G2 --- GlobalSign nv-sa

**Comment by Kr328** [comment]
那么这个问题就只可能是上游 Clash 甚至是 Golang 的问题 Clash for Android 无法解决

**Comment by chenyang12315** [comment]
> 那么这个问题就只可能是上游 Clash 甚至是 Golang 的问题 Clash for Android 无法解决

感谢解答。经详细查证并非Clash问题（因为直接使用Clash Core或Clash for Windows未出现同样问题）。
**实际问题为证书链不全**（缺少中间证书），自行补全证书链即可。Chrome可以正常访问是因为其自动下载并补全中间证书。
参：https://blog.myssl.com/faq-miss-ca-certificate/

**Comment by Joker2387089590** [comment]
> > 那么这个问题就只可能是上游 Clash 甚至是 Golang 的问题 Clash for Android 无法解决
> 
> 感谢解答。经详细查证并非Clash问题（因为直接使用Clash Core或Clash for Windows未出现同样问题）。 **实际问题为证书链不全**（缺少中间证书），自行补全证书链即可。Chrome可以正常访问是因为其能够自动下载并补全中间证书。 参：https://blog.myssl.com/faq-miss-ca-certificate/

我对证书这方面了解不深，最近配置 TLS 时也遇到了 `x509: vertificate signed by unknown authority` 的问题。
我是使用的自签名证书，已经在系统里添加了 CA 证书，在 Chrome 可以安全访问。
参考网站里，证书链补全似乎是适用于双证书的场景的，我也不知道应该如何应用。

**Comment by xuhaoyang** [comment]
@Joker2387089590 Android证书得添加到systrm吧

**Comment by Joker2387089590** [comment]
> @Joker2387089590 Android证书得添加到system吧

是在 system 里添加的，新版的安卓还会在任务栏提醒你“安装了 CA 证书，网络可能受监控”

**Comment by xuhaoyang** [comment]
@Joker2387089590 不用root 没法添加
