### ISSUE TITLE
[BUG] 快速操作后，网络设置界面始终不可用

### ISSUE THREAD

**Issue by TinyLord** [Kr328/ClashForAndroid#359]
**错误描述**
当快速进行 停止代理->设置->网络->切换控制模式->启动代理 两到三次之后，网络设置界面始终保持在灰色状态，即使停止代理也无法进行设置。只能卸载重装

**预期行为**
在停止代理后，网络设置页面应该能正常操作

**屏幕截图**
[图片1](https://imgchr.com/i/YGJMHU)
[图片2](https://imgchr.com/i/YGJKBT)

**设备信息**
 - 机型: 华为Mate9 MHA-AL00
 - 系统/ROM: EMUI 9.1.0
 - Android 版本 9

**应用信息**
 - 版本: 1.2.13
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: TG频道

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/81520472-f7245980-9376-11ea-8229-7563f3280029.png)
![image](https://user-images.githubusercontent.com/39107975/81520478-fbe90d80-9376-11ea-9c35-968164fad089.png)

**Comment by TinyLord** [comment]
那就是APP自动操作的，我从来没有设置过这个选项

**Comment by Kr328** [comment]
在用户不操作的情况下 第一个选项绝对不会自动关闭 除非你的系统发疯了 自动点击

**Comment by TinyLord** [comment]
我总不可能三次复现都是自己误操作吧?

**Comment by Kr328** [comment]
@TinyLord 那总不可能只有你一个有这个现象吧

**Comment by TinyLord** [comment]
行吧，当我没说

**Comment by Kr328** [comment]
@TinyLord 你要知道 这个选项关闭时 VPN 服务完全不可用 也就意味着 应用几乎完全失效 到现在为止 只有你提起这个问题 基本上可以断定你是个例 且 很大可能与 ROM 有关

**Comment by Kr328** [comment]
@TinyLord 你可以尝试 在 ROM 禁用 App 的 全部后台限制 
你们 EMUI 曾经有过 禁用应用内部交互的历史 也就意味着 可能应用向服务端查询设置的时候被系统拦截
