### ISSUE TITLE
[BUG] 开启热点后速度暴跌

### ISSUE THREAD

**Issue by abcdrl** [Kr328/ClashForAndroid#360]
三星note10＋ andriod10系统，开启热点共享后，连接的设备网速很慢

复现步骤:
1. 开启手机热点共享
2. ipad连接该热点
3. ipad speedtest测速只能跑到10mbps
4. 关闭手机端clash，重新ipad测速，200＋
5.重新开启clash连接
6.再次测速，10＋
7.关闭clash，100＋

三星note10+ android 10
iPad pro 13.4.1

**应用信息**
 - 版本: 1.2.13
 - 安装包文件名: 大包
 - 应用来源: github

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
应用 **完全无法干涉** WIFI 热点 的行为 

这个问题极大可能是 系统造成

**Comment by comzyh** [comment]
我 Mi 10 Pro 连 Wifi 开热点，和 iPad 2018 测了下，没发现这个问题，速度是一致的。
