### ISSUE TITLE
google APP均无法登陆

### ISSUE THREAD

**Issue by yyanxiao** [Kr328/ClashForAndroid#361]
更新后google APP均无法使用，提示“从服务器检索信息时出错”，网页能够正常登陆使用。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by yyanxiao** [comment]
已解决，谢谢！
