### ISSUE TITLE
[BUG] 软件本身无法联网，疑似https问题

### ISSUE THREAD

**Issue by Creedowl** [Kr328/ClashForAndroid#365]
**描述出现的错误**
软件本身无法联网，无法进行url订阅、测速，但可以正常连接代理。订阅时会出现以下错误

```text
Get "https://xxxx": x509: failed to load system roots and no roots provided; lstat /system/etc/security/cacerts/557de9dd.0: permission denied
```

**如何复现该错误**
复现步骤:
1. 添加订阅时出现
2. 测速没有结果

**预期行为**
正常添加订阅、测速

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Mi 8
 - 系统/ROM:  MIUI 12
 - Android 版本 10
 - ROM版本 存在好几个版本了

**应用信息**
 - 版本: 1.2.13
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
貌似更新miui12后出现的问题，重装应用无法解决

**Comment by Kr328** [comment]
这难道不应该反馈给你的系统提供商吗

应用连读取系统 TLS 证书的权限都没有

**Comment by Creedowl** [comment]
@Kr328 因为其它应用都正常，所以怀疑是app的问题，我再向miui方面反馈吧

**Comment by Kr328** [comment]
@Creedowl 这个问题 Clash for Android 也解决不了 要么是系统问题 要么是 Golang 的 TLS 实现问题

**Comment by soulmatenoe** [comment]
删除 Magisk 的 “解锁网易云灰色音乐” （UnblockNetease） 模块

**Comment by Creedowl** [comment]
竟然是这个的问题，这个模块有什么替代品吗

soulmatenoe <notifications@github.com> 于2020年6月2日周二 下午11:18写道：
