### ISSUE TITLE
[Feature Request] 默认代理模式

### ISSUE THREAD

**Issue by NanamiArihara** [Kr328/ClashForAndroid#369]
**功能描述**
每次启动 Clash 之后，代理模式默认规则模式，选中全局要多点几次比较麻烦
在 Android 手机上对某些应用进行全局代理的需求很常见

**描述你希望的实现方式**
在程序中增加一个设置，可以选择默认代理模式为规则/全局/直连

**附加信息**
实际上配置文件里面有mode: Rule
然而配置文件一般都是从 URL 上面获取下来的，本地不好更改

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/137
