### ISSUE TITLE
建议增加根据SSID选择代理方式的功能

### ISSUE THREAD

**Issue by cnperi** [Kr328/ClashForAndroid#37]
有些人家里的wlan是自动翻墙的。手机进到这个wlan里面可以关闭代理软件或是代理策略变成全部Direct。
目前，shadowsocks-android是通过提供tasker插件的方式，实现不同WLAN环境里面选用不同配置的代理、或是直接关闭shadowsocks-android。
iOS下的Quantumult，是通过「策略」里面的「SSID行为」来实现特定Wlan里面代理策略变成Direct的方式，让代理软件「功能失效」。
上述两种方式都是自动的，很方便。
建议 C4A 也增加类似功能，实现自动切换。

**Comment by Kr328** [comment]
自 Android 8.0 起 应用不再能获取 SSID

**Comment by cnperi** [comment]
那像shadowsocks那样，提供tasker的plugin呢？

**Comment by fgprodigal** [comment]
同样希望提供tasker的插件，以实现tasker自动化开关

**Comment by ccinls** [comment]
也希望同时支持Automate

**Comment by SwarmTags** [comment]
同求相关功能，在shadowrocket和Quantemalt里面叫做按需连接，谢谢大佬啦，已经请喝咖啡支持啦

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/319

**Comment by rickycm** [comment]
SSID suspend或者talker插件有一个也好……家里的网络是翻墙的，每次要手动切换真的很麻烦
