### ISSUE TITLE
[BUG] Clash for Windows/配置界面空白

### ISSUE THREAD

**Issue by qwer12345687** [Kr328/ClashForAndroid#370]
**描述出现的错误**
请简洁的描述你遇到的错误
配置界面全空白，无任何可供点击的地方，重装各个版本很多次没有用。
**如何复现该错误**
复现步骤:
1. 好像是当时不小心把配置界面的东西删除完了
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![MMAEXN{@3}JF}C_0U$NO{CN](https://user-images.githubusercontent.com/65883301/82778294-98390700-9e83-11ea-8057-2a32a10dc9d4.png)

**设备信息 (请完成以下信息):**
win10专业版

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/82778597-6aa08d80-9e84-11ea-9599-91216beb66e3.png)
![image](https://user-images.githubusercontent.com/39107975/82778601-6ffdd800-9e84-11ea-92ac-a41aededb56d.png)
![image](https://user-images.githubusercontent.com/39107975/82778608-73915f00-9e84-11ea-85fa-7e9afbd055f3.png)
