### ISSUE TITLE
CFA网速限制，差距有点大

### ISSUE THREAD

**Issue by palese** [Kr328/ClashForAndroid#379]
![Screenshot_20200527_002126_org zwanoo android speedtest](https://user-images.githubusercontent.com/13195594/82925673-9e78d180-9fb0-11ea-97b2-a0a018933c26.jpg)
zheshi这是没开CFA的速度

![Screenshot_20200527_002034_org zwanoo android speedtest](https://user-images.githubusercontent.com/13195594/82925732-b5b7bf00-9fb0-11ea-9da0-059920a3a3cc.jpg)
这是打开CFA后的速度

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
