### ISSUE TITLE
[BUG] CFA网速限制，差距有点大

### ISSUE THREAD

**Issue by palese** [Kr328/ClashForAndroid#380]
**描述出现的错误**
CFA下载速度限制

**如何复现该错误**
复现步骤:
1. 打开CFA
2. 关闭CFA
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![Screenshot_20200527_002126_org zwanoo android speedtest](https://user-images.githubusercontent.com/13195594/82926127-5312f300-9fb1-11ea-8690-840981fe7951.jpg)
这是关闭CFA后的速度

![Screenshot_20200527_002034_org zwanoo android speedtest](https://user-images.githubusercontent.com/13195594/82926199-6a51e080-9fb1-11ea-8d8d-0f0c6f756b89.jpg)
这是打开CFA后的速度

**设备信息 (请完成以下信息):**
 - 机型: 华为mate 20 pro
 - 系统/ROM: EMUI10
 - Android 版本 10
 - ROM版本 10.1.135

**应用信息**
 - 版本: 1.2.15
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: Google Play

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
无法复现 等一个有缘人来找原因

**Comment by kkkk2020** [comment]
这个跟你的节点选择有关系吧，不清楚CFA能否自定义规则，当你打开CFA后，有可能使用了代理去对这个基站进行测速，理论上代理后，对速度肯定是有变化的

**Comment by palese** [comment]
测速是直连

**Comment by palese** [comment]
最新的实验性版本1.3.2网速限制没有了，能跑男满带宽
