### ISSUE TITLE
Clash VPN isn't compatible with xiaomi redmi4prime

### ISSUE THREAD

**Issue by seso1129** [Kr328/ClashForAndroid#381]
Hey, there is an error in Google play store upon that the clash VPN isn't compatible with my device, that is Xiaomi redmi 4 prime.
Why is that?
![Screenshot_2020-05-26-22-04-02-951_com android vending](https://user-images.githubusercontent.com/52235140/82933064-a2035d00-9f9e-11ea-9ce0-f575e8b70b5f.png)
![Screenshot_2020-05-26-22-04-44-469_com android settings](https://user-images.githubusercontent.com/52235140/82933078-a4fe4d80-9f9e-11ea-8cc8-9a179eec8ee8.png)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by cccarbondioxide** [comment]
CFA Andriod version request to be 7 and higer,
'Surfboard' is another option for you

**Comment by seso1129** [comment]
> CFA Andriod version request to be 7 and higer,
> 'Surfboard' is another option for you

It's not working with Clash servers unfortunately
