### ISSUE TITLE
In Google play store Clash is incompatible with Xiaomi redmi 4 prime

### ISSUE THREAD

**Issue by seso1129** [Kr328/ClashForAndroid#382]
Clash VPN doesn't work on Xiaomi redmi 4 prime. Someone says it's not working for Android Bellow 7, and my phone has Android 6. Is that right?
![Screenshot_2020-05-26-22-04-02-951_com android vending](https://user-images.githubusercontent.com/52235140/82953251-aab85b00-9fbf-11ea-9677-6bad96e5f08f.png)
![Screenshot_2020-05-26-22-04-44-469_com android settings](https://user-images.githubusercontent.com/52235140/82953256-ae4be200-9fbf-11ea-862b-58c5ac612abc.png)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by seso1129** [comment]
> Please use Issue Template to create issue
> 请务必使用 Issue Template 创建 Issue
> 
> [Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

Kosse nanat madar jende.
