### ISSUE TITLE
[BUG] UI关于节点名称显示不全的问题 选节点靠盲猜

### ISSUE THREAD

**Issue by myjensen1973** [Kr328/ClashForAndroid#384]
**描述出现的错误**
节点选择界面 节点名称 只能显示前面极少几个字 节点一旦多了 只能靠猜的和记忆 去选择 其实也根本记不住 只能点选后 返回顶部看是选择了哪个 合并前缀功能 没有用 或是说这个功能根本解决不了问题 勾选后名称更乱 如下截图 我节点的名称包括了 协议类型 中转类型 节点等级 节点区域 节点服务商 节点倍率 是否解锁nf等 都是有用信息吧 看群里有人说去转换 只留下个区域hk us 这样子的？ 这不扯犊子 说鬼话 比如我的网络环境BGP不好使 iplc好使 或是hkt不好使 az的好使 那还得盲试了 ？

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
个人观点认为最好的呈现方式 就是横向一行显示一条节点信息 纵向排列下来 而非现在的一行两个 这样就有足够的位置来显示 如开发者没空打理ui 能让选框里的文字滚动显示吗 以充分利用选框内的区域 那么大的框显示那么点 感觉都浪费了 这个实在是太影响 请老板有空能解决一下这个美中不足

**屏幕截图**
![Screenshot_2020-05-28-07-55-38-42_1ed813789000d97ac1c6fc69779c1198](https://user-images.githubusercontent.com/41321598/83084170-ce140080-a0ba-11ea-9ad0-d0df3e472dd3.jpg)

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: 1.2.15
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
#246
