### ISSUE TITLE
Clash for Android

### ISSUE THREAD

**Issue by Jeraque007** [Kr328/ClashForAndroid#385]
No more shadowsocks - no wechat connection - no email response.   Now clash still no settings.   Have paid but no service.   Please respond to jeraque007 wechat.   Thanks

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Jeraque007** [comment]
Oh you can respond to the incorrect template but you can't respond on wechat!

Thank you so much!!




-------- Original message --------
