### ISSUE TITLE
添加快捷方式开关

### ISSUE THREAD

**Issue by tporwx** [Kr328/ClashForAndroid#386]
**功能描述**
请清晰的描述你想要的功能
能否添加快捷方式开关，就像shadowsocks那样，长按图标会出现一个开关选项

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
