### ISSUE TITLE
[BUG] 添加本地配置文件时 open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by quiminq** [Kr328/ClashForAndroid#388]
**设备信息**
 - 机型: 坚果Pro3
 - 系统/ROM: [smartisan 7.3.1]
 - Android 版本 [例如: 9]

**应用信息**
 - 版本: [例如: 1.2.15]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

尝试多种方法，无法给予clash存储权限。

**Comment by Kr328** [comment]
联系你的系统提供商 将配置文件以 **Content Provider** 传递 而不是使用 **非 Android 标准的 java.io.File**

**Comment by EdisonDragonSlayer** [comment]
这个用户自己无法修改吗？Smartisan OS注定不支持这个哎，好惨

**Comment by wjx** [comment]
python -m http.server
