### ISSUE TITLE
[Feature Request] redundant notification for config auto update

### ISSUE THREAD

**Issue by SSgumS** [Kr328/ClashForAndroid#389]
I have set auto update for my url profile. every 1 hour the config will be updated. but unfortunately for each update I receive a notification. I think it would be better if user could turn off auto update notifications.

**Comment by LM-Firefly** [comment]
@SSgumS 系统 通知设置可以关

**Comment by Kr328** [comment]
@LM-Firefly Setting -> Behavior -> Show Traffic

**Comment by Kr328** [comment]
It is required for run auto update process in background

**Comment by SSgumS** [comment]
> @SSgumS 系统 通知设置可以关

I don't want to turn off clash notifications entirely.
