### ISSUE TITLE
[BUG] 无法理解 CFA 的 DNS 逻辑, 请求解答.

### ISSUE THREAD

**Issue by lotusired** [Kr328/ClashForAndroid#390]
**描述出现的错误**
软件并没有使用我提供的 DNS 服务器.

**如何复现该错误**
复现步骤:
1. 在服务器端给 YAML 文件中的 dns->nameserver 中添加一些服务器.
2. 本地 Download, 运行.
3. 在 DNS 服务器抓包, 只能在最开始抓到一些数据包, 之后就没有任何请求.

**预期行为**
这些 DNS 服务器是我自己在运行的, 有 UDP 也有 Https. 软件如果发起 DNS 请求, 我应该可以收到发送的数据包.

**设备信息 (请完成以下信息):**
 - 机型: pixel 3a
 - 系统/ROM: pixel
 - Android 版本 9
 - ROM版本 2019.5

**应用信息**
 - 版本: 1.2.15
 - 安装包文件名: not applicable
 - 应用来源: Google Play

**附加信息**
服务器并没有真实在运行 DNS 服务, 我只是想抓取这些数据包.

**Comment by Kr328** [comment]
自己阅读源码 开源免费应用没有义务解答你的问题

**Comment by xuhaoyang** [comment]
@lotusired 建议问上游
