### ISSUE TITLE
uuid 不符合规则的不该报错，那是说明型节点，不是使用节点

### ISSUE THREAD

**Issue by xixiri** [Kr328/ClashForAndroid#391]
![image](https://user-images.githubusercontent.com/19706511/83339361-a06bc900-a2ff-11ea-900c-7c9d05110b4b.png)

这种问题没必要爆出来了吧，uuid 不对而已，就终止了更新节点。这个uuid为“aaa”的节点不是使用节点，是说明节点！！！！！何必让他一颗老鼠屎坏了一锅粥，其他好的也用不了啦

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
