### ISSUE TITLE
[BUG] VPN不定时断开

### ISSUE THREAD

**Issue by leic4u** [Kr328/ClashForAndroid#392]
**描述出现的错误**
VPN会不定时断开，手动关闭再打开即正常。

**如何复现该错误**
初步进行了测试，节点数量较少时（20个）没有出现过VPN断开，节点数量较多时（节点数量接近200个）会随机断开。
经过观察，好像和URL-TEST的时间能够对上，猜测是否由于URL-TEST导致VPN断开（URL-TEST interval 设置的300，但不是每5分钟都会断开，有时还是能坚持个半小时啥的）。
（CFW在接近200节点时为正常，判断不是clash的问题，所以这个ISSUE没有提到clash去，提到CFA来了）

> `17:01:23 |ERROR| Listen TCP redirect failure%!(EXTRA string=listen tcp4 0.0.0.0:0: socket: too many open files)`

日志中的这条信息似乎可以看出点倪端。

**预期行为**
不应断开

**设备信息 (请完成以下信息):**
机型：坚果Pro2S
系统/ROM：SmartisanOS
Android版本：8.1
ROM版本：7.0.0.1

**应用信息**
版本: 1.2.15
安装包文件名: app-arm64-v8a-release.apk
应用来源: Github

**日志**

> `# Logcat on 2020-05-31 16:54:31`
> `17:00:06 |INFO| [TCP] 172.31.255.253:42630 --> 91.108.56.152 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:06 |INFO| [TCP] 172.31.255.253:42626 --> 91.108.56.152 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:06 |INFO| [TCP] 172.31.255.253:45018 --> 91.108.56.152 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:06 |INFO| [TCP] 172.31.255.253:38472 --> 149.154.167.51 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:06 |INFO| [TCP] 172.31.255.253:42644 --> 91.108.56.152 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:06 |INFO| [TCP] 172.31.255.253:45030 --> 91.108.56.152 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:07 |INFO| [TCP] 172.31.255.253:38484 --> 149.154.167.51 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:07 |INFO| [TCP] 172.31.255.253:32956 --> firebaseinstallations.googleapis.com match DomainKeyword using 🔰 节点选择[🇭🇰 香港 01]`
> `17:00:09 |INFO| [TCP] 172.31.255.253:43612 --> in.appcenter.ms match Match using 🐟 漏网之鱼[🇭🇰 香港 01]`
> `17:00:10 |INFO| [TCP] 172.31.255.253:53368 --> 91.108.56.191 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:40 |INFO| [TCP] 172.31.255.253:53376 --> 91.108.56.191 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:00:40 |INFO| [TCP] 172.31.255.253:53380 --> 91.108.56.191 match IPCIDR using 📲 电报信息[🇭🇰 香港 01]`
> `17:01:23 |ERROR| Listen TCP redirect failure%!(EXTRA string=listen tcp4 0.0.0.0:0: socket: too many open files)`
> `17:01:23 |WARN| dial 🐟 漏网之鱼 error: gz.cm1.b2cloud.xyz:10001 connect error`
> `17:01:24 |INFO| [TCP] 172.31.255.253:58122 --> 103.56.60.171 match GeoIP using 🎯 全球直连[DIRECT]`
> `17:01:24 |INFO| TCP redirect exited`
> `17:01:24 |INFO| Packet redirect exited`

**Comment by Kr328** [comment]
首先 这个问题只能由 **ROM厂商解决** 应用没有任何办法

adb shell 运行命令

```bash
cat /proc/`pidof com.github.kr328.clash:background`/limits
```

贴上结果

**Comment by leic4u** [comment]
```
ocean:/ $ cat /proc/`pidof com.github.kr328.clash:background`/limits
cat: /proc//limits: No such file or directory
```

**Comment by Kr328** [comment]
@leic4u clash 跑起来了吗

**Comment by leic4u** [comment]
@Kr328 需要在CFA跑起来的时候运行上面的adb shell命令吗？我上面那个结果是没有跑CFA的，跑起来的稍等一下。

**Comment by leic4u** [comment]
```
ocean:/ $ cat /proc/`pidof com.github.kr328.clash:background`/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             21748                21748                processes
Max open files            1024                 4096                 files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       21748                21748                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         40                   40
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```
@Kr328

**Comment by xuhaoyang** [comment]
@leic4u 
flush mokee 保平安
osborn:/ # cat /proc/`pidof com.github.kr328.clash:background`/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             22052                22052                processes
Max open files            32768                32768                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       22052                22052                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         40                   40
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

**Comment by leic4u** [comment]
@xuhaoyang 你的锤子刷了魔趣吗，我比较喜欢锤子的ROM，不是很想换TAT

**Comment by xuhaoyang** [comment]
> @xuhaoyang 你的锤子刷了魔趣吗，我比较喜欢锤子的ROM，不是很想换TAT

早就刷了。锤子的系统卡死了。刷了后流畅很多

锤子是给妹子的备用机

早刷早享受
