### ISSUE TITLE
[BUG] Geoip问题

### ISSUE THREAD

**Issue by xingzhuanxing** [Kr328/ClashForAndroid#394]
**描述出现的错误**
有些国内ip规则无法Direct

**如何复现该错误**
复现步骤:
1. 183.254.116.116 国内ip却走了proxy
2. ...geoip,cn,direct 无法匹配上述ip
3. ...经测试 似乎 windows也是如此，尽管我已经在面板中更新了geoip。怀疑是引用的geoip源库问题
4. ..以上问题当然也能通过添加规则解决，但是如此会造成的麻烦就是不知道受影响的ip有多少，而且不可能逐个设置

**预期行为**
正常情况下应该是direct的

**屏幕截图**
无

**设备信息 (请完成以下信息):**
 - 机型: 与设备无关
 - 系统/ROM: 无关
 - Android 版本 无关
 - ROM版本 无关

**应用信息**
 - 版本: 最新版本也是如此
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: Google Play

**附加信息**
其他的可能与改错误相关的信息

**Comment by Kr328** [comment]
@xingzhuanxing 为什么都不肯帖点日志呢 真就让开发者学悬丝诊脉呗

**Comment by xingzhuanxing** [comment]
s

> @xingzhuanxing 为什么都不肯帖点日志呢 真就让开发者学悬丝诊脉呗

这还需要日志嘛。。。ip都贴出来了。 复制粘贴浏览器上试试？

编译你都源码一直过不了，mac/windows都试了。没好意思贴上来，估计你也没空支持

**Comment by Kr328** [comment]
我明确说吧 

无论是最新版 Clash for Android 
还是去年的 GEOIP 库

你这个 IP 都判断为 CN

**Comment by alexlee728** [comment]
https://github.com/alecthw/mmdb_china_ip_list

最好能够提供让用户填写mmdb下载地址入口。

**Comment by Kr328** [comment]
@alexlee728 那必然不可能

1. 没有办法检测正确性
2. 没有办法保证正确重新载入

**Comment by xuhaoyang** [comment]
@alexlee728 推荐使用chinaip 替换geoip

**Comment by alexlee728** [comment]
> @alexlee728 推荐使用chinaip 替换geoip



> @alexlee728 推荐使用chinaip 替换geoip

https://github.com/alecthw/mmdb_china_ip_list
这个就是包含ipip，我电脑端用的这个。

**Comment by ygsk10** [comment]
Country.mmdb 就在 assets 里，替换一下重新签APK就好了
