### ISSUE TITLE
建议安卓版跟pc版一样未连接时也打开代理列表

### ISSUE THREAD

**Issue by xixiri** [Kr328/ClashForAndroid#395]
**功能描述**
建议安卓版跟pc版一样未连接时也打开代理列表

为什么这么干呢！目前安卓版连接上才显示代理列表，这时的测速是不准确的，如果自动选择的是死节点。其他的节点测速都是测不出来的。pc版就可以测的准确，因为我没开代理的时候就去测速的

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
