### ISSUE TITLE
[BUG] 不使用 DNS 覆盖会导致域名匹配失效

### ISSUE THREAD

**Issue by lotusired** [Kr328/ClashForAndroid#396]
**描述出现的错误**
如果取消勾选 DNS 覆盖, 即使用 YAML 中的 DNS 设置, 则 rule 中的域名匹配规则会失效.

**如何复现该错误**
复现步骤:
1. 取消勾选 DNS 覆盖.
2. 在网页端打开网页.
3. 在 log 看到它只能匹配 IP-CIDR 规则, 不能匹配域名规则.

**预期行为**
如果把 DNS 覆盖勾选, 则可以在 log 中看到它匹配了域名规则.

**设备信息 (请完成以下信息):**
 - 机型: Pixel 3a
 - 系统/ROM: Pixel
 - Android 版本 9
 - ROM版本 2019.5

在多个手机上都可以复现, 并非系统设置问题.

**应用信息**
 - 版本: 1.1.15
 - 安装包文件名: arm64
 - 应用来源: release

**Comment by Kr328** [comment]
为什么不检查自己的配置文件呢

不覆盖意味着使用配置文件里的 DNS 配置文件里的 DNS 不具备反向推断域名时 当然会失效

**Comment by lotusired** [comment]
你好!

感谢你的快速回复. 我尝试把 nameserver 删到只剩 8.8.8.8, fallback 只剩 8.8.4.4, 并没有效果.
同样的配置在 win 和 macos 上可以正常使用.

**Comment by lotusired** [comment]
如果需要我可以给你发个临时配置文件帮助你复现 bug.

**Comment by Kr328** [comment]
@lotusired 与使用的 DNS 无关 建议通过搜索引擎了解 enhanced-mode

不用的 不是 BUG 是 预期的行为 你的配置文件 注定了反解析功能是无效的

**Comment by lotusired** [comment]
感谢! 问题已经解决.
是我对 clash 配置不熟悉. 开启 enhanced mode 之后就解决了问题.
祝您一切顺利.
