### ISSUE TITLE
访问京东商城出现ERR_CONNECTION_RESET错误

### ISSUE THREAD

**Issue by KisThFir** [Kr328/ClashForAndroid#40]
同配置下流量正常，而wifi下无论禁不禁用ipv6选项都出现同一错误，同配置对比过clasha也是正常的（但clasha有个问题，解析太慢了，cfa解析很快，体验比clasha好很多，希望大佬能解决下这个问题，愿意配合调试。
![4c486368294add9d](https://user-images.githubusercontent.com/19422564/70777921-f2557c80-1dbb-11ea-940d-fac08dad7cf7.jpg)

**Comment by KisThFir** [comment]
一个新的发现，在我设了私人dns后，开启cfa会导致私人dns失效，这是正常的，clasha也会，但clasha会处理dns污染问题，导致解析比cfa慢，我在想如果国内解析不抢答私人dns会不会就解决我这个问题了，因为我用bromite这个浏览器内置的DoH设置成功解决了上面京东那个问题，它不会被cfa用路由默认dns抢答掉国内域名。（以上都是小白的一点折腾过程，很多描述可能不对，但尽量表达了

**Comment by chenzhiwei** [comment]
@Kr328 部分域名被解析到 IPv6 地址了，然后导致用 IPv6 去连接，然后就出现这个问题了。另外，昨天的最新版也有同样的问题。

**Comment by KisThFir** [comment]
> @Kr328 部分域名被解析到 IPv6 地址了，然后导致用 IPv6 去连接，然后就出现这个问题了。另外，昨天的最新版也有同样的问题。

就是你说的这样，目前tg频道里的最新版1.0.21禁用ipv6的dns，已解决这问题。
