### ISSUE TITLE
[BUG] 狂野飙车9国际版无法运行提示无法连接到服务器启动（错误：2）

### ISSUE THREAD

**Issue by lpn418** [Kr328/ClashForAndroid#403]
**描述出现的错误**
狂野飙车9无法运行提示错误链接2，同样的规则，同样的订阅链接，使用的同一个节点，V2ray机场，Surfboard这个软件是可以正常运行的（规则模式和全局 模式都可以玩），clash这个就会提示（错误：2），咋都进不去游戏，请大佬帮忙分析下原因，看日志显示的都走代理节点了，但实际确实进不去游戏，clash选全局代理也同样的提示。

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: mix2
 - 系统/ROM: 
 - Android 版本：10
 - ROM版本  

**应用信息**
 - 版本: 1.2.15
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
# Logcat on 2020-06-04 08:31:34
08:31:40 |INFO| Android tun started
08:31:40 |INFO| Listen TCP redirect 42712
08:31:40 |INFO| Start initial compatible provider fallback
08:31:40 |INFO| Start initial compatible provider auto
08:31:40 |INFO| Start initial compatible provider 为游戏而生
08:31:40 |INFO| DNS: 8.8.8.8:53
08:31:40 |INFO| DNS: 8.8.4.4:53
08:31:40 |INFO| DNS: 1.2.4.8:53
08:31:40 |INFO| DNS: 223.5.5.5:53
08:31:40 |INFO| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
08:31:40 |INFO| HTTP proxy listening at: 127.0.0.1:7890
08:31:40 |INFO| SOCKS proxy listening at: 127.0.0.1:7891
08:31:40 |INFO| Set 为游戏而生 -> 新加坡
08:31:40 |INFO| Start initial compatible provider fallback
08:31:40 |INFO| Start initial compatible provider auto
08:31:40 |INFO| Start initial compatible provider 为游戏而生
08:31:40 |INFO| DNS: 58.20.127.170:53
08:31:40 |INFO| DNS: 58.20.127.238:53
08:31:40 |INFO| DNS: 223.5.5.5:53
08:31:40 |INFO| DNS: 119.29.29.29:53
08:31:40 |INFO| DNS: 1.1.1.1:53
08:31:40 |INFO| DNS: 208.67.222.222:53
08:31:40 |INFO| DNS server listening at: :0
08:31:40 |INFO| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
08:31:40 |INFO| Set 为游戏而生 -> 新加坡
08:31:41 |INFO| [TCP] 192.168.76.218:44189 --> 198.18.0.1 match Match using 为游戏而生[新加坡]
08:31:44 |INFO| [TCP] 172.31.255.253:39888 --> 91.108.56.125 match IPCIDR using 为游戏而生[新加坡]
08:31:53 |INFO| Set GLOBAL -> 圣何塞-01
08:32:01 |INFO| [TCP] 172.31.255.253:37173 --> graph.facebook.com using GLOBAL
08:32:01 |INFO| [TCP] 172.31.255.253:37175 --> graph.facebook.com using GLOBAL
08:32:01 |INFO| [TCP] 172.31.255.253:37171 --> graph.facebook.com using GLOBAL
08:32:01 |INFO| [TCP] 172.31.255.253:37183 --> graph.facebook.com using GLOBAL
08:32:01 |INFO| [TCP] 172.31.255.253:37563 --> etsv2.gameloft.com using GLOBAL
08:32:01 |INFO| [TCP] 172.31.255.253:46905 --> firebaseremoteconfig.googleapis.com using GLOBAL
08:32:01 |INFO| [TCP] 172.31.255.253:38724 --> iap.gameloft.com using GLOBAL
08:32:03 |INFO| [TCP] 172.31.255.253:49472 --> 201205igp.gameloft.com using GLOBAL
08:32:04 |INFO| [TCP] 172.31.255.253:38040 --> eve.gameloft.com using GLOBAL
08:32:06 |INFO| [TCP] 172.31.255.253:44293 --> vgold-asa.gameloft.com using GLOBAL
08:32:07 |INFO| [TCP] 172.31.255.253:40553 --> sink.gameloft.com using GLOBAL
08:32:07 |INFO| [TCP] 172.31.255.253:40555 --> sink.gameloft.com using GLOBAL
08:32:07 |INFO| [TCP] 172.31.255.253:40750 --> z.moatads.com using GLOBAL

```
此为全局代理时候的日志

**Comment by Kr328** [comment]
打开日志记录
运行游戏
上传日志

**Comment by lpn418** [comment]
已上传

**Comment by luoshaocong** [comment]
如果不用软路由v2ray不代理游戏

**Comment by lpn418** [comment]
> 如果不用软路由v2ray不代理游戏

不对吧，我用Surfboard，同样是v2ray，同一个节点就可以玩

**Comment by luoshaocong** [comment]
> > 如果不用软路由v2ray不代理游戏
> 
> 不对吧，我用Surfboard，同样是v2ray，同一个节点就可以玩

你Surfboard不用代理可以玩吗？ 游戏用的udp和tcp属于传送c游戏
> 
> 不对吧，我用Surfboard，同样是v2ray，同一个节点就可以玩

你Surfboard不用代理可以玩吗？ 游戏用的udp和tcp属于传送层， surfboard走的是应用层，传送层比应用层层级低不代理。一般游戏代理得用vpn

**Comment by lpn418** [comment]
> > > 如果不用软路由v2ray不代理游戏
> > 
> > 
> > 不对吧，我用Surfboard，同样是v2ray，同一个节点就可以玩
> 
> 你Surfboard不用代理可以玩吗？ 游戏用的udp和tcp属于传送c游戏
> 
> > 不对吧，我用Surfboard，同样是v2ray，同一个节点就可以玩
> 
> 你Surfboard不用代理可以玩吗？ 游戏用的udp和tcp属于传送层， surfboard走的是应用层，传送层比应用层层级低不代理。一般游戏代理得用vpn

Surfboard就是代理软件，和clash一样的。。。

**Comment by xuhaoyang** [comment]
....不用v2，但是你们不查一下配置么，看看Clash配置能否转发udp，看看是不是ipv6没匹配中导致direct？

**Comment by luoshaocong** [comment]
> > > > 如果不用软路由v2ray不代理游戏
> > > 
> > > 
> > > 不对吧，我用Surfboard，同样是v2ray，同一个节点就可以玩
> > 
> > 
> > 你Surfboard不用代理可以玩吗？ 游戏用的udp和tcp属于传送c游戏
> > > 不对吧，我用Surfboard，同样是v2ray，同一个节点就可以玩
> > 
> > 
> > 你Surfboard不用代理可以玩吗？ 游戏用的udp和tcp属于传送层， surfboard走的是应用层，传送层比应用层层级低不代理。一般游戏代理得用vpn
> 
> Surfboard就是代理软件，和clash一样的。。。

说错了， 我没用过surfboard，不过如果可以接管udp和tcp流量的话那就是有虚拟卡网的功能。就像我说的，理论上像v2ray这种socks5的代理是不接管udp和tcp的。

**Comment by xuhaoyang** [comment]
@luoshaocong ？？？ 不接管udp tcp ，请问靠啥通信？？？

**Comment by xuhaoyang** [comment]
请阅读 https://zh.wikipedia.org/wiki/OSI%E6%A8%A1%E5%9E%8B

![undefined](https://ws1.sinaimg.cn/large/6af1db27gy1gflt8feiwlg20v4183tf2.gif)

**Comment by Kr328** [comment]
@xuhaoyang 请阅读 https://www.ietf.org/rfc/rfc1928.txt

检查 socks5 如何处理 输入端 的 UDP/TCP

**Comment by luoshaocong** [comment]
> @luoshaocong ？？？ 不接管udp tcp ，请问靠啥通信？？？

你自己都理解不的osi模型发给我看干啥。你有问题我好心帮回答不感谢就算了还打算刁我？

**Comment by luoshaocong** [comment]
> @luoshaocong ？？？ 不接管udp tcp ，请问靠啥通信？？？

你自己都理解不的osi模型发给我看干啥。你有问题我好心帮回答不感谢就算了还真是。 你自己系统学习下网络原理吧。你自己说不接管udp tcp靠啥通信我都无语了

**Comment by luoshaocong** [comment]
> 请阅读 https://zh.wikipedia.org/wiki/OSI%E6%A8%A1%E5%9E%8B
> 
> ![undefined](https://camo.githubusercontent.com/823a7c98842203947515eef8f83519121ac30caa/68747470733a2f2f7778312e73696e61696d672e636e2f6c617267652f366166316462323767793167666c7438666569776c67323076343138337466322e676966)
@xuhaoyang  层级高的不接管层级低的。就像你开v2ray不能提高你家宽带一样

**Comment by xuhaoyang** [comment]
> > @luoshaocong ？？？ 不接管udp tcp ，请问靠啥通信？？？
> 
> 你自己都理解不的osi模型发给我看干啥。你有问题我好心帮回答不感谢就算了还真是。 你自己系统学习下网络原理吧。你自己说不接管udp tcp靠啥通信我都无语了

Android VPN实现，就是个tun网卡，无论什么形式去跟这个网卡进行数据交换。Clash for Android 是直接去tun网卡处理了。 对于software不处理这些流，那怎么和Server 进行通信？难道不就是字面意思的接管？

**Comment by lpn418** [comment]
各位大佬，不要搞那么好深啊，同一个机场订阅链接，同样的节点，Surfboard每次运行都要自动更新订阅信息有点坑，而用clash又不能玩，头大。之前在哪看过有没有可能是clash core对UDP支持有bug,之前忘了在哪个项目里看到过了。。。

**Comment by lpn418** [comment]
https://github.com/trojan-gfw/igniter/issues/224

**Comment by lpn418** [comment]
我这个问题，最新的版本能解决吗？

**Comment by Kr328** [comment]
@lpn418 你自己不试试 谁知道 我可没时间去挨个测试

**Comment by lpn418** [comment]
试过了2.0.7  仍然连不上 ，与之前的报错一样， 规则和全局代理模式都一样，   还是用不起啊

**Comment by lpn418** [comment]
2.0.14问题仍然未解决

**Comment by lpn418** [comment]
2.0.15问题仍然未解决

**Comment by Kr328** [comment]
@lpn418 如果更新日志里没有相关条目 就不需要在这里说了 你这个问题我是没法复现 现在就只是在等有缘人

**Comment by shikkoku** [comment]
我特意从Google Play下载了一个回来，我使用分应用代理可以正常进入游戏。而且看了下日志好像游戏没走UDP

**Comment by lpn418** [comment]
> 我特意从Google Play下载了一个回来，我使用分应用代理可以正常进入游戏。而且看了下日志好像游戏没走UDP
不用分应用代理，正常情况能进吗？例如全局代理。日志不准的，我用surfboard可以看到有UDP连接的。

**Comment by lpn418** [comment]
v2.0.17最新的版本终于解决了这个问题，感谢大佬，辛苦了。
另外提个建议，能够增加一个测试选项，采用ping，且显示当前丢包率。

**Comment by xuhaoyang** [comment]
@lpn418 这是core做的，去找
