### ISSUE TITLE
建议添加“一键连接”的exported

### ISSUE THREAD

**Issue by dazirangege** [Kr328/ClashForAndroid#404]
![qq_pic_merged_1591263625405](https://user-images.githubusercontent.com/66415470/83742431-fcca4200-a68b-11ea-96dc-566df54463ab.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
