### ISSUE TITLE
建议添加“一键连接”的exported

### ISSUE THREAD

**Issue by dazirangege** [Kr328/ClashForAndroid#405]
**附加信息**
![image](https://user-images.githubusercontent.com/66415470/83743761-bc6bc380-a68d-11ea-9d81-b2d463f43a5e.png)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
