### ISSUE TITLE
[Feature Request] 希望在APP中增加一个 “更新软件” 按钮，可以直接下载最新版的安装包到手机中

### ISSUE THREAD

**Issue by isArtJay** [Kr328/ClashForAndroid#406]
**功能描述**
在APP中增加一个 “更新软件” 按钮，可以直接下载最新版的安装包到手机中。

**描述你希望的实现方式**
点击 “更新软件” 按钮，检查是否是最新版，如果是，提示 “已经是最新版本~”；如果不是，则下载最新版安装包到手机中并安装。

**Comment by Kr328** [comment]
**应用内更新** 会违反 **Google Play 政策** 导致应用下架
