### ISSUE TITLE
[Feature Request] 想问一下，不支持Android 5.0 的系统吗？

### ISSUE THREAD

**Issue by tea1111980** [Kr328/ClashForAndroid#407]
**功能描述**
最低支持 安卓系统是 7.0 吗？
能不能支持一下 安卓 5.0 的系统？谢谢

**描述你希望的实现方式**
如题

**附加信息**
如题

**Comment by Kr328** [comment]
1. 不支持
2. 你可以帮我写兼容代码 写好后 然后提起 Pull Request 即可

**Comment by tea1111980** [comment]
> 1. 不支持
> 2. 你可以帮我写兼容代码 写好后 然后提起 Pull Request 即可

哈哈~~
写兼容代码难不？
不过，你后续的这个想法，我非常的想帮你实现，可是我不会编程。嘿嘿嘿~~

谢谢作者回复。
