### ISSUE TITLE
[BUG] Android Studio build项目时报错Exec go mod vendor failure

### ISSUE THREAD

**Issue by WayneLyn** [Kr328/ClashForAndroid#410]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
环境已经配置好了，但是run app的时候build提示这个错误

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
编译平台 Linux

其他问题自己解决

**Comment by Meteor2017** [comment]
@WayneLyn 老哥解决了吗，我也遇到此问题

**Comment by WayneLyn** [comment]
@Meteor2017 首先golang相关的环境需要配置，但是我还是报错，后面我试了很久发现是网络的原因。访问不到golang.org，然后我挂代理，在gradle里执行命令之前先export一下代理端口。
clash.gradle.kts这个文件这里我新增了自己的代理...
`    doFirst {
        val environment = generateGolangBuildEnvironment()
        ("export http_proxy=127.0.0.1:7890\n export https_proxy=127.0.0.1:7890\n" +
                "go get golang.org/x/mobile/cmd/gomobile").exec(env = environment)
    }`

**Comment by Meteor2017** [comment]
@WayneLyn 好的，非常感谢。我晚点尝试一下

**Comment by WayneLyn** [comment]
@Meteor2017 我直接自己在终端里添加代理是不生效的，代理AS和代理终端都没用，得在命令里添加才生效。

**Comment by Meteor2017** [comment]
@WayneLyn 非常感谢老哥这么详细的讲解，万分感谢

**Comment by zengchao928** [comment]
怎么弄的，老哥，我也是这个问题，一直解决不了

**Comment by zengchao928** [comment]
@WayneLyn 怎么弄的，老哥，我也是这个问题，一直解决不了

**Comment by WayneLyn** [comment]
@zengchao928 我上面已经给他回复得很详细了吧，你先自己挂个代理，然后在clash.gradle.kts在执行命令前按我说的添加你自己代理的端口

**Comment by zengchao928** [comment]
@WayneLyn 可是我能访问golang.org啊

**Comment by zengchao928** [comment]
@WayneLyn android studio需要配置go的什么嘛？

**Comment by WayneLyn** [comment]
@zengchao928 go环境你装了吧？你能访问golang.org是你代理生效了，但是他这脚本是直接bash命令，我自己测试是走不了代理。所以在执行命令之前强制设置一下

**Comment by zengchao928** [comment]
@WayneLyn go环境都是装好的，关键是我不懂go，所以也谷歌了半天也没找到什么问题

**Comment by WayneLyn** [comment]
@zengchao928 不需要懂啊，就是他gradle编译时候执行bash命令走不了代理而已，我上面都说的很清楚了啊...在那个命令前加上2行命令就行了

**Comment by zengchao928** [comment]
@WayneLyn 我加上你的那两行代码了，但是还是不行，报错，我简直就快崩溃了，可以加个qq或者微信请教下你吗
