### ISSUE TITLE
[Feature Request] 自定义GeoIP文件

### ISSUE THREAD

**Issue by Sentsuki** [Kr328/ClashForAndroid#411]
**功能描述**
目前clash用的MaxMind数据库对中国IP匹配不全，我想把Country.mmdb替换为如下项目：https://github.com/alecthw/mmdb_china_ip_list

**描述你希望的实现方式**
提供更改相关文件的途径

**Comment by Kr328** [comment]
GEOIP 嵌在 apk 里 且均 在运行时载入

GEOIP 数据库 因 **没有有效的校验手段** 未来也不会允许自定义/动态更新

你可以从源码构建自己的 apk 从而替换 mmdb

**Comment by fbigun** [comment]
#https://github.com/Hackl0us/GeoIP2-CN/issues/10

>

**Comment by Longway22** [comment]
> GEOIP 嵌在 apk 里 且均 在运行时载入
> 
> GEOIP 数据库 因 **没有有效的校验手段** 未来也不会允许自定义/动态更新
> 
> 你可以使用 rule-provider 引入其他来源的 IP 列表

所以有什么必要一定“检验”GeoIP吗，这个不是应该交给用户去自由选择？
