### ISSUE TITLE
[BUG] 部落冲突谷歌版断流，几个机场都是这样。

### ISSUE THREAD

**Issue by MANLIKALEX** [Kr328/ClashForAndroid#414]
大佬，麻烦请指教，是我不会设置吗？还是什么问题，打部落战断线好几次了。我很喜欢这个app。谢谢你了！

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
