### ISSUE TITLE
[BUG] Google voice等依赖于udp的voip应用不工作

### ISSUE THREAD

**Issue by baraja** [Kr328/ClashForAndroid#415]
**描述出现的错误**
Google voice wifi calling拨打美国手机号，拨打后对方没有声音，十余秒后自动挂断

**如何复现该错误**
复现步骤:
1. 设置Google voice使用wifi拨打电话
2. 拨打一个美国电话(for example citibank 's 800-374-9700)
3. GV开始尝试连通
4. 十余秒后联通失败，自动挂断

**预期行为**
如同ss-android以及v2rayng一般可以正常使用GV WIFI CALLING

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: Android 10]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: ]

**应用信息**
 - 版本: [例如: 1.2.15]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by baraja** [comment]
请参考ss android的这个issue
https://github.com/shadowsocks/shadowsocks-android/issues/2168
Clash是个好软件，不能GV是个小瑕疵，希望开发者能修复

**Comment by Kr328** [comment]
@baraja 信息填完 + 日志

**Comment by baraja** [comment]
已确认：最新的1.3.1已经修复该问题

**Comment by baraja** [comment]
我又仔细测试了一下，
V1.3.1和V1.3.2都没有完全修复这个问题，具体表现为vmess+ws+tls不能正常gv，而trojan可以正常GV
Vmess配置如下

proxies:

  - name: V2_tizi
    type: vmess
    server: mydomain.com
    port: 443
    uuid: myuuid
    alterId: 0
    cipher: none
    udp: true
    tls: true
    network: ws
    ws-path: /mypath

**Comment by Kr328** [comment]
预期行为

vmess 协议存在缺陷 **完全不能支持 stun**

**Comment by baraja** [comment]
好吧，不太清楚v2rayNG用的是怎样的魔法来实现的…（好像也是tun2socks）是可以正常gv通话的，其他几个v2ray实现比如bfrostv和kitsunebi确实也不行

**Comment by imaqine** [comment]
请问V2RAY NG你们能连voice吗，我连不上，打和接都是秒挂

**Comment by AkariiinMKII** [comment]
@imaqine vmess的UDP支持不完善，请用其他协议

**Comment by laggardkernel** [comment]
Trojan 同样问题，还没联通秒断。电脑端好像也有类似问题，打通了没有1分钟自动给我挂了。
