### ISSUE TITLE
在ClashForAndroid1.3.1版本启动代理后会产生不明上行速度[BUG] 

### ISSUE THREAD

**Issue by eivx** [Kr328/ClashForAndroid#418]
**描述出现的错误**
在ClashForAndroid1.3.1版本启动代理后会产生不明上行速度，停止代理后便恢复正常。

**如何复现该错误**
复现步骤:
1. 直接启动代理

**预期行为**
在无上传动作时上传速度为0

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![image](https://user-images.githubusercontent.com/26437323/84563009-fa05d600-ad8a-11ea-99c5-62078a0890f8.png)

**设备信息 (请完成以下信息):**
 - 机型: Xiaomi Note3
 - 系统/ROM: MIUI12
 - Android 版本 9
 - ROM版本 20.6.11

**应用信息**
 - 版本: 1.3.1
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: github

**附加信息**
可能与节点测速有关。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
