### ISSUE TITLE
[BUG] build失败

### ISSUE THREAD

**Issue by goomadao** [Kr328/ClashForAndroid#419]
**描述出现的错误**
build失败。

**如何复现该错误**
复现步骤:
1. clone dev branch
2. cp ```local.properties``` and ```keystore.properties```
3. ```./gradlew app:assembleRelease```

**预期行为**
build成功

**屏幕截图**
![image](https://user-images.githubusercontent.com/39483078/84563441-3a1a8800-ad8e-11ea-9f9b-029cc8d621c9.png)

**设备信息 (请完成以下信息):**
 - 机型: MacBook
 - 系统/ROM: macOS

**应用信息**
 - 版本: 1.3.1

**附加信息**
将app/build.gradle.kts 74行的```named```改为```register```即可在macOS和Linux上成功编译，但Windows仍有下图的错误：
![image](https://user-images.githubusercontent.com/39483078/84563505-a0070f80-ad8e-11ea-9535-930e04052838.png)
因为对gradle不是很熟悉，不清楚是否是这里```named```的错误，就不瞎提pr了。

**Comment by Kr328** [comment]
不是改了之后正常 而是第二次构建正常 不是很懂 Windows
