### ISSUE TITLE
[Feature Request] 支持修改HOSTS

### ISSUE THREAD

**Issue by fxzxmicah** [Kr328/ClashForAndroid#420]
**功能描述**
支持通过编辑Hosts文件来代理一些网站。

**描述你希望的实现方式**
加入一个Hosts编辑器，在Hosts中设置的网站使用Hosts中提供的IP直连，绕过所有的规则及代理。

**附加信息**
有些网站仅仅需要修改Hosts便可以实现快速访问，这时使用代理有些浪费。另外，由于安卓只能同时使用一个VPN连接，想用类似功能的软件只能关闭clash，比较麻烦，所以希望加入这样一个功能。

**Comment by Kr328** [comment]
自行编辑配置文件
