### ISSUE TITLE
[Feature Request] 希望能够自定义geoip数据库

### ISSUE THREAD

**Issue by kzw200015** [Kr328/ClashForAndroid#422]
**功能描述**
现在clash的geoip 数据库准确度不是很高，有些国内ip无法匹配
希望能够自定义geoip数据库并支持从在线URL或者本地文件更新数据库

**描述你希望的实现方式**
添加一个菜单，用于自定义数据库

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/411
