### ISSUE TITLE
[BUG] 节点名称显示不全

### ISSUE THREAD

**Issue by suemyass** [Kr328/ClashForAndroid#424]
**描述出现的错误**
订阅机场节点名称，节点名称显示不全

**如何复现该错误**
复现步骤:订阅
1. 显示
2. ...
3. ...
4. ...

**预期行为**
节点名称显示完全 一行一个

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 小米10
 - 系统/ROM: MIUI 11
 - Android 版本 10
 - ROM版本 11.0.25.0

**应用信息**
 - 版本: 1.2.15
 - 安装包文件名: 
 - 应用来源: Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/246
