### ISSUE TITLE
[BUG] 不能在OPPO手机上安装！

### ISSUE THREAD

**Issue by LovingXiaobing** [Kr328/ClashForAndroid#425]
这是我的安卓设备信息
![Screenshot_2020-06-15-09-41-47-64](https://user-images.githubusercontent.com/40991112/84610243-81b72600-aeec-11ea-92eb-6e0459e1ff0b.png)
安装的时候弹出的提示信息
![Screenshot_2020-06-15-09-41-43-80](https://user-images.githubusercontent.com/40991112/84610272-972c5000-aeec-11ea-92d5-475954ead6f5.png)

在网上搜索这个问题时，有别的网友说是apk未签名。

请问该如何解决？

除了x86的安装包没试过（arm不支持），其他的安装包全试过了。

**Comment by HinataKato** [comment]
只支持7.0+
[Requirement Android 7.0+ armeabi-v7a , arm64-v8a, x86 or x86_64 Architecture](https://github.com/Kr328/ClashForAndroid/blob/master/README.md#requirement)
