### ISSUE TITLE
[BUG] 不启动clash没法查到配置文件的proxy吗？另外有支持直接查询所有代理的api么

### ISSUE THREAD

**Issue by WayneLyn** [Kr328/ClashForAndroid#426]
**描述出现的错误**
请简洁的描述你遇到的错误
我这边发现不启动clash，首先queryAllproxyGroup是只能获取到一个默认的Global Direct全局直连的Group。配置中其他的proxy group是看不到的。启动clash后这个api可以查到所有proxy group，这是这么设计的么？有什么办法在加载过配置后，不启动也能获取到所有的代理组？另外有没有提供给上层android这块接口直接获取配置中所有的proxies的？

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
不启动不载入配置文件哪来的 Proxy Group

**Comment by WayneLyn** [comment]
我的意思是，首次启动了，之后关闭了。但是这个配置文件不是激活过了么，按理说应该有proxy的相关信息了吧，我看你这边是配置激活了但是没启动，代理那块的按钮是隐藏的。 @Kr328

**Comment by Kr328** [comment]
@WayneLyn 关闭了会载入空配置来防止 url test / rule provider 造成的资源浪费

**Comment by WayneLyn** [comment]
嗯，我是看到了，关闭后queryAllProxyGroup返回的是一个Global Direct的默认配置。那这个有办法在关闭的情况获取已激活的配置的proxy么

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/426#issuecomment-644187310

**Comment by SainoNamkho** [comment]
> 不启动不载入配置文件哪来的 Proxy Group

电脑版就可以
