### ISSUE TITLE
[BUG] io:read/write on closed pipe

### ISSUE THREAD

**Issue by qz1998** [Kr328/ClashForAndroid#428]
**描述出现的错误**
请简洁的描述你遇到的错误
机场订阅出现io:read/write on closed pipe
**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 一加7p
 - 系统/ROM:H2OS
 - Android 版本 10
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.3.2]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如:GITHUB]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
