### ISSUE TITLE
[BUG] Android 11 Beta 1 中无法正常工作

### ISSUE THREAD

**Issue by caijielun** [Kr328/ClashForAndroid#429]
**描述出现的错误**
 Pixel 3 XL 升级至 Android 11 Beta 1 后无法使用，表现为连接后持续 0 Bytes Forwarded，无 Log

使用 global 或者 proxy mode 均一样，Chrome 可访问国内网站，不可访问 Q 外网站

**如何复现该错误**
复现步骤:
1. 打开 ClashX
2. 点击 Stopped 按钮

**预期行为**
正常代理

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Pixel 3 XL
 - 系统/ROM: 原生
 - Android 版本 11 Beta
 - ROM版本 RPB1.200504.018

**应用信息**
 - 版本: 1.2.15
 - 安装包文件名: -
 - 应用来源: Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
@caijielun 是否与 https://issuetracker.google.com/issues/155221676 相关

**Comment by caijielun** [comment]
有可能是，我刚试着重启了一下，可以连接，断开后再次连接就不行了。

**Comment by Love4Taylor** [comment]
K20 Pro，Pixel Experience 10，类似症状（其中一次看 Clash 通知栏是以 10MB 的速度一直不停上传）重启后正常。

**Comment by SpringMagnolia** [comment]
> K20 Pro，Pixel Experience 10，类似症状（其中一次看 Clash 通知栏是以 10MB 的速度一直不停上传）重启后正常。

你解决了么

**Comment by Love4Taylor** [comment]
@SpringMagnolia 闭源后的版本没出现过该问题了。

**Comment by ygsk10** [comment]
Beta 2 中已经可以正常工作
