### ISSUE TITLE
刚开机，首次点击开启tap to start报错

### ISSUE THREAD

**Issue by DrSkilled** [Kr328/ClashForAndroid#43]
如题，再次点击就正常了

**Comment by DrSkilled** [comment]
设备是mate 20， 安卓10

**Comment by Kr328** [comment]
信息不足 无法判断

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
