### ISSUE TITLE
[Feature Request] 关于FCM单次连接时长的问题

### ISSUE THREAD

**Issue by JackRBlack** [Kr328/ClashForAndroid#432]
**功能描述**
开启代理后（模式为规则，不代理选中的国内应用），后台可以看到FCM单次连接时长为50秒左右。这样子会比较耗电… 不知道是否可以绕过FCM代理？我注意到之前已经关闭的一个issue https://github.com/Kr328/ClashForAndroid/issues/164 里面有提到相同的问题，但是开发者的回复中的issue链接点开后显示已删除，所以想再问一下。

**描述你希望的实现方式**
通过设置规则绕过FCM代理。

**附加信息**
FCM诊断信息如截图所示
![Screenshot_20200617-110800](https://user-images.githubusercontent.com/22671074/84850868-5a4a8f80-b08b-11ea-8ff0-2fe4a51f5abc.png)

**Comment by EKyero** [comment]
@JackRBlack https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
这应该你自己写

**Comment by Kr328** [comment]
![Screenshot_20200617-112007](https://user-images.githubusercontent.com/39107975/84851350-9d593280-b08c-11ea-9b42-2e325f51bf8a.png)

**Comment by JackRBlack** [comment]
谢谢，已经搞定了。第一次用 clash，原来规则设置是和配置文件在一起。之前还奇怪在哪里导入规则 2333
