### ISSUE TITLE
[Feature Request]  easier way to allow different app to connect different proxy address

### ISSUE THREAD

**Issue by dual2cross** [Kr328/ClashForAndroid#436]
Dear,

I love your work so much. It makes possibility to use several independent-purpose apps at one time. But the rule is ip/URL-based and it seems hard to figure out the list of ip(s) which a app tries to connect.

Can you try to allow different app as a whole to connect different Proxy Server? This means more specific control based on app, not URL.

By now, I noticed ClashForAndroid had a list to control apps' access to internet. It's good to have a firewall for android. This feature is just simple on/off option and what I want is the third option (controled proxy address).

Thank you.

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.1

See also `PROCESS-NAME` rules on https://github.com/Dreamacro/clash/wiki/configuration
