### ISSUE TITLE
[Feature Request] 请求增加“查看该网站使用的总计流量”功能

### ISSUE THREAD

**Issue by z245045** [Kr328/ClashForAndroid#437]
**功能描述**
在Connections界面的基础上，添加该连接的流量总使用量。

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Clash for Android 哪来的 Connections

而且 上游也没有实现这个功能
