### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by zer0yu** [Kr328/ClashForAndroid#438]
**功能描述**
希望可以加入局域网代理共享功能

**描述你希望的实现方式**
like电脑本版本的那样就可以

**附加信息**
无

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
