### ISSUE TITLE
[Feature Request] 能不能给拒绝本地主机流量和排除127.0.0.0/8这两个功能加个开关

### ISSUE THREAD

**Issue by jqglv** [Kr328/ClashForAndroid#439]
**功能描述**
请求给拒绝本地主机流量和始终排除127.0.0.0/8这两个功能加个开关

**描述你希望的实现方式**
我不知道实现的方法

**附加信息**
请求加开关的原因，之前用旧版本一直没事，但是从1.2.13这个版本之后EvolutionX的允许热点使用VPN的功能用不了了，更准确的说是开启EvolutionX的允许热点使用VPN的功能之后所有连接热点的设备都无法联网。我猜测是因为新加的拒绝本地主机流量和始终排除127.0.0.0/8这两个功能的原因，所以大佬能不能给这两个功能加一个开关

**Comment by Kr328** [comment]
现在退回 1.2.12 就能用了?
