### ISSUE TITLE
希望添加快速切换开关状态的桌面方式的功能

### ISSUE THREAD

**Issue by zyc63959** [Kr328/ClashForAndroid#440]
**功能描述**
添加桌面快捷方式，3D菜单快捷方式（长按桌面图标可以显示的菜单）
**描述你希望的实现方式**
归根揭底是为了被Tasker调用，Tasker功能已经添加了对快捷方式的支持，作者不必引入Tasker插件包，当然如果能直接添加对Tasker的支持更好。
**附加信息**
目前很多开源的工具，s{2}，s{2}r，s{2}rr，open^bu，WG，均可以被Tasker调用

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
