### ISSUE TITLE
[Feature Request] 问一下，就是谷歌市场那一边不更新了？

### ISSUE THREAD

**Issue by Potterli20** [Kr328/ClashForAndroid#442]
我就是想问问谷歌市场不更了？

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by EKyero** [comment]
@Potterli20 1. 会
2. 实验性版本 和 不稳定版本 都只是在github上发, 较稳定版本 才会在play上发

**Comment by Potterli20** [comment]
> @Potterli20
> 
> 1. 会
> 2. **实验性版本** 和 **不稳定版本** 都只是在github上发, **较稳定版本** 才会在play上发

哦哦明白
