### ISSUE TITLE
不开源后会不会继续提供googleplay下载？

### ISSUE THREAD

**Issue by 1human** [Kr328/ClashForAndroid#443]
今天进那个tg群，大佬说不再开源。那么不开源的版本会不会继续登陆Google商店？
然後，希望代理规则可以自定义。默认分流规则和V2ray比差一点，和ssr的默认列表差两点，和ssr的自定义规则差三点..........

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by AkariiinMKII** [comment]
1. “那个tg群”是哪个？
2. 不稳定版本从一开始就是在GitHub和tg频道发布的
3. 不能自定义规则也是“那个tg群”的大佬教你的吗？
