### ISSUE TITLE
[Feature Request]  能不能实现自定义分流规则？

### ISSUE THREAD

**Issue by 1human** [Kr328/ClashForAndroid#444]
希望能实现自定义分规则，默认的那个根本不行，太费劲了，只能设置分应用代理+全局。。。。

**Comment by 1human** [comment]
奥，如果不开源的的话，会不会继续提供gp下载

**Comment by xuhaoyang** [comment]
@1human 请您了解下Clash rules。https://lancellc.gitbook.io/clash/clash-config-file/rules

**Comment by Kr328** [comment]
![Screenshot_20200622-160325](https://user-images.githubusercontent.com/39107975/85263589-f61c3700-b4a1-11ea-9e56-b9e1d2cf1baa.png)
抄写一万遍

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/442#issuecomment-647346221

**Comment by 1human** [comment]
> @1human 请您了解下Clash rules。https://lancellc.gitbook.io/clash/clash-config-file/rules

不好意思，没看明白。这个网貌似介绍了clash的语法规则，我好想并没有看到现在的app里有现成的导入什么的选项。 或者这个规则是根据订阅节点设置的？ 不明白 不明白 不明白
反正我是觉得像ssr 小火箭 圈x的规则一搜一大把，很方便导入。。。。 希望更简单吧
