### ISSUE TITLE
doh dns 使用 alidns 等大型公共 dns 会不会更好？

### ISSUE THREAD

**Issue by qianxu2001** [Kr328/ClashForAndroid#445]
2.0.3 版本的更新日志中提到使用了 rixCloud 提供的 doh dns，没记错这个提供商应该是个搞机场的，想问一下使用 alidns 之类的话会不会在延迟、稳定性、隐私保护等方面上更好？
举例 [alidns](https://alidns.com/faqs/#dns-safe)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by NevadaCities** [comment]
@qianxu2001 玄学考虑

**Comment by Kr328** [comment]
@NevadaCities 你自己改配置文件 自己体验 我反正说什么都不如你自己体验来的实在
