### ISSUE TITLE
[Feature Request] 使用url scheme时避免重复导入

### ISSUE THREAD

**Issue by qswlqswl** [Kr328/ClashForAndroid#446]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
使用url scheme时避免重复导入同一url profile

**Describe alternatives you've considered**

**Additional context**

**Comment by Kr328** [comment]
每一个请求应当视为一个新的配置文件

这个行为应当与手动创建配置文件一致

**Comment by qswlqswl** [comment]
虽然不是同一个项目 clashforwin 和 clashx 都不会重复导入

**Comment by qswlqswl** [comment]
ios 的绝大多数也不会

**Comment by Kr328** [comment]
@qswlqswl 那就应该问前端 而不是 让 App 来擦屁股

**Comment by qswlqswl** [comment]
前端指的是提供商的网站吗

**Comment by Kr328** [comment]
@qswlqswl 对

并且在不同的 ROM 上命中 url scheme 的逻辑也可能不同 在 未经大量修改的 ROM 上 跳转一次相关链接 仅会产生一次创建配置请求

**Comment by qswlqswl** [comment]
重复导入实际上也没什么关系 这样看来不如不改
