### ISSUE TITLE
clash每次选择全局，软件退出后又变回规则了

### ISSUE THREAD

**Issue by OR120** [Kr328/ClashForAndroid#448]
clash每次选择全局，软件退出后又变回规则了

**如何复现该错误**
复现步骤:
clash每次选择全局，软件退出后又变回规则了，百分百

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
