### ISSUE TITLE
[BUG] Shield TV 启用后Youtube可以访问，但WLAN始终显示“已连接，但无法访问互联网”

### ISSUE THREAD

**Issue by crackerfly** [Kr328/ClashForAndroid#449]
**描述出现的错误**
设备平台：Nvidia Shield TV 2017/2019
系统版本：Android TV OS 9.0
软件版本：clash 2.0.3
故障现象：启用代理后Youtube、Google play、Netfilx都可以访问，但系统设置内WLAN始终显示“已连接，但无法访问互联网”

**如何复现该错误**
复现步骤:
1. 安装clash
2. 配置代理
3. 启用
4. 连接成功

**应用信息**
 - 版本: [2.0.3]
 - 安装包文件名: [app-arm64-v8a-release.apk]
 - 应用来源: [本站]

**附加信息**
//

**配置文件**
//
# 在此粘贴
//

**日志**
//

**Comment by Kr328** [comment]
没有日志的话 等未来有缘人解决吧

**Comment by 4512369781** [comment]
访问控制模式用“仅允许以选择的应用”，应该可以解决你的问题。

**Comment by asinitial** [comment]
这个是类似于手机上wifi显示的叉号，你谷歌一下去除叉号的方法，然后远程adb进盒子，改一下检测服务器就行了

**Comment by crackerfly** [comment]
> 这个是类似于手机上wifi显示的叉号，你谷歌一下去除叉号的方法，然后远程adb进盒子，改一下检测服务器就行了

使用您的方法问题已解决，感谢
