### ISSUE TITLE
[BUG] 启动代理后clash监听失败

### ISSUE THREAD

**Issue by mchobbylong** [Kr328/ClashForAndroid#450]
**描述出现的错误**
启动代理后主界面显示clash为已启动状态，但是系统的VPN标识很快就消失了。

**如何复现该错误**
复现步骤:
1. 点击启动代理

**设备信息 (请完成以下信息):**
 - 机型: OnePlus 5T
 - 系统/ROM: 氢OS
 - Android 版本: 9
 - ROM版本: 9.0.9

**应用信息**
 - 版本: 1.3.2
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GitHub Releases

**配置文件**
[Pastebin](https://pastebin.ubuntu.com/p/G4NfqP9JGd/)

**日志**
[Pastebin](https://pastebin.ubuntu.com/p/V4wXkFpfk8/)

**Comment by NevadaCities** [comment]
@mchobbylong 開啟一次后關閉後台再開啟就可以了

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.0.3

**Comment by mchobbylong** [comment]
@NevadaCities 感谢指点。

刚刚发现是更新时误安装了旧版的安装包。使用 2.0.3 一切正常。
