### ISSUE TITLE
[BUG] 访问控制应用包列表对系统应用识别错误

### ISSUE THREAD

**Issue by zincccccc** [Kr328/ClashForAndroid#451]
**描述出现的错误**
在访问控制应用包列表中选择过滤，若“系统应用”未勾选，实际显示的是**系统应用**；若“系统应用”已勾选，实际显示的是全部应用。

**预期行为**
若“系统应用”未勾选，实际显示的应当是**非系统应用**

**应用信息**
 - 版本: [2.0.3]

**Comment by cheeserick** [comment]
我也遇到这个问题，刚想来提issue就发现已经有了😂

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.0.4
