### ISSUE TITLE
[help wanted] 使用DlerCloud的订阅无法访问

### ISSUE THREAD

**Issue by ily433664** [Kr328/ClashForAndroid#452]
**描述出现的错误**
使用DlerCloud的订阅，获取、更新配置和测试速度都正常，但是开启代理无法访问外网，上传和下载一直都是显示0kb，规则模式和全局模式都试过了。
该订阅在pc上面可以正常使用。

**如何复现该错误**
复现步骤:
正常操作

**预期行为**
正常应该访问google，twitter等

**屏幕截图**
![image](https://user-images.githubusercontent.com/30280772/85493276-2df1be80-b609-11ea-8491-68c7cd6931ba.png)

![image](https://user-images.githubusercontent.com/30280772/85491857-d5b9bd00-b606-11ea-9d75-ddc5143ae9ee.png)

**设备信息 (请完成以下信息):**
 - 机型: 魅族16th
 - 系统/ROM: flyme 8.1.0.0A
 - Android 版本 8.1.0
 - ROM版本 20.3.1

**应用信息**
 - 版本: 2.0.3（其它版本也试过了）
 - 安装包文件名: app-universal-release.apk
 - 应用来源: github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
![image](https://user-images.githubusercontent.com/30280772/85493164-fa169900-b608-11ea-8417-1c3a0987f370.png)
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
