### ISSUE TITLE
[BUG] 使用内置DNS部分软件无法使用

### ISSUE THREAD

**Issue by YamazakuraH** [Kr328/ClashForAndroid#455]
**描述出现的错误**
请简洁的描述你遇到的错误
比如网易云无法缓冲歌曲
**如何复现该错误**
复现步骤:
开启 DNS配置覆盖

**设备信息 (请完成以下信息):**
 - 机型: Xiaomi 9
 - 系统/ROM: MIUI12
 - Android 版本 10
 - ROM版本 20.6.23

**应用信息**
 - 版本: 2.0.5
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GitHub

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
没有日志的话 等上帝来给你修吧

**Comment by YamazakuraH** [comment]
等 会

**Comment by YamazakuraH** [comment]
是vps的问题，弄好了。
