### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by WangYuana** [Kr328/ClashForAndroid#457]
**Describe the bug**
我是开发人员用的你的源码为何现在运行崩溃了，有什么办法可以解决

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: [e.g. Pixel 4]
 - ROM: [e.g: AOSP]
 - ROM Version:
 - Android Version [e.g. 10]

**Application Info (please complete the following information):**

 - Version: [e.g. 1.1.10]
 - Apk File Name: [e.g. app-release-arm64-v8a.apk]
 - Distribution Channel: [e.g. Google Play]

**Additional context**

**Configure**
If applicable, paste **removed server info** configure
```yaml
# paste here
```

**Logs**
If applicable, paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by Kr328** [comment]
@WangYuana 你既然是开发人员 就应该自己解决代码问题 不然要你何用 对吧

**Comment by WangYuana** [comment]
崩溃时源代码问题，你在里面加了一些核心东西导致不能用了。如果我这边写的代码问题我肯定及时解决了，因为用的你们的创建vpn,在换别的vpn源代码也麻烦，麻烦你给个解决方案感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kr328"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 晚上11:35
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;; 
抄送: "咕叽咕叽"<1918765432@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Kr328/ClashForAndroid] [BUG]  (#457)





 
@WangYuana 你既然是开发人员 就应该自己解决代码问题 不然要你何用 对吧

**Comment by Kr328** [comment]
@WangYuana 我都免费开发 App 了 为什么还要免费给你调试呢

**Comment by WangYuana** [comment]
算了我用v2ray开源代码去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kr328"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 晚上11:41
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;; 
抄送: "咕叽咕叽"<1918765432@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Kr328/ClashForAndroid] [BUG]  (#457)





 
@WangYuana 我都免费开发 App 了 为什么还要免费给你调试呢

**Comment by Kr328** [comment]
@WangYuana 走好不送

**Comment by WangYuana** [comment]
或者加你个电报友，给个更换的时间也行。在或者购买你的源码用也行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kr328"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 晚上11:34
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;; 
抄送: "咕叽咕叽"<1918765432@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Kr328/ClashForAndroid] [BUG]  (#457)





 
Please use Issue Template to create issue
 请务必使用 Issue Template 创建 Issue
 
Issue Template

**Comment by Kr328** [comment]
@WangYuana 我可不敢收钱 不然过几天人没了 就不好了

**Comment by WangYuana** [comment]
我们公司用的你的搭建vpn去售卖了，目前有5000多用户，如果你愿意合作可以购买你的源码，不愿意我们更换v2ray,trojan三方的源代码放上去一样可用只是加班修复问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kr328"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 晚上11:46
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;; 
抄送: "咕叽咕叽"<1918765432@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Kr328/ClashForAndroid] [BUG]  (#457)





 
@WangYuana 我可不敢收钱 不然过几天人没了 就不好了

**Comment by Kr328** [comment]
@WangYuana 你们公司那么厉害 找个能调通的人 并不难呢 对吧

**Comment by WangYuana** [comment]
在看，大晚上被交到公司真尼玛无语




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kr328"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 晚上11:50
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;; 
抄送: "咕叽咕叽"<1918765432@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Kr328/ClashForAndroid] [BUG]  (#457)





 
@WangYuana 你们公司那么厉害 找个能调通的人 并不难呢 对吧

**Comment by Delecomp** [comment]
@WangYuana ？

**Comment by Kr328** [comment]
@WangYuana 好的呢 祝你好梦 走好不送
