### ISSUE TITLE
[BUG] vmess 部分混淆不可用

### ISSUE THREAD

**Issue by foxni** [Kr328/ClashForAndroid#459]
**描述出现的错误**
从电脑上直接copy过来的配置文件，tls+ws的没有问题，tcp+http伪装的在手机上无法连接，没有抓到相关日志

**如何复现该错误**
参照Dreamacro给出来的tcp+http的配置例子，额外新增了Host，user-agent等header参数，macOS下的clashx可以正常使用，但是配置文件在手机上无法连接。

**预期行为**
听说完全继承了clash prime的特性，另外http伪装非常有助于避免Qos(至少在我这边效果相当明显)，希望手机版的也能继承该特性

**屏幕截图**
应用自带的日志捕捉没有捕捉到任何日志，也未有任何报错信息抛出。

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]
三星 s10+ 国行 Android 10 one ui 2.1

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]
app-release-arm64-v8a.apk 2.0.6
Goolge Play上的1.2几的版本都尝试过

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
没有日志的话 那就是你们三星 VPN 实现问题了

**Comment by Kr328** [comment]
自行修改配置文件 把日志级别调整到 debug 再看看

**Comment by foxni** [comment]
日志出来了，经过这两天测试发现，可能跟clash 本身对http伪装支持不完善有关，app上其实能连上，但是质量很差，基本处于不可用状态。在电脑端情况稍微好点，但是网络质量依然很差。

**Comment by Kr328** [comment]
那就是上游问题了
