### ISSUE TITLE
更新订阅请求时发送clashforandroid协议头

### ISSUE THREAD

**Issue by tokumeikoi** [Kr328/ClashForAndroid#46]

**Comment by Kr328** [comment]
在? 来点细节

**Comment by Howard-00** [comment]
> 在? 来点细节

我估计他的意思应该是让服务器可以知道发出请求的是 Clash For Android，然后可以针对地对配置文件做出一些改动

**Comment by Kr328** [comment]
> > 在? 来点细节
> 
> 我估计他的意思应该是让服务器可以知道发出请求的是 Clash For Android，然后可以针对地对配置文件做出一些改动

这个知道 但是又不说 哪个头 总不能 Content-Type 吧
还有 Url 参数 不好吗

**Comment by tokumeikoi** [comment]
失策，忘了说哪个头了，UA能加上clash for android就好了

**Comment by tokumeikoi** [comment]
> > > 在? 来点细节
> > 
> > 
> > 我估计他的意思应该是让服务器可以知道发出请求的是 Clash For Android，然后可以针对地对配置文件做出一些改动
> 
> 这个知道 但是又不说 哪个头 总不能 Content-Type 吧
> 还有 Url 参数 不好吗

这样可以做到一个地址适配全部客户端岂不是美滋滋

**Comment by mmmji** [comment]
强烈建议UA增加clash for android，目前没有ua 订阅无法自动识别

**Comment by betaxab** [comment]
同样请求跟进，谢谢。

**Comment by Kr328** [comment]
1.1.0 版本的 User-Agent 为 
`ClashForAndroid/<VersionName>`
