### ISSUE TITLE
[BUG] 从通知栏快捷开关打开提示应用损坏

### ISSUE THREAD

**Issue by xiaoguoyi** [Kr328/ClashForAndroid#461]
**描述出现的错误**

从通知栏快捷开关打开提示应用损坏
**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**

从通知栏快捷开关打开提示应用损坏
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![9_KZ92X_C_Z9YR~9TU7`2KL.jpg](https://i.loli.net/2020/06/27/hoBTwnGivWOc8VL.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米9
 - 系统/ROM: MIUI 12开发版
 - Android 版本 10
 - ROM版本 : 20.6.18

**应用信息**
 - 版本: 2.0.7 -arm64-v8a
 - 安装包文件名:  app-release-arm64-v8a.apk
 - 应用来源: Google Play

**附加信息**

**配置文件**

```yaml
# 在此粘贴
```

**日志**

```
<在此粘贴>
```

**Comment by xiaoguoyi** [comment]
github下载的也是同样

**Comment by Kr328** [comment]
@xiaoguoyi 在你们 MIUI 的 安全中心 允许 Clash for Android 唤醒 以及 自启动

**Comment by xiaoguoyi** [comment]
> @xiaoguoyi 在你们 MIUI 的 安全中心 允许 Clash for Android 唤醒 以及 自启动

蟹蟹QAQ

**Comment by Kr328** [comment]
This issue has been resolved
此问题已得到解决
