### ISSUE TITLE
如何关闭内置的机场DoH

### ISSUE THREAD

**Issue by kslr** [Kr328/ClashForAndroid#462]
2.0.7 Goolgle Play

没有找到关闭的位置。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by kslr** [comment]
遗憾的是，这并不适用模板。

**Comment by Kr328** [comment]
![Screenshot_20200628-003419](https://user-images.githubusercontent.com/39107975/85927207-2c5d1a80-b8d7-11ea-965d-31980dab1ae4.png)

眼睛不需要可以捐给有需要的人
