### ISSUE TITLE
[Feature Request] 建议提供更新订阅时改写Proxy、Proxy Group、Rule等字段为proxies、proxy-groups、rules的功能

### ISSUE THREAD

**Issue by zhouzl7** [Kr328/ClashForAndroid#463]
**功能描述**
建议提供更新订阅时改写Proxy、Proxy Group、Rule等字段为proxies、proxy-groups、rules的功能，具体可以参考Clash For Windows的做法。原因是很多代理商并不会更新他们的clash规则，他们只会要求用户使用某个年代久远的支持他们规则的客户端版本。

**描述你希望的实现方式**
具体可以参考Clash For Windows的做法。
cfw-profile-parsers:
  - url: https://example.com
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const { 'Rule': rules = [], 'Proxy Group':groups = [], 'Proxy': proxies = [] } = rawObj
        delete rawObj['Rule']
        delete rawObj['Proxy Group']
        delete rawObj['Proxy']
        return yaml.stringify({ ...rawObj, proxies, 'proxy-groups': groups, rules })
      }

或者进行字符串的匹配。

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
1. Android 没有高效执行各种脚本语言的环境
2. Android 是移动设备 需要经常执行重载操作不可能使用低效脚本实现来处理
3. 不修改配置文件是原则 也没有方便的手段修改
