### ISSUE TITLE
[BUG] proxy-providers 在 proxy 配置文件更新后 clash 没有添加新的 proxy

### ISSUE THREAD

**Issue by kuyagic** [Kr328/ClashForAndroid#465]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1.使用 proxy-providers 来使用独立文件配置 proxies
2. 添加一个代理到 proxies,
3. clash 更新配置文件
4. 再添加一个代理到 proxies
5. clash 更新配置文件 没有发现第四步中添加的代理. 还是只有最原始的代理配置(1个)
**预期行为**
更新所有 proxies 独立文件中定义的代理

目前只能删除配置重新添加并更新可以解决这个问题.

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Oneplus 5
 - 系统/ROM: PixelExperience
 - Android 版本 10
 - ROM版本 最新版

**应用信息**
 - 版本: 2.07
 - 安装包文件名:  app-release-arm64-v8a.apk
 - 应用来源: Github

**Comment by Kr328** [comment]
更新配置文件不意味着更新 provider

provider 更新逻辑由配置文件决定

下版本会提供 provider 管理功能
