### ISSUE TITLE
自定义IP库（mmdb库）更新地址

### ISSUE THREAD

**Issue by alexlee728** [Kr328/ClashForAndroid#467]
希望可以在设置里添加自定义IP库（mmdb库）更新地址

https://github.com/Dreamacro/clash/issues/82#issuecomment-630541992

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
