### ISSUE TITLE
自定义IP库（mmdb库）更新地址

### ISSUE THREAD

**Issue by alexlee728** [Kr328/ClashForAndroid#468]
**功能描述**
添加自定义IP库（mmdb库）更新地址，及手动点击更新

**描述你希望的实现方式**
在设置中有输入框输入自定义的地址，并可以点击更新

**附加信息**
https://github.com/Dreamacro/clash/issues/82#issuecomment-630541992

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
