### ISSUE TITLE
[BUG] 2.0.8 版本 miui 11 状态栏快捷开关失效，VPN 图标异常

### ISSUE THREAD

**Issue by ehlxr** [Kr328/ClashForAndroid#469]
**描述出现的错误**
1. 2.0.8 版本 miui 11 状态栏快捷开关失效
2. WIFI 模式下 VPN 图标不显示，移动数据模式下关闭软件 VPN 图标不消失

**设备信息 (请完成以下信息):**
 - 机型: 小米 mix3
 - 系统/ROM: MIUI 11
 - Android 版本: 10
 - ROM版本: 11.0.3.0

**应用信息**
 - 版本: 2.0.8
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: github release

**Comment by xuhaoyang** [comment]
@ehlxr 1. 移除再添加

**Comment by wbmins** [comment]
@ehlxr 我也有这个问题，我感觉是手机的问题（小米8）

**Comment by ehlxr** [comment]
> @ehlxr 1. 移除再添加

👍 可以解决快捷开关失效的问题。VPN 图标还是异常

**Comment by ehlxr** [comment]
> @ehlxr 我也有这个问题，我感觉是系统的问题（小米8）

2.0.6版本以前是没问题的

**Comment by silentxrture** [comment]
去手机管家把cfa的自启动开关打开

**Comment by Kr328** [comment]
1. https://github.com/Kr328/ClashForAndroid/issues/461
2. VPN 应用 **完全没有** 能力控制 VPN 图标 为什么不去和 MIUI 开发组反馈呢
