### ISSUE TITLE
[BUG] 更新2.0.9后启动失败 & 更新订阅失败

### ISSUE THREAD

**Issue by cheeserick** [Kr328/ClashForAndroid#472]
**描述出现的错误**
更新到2.0.9版本后连接自动断开，试图重连时提示「启动失败」，清除应用数据并从 url 更新订阅时提示「下载失败」。退回2.0.8后恢复正常。

**如何复现该错误**
如上所述。

**预期行为**
应当正常启动。

**设备信息 (请完成以下信息):**
 - 机型: 一加5t
 - 系统/ROM: Pixel Experience
 - Android 版本: 10

**应用信息**
 - 版本: 2.0.9
 - 安装包文件名: ClashForAndroid-v2.0.9-app-arm64-v8a-release.apk
 - 应用来源: releases

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by standritsu** [comment]
https://github.com/Dreamacro/clash/wiki/Breaking-Changes-in-1.0.0

**Comment by Kr328** [comment]
@standritsu https://github.com/Kr328/ClashForAndroid/releases/tag/v2.0.10
