### ISSUE TITLE
[BUG] 新版的dns还是有问题

### ISSUE THREAD

**Issue by Zyears** [Kr328/ClashForAndroid#473]
**描述出现的错误**
新版的dns还是有问题
https://source.android.google.cn/这个网站打不开
显示无法访问，但是其他google.com的都没事，配置文件，也有那一项

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 一加3t
 - 系统/ROM: havoc3.6
 - Android 版本 10
 - ROM版本 20.6.7

**应用信息**
 - 版本: 2.0.10
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: git

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
为什么不检查日志和规则呢

我只能说 无法复现

**Comment by xuhaoyang** [comment]
@Zyears 规则不贴，日志不给，神仙帮忙
