### ISSUE TITLE
[BUG] java.io.IOException (no error message)

### ISSUE THREAD

**Issue by WangYuana** [Kr328/ClashForAndroid#474]
**描述出现的错误**
as运行报错，错误信息如下
Exec gomobile bind -target=android -trimpath github.com/kr328/cfa/bridge failure
> java.io.IOException (no error message)

**如何复现该错误**
复现步骤:
1. ...下载最新go版本
2. ...将core修改的代码全部替换Dreamacro/clash下的对应代码
3. ...运行出现上述错误
4. ...

**预期行为**
按照提示修改核心的core代码运行应该正常跑起来。

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
不对编译问题提供任何支持
