### ISSUE TITLE
[Feature Request] 能否添加直接开启配置的快捷方式，或者发布快速启动的广播，方便其他软件调用

### ISSUE THREAD

**Issue by sidesand** [Kr328/ClashForAndroid#475]
**功能描述**
1.能否添加可调用的快捷方式，直接启动节点。
2.能否公布一下：快速开启的广播

以上两点为了使用shell调用intent直接在clash软件无后台的状态下直接无界面启动节点连接。
或者是在自动化软件Tasker中以插件形式自动调用。

不知道我表达的清不清楚，emmm，意思就是想在自动无界面直接启动节点连接。

**Comment by Kr328** [comment]
#326
