### ISSUE TITLE
[BUG] 不是说2.0.1版就添加了rule set支持吗？

### ISSUE THREAD

**Issue by palese** [Kr328/ClashForAndroid#476]
**描述出现的错误**
不是说2.0.1版就添加了rule set支持吗？
现在用rule set规则还是添加不上

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![158105](https://user-images.githubusercontent.com/13195594/86219231-7d5d5f00-bbb4-11ea-9eda-cf2eca5ef97f.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 华为Mate 20 Pro
 - 系统/ROM: EMUI10
 - Android 版本 10
 - ROM版本 10.1.0.160

**应用信息**
 - 版本: 2.0.10
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```
:
# 自定义规则
- DOMAIN-SUFFIX,record.xiaojukeji.com,AdBlock
- DOMAIN-SUFFIX,is.snssdk.com,AdBlock
- DOMAIN-SUFFIX,show-m.mob.com,AdBlock
- DOMAIN-SUFFIX,ad.yipinread.com,AdBlock
- DOMAIN-SUFFIX,v3-ad.ixigua.com,AdBlock
- DOMAIN-SUFFIX,ldnovel.com,AdBlock
- DOMAIN-SUFFIX,xiaojukeji.com,Domestic
- DOMAIN-SUFFIX,udache.com,Domestic
- IP-CIDR,139.199.240.80/32,AdBlock
- IP-CIDR,139.199.240.81/32,AdBlock
- IP-CIDR,139.199.240.82/32,AdBlock
- IP-CIDR,139.199.240.83/32,AdBlock
- IP-CIDR,139.199.240.84/32,AdBlock
- IP-CIDR,139.199.240.85/32,AdBlock
- IP-CIDR,139.199.240.86/32,AdBlock
- IP-CIDR,139.199.240.87/32,AdBlock
- IP-CIDR,139.199.240.88/32,AdBlock
- IP-CIDR,139.199.240.89/32,AdBlock
- IP-CIDR,139.199.240.90/32,AdBlock

- RULE-SET,https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Liby.list,AdBlock

- RULE-SET,https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Apple_CDN.list,Apple
- RULE-SET,https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Apple_API.list,Apple

- RULE-SET,https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/AsianMedia.list,Domestic
- RULE-SET,https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/GlobalMedia.list,Global

- RULE-SET,https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Domestic.list,Domestic
- RULE-SET,https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Global.list,Global
  
- GEOIP,CN,Domestic
- MATCH,Global
**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
自行翻看上游文档

不要以你这点陈旧的知识来看待不同应用

**Comment by palese** [comment]
请指导一下怎么使用rule set

**Comment by Kr328** [comment]
@palese 自  行  翻  看  上  游  文  档

这里不照顾伸手党

**Comment by palese** [comment]
上游全英文的看不懂啊，也找不到个范本参考

**Comment by palese** [comment]
这个用法还是在规则维护者那里抄过来的，结果不能使用，也找不到其他可以参考的范本

**Comment by Kr328** [comment]
@palese 那你就等呗 等着有耐心的人来教教你

**Comment by AkariiinMKII** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/rule-provider
请

**Comment by palese** [comment]
> https://lancellc.gitbook.io/clash/clash-config-file/rule-provider
> 请

谢谢，文档看过了，但还是没学会怎么使用，很抱歉

**Comment by EKyero** [comment]
@palese https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/Global.yaml

**Comment by palese** [comment]
@EKyero 十分感谢，有范本参考就可以了
