### ISSUE TITLE
界面主题

### ISSUE THREAD

**Issue by isoraforever** [Kr328/ClashForAndroid#477]
**功能描述**
增加偏灰色主题
**描述你希望的实现方式**
黑色主题太黑了能偏灰点吗
**附加信息**
我爱死你了这个开发者 应用真的很棒 加油

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
