### ISSUE TITLE
[BUG] Play Store应用无法下载

### ISSUE THREAD

**Issue by Vincentaria** [Kr328/ClashForAndroid#478]
**描述出现的错误**
更新Clash到最新2.0.11版本后无法下载Google.Play商店应用，回退到旧版本没有问题。

**如何复现该错误**
复现步骤:
1. Play Store下载/更新 任意应用
2. 无法下载

**设备信息 (请完成以下信息):**
 - 机型: 小米10 Pro
 - 系统/ROM: MIUI 12
 - Android 10
 - ROM版本 12.0.2.0

**应用信息**
 - 版本: 2.0.11
 - 安装包文件名: arm64-v8a
 - 应用来源: Google Play

**Comment by Kr328** [comment]
无法复现

没有日志

神仙难救

**Comment by AkariiinMKII** [comment]
@Vincentaria 清理play store数据后再次尝试

**Comment by icolourful** [comment]
@AkariiinMKII 把google play省电策略改成无限制，把下载管理和下载管理程序的数据清理下。

**Comment by shikkoku** [comment]
给我关掉你下载管理器的迅雷加速…

**Comment by Begger-VIP** [comment]
@Vincentaria 请问目前问题解决了吗，我也是 play store 无法更新及下载？以及你使用的是哪个机场？

**Comment by unkosun** [comment]
我也遇到了同样的问题，Play Store里的应用无法下载和更新。小米Mix2s,MIUI 12

**Comment by mirrorb** [comment]
我也遇到了 好像把所有都代理之后就能下载了

**Comment by zhijianguo** [comment]
我也是，xiaomi9，不知道为什么，换成v2rayNG就没有问题！

**Comment by happyeddie** [comment]
MIUI 12.5
小米 11 ultra 和 小米平板 5 Pro 用 Clash，都无法从 Google Play 下载和更新，换成 Shadowsocks 就好了

**Comment by valee777** [comment]
红米K20pro同样的问题。所以问题是系统级的吗

**Comment by xuhaoyang** [comment]
国产ROM这个问题的确很烦人。

有一点确定的是，和CFA关系不大：
自查点儿：
1、国产rom魔改的Download，比如迅雷加速
2、节点问题
3、国产rom用的cn域名解析

关于2、3拓展讲一下
国产rom，用的google cn解析，下载软件 几乎100%会分配xn--ngstr-lra8j.com这个域名下，或类似。
表现有几个：
1、会解析到国内ip，无法下载
2、会解析到香港ip(正常)，国产ROM无法下载，但是经过魔改的XIAOMI EU或氧OS这种对外的ROM，是正常下载。

这种时候的解决方式，清空相关软件cache，选择非HK SG节点。拿到的下载域名是给比如JP等，基本上国产ROM都可以下载。

你也可以将xn--ngstr-lra8j.com改至其他地区的Google服务器ip，也可以正常下载。

**Comment by tobarcn** [comment]
> 国产ROM这个问题的确很烦人。
> 
> 有一点确定的是，和CFA关系不大： 自查点儿： 1、国产rom魔改的Download，比如迅雷加速 2、节点问题 3、国产rom用的cn域名解析
> 
> 关于2、3拓展讲一下 国产rom，用的google cn解析，下载软件 几乎100%会分配xn--ngstr-lra8j.com这个域名下，或类似。 表现有几个： 1、会解析到国内ip，无法下载 2、会解析到香港ip(正常)，国产ROM无法下载，但是经过魔改的XIAOMI EU或氧OS这种对外的ROM，是正常下载。
> 
> 这种时候的解决方式，清空相关软件cache，选择非HK SG节点。拿到的下载域名是给比如JP等，基本上国产ROM都可以下载。
> 
> 你也可以将xn--ngstr-lra8j.com改至其他地区的Google服务器ip，也可以正常下载。
> 
> 比如Google 把你的IP认为是国内 也会影响

牛，换个地区的节点确实解决了

**Comment by shy1997** [comment]
1.关闭迅雷加速下载
2.用非tw、hk、sg节点，用jp、us节点下载
解决了我多年的心病

**Comment by chobitsos** [comment]
> 国产ROM这个问题的确很烦人。
> 
> 有一点确定的是，和CFA关系不大： 自查点儿： 1、国产rom魔改的Download，比如迅雷加速 2、节点问题 3、国产rom用的cn域名解析
> 
> 关于2、3拓展讲一下 国产rom，用的google cn解析，下载软件 几乎100%会分配xn--ngstr-lra8j.com这个域名下，或类似。 表现有几个： 1、会解析到国内ip，无法下载 2、会解析到香港ip(正常)，国产ROM无法下载，但是经过魔改的XIAOMI EU或氧OS这种对外的ROM，是正常下载。
> 
> 这种时候的解决方式，清空相关软件cache，选择非HK SG节点。拿到的下载域名是给比如JP等，基本上国产ROM都可以下载。
> 
> 你也可以将xn--ngstr-lra8j.com改至其他地区的Google服务器ip，也可以正常下载。
> 
> 比如Google 把你的IP认为是国内 也会影响

实测换节点有效

**Comment by hanrai** [comment]
现在换节点也不好用了

>

**Comment by waxi-i** [comment]
同样遇到这个问题，无法下载应用，这个大家有解决办法吗
