### ISSUE TITLE
[BUG] 你们的网站上不去了

### ISSUE THREAD

**Issue by skywalker-dell** [Kr328/ClashForAndroid#479]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: [e.g. Pixel 4]
 - ROM: [e.g: AOSP]
 - ROM Version:
 - Android Version [e.g. 10]

**Application Info (please complete the following information):**

 - Version: [e.g. 1.1.10]
 - Apk File Name: [e.g. app-release-arm64-v8a.apk]
 - Distribution Channel: [e.g. Google Play]

**Additional context**

**Configure**
If applicable, paste **removed server info** configure
```yaml
# paste here
```

**Logs**
If applicable, paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
我什么时候有网站了???

**Comment by skywalker-dell** [comment]
[image: image.png]这个网站啊，我们在上面买会员，找安装包，还有人工客服

Kr328 <notifications@github.com> 于2020年7月2日周四 下午3:45写道：

**Comment by skywalker-dell** [comment]
[image: image.png]当初的界面是这个样子

wenxuan zhu <skywalker.dell@gmail.com> 于2020年7月2日周四 下午3:48写道：

**Comment by Kr328** [comment]
1. 我写代理软件 **从不提供服务**
2. 我没有开设过任何提供服务的网站

**Comment by EKyero** [comment]
@skywalker-dell

**Comment by skywalker-dell** [comment]
到底什么情况啊，你的软件能在那个网站上下载  clsah for Windows
那你这个软件是免费翻墙的吗

EKyero <notifications@github.com> 于2020年7月2日周四 下午3:50写道：

**Comment by Kr328** [comment]
1. **软件不收费**
2. **软件不提供任何网络服务**
3. 这里不接受除软件本身问题外的任何反馈
