### ISSUE TITLE
切换VPN导致ipv6路由错误

### ISSUE THREAD

**Issue by 948171624** [Kr328/ClashForAndroid#48]
安卓9 miui11 红米note5 移动4g网络（有公网v6）
软件：1.0.16（打开ipv6选项）或1.0.19（默认禁用ipv6选项）
操作（100%复现）：
1.用v2rayng（未打开此软件的ipv6选项）链接任意节点，此时ifconfig输出一个tun0设备
2.不断开v2ng的vpn，打开clash，start，系统会立即断开立即链接一个新vpn
3.ifconfig输出tun1设备（tun0消失）
4.断开clash，tun1消失
5.ping6任意ipv6，显示no route to host
6.飞行模式、再次重复步骤无法复原，必须重启。怀疑路由表错乱

建议：可能是clash反应太快以至于tun0没释放就新建了tun1。而同样操作把第二步的clash换成官方ss客户端就没事（此时仅仅生成新参数的tun0，不出现tun1），请您加一个判断，start前先断开已有vpn再新建。

注：1.0.16不打开ipv6选项没问题。1.0.19默认禁用ipv6反而有问题。

**Comment by Kr328** [comment]
没有权限管理非本应用建立的 VPN

**Comment by 948171624** [comment]
> 没有权限管理非本应用建立的 VPN

请问能申请到创建vpn权限后等待一下吗？
比如我先开clash再开ss官方客户端点开始，ss客户端会等半秒钟再创建vpn

**Comment by Kr328** [comment]
> > 没有权限管理非本应用建立的 VPN
> 
> 请问能申请到创建vpn权限后等待一下吗？
> 比如我先开clash再开ss官方客户端点开始，ss客户端会等半秒钟再创建vpn

不创建 VPN 你怎么关掉上一个 VPN
