### ISSUE TITLE
混淆插件支持

### ISSUE THREAD

**Issue by isoraforever** [Kr328/ClashForAndroid#480]
**功能描述**
能否增加Cloak流量混淆插件的支持
https://github.com/cbeuw/Cloak-android

**描述你希望的实现方式**
～

**附加信息**
爱你

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
