### ISSUE TITLE
[BUG] 开启cfa时，app经常需要登出后台或者刷新页面才能连接上并正确显示内容的问题

### ISSUE THREAD

**Issue by MinaseInori233** [Kr328/ClashForAndroid#483]
**描述出现的错误**
RT,绝大部分app会出现这个问题，有不同的表现形式

**如何复现该错误**
1. nga表现为一直转圈打不开页面，再次打开该页面即可正确显示内容
2. chrome表现为地址栏下方进度条一直在加载，退出后台重启chrome即可正确显示内容
3. bilibili表现为提示接口返回失败，所有视频均黑屏，退出后台重启bilibili即可正确显示内容
4. 贴吧表现为一直转圈打不开页面，再次打开该页面即可正确显示内容

**预期行为**
不应该出现的情况，我的配置文件使用surfboard和CFW都不会发生这个问题

**设备信息 (请完成以下信息):**
 - 机型: [OnePlus 5T(ONEPLUS A5010)]
 - 系统/ROM: [H2OS]
 - Android 版本 [10]
 - ROM版本 [20.05.19]

**应用信息**
 - 版本: [2.0.11以前的版本也有同样的问题]
 - 安装包文件名: [-arm64-v8a]
 - 应用来源: [Google Play]

**附加信息**
最开始用过一段时间CFA，大概是前两个多月左右，那时候还没有出现这个问题，是突发情况，具体什么时候记不清了，可能和系统更新有关，也有可能是CFA的版本问题

**配置文件**
[配置文件-DIYUnban+BanAD+Chinaip.txt](https://github.com/Kr328/ClashForAndroid/files/4867342/-DIYUnban%2BBanAD%2BChinaip.txt)

**日志**
日志里看到最大的和surfboard的区别是listen TCP （端口）

**Comment by Kr328** [comment]
务必上传完整的日志

**Comment by MinaseInori233** [comment]
> 务必上传完整的日志

[nga出问题时的日志.txt](https://github.com/Kr328/ClashForAndroid/files/4867575/nga.txt)
[贴吧出问题时的日志.txt](https://github.com/Kr328/ClashForAndroid/files/4867576/default.txt)

bilibili和chrome相对于贴吧和nga的情况要少很多  暂时没测试出来描述的问题

**Comment by neteroster** [comment]
有相同问题。Android 10。之前用 Android 9 的时候就正常。

**Comment by MinaseInori233** [comment]
> 务必上传完整的日志

[chrome问题.txt](https://github.com/Kr328/ClashForAndroid/files/4880100/chrome.txt)

chrome断流的问题，今天多起来了，还是一样需要杀后台或者关闭页面重新访问才能连上，这个日志只需要看00.12之后的

**Comment by Kr328** [comment]
@MinaseInori233 为什么不更新之后再试

**Comment by MinaseInori233** [comment]
> @MinaseInori233 为什么不更新之后再试

新版暂时没发现这种情况，但是有新的问题，CFW上能用的某两个节点在CFA上测速无数据，也无法正常使用这两个节点
