### ISSUE TITLE
在谷歌pixel 3上无法正常工作

### ISSUE THREAD

**Issue by danywheeler** [Kr328/ClashForAndroid#485]
![image](https://user-images.githubusercontent.com/8910772/86447389-ddd0d580-bd47-11ea-9896-7cb61e3318a3.png)

看上去一直没连接上代理服务器。

同样的订阅放到v2rayNG 上面工作正常

配置如下：
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
proxies:
   ...
proxy-groups:
    ...
rules:
    ...

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
