### ISSUE TITLE
[BUG] 更新后一直无法连上

### ISSUE THREAD

**Issue by LimonChoms** [Kr328/ClashForAndroid#487]
**描述出现的错误**
旧版本没问题，新版更新后一直无法连上，也更新了config，更换了新版的神机规则，尝试了自行设置DNS和关闭内置DNS都无效

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![QQ图片20200703163045](https://user-images.githubusercontent.com/46754160/86449493-d9f28280-bd4a-11ea-9ab7-55c9754a08e4.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 三星S10
 - Android 版本 10

**应用信息**
 - 版本: [2.0.11]
 - 应用来源: Play和github

**Comment by heham** [comment]
同问题，也是更新了之后无法使用，以为是规则的问题，重新编制了规则，电脑上测试无问题，手机上就不行了，原来的配置文件也不行

**Comment by heham** [comment]
测试链接都不成功，似乎就没有链接上服务器

**Comment by 707666** [comment]
+1

**Comment by LimonChoms** [comment]
> 测试链接都不成功，似乎就没有链接上服务器

是的

**Comment by Ros-ua** [comment]
+1 same problem.
on laptop working, on redmi k30 5g  clash v2.0.11 today noon stopped working
after adding profile it sees the servers but can not connect

**Comment by OnlyCharacter** [comment]
设置->网络->DNS配置覆盖->关闭

**Comment by LimonChoms** [comment]
> 设置->网络->DNS配置覆盖->关闭

没用

**Comment by Ros-ua** [comment]
> 设置->网络->DNS配置覆盖->关闭

this helped me,
Thank you

**Comment by heham** [comment]
> 设置->网络->DNS配置覆盖->关闭

谢谢，可用

**Comment by pudding1111** [comment]
设置里面我这儿没用，猫显示   检测到过时的配置文件

**Comment by OnlyCharacter** [comment]
> 设置里面我这儿没用，猫显示   检测到过时的配置文件

那是另一个问题了，你去看更新日志
