### ISSUE TITLE
[BUG] UDP流量无法正确匹配规则

### ISSUE THREAD

**Issue by isoraforever** [Kr328/ClashForAndroid#491]
**描述出现的错误**
UDP流量无法正确匹配规则

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
UDP流量正确匹配规则

**屏幕截图**
![Screenshot_20200704-142045~2](https://user-images.githubusercontent.com/31514237/86506496-585e2b80-be02-11ea-90e5-f2ec8545f8b8.png)

**设备信息 (请完成以下信息):**
 - 机型: [例如: HTC U11+]
 - 系统/ROM: [China sense]
 - Android 版本 [9]

**应用信息**
 - 版本: [the last release form Google Play]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [Google Play]

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/86506606-6bbdc680-be03-11ea-86b0-063cd617c8c0.png)

**Comment by isoraforever** [comment]
感谢提醒，已解决。
