### ISSUE TITLE
[BUG] Cann't launch 2.0.13 version of Clash

### ISSUE THREAD

**Issue by DrovGamedev** [Kr328/ClashForAndroid#492]
The program crashes

**Comment by cskz008** [comment]
我也是，直接闪退，我以为只有我有问题

**Comment by sidesand** [comment]
作者日夜兼程啊，给他点个大大的赞，顺便，话说最近K大有没有添加 #475 中的快捷方式的计划

**Comment by Kr328** [comment]
@sidesand "low-priority"

**Comment by DrovGamedev** [comment]
with version 2.0.14 everything is ok
