### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zqchina** [Kr328/ClashForAndroid#494]
![Screenshot_20200705_183457](https://user-images.githubusercontent.com/26019692/86530992-29be7e80-bef0-11ea-8dd2-c71003532dd1.jpg)
 每次运行都出这个提示，怎么回事？

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)

**Comment by EKyero** [comment]
https://github.com/Dreamacro/clash/commit/88d8f937938d7aba774b1af638df6910b1a1a14d

**Comment by AkariiinMKII** [comment]
https://github.com/Dreamacro/clash/wiki/Breaking-Changes-in-1.0.0
