### ISSUE TITLE
[BUG] 日志里出现的dial REJECT eror错误

### ISSUE THREAD

**Issue by isoraforever** [Kr328/ClashForAndroid#496]
**描述出现的错误**
日志里udp频繁出现Dial REJECT eror错误提示

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
排查错误

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
[Config](https://onedrive.live.com/?cid=261dea01eb20ce0c&id=261DEA01EB20CE0C%21108&authkey=!AKIsGhIlQqvzMEI) 
**日志**
[日志](https://onedrive.live.com/?authkey=%21AN-Cm_gycdUyP3c&cid=261DEA01EB20CE0C&id=261DEA01EB20CE0C%21109&parId=root&o=OneUp)

**Comment by Kr328** [comment]
REJECT 不出错我都不信
