### ISSUE TITLE
能否增加android 6.0的支持

### ISSUE THREAD

**Issue by liuwangfeng** [Kr328/ClashForAndroid#498]
**功能描述**
能否增加android 6.0的支持。

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
云手机就能用了

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
