### ISSUE TITLE
通知图标文件应为纯白色

### ISSUE THREAD

**Issue by NekoInverter** [Kr328/ClashForAndroid#5]
在一些 ROM（MIUI）上，带颜色的图标不会被 Tint
/service/src/main/res/drawable/ic_notification_icon.png

**Comment by NekoInverter** [comment]
（按照规范来说图标是必须为纯白色的

**Comment by maxitio** [comment]
贡献个svg格式的clash logo

```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
<title></title>
<g>
</g>
<path d="M843.28 48.821c-7.072 2.832-27.447 26.848-40.167 47.239-6.667 10.697-22.608 39.762-35.328 64.393-15.342 29.275-24.226 44.811-26.249 44.617-1.618-0.194-11.701-1.813-22.203-3.431-47.029-7.865-52.482-8.27-112.037-8.48-40.976 0-66.011 0.809-77.712 2.622-18.773 3.026-45.621 8.075-50.67 9.483-2.217 0.809-6.263-4.645-14.937-19.582-52.693-92.649-90.432-138.674-112.441-136.457-5.454 0.405-7.266 2.023-10.293 8.075-5.858 12.105-10.907 31.897-21.605 84.379-10.098 50.459-19.582 106.583-29.065 170.571-1.618 11.102-4.839 32.496-7.072 47.433s-5.454 37.755-7.266 50.459c-3.431 24.016-4.434 32.496-11.102 83.765-2.217 16.555-5.243 40.167-6.862 52.482-10.503 77.712-37.545 321.966-37.545 338.926 0 3.641-1.214 3.835-20.795 2.622-64.393-3.835-100.32-30.683-108.395-80.738-5.648-35.522 10.907-62.985 56.123-93.863 10.293-7.072 20.181-14.937 21.799-17.769 4.434-6.667 2.217-14.128-5.858-19.177-5.454-3.431-8.885-4.030-22.009-3.237-13.529 0.599-18.174 2.023-32.302 9.079-49.861 24.825-78.117 69.232-78.327 122.928 0 32.091 8.075 59.959 24.016 82.567 29.47 41.785 70.041 62.176 135.454 67.63 14.937 1.214 30.683 3.431 34.713 5.049 32.302 11.911 203.067 18.174 432.589 16.151 200.041-1.618 319.344-8.075 331.255-17.769 4.24-3.237 5.049-15.131 2.832-46.43-3.641-51.269-17.963-175.815-30.279-264.030-2.217-14.937-6.667-46.834-9.888-70.656-10.098-71.659-18.174-125.55-25.44-170.571-2.622-16.75-6.263-38.953-7.865-49.456-7.072-44.811-15.941-97.294-19.582-117.086-2.023-11.701-4.839-26.249-5.858-32.302-13.319-72.663-27.657-136.862-33.515-151.2-4.24-10.098-7.477-11.911-16.151-8.27z"></path>
</svg>
```

**Comment by NekoInverter** [comment]
（指的是通知图标文件

**Comment by Kr328** [comment]
FIXED in 1.1.0

**Comment by atbest** [comment]
最新版的2.0.18在深色状态栏下还是深蓝色的

**Comment by Kr328** [comment]
@atbest 不然呢 

你可以看看 Android 的 样例 是不是白色的

https://developer.android.com/guide/topics/ui/notifiers/notifications

**Comment by atbest** [comment]
应该是白色的啊，现在是这样的，如果状态栏是黑色的话就根本看不出来了 
![Screenshot_20200721](https://user-images.githubusercontent.com/8389395/88015012-dc2e4c80-cb52-11ea-81d8-b67bf5845678.png)

**Comment by Kr328** [comment]
![IMG_20200721_131002_101](https://user-images.githubusercontent.com/39107975/88015327-81492500-cb53-11ea-8b5c-d653fcb9caa1.jpg)
![IMG_20200721_130959_453](https://user-images.githubusercontent.com/39107975/88015331-85754280-cb53-11ea-96c1-0ce6c4ee5594.jpg)

难道不应该问问你的 ROM ?

**Comment by AkariiinMKII** [comment]
@atbest 们XXUI的问题

**Comment by atbest** [comment]
奇怪，别的app都没问题，请问你能不能清空一下编译的缓存然后重新编译一下试试？

**Comment by Kr328** [comment]
@atbest 这个版本就是全新编译的

**Comment by atbest** [comment]
@AkariiinMKII 怎么调成minimize?

**Comment by AkariiinMKII** [comment]
> @AkariiinMKII 怎么调成minimize?

notification settings里面
![Screenshot_20200721-132101.png](https://user-images.githubusercontent.com/6019344/88016028-1dbff700-cb55-11ea-8e2b-4b8a2811a5a8.png)

**Comment by atbest** [comment]
@AkariiinMKII 没有这个界面
@Kr328 根据我不成熟的观察，其他正常的app通知标题的颜色都是默认的，没有专门设置过，请问你能不能编译一个不设置标题和图标颜色的版本我试一下？
![Screenshot_20200721](https://user-images.githubusercontent.com/8389395/88016493-14835a00-cb56-11ea-86a0-0ef81cab1105.png)

**Comment by Kr328** [comment]
@atbest 不能 画图标的人现在不在

**Comment by AkariiinMKII** [comment]
@atbest 那只能问你们XXUI了

**Comment by atbest** [comment]
不用改图标，只是去掉设置颜色的代码就行，应该是在kotlin里面

**Comment by Kr328** [comment]
[app-arm.zip](https://github.com/Kr328/ClashForAndroid/files/4951508/app-arm.zip)

**Comment by atbest** [comment]
谢谢，不过还是不行，应该在其他的地方

**Comment by atbest** [comment]
我看了一下1.3.2的代码，里面 service/src/main/res/drawable/ic_notification.xml的fillColor是 #000000，如果最新版没变的话，应该是这个的问题，改成 #FFFFFFFF 应该就好了

**Comment by atbest** [comment]
这是我自己的一个app，我把那个耳机图标中两个竖条的 fillColor 改成 #000000 以后就变成了黑色了，剩下的半圆环的 fillColor 是 #FFFFFF。
![Screenshot_20200721](https://user-images.githubusercontent.com/8389395/88026656-c592f000-cb68-11ea-8626-7e5eb6ce7d39.png)

**Comment by AkariiinMKII** [comment]
@atbest fyi 在pixel上深色/浅色图标着色为#707173/#DDDDDD而没有使用APP自定义的#000000 
你细品.jpg

**Comment by AkariiinMKII** [comment]
> 这是我自己的一个app，我把那个耳机图标中两个竖条的 fillColor 改成 #000000 以后就变成了黑色了，剩下的半圆环的 fillColor 是 #FFFFFF。
> ![Screenshot_20200721](https://user-images.githubusercontent.com/8389395/88026656-c592f000-cb68-11ea-8626-7e5eb6ce7d39.png)
> 

另外有点好奇浅色状态栏下这个icon是什么表现

**Comment by atbest** [comment]
@AkariiinMKII 我不知道你说的这个跟我说的是不是同一个东西，不过我反编译了一下最新的apk文件，里面ic_notification.xml的fillColor是 #000000，而且我第一个截图的图标颜色也是#000000，跟我后来用自己的app试的结果是一样的。这么看来，这个问题就是fillColor是#000000的缘故，改成#FFFFFF或者#FFFFFFFF都可以修复这个问题。

**Comment by Kr328** [comment]
@atbest 他说的问题是 你的 ROM 行为与 AOSP 不一致 AOSP 无论什么颜色都能正确显示

**Comment by atbest** [comment]
@Kr328 麻烦你方便的时候把ic_notification.xml中的fillColor改成#FFFFFF吧，我再试一下，谢谢。

**Comment by AkariiinMKII** [comment]
@atbest 按照规范来的话icon的颜色是系统值决定的 不会引用fillcolor的值（有点好奇浅色状态栏下是直接反色？

**Comment by atbest** [comment]
@Kr328 麻烦你方便的时候把ic_notification.xml中的fillColor改成#FFFFFF吧，我再试一下，谢谢。

**Comment by atbest** [comment]
@AkariiinMKII 浅色的时候如果原来定义是白色的话是#6a6a6a，如果是黑色的话还是黑色

**Comment by AkariiinMKII** [comment]
@atbest 那你自行编译的那个呢

**Comment by Kr328** [comment]
@atbest 已经开始新版本迭代 懒得去编译旧版了

**Comment by atbest** [comment]
@AkariiinMKII 更正一下前面说的，浅色的时候黑色会变成 #515151
![Screenshot](https://user-images.githubusercontent.com/8389395/88056733-9a71c600-cb93-11ea-9b05-ee85468c0955.png)
@Kr328 没关系，用你现在的版本也行，只要能编得通跑得起来就行

**Comment by atbest** [comment]
> 在pixel上深色/浅色图标着色为#707173/#DDDDDD而没有使用APP自定义的#000000
@AkariiinMKII 我没有找到两个颜色的来源，你能说一下你的消息来源吗？最好有代码

**Comment by atbest** [comment]
> 在pixel上深色/浅色图标着色为#707173/#DDDDDD而没有使用APP自定义的#000000
@AkariiinMKII 我没有找到两个颜色的来源，你能说一下你的消息来源吗？最好有代码

**Comment by AkariiinMKII** [comment]
> > 在pixel上深色/浅色图标着色为#707173/#DDDDDD而没有使用APP自定义的#000000
> @AkariiinMKII 我没有找到两个颜色的来源，你能说一下你的消息来源吗？最好有代码
> 
> 

自己截图取的（

**Comment by atbest** [comment]
我怀疑这个具体的数值跟Android的版本有关系，还有你前面提到的minimize应该也是Android 8或者9以后才有的，之前的版本并不存在这个。不知道你如果不minimize的话是什么颜色的。

**Comment by atbest** [comment]
@Kr328 看到Play商店上的更新了，能改一下状态栏图标的颜色吗？谢谢

**Comment by Kr328** [comment]
@atbest Google Play 上的更新文件 来自 Github Release 并没有重新编译

**Comment by atbest** [comment]
好的，那等你下次发布新版本
