### ISSUE TITLE
一加 LineageOs 启动代理后不能上网

### ISSUE THREAD

**Issue by gyzclw** [Kr328/ClashForAndroid#50]
启动代理后不能上网,0bytes/s 上传 0bytes/s下载,mac 上的clash是 能正常使用

**Comment by Kr328** [comment]
1. 应用版本
2. 截取日志

**Comment by gyzclw** [comment]
1.021 alpha
![WechatIMG15](https://user-images.githubusercontent.com/10341322/71067361-62467700-21af-11ea-81bc-c743afc4ef2a.jpeg)

**Comment by CodingOX** [comment]
节点是不是有中文！？

> 启动代理后不能上网,0bytes/s 上传 0bytes/s下载,mac 上的clash是 能正常使用

节点是不是有中文！？

**Comment by CodingOX** [comment]
> 1. 应用版本
> 2. 截取日志

我刚测试了下，在我MIUI11中节点有中文，无法连接

**Comment by gyzclw** [comment]
新版本可以用
