### ISSUE TITLE
[Feature Request] 导入配置时的抗DNS污染

### ISSUE THREAD

**Issue by Olivercoco** [Kr328/ClashForAndroid#500]
**功能描述**
导入配置时会因raw.githubusercontent.com被污染，以致失败。请问clash本身有无可能实现导入配置时抗DNS污染?

**附加信息**
![photo_2020-07-09_09-14-06](https://user-images.githubusercontent.com/39828052/86985817-b99c4b00-c1c4-11ea-898d-1b09e3909354.jpg)

**Comment by seekingchan** [comment]
我也碰到这问题,我是先开其他代理软件导入

**Comment by fengz63** [comment]
> 我也碰到这问题,我是先开其他代理软件导入

同样是这个问题，有解决办法吗？这样的话我手机需要有一个额外的代理才能用clash软件。

**Comment by dawnbrave** [comment]
这个可能是clash自身的问题，windows版本也有该问题。如果软件能在联网下载规则列表时，自动启动代理模式，也许能解决这个问题。理论上是可以实现的。

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.1
