### ISSUE TITLE
[BUG] cursor window allocation of 2048kb failed

### ISSUE THREAD

**Issue by FulLiunian** [Kr328/ClashForAndroid#503]
**描述出现的错误**
cursor window allocation of 2048kb failed

**如何复现该错误**
复现步骤:
1. ...打开代理就提示

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: OPPO R9s Plus
 - 系统/ROM: Color OS
 - Android 版本 android 7.1.1
 - ROM版本 Color OS V3.2_180426_Beta

**应用信息**
 - 版本: 2.0.14
 - 安装包文件名: app-armeabi-v7a-release
app-arm64-v8a-release
 - 应用来源: Github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
# Logcat on 2020-07-10 12:41:11
12:41:13 |INFO| Android tun started
12:41:13 |INFO| Listen TCP redirect 35940
12:41:13 |INFO| Start initial compatible provider Info
12:41:13 |INFO| Start initial compatible provider fallback
12:41:13 |INFO| Start initial compatible provider auto
12:41:13 |INFO| Start initial compatible provider UPear
12:41:13 |INFO| [DNS] Main 223.5.5.5:53
12:41:13 |INFO| [DNS] Main 119.29.29.29:53
12:41:13 |INFO| [DNS] Main 1.1.1.1:53
12:41:13 |INFO| [DNS] Main 1.0.0.1:53
12:41:13 |INFO| [DNS] Fallback https://162.159.36.1/dns-query
12:41:13 |INFO| [DNS] Fallback https://162.159.46.1/dns-query
12:41:13 |INFO| [DNS] Fallback https://1.1.1.1/dns-query
12:41:13 |INFO| [DNS] Fallback https://1.0.0.1/dns-query
12:41:13 |INFO| [DNS] Fallback https://139.224.112.177/dns-query
12:41:13 |INFO| [DNS] Fallback https://162.14.13.12/dns-query
12:41:13 |INFO| HTTP proxy listening at: 127.0.0.1:7890
12:41:13 |INFO| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
12:41:13 |INFO| SOCKS proxy listening at: 127.0.0.1:7891
12:41:13 |INFO| Start initial compatible provider fallback
12:41:13 |INFO| Start initial compatible provider auto
12:41:13 |INFO| Start initial compatible provider Info
12:41:13 |INFO| Start initial compatible provider UPear
12:41:13 |INFO| [DNS] Main 223.5.5.5:53
12:41:13 |INFO| [DNS] Main 119.29.29.29:53
12:41:13 |INFO| [DNS] Main 1.1.1.1:53
12:41:13 |INFO| [DNS] Main 1.0.0.1:53
12:41:13 |INFO| [DNS] Main 192.168.123.1:53
12:41:13 |INFO| [DNS] Main 114.114.114.114:53
12:41:13 |INFO| [DNS] Fallback https://162.159.36.1/dns-query
12:41:13 |INFO| [DNS] Fallback https://162.159.46.1/dns-query
12:41:13 |INFO| [DNS] Fallback https://1.1.1.1/dns-query
12:41:13 |INFO| [DNS] Fallback https://1.0.0.1/dns-query
12:41:13 |INFO| [DNS] Fallback https://139.224.112.177/dns-query
12:41:13 |INFO| [DNS] Fallback https://162.14.13.12/dns-query
12:41:13 |INFO| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
12:41:13 |WARN| TCP Redirect receive error: accept tcp4 0.0.0.0:35940: accept4: too many open files
12:41:13 |INFO| Listen TCP redirect 45789
12:41:13 |WARN| TCP Redirect receive error: accept tcp4 0.0.0.0:45789: accept4: too many open files
12:41:13 |ERROR| Listen TCP redirect failure%!(EXTRA string=listen tcp4 0.0.0.0:0: socket: too many open files)
12:41:13 |INFO| TCP redirect exited
12:41:13 |INFO| Packet redirect exited
12:41:18 |INFO| Android tun stopped

```
<在此粘贴>
```

**Comment by Kr328** [comment]
换一台内存大的手机即可

**Comment by Hemingway2003** [comment]
设置-网络-DNS劫持-取消选择
Setting-Network-DNS Hijacking-Not Select

**Comment by Hemingway2003** [comment]
> 换一台内存大的手机即可

看报错只是需要2M的内存容量，所以应当是程序本身申请的内存过小导致的，因为clash甚至可以运行在我一台64MB运存的路由器中--当然top命令看时clash core会占用700M+内存但是不影响路由器整体运行以及clash的运行

**Comment by xuhaoyang** [comment]
@Hemingway2003 Android内存不是应用申请，是系统分配。内存小了，就那么点给你。换大一点内存手机
