### ISSUE TITLE
[BUG] 关闭自启动后被系统ui启动

### ISSUE THREAD

**Issue by knight0615** [Kr328/ClashForAndroid#504]
**描述出现的错误**
请简洁的描述你遇到的错误
miui12系统 关闭自启动后 被系统ui启动
**如何复现该错误**
复现步骤:
1. 结束进程
2. 关闭自启动
3. 查看应用行为记录
4. 被系统ui启动

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
关闭自启动后不被系统ui启动
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![Screenshot_2020-07-10-17-44-12-370_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/47374434/87141029-fd7e7580-c2d4-11ea-8fd0-045dcf4839f2.jpg)
**设备信息 (请完成以下信息):**
 - 机型: 小米10
 - 系统/ROM: MIUI 12
 - Android 版本 10
 - ROM版本 12.0.4

**应用信息**
 - 版本: [例如: 2.0.14]
 - 安装包文件名: com.github.kr328.clash
 - 应用来源:  Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
为什么不问问你的系统 UI 呢
