### ISSUE TITLE
请求支持SSR协议的服务器

### ISSUE THREAD

**Issue by VersionZKP2356** [Kr328/ClashForAndroid#506]
我有一个订阅链接，电脑版的clash已经可以支持SSR协议，但是Android版不能添加，提示SSR不受支持，望添加，谢谢

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
