### ISSUE TITLE
仅允许已选择的应用访问网络】Google Play store，Youtube无法连接网络

### ISSUE THREAD

**Issue by wa008** [Kr328/ClashForAndroid#511]
**Describe the bug**
网络模式里选择【仅允许已选择的应用】，把包含google字符的所有应用都选上，Play商店和Youtube仍然无法连接网络。网络模式选择【允许所有应用】，Play商店和Youtube可以正常连接网络。

**Screenshots**
![Screenshot_20200712-153008](https://user-images.githubusercontent.com/29834520/87241382-32193b00-c455-11ea-8d74-2d1d77970f38.jpg)

**Device Info (please complete the following information):**

 - Device: [Oneplus 7T]
 - ROM: [HOS10.0.10]
 - ROM Version:10
 - Android Version [10.0.10.HD65]

**Application Info (please complete the following information):**

 - Version: [ 2.0.15]
 - Apk File Name: [app-release-arm64-v8a.apk]
 - Distribution Channel: [Google Play]

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
