### ISSUE TITLE
[BUG] Google Play store，Youtube无法连接网络

### ISSUE THREAD

**Issue by wa008** [Kr328/ClashForAndroid#513]
**Describe the bug**
网络模式里选择【仅允许已选择的应用】，把包含google字符的所有应用都选上，Play商店和Youtube仍然无法连接网络。网络模式选择【允许所有应用】，Play商店和Youtube可以正常连接网络。

**Screenshots**
![Screenshot_20200712-153008](https://user-images.githubusercontent.com/29834520/87241382-32193b00-c455-11ea-8d74-2d1d77970f38.jpg)

**Device Info (please complete the following information):**

 - Device: Oneplus 7T
 - ROM: HOS10.0.10
 - ROM Version:10
 - Android Version 10.0.10.HD65

**Application Info (please complete the following information):**

 - Version: 2.0.15
 - Apk File Name: app-release-arm64-v8a.apk
 - Distribution Channel: Google Play

**Additional context**
先选择全局，让Youtube连接网络，再选择【仅允许已选择的应用】，Youtube可以正常连接网络。

**Comment by Kr328** [comment]
测试了**本应用**内能控制的部分 **全部正常**

其他的行为取决于 **系统** 和 **应用本身** 

**本应用** 无法控制

**Comment by wa008** [comment]
> 测试了**本应用**内能控制的部分 **全部正常**
> 
> 其他的行为取决于 **系统** 和 **应用本身**
> 
> **本应用** 无法控制

明白，多谢啦

**Comment by laggardkernel** [comment]
我也出现了。好像是 "Access Control Mode" 问题，我用的是黑名单 "Denty selected apps" 模式，开关一次（切换到 All 再切回来）就好了。还没明白如何复现这个 bug。
