### ISSUE TITLE
[BUG] 最新版本闪退！

### ISSUE THREAD

**Issue by ding667** [Kr328/ClashForAndroid#516]
**描述出现的错误**
最新版本闪退

**如何复现该错误**
复现步骤:
1. 安装频道推送的最新版
2. ...
3. ...
4. ...

**预期行为**
打开主页面

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 华为nova青春版
 - 系统/ROM: emui 5
 - Android 版本 7
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: 最新版…
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.0.16
