### ISSUE TITLE
[BUG] 2.0.16 版本闪退

### ISSUE THREAD

**Issue by kinfables** [Kr328/ClashForAndroid#517]
**描述出现的错误**
更新 2.0.16 版本后出现闪退。

**设备信息 (请完成以下信息):**
 - 机型: [OPPO K3]
 - 系统/ROM: [ColorOS 7]
 - Android 版本 [10]
 - ROM版本 [4.9.186]

**应用信息**
 - 版本: [2.0.16]
 - 安装包文件名: [app-release-arm64-v8a.apk]
 - 应用来源: [Github Release]

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.0.16
