### ISSUE TITLE
[功能增加] 希望捐赠功能里添加其他捐赠渠道

### ISSUE THREAD

**Issue by iliuyuyang** [Kr328/ClashForAndroid#518]
很喜欢该应用，想对开发者进行捐赠以感谢作者的付出，发现现在捐赠里面只有TG链接，因为本人不使用TG也不会为这去下载TG，所以希望作者添加使用Paypal、信用卡之类的捐赠渠道。

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
