### ISSUE TITLE
自定义DNS[Feature Request] 

### ISSUE THREAD

**Issue by ding667** [Kr328/ClashForAndroid#521]
**功能描述**
dns自定义

**描述你希望的实现方式**
设置，网络，这里可以把那几个开关改一下

**附加信息**
dns自定义可以顺便过滤一下广告

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
