### ISSUE TITLE
[Feature Request] 自定义DNS

### ISSUE THREAD

**Issue by ding667** [Kr328/ClashForAndroid#522]
**功能描述**
请清晰的描述你想要的功能
dns自定义
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
设置中强制覆盖系统dns等开关可以用自定义dns选项替代
**附加信息**
其他的与改功能相关的附加信息
这样可以避免一下污染问题(?)，另外也可以用这种方式去广告。

**Comment by Kr328** [comment]
@ding667 你既然有这个需求 为什么不能自己编辑配置文件呢

**Comment by ding667** [comment]
啊？可以吗？

**Comment by ding667** [comment]
配置文件链接由机场提供…我也找不到怎么把它导出…

**Comment by Kr328** [comment]
@ding667 复制一份就是本地文件了

**Comment by ding667** [comment]
好的，我试试。谢谢
