### ISSUE TITLE
[BUG] 任一模式使用Google助理和智能镜头均有无法连接到网络的情况

### ISSUE THREAD

**Issue by YuukiHibiki** [Kr328/ClashForAndroid#524]
**描述出现的错误**
google助理会提示暂时无法连接到google，智能镜头会提示暂时无法读取图像

**如何复现该错误**
复现步骤:
1. 使用仅选择应用模式
2. 使用全局代理\规则代理
3. 使用全应用匹配模式
4. 均会出现上述问题

**预期行为**
v2ray不会出现此问题

**设备信息 (请完成以下信息):**
机型: [OnePlus 5T(ONEPLUS A5010)]
系统/ROM: [H2OS]
Android 版本 [10]
ROM版本 [20.05.19]

**应用信息**
版本: [2.0.16以前的版本也有同样的问题]
安装包文件名: [-arm64-v8a]
应用来源: [Google Play]

**日志**
[googlebug.log.txt](https://github.com/Kr328/ClashForAndroid/files/4924513/googlebug.log.txt)
这是单一应用匹配时全局模式的日志，这个日志的时间段里智能镜头出现了连接不上的问题

**Comment by Kr328** [comment]
不使用 访问控制 呢

**Comment by MinaseInori233** [comment]
> 不使用 访问控制 呢

[智能镜头出现连接故障，点重试后ok.log.txt](https://github.com/Kr328/ClashForAndroid/files/4924554/ok.log.txt)
[google助理出现暂时连接不上问题.log.txt](https://github.com/Kr328/ClashForAndroid/files/4924557/google.log.txt)

google助理在cfa开启时表现为读取我的语音需要很长的响应时间然后直接提示暂时无法连接
v2ray则可以很快响应我的语音，尽管它会听错，但它一定会马上显示结果

**Comment by Kr328** [comment]
@MinaseInori233 DNS 覆盖打开了吗

**Comment by MinaseInori233** [comment]
> @MinaseInori233 DNS 覆盖打开了吗

关闭和打开均有此问题

**Comment by MinaseInori233** [comment]
应该也不是我的配置文件的问题，我使用了机场自带的clashyml也会有这种情况

**Comment by MinaseInori233** [comment]
> @MinaseInori233 DNS 覆盖打开了吗

2.0.17版本google助理使用正常，google镜头依然存在上述问题

**Comment by douglarek** [comment]
Google 服务非常的神奇，莫名的链接不上，而此时打开 TG 却无问题

**Comment by KhaosChow** [comment]
也有此情况，不知道是软件问题还是谷歌问题。
