### ISSUE TITLE
[BUG] load-balance能读取到但无法实际使用？

### ISSUE THREAD

**Issue by baraja** [Kr328/ClashForAndroid#525]
我的配置如下
  - name: LB
    proxies:
      - TJ_US1
      - TJ_US2
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 600

应用主界面显示了LB，但无法选中
请问是功能还没有实现吗？

**Comment by NevadaCities** [comment]
@baraja Loadbalance不需要手动选择节点

**Comment by Kr328** [comment]
LoadBalance 都 选中了 还 做个 ** 的 负载均衡

**Comment by NevadaCities** [comment]
@Kr328 精辟

**Comment by baraja** [comment]
现在的问题是我只能选proxy下面的某个节点
LB虽然在最上方和Proxy并列显示，但并不能点选
我要如何才能使用LB呢？

**Comment by baraja** [comment]
大佬，我知道load balance怎么用了，就是name必须是Proxy，而不能自定义为LB
这个跟cfw逻辑有点不太一样，cfw是既可以点选Proxy里面的节点，也可以点选自定义负载均衡列表。
我觉得cfa是不是也应该考虑一下这种场景：也就是我并不想把我所有的节点都加到负载均衡里
Proxy和LB应该都可以点击，现在这样LB显示在界面上却不能使用（只能使用Proxy）还是挺困惑的

**Comment by Kr328** [comment]
@baraja 我佛了 

LoadBalance 就没有任何一个 正在使用的服务器 选择有什么意义

**Comment by NevadaCities** [comment]
@baraja name参数是可以自定义的。

**Comment by Kr328** [comment]
@Kr328 以及 Clash 核心 根本没有 相关 的 可选择的操作

**Comment by NevadaCities** [comment]
@baraja 你自己维基百科负载均衡到底是干啥的

**Comment by baraja** [comment]
两位大佬，是我的问题，后来才发现使用上跟cfw逻辑上是一致的，选全局模式就可以既能选节点也能选负载均衡了。此问题终结
