### ISSUE TITLE
[Feature Request]希望可以增加允许局域网连接的开关功能

### ISSUE THREAD

**Issue by qysjames** [Kr328/ClashForAndroid#526]
**功能描述**
希望可以增加允许局域网连接的开关功能

**描述你希望的实现方式**
ClashA有这个功能，希望可以加入这个功能，不然只能自己手机用，无法共享，希望可以和电脑端一样有这个功能，并且可以自定义代理端口
![2648209155](https://user-images.githubusercontent.com/26586130/87743404-6e64e680-c81b-11ea-97a9-8d544430d2ac.png)

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
自行修改配置文件
