### ISSUE TITLE
[Feature Request] 请求加入 SSID Suspend 功能

### ISSUE THREAD

**Issue by isXiaoLin** [Kr328/ClashForAndroid#529]
**功能描述**
参照 Surge, 可以在检测到指定 SSID 后自动断开连接, 防止在路由器上部署透明代理的用户套娃代理
以及对应的离开 SSID / 断开 WiFi 后自动连接
附: [Surge Changelog](https://manual.nssurge.com/release-note/surge-mac.html#ssid-suspend)

**描述你希望的实现方式**
[Stackoverflow](https://stackoverflow.com/questions/3119607/how-to-be-notified-on-wifi-network-status-change)
> Register a BroadcastReceiver for ConnectivityManager.CONNECTIVITY_ACTION. In the onReceive handler you can call NetworkInfo info = (NetworkInfo) intent.getParcelableExtra(ConnectivityManager.EXTRA_NETWORK_INFO) and then info.getType() and check for ConnectivityManager.TYPE_WIFI and do what you want then. :)

**附加信息**
应该是个很实用的功能, 希望可以添加相关选项

**Comment by EKyero** [comment]
https://github.com/Kr328/ClashForAndroid/issues/37
