### ISSUE TITLE
[BUG] 2.0.17版广告过滤有问题

### ISSUE THREAD

**Issue by xianren78** [Kr328/ClashForAndroid#531]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
以前所有版本广告过滤都没问题的，这个版本不能过滤了。app举例  留览器 下面的广告横幅

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]  s20+
 - 系统/ROM: [例如: MIUI 11]  oneui2
 - Android 版本 [例如: 10]  10
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]2.0.17
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
那么大的日志写在那里 为什么就不填呢

**Comment by xianren78** [comment]
> 那么大的日志写在那里 为什么就不填呢

日志截图可见，没有广告域名匹配，全部转换成ip匹配的
![2.0.17](https://user-images.githubusercontent.com/26913311/87893146-93eb2d80-ca71-11ea-938c-c3fc56b2d4f6.png)
![2.0.16](https://user-images.githubusercontent.com/26913311/87893153-96e61e00-ca71-11ea-9a59-3357d1486868.png)

**Comment by Kr328** [comment]
自己 关掉 DNS 覆盖 修改配置文件 DNS 到 fake ip 模式 吧

**Comment by xianren78** [comment]
> 自己 关掉 DNS 覆盖 修改配置文件 DNS 到 fake ip 模式 吧

2.0.17关掉DNS覆盖，配置文件改用fake-ip，在youtube 客户端上表现也和2.0.16不一样。2.0.16，连接googlevideo.com用的是TCP；2.0.17则用UDP。UDP明显Qos厉害，速度起不来

**Comment by Kr328** [comment]
Youtube 问题你得去问 Google

redir-host 丢映射是上游的问题

**Comment by xianren78** [comment]
> Youtube 问题你得去问 Google
> 
> redir-host 丢映射是上游的问题

限于知识面问题，无法理解fake-ip和redir-host模式直接的区别。你说的意思是我应该在VPS上限制youtube的QUIC链接，强制走TCP吧？

**Comment by Kr328** [comment]
@xianren78 直接在 proxies 里 udp: false 就行了

**Comment by xianren78** [comment]
2.0.18解决了这个问题。
