### ISSUE TITLE
[BUG] 最新的2.0.17版本无法导入规则

### ISSUE THREAD

**Issue by MinaseInori233** [Kr328/ClashForAndroid#533]
**描述出现的错误**
CFW以及2.0.16确定可用的规则,CFA无法导入，详情日志

**如何复现该错误**
复现步骤:
开启/关闭代理均无法正常导入规则

**预期行为**
2.0.16和CFW可以正常使用的配置文件

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
机型: [OnePlus 5T(ONEPLUS A5010)]
系统/ROM: [H2OS]
Android 版本 [10]
ROM版本 [20.05.19]

**应用信息**
版本: [2.0.16以前的版本也有同样的问题]
安装包文件名: [-arm64-v8a]
应用来源: [Google Play]

**附加信息**
全部域名被导入到GEOIP和FINAL

**配置文件**
[配置文件.txt](https://github.com/Kr328/ClashForAndroid/files/4945178/default.txt)

**日志**
[无法导入规则.log.txt](https://github.com/Kr328/ClashForAndroid/files/4945181/log.txt)

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/531#issuecomment-660780205
