### ISSUE TITLE
[Feature Request] 请求将通知栏中显示的配置文件名改为显示节点名

### ISSUE THREAD

**Issue by akw5454521** [Kr328/ClashForAndroid#536]
**功能描述**
目前下拉通知栏中第二行是黑色字体的配置文件名称，请求改为当前使用的节点名称，或者在选项中可自行选择显示配置名or节点名

**描述你希望的实现方式**
修改相关字段

**附加信息**
因为很多人应该都是只有一个配置文件，里面很多节点，所以在通知栏显示实际连接哪个节点应该作用更大，例如节点组选择的是“测试延迟自动选最快”那个节点组，连的节点可能随时变化，那么用户不点进软件是没法知道当前用的哪个节点的，如果能在通知栏显示的话就很方便了。
我有找到之前的 #138 和 #140，感觉开发者可能跟issue的人没想到一块去，因此我详细说明一下请求，希望开发者能考虑下～～

**Comment by Kr328** [comment]
说了不止一万遍

** Clash 不是单节点应用**

根据 **规则** 选择 **不同的代理组** 再 **选择目标节点**

没有任何节点是 **正在使用** 或者说 **所有节点都在使用**

通知栏无法放下全部的代理组
