### ISSUE TITLE
[Feature Request] GooglePlay该同步Release更新了

### ISSUE THREAD

**Issue by isoraforever** [Kr328/ClashForAndroid#537]
**功能描述**
请清晰的描述你想要的功能

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by xuhaoyang** [comment]
别没事无事，发这种无意义issue，来浪费开发者精力。

**Comment by isoraforever** [comment]
意义就是提醒他更新可能他忙忘了 他能做出这么棒的app我比你更爱他
