### ISSUE TITLE
[BUG] 2.0.18 clash启动失败，Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by GrayXu** [Kr328/ClashForAndroid#539]
**描述出现的错误**
启动失败，详情提示`Cursor window allocation of 2048 kb failed`。
已经尝试重新下载、清除数据等重置方法，无效。也尝试了重启。

**如何复现该错误**
复现步骤:
1. 配置内添加新配置，可以正常添加。
2. 点击启动代理，提示启动失败。

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: LG G7
 - 系统/ROM: G710ULM11g
 - Android 版本 8.0
 - ROM版本 G710ULM11g

**应用信息**
 - 版本: 2.0.18
 - 安装包文件名: app-arm64-v8a-release
 - 应用来源: github releases

**Comment by Kr328** [comment]
#503

**Comment by GrayXu** [comment]
但回滚到2.0.14版本上，是正常工作的…

**Comment by Kr328** [comment]
@GrayXu 这就得问你的 ROM 了 这个异常 是 ROM 的 API 抛 

Google 的 封装

近期唯一有关的操作 就是 更新了 来自 Google 的 封装

你可以去问问 Google 的 叫 jetpack room 的 东西

**Comment by GrayXu** [comment]
> @GrayXu 这就得问你的 ROM 了 这个异常 是 ROM 的 API 抛
> 
> Google 的 封装
> 
> 近期唯一有关的操作 就是 更新了 来自 Google 的 封装
> 
> 你可以去问问 Google 的 叫 jetpack room 的 东西

好吧，谢谢！
