### ISSUE TITLE
通知横幅里面应用图标没有眼睛和嘴巴

### ISSUE THREAD

**Issue by YanpengHuang** [Kr328/ClashForAndroid#54]
Feedback ID: bca8b2e720ca88d38cca85498f55516c

通知横幅里面应用图标没有眼睛和嘴巴.

![photo_2019-12-21_14-54-33](https://user-images.githubusercontent.com/50351345/71304445-d0827800-2401-11ea-99b7-0ed7b24f3eb9.jpg)

**Comment by Kr328** [comment]
预期行为
