### ISSUE TITLE
[BUG] 内建dns打不开某些网站

### ISSUE THREAD

**Issue by Oaken-baiyu** [Kr328/ClashForAndroid#541]
**描述出现的错误**
我使用的机场并没有封锁大纪元这类网站，发现只要打开dns配置覆盖就无法访问，关闭后使用配置文件里的dns就可以，我虽然不看这种网站只是偶然发现的，但是还是不太舒服，cfa不会在搞自我审查吧

**屏幕截图**
![Screenshot_20200725_091633](https://user-images.githubusercontent.com/63627139/88445966-db4e3100-ce58-11ea-860f-3e4bfcc5f270.jpg)
![Screenshot_20200725_091720](https://user-images.githubusercontent.com/63627139/88445970-e2753f00-ce58-11ea-8bd6-adde49f2a264.jpg)

**应用信息**
 - 版本: 2.0.18
 - 安装包文件名:
 - 应用来源: GitHub

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
打不开就自己配置 决定权又不在我手里
