### ISSUE TITLE
[BUG] 访问控制应用包列表无法检索到某个应用

### ISSUE THREAD

**Issue by Xm798** [Kr328/ClashForAndroid#542]
**描述出现的错误**
访问控制应用包列表无法检索到已经安装的应用，目前发现com.google.android.apps.hangoutsdialer（环聊拨号器）无法被检索。未开启系统应用过滤功能。

**预期行为**
应当能够正常检索所有已经安装的应用。

**屏幕截图**
![应用信息com.google.android.apps.hangoutsdialer](https://img.vvzero.com/ih/2020/07/27/35855dc91ad12.jpg)
![包名检索com.google.android.apps.hangoutsdialer](https://img.vvzero.com/ih/2020/07/27/d9e5e30dba2c9.jpg)
![包名关键字检索hangoutsdialer](https://img.vvzero.com/ih/2020/07/27/7622deb1409a3.jpg)
![应用名称检索](https://img.vvzero.com/ih/2020/07/27/d0b0a888ef06c.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Mi 10 Pro
 - 系统/ROM: MIUI 12
 - Android 版本: 11
 - ROM版本: 20.6.18

**应用信息**
 - 版本: v2.0.18
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: [Github Releases](https://github.com/Kr328/ClashForAndroid/releases/tag/v2.0.18)

**Comment by Kr328** [comment]
@Xm798 如果应用没有请求网络权限 是不会显示在列表里的
