### ISSUE TITLE
[Feature Request] 建议从"已停止"切换到”运行中“时，自动更新”配置“

### ISSUE THREAD

**Issue by FrontendStack** [Kr328/ClashForAndroid#546]
**功能描述**
建议从"已停止"切换到”运行中“时，自动更新”配置“。每次手动更新比较麻烦。

**描述你希望的实现方式**
从"已停止"切换到”运行中“时，自动更新”配置“

**Comment by EKyero** [comment]
@FrontendStack 为什么不设置自动更新?

**Comment by Kr328** [comment]
不做 麻烦

自动更新已经足够了 再设计这个完全没有必要
