### ISSUE TITLE
[Feature Request] 支持安卓5.0-6.0(很多安卓电视的操作系统)

### ISSUE THREAD

**Issue by ubertao** [Kr328/ClashForAndroid#552]
**功能描述**
能够对支持多数安卓电视还在运行的安卓5.0-6.0操作系统，解决安装时显示无法解析安装包的错误。

**描述你希望的实现方式**
* 必要：将App所支持的操作系统版本降低为5.0 (API 21)
* 可选：UI针对电视屏幕和遥控器控制方式进行适当优化

**附加信息**
* 低版本中不支持的`java.util.stream.*`和`java.util.concurrent.*`功能可以采用某个backports解决，如：`https://github.com/SgtSilvio/android-retrofix`
* 安卓SDK中低版本不支持的功能，可使用各`*Compat`类替代，或者自行包装为向后兼容的代码

**参考实现**

参见这里：https://github.com/Kr328/ClashForAndroid/commit/94eb882c8e931067d470bf28cb16ffb1ea46c9f5
由于现在项目闭源了，也没法提交PR。
只能针对闭源之前的1.3.2版本代码尝试修改了以下，大约100行代码，不一定完整，但影响大致可行。

**Comment by Kr328** [comment]
不做

即使技术上在当前版本可行 我也不想为一个在 5 年前发布的系统 维护兼容代码

会带来很多的维护成本 未来开发各种新功能 得额外考虑兼容性问题 束手束脚

顺带一提 即使是 Android 7.0 以上的 Android TV 也有很多 VPN 组件丢失问题

在 AppCenter 的 错误统计 中 出现 VPN 启动失败 的 最多的 ROM 类型 就是 Android TV

**Comment by xuhaoyang** [comment]
@ubertao 拿ClashA换core不好吗 斜眼

**Comment by ubertao** [comment]
ClashA也不维护了吧？

**Comment by xuhaoyang** [comment]
@ubertao 不维护的系统加不维护的app，不正好么 斜眼

**Comment by Teraflopst** [comment]
这个情况还是自己去折腾路由器吧，支持作者不要浪费精力去做这个

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.1
