### ISSUE TITLE
[BUG] 多维网等几个时政类网站无法访问，难道有个小墙？

### ISSUE THREAD

**Issue by libertypi** [Kr328/ClashForAndroid#554]
**描述出现的错误**
发现多维网（dwnews.com）以及几个时政类网站（例如轮子的），无法通过ClashForAndroid访问。连接立刻显示拒绝访问。同样的节点，用电脑ClashForWindows就可以访问了。换节点无效，修改DNS配置无效。版本是最新的2.0.18，Google Pixel Android 10。请各位测试是否可以复现。如果需要我再贴上log。
使用这类软件，当然是为了拿回自己控制信息的权利，不需要别人来规定什么该看什么不该看。希望只是个Bug。

**如何复现该错误**
复现步骤:
1. 打开ClashForAndroid
2. Chrome访问多维网（或几个时政类网站）
3. 立刻显示拒绝连接
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
默认的 DNS 里包含 rixcloud 的 DNS over https

这个 DNS 用于对抗 DNS 污染 同时 会污染一些政治敏感的网站以规避一些 "可能存在的不可抗压力"

你可以 **关掉 DNS 覆盖** 然后通过自定义 DNS 解决

**Comment by libertypi** [comment]
既然如此，那还是希望作者考虑取消把这个作为默认DNS。不在于要访问这些网站，而是和使用这类软件的初衷矛盾了。

**Comment by Kr328** [comment]
@libertypi 你认为除了这个 DNS 外 还有体验更好的 DNS 吗

我设计这个 App 从来都是为了学习技术 而不是 使用键盘 尝试将自己的观点输入别人的脑袋

**Comment by Kr328** [comment]
@libertypi 不加这个 DNS 很大概率连 www.google.com 都无法正常访问 你认为这个值得吗

这里已经提供选项让有这个小众需求的人自定义了

**Comment by AkariiinMKII** [comment]
@libertypi 优先保证技术上的可用性并没有问题，不爽建议自己写

**Comment by libertypi** [comment]
那么严重的吗，旧版本和其他平台的Clash好像没这类问题呀。

**Comment by libertypi** [comment]
谢谢作者解答。原来如此。
我修改配置文件为redir-host，似乎还可以。按我的理解，redir-host的dns查询不也是走代理分流的吗，那么配置一个国内dns，一个国外dns（就算普通53端口），并发查询，似乎就已经解决了污染问题？

**Comment by hardy-one** [comment]
@libertypi dns不走代理

**Comment by Kr328** [comment]
@libertypi Clash 的 DNS 流量 均不通过代理

**Comment by libertypi** [comment]
好吧，可能google返回0.0.0.0这种流氓手段我还没遇到过，所以一直用redir-host都没遇到问题

**Comment by akw5454521** [comment]
RixCloud是著名的爱国机场，可以看看他家的 ToS，访问这类网站就不要开内置DNS了，因为他能知道你的浏览记录

**Comment by libertypi** [comment]
> RixCloud是著名的爱国机场，可以看看他家的 ToS，访问这类网站就不要开内置DNS了，因为他能知道你的浏览记录

的确，有时候安全比便利更重要。既然一个dns能设置小墙，难免怀疑会不会干别的。也挺搞笑的，如果这些机场东窗事发，难道会因为屏蔽了几个“反动网站”减刑吗？

**Comment by xuhaoyang** [comment]
主动屏蔽可以少掉很多麻烦。也是过滤的一种手段。

**Comment by Kr328** [comment]
@libertypi 按照 Clash 的 策略 假设已经到了使用 RixCloud 的 DNS 的时候 
也一定会同时使用 未加密的 主 DNS 
也就是说 运营商更懂你在访问什么

**Comment by H4M5TER** [comment]
@Kr328 你好，我想了解一下：

1. 上文提到 fake-ip 模式存在的问题是怎么产生的
2. redir-host 模式为什么需要抗污染的 DNS（或者说 fake-ip 模式为什么能抗污染）
3. 只有规则里没有匹配到 Proxy 的域名才会走 DNS，是这样的吗？

我看了[这个文档](https://lancellc.gitbook.io/clash/clash-config-file/dns#enhanced-mode)，不过还是没有搞明白。

**Comment by Kr328** [comment]
@H4M5TER 1. 不知道 实践得知的 自己阅读相关 Issue
2. 认真读上文了吗 redir-host 能解决 0.0.0.0 污染问题吗 (fake-ip 压根就不返回真正应该解析出来的 IP 会污染吗
3. 不是 DNS 可能发生在规则匹配以及 DNS 服务透传

**Comment by happyeddie** [comment]
@Kr328 非常感谢提供了如此优秀的软件，我不是很懂网络，但是也说一下我的情况和想法，看有没有参考价值：

1. 用 Shadowsocks 等软件，下载 Google Play 基本没有障碍，但是用 Clash 会经常 Pending，所以我觉得 Clash 还有值得改进地方
2. 我的家庭网络，在网关做了规则处理，下载 Google Play 无障碍，做法是通过 gfwlist，生成 dnsmasq.conf，指定这些域名的 DNS 解析到内网的 NameServer，而这个 NameServer 转发了流量到 8.8.8.8 来解析 IP，这样是不是就实现了无污染的 DNS？

以上，仅供参考，非常感谢

**Comment by Longway22** [comment]
> 会污染一些政治敏感的网站以规避一些 "可能存在的不可抗压力"

压力就是共产党罢，觉得把时政类网站屏蔽了可以减刑？

> 我设计这个 App 从来都是为了学习技术 而不是 使用键盘 尝试将自己的观点输入别人的脑袋
