### ISSUE TITLE
[BUG] 暗黑模式下，文字标签前的小图标与背景溶在一起，看不见了。

### ISSUE THREAD

**Issue by Shangbaize-Daoye** [Kr328/ClashForAndroid#558]
![image](https://user-images.githubusercontent.com/9370822/89113861-c8ff7300-d4a8-11ea-8938-7df208bdc89f.png)
![image](https://user-images.githubusercontent.com/9370822/89113864-cef55400-d4a8-11ea-8c9f-117ef77d5436.png)

第一张图是dark mode下的，第二张图是light mode下的。

希望能将dark mode里文字标签前的小图标可视化。

**Comment by Shangbaize-Daoye** [comment]
系统是MIUI 12

**Comment by hardy-one** [comment]
@Shangbaize-Daoye 这是MIUI强制深色功能的bug，和cfa无关

**Comment by Shangbaize-Daoye** [comment]
关掉MIUI的dark mode确实解决了，不过我一般是开着系统的dark mode的。。。算了，反正平时也不怎么用CFA的UI，一个toggle按钮就完事了。

**Comment by hardy-one** [comment]
@Shangbaize-Daoye MIUI深色模式有各应用的单独开关

**Comment by Shangbaize-Daoye** [comment]
啊，我找到了，多谢！

**Comment by Shangbaize-Daoye** [comment]
已找到解决方案，关闭此issue。解决方案为：当MIUI 12中系统dark mode开启时，需要在settings里dark mode设置中将individual apps（三方应用）里的CFA单独关闭。并在CFA自己的设置中将主题选择成dark mode。

**Comment by ZerOri** [comment]
> 已找到解决方案，关闭此issue。解决方案为：当MIUI 12中系统dark mode开启时，需要在settings里dark mode设置中将individual apps（三方应用）里的CFA单独关闭。并在CFA自己的设置中将主题选择成dark mode。

原来如此，还以为是app没做好，已解决，谢谢。
