### ISSUE TITLE
[Feature Request] 能不能让更新配置 也支持使用系统dns?

### ISSUE THREAD

**Issue by fcying** [Kr328/ClashForAndroid#559]
**功能描述**
设置->网络里面已经设置 追加系统DNS.
因为配置是存在内网的NAS上的, 在内网访问的时候如果是系统的DNS, 会自动转成内网的IP.
现在在内网点更新配置的时候, 访问的是外网的IP(光猫没有nat回流功能, 直接访问IP 无法连接), 所以一直更新失败.

**描述你希望的实现方式**
使用追加系统DNS后, 更新配置 的时候也可以用系统DNS.

**Comment by Kr328** [comment]
不能

现在更新配置流量会经过 clash 出口处只能使用 clash 的 DNS
