### ISSUE TITLE
会考虑支持SSR协议吗？

### ISSUE THREAD

**Issue by qqice233** [Kr328/ClashForAndroid#56]
如果以[clashr](https://github.com/frainzy1477/clashrdev) 为核心代替clash原版核心的话是否可以实现ssr协议的支持？会考虑做这样的分支嘛…？

**Comment by Kr328** [comment]
**不能 **

现在的 Clash for Android 与 上游 Clash 高度耦合
不能通过简单替换实现

并且

Clash 上游作者 能够为 Clash for Android 提供私有特性
包括 但 不限于
1. 基于系统协议栈实现的 tun
2. 非 GPL 的 允许闭源 的 独立授权协议

能够支持 SSR 的 唯一方式 只有 
**说服 上游 Clash 开发者 合并入 主分支**
