### ISSUE TITLE
[Feature Request] 可以实现各分组折叠吗？

### ISSUE THREAD

**Issue by Moriarty-989** [Kr328/ClashForAndroid#561]
**功能描述**
各分组可进行折叠吗，我个人写的配置分组多，在PC上使用，分组可折叠，没明显问题，改哪个组就拉倒哪个组把折叠打开，到手机上，全部分组全自动打开，并且不可折叠，往往浏览和修改时，需要拉很长才能找到我想改的部分

**描述你希望的实现方式**
类似CFW那种分组折叠

**附加信息**
无，只要分组可折叠就可以了，谢谢了

**Comment by Kr328** [comment]
#21
