### ISSUE TITLE
[BUG] 关于Vmess的UDP规则匹配和SS/Trojan不同的疑问

### ISSUE THREAD

**Issue by akw5454521** [Kr328/ClashForAndroid#562]
**描述出现的错误**

之前在用Trojan线路时查看日志，发现Youtube app的UDP连接会走直连，然后查找了issue里的 #491 和 #408 后，在规则里加了true后已经正常。然后我改用ss和vmess(tcp)线路想看看是否也是这样，结果发现还不一样

**如何复现该错误**
复现步骤:
1. ss线路，不做udp备注或者备注为false时，UDP会直连
2. ss线路，udp备注为true时，UDP会正常匹配规则走代理
3. vmess线路，不做udp备注或者备注为false时，UDP会正常匹配规则走代理
4. vmess线路，udp备注为true时，UDP会正常匹配规则走代理

**预期行为**

看起来ss和trojan是一样的，需要备注true才正常，而vmess则无论udp备注是啥都会正常匹配域名规则。这个不算bug也不是什么严重的情况啦，就是想确认下这个是不是预期行为？比如vmess协议有什么特殊的udp实现之类的？

除此之外还想问一下有无方法阻止udp连接(除dns相关)啊？我本以为备注false就是直接不会建立udp连接的，结果还不是。因为我ss和vmess线路的服务商号称是不支持udp连接的，虽然日志里看起来走代理的连接正常，但我猜日志里只是传出连接吧，推测udp连接发给服务端后会被拒绝，造成了资源的浪费，不过这也许是上游的问题？

**屏幕截图**
NA

**设备信息 (请完成以下信息):**
NA

**应用信息**
 - 版本: 2.0.16
 - 安装包文件名: arm64-v8a版的
 - 应用来源: 本仓库

**附加信息**
NA

**配置文件**
上面描述了就不贴了

**日志**
上面描述了就不贴了

**Comment by Kr328** [comment]
与 Clash for Android 无关

去上游反馈
