### ISSUE TITLE
[BUG] 无法成功代理连网

### ISSUE THREAD

**Issue by sniperhalo** [Kr328/ClashForAndroid#566]
**描述出现的错误**
在代理服务器正常的情况下，每次启动都出现无法连接服务器，只有to auto 自动模式能连接

**如何复现该错误**
复现步骤:
1. 上次关闭app几分钟后
2. 上次关闭app几分钟后
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**设备信息 (请完成以下信息):**
 - 机型: 魅族16x
 - 系统/ROM: flyme
 - Android 版本8.1.0
 - ROM版本 8.1.5.0a

**应用信息**
 - 版本: 2.0.18
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: github

**Comment by Kr328** [comment]
你这关键的东西一律不填

是等着通灵吗
