### ISSUE TITLE
[BUG] ipv6网站的dns解析问题

### ISSUE THREAD

**Issue by shenwei101623** [Kr328/ClashForAndroid#567]
**描述出现的错误**
cfa无法上纯ipv6网站，相同节点同一局域网，cfw可以

**如何复现该错误**
复现步骤:
1. 拥有一个可以访问ipv6的节点A
2. cfa连接A
3. 浏览器访问bt.byr.cn
4. 错误：无法访问此网站，找不到服务器的IP地址，DNS_PROBE_FINISHED_NXDOMAIN

**应用信息**
 - 版本: 2.0.18-ARM64-V8A
 - 应用来源: Google Play

**Comment by Kr328** [comment]
这个问题存在 但是是上游问题

**Comment by Kr328** [comment]
@Kr328 你可以自己改写 dns 更换 fake-ip 模式

**Comment by shenwei101623** [comment]
ok，感谢
