### ISSUE TITLE
[Feature Request] Clash Premium已经支持了ssr协议，但最新的clash for android还不能用

### ISSUE THREAD

**Issue by tothemoon96** [Kr328/ClashForAndroid#568]
**功能描述**
Clash Premium已经支持了ssr协议，但最新的clash for android还不能用
**描述你希望的实现方式**
实现Clash Premium的ssr协议

**附加信息**
其他的与改功能相关的附加信息

**Comment by EKyero** [comment]
https://github.com/Kr328/ClashForAndroid/issues/538
