### ISSUE TITLE
[BUG] ehviewer某些本永远网络连接失败或者509

### ISSUE THREAD

**Issue by 148278001** [Kr328/ClashForAndroid#570]
如题，同时间同节点，下a本网络连接失败509，b本可以正常下载游览，而且a本好像是永久性的无法下载，过了好几天也一样。试着换了Trojan Igniter等，同一节点可以正常下载。

**如何复现该错误*
不清楚有无共通性，我进的exh，[おぶせっしょん! (ひょうが。)] 乱れる焔に 貫く白銀 [中国翻訳] [DL版]这本就无法下载，无下载速度，过段时间提示下载失败，点开页面显示网络连接失败或509

**设备信息 (请完成以下信息):**
 - 机型: 索尼 Xperia 1
 - 系统/ROM: [安卓10]
 - Android 版本 [10]

**应用信息**
 - 版本: [2.0.18，谷歌商店最新]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
要么把信息填全 要么把手机寄给我

**Comment by NevadaCities** [comment]
@148278001 50包邮解君愁

**Comment by AkariiinMKII** [comment]
![Screenshot_20200811-193733.png](https://user-images.githubusercontent.com/6019344/89893048-4003dc80-dc0a-11ea-948b-29e1701f5478.png)自查节点规则

**Comment by 148278001** [comment]
日志捕捉开了后是一片空白……开关节点显示
# Logcat on 2020-08-11 19:21:57
19:22:05 |INFO| Android tun started
19:22:05 |INFO| Listen TCP redirect 41859
19:22:05 |WARN| Patch deprecated proxies
19:22:05 |WARN| Patch deprecated proxy groups
19:22:05 |WARN| Patch deprecated rules
19:22:05 |INFO| Start initial compatible provider Auto
搞了半天想起新版本提示过时配置文件，我是Trojan，这问题也是版本提示后开始出现的。试了几个版本回退到1.2后居然正常了…

**Comment by Kr328** [comment]
@148278001 你这配置 下版本不让用了 都提示过时了 还不改吗

**Comment by xuhaoyang** [comment]
@148278001

**Comment by 148278001** [comment]
> @148278001 你这配置 下版本不让用了 都提示过时了 还不改吗

自己的到期了…犯懒找机场，机场直接给ClashX 配置，用了大半年其他应用都正常就没在意…刚换回最新版找朋友借了v2试一圈ehv都ok，就我那Trojan不行。干脆先挂路由器上用了，谢谢各位大佬…脑子一时没转过来
