### ISSUE TITLE
[BUG] Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by callzhang** [Kr328/ClashForAndroid#572]
**描述出现的错误**
点击启动后无法开启应用

**如何复现该错误**
复现步骤:
1. 点击启动
2. ...
3. ...
4. ...

**预期行为**
开启

**屏幕截图**
![Screenshot_2020-08-15-01-10-44-483_com github kr328 clash](https://user-images.githubusercontent.com/5102827/90275398-d0555200-de94-11ea-8acc-a984dd53699f.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米平板4 Pro
 - 系统/ROM: MIUI 10
 - Android 版本 9
 - ROM版本 10.9.8.29

**应用信息**
 - 版本: 2.0.18
 - 安装包文件名: 
 - 应用来源: Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
[xx.yaml.txt](https://github.com/Kr328/ClashForAndroid/files/5075997/xx.yaml.txt)

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
#503
