### ISSUE TITLE
[Feature Request] 允许该程序成为一个Proxy Server通过本地端口让例如Proxy SwitchyOmega连接

### ISSUE THREAD

**Issue by stars-island** [Kr328/ClashForAndroid#573]
**功能描述**
举个例子，Chrome 浏览器插件 Proxy SwitchyOmega 可以通过本地端口连接 Clash for Windows，从而选择哪些直接走，哪些绕着走。还有 KiwiBrowser 也可以这样做。

**描述你希望的实现方式**
软件有个允许，让 ProxySwitchyOmega 通过本地端口可以连得上。我不是学计算机的，不太懂原理，感觉是这样……如果我讲得不明白，还请您不吝赐教啦^__^ 谢谢！

**附加信息**
当然 clash 的 profile 本身允许编写规则的特性也是非常好的，不过多一层保险也许能够更加合理地利用流量吧。毕竟手机不像电脑可以随时打开config或者profile改改改……
感谢开发者的辛勤劳动！

**Comment by Kr328** [comment]
自己改配置文件

**Comment by stars-island** [comment]
感谢解答！😄
