### ISSUE TITLE
[Feature Request] 希望能添加代理组收起和展开的功能

### ISSUE THREAD

**Issue by SenaJun** [Kr328/ClashForAndroid#574]
**功能描述**
如同标题，希望能添加一个代理组「收起」「展开」的功能，方便查看代理组内代理信息

**描述你希望的实现方式**
在每个代理组的最右侧「测速闪电标志」旁边添加一个「收起展开箭头按钮」
或将按钮添加在最左侧

**附加信息**
无

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/21
