### ISSUE TITLE
[BUG] 跳转activity时会出现闪屏

### ISSUE THREAD

**Issue by tjc0726** [Kr328/ClashForAndroid#578]
**描述出现的错误**
点击主界面设置，日志，配置（基本上所有按钮）会出现闪屏，应该是activity跳转时出现的问题，应该可以将Activity的Theme设置成透明来解决（修改style.xml）
参考：https://blog.csdn.net/Afanbaby/article/details/72858301
https://blog.csdn.net/dj0379/article/details/51362793

**如何复现该错误**
复现步骤:
点击主界面设置，日志，配置（基本上所有按钮）都会出现

**预期行为**
不闪屏

**设备信息 :**
 - 机型: 一加6
 - 系统/ROM: 氢os
 - Android 版本 10
 - ROM版本 OP6_H2_BETA_35

**应用信息**
 - 版本: 2.0.18及之前
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: github及Google Play

**Comment by Kr328** [comment]
无法复现

以及

参考方法会对原生用户体验造成影响

**Comment by Kr328** [comment]
@Kr328 录个屏 发上来

**Comment by tjc0726** [comment]
[http://qfchhg9gw.hd-bkt.clouddn.com/20-08-20-12-13-16.mp4](url)

**Comment by tjc0726** [comment]
https://github.com/Kr328/ClashForAndroid/issues/578#issuecomment-676991658

应该是我关闭了系统动画的缘故，开启动画之后正常

**Comment by tjc0726** [comment]
http://qfchhg9gw.hd-bkt.clouddn.com/20-08-20-12-13-16.mp4

应该是我关闭了系统动画的缘故，开启动画后正常
