### ISSUE TITLE
[Feature Request] 希望加入忽略电池优化的快捷方式

### ISSUE THREAD

**Issue by Aragamiz** [Kr328/ClashForAndroid#585]
在目前某些系统：MIUI、flyme等下，偶发断流，进入app后发现中断。手动重连后并加入忽略电池优化正常
希望加入快捷请求忽略电池优化的快捷方式帮助 clash for Android 快速调节保持后台的方式

**Comment by Kr328** [comment]
没有此类实现的标准方式
