### ISSUE TITLE
[BUG] wifi信号切换到手机信号上网，谷歌服务会断流，但是网络正常可以用

### ISSUE THREAD

**Issue by levis0792** [Kr328/ClashForAndroid#586]
wifi信号切换到手机信号上网，谷歌服务会断流，但是网络正常可以用
**描述出现的错误**
wifi信号切换到手机信号上网，谷歌服务会断流，但是网络正常可以用，必须重新开关clash才正常。

**如何复现该错误**
复现步骤:
1. 开clash 然后链接任意wifi
2. 关闭wifi信号范围，使用手机网络，这时候谷歌服务断流，表现为原生负一屏无法更新，chrome显示离线搜索，youtube显示无网络链接，但是可以看视频，电报可以打开并发送消息。
3. 关闭clash代理，再开启
4. 网络又正常

**预期行为**
希望能改善这个bug

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: pixel 4xl
 - 系统/ROM: QQ3A.200805.001
 - Android 版本 10
 - ROM版本 [QQ3A.200805.001]

**应用信息**
 - 版本: v2.13
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GITHUB

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
proxies:
   

**日志**
如果适用, 粘贴日志以帮助侦测错误
# Logcat on 2020-08-30 11:19:26
11:19:30 |Info| [TCP] 172.31.255.253:41376 --> www.google.com match DomainKeyword(google) using 🔰国外流量[A116U-1X-BGP-HK]
11:19:31 |Info| [UDP] 172.31.255.253:39103 --> 172.217.160.65 match Match() using ⚓️其他流量[A116U-1X-BGP-HK]
11:19:31 |Info| [UDP] 172.31.255.253:42253 --> 172.217.24.1 match Match() using ⚓️其他流量[A116U-1X-BGP-HK]
11:19:33 |Info| [TCP] 172.31.255.253:46896 --> 42.81.172.41 match GeoIP(CN) using DIRECT
11:19:34 |Info| [TCP] 172.31.255.253:45582 --> long.weixin.qq.com match DomainSuffix(qq.com) using DIRECT
11:19:34 |Info| [TCP] 172.31.255.253:38546 --> extshort.weixin.qq.com match DomainSuffix(qq.com) using DIRECT
11:19:39 |Info| [TCP] 172.31.255.253:47346 --> mtalk.google.com match DomainKeyword(google) using 🔰国外流量[A116U-1X-BGP-HK]
11:19:58 |Info| [UDP] 172.31.255.253:44179 --> suggestqueries.google.com match DomainKeyword(google) using 🔰国外流量[A116U-1X-BGP-HK]
11:19:58 |Info| [TCP] 172.31.255.253:45704 --> suggestqueries.google.com match DomainKeyword(google) using 🔰国外流量[A116U-1X-BGP-HK]
11:19:58 |Info| [UDP] 172.31.255.253:37266 --> youtubei.googleapis.com match DomainKeyword(google) using 🔰国外流量[A116U-1X-BGP-HK]
11:20:00 |Info| [TCP] 172.31.255.253:38658 --> android.googleapis.com match DomainKeyword(google) using 🔰国外流量[A116U-1X-BGP-HK]
11:20:03 |Info| [TCP] 172.31.255.253:46518 --> i.ytimg.com match DomainSuffix(ytimg.com) using 🔰国外流量[A116U-1X-BGP-HK]
11:20:08 |Info| Start initial compatible provider 🍎苹果服务
11:20:08 |Info| Start initial compatible provider 🎬国外媒体
11:20:08 |Info| Start initial compatible provider ✈️Telegram
11:20:08 |Info| Start initial compatible provider ⚓️其他流量
11:20:08 |Info| Start initial compatible provider 🎬Netflix
11:20:08 |Info| Start initial compatible provider 🎬Youtube
11:20:08 |Info| Start initial compatible provider 🚀直接连接
11:20:08 |Info| Start initial compatible provider 🔰国外流量
11:20:08 |Info| [DNS] Main 223.5.5.5:53
11:20:08 |Info| [DNS] Main 119.29.29.29:53
11:20:08 |Info| [DNS] Main 8.8.8.8:53
11:20:08 |Info| [DNS] Main 1.1.1.1:53
11:20:08 |Info| [DNS] Main 192.168.2.1:53
11:20:08 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:08 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:08 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:08 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:08 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:08 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:08 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:08 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:08 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:08 |Info| Start initial compatible provider 🚀直接连接
11:20:08 |Info| Start initial compatible provider 🔰国外流量
11:20:08 |Info| Start initial compatible provider ✈️Telegram
11:20:08 |Info| Start initial compatible provider ⚓️其他流量
11:20:08 |Info| Start initial compatible provider 🎬国外媒体
11:20:08 |Info| Start initial compatible provider 🎬Youtube
11:20:08 |Info| Start initial compatible provider 🍎苹果服务
11:20:08 |Info| Start initial compatible provider 🎬Netflix
11:20:08 |Info| [DNS] Main 223.5.5.5:53
11:20:08 |Info| [DNS] Main 119.29.29.29:53
11:20:08 |Info| [DNS] Main 8.8.8.8:53
11:20:08 |Info| [DNS] Main 1.1.1.1:53
11:20:08 |Info| [DNS] Main 192.168.2.1:53
11:20:08 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:08 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:08 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:08 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:08 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:08 |Info| Start initial compatible provider 🎬Netflix
11:20:08 |Info| Start initial compatible provider ⚓️其他流量
11:20:08 |Info| Start initial compatible provider 🚀直接连接
11:20:08 |Info| Start initial compatible provider 🔰国外流量
11:20:08 |Info| Start initial compatible provider 🎬国外媒体
11:20:08 |Info| Start initial compatible provider ✈️Telegram
11:20:08 |Info| Start initial compatible provider 🍎苹果服务
11:20:08 |Info| Start initial compatible provider 🎬Youtube
11:20:08 |Info| Start initial compatible provider ✈️Telegram
11:20:08 |Info| Start initial compatible provider 🎬Youtube
11:20:08 |Info| Start initial compatible provider ⚓️其他流量
11:20:08 |Info| Start initial compatible provider 🍎苹果服务
11:20:08 |Info| Start initial compatible provider 🎬Netflix
11:20:08 |Info| Start initial compatible provider 🚀直接连接
11:20:08 |Info| Start initial compatible provider 🔰国外流量
11:20:08 |Info| Start initial compatible provider 🎬国外媒体
11:20:08 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:08 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:08 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:08 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:08 |Info| [DNS] Main 223.5.5.5:53
11:20:08 |Info| [DNS] Main 119.29.29.29:53
11:20:08 |Info| [DNS] Main 8.8.8.8:53
11:20:08 |Info| [DNS] Main 1.1.1.1:53
11:20:08 |Info| [DNS] Main 192.168.2.1:53
11:20:08 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:08 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:08 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:08 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:08 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:08 |Info| [DNS] Main 223.5.5.5:53
11:20:08 |Info| [DNS] Main 119.29.29.29:53
11:20:08 |Info| [DNS] Main 8.8.8.8:53
11:20:08 |Info| [DNS] Main 1.1.1.1:53
11:20:08 |Info| [DNS] Main 192.168.2.1:53
11:20:08 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:08 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:08 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:08 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:08 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:08 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:08 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:08 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:08 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:08 |Info| Start initial compatible provider 🎬Netflix
11:20:08 |Info| Start initial compatible provider 🎬Youtube
11:20:08 |Info| Start initial compatible provider 🍎苹果服务
11:20:08 |Info| Start initial compatible provider 🎬国外媒体
11:20:08 |Info| Start initial compatible provider 🚀直接连接
11:20:08 |Info| Start initial compatible provider 🔰国外流量
11:20:08 |Info| Start initial compatible provider ⚓️其他流量
11:20:08 |Info| Start initial compatible provider ✈️Telegram
11:20:08 |Info| [DNS] Main 223.5.5.5:53
11:20:08 |Info| [DNS] Main 119.29.29.29:53
11:20:08 |Info| [DNS] Main 8.8.8.8:53
11:20:08 |Info| [DNS] Main 1.1.1.1:53
11:20:08 |Info| [DNS] Main 192.168.2.1:53
11:20:08 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:08 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:08 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:08 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:08 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:08 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:08 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:08 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:08 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:08 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:08 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:08 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:08 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:08 |Info| [TCP] 172.31.255.253:39726 --> mtalk.google.com match DomainKeyword(google) using 🔰国外流量[A116U-1X-BGP-HK]
11:20:08 |Info| [UDP] 172.31.255.253:45516 --> 122.112.251.56 match GeoIP(CN) using DIRECT
11:20:08 |Info| [UDP] 172.31.255.253:38508 --> 122.112.141.133 match GeoIP(CN) using DIRECT
11:20:08 |Info| [UDP] 172.31.255.253:45543 --> 47.103.65.112 match GeoIP(CN) using DIRECT
11:20:08 |Info| [UDP] 172.31.255.253:44842 --> 119.3.204.221 match GeoIP(CN) using DIRECT
11:20:08 |Info| [UDP] 172.31.255.253:41466 --> 122.112.178.101 match GeoIP(CN) using DIRECT
11:20:08 |Info| [UDP] 172.31.255.253:37500 --> 122.112.229.109 match GeoIP(CN) using DIRECT
11:20:08 |Info| [TCP] 172.31.255.253:37561 --> 119.3.204.221 match GeoIP(CN) using DIRECT
11:20:09 |Info| [TCP] 172.31.255.253:49174 --> www.taobao.com match DomainSuffix(taobao.com) using DIRECT
11:20:09 |Info| [TCP] 172.31.255.253:45518 --> cm-10-13.getui.com match GeoIP(CN) using DIRECT
11:20:09 |Info| [TCP] 172.31.255.253:48712 --> 101.89.15.106 match GeoIP(CN) using DIRECT
11:20:09 |Info| [TCP] 172.31.255.253:43130 --> app-measurement.com match GeoIP(CN) using DIRECT
11:20:09 |Info| Start initial compatible provider 🍎苹果服务
11:20:09 |Info| Start initial compatible provider ✈️Telegram
11:20:09 |Info| Start initial compatible provider ⚓️其他流量
11:20:09 |Info| Start initial compatible provider 🚀直接连接
11:20:09 |Info| Start initial compatible provider 🔰国外流量
11:20:09 |Info| Start initial compatible provider 🎬国外媒体
11:20:09 |Info| Start initial compatible provider 🎬Youtube
11:20:09 |Info| Start initial compatible provider 🎬Netflix
11:20:09 |Info| [DNS] Main 223.5.5.5:53
11:20:09 |Info| [DNS] Main 119.29.29.29:53
11:20:09 |Info| [DNS] Main 8.8.8.8:53
11:20:09 |Info| [DNS] Main 1.1.1.1:53
11:20:09 |Info| [DNS] Main 192.168.2.1:53
11:20:09 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:09 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:09 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:09 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:09 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:09 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:09 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:09 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:09 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:09 |Info| Start initial compatible provider 🍎苹果服务
11:20:09 |Info| Start initial compatible provider ⚓️其他流量
11:20:09 |Info| Start initial compatible provider 🚀直接连接
11:20:09 |Info| Start initial compatible provider 🔰国外流量
11:20:09 |Info| Start initial compatible provider 🎬国外媒体
11:20:09 |Info| Start initial compatible provider 🎬Netflix
11:20:09 |Info| Start initial compatible provider ✈️Telegram
11:20:09 |Info| Start initial compatible provider 🎬Youtube
11:20:09 |Info| Start initial compatible provider ✈️Telegram
11:20:09 |Info| Start initial compatible provider 🎬国外媒体
11:20:09 |Info| Start initial compatible provider 🎬Youtube
11:20:09 |Info| Start initial compatible provider ⚓️其他流量
11:20:09 |Info| Start initial compatible provider 🍎苹果服务
11:20:09 |Info| Start initial compatible provider 🎬Netflix
11:20:09 |Info| Start initial compatible provider 🚀直接连接
11:20:09 |Info| Start initial compatible provider 🔰国外流量
11:20:09 |Info| [DNS] Main 223.5.5.5:53
11:20:09 |Info| [DNS] Main 223.5.5.5:53
11:20:09 |Info| [DNS] Main 119.29.29.29:53
11:20:09 |Info| [DNS] Main 119.29.29.29:53
11:20:09 |Info| [DNS] Main 8.8.8.8:53
11:20:09 |Info| [DNS] Main 1.1.1.1:53
11:20:09 |Info| [DNS] Main 8.8.8.8:53
11:20:09 |Info| [DNS] Main 1.1.1.1:53
11:20:09 |Info| [DNS] Main 192.168.2.1:53
11:20:09 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:09 |Info| [DNS] Main 192.168.2.1:53
11:20:09 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:09 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:09 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:09 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:09 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:09 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:09 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:09 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:09 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:09 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:09 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:09 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:09 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:09 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:09 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:09 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:09 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:09 |Info| Start initial compatible provider 🚀直接连接
11:20:09 |Info| Start initial compatible provider 🔰国外流量
11:20:09 |Info| Start initial compatible provider ✈️Telegram
11:20:09 |Info| Start initial compatible provider 🎬Youtube
11:20:09 |Info| Start initial compatible provider 🎬Netflix
11:20:09 |Info| Start initial compatible provider 🍎苹果服务
11:20:09 |Info| Start initial compatible provider 🎬国外媒体
11:20:09 |Info| Start initial compatible provider ⚓️其他流量
11:20:09 |Info| [DNS] Main 223.5.5.5:53
11:20:09 |Info| [DNS] Main 119.29.29.29:53
11:20:09 |Info| [DNS] Main 8.8.8.8:53
11:20:09 |Info| [DNS] Main 1.1.1.1:53
11:20:09 |Info| [DNS] Main 192.168.2.1:53
11:20:09 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:09 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:09 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:09 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:09 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:09 |Info| Start initial compatible provider ⚓️其他流量
11:20:09 |Info| Start initial compatible provider 🎬Netflix
11:20:09 |Info| Start initial compatible provider 🍎苹果服务
11:20:09 |Info| Start initial compatible provider ✈️Telegram
11:20:09 |Info| Start initial compatible provider 🚀直接连接
11:20:09 |Info| Start initial compatible provider 🔰国外流量
11:20:09 |Info| Start initial compatible provider 🎬国外媒体
11:20:09 |Info| Start initial compatible provider 🎬Youtube
11:20:09 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:09 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:09 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:09 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:09 |Info| [DNS] Main 223.5.5.5:53
11:20:09 |Info| [DNS] Main 119.29.29.29:53
11:20:09 |Info| [DNS] Main 8.8.8.8:53
11:20:09 |Info| [DNS] Main 1.1.1.1:53
11:20:09 |Info| [DNS] Main 192.168.2.1:53
11:20:09 |Info| [DNS] Fallback https://dns.google/dns-query
11:20:09 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
11:20:09 |Info| [DNS] Fallback https://doh.pub/dns-query
11:20:09 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
11:20:09 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/0.yaml loaded
11:20:09 |Info| Set ⚓️其他流量 -> 🔰国外流量
11:20:09 |Info| Set ✈️Telegram -> 🔰国外流量
11:20:09 |Info| Set 🎬Youtube -> 🔰国外流量
11:20:09 |Info| Set 🔰国外流量 -> A116U-1X-BGP-HK
11:20:09 |Info| [TCP] 172.31.255.253:45892 --> 64.233.177.188 match Match() using ⚓️其他流量[A090T-0.7X-BGP-HK]
11:20:09 |Info| [TCP] 172.31.255.253:45802 --> 101.91.96.61 match GeoIP(CN) using DIRECT
11:20:11 |Info| [TCP] 172.31.255.253:41522 --> 216.58.200.68 match Match() using ⚓️其他流量[A116U-1X-BGP-HK]
11:20:13 |Info| [UDP] 172.31.255.253:39103 --> 172.217.160.65 match Match() using ⚓️其他流量[A116U-1X-BGP-HK]
11:20:15 |Warning| dial DIRECT error: dial tcp4 101.91.69.38:8080: connect: network is unreachable
11:20:15 |Warning| dial DIRECT error: dial tcp4 101.91.69.38:8080: connect: network is unreachable
11:20:17 |Info| [TCP] 172.31.255.253:47842 --> long.weixin.qq.com match DomainSuffix(qq.com) using DIRECT
11:20:18 |Info| [UDP] 172.31.255.253:44179 --> 216.58.200.238 match Match() using ⚓️其他流量[A116U-1X-BGP-HK]
11:20:23 |Info| [TCP] 172.31.255.253:46162 --> mtalk.google.com match DomainKeyword(google) using 🔰国外流量[A116U-1X-BGP-HK]

**Comment by Kr328** [comment]
日志呢 配置呢 重要的东西一个不填 要不手机送给我 我来调

**Comment by levis0792** [comment]
> 日志呢 配置呢 重要的东西一个不填 要不手机送给我 我来调

贴上配置文件和日志了，麻烦大佬看看，关闭wifi用手机流量就没法链接谷歌服务，必须关闭重新开下软件才行。辛苦了

**Comment by Kr328** [comment]
@levis0792 你这日志? 是复现过了吗

**Comment by levis0792** [comment]
> @levis0792 你这日志? 是复现过了吗

日志我获取出来就是这个样子，从wifi到关闭wifi，昨晚更新了新版本试了下，发现是关闭wifi的时候，谷歌服务断流，外网可用。

**Comment by Kr328** [comment]
意思是 日志没有任何一点用

甚至连一条连接都找不到

打开日志之后 复现问题 保存之后 才是有效的

**Comment by levis0792** [comment]
> 意思是 日志没有任何一点用
> 
> 甚至连一条连接都找不到
> 
> 打开日志之后 复现问题 保存之后
点 日志-clash 日志捕捉工具  就是下面的日志
# Logcat on 2020-08-30 01:56:31
01:56:42 |Info| Android tun started
01:56:42 |Info| Listen TCP redirect 40379
01:56:42 |Info| Start initial compatible provider 🎬Youtube
01:56:42 |Info| Start initial compatible provider 🚀直接连接
01:56:42 |Info| Start initial compatible provider 🔰国外流量
01:56:42 |Info| Start initial compatible provider ⚓️其他流量
01:56:42 |Info| Start initial compatible provider 🍎苹果服务
01:56:42 |Info| Start initial compatible provider 🎬国外媒体
01:56:42 |Info| Start initial compatible provider ✈️Telegram
01:56:42 |Info| Start initial compatible provider 🎬Netflix
01:56:42 |Info| [DNS] Main 223.5.5.5:53
日志捕捉工具，我只有在关闭代理时候先点击，才会有记录上面的日志信息。如果是开启代理状态下，怎么点击日志捕捉工具，里面的日志都是空的。上面的日志信息是开启代理前点击捕捉然后开启代理获取的，后面手机怎么再怎么操作，日志都是上面的内容，没有增加，不知道我表述的清楚没有。

**Comment by Kr328** [comment]
@levis0792 去复写里把日志级别调到 debug 再抓

**Comment by levis0792** [comment]
> @levis0792 去覆写里把日志级别调到 debug 再抓

日志和配置文件已经更新，日志记录了2次关闭无线网使用手机网络谷歌服务断流的状态。

**Comment by levis0792** [comment]
2.14好像正常了，今天观察一天。

**Comment by levis0792** [comment]
观察了一天，好像正常了。暂时没发现谷歌断流情况

**Comment by levis0792** [comment]
2.1.6版本，又出现了2次这种情况。

**Comment by levis0792** [comment]
2.16情况愈发严重，盼解决

**Comment by leo-fengchao** [comment]
我除了谷歌服务之外，有一些 App 在切换 WiFi 到流量的时候都会出现无法联网的情况（如掌上生活、美团），需要重开关一下 Clash 或者给 App 设置绕行之后就好了

**Comment by levis0792** [comment]
> 我除了谷歌服务之外，有一些 App 在切换 WiFi 到流量的时候都会出现无法联网的情况（如掌上生活、美团），需要重开关一下 Clash 或者给 App 设置绕行之后就好了

我也遇到了这个情况，设置不代理可以解决，但是google断流太烦了

**Comment by levis0792** [comment]
> 意思是 日志没有任何一点用
> 
> 甚至连一条连接都找不到
> 
> 打开日志之后 复现问题 保存之后 才是有效的

盼望解决，2.1.6情况严重
