### ISSUE TITLE
weird dns errors in logs

### ISSUE THREAD

**Issue by chenzhiwei** [Kr328/ClashForAndroid#59]
there are some weird dns error logs, see picture:

![IMG_20191225_010656_267](https://user-images.githubusercontent.com/672668/71421018-44977700-26b3-11ea-83fb-6ea446bb3dbc.jpg)

btw, syntax error.

**Comment by Kr328** [comment]
**Expected behavior**

The domains is **INVALID**

**Comment by Kr328** [comment]
This is only Chrome connection testing
