### ISSUE TITLE
[BUG] 2.1.1版本存在*的Profile URL无法填入

### ISSUE THREAD

**Issue by Dark-Existed** [Kr328/ClashForAndroid#590]
**描述出现的错误**

2.1.1版本存在 * 的Profile URL无法填入

**屏幕截图**
![Screenshot_20200828-010648](https://user-images.githubusercontent.com/24956657/91473250-339aa780-e8cb-11ea-872f-01e17630d0cd.jpg)

**应用信息**
 - 版本: 2.1.1
 - 安装包文件名:  app-release-arm64-v8a.apk
 - 应用来源: Github

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.4
