### ISSUE TITLE
[BUG]  clash托管配置链接自动或手动导入均失败

### ISSUE THREAD

**Issue by nicolea-bx** [Kr328/ClashForAndroid#592]
![Screenshot_20200828_105644_com github kr328 clash](https://user-images.githubusercontent.com/70358481/91519584-8f245f80-e8e2-11ea-93bd-5ac6cd1e2758.jpg)
![Screenshot_20200828_105647_com github kr328 clash](https://user-images.githubusercontent.com/70358481/91519585-90ee2300-e8e2-11ea-853a-c951178f8f2d.jpg)

**描述出现的错误**
请简洁的描述你遇到的错误： 一开始节点均显示timesout， 然后删除重新下载之后，自动或手动导入托管配置链接失败，不清楚什么原因。。。

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/591
