### ISSUE TITLE
[BUG] 被动从wifi切换到4G会导致clash停止和清空配置

### ISSUE THREAD

**Issue by dyxushuai** [Kr328/ClashForAndroid#596]
**描述出现的错误**
clash从wifi切换到4G会自动停止并清空代理配置 而且系统配置界面显示正在运行

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![gt_2020828_18850_v_gif](https://user-images.githubusercontent.com/5157648/91563819-1f5db580-e972-11ea-9ff0-2f5878daea61.gif)

**设备信息 (请完成以下信息):**
 - 机型: mate30pro
 - 系统/ROM: EMUI10.0.1
 - Android 版本 10
 - ROM版本 

**应用信息**
 - 版本: 2.1.2
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: github

**附加信息**
详见gift

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
无日志
```

**Comment by Kr328** [comment]
必然不可能没有日志 日志级别改到 debug

**Comment by dyxushuai** [comment]
看gift最后去看日志的时候卡死了 强制关闭了

**Comment by Kr328** [comment]
能用 adb logcat 吗

**Comment by dyxushuai** [comment]
我明天抓一下 不是百分百复现的

**Comment by dyxushuai** [comment]
新版本好像没有问题了
