### ISSUE TITLE
[Feature Request] 解决不兼容老文件，请求增设类似CFW设置里的profiles里的parsers项目

### ISSUE THREAD

**Issue by williamjaung** [Kr328/ClashForAndroid#597]
**功能描述**
解决不兼容老文件，请求增设类似CFW设置里的profiles里的parsers项目。可以在这个parsers里自己写入代码，兼容老版本的订阅文件格式。

**描述你希望的实现的功能**
请求增设类似CFW设置里的profiles里的parsers项目
**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
你想让 Clash for Android 像 Clash for Windows 一样 一个安装包 100M+ 或者 载入配置文件 需要 1 min+ 吗

**Comment by williamjaung** [comment]
如果想要使用clash for Android的最新版，就只能更新订阅文件吗？但是我那个机场主，不跟进那个文件。

best regards

William

________________________________
