### ISSUE TITLE
[Feature Request]  auto proxy list refresh in background

### ISSUE THREAD

**Issue by messi06** [Kr328/ClashForAndroid#598]
Hello, awesome work really.. respect !
However in order to get the best of clash : using groups , time based url test etc...
Only issue is in order to see the change after x time we have to manually press  refresh option in the menu Everytime, I wish if you just open the proxy list and see the change live , like the fastest ping servers getting on top etc.. so far we have to press refresh manually Everytime and we can't be sure if the app actually changes in the background to the best server in the group unless we hit refresh then we see it changed..
Thank you

**Comment by xuhaoyang** [comment]
You should understand how auto proxy group works

**Comment by messi06** [comment]
I understand how it works , you see with a url test type , after x time , the servers of that group will be tested and have a ping value , and based on my preference i set the list to be sorted from lowest ping to highest , as I said , unless you press refresh you won't see the ping values generated from the auto url test of the group . Clash for windows refreshes automatically , literally you open the app and the proxies in each group get tested automatically and the list is sorted from lowest ping to highest automatically... I think if we can set a custom timer to refresh the list automatically would work great ?!

**Comment by messi06** [comment]
> You should understand how auto proxy group works

⬆️

**Comment by xuhaoyang** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto
![image](https://user-images.githubusercontent.com/1927125/91624983-3d5d0180-e9d6-11ea-90af-0b5f3323d449.png)
Retest the latency after several seconds.

https://github.com/Dreamacro/clash/blob/93ea037230893576279a098a3429d58db2a70473/adapters/provider/healthcheck.go
https://github.com/Dreamacro/clash/blob/7c62fe41b40e6b20c8c88e0e5b5ee96ac0c46dd9/adapters/outboundgroup/parser.go
https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/adapters/provider/fetcher.go

**Comment by xuhaoyang** [comment]
set interval <30s . See?

**Comment by messi06** [comment]
[video.zip](https://github.com/Kr328/ClashForAndroid/files/5144653/video.zip)

proxy-groups:
  - name: 💟 Auto-Fast-SG
    proxies:
      - IPLC-SH-SG-01
      - IPLC-SH-SG-02
      - IPLC-SH-SG-03
      - IPLC-SH-SG-04
      - IPLC-SH-SG-05
      - IPLC-SH-SG-06
      - IPLC-SH-SG-07
      - IPLC-SH-SG-08
      - IPLC-SH-SG-09
      - IPLC-SZ-SG-1
      - IPLC-SZ-SG-2
      - IPLC-SZ-SG-3
      - IPLC-SZ-SG-4
      - IPLC-SZ-SG-5
      - IPLC-SZ-SG-6
      - IPLC-SZ-SG-7
      - IPLC-SZ-SG-8
      - IPLC-SZ-SG-9
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: "85"
  - name: ☢️ Auto-Fast-VIP
    proxies:
      - "#💎-VIP4| N01 | Premium-8k01-[US]"
      - "#💎-VIP4| N02 | Premium-8k02-[US]"
      - "#💎-VIP4| N03 | Premium-8k03-[US]"
      - "#💎-VIP4| N04 | Premium-8k04-[US]"
      - "#💎-VIP4| N05 | Premium-8k05-[US]"
      - "#💎-VIP4| N06 | Premium-8k06-[US]"
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: "90"

**Comment by xuhaoyang** [comment]
原来是你
![image](https://user-images.githubusercontent.com/1927125/91625676-e1957700-e9db-11ea-85b2-2918ab2d8886.png)
都是中国人讲什么英文。
拜托你搞清楚Auto工作逻辑再来提问，你没看到就是没工作？

**Comment by messi06** [comment]
> 原来是你

不，那是我的双胞胎兄弟，啊。

**Comment by AkariiinMKII** [comment]
sudo roll
感谢您的支持
