### ISSUE TITLE
软件进入后台一段时间后无法联网（应该不是杀后台导致）

### ISSUE THREAD

**Issue by Kvkzhi** [Kr328/ClashForAndroid#6]
经测试，软件进入后台一段时间（2、3个小时左右吧）就会无法上网，国内、国外均不能访问（telegram一直显示连接中，浏览器访问国内百度无法正常打开），只有进入clash界面关闭运行再打开才恢复正常。已经设置了clash允许后台，电池优化也设置了clash不允许优化。
手机：华为mate 20 Pro
系统版本：emui 9. 1. 0. 135
安卓版本：andriod 9
附logs截图：
![微信图片_20191208193213](https://user-images.githubusercontent.com/5763455/70388398-23186900-19ec-11ea-97da-584bfaf2bc96.jpg)

**Comment by Kr328** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/Kr328/ClashForAndroid/issues/new/choose)
