### ISSUE TITLE
疑惑问题

### ISSUE THREAD

**Issue by KeSaite** [Kr328/ClashForAndroid#60]
# **建议+问题**
**Feedback ID** 
- **a8951833779078f08a9c0244a75ab1a7**
1. 不能修改配置文件嘛？功能还没做嘛？
![Screenshot_20191226-152008__01](https://user-images.githubusercontent.com/13944595/71464162-9ba46580-27f3-11ea-9b7c-46a68a127ff6.jpg)
![Screenshot_20191226-151953__01](https://user-images.githubusercontent.com/13944595/71464168-9e9f5600-27f3-11ea-9876-8cc824cd3271.jpg)

2.建议增加其他类型的导入方式，比如二维码扫描、剪切板导入；导入后最好APP自行创建最基本的配置文件然后用户自行修改配置文件。目前只有两个导入方式太少了。

3.建议增加配置文件导出文件、URL、剪切板、二维码功能。对应上面的建议2。

4.UI黑暗模式走一波~

5.虽然clash都没中文，但是还是要努力发出添加中文的呐喊~

6.Logs里面的流量详情可以跟Windows版本的UI借鉴，可以复制，然后再配合编辑功能修改配置文件

7.根据建议2.6，配置文件的编辑功能得好好做了。比如从Logs复制未匹配的规则然后到编辑功能进行相应的规则匹配，类似Windows那样；还有用户找到了别的规则，想添加到配置文件，假如编辑功能模块有快捷添加规则的功能就会很方便。

8.辛苦作者了~mua~

**Comment by Kr328** [comment]
1. 没做
2. 剪切板容量不足以放下配置文件
3. 同 2
4. 有重复的 Issue
5. 没计划
6.日志只是一个字符串 解析不稳定
7. 同 6

**Comment by KeSaite** [comment]
2.可以折中一下，配置文件大的情况下，可以考虑单独支持ss、vemss这些协议的导入到配置文件。如果我只有一个ss节点，使用逻辑是打开app导入ss协议并创建相应配置文件

**刚才使用的过程中，在配置文件策略组中存在url-test的情况下，点开app的Proxy会导致闪退**

- Android 9.0

- 复现次数为每次

**Comment by Kr328** [comment]
**不能**
Clash 的 代理 代理组 规则 是 **强关联的**
不能单独分离 否则就失去了 **配置文件的意义**

并且 

Clash for Android 的 原则之一 就是 配置文件 **仅由 Clash 处理**
