### ISSUE TITLE
[BUG] 通过快捷开关启动cfa可能会出现多项问题

### ISSUE THREAD

**Issue by ausers** [Kr328/ClashForAndroid#602]
**描述出现的错误**
未直接打开应用时，通过快捷开关操作：
1. 代理显示连接却无法连接网络（包括我通过ip连接国内服务器也连不上）
2. 切换网络环境会导致代理仍连接却无法使用

3. 刚才在那里为了确定浮现步骤，开开关关好几次，现在我的手机通过这开关打开彻底连不上代理了，所以以下复现操作可能并不完善

**如何复现该错误**
复现步骤:
1. 确定没有打开cfa应用
2. 操作快捷开关
![qq_pic_merged_1598692983337](https://user-images.githubusercontent.com/54773815/91633605-64d6bd00-ea1c-11ea-8634-057feb55ce5f.jpg)
3. 问题1：反复开关几次
4. 问题2：关闭WiFi

**预期行为**
按钮准确反映了clash的开关，并在网络环境改变时准确切换

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: VIVO NEX
 - 系统/ROM: Funtouch OS_10
 - Android 版本 10
 - ROM版本 PD1806B-YD-B_A_8.10.1

**应用信息**
 - 版本: 2.1.3-armeabi-v7a
 - 安装包文件名: app-armeabi-v7a-release.apk
 - 应用来源: GitHub

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
由于以上问题出现于未直接启动cfa时，故无法捕捉到logcat
```

**Comment by xuhaoyang** [comment]
这个更像你手机系统改出来的问题。比如miui一类的

**Comment by 752376710** [comment]
额，我的miui12也有这问题，表现为快捷开关变成灰色，且无法点击。这应该不是cfa的问题，像是v2rayng等都有概率在miui上复现。
或许将此bug发送给系统维护者会更好

**Comment by levis0792** [comment]
2切换网络环境会导致代理仍连接却无法使用 
这个我也遇到了。我也发了bug贴，具体你试试wifi切换到手机网络时候，谷歌服务不可用，但是电报之类的却没问题

**Comment by fgprodigal** [comment]
tile开关几次进app发现配置文件都不见了，杀掉进程重开又出现了

**Comment by ausers** [comment]
> tile开关几次进app发现配置文件都不见了，杀掉进程重开又出现了

确实有这个问题，我也有遇到

**Comment by ausers** [comment]
> 额，我的miui12也有这问题，表现为快捷开关变成灰色，且无法点击。这应该不是cfa的问题，像是v2rayng等都有概率在miui上复现。
> 或许将此bug发送给系统维护者会更好

我在我手机上从未遇到过快捷开关“无法点击”的问题，我的问题主要表现在操作开关时cfa并未完善的执行相应操作

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.1.4

**Comment by ausers** [comment]
v2.1.4 仍未解决我所描述的问题，但因为一些原因懒得继续反馈了，还请各位遇到类似bug的自行发起issue
