### ISSUE TITLE
[Feature Request] 增加Android tv遥控支持

### ISSUE THREAD

**Issue by JasprW** [Kr328/ClashForAndroid#605]
**功能描述**
* 修改布局前的版本使用遥控器可以正常选择proxy group和节点，修改后无法选择节点，仅可以选择group
* profile管理无法使用遥控器选择到profile条目菜单

**描述你希望的实现方式**
* 允许使用遥控器手动选择节点
* profile管理对菜单按钮设置focus状态，允许使用遥控器选择到菜单键
* 增加Android TV启动图标

**附加信息**
* 可使用键盘上下左右模拟遥控器操作进行调试

**Comment by xuhaoyang** [comment]
* 修改布局前的版本使用遥控器可以正常选择proxy group和节点，修改后无法选择节点，仅可以选择group

最新版 redmi x55 可以正常选择节点，选择后，也可以继续选择

* profile管理无法使用遥控器选择到profile条目菜单

老问题，安装悟空遥控器，实现模拟鼠标操作后，可先行绕过

**Comment by Kr328** [comment]
#58

**Comment by LilHayah** [comment]
同Android TV，刚更新到最新版本(2.1.4)，请问现在是无法测延迟了么？(之前用的版本上有小闪电符号可以测延迟)，还有现在无法直接选择模式了么(Global,Rule,Direct)？默认只能在Rule里选节点，但比如想使用全局，还必须去设置覆写里切换到Global才行。

**Comment by Kr328** [comment]
@LilHayah 1. 还可以双击 TAB
2. 是的
