### ISSUE TITLE
[Feature Request] 在代理界面的汉堡菜单内添加全局模式切换选项

### ISSUE THREAD

**Issue by kingofotaku** [Kr328/ClashForAndroid#607]
**功能描述**
添加类似大更新之前版本那样的全局/规则模式切换

**描述你希望的实现方式**
如题

**附加信息**
其他的与改功能相关的附加信息
因为套用的规则内去广告较多，有时被误杀的情况下需要切换至全局模式使用，最近新版本的改动使得在全局和规则模式之间切换变得非常不方便，因此请求加回之前代理页菜单中那样的开关。

**Comment by Kr328** [comment]
会不方便做持久化 以及出现冲突问题
