### ISSUE TITLE
[Feature Request] App shortcuts

### ISSUE THREAD

**Issue by xmha97** [Kr328/ClashForAndroid#609]
**Is your feature request related to a problem? Please describe.**
The strong point of "Shadowsocks" compared to "Clash" is that it has an "App Shortcuts" feature.

**Describe the solution you'd like**
I can connect without entering the app.

**Describe alternatives you've considered**
The link below may help you:
https://developer.android.com/guide/topics/ui/shortcuts

**Additional context**
Screenshot:
![App Shortcuts](https://user-images.githubusercontent.com/23485114/91670899-04886e00-eb37-11ea-8763-1f970ea0bbe3.jpg)

**Comment by Kr328** [comment]
#326
