### ISSUE TITLE
[BUG] 异常的待机耗电

### ISSUE THREAD

**Issue by zszeng** [Kr328/ClashForAndroid#612]
**Describe the bug**
更新2.1.4直接 一个晚上的待机耗光了我的设备电量，在耗电占比中 cfa在百分之五十以上，这是不正常的。
**To Reproduce**
1. 打开cfa代理
2. 睡一晚上
3. 查看耗电占比

**Expected behavior**
正常的耗电量

**Device Info (please complete the following information):**

 - Device: MIX2
 - ROM: MIUI
 - ROM Version:10.3
 - Android Version 8.0

**Application Info (please complete the following information):**

 - Version: .1.4
 - Apk File Name: app-release-arm64-v8a.apk
 - Distribution Channel: github release

**Configure**
If applicable, paste **removed server info** configure
```yaml
# paste here
```

**Logs**
If applicable, paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
#505
