### ISSUE TITLE
[Feature Request]请增加vmess链接的支持

### ISSUE THREAD

**Issue by yaoshuangshl** [Kr328/ClashForAndroid#615]
**功能描述**
请增加vmess链接的支持，因为我是自己搭的v2ray服务器，除了生成vmess链接我不会其他办法啊···

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by xuhaoyang** [comment]
@yaoshuangshl please
https://github.com/tindy2013/subconverter/blob/master/README-cn.md

**Comment by Kr328** [comment]
自行使用转换 API

添加非核心功能与 Clash for Android 设计理念不符
