### ISSUE TITLE
[BUG] app自动断开连接

### ISSUE THREAD

**Issue by RuCu6** [Kr328/ClashForAndroid#616]
**描述出现的错误**
app连接后，打开tg/apkpure会概率性自动关闭，但是并没有发生闪退

**如何复现该错误**
复现步骤:
1. 使用app连接Trojan
2. 把app放到后台运行
3. 打开apkpure
4. app连接已断开

**预期行为**
希望修复这个bug，太影响使用了

**屏幕截图**
无截图

**设备信息 (请完成以下信息):**
 - 机型: [小米10]
 - 系统/ROM: [MIUI 12 稳定版]
 - Android 版本 [10]
 - ROM版本 [12.0.4.0]

**应用信息**
 - 版本: [2.1.5]
 - 安装包文件名: [app-release-arm64-v8a.apk]
 - 应用来源: [GitHub]

**附加信息**
1.app从2.1.2版本到2.1.5版本均出现该问题。
2.无法抓取日志。打开app的日志捕捉工具，当此bug发生时，日志捕获同样失效。打开app已保存的日志，但显示空白
3.MIUI已设置此app无限制后台运行的权限

**配置文件**
不方便填写

**日志**
无

**Comment by devon-ge** [comment]
昨天更新的版本也有类似bug，配置自动丢失，显示空白。需要关闭app进程重启才能使用，然后过一会儿继续失效

**Comment by DorKingGG** [comment]
是的  2.1.2开始就有这个bug

**Comment by DorKingGG** [comment]
我遇到的bug没有丢失配置，只是自动关闭了，状态栏还有连接速度显示，所以应该不是闪退，但是日志捕捉不到😓😓

**Comment by skrad9101** [comment]
我也遇到这个问题。在4G网络下非常严重，在wifi下一直没事。具体现象就是程序自动关闭，也无法捕捉日志，因为还没有关闭日志记录，程序自己就退出了。

**Comment by Kr328** [comment]
新版本 日志 请

**Comment by MuyueJusan** [comment]
我也有遇到，不止clash还有ssr和surfboard都有这种情况出现，在使用过程中突然中断，我判断是miui的问题，目前miui版本12.2.2稳定版，设备为redmi k30pro
