### ISSUE TITLE
[BUG] wifi切换到4g时，无法联网,且无法关闭或打开软件

### ISSUE THREAD

**Issue by harnseen** [Kr328/ClashForAndroid#617]
**描述出现的错误**
从wifi切换到4g时（在不关闭clash的情况下）,无法连接到网络（包括直连和代理），也无法打开或关闭软件
目前我的解决方法是：1.切换网络环境之前，先关闭clash，切换之后再打开clash。2.无法关闭软件时，在系统设置里强制停止，然后再打开clash

**如何复现该错误**
复现步骤:
1. 连接wifi的状态下，切换4g（打开clash的情况下）
2. 网络连接错误
3. 无法关闭或打开软件
复现率100%

**预期行为**
切换网络环境能够不中断代理，网络连接正常，并且可以正常打开或关闭软件

**屏幕截图**
![](https://pic.downk.cc/item/5f536cbc160a154a67c97242.gif)
![](https://pic.downk.cc/item/5f536d06160a154a67c98308.gif)
**设备信息:**
 - 机型: [一加六]
 - 系统/ROM: [氢os]
 - Android 版本 [10]
 - ROM版本 [OP6_H2_BETA_35]

**应用信息**
 - 版本: [2.1.5-arm64-v8a]
 - 应用来源: [github]

**附加信息**
从2.1.1开始支持ssr的版本开始出现这个问题

**配置文件**
无

**日志**
日志无法记录此问题

**Comment by linchen123** [comment]
我也有这个问题

**Comment by lpn418** [comment]
我这点此启动  根本就点不开   安卓10

**Comment by leo-fengchao** [comment]
我是有时候 Wi-Fi 切换成 4G 之后 Google 全家桶和 Bixby 会出现无法连接的状况，比较快的解决方案是断开 Clash 使用 V2Ray 连接一下就正常了，然后就可以切换回 Clash 了

 

三星 S20 

One UI 2.5 

安卓 10 

 

发件人: lpn418 <notifications@github.com>
答复: Kr328/ClashForAndroid <reply@reply.github.com>
日期: 2020年9月6日 星期日 上午7:52
收件人: Kr328/ClashForAndroid <ClashForAndroid@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Kr328/ClashForAndroid] [BUG] wifi切换到4g时，无法联网,且无法关闭或打开软件 (#617)

 

我这点此启动 根本就点不开 安卓10

**Comment by xiandu999-yu** [comment]
把应用强制停止吧😂....

**Comment by guoyitian315** [comment]
我这只要切换网络就假死，无解

**Comment by uoox** [comment]
同样遇到这个问题

**Comment by clancygo** [comment]
我也有一样的问题

**Comment by 1064298219** [comment]
相同问题

**Comment by 1064298219** [comment]
本人在刚开始使用时，使用的时ss转clash，出现该问题。在后来直接使用配置文件直接导入后，问题的到解决。
值得一提的时本人发现clash for windows的配置文件等可直接用于android

**Comment by Kr328** [comment]
新版本 日志 请
