### ISSUE TITLE
请问这个 warn 是什么情况

### ISSUE THREAD

**Issue by Forty-nine** [Kr328/ClashForAndroid#62]
![photo_2019-12-30_09-07-36](https://user-images.githubusercontent.com/14026156/71564968-0e5b5c80-2ae4-11ea-800e-bd327aec5160.jpg)
配置文件我一直没有改

**Comment by Kr328** [comment]
如果是在**快速重启**应用后出现
那就是预期的 **DNS映射丢失**

**Comment by Forty-nine** [comment]
请问如何解决？

**Comment by Kr328** [comment]
预期行为
无法解决

**Comment by Forty-nine** [comment]
关闭 cfa 一分钟后，重启打开cfa vpn，依旧如此。
邮件 app ，访问 imap.gmail.com 端口 993 就会出现

**Comment by Kr328** [comment]
一分钟太短了 部分应用的 DNS 缓存持续时间 高达 10-20 分钟
