### ISSUE TITLE
[Feature Request] 单个节点测速和群组切换

### ISSUE THREAD

**Issue by xiandu999-yu** [Kr328/ClashForAndroid#620]
**功能描述**
单个节点延迟测试和群组切换

**描述你希望的实现方式**
长按对应节点进行延迟测试；右下角增加个按钮打开二级菜单，一键测试当前组延迟、外部引用和群组（和外部引用一样的界面[可以隔空测延迟？]）

**附加信息**
对单个节点延迟测试应该会节约一丁点时间吧...以及二级菜单对单手操作的方便性。

**Comment by Mit2g** [comment]
下拉即可对当前组测试延迟

**Comment by xiandu999-yu** [comment]
> 下拉即可对当前组测试延迟

这个我知道...

**Comment by Kr328** [comment]
无法实现

**Comment by xiandu999-yu** [comment]
> 无法实现

啊这....
