### ISSUE TITLE
[Feature Request] 关于节点选择时的文字滚动

### ISSUE THREAD

**Issue by ljq2333** [Kr328/ClashForAndroid#621]
>
![1599394512397](https://user-images.githubusercontent.com/39020075/92325478-c2689c00-f010-11ea-92ff-da3f44fe3749.jpg)
我看不到全部的节点信息

**功能描述**
请清晰的描述你想要的功能

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
单列模式 请

**Comment by ljq2333** [comment]
好吧,虽然我不怎么喜欢单例模式╯﹏╰
已赞助2.33
