### ISSUE TITLE
[BUG] Spotify 无法联网

### ISSUE THREAD

**Issue by stars-island** [Kr328/ClashForAndroid#627]
**描述出现的错误**
开启 CFA 的状态下，Spotify 没有联网。

**如何复现该错误**
复现步骤:
1. 安装 app。CFA 所有 app 允许代理 + rule 模式
2. 打开 Spotify，登录帐号
3. 或者，打开已经登录的 Spotify，等待加载页面
4. 出现 无互联网连接 的 错误提示

**预期行为**
Spotify的流量被代理，并且正常联网，页面正常加载，能听音乐。

**屏幕截图**
![Screenshot_20200908-172829__01](https://user-images.githubusercontent.com/66160777/92459101-d5d65b80-f1f8-11ea-8b74-a1b48d0057d8.jpg)

![Screenshot_20200908-172836__01](https://user-images.githubusercontent.com/66160777/92459112-d969e280-f1f8-11ea-9f99-c4ccd7b2dda2.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Oneplus 5
 - 系统/ROM: OxygenOS
 - Android 版本 10
 - ROM版本 10.0.0

**应用信息**
 - 版本: 2.1.6
 - 安装包文件名: 2.1.6-arm64-v8a.apk
 - 应用来源: Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```
配置文件检查过，Spotify 对应的规则归为国外媒体，其流量会被代理。

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
@stars-island 日志呢 配置呢 要不手机寄给我

**Comment by stars-island** [comment]
**日志：**  

Logcat

21:03:33 |Info| [TCP] 172.31.255.253:42909 --> gae2-accesspoint-b-3z4r.ap.spotify.com match DomainSuffix(spotify.com) using 🎬国外媒体

21:03:44 |Info| [TCP] 172.31.255.253:43719 --> gae2-accesspoint-b-xtpm.ap.spotify.com match DomainSuffix(spotify.com) using 🎬国外媒体

21:03:47 |Info| [TCP] 172.31.255.253:44331 --> gae2-accesspoint-b-s6j6.ap.spotify.com match DomainSuffix(spotify.com) using 🎬国外媒体

21:03:48 |Info| [TCP] 172.31.255.253:38204 --> app.adjust.com match Domain(app.adjust.com) using DIRECT

21:03:50 |Info| [TCP] 172.31.255.253:46837 --> i.scdn.co match DomainSuffix(scdn.co) using 🎬国外媒体

21:03:50 |Info| [TCP] 172.31.255.253:46839 --> i.scdn.co match DomainSuffix(scdn.co) using 🎬国外媒体

21:03:52 |Info| [TCP] 172.31.255.253:46845 --> i.scdn.co match DomainSuffix(scdn.co) using 🎬国外媒体

21:03:57 |Info| [TCP] 172.31.255.253:44930 --> gae2-accesspoint-b-pwbw.ap.spotify.com match DomainSuffix(spotify.com) using 🎬国外媒体

21:04:05 |Info| [TCP] 172.31.255.253:40511 --> guc3-accesspoint-b-0j5x.ap.spotify.com match DomainSuffix(spotify.com) using 🎬国外媒体

21:04:10 |Warning| dial DIRECT error: dial tcp4 185.151.204.6:443: i/o timeout


**配置：**

  port: 1081
  socks-port: 1080  
  redir-port: 1082
  mixed-port: 1080  
  mode: Rule
  log-level: info

  proxy-groups:
      name: 🎬国外媒体
      type: select
      proxies:
        - 🔰国外流量

      name: 🚀直接连接
      type: select
      proxies:
        - DIRECT

**Comment by AkariiinMKII** [comment]
@stars-island 这不是好好连着的吗

**Comment by stars-island** [comment]
刚才再打开 Spotify 就发现又好了，暂时没有无法连接互联网的问题。谢谢解惑！

估计又是玄学问题了……下一次出问题的时候再说吧，现在能用就算了 o(TヘTo)

**Comment by xuhaoyang** [comment]
@stars-island 这种更像节点问题

**Comment by stars-island** [comment]
啊这……

我在配置文件里，将

log-level 只有改为 info 的时候，Spotify 可以联网；
               
改成其它的选项时，均无法联网……

**Comment by stars-island** [comment]
> @stars-island 这种更像节点问题

个人觉得，节点应该没啥大问题的，我在电脑上用 CFW 也能正常打开使用 spotify 的服务呀…… /(ㄒoㄒ)/~~

**Comment by Mit2g** [comment]
大概率节点问题 如果网络允许建议直连 不允许的情况请多尝试其他节点

**Comment by stars-island** [comment]
感谢解答。后面多尝试了几遍，发现确实有些节点存在问题，多换几个确实就好了。可能是节点本身的某些技术问题吧
