### ISSUE TITLE
[Feature Request] 更新 geoip 库

### ISSUE THREAD

**Issue by ygsk10** [Kr328/ClashForAndroid#628]
**功能描述**

规则中设置 GEOIP,CN,Domestic 较高优先级 后目前的 geoip 库将大量 Wikipedia 甚至 Google、Twitter 的 IP 认定为 Domestic

**描述你希望的实现方式**

在下一次分发的 APK 包中更新 Country.mmdb，或者给用户自定义更新源的选项

**附加信息**

**Comment by Kr328** [comment]
你这不考虑抗 DNS 污染 而是去 让更新 GEOIP 谁救的了

**Comment by Kr328** [comment]
顺便 每次打包 apk 都会更新 GEOIP

**Comment by ygsk10** [comment]
![Screenshot_20200908-194554](https://user-images.githubusercontent.com/60314251/92472424-02e03980-f20c-11ea-95ba-188891019e57.png)

**Comment by Kr328** [comment]
@ygsk10 你从哪看出来 GEOIP 有问题的

**Comment by ygsk10** [comment]
> @ygsk10 你从哪看出来 GEOIP 有问题的

这些 IP 是正确的。但是被判定直连

**Comment by Kr328** [comment]
@ygsk10 截图里一个命中直连的日志都没有

**Comment by MarksonHon** [comment]
@ygsk10 在你的配置里面，Domestic 是个啥组？如果是代理组，那就没毛病。

**Comment by ygsk10** [comment]
> @ygsk10 在你的配置里面，Domestic 是个啥组？如果是代理组，那就没毛病。

这个组我指定的直连，如果是代理组有问题应该会出现到 代理服务器的 time out 日志

**Comment by Kr328** [comment]
timeout 不代表任何问题

`[TCP] xxxx -> xxxx using ` 开头的 才能说明 命中了那个规则

**Comment by AkariiinMKII** [comment]
@ygsk10 麻烦命中geoip,cn的日志来一个

**Comment by ygsk10** [comment]
> @ygsk10 麻烦命中geoip,cn的日志来一个

只有连接成功才会显示命中某种规则，否则只是 timeout。
比如我把 '+.doubleclick.net':0.0.0.0 写入 hosts，之后指定 DOMAIN-KEYWORD,doubleclick,DIRECT
这样日志中只会出现 到 0.0.0.0 的 timeout，不会显示 doublick 域名或者命中某规则

**Comment by Kr328** [comment]
那么 上面的 SUFFIX 已经正确命中了 难道不应该考虑 增强规则吗

顺便一提 GEOIP 的 这个 IP 区域号 确实是 CN

**Comment by ygsk10** [comment]
> 那么 上面的 SUFFIX 已经正确命中了 难道不应该考虑 增强规则吗
> 
> 顺便一提 GEOIP 的 这个 IP 区域号 确实是 CN

那是因为 GEOIP 规则位于 SUFFIX 前列，这样可以避免很多问题。
？？ ipip.net 查询的结果是 HK

**Comment by Kr328** [comment]
我是不明白 geoip 放在前面有什么好处 一来不能抗污染 二来 在 fake-ip 模式会做额外的 DNS 查询提高连接延迟

![image](https://user-images.githubusercontent.com/39107975/92475760-7f751700-f210-11ea-838f-6a574f9451b4.png)

**Comment by ygsk10** [comment]
> 我是不明白 geoip 放在前面有什么好处 一来不能抗污染 二来 在 fake-ip 模式会做额外的 DNS 查询提高连接延迟
> 
> https://www.maxmind.com/en/geoip-demo
> 
> ![image](https://user-images.githubusercontent.com/39107975/92475760-7f751700-f210-11ea-838f-6a574f9451b4.png)

那就是 GEOIP 库有问题了,这个地理位置甚至是 河南郑州。

**Comment by Kr328** [comment]
@ygsk10 Clash 向来不推荐只依赖 IP 判断路径 为什么优先使用域名规则呢

**Comment by AkariiinMKII** [comment]
> > @ygsk10 麻烦命中geoip,cn的日志来一个
> 
> 只有「连接成功」才会显示命中某种规则，否则只是 timeout。
> 比如我把 '+.doubleclick.net':0.0.0.0 写入 hosts，之后指定 DOMAIN-KEYWORD,doubleclick,DIRECT
> 这样日志中只会出现 到 0.0.0.0 的 timeout，不会显示 doubeclick 域名或者命中某规则（日志截图中的WAENING行就是这样的）

别走direct不就能看到了![Screenshot_20200908-203655.png](https://user-images.githubusercontent.com/6019344/92477429-2ce92a00-f213-11ea-8d36-73dfc932c93d.png)

**Comment by ygsk10** [comment]
> > > @ygsk10 麻烦命中geoip,cn的日志来一个
> > 
> > 
> > 只有「连接成功」才会显示命中某种规则，否则只是 timeout。
> > 比如我把 '+.doubleclick.net':0.0.0.0 写入 hosts，之后指定 DOMAIN-KEYWORD,doubleclick,DIRECT
> > 这样日志中只会出现 到 0.0.0.0 的 timeout，不会显示 doubeclick 域名或者命中某规则（日志截图中的WAENING行就是这样的）
> 
> 别走direct不就能看到了![Screenshot_20200908-203655.png](https://user-images.githubusercontent.com/6019344/92477429-2ce92a00-f213-11ea-8d36-73dfc932c93d.png)

只有「连接成功」才会显示命中某种规则

**Comment by AkariiinMKII** [comment]
@ygsk10 你看我不是「连接成功」了嘛（然后答案也出来了）

**Comment by ygsk10** [comment]
> @ygsk10 你看我不是「连接成功」了嘛（然后答案也出来了）

可是这是 GEOIP 库的问题

**Comment by AkariiinMKII** [comment]
@ygsk10 我们讨论的不是「麻烦命中geoip,cn的日志来一个」嘛

**Comment by ygsk10** [comment]
> @ygsk10 我们讨论的不是「麻烦命中geoip,cn的日志来一个」嘛

那只有一行，并且日志不会显示 hosts 指定的 IP 的
![Screenshot_20200908-205215](https://user-images.githubusercontent.com/60314251/92478781-42f7ea00-f215-11ea-8ef6-98382e4d8c72.png)

**Comment by ygsk10** [comment]
> @ygsk10 Clash 向来不推荐只依赖 IP 判断路径 为什么优先使用域名规则呢

优先使用域名规则当然也可以解决问题，只是 GEOIP 库还是不准确的。

**Comment by Kr328** [comment]
@ygsk10 对啊 是这样 所以为什么要引入域名判断 懂了吧

**Comment by MarksonHon** [comment]
@ygsk10 今天中国国内的一个IP，明天就可能被ISP或云服务主机上用到英国去，用IP库累不累啊~

**Comment by ygsk10** [comment]
> @ygsk10 今天中国国内的一个IP，明天就可能被ISP或云服务主机上用到英国去，用IP库累不累啊~

不是这样的，亚洲的 IP 不会轻易重分配到欧洲。（大概

**Comment by ygsk10** [comment]
> @ygsk10 对啊 是这样 所以为什么要引入域名判断 懂了吧

所以 GEOIP 库 的问题 没有计划解决吗？比如更换数据源之类的

**Comment by Kr328** [comment]
@ygsk10 放心吧 必然不可能换

**Comment by EKyero** [comment]
@ygsk10 https://github.com/Kr328/ClashForAndroid/issues/411#issuecomment-640780469

**Comment by ygsk10** [comment]
#- DOMAIN,zh.wikipedia.org,V2-Y #103.56.16.112,HK
- DOMAIN,r3---sn-i3b7kns6.googlevideo.com,V2-Y #118.107.180.216,HK

**Comment by wpzzz** [comment]
> 

两年之后，我遇到了和你一样的问题，103.56.16.112依旧被判为CN 哈哈

**Comment by Longway22** [comment]
> 两年之后，我遇到了和你一样的问题，103.56.16.112依旧被判为CN 哈哈

@wpzzz 总之我觉得这是作者的问题，IP判断出错明显是bug，他却把其他的迂回解决方法当作金科玉律，加什么域名规则，像个脑残。
