### ISSUE TITLE
[BUG] +新配置 > 从文件导入 时打开的是我的电话簿，而不是文件浏览器

### ISSUE THREAD

**Issue by dotAge** [Kr328/ClashForAndroid#629]
**Describe the bug**
+新配置 > 从文件导入 时打开的是我的电话簿，而不是文件浏览器

**To Reproduce**
1. Go to '主界面'
2. Click on '配置'
3. Click on '+ 新配置'
4. Click on '文件'
5. 电话通讯录被打开

**Expected behavior**
一个文件浏览器

**Device Info (please complete the following information):**

 - Device: [Nubia Z17 (NX563J)]
 - ROM: [NX563J_CNCommon_v4.06]
 - ROM Version:4.06
 - Android Version [7.1.1]

**Application Info (please complete the following information):**

 - Version: [2.1.6-arm64-v8a]
 - Apk File Name: [app-arm64-v8a-release.apk]
 - Distribution Channel: [GITHUB]

**Comment by Kr328** [comment]
去给你的 ROM 厂商反馈

应用遵循 Android 标准打开文件 而你的 ROM 厂商并不
