### ISSUE TITLE
[BUG] Android 11版本的指定hosts失效

### ISSUE THREAD

**Issue by hepingsicilia** [Kr328/ClashForAndroid#637]
**描述出现的错误**
在Android 11中，原本定义的自定义hosts没有生效，导致程序还是会使用默认DNS返回的IP

**如何复现该错误**
复现步骤:
1. 开启Clash
2. 观察`*#*#426#*#*`中的Host项

**预期行为**
程序应该使用配置文件里定义的hosts IP去连接，不是DNS结果

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![Screenshot_20200914-103631](https://user-images.githubusercontent.com/62328246/93040467-aaca8c80-f67c-11ea-9384-4d8debcb6611.png)
![Screenshot_20200914-102242](https://user-images.githubusercontent.com/62328246/93040493-b9b13f00-f67c-11ea-8cf6-60e4432294eb.png)
![Screenshot_20200914-112445](https://user-images.githubusercontent.com/62328246/93040558-e06f7580-f67c-11ea-8c42-4095ceadaa9d.png)

**设备信息 (请完成以下信息):**
 - 机型: Pixel 4XL
 - 系统/ROM: Android 11 正式版
 - Android 版本 11
 - ROM版本 RP1A.200720.009

**应用信息**
 - 版本: 2.1.6-universal
 - 安装包文件名: app-universal-release.apk
 - 应用来源: GitHub release page

**附加信息**
在三星Note10+最新9月份补丁中没有看到这个问题，版本是Android 10，build N975U1UES4CTH1

**配置文件**
使用自建节点，其他配置没有变更
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/Global.yaml

**日志**
如果适用, 粘贴日志以帮助侦测错误
![Screenshot_20200914-102229](https://user-images.githubusercontent.com/62328246/93040385-7951c100-f67c-11ea-8f74-856836963cc0.png)

**Comment by Kr328** [comment]
预期行为

Clash 会通过 redir-host 反解域名 设定的 hosts 会在 Clash 转发时才生效 除非开启 DNS 服务的 `use-hosts`

**Comment by hepingsicilia** [comment]
@Kr328 作者您好
我按照您所说的在配置里面加上了`use-hosts: true` 这一配置，但是实际的请求还是走了默认DNS的IP
![Screenshot_20200914-123243](https://user-images.githubusercontent.com/62328246/93044152-912e4280-f686-11ea-9983-746e7ba1ea6d.png)
![Screenshot_20200914-123135](https://user-images.githubusercontent.com/62328246/93044163-97242380-f686-11ea-8427-b4a723228a80.png)
![Screenshot_20200914-123129](https://user-images.githubusercontent.com/62328246/93044164-9a1f1400-f686-11ea-90c2-2961c2a556ae.png)
![Screenshot_20200914-123438](https://user-images.githubusercontent.com/62328246/93044177-a4411280-f686-11ea-8cdf-8a84f483ce6b.png)

**Comment by AkariiinMKII** [comment]
@hepingsicilia listen不能低于1024

**Comment by Kr328** [comment]
@hepingsicilia DNS 复写里 DNS 策略调整到 使用配置 了吗

**Comment by hepingsicilia** [comment]
> @hepingsicilia DNS 复写里 DNS 策略调整到 使用配置 了吗

@Kr328 您好，我看了一下之前为`use built-in`，刚刚尝试更改到`Preferred config`， 并没有解决

**Comment by hepingsicilia** [comment]
> @hepingsicilia listen不能低于1024

您好，在我的印象中这个并不影响Clash对域名的请求以及处理

**Comment by hepingsicilia** [comment]
@Kr328 
您好，非常抱歉我想我应该知道什么原因了
看来Android 11会把`142.250.101.188`这个IP当作在开启VPN以后的默认placeholder(WiFi路由器科学的时候会显示正确连接IP)
我手动把之前hosts里面的FCM IP指到了`8.8.8.8`发现Clash会处理请求并对它去发起连接
![Screenshot_20200914-131039](https://user-images.githubusercontent.com/62328246/93046374-3566b800-f68c-11ea-892d-b10be370b1c9.png)

实际上我一直连接的都是hosts里面指定的地址
再次感谢您的回复
