### ISSUE TITLE
[BUG] 打开控制应用列表就fc

### ISSUE THREAD

**Issue by fanghuan27** [Kr328/ClashForAndroid#638]
**描述出现的错误**
我是Android 8.0类原生系统，大概从2.0版本之后，打开控制应用包列表就会fc。回到1.3.2版本可以正常打开。

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![Screenshot_20200914-180959](https://user-images.githubusercontent.com/1284794/93073974-4e845e80-f6b6-11ea-9e5f-0d352c2bdfa6.png)
![Screenshot_20200914-180946](https://user-images.githubusercontent.com/1284794/93073983-504e2200-f6b6-11ea-865b-be8748b54047.png)

**设备信息 (请完成以下信息):**
 - 机型: [例如: Xperia xzs]
 - 系统/ROM: []
 - Android 版本 [例如: 8.0]
 - ROM版本 []

**应用信息**
 - 版本: [例如: 2.1.6]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
fc后重新启动日志就会清空
```

**Comment by xuhaoyang** [comment]
adb bugreport 

https://developer.android.com/studio/debug/bug-report?hl=zh-cn

建议参照后提供后方便开发者调试

**Comment by 4512369781** [comment]
系统版本 索尼BRAVIA 安卓9
软件版本 v2.1.6 v7a

从v2.0.18升级后，我在电视上也打不开，但是没有出现崩溃，只是按了后没有任何反应。

**Comment by Kr328** [comment]
#768
