### ISSUE TITLE
[Feature Request] 希望能添加单节点延迟测试

### ISSUE THREAD

**Issue by lumo0095** [Kr328/ClashForAndroid#641]
**功能描述**
因为机场禁止批量延迟测试，希望能添加类似于CFW那样的单节点测试
**描述你希望的实现方式**
节点后方添加闪电图标或check或者长按节点
**附加信息**
希望添加下拉批量测试的开关，上次误操作差点封号~~~

**Comment by Kr328** [comment]
#620
