### ISSUE TITLE
[Feature Request] 无网络的情况下减少或终止自动重连的功能

### ISSUE THREAD

**Issue by sjdhome** [Kr328/ClashForAndroid#642]
**功能描述**
请清晰的描述你想要的功能
如标题所示，在现有情况下如果将WiFi和数据网络都关闭（比如晚上睡觉时），
Clash日志中会出现`connect: network is unreachable`，且每隔几分钟会再次重试（注：并非节点连不上），
造成手机被频繁唤醒，且每隔几分钟就会再次重试。在信号不好的地区也可能出现这种情况。
考虑到方便性和Google框架，每次手动关闭Clash也不太好。
希望能在网络状况不佳或无网络时减少或终止自动重连的功能。
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
可以增加每次重试间隔的时间，或直接检测系统网络是否连接。
**或提供用于关闭和开启的Intent，以便在Tasker上触发。**

**附加信息**
其他的与改功能相关的附加信息
![XTV1Y5%EN)J8(6QCVR86@KW](https://user-images.githubusercontent.com/11871061/93662030-5285f700-fa8f-11ea-807a-5343d7eec839.png)

**Comment by Kr328** [comment]
现在熄灭屏幕的时候会停止一切的内部定时任务

图中 出现的 Dial 不是由 Clash 发起 而是手机内部的其他应用

既然其他应用能够 connect 也就意味着 手机已经被唤醒

难道不应该去找其他应用的问题吗
