### ISSUE TITLE
[BUG] 无法创建配置 

### ISSUE THREAD

**Issue by TiAmo-chen** [Kr328/ClashForAndroid#644]
**描述出现的错误**
创建配置时，无论是从URL导入 还是从文件导入都失败

**如何复现该错误**
复现步骤:
1. 添加就复现失败
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![IMG_20200920_134623.png](http://ww1.sinaimg.cn/large/007B7hvuly1gix2m9mlszj30wa1wdgxh.jpg)

**设备信息 (请完成以下信息):**
 - 机型: redmi k20Pro
 - 系统/ROM: MIUI12 
 - Android 版本 10
 - ROM版本20.9.17

**应用信息**
 - 版本: 2.1.5-arm64-v8a
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml

```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/365
