### ISSUE TITLE
proxy only mode下无法翻墙

### ISSUE THREAD

**Issue by jiahe224** [Kr328/ClashForAndroid#65]
切换到这个模式下，开关上的流量统计为 0 bytes Forwarded，但微信等能上，想chrome里用Google只能用VPN模式，另VPN下配置文件里的规则是否还有效？如果有效那就先凑合用，但感觉无效，因为好多广告还在

**Comment by Kr328** [comment]
预期行为

Proxy Only 需要 **手动配置** 代理流量通过 Clash

**Comment by Kr328** [comment]
域名规则 需要 配合 合理的 DNS 

具体参见
https://blog.skk.moe/post/what-happend-to-dns-in-proxy/

**Comment by jiahe224** [comment]
> 预期行为
> 
> Proxy Only 需要 **手动配置** 代理流量通过 Clash

我用的这里的规则：https://github.com/ConnersHua/Profiles/blob/master/Clash/Pro.yaml
感觉没问题，如果有问题，能否出一个配套的yaml文件模板呢？没有订阅的可用

**Comment by Kr328** [comment]
规则没问题

广告过滤在 **没有MITM** 很难完整实现
想要更优秀的广告过滤 请使用 **AdGuard**

**Comment by jiahe224** [comment]
> 规则没问题
> 
> 广告过滤在 **没有MITM** 很难完整实现
> 想要更优秀的广告过滤 请使用 **AdGuard**

规则对的话，那为何chrome里打不开Google呢，对网络一窍不通(lll￢ω￢)
之前试过 AdGuard，但和 V2ray 等应用不能同时开着，然后网友说 AdGuard 不能屏蔽微信公众号广告，我就没再折腾了

**Comment by Kr328** [comment]
> 预期行为
> 
> Proxy Only 需要 **手动配置** 代理流量通过 Clash

大声朗读 10 遍

**Comment by jiahe224** [comment]
> > 预期行为
> > Proxy Only 需要 **手动配置** 代理流量通过 Clash
> 
> 大声朗读 10 遍

不好意思，我是这么转换的，可能有错：
手动配置→要有规则→已有规则且你说没问题，然后还不能翻墙，所以我就晕了。
然后就是不知VPN模式下规则是否有效？有效的话我就不折腾Proxy Only，无效的话那就继续折腾

**Comment by jiahe224** [comment]
> 规则没问题
> 
> 广告过滤在 **没有MITM** 很难完整实现
> 想要更优秀的广告过滤 请使用 **AdGuard**

不知后期能加入脚本支持吗？得知网友用圈的脚本功能来屏蔽微信公众号的广告，但目前安卓平台还没有支持脚本的代理App，急需从0到1.

**Comment by Kr328** [comment]
> > > 预期行为
> > > Proxy Only 需要 **手动配置** 代理流量通过 Clash
> > 
> > 
> > 大声朗读 10 遍
> 
> 不好意思，我是这么转换的，可能有错：
> 手动配置→要有规则→已有规则且你说没问题，然后还不能翻墙，所以我就晕了。
> 然后就是不知VPN模式下规则是否有效？有效的话我就不折腾Proxy Only，无效的话那就继续折腾

1. 有效
2. 规则不是很强

**Comment by Kr328** [comment]
> > 规则没问题
> > 广告过滤在 **没有MITM** 很难完整实现
> > 想要更优秀的广告过滤 请使用 **AdGuard**
> 
> 不知后期能加入脚本支持吗？得知网友用圈的脚本功能来屏蔽微信公众号的广告，但目前安卓平台还没有支持脚本的代理App，急需从0到1.

返回上游 Clash 请
