### ISSUE TITLE
[BUG] google app在wifi和4g来回切换后不能联网

### ISSUE THREAD

**Issue by neo16ye** [Kr328/ClashForAndroid#655]
**描述出现的错误*
手机在wifi和4g网络条件来回切换一两次后，4g下google应用就不能联网了，但我试过此时其他应用是可以联网的，这时只有把clash关了再开，google app才能恢复联网。测试surfboard也有该问题，ssrr正常，节点都是使用机场订阅。
*如何复现该错误**
复现步骤:
1. ...见上
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型:pixel 4 xl
 - 系统/ROM:android 11
 - Android 版本 11
 - ROM版本 [例如: 20.3.19

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by levis0792** [comment]
我也反馈了这个问题，是切换后谷歌服务连不上了。

**Comment by Kr328** [comment]
日志 配置 请

**Comment by ZerowindSE** [comment]
一加6同样出现这个问题，H2OS版本10.0.6，Clash版本为最新。
重启clash甚至重启手机均无法解决此问题，twitter和浏览器可以被代理，只有google play不行。
clash中日志显示一切正常，粒度debug（[TCP] xx.x.xxx.xxx:xxxx ->> xxx.xxx.xxx.xxx using global）。
google play返回连接超时。

**Comment by uoox** [comment]
![Uploading Screenshot_20200929-124253.jpg…]()

**Comment by uoox** [comment]
![Uploading Screenshot_20200929-124253.jpg…]()

**Comment by uoox** [comment]
#120 #191

**Comment by uoox** [comment]
![Uploading dep6h-qz5q3.gif…]()

**Comment by uoox** [comment]
![dep6h-qz5q3](https://user-images.githubusercontent.com/31897243/94790122-6ffc7e80-0408-11eb-9463-d1a983a9b2f6.gif)

**Comment by yswtrue** [comment]
一样有这个问题

**Comment by auqfgmd** [comment]
这个问题很严重  好像用机场都有这个问题
