### ISSUE TITLE
[Feature Request] 希望支持Trojan-go

### ISSUE THREAD

**Issue by jinhill** [Kr328/ClashForAndroid#658]
**功能描述**
Trojan-go 支持CDN流量中转(基于WebSocket over TLS/SSL)，兼容Trojan，https://github.com/p4gefau1t/trojan-go

**描述你希望的实现方式**
添加节点的选项增加trojan-go，比trojan多了WebSocket配置

**附加信息**
无

**Comment by Kr328** [comment]
去上游 请
