### ISSUE TITLE
偶尔出现Google feed刷新失败

### ISSUE THREAD

**Issue by VVMiao** [Kr328/ClashForAndroid#66]
偶尔出现Google feed刷新失败，play商店连接失败，Google assistant连接失败。墙洞同一节点用surfboard又不会出现这种情况。两台pixel Android Q都一样问题。清Google [App缓存有时能短暂恢复正常刷新，但很快又不行
![image](https://user-images.githubusercontent.com/39823489/71610337-fca0b480-2bca-11ea-80a2-7a9ab23d5ab1.png)这个是正常刷新成功的logs
![image](https://user-images.githubusercontent.com/39823489/71610350-1641fc00-2bcb-11ea-9d64-e3a8cb316ee2.png)这个是无法刷新的
请问是clash的问题还是节点的问题呢？

**Comment by Kr328** [comment]
发送你 **脱敏后的** 配置文件

**Comment by VVMiao** [comment]
> 发送你 **脱敏后的** 配置文件

请问 脱敏后的 是? 就订阅的配置文件吗

**Comment by Kr328** [comment]
> > 发送你 **脱敏后的** 配置文件
> 
> 请问 脱敏后的 是? 就订阅的配置文件吗

去除 节点信息 之类的 敏感信息 后的 配置文件

**Comment by VVMiao** [comment]
[Dler Cloud.txt](https://github.com/Kr328/ClashForAndroid/files/4011943/Dler.Cloud.txt)

**Comment by VVMiao** [comment]
> > > 发送你 **脱敏后的** 配置文件
> > 
> > 
> > 请问 脱敏后的 是? 就订阅的配置文件吗
> 
> 去除 节点信息 之类的 敏感信息 后的 配置文件

这个删了除平时用的节点外的其他节点信息

**Comment by VVMiao** [comment]
![image](https://user-images.githubusercontent.com/39823489/71649692-b4f56680-2d4b-11ea-915f-0151d0db70a2.png)
这就是手动刷新失败的情况，就算失败一般反应也很快，不像是无法连接或没挂梯子的那样

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
