### ISSUE TITLE
[BUG] 使用已经转换好的clash链接无法下载订阅（Android 版）

### ISSUE THREAD

**Issue by MCER2020** [Kr328/ClashForAndroid#661]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. ...在添加订阅的时候选择从URL导入
2. ...在填好地址之后点保存
3. ...弹出下载失败（有多次出现不同理由）
4. ...在网站上浏览我复制的订阅链接是可以看到东西的
![Screenshot_20200930-184236](https://user-images.githubusercontent.com/62318945/94676457-ef794780-034d-11eb-84c1-fc523eff568f.jpg)

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![Screenshot_20200930-185020](https://user-images.githubusercontent.com/62318945/94676370-d2dd0f80-034d-11eb-9be8-d4c1a978b547.jpg)
![Screenshot_20200930-185025](https://user-images.githubusercontent.com/62318945/94676384-d7092d00-034d-11eb-9fa7-9bf5fc1f509b.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 一加8Pro
 - 系统/ROM: 氢OS10.5.14
 - Android 版本 10
 - ROM版本  10.5.14 IN11

**应用信息**
 - 版本: 2.1.5
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/365
