### ISSUE TITLE
[Feature Request] 与adguard共存方法？

### ISSUE THREAD

**Issue by zif68** [Kr328/ClashForAndroid#664]
clash for android与adguard共存的详细设置过程，谢谢！
我自己设置的总有一些问题，代理不全。

**Comment by Liu0802** [comment]
adguard代理添加socks5并且输入127.0.0.1:7891，clash关闭设置-网络-自动路由系统流量。先开启adguard，再开启代理，然后开启clash。

**Comment by Kr328** [comment]
自行使用搜索引擎

**Comment by zif68** [comment]
共存搞定了，但代理上不稳定，有的可以，有的不走代理，搞得头痛啊！就是时有时无，也不知道具体原因。

**Comment by Liu0802** [comment]
你可以看一下左上角里的应用管理，那里有应用通过的管理。

**Comment by zif68** [comment]
> 你可以看一下左上角里的应用管理，那里有应用通过的管理。

你说的是设置走代理的应用，就是我设置了走代理的应用，有时候它不走代理，例如，YouTube app 走代理没有反应，但Chrome上YouTube又可以，，总之代理不稳定，时有时无。

**Comment by benchow18** [comment]
同样的问题，虽然可以共存，但是无法连接网络

**Comment by Tdctao** [comment]
> adguard代理添加socks5并且输入127.0.0.1：7891，clash关闭设置-网络-自动路由系统流量。先开启adguard，再开启代理，然后开启clash。

好用

**Comment by asher-001** [comment]
YouTube同样无法使用

**Comment by asher-001** [comment]
> 

解决了嘛。碰到了一模一样的问题，求解求解

**Comment by asher-001** [comment]
> > 你可以看一下左上角里的应用管理，那里有应用通过的管理。
> 
> 你说的是设置走代理的应用，就是我设置了走代理的应用，有时候它不走代理，例如，YouTube app 走代理没有反应，但Chrome上YouTube又可以，，总之代理不稳定，时有时无。

解决了嘛？碰到了一模一样的问题，求解一下

**Comment by xsgteamx** [comment]
> adguard代理添加socks5并且输入127.0.0.1:7891，clash关闭设置-网络-自动路由系统流量。先开启adguard，再开启代理，然后开启clash。

# 亲测有效 ,adguard v3.6.11 与 clash Android进行共存
1. adguard代理添加socks5并且输入127.0.0.1:你的端口
2. clash关闭设置-网络-自动路由系统流量。
3. 记得设置DNS自定义,现在clash中设置DNS监听地址 [例如:更改为 127.0.0.1:50053]
4. 然后在ADG中更改自定义DNS为 127.0.0.1:50053
5. 先开启adguard，再开启代理，然后开启clash。
# 其他
 如果各位知道最新版的 4.0 adg 如何设置 请通知我!感谢!
