### ISSUE TITLE
想问下配置文件config的目录在哪里？想自己添加一些规则

### ISSUE THREAD

**Issue by zhongqiujie13** [Kr328/ClashForAndroid#67]
手机root了，找了半天也没有找到配置文件！能否告知一下，谢谢了

**Comment by Kr328** [comment]
@zhongqiujie13 /data/data/com.github.kr328.clash/files/profiles

**Comment by alian1126** [comment]
/data/data/com.github.kr328.clash/files/profiles
安卓手机好像没有找到这个路径？
