### ISSUE TITLE
[Feature Request] 加入类似clash of windows 一样的Country.mmdb

### ISSUE THREAD

**Issue by LittleRey** [Kr328/ClashForAndroid#670]
**功能描述**
加入类似clash of windows 一样的Country.mmdb，可以直接通过本地geoIp方式直接查询IP， 类似- GEOIP,CN,Direct，免去大量Doh的查询

**描述你希望的实现方式**
加入本地Country.mmdb

**附加信息**
其他的与改功能相关的附加信息

**Comment by EKyero** [comment]
@LittleRey 一直有

**Comment by LittleRey** [comment]
@EKyero 请问，本地的country.mmdb文件在哪，我想更新一下

**Comment by EKyero** [comment]
@LittleRey https://github.com/Kr328/ClashForAndroid/issues/411
