### ISSUE TITLE
[Feature Request] 流量统计

### ISSUE THREAD

**Issue by waldens** [Kr328/ClashForAndroid#671]
**功能描述**
不好意思不是功能请求，是单纯提问帖

Clash for Windows 目前的流量统计，是包含直连和走代理 两部分的流量。部分网友有提功能请求，希望能显示只走代理的这部分流量统计（毕竟 PC 端多数人不关心直连跑了多少吧，要关心也是花钱的✈️流量套餐用了多少），作者 Fndroid 的解释是“Clash Core 的 API 只会给出上下行，没有其他数据”，即需要向上游提功能请求

但 **Clash for Android 主界面的“已转发”，统计的就是仅走代理的流量，那 Clash for Android 是怎么实现这功能的？** 难道没有依赖 Clash Core，是自己写的吗？

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
Clash for Android 使用**动态链接**的方式执行 Clash 而不是 运行 core 二进制 并 使用 http api

同时对 clash core 做了一些适用于 Android 的修改
