### ISSUE TITLE
[BUG] 取消勾选“过滤系统应用”后仍无法看见系统应用

### ISSUE THREAD

**Issue by lomomcat** [Kr328/ClashForAndroid#673]
**描述出现的错误**
“访问控制应用包列表”中，默认是过滤系统应用的，但是我取消勾选“过滤系统应用”后仍看不见系统应用，也无法下滑刷新，重进“访问控制应用包列表”中还是默认勾选了“过滤系统应用”

**如何复现该错误**
复现步骤:
1. 打开“设置”
2. 打开“网络”
3. 打开“访问控制应用包列表”
4. 取消过滤系统应用

**预期行为**
白名单模式下系统应用总是被代理，我想让部分系统应用不被代理，比如“系统更新”“应用商店”等。正常情况我取消过滤系统应用后可以勾选系统应用。

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![Screenshot_2020-10-06-23-13-00-897_com.github.kr328.clash.jpg](https://user-images.githubusercontent.com/62339707/95220930-8ef47980-0829-11eb-992e-0cce2d11c8ba.jpg)
![Screenshot_2020-10-06-23-13-10-244_com.github.kr328.clash.jpg](https://user-images.githubusercontent.com/62339707/95220984-987de180-0829-11eb-878b-487a01b86810.jpg)
![Screenshot_2020-10-06-23-13-18-123_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/62339707/95221029-9e73c280-0829-11eb-9ce5-f075c70677df.jpg)

**设备信息 (请完成以下信息):**
 - 机型:小米10至尊纪念版 [例如: Pixel 4]
 - 系统/ROM:MIUI12 [例如: MIUI 11]
 - Android 版本 10[例如: 10]
 - ROM版本 20.9.29[例如: 20.3.19]

**应用信息**
 - 版本:2.1.6-arm64-v8a [例如: 1.1.10]
 - 安装包文件名:app-arm64-v8a-release.apk [例如: app-release-arm64-v8a.apk]
 - 应用来源:Github/Kr328/ClashForAndroid [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by lomomcat** [comment]
求大大更新

**Comment by Kr328** [comment]
@lomomcat 过滤选项选中才是显示对应的项目

其次 没有请求网络权限的应用 不会显示在列表 因为没有必要
