### ISSUE TITLE
[BUG] v2.1.6耗电量较大（相比于2.0.18）

### ISSUE THREAD

**Issue by sdustbiglong** [Kr328/ClashForAndroid#676]
如题，最新版本v2.1.6耗电量较大，换成play商店里的最新版本v2.0.18就好很多
![S01009-15004119](https://user-images.githubusercontent.com/70256442/95553058-5f6b8a00-0a40-11eb-8aaa-101c552af3b4.jpg)

**设备信息 (请完成以下信息):**
 - 机型: [例如: 魅族16s]
 - 系统/ROM: [例如: Flyme 8]
 - Android 版本 [例如: 9]
 - ROM版本 [例如: 8.1.5.0A]

**应用信息**
 - 版本: [例如: 2.1.6]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: github release]

**Comment by Kr328** [comment]
#505

**Comment by sdustbiglong** [comment]
Hi,I submit a issue about battery in Github.

Kr328 <notifications@github.com> 于 2020年10月9日周五 15:26写道：
