### ISSUE TITLE
[BUG] 一加 黑暗模式 显示 bug

### ISSUE THREAD

**Issue by black-desk** [Kr328/ClashForAndroid#681]
**描述出现的错误**
请简洁的描述你遇到的错误

![Screenshot_20201017-135200.jpg](https://user-images.githubusercontent.com/29726878/96329508-38383c80-1080-11eb-8f79-ecc5178f217f.jpg)

如图

**如何复现该错误**

一加7pro 氧os

最新release universal

**Comment by black-desk** [comment]
系统调为黑暗模式后底色仍然是白的

**Comment by Kr328** [comment]
模板填完 别写什么 最新版 没意义
