### ISSUE TITLE
[BUG] 一加7 氧OS 黑暗模式 渲染错误

### ISSUE THREAD

**Issue by black-desk** [Kr328/ClashForAndroid#682]
**描述出现的错误**

系统调整至黑暗模式后 app 文字颜色变白, 但是底色仍然为白色.

**如何复现该错误**
复现步骤:
从 Release 页面或从 Play Store 下载应用,
调整系统设置 个性化 预置主题 沉浸

**预期行为**
页面底色应该是黑的.

**屏幕截图**

![image](https://user-images.githubusercontent.com/29726878/96331572-ea780000-1090-11eb-8732-1298ff8bb218.png)

**设备信息 (请完成以下信息):**
 - 机型:  OnePlus 7 Pro
 - 系统/ROM: 氧OS
 - Android 版本 10
 - ROM版本 10.3.4GM21AA

**应用信息**
 - 版本: 2.1.5
 - 安装包文件名: app-universal-release.apk
 - 应用来源: Release 页面

**附加信息**
无

**Comment by EKyero** [comment]
@black-desk 哪来的2.5.1?

**Comment by black-desk** [comment]
不好意思 2.1.5

**Comment by Kr328** [comment]
@black-desk 找找 你们 的 ROM 所谓的 强制黑暗模式

对 Clash for Android 关闭

**Comment by black-desk** [comment]
rom 没有强制黑暗模式的开关. 在开发者选项里面找到了一个 override force-dark, 开启后勉强能用.
 
![image](https://user-images.githubusercontent.com/29726878/96333208-20ba7d00-109b-11eb-8b86-90f86764cea9.png)
