### ISSUE TITLE
[BUG] 2.1.5和2.1.6都占用内存大，并经常出现未计入统计的流量占用

### ISSUE THREAD

**Issue by OvOooooooo** [Kr328/ClashForAndroid#683]
**描述出现的错误**
Xperia1mark2，系统近似原生安卓10。
不管是谷歌商店的还是github上的arm64-v8a，在一直开着代理的情况下都出现内存占用大的情况，开发者选项里显示平均占用3g。
并且开着代理时还经常显示有1m/s左右的网速占用，但是统计的流量数据并没有增加。

**使用环境**
1. 没试过其它系统
2. 只装过2.1.5和2.1.6的arm64-v8a
3. 在Xperia xzp上（安卓9）也装过2.1.5，并未出现占用内存大
4. 系统本身没有网速显示功能，装了应用 网速指示计 来实时显示，并开启了使用系统api读取流量的选项。

**预期行为**
希望解决内存占用和流量问题😂多谢开发者大大

**屏幕截图**
图为三小时内内存占用
![Screenshot_20201018-105120](https://user-images.githubusercontent.com/38456160/96357557-f8c92900-112f-11eb-85a2-a697e1f2ed03.png)
图为应用信息
![Screenshot_20201018-105946](https://user-images.githubusercontent.com/38456160/96357639-2b275600-1131-11eb-976f-5df7ad599c87.png)
![Screenshot_20201018-105958](https://user-images.githubusercontent.com/38456160/96357640-2fec0a00-1131-11eb-92ab-d0417d390756.png)
![Screenshot_20201018-110013](https://user-images.githubusercontent.com/38456160/96357641-34182780-1131-11eb-83b3-64f6391878cc.png)

流量为实时动态，总量分毫不变
下图为当前实时流量 总量 clash显示流量信息
![Screenshot_20201018-110204](https://user-images.githubusercontent.com/38456160/96357697-d1735b80-1131-11eb-9a54-3c6076736e17.png)
而下图为不到一分钟之后的
![Screenshot_20201018-110214](https://user-images.githubusercontent.com/38456160/96357679-9cff9f80-1131-11eb-82f4-2032e5e43ac6.png)

**设备信息 (请完成以下信息):**
 - 机型: [Xperia 1 mark 2]
 - 系统/ROM: [Android 10]
 - Android 版本 [10]
 - ROM版本 [58.0.A.3.170]

**应用信息**
 - 版本: [2.1.5和2.1.6]
 - 安装包文件名: [2.1.6-arm64-v8a.apk]
 - 应用来源: [Google Play和GitHub发布]

**Comment by Kr328** [comment]
#490
