### ISSUE TITLE
[Feature Request] 保留覆写配置内容

### ISSUE THREAD

**Issue by Mit2g** [Kr328/ClashForAndroid#686]
**功能描述**
 - 保留```设置-覆写-DNS-策略-使用覆写```的相应内容
 - 更改策略模式的操作次数

**描述你希望的实现方式**
- 对于DNS覆写 希望可以保留上次配置的相关信息
填写一次完整的内容太繁琐了 为了测试临时修改之后再更改回覆写配置会全部丢失

- 对于策略模式 可以增加一个选项```在代理内控制``` 或者 移动回上一个大版本时的位置
现有模式虽然整洁且符合配置文件逻辑但操作步骤相较以往增加了 不便于临时修改使用

**附加信息**
无

**Comment by Kr328** [comment]
不做

复写本意是为 **通用的选项** 提供使用同一套配置的方法 与配置文件直接关联的 不通用的选项 请自行修改配置文件

**Comment by Kr328** [comment]
1. DNS 复写提供了 三种状态的开关 意味着需要 "不修改" "启用复写" 和 "使用内置 DNS" 而正好对应 "删除复写 DNS 配置" "强制启用 DNS" 和 "强制停用 DNS"

2. 之前版本的代理模式选项存在持久化缺陷 现在有复写实现 能稳定实现且保证符合预期
并且 假设你需要频繁修改代理模式 也就没有使用这个软件的必要了 
在自行编辑规则和策略组的情况下都不能满足需求 而需要频繁的修改代理模式 建议使用 Shadowsocks 或者 V2rayNG

**Comment by Mit2g** [comment]
> 1. DNS 复写提供了 三种状态的开关 意味着需要 "不修改" "启用复写" 和 "使用内置 DNS" 而正好对应 "删除复写 DNS 配置" "强制启用 DNS" 和 "强制停用 DNS"
> 2. 之前版本的代理模式选项存在持久化缺陷 现在由复写实现 能稳定实现且保证符合预期
>    并且 假设你需要频繁修改代理模式 也就没有使用这个软件的必要了
>    在自行编辑规则和策略组的情况下都不能满足需求 而需要频繁的修改代理模式 建议使用 Shadowsocks 或者 V2rayNG

 1 由于已经在配置文件中加入了dns相应参数 所以选择了使用内置DNS来确保不会受到设置DNS影响 这么做的原因是因为移动数据下经常因为向DNS请求超时而导致的网络连接失败 必须重启Clash才可以正常使用 有这个需求也是在测试是否有解决方法时发现的覆写内容被清除

 2 正是由于其策略的特性 手机端又无法临时修改配置文件(指使用链接订阅而非配置文件导入) 所以才有临时修改的需求 而又因上个大版本相较 当前方案步骤多了一些 才有此需求

**Comment by Kr328** [comment]
1. 在网络变更时 配置文件会被重新载入 DNS 缓存被清除
2. 可以使用 proxy-providers 脱离陈旧的全套下载配置文件的形式

**Comment by Mit2g** [comment]
> 1. 在网络变更时 配置文件会被重新载入 DNS 缓存被清除
明白了 我再测试观察下结果 感谢回复
