### ISSUE TITLE
[Feature Request] 如何将手机的yaml文件拷贝出来？

### ISSUE THREAD

**Issue by gupengzytm** [Kr328/ClashForAndroid#688]
**功能描述**
能将手机中的yaml文件提取出来

**描述你希望的实现方式**
以任何形式分享

**附加信息**
折腾了半天没在手机里发现yaml文件，由于订阅网址已失效，只有yaml文件可用，能实现这个功能吗？

**Comment by Kr328** [comment]
duplicate of #317

**Comment by xuhaoyang** [comment]
@gupengzytm https://telegra.ph/%E9%AB%98%E5%BA%A6%E5%AE%9A%E5%88%B6Android%E7%B3%BB%E7%BB%9F%E6%9F%A5%E7%9C%8BClashforAndroid-Profile%E9%85%8D%E7%BD%AE%E5%86%85%E5%AE%B9-09-03

**Comment by gupengzytm** [comment]
> 
> 
> @gupengzytm https://telegra.ph/%E9%AB%98%E5%BA%A6%E5%AE%9A%E5%88%B6Android%E7%B3%BB%E7%BB%9F%E6%9F%A5%E7%9C%8BClashforAndroid-Profile%E9%85%8D%E7%BD%AE%E5%86%85%E5%AE%B9-09-03

十分感谢老哥，困扰我24小时的问题终于解决了
