### ISSUE TITLE
请教：v2rayNG自己搭建的ws-tls协议节点怎样导入clash里？

### ISSUE THREAD

**Issue by zhongqiujie13** [Kr328/ClashForAndroid#69]
自己vps搭建的ws-tls协议的节点，按照clash的readme.md看了半天也没摸到头绪，所以特来请教该如何写配置？我自己看了下导入的机场配置是这样写的：
- {"name":"随便","type":"vmess","server":"www.xxx.xxx","port":443,"uuid":"xxxx-xxx。。。","alterId":0
,"cipher":"auto","network":"ws","ws-path":"/user","ws-headers":{"Host":"www.xxx.xxx"}}
但是它这个没加tls的，加了tls后我直接"tls":"true"这样加进去不行。
一样大神教一下应该怎样写入，先谢过了！
![IMG_20191231_191030](https://user-images.githubusercontent.com/16622626/71629072-4d012c00-2c36-11ea-9290-b0051159988f.jpg)

**Comment by zhongqiujie13** [comment]
> 自己vps搭建的ws-tls协议的节点，按照clash的readme.md看了半天也没摸到头绪，所以特来请教该如何写配置？我自己看了下导入的机场配置是这样写的：
> 
> -  {"name":"随便","type":"vmess","server":"www.xxx.xxx","port":443,"uuid":"xxxx-xxx。。。","alterId":0
>   ,"cipher":"auto","network":"ws","ws-path":"/user","ws-headers":{"Host":"www.xxx.xxx"}}
>   但是它这个没加tls的，加了tls后我直接"tls":"true"这样加进去不行。
>   一样大神教一下应该怎样写入，先谢过了！
>   ![IMG_20191231_191030](https://user-images.githubusercontent.com/16622626/71629072-4d012c00-2c36-11ea-9290-b0051159988f.jpg)

**Comment by Kr328** [comment]
不知道

**Comment by lbwstco** [comment]
@zhongqiujie13 可以用subconverter转一下
