### ISSUE TITLE
[BUG] 没有“模式”选择，无法全局代理或直连

### ISSUE THREAD

**Issue by seanxyzzz** [Kr328/ClashForAndroid#690]
![Screenshot_20201022-212205](https://user-images.githubusercontent.com/73294675/96878249-3241c180-14ad-11eb-9a05-7f8c40b333fd.jpg)
我记得以前是可以选择全局，规则或直连模式的，现在找不到那个选项了。

**Comment by AkariiinMKII** [comment]
@seanxyzzz settings - override - mode
