### ISSUE TITLE
[BUG] 一加1无法转发流量

### ISSUE THREAD

**Issue by llllllllqq** [Kr328/ClashForAndroid#691]
**描述出现的错误**
一加1手机打开clash允许vpn后，任何流量不被转发

**如何复现该错误**
复现步骤:
1. 重装clash
2. 放入能在其它手机正常工作的配置文件（我确保不是配置文件设置为直连的问题）
3. 链接
4. 打开任意app，均不转发流量，直接直连或干脆上不去网
5. 此时显示0 KB转发，一丁点都不动。极小概率这个数字增加几KB但随即失效。

**预期行为**
能转发

**设备信息 (请完成以下信息):**
 - 机型: 一加1 A0001
 - 系统/ROM: Tugapower Q13(基于lineageos最新版)
 - Android 版本 10
 - ROM版本 Q13

**应用信息**
 - 版本: 2.1.5
 - 安装包文件名: armv7的
 - 应用来源: Google Play

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
日志内无任何报错，无端口占用，clash本身能正常上网，下拉检测节点功能能正常使用
```

**Comment by Kr328** [comment]
两个必填项啥都没有 等着通灵呢

**Comment by llllllllqq** [comment]
> 两个必填项啥都没有 等着通灵呢

不好意思。
但实际情况就是这样，任何配置文件都能复现，并且启动时的日志和另一个机子上正常工作时的日志一模一样。而启动后不转发时因为根本没有新日志出现便没有上传。

**Comment by Kr328** [comment]
@llllllllqq 启动日志 再 打开开关

存在配置载入成功必然不能没有任何日志

**Comment by llllllllqq** [comment]
> @llllllllqq 启动日志 再 打开开关
> 
> 存在配置载入成功必然不能没有任何日志

感谢，捕捉到了
测试时访问了youtube，并且该节点在另一个机子可用。 

[2020-10-23 14_48_30.log.txt](https://github.com/Kr328/ClashForAndroid/files/5427770/2020-10-23.14_48_30.log.txt)

**Comment by akw5454521** [comment]
骁龙800还能上安卓10啊……

**Comment by AnyoeDove** [comment]
这是内核问题，之前我就试过了，一加1的第三方ROM除了 Tomoms 的 [LineageOS 16](https://forum.xda-developers.com/oneplus-one/development/rom-unofficial-optimized-lineageos-14-1-t3693223) 以外没有其他 ROM 修复过这个问题，建议抓 log 向维护者反馈。

> Previous releases (LineageOS 16):
> 
> June 27th:
>>synced with LineageOS
>>a few minor tweaks in the device tree
>>several kernel updates; kernel built with GCC 10
>>all kind of VPN-related kernel panics are now fixed for good

**Comment by llllllllqq** [comment]
tg群最新测试版已修复。谢谢
