### ISSUE TITLE
[BUG] 随机发生的配置文件失踪

### ISSUE THREAD

**Issue by oott123** [Kr328/ClashForAndroid#692]
**描述出现的错误**
在使用过程中随机出现：代理显示“未运行”，配置列表显示为空，新建配置不管点击“URL”还是“文件”均没有反应，此时系统 VPN 为连接状态。强行停止 App 并重启 App 后，配置列表和上述功能均恢复正常。

**如何复现该错误**
没有找到稳定的复现步骤，更新到新版本之后大概出现了3次。但我使用了订阅和自动更新功能，可能是在后台更新后出现（没有观察到具体时机）。

**设备信息 (请完成以下信息):**
 - 机型: OnePlus 7Pro
 - 系统/ROM: Oxygen OS
 - Android 版本 10
 - ROM版本 10.3.4 GM21AA

**应用信息**
 - 版本: 2.1.5-arm64-v8a
 - 安装包文件名: N/A
 - 应用来源: Google Play

来自 GitHub Release 的 2.1.6-arm64-v8a 也有此问题。

**Comment by oott123** [comment]
刚刚又出现了一次。看起来和自动更新订阅无关，因为我已经把更新关掉了。

**Comment by oott123** [comment]
因为这个问题复现比较随机，抓日志比较难，所以此前并未上传日志。后来复现次数越来越多，一直开着 logcat ，抓到一次日志（在 2.1.6 抓的）：

https://gist.github.com/oott123/6967674f709d341cca2840839591c64a

不过日志看起来并没有什么异常，看日志好像是发生在切换网络的时候。clash 日志因为真的没什么特殊的，手机打码不方便，在此略过。如果对排查问题有帮助，我会再提供。

此时应用显示如图：

![Screenshot_20201024-192933](https://user-images.githubusercontent.com/905663/97083769-fa6d8200-1644-11eb-9856-6b2b588386d9.jpg)

![Screenshot_20201024-192944](https://user-images.githubusercontent.com/905663/97083778-08230780-1645-11eb-847f-07d5f3637f77.jpg)

事实上配置文件是正确且可以加载的。考虑到此前我并没有频繁切换网络的习惯（最近在出差所以切换比较多），也可能和版本更新无关。

之后我尝试下载 2.1.4 用两天看看。

**Comment by chinawenxu** [comment]
同样出现再次，清空后台重新开启后又正常了。

**Comment by yangon99** [comment]
在两部手机和一台 ChromeBook 上有相同问题，尝试不使用 provider 之后就没有再出现过类似情况了（小内存手机的泪

**Comment by oott123** [comment]
> 在两部手机和一台 ChromeBook 上有相同问题，尝试不使用 provider 之后就没有再出现过类似情况了（小内存手机的泪

@yangon99 我没有使用 provider。不过我用了一个七万行的配置文件，虽然我内存还够用，但听起来确实也可能和这有关系。

同时也附上配置文件方便排查问题：https://gist.github.com/oott123/de95fd4f52c38defe071f08c18cbb0aa

**Comment by oott123** [comment]
检查了最近的 issue，该问题看起来和 #655 #674 #586 是重复问题。

我理解这类问题比较难排查，在我这边长时间挂 adb logcat 和 clash 日志，复现之后依然没有任何有价值的日志。Owner 如果有时间看到 issue 的话，也辛苦抽空指导排查思路。

我这边在网络变稳定之后，出现的频率也降低了不少。推测可能是规则过于复杂之后发生的 OOM，我这边将配置缩减了一下，会继续观察该问题是否存在。

**Comment by Hxmg** [comment]
我也多次遇到这个问题了。
感觉是配置文件内容过多的原因。

**Comment by callzhang** [comment]
我每天都遇到，感觉是切网络的时候会卡住。

**Comment by rurirei** [comment]
is this app uses sharedPreferences?

**Comment by dispoper** [comment]
七连还能进去吗

**Comment by Kr328** [comment]
@dispoper 请不要在应用反馈处讨论代理提供商

**Comment by oott123** [comment]
经过这几天的测试，我发现该情况多数出现于 clash 启动时——无论是开机或者网络切换导致 clash 重启的时候，都有概率出现这个问题。

同时我将配置文件的大小缩减了一半，但此问题依然存在，可能需要继续缩小配置文件。

此外，即使是 OOM ，也应该留下日志信息才对，但我多次监控 adb 都没有发现类似的日志信息。

**Comment by xzh202o** [comment]
订阅付款后没有收到端口链接是怎么回事？

**Comment by fengshansi** [comment]
我的华为手机一直出现这个问题

**Comment by xzh202o** [comment]
我用mac电脑登录也没有发给我链接。我现在联系不到这个网站的任何人呢！您知道我该怎么解决这个问题吗？谢谢

在 2020-11-19 14:38:09，fengshansi <notifications@github.com> 写道：


我的华为手机一直出现这个问题

**Comment by AkariiinMKII** [comment]
> 我用mac电脑登录也没有发给我链接。我现在联系不到这个网站的任何人呢！您知道我该怎么解决这个问题吗？谢谢 在 2020-11-19 14:38:09，fengshansi <notifications@github.com> 写道： 我的华为手机一直出现这个问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

关CFA PIS 去找你的服务商

**Comment by Kr328** [comment]
@xzh202o 本应用完全免费 不收取任何费用 亦不提供任何服务 更没有任何网站 

在这里仅接受应用本身的反馈 不提供关于服务提供商的任何相关支持

**Comment by Quzard** [comment]
确实，打开代理时，会突然变得很卡。不知道为啥。

**Comment by uoox** [comment]
我也说下我的情况，用商家的默认配置好像很少出现此问题，但是我用subconverter进行了转化，规则用的acl4ssr，不知道楼上的朋友是不是同样的情况。

**Comment by gang4399** [comment]
> 我也说下我的情况，用商家的默认配置好像很少出现此问题，但是我用subconverter进行了转化，规则用的acl4ssr，不知道楼上的朋友是不是同样的情况。

类似。自制规则，在线拉github上的list，以前没问题，最近这两个版本不定期丢配置文件。内存的话我不知道，规则一直是没变过。

手机用的规则一直是这个：https://raw.githubusercontent.com/gang4399/CLS/master/2mm.ini

**Comment by gang4399** [comment]
> > 我也说下我的情况，用商家的默认配置好像很少出现此问题，但是我用subconverter进行了转化，规则用的acl4ssr，不知道楼上的朋友是不是同样的情况。
> 
> 类似。自制规则，在线拉github上的list，未开启自动更新订阅，节点url-test半小时一次，以前没问题，最近这两个版本不定期丢配置文件。内存的话我不知道，规则一直是没变过。
> 
> 手机用的规则一直是这个：https://raw.githubusercontent.com/gang4399/CLS/master/2mm.ini

我最近发现，我一直fake-ip，nameservicer fallback自定义的已经很久没丢配置了。

**Comment by epoweripione** [comment]
On my nexus 6p, if the `proxies` node have a large items ( more than 200 ), the app show error message: `Cursor window allocation of 2048 kb failed` when `Tap to start`.

Maybe this issue caused by using External SQLite, ref to `https://stackoverflow.com/questions/11340257/sqlite-android-database-cursor-window-allocation-of-2048-kb-failed`:
>There is indeed a maximum size Android SQLite cursor windows can take and that is 2MB, anything more than this size would result into the above error. Mostly, this error is either caused by a large image byte array stored as blob in sql database or too long strings.

**Comment by usamoi** [comment]
相同的问题。存在两个配置文件时未发现此现象，当我增加第三个配置文件后，两台设备在同一天发生了同样的现象。

**Comment by alexlee728** [comment]
同样出现过多次，强行停止后又恢复。但是关闭UDP之后似乎没出现过这个问题。

**Comment by oott123** [comment]
将代理节点减少了一半之后反复测试也没有发生问题。或许这是一个良好的 workaround。

**Comment by SadYuyuko** [comment]
我也遇到过这个，最频繁的时候甚至间隔不到10分钟

**Comment by yangon99** [comment]
> 推测可能是规则过于复杂之后发生的 OOM
如果配置文件里有 url-test 的节点组，可以尝试不用 url-test 组，我在把 url-test 组取消后，节点增加了不少，也没再出现过类似的问题……

**Comment by Kr328** [comment]
新版本 传日志 请

**Comment by uoox** [comment]
重构后版本用了几天，目前没出现之前情况。

环境：
一加7pro Android 11 oos beta4
