### ISSUE TITLE
[BUG] 安卓版本Clash无法全局代理

### ISSUE THREAD

**Issue by AQ-Official** [Kr328/ClashForAndroid#693]
**描述出现的错误**
 安卓版本Clash无法全局代理

在规则配置页面右上角点开没有模式选项，不能全局代理

**预期行为**
可以全局代理

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型:Samsung Galaxy S20 Ultra
 - 系统/ROM: One UI 2.5
 - Android 版本 10

**应用信息**
 - 版本:2.1.5-arm64-v8a
 - 应用来源:Google Play

**Comment by Kr328** [comment]
#690

**Comment by Macyrate** [comment]
issue 690 has been deleted.

**Comment by FengJunda** [comment]
I also has the same problem.

**Comment by AkariiinMKII** [comment]
Settings > override > mode

**Comment by EnosXu** [comment]
设置-复写-模式

**Comment by FengQwQ233** [comment]
没有用依然无法全局
全局之后外网都无法使用
型号：JSN-AL00a
系统：EMUI10
Android版本10

**Comment by RtYkk** [comment]
@FengQwQ233 [#846-800898471](https://github.com/Kr328/ClashForAndroid/issues/846#issuecomment-800898471)

**Comment by Aony0615** [comment]
> 设置-复写-模式

Thanks

**Comment by sunucheng** [comment]
无法使用全局
全局之后就连不上外网了，只能改回不修改模式
型号：华为mate40pro
系统：鸿蒙2.0

**Comment by wujunlonga** [comment]
我的是开启了全局，但是ip还是在国内，导致facebook能上 但是linkedin国际版不能上；
型号：华为mate30
系统：鸿蒙2.0

**Comment by Waldenth** [comment]
同样，全局模式国外网站完全不能使用，所有机场都不行。规则模式不能添加规则导致很多网站依旧访问不了，极其鸡肋

**Comment by xuhaoyang** [comment]
@Waldenth 笑死，切换Global后，需要自己手动选下节点，不然是Direct

**Comment by xuhaoyang** [comment]
建议各位发言前，多了解下软件细节。如果你觉得这个逻辑是个问题，请向 https://github.com/Dreamacro/clash 提

**Comment by wangzs** [comment]
全局模式 要在GLobal那选节点，默认是Direct的

**Comment by HUANGJIN169** [comment]
这个问题 我来回复所有新手 关于全局代理无法使用，在你的机场订阅地址 复制粘贴到Clash然后点进去代理看见一个GLOBAL模式选择你的服务器就可以全局代理模式了。然后也可以手动模式选择服务器了 如果还是无法使用 就先划掉Clash再次启动
