### ISSUE TITLE
[BUG] 同一网址，UDP和TCP匹配到不同规则

### ISSUE THREAD

**Issue by returnL** [Kr328/ClashForAndroid#694]
**描述出现的错误**
Google Play下不动软件，看了日志， UDP的googleapis.cn没走代理，但是TCP的googleapis.cn走代理了，所以应该也不是规则的问题

**如何复现该错误**
复现步骤:
1. 打开Google Play
2. 下载任意APP

**预期行为**
Google Play可以正常下载APP

**设备信息 (请完成以下信息):**
 - 机型: 三星S9+
 - 系统/ROM:One UI 2.1
 - Android 版本 10
 - ROM版本 2.1

**应用信息**
 - 版本: 2.15
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Google Play

**日志**
```
[UDP] 172.31.255.253:50318 --> services.googleapis.cn match DomainSuffix(cn) using DIRECT

[TCP] 172.31.255.253:51326 --> services.googleapis.cn match DomainSuffix(googleapis.cn) using Proxies[🇭🇰 日用-香港-0.2]
```

**Comment by EKyero** [comment]
@returnL 节点加上udp:ture 
没开udp只能direct了呗

**Comment by returnL** [comment]
> @returnL 节点加上udp:ture 
> 没开udp只能direct了呗

那udp匹配到的规则是哪里的呢🤪

**Comment by AkariiinMKII** [comment]
@returnL log level开到debug就能看见了

**Comment by returnL** [comment]
> @returnL log level开到debug就能看见了

好的，感谢
