### ISSUE TITLE
关于URI订阅的一些小问题

### ISSUE THREAD

**Issue by bgtro** [Kr328/ClashForAndroid#70]
您好Kr328，我最近在使用Clash For Android遇到了些比较棘手的问题，当我输入订阅地址的时候，遇到了Invalid Config的问题，经过我的测试在Chrome下可以正常的下载订阅文件，应该不是个例我已经又两个朋友遇到这个问题了，如果能的话请尽力修复谢谢

**Comment by Kr328** [comment]
截图?

**Comment by bgtro** [comment]
Kr328 <notifications@github.com> 于 2020年1月3日周五 18:37写道：

**Comment by bgtro** [comment]
https://wx2.sinaimg.cn/large/7f5e07e9ly1gajkntdy4ij20u01o0abh.jpg

**Comment by Kr328** [comment]
@bgtro Feedback -> Feedback ID

**Comment by bgtro** [comment]
3957cc4e7b8446d8f1b90951bc451acb

**Comment by bitfucker** [comment]
真的，我这边也用不了，就是订阅不上，提示invalid Config

**Comment by LunaticTian** [comment]
3600c714e2208b3d551eaaf7521f2c03

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
