### ISSUE TITLE
[BUG] clash能正常连接使用的情况下内存占用达到1.71g

### ISSUE THREAD

**Issue by LinnyR** [Kr328/ClashForAndroid#702]
**描述出现的错误**
开启clash2.1.6在miui12.0.9下正常使用(就是在浏览器上看了一个来小时油管视频）情况下偶然发现内存占用达到1.71g，请问这样的情况正常吗？还是有内存泄露的地方？

**屏幕截图**
![Screenshot_2020-10-29-17-50-00-512_com.miui.cleanmaster.jpg](https://user-images.githubusercontent.com/38827394/97554028-333e8b80-19a4-11eb-8584-1ab4f37234dd.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 红米k30pro 8g
 - 系统/ROM:MIUI 12.0.9稳定版

**应用信息**
 - 版本: 2.1.6
 - 应用来源: 作者github release

**Comment by Kr328** [comment]
#490
