### ISSUE TITLE
[BUG] Google Play 商店无法更新到最新的版本

### ISSUE THREAD

**Issue by dingwen07** [Kr328/ClashForAndroid#703]
**描述出现的错误**
在 Google Play 商店下载的 App 不是最新的版本，目前为 2.0.18-arm64-v8a 版本。

**如何复现该错误**
复现步骤:
1. 在 Google Play 商店下载 [Clash for Android](https://play.google.com/store/apps/details?id=com.github.kr328.clash)

**预期行为**
能够在 Play 商店更新到最新的版本

**屏幕截图**
Null

**设备信息 (请完成以下信息):**
 - 机型: Galaxy S10+, Xiaomi MI 6
 - 系统/ROM: One UI 2.5, MIUI 12
 - Android 版本: 10.0, 9
 - ROM版本: G9750TGY4DTJ2, 20.6.18

**应用信息**
 - 版本: 2.0.18-arm64-v8a
 - 安装包文件名: Unknown
 - 应用来源: Google Play

**附加信息**
Null

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
Null
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
Null
```

**Comment by Kr328** [comment]
问 Google

**Comment by dingwen07** [comment]
请确认你们上传到Play的版本和相关设置是否正确
