### ISSUE TITLE
[Feature Request] 进入 代理节点选择界面时，自动测试节点延迟

### ISSUE THREAD

**Issue by DBinK** [Kr328/ClashForAndroid#704]
**功能描述**
如题

**附加信息**

希望是个可选项，可在设置关闭

**Comment by Kr328** [comment]
会导致 连接数暴增 fd 不足 应用崩溃

**Comment by akw5454521** [comment]
手动测试延迟也就点击一下闪电图标的事……另外节点抽风的话可以编辑一个fallback组

**Comment by DBinK** [comment]
> 会导致 连接数暴增 fd 不足 应用崩溃

把上次测试得到的节点延迟数据和排列顺序保存

这个呢？

**Comment by Kr328** [comment]
@DBinK 一直以来就是这样
