### ISSUE TITLE
[BUG] proxy-providers无法读取本地配置文件

### ISSUE THREAD

**Issue by darlling** [Kr328/ClashForAndroid#706]
**描述出现的错误**
添加配置文件时，配置文件中使用了proxy-providers。在proxy-providers内，本地文件类型（type: file）下path参数无法正确读取外部存储路径  

通过错误信息发现路径默认为：`/data/user/0/com.github.kr328.clash/files/clash/0/xxxxxxxxxxxx`，且无法指向外部存储路径如：`/storage/emulated/0/Android/data/com.github.kr328.clash`

**屏幕截图**
报错信息如下：  
![image](https://user-images.githubusercontent.com/49542748/98007600-901bc500-1e2e-11eb-958b-8a0f7cddd510.png)

proxy-providers具体配置如下：  
![image](https://user-images.githubusercontent.com/49542748/98007716-ab86d000-1e2e-11eb-8193-d483c6570d69.png)

**设备信息 (请完成以下信息):**
 - 机型: Honor 9x
 - 系统/ROM: EMUI 10.1
 - Android 版本: 10

**应用信息**
 - 版本: 2.1.6-arm64-v8a
 - 应用来源: github

**Comment by Kr328** [comment]
预期行为

未来会提供导入选项
