### ISSUE TITLE
[Feature Request] 请在GooglePlay上同步更新进度

### ISSUE THREAD

**Issue by pty819** [Kr328/ClashForAndroid#708]
**Is your feature request related to a problem? Please describe.**
目前clash在playstore上仍然是7月份的版本，但是github已经发布到9月份的了，这对于喜欢用googleplay的用户来说并不方便更新。

**Describe the solution you'd like**
请在发布github更新之后同步playstore的版本，store版界面稍微加一两个广告是可以接受的。

**Describe alternatives you've considered**

**Additional context**

**Comment by Kr328** [comment]
Google Play 早在一个月前上传新版本 而你没有被 Google 选中 成为 50% 的用户

新版本存在的大量问题导致它不可能分发给全部的用户

**Comment by NetHeritage** [comment]
不要加广告啊  单独出付费版本也不要加广告

**Comment by xuhaoyang** [comment]
@NetHeritage 哪来的广告？
