### ISSUE TITLE
貌似规则中如果节点名称带有中文，无法连接外网

### ISSUE THREAD

**Issue by CodingOX** [Kr328/ClashForAndroid#71]
简单来说就是订阅的规则中，如果节点的名称是中文，能够正常启动，但是无法连接外网。
设备MI6,MZ16,RedMIK20Pro都是如此！

**Comment by Kr328** [comment]
我的机器上正常

**Comment by CodingOX** [comment]
> 我的机器上正常

目前我是将规则下载到本地，然后替换中文来搞定的。我看提Issue的有个一加的，看看他是不是也是如此。

**Comment by Kr328** [comment]
@CodingOX 即使存在这样的问题 也是上游 clash 的

**Comment by CodingOX** [comment]
> @CodingOX 即使存在这样的问题 也是上游 clash 的

之前用的`ClashA`没有次问题，但是他不貌似不适配`MIUI11`，看他在推荐你，我今天才试用了下！

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/71724581-b918a580-2e6b-11ea-8e19-8f1525099fc8.png)

你这个环境 不感觉是 clash 的问题

**Comment by alphayxc** [comment]
我版本1.0.35，手机oppo reno ace，安卓9，coloros6.1，存在相同问题

**Comment by Kr328** [comment]
@alphayxc 我都还没有发布 1.0.35 你哪来的

**Comment by alphayxc** [comment]
> @alphayxc 我都还没有发布 1.0.35 你哪来的
TG机场群“几鸡”里昨晚20:02群友发的，不会是盗版吧笑哭，在软件的关于里确实写着1.0.35-alpha
![Screenshot_2020-01-30-02-00-17-03](https://user-images.githubusercontent.com/60443192/73383528-762fdd80-4304-11ea-90b1-fdd319f36d12.jpg)

**Comment by Comah** [comment]
我的也是 今天搞了一天了 估计真的是此愿因 ssr节点用纸飞机一切正常 用了clashr后全部超时无法接通

**Comment by sensen1** [comment]
k20pro, 10系统，中文节点v2ray,一切正常，感觉和中文没关系。 大概率是系统问题？

**Comment by tyh97** [comment]
我的MZ16确实能够启动，但是不能连接外网

**Comment by sensen1** [comment]
> > @alphayxc 我都还没有发布 1.0.35 你哪来的
> > TG机场群“几鸡”里昨晚20:02群友发的，不会是盗版吧笑哭，在软件的关于里确实写着1.0.35-alpha
> > ![Screenshot_2020-01-30-02-00-17-03](https://user-images.githubusercontent.com/60443192/73383528-762fdd80-4304-11ea-90b1-fdd319f36d12.jpg)

用作者发布的，这也算基本常识了。 目前据我所知的，都没有发生这个问题的，节点都是包含中文的

**Comment by naloder** [comment]
楼上你这是ClashR而这里是clash的反馈的地方。。clashR维护者目前跑路了。。有问题也不是找clash来反馈啊。。

**Comment by tyh97** [comment]
> 我的MZ16确实能够启动，但是不能连接外网
> 现在把节点名改成非中文，但是仍然无法启动，能够测试延迟，但是就是上不了外网，logs也为空。
> 机型为mz16th，系统是flyme8.20.1.15daliy Android8.1.0

今天抓了应用在手机上的日志，但是也不知道哪出了问题？
[https://www.dztyh.xin/clash_log.log](url)

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复
