### ISSUE TITLE
[BUG] 创建配置URL下载失败

### ISSUE THREAD

**Issue by hzlsdu** [Kr328/ClashForAndroid#711]
**描述出现的错误**
新增配置，用SSR客户端可以创建成功，用Clash提示下载失败。浏览器能下载，下载后本地导入还是失败。

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![Screenshot_20201109_082945_com github kr328 clash](https://user-images.githubusercontent.com/72636625/98488767-f907a080-2265-11eb-8cd0-b8b9e43d1399.jpg)

**设备信息 (请完成以下信息):**
 - 机型: HUAWEI mate 20 pro
 - 系统/ROM: EMUI 10.1.0
 - Android 版本 10
 - ROM版本 10.1.0.165

**应用信息**
 - 版本: 2.1.5
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴，不会搞…
```

**日志**
如果适用, 粘贴日志以帮助侦测错误，
```
<在此粘贴>
```
没有日志

**Comment by xuhaoyang** [comment]
@hzlsdu 字面意思 已经告诉你配置有问题

**Comment by hzlsdu** [comment]
@xuhaoyang 可是我用shadowsocksr那个客户端，可以成功创建配置…而且能用…觉得手机里装两种客户端太麻烦，而且那个SSR客户端用的实在不舒服

**Comment by xuhaoyang** [comment]
@hzlsdu 谁告诉你clash和ssr配置通用？

**Comment by AkariiinMKII** [comment]
@hzlsdu subcon 请

**Comment by hzlsdu** [comment]
@AkariiinMKII 啥意思…看不懂

**Comment by hzlsdu** [comment]
@xuhaoyang 纯小白，你的意思是没法用clash了？

**Comment by xuhaoyang** [comment]
@hzlsdu 纯小白 不懂Google baidu一下？

**Comment by QQ6988** [comment]
@hzlsdu你就算是小白，百度和谷歌会用吧，不会自己搜索一下吗

**Comment by hzlsdu** [comment]
大神们都好严厉…还是感谢回复的各位哈

**Comment by QQ6988** [comment]
@赫兹杜  什么时候能添加改混淆的，软件倒还好，就是现在这软件只能翻不能免流😂😂

**Comment by QQ6988** [comment]
混淆
