### ISSUE TITLE
[Feature Request] Add a option for hide update notification

### ISSUE THREAD

**Issue by xmha97** [Kr328/ClashForAndroid#712]
Hi,
Please add a option for hide update notification.
![MIUI 11 Notification Bar](https://user-images.githubusercontent.com/23485114/98662731-795cfd00-235d-11eb-802e-3aa2ce4b7c69.png)

**Comment by Kr328** [comment]
please disable the notification category by your self
![Screenshot_20201110-184537](https://user-images.githubusercontent.com/39107975/98664182-ff406e80-2384-11eb-93e6-34ea3596d557.png)
