### ISSUE TITLE
[Feature Request] 能否使用命令行关闭和开启代理？

### ISSUE THREAD

**Issue by forliuyifei** [Kr328/ClashForAndroid#717]
**功能描述**
有一部闲置安卓机，屏幕坏一半，每次下拉通知栏或者点开 Clash 开启代理都不够方便（因为都在上部）。  
暂时的方法是强制屏幕旋转，需要点击哪部分就把手机不失灵的那部分翻转过去，有时心太烦还会扭到脖子……

**描述你希望的实现方式**
希望支持简单的命令行启动/关闭代理，那部手机已 root，Termux 和 adb 命令基本可用。

**附加信息**
暂无……

**Comment by Kr328** [comment]
自己跑 Core 请
