### ISSUE TITLE
[Feature Request] 添加对所有应用dns代理

### ISSUE THREAD

**Issue by monokiu** [Kr328/ClashForAndroid#718]
**功能描述**
添加对所有应用dns代理

**描述你希望的实现方式**
网络>vpnservices选项下加入此功能

**附加信息**
发现不在访问控制应用包列表中的应用使用了isp dns，而不是clash指定的dns。此功能应该对本机所有应用的dns请求进行代理，不论其是否在应用包列表中。（之所以需要是因为想对微信QQ等不需要ip代理的应用使用dot,doh，但android自带的dot只能填写一个地址，想借用clash的dns代理功能实现）（所以dns劫持选项到底有什么用呢？）

**Comment by Kr328** [comment]
做不到
