### ISSUE TITLE
[Feature Request] 将模式切换添加到下拉栏菜单

### ISSUE THREAD

**Issue by w3AD4y-r5** [Kr328/ClashForAndroid#719]
**功能描述**
将模式切换添加到常驻通知

**描述你希望的实现方式**
clash的常驻通知中添加直接切换模式的功能。

**附加信息**
每次切换模式都要点好几下，入口太深。或者将其提到app主页面，与代理、配置、运行状态平行也可。

**Comment by Drak-Fish** [comment]
你好作者，我发现有一些clash for andriod中的一些小问题。例如在我开启 网络~访问控制~仅允许已选择的应用，然后我发现我选择的应用例如油管刷新页面很慢，只有把设置改为允许所有应用，再改回来就很正常。但是直接用允许所有应用就没啥问题，但是我用小猫咪就是为了强大的分流。

**Comment by Kr328** [comment]
切换模式不是是核心功能

需要频繁切换模式的话 说明你可能不适合使用这样的应用
