### ISSUE TITLE
[Feature Request] 加入类似shadowrocket的场景自动切换

### ISSUE THREAD

**Issue by sqliuchang** [Kr328/ClashForAndroid#723]
**功能描述**

https://github.com/eycorsican/kitsunebi-android/issues/28
此issue描述的很完整，但主要需求是区分不同ssid的WiFi和蜂窝数据场景，从而使用不同的PROXY。至于再具体到是规则模式还是全局模式可以不用考虑。

**描述你希望的实现方式**

功能上相当于添加了一种新的proxy group，是根据当前的网络场景来自动切换所需节点，不过在clash core上应该不方便实现，所以在这里发issue。

**Comment by Kr328** [comment]
#319
