### ISSUE TITLE
[BUG] google play更新软件时很慢

### ISSUE THREAD

**Issue by kusiru** [Kr328/ClashForAndroid#724]
**描述出现的错误**
经常出现正在下载，或者下载到一半没速度了，下载到99%就停了，换了v2rayNG就能马上下完。

**设备信息 (请完成以下信息):**
 - 机型: samsung s20+
 - 系统/ROM: oneui 2.5
 - Android 版本 10

**Comment by Kr328** [comment]
填完 请

**Comment by akw5454521** [comment]
全局模式应该正常吧？
