### ISSUE TITLE
[BUG] 无法创建配置

### ISSUE THREAD

**Issue by licwang13** [Kr328/ClashForAndroid#727]
**描述出现的错误**
删除原有配置后，按照教程进行新配置的创建，无法创建成功

**如何复现该错误**
复现步骤:
1. 删除原有配置
2. 按照教程进行新配置
3. 填写名称
4. 复制clash配置链接到URL
5. 点击保存
6. 显示下载失败
**预期行为**
可以完成新配置

**屏幕截图**
![mmexport1606270400109](https://user-images.githubusercontent.com/74998790/100174251-05972480-2f07-11eb-97f1-c32b16e2d4bf.jpg)
![mmexport1606270396440](https://user-images.githubusercontent.com/74998790/100174266-0b8d0580-2f07-11eb-83af-aa1eace4cd47.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 华为p20
 - 系统/ROM: EMUI 10.0.0
 - Android 版本 :10
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 2.0.18]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
阅读图中的错误内容 自己修改配置文件
