### ISSUE TITLE
[Feature Request] 跟进上游支持 vmess http/2 传输方式

### ISSUE THREAD

**Issue by liberal-boy** [Kr328/ClashForAndroid#730]
**功能描述**
跟进上游支持 vmess http/2 传输方式

**描述你希望的实现方式**
跟进上游

**Comment by elvisw** [comment]
这不是上游1.2支持的特性么，这边为何不合并呢：
https://github.com/Dreamacro/clash/releases/tag/v1.2.0

**Comment by Kr328** [comment]
@elvisw 新版本会使用上游最新的 commit

unplan 只是没有任何计划出新版本

更新随缘
