### ISSUE TITLE
[BUG] 全局模式下用了clash dns

### ISSUE THREAD

**Issue by monokiu** [Kr328/ClashForAndroid#731]
**描述出现的错误**
全局模式下发现dns用了自己覆写的dns

**如何复现该错误**
复现步骤:
0. dns覆写成自定义dns(追加到系统off ipv6 off redir-host name servers: tls://dns.pub:853  tls://dns.alidns.com:853
fallback tls://1.1.1.1:853  tls://dns.google:853 default 1.1.1.1 119.29.29.29 223.5.5.5 8.8.8.8 fakeip 无 geoip on ipcidr 无)
1.覆写-模式调成全局
2. 重启手机清除缓存
3.测试dns(https://www.dnsleaktest.com/)
4. 发现有广东（腾讯）和杭州（阿里）地址

**预期行为**
全局模式下，所有dns均由远端服务器isp解析。

**屏幕截图**
![1](https://user-images.githubusercontent.com/68957954/100306107-83f0d680-2f9a-11eb-8049-09fa82f6ed5b.jpg)

**设备信息 (请完成以下信息):**
 - 机型: [ huawei mate 10]
 - 系统/ROM: [ emui 10.0]
 - Android 版本 [10]
 - ROM版本 [见截图]

**应用信息**
 - 版本: [2.1.5 arm64v8a]
 - 安装包文件名: 不知道
 - 应用来源: [Google Play]

**附加信息**
clash for windows用同一服务器，没有用阿里腾讯dns解析，可以排除节点本身的问题。

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
有需要再上传
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
有需要再上传
```
<在此粘贴>
```

**Comment by Kr328** [comment]
> tls://dns.pub:853 -> 腾讯
> tls://dns.alidns.com:853 -> 阿里

**Comment by Kr328** [comment]
以及 Clash DNS **均为本地解析** 然后通过反向解析域名 送往远端

**Comment by Kr328** [comment]
以及

https://blog.skk.moe/post/what-happend-to-dns-in-proxy/

请

**Comment by monokiu** [comment]
发现fake-ip 可以解决此问题
