### ISSUE TITLE
[BUG] 开机自启怎么没了？或者是我找不到？

### ISSUE THREAD

**Issue by sachmx001** [Kr328/ClashForAndroid#732]
**描述出现的错误**
请简洁的描述你遇到的错误   我记得以前有开机自启的哎，怎么现在反而没了？每次开机都要手动再开启一下，很烦

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by akw5454521** [comment]
安卓真有人天天关机？

**Comment by sachmx001** [comment]
？

**Comment by ChengzhiLiu** [comment]
不用发“?”，就是你找不到而已，我的开机自启完全正常，国产魔改UI。

**Comment by AkariiinMKII** [comment]
@sachmx001 别?了，我都没?呢
系统不说软件版本不说该填的都不填回头发个?不知道的还以为在伺候女朋友呢

**Comment by sachmx001** [comment]
> @sachmx001 别?了，我都没?呢
> 系统不说软件版本不说该填的都不填回头发个?不知道的还以为在伺候女朋友呢

那意思我得把你当女朋友伺候？

**Comment by sachmx001** [comment]
> @sachmx001 别?了，我都没?呢
> 系统不说软件版本不说该填的都不填回头发个?不知道的还以为在伺候女朋友呢

哦，对不起，我应该把你当女朋友伺候，你才是老大，我们是为你服务的！

**Comment by AkariiinMKII** [comment]
@sachmx001 您消停吧 auto restart自己找吧 我不介意做谜语人

**Comment by sachmx001** [comment]
哦，对不起！让您受精了！宝贝，你能否告诉我，自动重启和开机自启是一个意思吗？



---原始邮件---
发件人: "AkariiinMKII"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 下午5:59
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [Kr328/ClashForAndroid] [BUG] 开机自启怎么没了？或者是我找不到？ (#732)




 
@sachmx001 您消停吧 auto restart自己找吧 我不介意做谜语人

**Comment by AkariiinMKII** [comment]
> 哦，对不起！让您受精了！宝贝，你能否告诉我，自动重启和开机自启是一个意思吗？
> 
> 
> 
> ---原始邮件---
> 发件人: "AkariiinMKII"<notifications@github.com&gt;
> 发送时间: 2020年11月29日(周日) 下午5:59
> 收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;;
> 抄送: "Mention"<mention@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
> 主题: Re: [Kr328/ClashForAndroid] [BUG] 开机自启怎么没了？或者是我找不到？ (#732)
> 
> 
> 
> 
>  
> @sachmx001 您消停吧 auto restart自己找吧 我不介意做谜语人
>  
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

本来就是这么实现的
![ceBGWXdp.gif](https://user-images.githubusercontent.com/6019344/100538946-cbfb4c00-326d-11eb-823a-74b55719d4c7.gif)
