### ISSUE TITLE
[Feature Request] 开启自启功能能否恢复呢？

### ISSUE THREAD

**Issue by sachmx001** [Kr328/ClashForAndroid#735]
如题

**Comment by Kr328** [comment]
![Screenshot_20201128-193130](https://user-images.githubusercontent.com/39107975/100514511-61380b00-31b0-11eb-8231-fa5a7c0e0c62.png)
 请

**Comment by sachmx001** [comment]
这个是开机自启？我试过打开，然后一会它就自动关了，我还很奇怪，这是啥意思？



---原始邮件---
发件人: "Kr328"<notifications@github.com&gt;
发送时间: 2020年11月28日(周六) 晚上7:32
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [Kr328/ClashForAndroid] [Feature Request] 开启自启功能能否恢复呢？ (#735)




 

 请

**Comment by Kr328** [comment]
那就应该检查你自己的系统 有没有禁用 App 的组件

**Comment by sachmx001** [comment]
绝对没有禁用任何组件
不过这不说了，那什么，我能否提个建议，您们大神开发者们，能否在命名的时候浅显易懂一点？大众直白点？否则我们小白不易理解啊……谢谢大神了！



---原始邮件---
发件人: "Kr328"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 晚上6:07
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [Kr328/ClashForAndroid] [Feature Request] 开启自启功能能否恢复呢？ (#735)




 
那就应该检查你自己的系统 有没有禁用 App 的组件
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: "Kr328"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 晚上6:07
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [Kr328/ClashForAndroid] [Feature Request] 开启自启功能能否恢复呢？ (#735)




 
那就应该检查你自己的系统 有没有禁用 App 的组件

**Comment by Kr328** [comment]
这个是最准确的描述

应用会在 **更新** 和 **重启** 两个时机 **根据上次状态** 决定是否启动

以及

这个开关与组件状态完全关联 如果没有在这里关闭的话 只能是被系统或者第三方应用限制了

**Comment by sachmx001** [comment]
哦，那什么，这可能是你们程序员最能理解的属于，但是对于咱普通用户，可能不好理解这话，所以，我的意思是，能否用普通用户能理解的话来命名？意思就是不要带有专业性的东西，专业性的东西你可以写在详细手册上，像V2rayng，那意思就都很好理解，什么选项什么作用，一看便知，虽然它也不带开机自启，但它适配tasker，我可以用tasker控制，clash也许性能比V2ray更好，但有些命名术语实在拗口，难以理解😂😂或者你也可以在各选项旁做个注释，什么作用我一点就明白……thank you very much！😁😁



---原始邮件---
发件人: "Kr328"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 晚上7:01
收件人: "Kr328/ClashForAndroid"<ClashForAndroid@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [Kr328/ClashForAndroid] [Feature Request] 开启自启功能能否恢复呢？ (#735)




 
这个是最准确的描述
 
应用会在 更新 和 重启 两个时机 根据上次状态 决定是否启动
 
以及
 
这个开关与组件状态完全关联 如果没有在这里关闭的话 只能是被系统或者第三方应用限制了

**Comment by Kr328** [comment]
@sachmx001 用这类软件连最基本的术语都不明白的话 真的建议不要用了 留一些门槛

我向来不是为了小白做软件 最基本的基础知识 还是要有的
