### ISSUE TITLE
[BUG] 同一配置文件，CFW导入成功，CFA导入时提示proxy-providers下载失败

### ISSUE THREAD

**Issue by waldens** [Kr328/ClashForAndroid#736]
别误会，知道作者不用Windows。说CFW能导成功，CFA不行，并不是说CFA不好，只是描述客观现象。

**描述出现的错误**
如题

**如何复现该错误**
复现步骤:
1. 先在CFW中连上可用的代理
2. 在CFW中导入URL（最终节点信息是杜撰的，仅供本测试用，不影响测试目的）: `https://gist.githubusercontent.com/waldens/75328a42b9dc4133401a4d88e69949ab/raw/%25E4%25B8%25BB%25E8%25A7%2584%25E5%2588%2599.yaml`
结果：导入成功
3. 在CFA中连上可用的代理（已登录推特电报验证过）
4. CFA中导入如上URL配置

**预期行为**
第4步：
预期结果：导入成功
实际结果：导入失败

**屏幕截图**
![1111111](https://user-images.githubusercontent.com/3130930/100514632-75303c80-31b1-11eb-9f19-02c3e0713484.jpg)
![2222222](https://user-images.githubusercontent.com/3130930/100514634-782b2d00-31b1-11eb-9a2a-1bf32594d473.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Redmi Note 7
 - 系统/ROM: MIUI 10.2
 - Android 版本: Android 9
 - ROM版本: xiaomi.eu 10.2.8.0

**应用信息**
 - 版本: 2.1.5-arm64-v8a
 - 安装包文件名: 
 - 应用来源: release中下载

**附加信息**
是否可能主配置文件走代理，而下载proxy-providers没走代理（当前gist被墙）导致下载失败？

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
检查网络问题

**Comment by waldens** [comment]
@Kr328 10分钟后附上录像

**Comment by Kr328** [comment]
@waldens 别附带了 就是网络问题

**Comment by waldens** [comment]
@Kr328   那是一切换到浏览器，网络就好了。一切回CFA，网络就出问题啦？
也不是说一定是BUG（只要只有REQ和BUG模板，没提问模板），只是真诚请教下：怎么去排查问题。录像只展示了浏览器，实际电报、脸书客户端全都网络正常，只有CFA网络异常？这种网络问题怎么排查呢……
https://verynginx.wistia.com/medias/oyt7zlpuzn

**Comment by waldens** [comment]
是否可能URL导入主配置文件时，走代理，而二次导入proxy-providers时，没走代理（当前gist被墙）导致下载失败？

**Comment by Kr328** [comment]
@waldens 上游的 provider 的下载会被要求强制直连 CFA 只能一定程度上解决 DNS 污染问题 下载的时候 完全直连

**Comment by waldens** [comment]
@waldens 原来如此，是谁强制直连的啊？我记得CFA没用clash core吧？没办法走代理吗？
因为这样CFA和CFW要维护俩配置了…

**Comment by Kr328** [comment]
@waldens Clash 自身要求的直连 因为会有 鸡生蛋 蛋生鸡 的问题

**Comment by waldens** [comment]
@waldens 明白了，套娃。还是想办法托管到没墙的网站吧，又要不泄露订阅，又要没墙，又要有固定的URL，真不好找。谢谢啦

**Comment by LM-Firefly** [comment]
@waldens 搭个subconverter 做中转

**Comment by SplitGemini** [comment]
> @waldens 明白了，套娃。那我还是想办法托管到没墙的网站吧，又要不泄露订阅，又要没墙，又要有固定的URL，真不好找。谢谢啦

gist做订阅链接而不是proxy-providers链接

**Comment by trulynb** [comment]
老哥解决了吗  我和你同一个问题    然后我尝试用gitee fork github上的规则   但是现在提示initial rule provider error yaml line50 mapping values are not allowed in thiscontext   不知道怎么搞了

**Comment by qhfls** [comment]
> > @waldens 明白了，套娃。那我还是想办法托管到没墙的网站吧，又要不泄露订阅，又要没墙，又要有固定的URL，真不好找。谢谢啦
> 
> gist做订阅链接而不是proxy-providers链接

gitcdn.xyz做gist的CDN试试
