### ISSUE TITLE
[BUG] 访问控制列表加载不出

### ISSUE THREAD

**Issue by xiaxianxue** [Kr328/ClashForAndroid#739]
**描述出现的错误**
在没有开启clash的情况下,进入设置，网络，VPN service选项中，访问控制应用包列表选项卡中，没有任何应用加载出，没有任何权限请求弹出

**如何复现该错误**
复现步骤:
1. 进入相关功能即可

**预期行为**
通过GUI界面提供的选项，直接进入功能

**屏幕截图**
手机网页端提交，无法提供截图

**设备信息 (请完成以下信息):**
 - 机型: [OnePlus 7Pro]
 - 系统/ROM: [MIUI 12]
 - Android 版本 [10]
 - ROM版本 [20.11.15]

**应用信息**
 - 版本: [2.1.6_arm64_v8a]
 - 安装包文件名: [app-release-arm64-v8a.apk]
 - 应用来源: [github]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
允许应用访问应用列表了吗

**Comment by Kr328** [comment]
你们 MIUI 的 权限管理 里 有一个额外的权限

**Comment by xiaxianxue** [comment]
> 允许应用访问应用列表了吗

允许访问列表了，不过我后来想了一下，可能是我使用了thonox的原因，然后在thonox应用列表里一查，果不其然，查询其它信息的权限为禁前台允许。后来，将权限重新设定为始终允许，重新打开软件，应用列表就加载出来了🌚🌚，阿这……属实尴尬，又提交了一个没啥用的reply😂😂
