### ISSUE TITLE
通知栏实时网速显示问题

### ISSUE THREAD

**Issue by LittleDragonSun** [Kr328/ClashForAndroid#74]
我观察发现通知栏的实时网速显示的并非通过代理服务器的速率，而是非bypass应用的速率，即使是直连或者通过代理。

一般此类代理软件通常显示为通过代理的速率，不显示直连的速率。望作者修改为显示通过代理的速率以符合用户的认知，不会造成误解。

**Comment by Kr328** [comment]
预期行为
