### ISSUE TITLE
[Feature Request] 申请应用添加到系统白名单

### ISSUE THREAD

**Issue by JiZhi-Error** [Kr328/ClashForAndroid#746]
**功能描述**
申请应用添加到系统白名单

**描述你希望的实现方式**
相关代码：
manifest：
//判断是否在白名单中L：
@RequiresApi（api = Build.VERSION_CODES.M）
private boolean isIgnoringBatteryOptimizations（）{
boolean isIgnoring = false;
PowerManager powerManager =（PowerManager）getSystemService（Context.POWER_SERVICE）;
如果（powerManager！= null）{
isIgnoring = powerManager.isIgnoringBatteryOptimizations（getPackageName（））;
}
return isIgnoring;
}
//申请加入到白名单
@RequiresApi（api = Build.VERSION_CODES.M）
public void requestIgnoreBatteryOptimizations（）{
试试{
Intent intent = new Intent（Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS）;
intent.setData（Uri.parse（“ package：” + getPackageName（）））;
startActivity（intent）;
} catch（Exception e）{
e.printStackTrace（）;
}
}

**Comment by JiZhi-Error** [comment]
@Kr328

**Comment by Kr328** [comment]
这个对主流魔改 ROM 无效 (MIUI, ColorOS, OneUI

而对 AOSP 及 AOSP 衍生 的 类原生 ROM 没有任何意义 (并不需要修改电池优化就能正常工作

那么 这个功能的意义何在 增加一个权限并顺便降低用户信任度吗
