### ISSUE TITLE
[BUG] 覆写DNS 崩溃

### ISSUE THREAD

**Issue by Olivercoco** [Kr328/ClashForAndroid#747]
**描述出现的错误**
 覆写DNS，添加NameServers。添加到第二个条目，程序崩溃。
**如何复现该错误**
复现步骤:

1. 设置
2. 覆写
3. DNS策略使用覆写
4. NameServers添加一个条目
5. NameServers添加第二个条目

**屏幕截图**
![image](https://user-images.githubusercontent.com/39828052/101436641-84e61880-3949-11eb-95ea-fadd07a9a12d.png)

**设备信息 (请完成以下信息):**
 - 机型: [GALAXY S9]
 - 系统/ROM: [One UI 2.5]
 - Android 版本 [10]
 - ROM版本 [2.5]

**应用信息**
 - 版本: [例如: 2.1.6]
 - 安装包文件名: [app-release-arm64-v8a.apk]
 - 应用来源: [Github]

**日志**
很遗憾，尝试抓取日志，结果日志为 空。

**Comment by kettly1260** [comment]
请问一下这个dns设置是在哪啊？我点进去几个选择没有一个可以填写dns服务器的

**Comment by Mit2g** [comment]
> 请问一下这个dns设置是在哪啊？我点进去几个选择没有一个可以填写dns服务器的

设置 覆写 DNS策略 使用覆写

**Comment by 491575758-cloud** [comment]
请问下这个配置在哪里弄啊，我之前在网上买了半年结果才用两个月就进不去了

**Comment by xvgr** [comment]
> 
> 
> 请问下这个配置在哪里弄啊，我之前在网上买了半年结果才用两个月就进不去了

去找自己买的机场，如果是自建节点需要自己编写配置文件。

**Comment by Kr328** [comment]
尝试新版本

**Comment by Olivercoco** [comment]
应用版本 2.3.22
问题已解决。
