### ISSUE TITLE
[Feature Request] 希望更换IP数据库

### ISSUE THREAD

**Issue by Celeter** [Kr328/ClashForAndroid#749]
通常使用的 GeoIP 数据库是来自于 MaxMind 的 GeoLite2 免费数据库。这个数据库目前存在一下几个问题：

数据量大：数据库庞大，包含全球的 IP 地址段，约 4 MB
准确度低：对中国大陆的 IP 地址判定不准，如：香港阿里云的 IP 被判定为新加坡、中国大陆等
而最致命的问题就是准备度低，这会导致代理工具查询后得到错误，做出错误的分流判定，最终导致用户体验不佳。

希望使用 https://github.com/Hackl0us/GeoIP2-CN 中的IP数据库

**Comment by Kr328** [comment]
应用不针对中国大陆用户设计

**Comment by Olivercoco** [comment]
可以考虑提供一个入口替换Country.mmdb 吗？

**Comment by Kr328** [comment]
@Olivercoco #441
