### ISSUE TITLE
打开amp cdn的链接出错！

### ISSUE THREAD

**Issue by offferu** [Kr328/ClashForAndroid#75]
现象：打开含有CDN的链接会弹出错误，
如：https://gizmodo-com.cdn.ampproject.org/v/s/gizmodo.com/the-biggest-problems-with-bluetooth-audio-are-about-to-1840461602/amp?amp_js_v=a2&amp_gsa=1&usqp=mq331AQCKAE%3D#referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s&ampshare=https%3A%2F%2Fgizmodo.com%2Fthe-biggest-problems-with-bluetooth-audio-are-about-to-1840461602

用clash for android 打开是这样的
https://gizmodo-com.cdn.ampproject.org/v/s/gizmodo.com/the-biggest-problems-with-bluetooth-audio-are-about-to-1840461602/amp?amp_js_v=a2&amp_gsa=1&usqp=mq331AQCKAE%3D#referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s
缺少了后面部分&ampshare=https%3A%2F%2Fgizmodo.com%2Fthe-biggest-problems-with-bluetooth-audio-are-about-to-1840461602

[img]https://ibb.co/17ztYkG[/img]

**Comment by Kr328** [comment]
检查你自己的浏览器
**Clash 没有修改 http/https 的能力**

**Comment by offferu** [comment]
[https://ibb.co/17ztYkG](url)
