### ISSUE TITLE
[BUG] 深色模式部分图标看不见。

### ISSUE THREAD

**Issue by ZerOri** [Kr328/ClashForAndroid#751]
![Screenshot_2020-12-12-10-47-20-973_com github kr328 clash](https://user-images.githubusercontent.com/46775615/101970787-81170680-3c67-11eb-9a8c-3e150e438735.jpg)
![Screenshot_2020-12-12-10-47-42-336_com github kr328 clash](https://user-images.githubusercontent.com/46775615/101970791-84aa8d80-3c67-11eb-9752-31fc01441e3a.jpg)
RT，OLED屏，深色模式下由于图标也是黑色，与背景混淆导致图标看不清，建议更改深色下图标颜色。

**Comment by Kr328** [comment]
#610
