### ISSUE TITLE
[BUG] Android app not tumneling adult websites

### ISSUE THREAD

**Issue by Pedramngh** [Kr328/ClashForAndroid#760]
**Describe the bug**
The android app doesn't tunnel adult websites but with others websites and apps it works fine. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: [mi note 10]
 - ROM: [e.g: AOSP]
 - ROM Version:
 - Android Version [10]

**Application Info (please complete the following information):**

 - Version: [e.g. 1.1.10]
 - Apk File Name: [e.g. app-release-arm64-v8a.apk]
 - Distribution Channel: [e.g. Google Play]

**Additional context**

**Configure**
If applicable, paste **removed server info** configure
```yaml
# paste here
```

**Logs**
If applicable, paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
complete template plz
