### ISSUE TITLE
[BUG] Socks5 能否返回IPv6不支持信息

### ISSUE THREAD

**Issue by clatteringmarion** [Kr328/ClashForAndroid#764]
**描述出现的错误**
在本身网络支持IPv6但是梯子不支持IPv6的环境下， 使用Adguard Android作为VPN服务 + Clash For Android作为Socks5服务会导致支持IPv6的网站无法访问。 Clash记录的错误代码是IP version error。 这个有点看脸.... 5次里面2-3次会出现这个问题

**如何复现该错误**
复现步骤:
1. 开启Adguard并打开Clash
2. 访问支持IPv6的网站
3. 烧香期待能打开

**预期行为**
如果梯子不支持IPv6， 根据Adguard那边说法 作为Socks5 proxy需要返回相对应不支持该地址的信息， 这样Adguard会尝试连接v4而不是v6。

**屏幕截图**
暂无

**设备信息 (请完成以下信息):**
 - 机型: Samsung Note9
 - 系统/ROM: Android 10 OneUI 2.5
 - Android 版本 10
 - ROM版本 FTK1

**应用信息**
 - 版本: 2.1.5-arm64-v8a
 - 安装包文件名: 无
 - 应用来源: Google Play

**附加信息**
AdGuard CoreLibs: https://github.com/AdguardTeam/CoreLibs/issues/1393

**配置文件**
暂无

**日志**
暂无

P.S. 手残， 标题真不知道怎么写了.....

**Comment by Kr328** [comment]
反馈上游 请

**Comment by HinataKato** [comment]
我记得Adguard+Clash4A Sock5 IPv6是正常的需要 fake-ip 模式
