### ISSUE TITLE
[BUG] PROCESS-NAME is not working on android 9 (no-root) causing permission denied

### ISSUE THREAD

**Issue by ni-max** [Kr328/ClashForAndroid#767]
**Describe the bug**

PROCESS-NAME rules cause:
`[Process] Resolve process of tcp:<IP>:<PORT> failure: permission denied`

According to this:  [process_linux.go#L251](https://github.com/Kr328/clash/blob/42cfeaf218e71bea7af02ee2cbca2f503aa6b0bf/rules/process_linux.go#L251)
I think the app does not have access to `/proc/<PID/fd`
```
$ adb shell 'ls -al /proc/18570/fd'
ls: /proc/18570/fd: Permission denied
```

**To Reproduce**

- add this rule: `PROCESS-NAME,org.mozilla.firefox,REJECT`
- debug logcat: `[Process] Resolve process of tcp:<IP>:<PORT> failure: permission denied`

**Expected behavior**

Blocking the Firefox(org.mozilla.firefox) app.

**Device Info (please complete the following information):**

 - Device: Galaxy Note 8 (no-root)
 - Android Version: 9

**Application Info (please complete the following information):**

 - Version: 2.1.5
 - Apk File Name: app-release-arm64-v8a.apk
 - Distribution Channel: Google Play

Thanks.

**Comment by Kr328** [comment]
try latest version

**Comment by ni-max** [comment]
👌 I just did and it works perfectly.

keep up the good work 👏
