### ISSUE TITLE
[BUG] 启用CFA后其他设备链接手机热点速度变慢

### ISSUE THREAD

**Issue by Scarecrow-ai** [Kr328/ClashForAndroid#771]
**描述出现的错误**
启用CFA后其他设备(测试了Android手机,Android TV,Windows PC)链接手机热点速度变慢

**如何复现该错误**
复现步骤:
1. 启用CFA
2.启用热点
3. 链接热点

**设备信息 (请完成以下信息):**
 - 机型: 一加7Pro
 - 系统/ROM: O2os
 - Android 版本 11
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: 2.1.6
 - 安装包文件名: universal
 - 应用来源: release

**Comment by Kr328** [comment]
填完信息 请
