### ISSUE TITLE
[BUG] 从 URL 下载配置提示下载失败

### ISSUE THREAD

**Issue by sbilly** [Kr328/ClashForAndroid#773]
**描述出现的错误**
从 URL 下载配置提示下载失败，打开日志查看器发现有日志：

Info
Start initial provider home-proxies

Warning
Load profile override failure: open /data/user/0/com.github.kr328.clash/files/clash/override.json: no such file or directory

我从服务器看到已经访问并下载了配置文件。相应配置文件我在笔记本上能正常加载。

**预期行为**
应该能正常下载并解析

**屏幕截图**
无

**设备信息 (请完成以下信息):**
 - 机型: SONY TV
 - 系统/ROM: Unknown
 - Android 版本 Unknown
 - ROM版本 Unknown

**应用信息**
 - 版本: latest
 - 安装包文件名: github release 下载
 - 应用来源: github release 下载

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
Info
Start initial provider home-proxies

Warning
Load profile override failure: open /data/user/0/com.github.kr328.clash/files/clash/override.json: no such file or directory
```

**Comment by Kr328** [comment]
全部日志贴上来 请

这段无论有没有都不会影响下载

以及出错截图

**Comment by sbilly** [comment]
日志就是上面这些。

发现是配置文件里面的 proxy-provider 域名失效了，改为 IP 即正常
