### ISSUE TITLE
[BUG] cursor window allocation of 2048kb failed

### ISSUE THREAD

**Issue by zdf0145** [Kr328/ClashForAndroid#774]
**描述出现的错误**
启动时报cursor window allocation of 2048kb failed。

**如何复现该错误**
复现步骤:
1. 代理启动时

**设备信息 (请完成以下信息):**
 - 机型: 小米6
 - 系统/ROM: MIUI9.2
 - Android 版本 [7.1.1]

**应用信息**
 - 版本: 2.1.5-arm64-v8a
 - 应用来源:  Google Play

**Comment by Kr328** [comment]
#503
