### ISSUE TITLE
[Feature Request] 希望增加适合电视Android TV通用版的节点测试功能

### ISSUE THREAD

**Issue by nicolasking84** [Kr328/ClashForAndroid#780]
**功能描述**
希望增加适合电视Android TV通用版的节点测试功能，电视不能触屏刷新看不到节点的延迟

**描述你希望的实现方式**
在右上角的三个点设置里增加节点延迟测试就行了

**附加信息**
感谢

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/605#issuecomment-683448549
