### ISSUE TITLE
[BUG] clash后台崩溃

### ISSUE THREAD

**Issue by Donkey-Benjamin** [Kr328/ClashForAndroid#782]
**描述出现的错误**
clash后台运行时经常会崩溃

**如何复现该错误**
复现步骤:
1. 打开clash
2. 后台运行

**预期行为**
不崩溃

**屏幕截图**
![Screenshot_2021-01-24-01-47-14-532_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/77800168/105613071-14ad2c80-5dfb-11eb-93a7-5df3bb032ac5.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Redmi k30pro
 - 系统/ROM: MIUI12 eu版
 - Android 版本 ：11
 - ROM版本 12.2.2

**应用信息**
 - 版本: 2.1.6-arm64-v8a
 - 安装包文件名:app-release-arm64-v8a.apk
 - 应用来源:GitHub

**Comment by Kr328** [comment]
看起来是 MIUI 的  API 的问题

**Comment by Donkey-Benjamin** [comment]
对的，好像是双开应用的问题，安卓11的miui12真的问题多的不得了
