### ISSUE TITLE
[BUG] CFA与华为手机的加密dns功能貌似有冲突

### ISSUE THREAD

**Issue by GHOSTagw** [Kr328/ClashForAndroid#783]
**描述出现的错误**
当开启emui的加密dns时，CFA可以连通代理服务器，但是却没有流量通过，CFA显示网速为0，无法访问外网，国内网络正常访问。
关闭加密dns后一切正常。
尝试使用redir模式，依旧无法访问外网。

**如何复现该错误**
复现步骤:
设置加密dns，再开启clashforandroid，即可复现。

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![Screenshot_20210124_115939_com github kr328 clash](https://user-images.githubusercontent.com/40930046/105620844-003d5400-5e3c-11eb-8cfe-5e1a5abfe88e.jpg)
感觉和平常差不多

**设备信息 (请完成以下信息):**
 - Honor V9 (EMUI 9.1 Android 9)
 - Huawei M6 (Emui 11.0 Android 10)
 - 两个设备都是这个问题......

**应用信息**
 - 版本: 2.1.6
 - 应用来源: Github

**Comment by Kr328** [comment]
是这样的

包括原生系统一定程度上 (指设置国内的 DoT) 也会这样

这个不是应用能解决的

**Comment by iKira** [comment]
> 是这样的
> 
> 包括原生系统一定程度上 (指设置国内的 DoT) 也会这样
> 
> 这个不是应用能解决的


能分析下导致这个问题的原因吗？

CFA从2.1.6到2.3.21一直存在这个问题。不单只是国内的DoT，用境外VPS搭建的DoT同样会出现这个问题，由此可见这可能是Clash对DNS请求的处理机制与Android系统的“私人DNS”冲突导致的。

我用v2rayNG客户端，系统同样开启“私人DNS”，这个问题就不会出现，所以我怀疑是不是x2ray-core/xray-core和Clash对DNS请求的处理机制有差异导致的，还请解答下，thx :)
