### ISSUE TITLE
[Feature Request] 希望给TV版加上icon，androidTV装了要到设置里面找很麻烦

### ISSUE THREAD

**Issue by Darren-X1** [Kr328/ClashForAndroid#785]
[Feature Request] 希望给TV版加上icon，androidTV装了要到设置里面找很麻烦

**Comment by Kr328** [comment]
但凡是个 Android 应该都会去找到 目前的入口 放置在启动器

已经被魔改到启动器都不正常的 ROM 甚至连最基本的信息都不提供 那就只能等有缘人提出解决方案了

**Comment by Darren-X1** [comment]
我是chromecast with android tv，查了下无法显示是因为没有那个电视上的长方形的icon

**Comment by Kr328** [comment]
那就归到 #58
