### ISSUE TITLE
[BUG] 谷歌商店下载应用一直等待中

### ISSUE THREAD

**Issue by lfscqk67** [Kr328/ClashForAndroid#790]
**描述出现的错误**
我换了k30s，miui12的系统，可以打开谷歌商店，图片视频啥的也没问题，油管也是秒开，但是下载应用一直等待中，但用v2ray下载却是正常的

**屏幕截图**
![Screenshot_2021-01-30-11-43-17-163_com android ve](https://user-images.githubusercontent.com/37235589/106346240-87814080-62f0-11eb-942b-23d80861636d.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米K30s至尊纪念版
 - 系统/ROM: MIUI12.0.10稳定版
 - Android 版本: 10
 - ROM版本： 12.0.10.0（QJDCNXM）

**应用信息**
 - 版本: 2.1.5
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: GitHub

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<# Logcat on 2021-01-30 11:28:40
11:28:42 |Info| Android tun started
11:28:42 |Info| Listen TCP redirect 43275
11:28:43 |Warning| Load profile override failure: open /data/user/0/com.github.kr328.clash/files/clash/override.json: no such file or directory
11:28:43 |Info| Start initial compatible provider 🚀直接连接
11:28:43 |Info| Start initial compatible provider 🔰国外流量
11:28:43 |Info| Start initial compatible provider 🎬国外媒体
11:30:13 |Info| Android tun started
11:30:13 |Info| Listen TCP redirect 40539
11:30:13 |Warning| Load profile override failure: open /data/user/0/com.github.kr328.clash/files/clash/override.json: no such file or directory>
```

**Comment by Kr328** [comment]
订阅泄漏了知道了吗

让把配置文件 处理之后 再粘贴

还有日志 里什么都没有

只开日志 不去复现问题 毫无意义

**Comment by akw5454521** [comment]
全局模式正常吗

**Comment by NneurotransmitterR** [comment]
尝试关闭MIUI系统下载的迅雷加速再看看。

**Comment by Feiyuyu0503** [comment]
我也是K30S，也遇到过同样的问题，我使用了如下手段后，就没有这问题了。
如果你使用了访问控制，不要令 “下载管理程序”不允许走代理，且需要允许“下载管理程序”能够自启动（不妨把迅雷加速也关闭）
另外CFA中设置-覆写-Hosts中添加一条 'services.googleapis.cn:172.217.31.234'

**Comment by iKira** [comment]
以下这几个原因：
1、主机的IP本身不是原生IP，被Google屏蔽了
2、配置文件规则写得有问题，IP规则放到域名规则后面
3、配置文件DNS没有写好，DNS服务器可以用DoH

**Comment by lfscqk67** [comment]
> 订阅泄漏了知道了吗
> 
> 让把配置文件 处理之后 再粘贴
> 
> 还有日志 里什么都没有
> 
> 只开日志 不去复现问题 毫无意义

是我的节点问题，添麻烦了，老哥把问题关闭吧
