### ISSUE TITLE
[issue] 大家怎么解决divine配置在clash for Android 的下载失败的问题的

### ISSUE THREAD

**Issue by trulynb** [Kr328/ClashForAndroid#794]
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/Outbound.yaml   其中Rule Provider的规则片段链接在浏览器都能打开   但是在APP里一直报错   比如
![image](https://user-images.githubusercontent.com/17597573/106553078-90be1780-6553-11eb-9b2a-78e27c6d3566.png)

大家有碰到过这种情况吗

**Comment by akw5454521** [comment]
被污染了，下载到本地导入吧

**Comment by trulynb** [comment]
> 被污染了，下载到本地导入吧

具体怎么操作   能大致讲一下吗  我不知道文件路径  该放哪
