### ISSUE TITLE
[BUG] 配置文件运行时\运行后消失

### ISSUE THREAD

**Issue by yyxida** [Kr328/ClashForAndroid#796]
**描述出现的错误**
配置文件在使用中或第二次点击运行按钮后会自己消失，需要强制停止应用才能恢复

**如何复现该错误**
复现步骤:
1. 新添加配置或强制停止应用之后重新运行
2. 点击运行
3. 正常运行
4. 重新点击运行或使用一段时间后“代理”中的配置会全部消失

**预期行为**
正常运行

**屏幕截图**
![Screenshot_20210202-172949](https://user-images.githubusercontent.com/22792135/106583498-21125180-6580-11eb-9d32-773e68081f15.jpg)
![Screenshot_20210202-172953](https://user-images.githubusercontent.com/22792135/106583562-31c2c780-6580-11eb-8214-4788c4637ae8.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 一加7T pro
 - 系统/ROM: 氢OS 11 公测版beta1
 - Android 版本:11
 - ROM版本:OP7TPro_H2_ BETA _01

**应用信息**
 - 版本: 2.1.5-arm64-v8a
 - 安装包文件名: 
 - 应用来源: Google Play

**附加信息**
配置文件为acl4ssr订阅转换生成的

**配置文件**

```yaml
[config.txt](https://github.com/Kr328/ClashForAndroid/files/5910339/config.txt)

```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
# Logcat on 2021-02-02 17:26:20
17:26:24 |Info| Android tun started
17:26:24 |Info| Listen TCP redirect 42397
17:26:24 |Warning| Load profile override failure: open /data/user/0/com.github.kr328.clash/files/clash/override.json: no such file or directory
17:26:25 |Info| Start initial compatible provider 📺 巴哈姆特
17:26:25 |Info| Start initial compatible provider 🇺🇲 美国节点
17:26:25 |Info| Start initial compatible provider 🇯🇵 日本节点
17:26:25 |Info| Start initial compatible provider 🇨🇳 台湾节点
17:26:25 |Info| Start initial compatible provider 🇭🇰 香港节点
17:26:25 |Info| Start initial compatible provider ♻️ 自动选择
17:26:25 |Info| Start initial compatible provider 🚀 节点选择
17:26:25 |Info| Start initial compatible provider 🛑 广告拦截
17:26:25 |Info| Start initial compatible provider 🍃 应用净化
17:26:25 |Info| Start initial compatible provider 🌏 国内媒体
17:26:25 |Info| Start initial compatible provider 🎥 奈飞视频
17:26:25 |Info| Start initial compatible provider 🇰🇷 韩国节点
17:26:25 |Info| Start initial compatible provider 🇸🇬 狮城节点
17:26:25 |Info| Start initial compatible provider 🎯 全球直连
17:26:25 |Info| Start initial compatible provider 🌍 国外媒体
17:26:25 |Info| Start initial compatible provider 🎥 奈飞节点
17:26:25 |Info| Start initial compatible provider 📺 哔哩哔哩
17:26:25 |Info| Start initial compatible provider 📢 谷歌FCM
17:26:25 |Info| Start initial compatible provider 🍎 苹果服务
17:26:25 |Info| Start initial compatible provider 🚀 手动切换
17:26:25 |Info| Start initial compatible provider 📹 油管视频
17:26:25 |Info| Start initial compatible provider Ⓜ️ 微软云盘
17:26:25 |Info| Start initial compatible provider 🐟 漏网之鱼
17:26:25 |Info| Start initial compatible provider 🎮 游戏平台
17:26:25 |Info| Start initial compatible provider 📲 电报消息
17:26:25 |Info| Start initial compatible provider 🎶 网易音乐
17:26:25 |Info| [DNS] Main 223.5.5.5:53
17:26:25 |Info| [DNS] Main 119.29.29.29:53

```

**Comment by offlineface** [comment]
设备：pixel 5 4G
Android版本：11
Clash版本：prerelease和2.1.5 V8a都尝试过
问题和你的一模一样。

日志：
"08:02:30 |Warning| dial 被墙服务🚧 error: us35.clashcloud.tech:23524 connect error: dial tcp4 162.14.8.124:23524: connect: network is unreachable
08:02:31 |Warning| Load profile override failure: open /data/user/0/com.github.kr328.clash/files/clash/override.json: no such file or directory
08:02:31 |Info| Start initial compatible provider 广告拦截❌
08:02:31 |Info| Start initial compatible provider 浏览劫持🚫"

**Comment by jap33** [comment]
配置文件运行时\运行后消失重启手机后才正常

**Comment by offlineface** [comment]
对我来说重启手机也没卵用。

**Comment by offlineface** [comment]
似乎发生在切换网络的时候。比如从WiFi到4G, 从4G到WiFi，然后配置文件重新载入然后就崩溃了。

**Comment by nagisastudio** [comment]
+1，不过发现似乎是因为节点过多的问题，如果节点较少就不会触发这个BUG，节点过多的情况下就需要结束程序再开启一次。

**Comment by zbodo** [comment]
> +1，不过发现似乎是因为节点过多的问题，如果节点较少就不会触发这个BUG，节点过多的情况下就需要结束程序再开启一次。

同样因为节点过多触发了这个bug

**Comment by gamerenzz** [comment]
同样因为节点过多触发了这个bug

**Comment by Kr328** [comment]
新版本 传日志 请

**Comment by offlineface** [comment]
日志就不放了，反正就是丝滑。
