### ISSUE TITLE
[BUG] 安装在小米智能盒子上，无法手动更新配置，即已有配置右侧的三个点无法点击

### ISSUE THREAD

**Issue by qingyun1988** [Kr328/ClashForAndroid#797]
**描述出现的错误**
安装在小米智能盒子上，无法手动更新配置，即已有配置右侧的三个点无法点击，如图所示。
![xiaomi](https://user-images.githubusercontent.com/38597436/106997682-42608100-67be-11eb-81ea-3aafa6491ced.jpg)

**预期行为**
希望可以在电视上点击实现手动更新配置，不然很麻烦。谢谢！

**设备信息 (请完成以下信息):**
小米盒子Mi box2

**Comment by EKyero** [comment]
@qingyun1988 插上鼠标，设置自动更新吧

**Comment by qingyun1988** [comment]
> @qingyun1988 插上鼠标，设置自动更新吧

自动更新设置了，但貌似没什么用

**Comment by Kr328** [comment]
#803
