### ISSUE TITLE
[Feature Request] 希望更新下内核

### ISSUE THREAD

**Issue by lis923** [Kr328/ClashForAndroid#798]
**功能描述**
请清晰的描述你想要的功能

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
内核好久没更新了

**Comment by ygsk10** [comment]
Kr328: 

请务必按照 issue 模板 创建 issue

#798 Closed

**Comment by ygsk10** [comment]
请务必按照 issue 模板 创建 issue

@Kr328 closed this

或者

Duplicate of #722

@Kr328 added the unplan label
