### ISSUE TITLE
[Feature Request] 请问在哪里能自定义配置文件呢？

### ISSUE THREAD

**Issue by ArsenicX** [Kr328/ClashForAndroid#799]
**功能描述**
我的机场主把一些国内能直连的网站划分为了国外网站，走了代理模式
我希望能让我手动把这些网站的策略改成我想要的

**描述你希望的实现方式**
我知道代理、规则、策略这些东西是写在一起的，我希望的是能像电脑版clash一样，有地方能让我编辑被下载下来的yaml文件，我去手动编辑改动我想要的规则
比如下载下来的yaml文件里面是：
```
rules:
  - DOMAIN-SUFFIX,google.com,PROXY
```
我手动编辑文件改成：
```
rules:
  - DOMAIN-SUFFIX,google.com,DIRECT
```

**附加信息**
或者请问下下载下来的yaml文件在哪啊？我手机已经root了，我找到了直接改。

**Comment by Kr328** [comment]
自己下载好之后文件导入

**Comment by ArsenicX** [comment]
> 自己下载好之后文件导入

我更希望dalao能麻烦做个直接修改的功能
从文件导入的话，麻烦的是没法更新节点。每次更新都需要我重新去官网上下载-编辑-导入
如果能直接修改，我直接在软件内更新订阅，然后从qq里面把自定义的规则复制粘贴进去就行了，能更方便些

**Comment by Kr328** [comment]
可编辑和可更新是互斥的

为了防止 "已经改好的规则 更新之后又没了" 的 Issue 出现

以及有这样的需求 为什么不用 provider 呢

**Comment by ArsenicX** [comment]
我以前都不知道 provider 这东西...折腾了半天终于看懂改好了，感谢大佬😂
