### ISSUE TITLE
[Feature request] 下载配置文件时请求头 UA 增加 "ClashForAndroid"

### ISSUE THREAD

**Issue by DesperadoJ** [Kr328/ClashForAndroid#80]
[v2board](https://github.com/v2board/v2board) 的订阅控制器通过识别请求头 UA 来判断代理客户端类型，由此做到一个订阅链接适配不同代理客户端。返回 Clash 配置文件需要 [UA 中包含 "clash" 字样](https://github.com/v2board/v2board/blob/e576d829554fe8407f38d7b188083a0cec2f3860/app/Http/Controllers/ClientController.php#L37)，目前 ClashX 与 Clash for Windows 均可以正常下载配置文件，由于 ClashForAndroid 未对 UA 做出修改，不能正常下载。希望下个版本可以在 UA 中增加 "ClashForAndroid"

**Comment by Kr328** [comment]
#46
