### ISSUE TITLE
[Feature Request] 希望能长按导出单链接

### ISSUE THREAD

**Issue by miku646** [Kr328/ClashForAndroid#800]
**功能描述**
希望小猫咪能增加导出节点单链接。虽然可以通过yaml获取节点，如果想从clash里面提取几个节点的话，需要手动在其他客户端手动输入配置

**描述你希望的实现方式**
长按节点可以复制单链接

**附加信息**
无

**Comment by Kr328** [comment]
不做 太麻烦

**Comment by Roiyaru** [comment]
@miku646 提高使用门槛可以有效减少bug的发生（bushu）
