### ISSUE TITLE
[BUG] Clash不识别我自己添加的CA证书

### ISSUE THREAD

**Issue by supertsy5** [Kr328/ClashForAndroid#801]
**描述出现的错误**
我在Android系统设置中添加了我自己的CA证书（在电脑上的Trojan客户端可正常使用），Clash日志报告`certificate signed by unknown authority`，与不添加CA相同效果

**如何复现该错误**
复现步骤:
1. 打开“设置”应用 - 密码和安全 - 系统安全 - 加密与凭据 - 从SD卡安装 - 选择CA证书文件 - 添加证书
2. 打开“Clash”应用 - 配置 - 新配置 - 文件 - 选择配置文件 - 设置名称 - 保存
3. 启动Clash
4. 开始捕捉日志

**预期行为**
正常识别证书并建立连接

**设备信息 :**
 - 机型: 小米红米 Note 7
 - 系统/ROM: MIUI Global 12
 - Android 版本 10
 - ROM版本 12.0.1

**应用信息**
 - 版本: 2.1.5-arm64-v8a
 - 应用来源: Google Play

**日志**
```
WARN[0040] dial PROXY error: ......(my server IP and port) connect error: x509: certificate signed by unknown authority
```

**Comment by Kr328** [comment]
Android 7.0 起 应用默认只信任系统证书

golang 也确实只会去读系统证书 这个可能需要反馈给 golang

**Comment by supertsy5** [comment]
> Android 7.0 起 应用默认只信任系统证书
> 
> golang 也确实只会去读系统证书 这个可能需要反馈给 golang

谢谢回答。我继续用`skip-cert-verify: true`。

**Comment by Inasayang** [comment]
但是这里https://github.com/Kr328/ClashForAndroid/blob/main/app/src/main/res/xml/network_security_config.xml加上了读取用户CA, 依然不可以验证
