### ISSUE TITLE
[BUG]  添加新配置 从文件中导入时出错 错误信息 java.io.FileNotFoundException: permission denied

### ISSUE THREAD

**Issue by XieYuDeGitHub** [Kr328/ClashForAndroid#805]
**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. 配置
2. 新配置
3. 从文件中导入
4. 选择yml文件
5. 保存
6. 下载失败

**预期行为**
成功添加配置

**屏幕截图**

**设备信息 (请完成以下信息):**
 - 机型:  OPPO A33
 - 系统/ROM: MIUI 9.5
 - Android 版本   5.1
 - ROM版本  9.5.2.0

**应用信息**
 - 版本:   v2.1.5
 - 安装包文件名:   app-arm64-v8a-release.apk
 - 应用来源: https://github.com/Kr328/ClashForAndroid/releases

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
#388
