### ISSUE TITLE
[Feature Request]  能否改进延迟测量方式

### ISSUE THREAD

**Issue by 22hello** [Kr328/ClashForAndroid#807]
**功能描述**
改进延迟测量，向上滑动测量很容易误触

**描述你希望的实现方式
增加延迟测量按钮

**附加信息**
不知道为什么用vmess节点订阅导入时会自动测ping

**Comment by Kr328** [comment]
这功能由上游实现

**Comment by 22hello** [comment]
只能等上游实现吗

**Comment by Kr328** [comment]
看错了

**Comment by 22hello** [comment]
谢谢 dalao

**Comment by HXHGTS** [comment]
建议搞成clash for windows那样，下拉以后进行批量测速，不然效率太低了
