### ISSUE TITLE
[Feature Request] Clash for Android 能否解决下安卓看TikTok的问题

### ISSUE THREAD

**Issue by seoho8908** [Kr328/ClashForAndroid#808]
Clash for Android 能否解决下安卓看TikTok的问题。

开发出类似iOS端 小火箭、圈X中的功能。

**Comment by Kr328** [comment]
受到上游和 Android 本身限制

不能

**Comment by LM-Firefly** [comment]
@seoho8908 直接装第三方app就可以了呀 https://play.google.com/store/apps/details?id=com.sunshine.makilite 这个就可以
