### ISSUE TITLE
[BUG] 启动失败

### ISSUE THREAD

**Issue by LX-huaiyin** [Kr328/ClashForAndroid#814]
请简洁的描述你遇到的错误
点击启动按钮后，屏幕一闪就又恢复原样，并出现连接失败弹窗，点击详情显示“cursor window allocation of 2048 kb failed”
安装后第一次能正常使用，再次打开时就无法启动，尝试了2.1.4到2.1.6三个版本，都是这样

复现步骤:
1. 打开软件
2. 点击启动按钮

清晰简单的描述你预期的应用应该表现的行为
启动按钮变色并显示“运行中”，网络连接至国外节点

如果适用, 上传屏幕截图以帮助描述错误
![2a7e59278ca199a8](https://user-images.githubusercontent.com/28398462/108536759-c31f9100-7317-11eb-86de-fad687d2e0c1.jpg)
![2a7e59278ca199a8](https://user-images.githubusercontent.com/28398462/108536765-c581eb00-7317-11eb-9fe0-998c659ac61a.jpg)

 - 机型: 小米平板4Plus
 - 系统/ROM: MIUI 10.3.2
 - Android 版本 8.1.0
 - ROM版本 10.3.2.0（ODJCNXM）

 - 版本: 2.1.6
 - 安装包文件名: app-universal-release.apk
 - 应用来源: GitHub

**Comment by LX-huaiyin** [comment]
![Uploading 3a09f019620115b2.jpg…]()
传错了一张图片

**Comment by LX-huaiyin** [comment]
![3a09f019620115b2](https://user-images.githubusercontent.com/28398462/108538460-c87ddb00-7319-11eb-8e4a-ac07c4f6f721.jpg)
传错了一张图片

**Comment by Kr328** [comment]
#503
