### ISSUE TITLE
[BUG]首次添加配置文件，点击开始, 日志输出一堆 dial Proxy error:XXXXXXXXi/o timeout

### ISSUE THREAD

**Issue by candiceatwb** [Kr328/ClashForAndroid#816]
我使用的app不是最新版本，首次添加配置文件，开始使用vpn，进入proxy页面，点击测速没任何反应,日志提示一大堆dial Proxy error:XXXXXXXXi/o timeout 错误；强制从后台退出app,再重新打开，再链接vpn, 进入proxy页面，测速，每个节点有对应的延迟；这个问题只在第一次添加配置文件会遇到，想知道这个问题的解决方案？

复现步骤:
app版本是1.3.3
操作步骤:
1.单击配置并添加URL
2.点击保存
3.点击开始,vpn显示链接成功
4.进入proxy，测速，没有任何反应，查看日志输出一大堆 dial Proxy error:XXXXXXXXi/o timeout 错误；
5.从后台强制退出app
6.再启动app,点击开始， vpn显示链接成功
7.进入proxy，测速，每个节点有对应的延迟；
8.重复以上操作几次，发现这个问题在第一次添加配置文件是必现的

**预期行为**
首次添加配置文件，应该正常工作

**设备信息 (请完成以下信息):**
 - 机型: Redmi Note 8
 - 系统/ROM: MIUI 11
 - Android 9

**应用信息**
 - 版本: 1.3.3
 - 应用来源: ClashForAndroid

**Comment by Kr328** [comment]
不是最新版本这里不提供任何支持
