### ISSUE TITLE
[Feature Request] 希望能在安卓的shortcut中添加开关按钮和切换配置文件的按钮，方便用tasker之类的app进行自动化的操作

### ISSUE THREAD

**Issue by tigerchen1998** [Kr328/ClashForAndroid#817]
**功能描述**
在安卓的shortcut中增加开关按钮和切换配置文件的按钮

**描述你希望的实现方式**
长按桌面图标的shortcut中增加开关按钮和切换配置文件的按钮

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
#326

**Comment by Roiyaru** [comment]
@Kr328 咕咕咕

**Comment by zyc63959** [comment]
用Tasker就行，无需root
