### ISSUE TITLE
[BUG] APP代理开启异常，无法启用或查看代理

### ISSUE THREAD

**Issue by yangwang2001** [Kr328/ClashForAndroid#828]
**描述出现的错误**
如截图，磁铁和通知显示代理已启用，实际未启用，进入点击启用无效，点击进入配置列表无法查看。

**如何复现该错误**
复现步骤:（概率性）
从磁贴直接启用代理发生异常概率最大，长时间后台代理之后也可能发生异常，有时进入APP启用代理也会异常。
**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
![image](https://user-images.githubusercontent.com/56078461/109393569-80843700-795d-11eb-9063-965c71278df8.png)
![image](https://user-images.githubusercontent.com/56078461/109393575-8a0d9f00-795d-11eb-8d3c-7e86cc86f4bc.png)
![image](https://user-images.githubusercontent.com/56078461/109393578-8d088f80-795d-11eb-9280-c148e0e9e6c6.png)

**设备信息 (请完成以下信息):**
 - 机型: [荣耀v20]
 - 系统/ROM: [EMUI 11]
 - Android 版本 [10]
 - ROM版本 [11.0.0.130]

**应用信息**
 - 版本: [2.1.5]
 - 安装包文件名: [app-release-arm64-v8a.apk]
 - 应用来源: [github release]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
太长超出限制，已上传附件

[新建文本文档.txt](https://github.com/Kr328/ClashForAndroid/files/6054943/default.txt)
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by siuze** [comment]
我也有此问题，是这个版本的bug，比较早期（并不支持新版clash配置写法）的版本并没有此问题，不知道何时能修复

**Comment by Kr328** [comment]
传日志 请 

最好是 adb logcat
