### ISSUE TITLE
能否增加小飞机的单测功能啊？

### ISSUE THREAD

**Issue by zehong1995** [Kr328/ClashForAndroid#83]
现在clash只支持全局测速，不支持单节点测试，可否在running后增加已选节点测试功能，也方便看是否节点挂了

**Comment by Kr328** [comment]
@zehong1995 按照现在 Clash 的设计 
不能

**Comment by alex4ord** [comment]
https://clash.gitbook.io/doc/restful-api/proxies

clash有这个功能啊

Kr328 <notifications@github.com> 于 2020年1月18日周六 14:37写道：

**Comment by Kr328** [comment]
你考虑过 provider 怎么办吗
建议完整阅读 provider 的 处理
