### ISSUE TITLE
[BUG] VMESS断流

### ISSUE THREAD

**Issue by 22hello** [Kr328/ClashForAndroid#830]
**描述出现的错误**
用VMESS的话下载东西和看youtube视频会出现断流
trojan无问题

**如何复现该错误**
复现步骤:
使用VMESS协议下载或观看视频

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
能正常观看视屏和下载
**设备信息 (请完成以下信息):**
 - 机型: [小米8UD]
 - 系统/ROM: [例如: MIUI 12]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 12.0.4]

**应用信息**
 - 版本: [例如: 2.1.6]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: GITHUB]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**

 

> **日志
[UDP] 172.31.255.253:37866 --> r4---sn-i3belnlz.gvt1.com match Match() using Anrun | Liwei Group[🇭🇰中国香港HE06S2-广港IEPL]
[TCP] 172.31.255.253:44040 --> play.googleapis.com match DomainKeyword(google) using Anrun | Liwei Group[🇭🇰中国香港HE06S2-广港IEPL]
[UDP] 172.31.255.253:44406 --> android.clients.google.com match DomainKeyword(google) using Anrun | Liwei Group[🇭🇰中国香港HE06S2-广港IEPL]

**Comment by Kr328** [comment]
反馈上游
