### ISSUE TITLE
[Feature Request] 希望能够merge一下新的Clash Core

### ISSUE THREAD

**Issue by EricKY26** [Kr328/ClashForAndroid#832]
**功能描述**
希望出个新版本能够merge一下新的Clash Core

**Comment by v20coeur** [comment]
The "Round Robin" and "Lazy" options in Proxy Group are great upgrades, it seems the actual release is based on the v1.1.0 core.

**Comment by XinSSS** [comment]
要是可以自己下载最新的内核使用就好了, 不用麻烦作者每次更新apk这样...

**Comment by XinSSS** [comment]
还有那个geoip的数据库文件, 要是同样的能够自己更新使用本地文件就很强了

**Comment by elvisw** [comment]
许多人都提过，作者说没有时间，更新随缘
https://github.com/Kr328/ClashForAndroid/issues/730

**Comment by ha-ku** [comment]
@Kr328 core需要更新，vmess的MD5认证机制已经开始淘汰，上游core已经支持AEAD了
