### ISSUE TITLE
[BUG] 新建url配置提示 io: read/write on closed pipe

### ISSUE THREAD

**Issue by czh6888** [Kr328/ClashForAndroid#833]
新建文件配置蓝屏之后卡死
新建url配置提示 io: read/write on closed pipe

**设备信息 (请完成以下信息):**
 - 机型: 斐讯T1
 - 系统/ROM:T1 YYF 
 - Android 版本 android TV 7.1 
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: 2.1.5 2.1.4
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Github
![IMG_9887](https://user-images.githubusercontent.com/22154777/110056719-46ba9280-7d9a-11eb-900c-301d0ebe2df1.jpg)

**Comment by Kr328** [comment]
检查网络
