### ISSUE TITLE
[Feature Request] 请求添加类似于SSR的前置代理功能

### ISSUE THREAD

**Issue by DBinK** [Kr328/ClashForAndroid#837]
**功能描述**
SSR的前置代理，可以使用http、socks5协议
（为什么不用SSR？年久失修bug太多了稳定性太差）

目前遇到了在Android上套双层代理的需求，实现方式是在Android上，用多用户的功能（我在用island创建的工作资料），可以在其它用户开启一个用VPN通道的代理软件后，在主用户用 http 127.0.0.1:[端口] 连接上它。（只要是用户不同下的app，Android 可以开很多个VPN通道不会相互占用）

**附加信息**

**Comment by Kr328** [comment]
上游 relay 请
