### ISSUE TITLE
[BUG] OPPO 安装不了apk

### ISSUE THREAD

**Issue by xiaocuic** [Kr328/ClashForAndroid#838]
下载了apk后显示apk异常安装不了
**屏幕截图**
![Screenshot_2021-03-07-15-11-15-17](https://user-images.githubusercontent.com/80192397/110233182-40284880-7f5d-11eb-9a5b-193a5434750d.png)

**设备信息 :**
 - 机型:  oppo A57
 - Android 版本  6.0.1

**应用信息**
 - 版本: [2.1.6]
 - 安装包文件名: clash_for_android.apk
 - 应用来源: 在人间用户面板

**Comment by xiaocuic** [comment]
有大佬能教教我吗？求解！(ಥ_ಥ)

**Comment by Kr328** [comment]
不在 Release 下的自己想办法
