### ISSUE TITLE
[Feature Request] 保存Proxy-groups个人设置

### ISSUE THREAD

**Issue by w3AD4y-r5** [Kr328/ClashForAndroid#839]
**目前行为**
在clash gui将某个proxy group指定到某个proxy（如代理组Spotify 指定为使用代理USA-8），手动开关代理（耗时1秒，Clash保持前台），发现代理组Spotify 又在使用供应商提供的proxy列表的第一位默认值（HK-1）
**功能描述**
手动开关代理后，proxy group使用的proxy保持为自定义值（USA-8）
**附加信息**
正在使用Google play 2.1.5-arm64-v8a
**与Feature Request无关的问题**
想问下Google play下个版本什么时候更新

**Comment by Kr328** [comment]
理论上现有版本都会保存 Proxy Group 无法保存的话尝试清除数据 如 果还不行 就按照 BUG 的模板填写 Issue
