### ISSUE TITLE
[Feature Request] 请求恢复PROXY界面的测速按钮，方便用于电视

### ISSUE THREAD

**Issue by QX-crypto** [Kr328/ClashForAndroid#841]
**功能描述**
老版本的闪电测速按钮

**描述你希望的实现方式**
与老版本相同，或者能在进入PROXY界面默认启动测速就更好了，因电视无触摸屏无法下拉测速

**附加信息**
感谢开发者，自由无疆。

**Comment by Zhuager** [comment]
双击代理页面的标签就可以测速

**Comment by Kr328** [comment]
#803
