### ISSUE TITLE
[Feature Request] 希望export TunService

### ISSUE THREAD

**Issue by ha-ku** [Kr328/ClashForAndroid#843]
**功能描述**
请清晰的描述你想要的功能
希望export TunService来实现通过tasker来开关VPN和添加桌面小部件等功能。

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
就个人浅薄的了解，在AndroidManifest.xml中将com.github.kr328.clash.service.TunService的android:exported改为true即可。个人对安卓开发了解得很少，不确定是否还需要额外的改动。

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
不做 

应用本身逻辑只保证自己处理 TunService 不想额外保证对外部调用的支持

**Comment by ha-ku** [comment]
> 不做
> 
> 应用本身逻辑只保证自己处理 TunService 不想额外保证对外部调用的支持

这个request并不是希望有任何额外的功能、支持或可用性保证，只是希望app不要在设置上阻碍屏蔽外部调用，使有需要的用户可以自行尝试。在app屏蔽直接start service的情况下，有需要的用户只能被迫去用模拟点击，这个request只是希望可能的情况下不要徒增如此不必要的麻烦。

**Comment by Kr328** [comment]
@ha-ku 但是这样做之后应用会出现奇奇怪怪的行为

这些奇奇怪怪的行为会给问题排查带来困扰 就是不希望被这些噪音影响到真正的问题排查

未来会有外部 API 来提供自动化功能

**Comment by ha-ku** [comment]
> @ha-ku 但是这样做之后应用会出现奇奇怪怪的行为
> 
> 这些奇奇怪怪的行为会给问题排查带来困扰 就是不希望被这些噪音影响到真正的问题排查
> 
> 未来会有外部 API 来提供自动化功能

有完整的外部API当然更好，希望可以尽快实现
