### ISSUE TITLE
[BUG] 全局模式连不了网

### ISSUE THREAD

**Issue by damengzhu** [Kr328/ClashForAndroid#846]
**描述出现的错误**
请简洁的描述你遇到的错误
设置全局模式，只能访问国内网站，访问国外网站连不了网

**如何复现该错误**
复现步骤:
1. ...覆写里设置全局模式
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
# Logcat on 2021-03-17 13:48:40
13:48:44 |Info| Android tun started
13:48:44 |Info| Listen TCP redirect 42329
13:48:44 |Info| Start initial compatible provider AsianTV
13:48:44 |Info| Start initial compatible provider GlobalTV
```
# Logcat on 2021-03-17 16:14:26
16:14:30 |Info| Android tun started
16:14:30 |Info| Listen TCP redirect 37154
16:14:30 |Info| Start initial compatible provider Proxy
16:14:30 |Info| Start initial compatible provider Domestic
16:14:30 |Info| Start initial compatible provider GlobalTV
16:14:30 |Info| Start initial compatible provider AsianTV
16:14:30 |Info| Start initial compatible provider Others
16:14:30 |Info| [DNS] Main 223.5.5.5:53
16:14:30 |Info| [DNS] Main 119.29.29.29:53
16:14:30 |Info| [DNS] Main 8.8.8.8:53
16:14:30 |Info| [DNS] Main 1.1.1.1:53
16:14:30 |Info| [DNS] Fallback https://dns.google/dns-query
16:14:30 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
16:14:30 |Info| [DNS] Fallback https://doh.pub/dns-query
16:14:30 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
16:14:30 |Warning| Failed to start Redir UDP Listener: operation not permitted
16:14:30 |Info| HTTP proxy listening at: :7890
16:14:30 |Info| SOCKS proxy listening at: :7891
16:14:30 |Info| Redir proxy listening at: :7892
16:14:30 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/1.yaml loaded
16:14:30 |Info| Set Proxy -> VIP节点-香港D
16:14:30 |Info| Start initial compatible provider Others
16:14:30 |Info| Start initial compatible provider GlobalTV
16:14:30 |Info| Start initial compatible provider AsianTV
16:14:30 |Info| Start initial compatible provider Proxy
16:14:30 |Info| Start initial compatible provider Domestic
16:14:30 |Info| [DNS] Main 223.5.5.5:53
16:14:30 |Info| [DNS] Main 119.29.29.29:53
16:14:30 |Info| [DNS] Main 8.8.8.8:53
16:14:30 |Info| [DNS] Main 1.1.1.1:53
16:14:30 |Info| [DNS] Main 192.168.2.1:53
16:14:30 |Info| [DNS] Fallback https://dns.google/dns-query
16:14:30 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
16:14:30 |Info| [DNS] Fallback https://doh.pub/dns-query
16:14:30 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
16:14:30 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/1.yaml loaded
16:14:30 |Info| Set Proxy -> VIP节点-香港D
16:14:30 |Info| [TCP] 172.31.255.253:46612 --> 118.26.252.225 using GLOBAL
16:14:30 |Debug| [DNS] response msg empty: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0xf1c2, Response:true, Opcode:0, Authoritative:true, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:3}, Compress:false, Question:[]dns.Question{dns.Question{Name:"253.255.31.172.in-addr.arpa.", Qtype:0xc, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)}
16:14:30 |Info| [TCP] 172.31.255.253:47756 --> aeventlog.beacon.qq.com using GLOBAL
16:14:31 |Warning| TCP Redirect receive error: accept tcp4 0.0.0.0:37154: use of closed network connection
16:14:31 |Info| TCP redirect exited
16:14:31 |Info| Android tun stopped
16:14:31 |Info| Packet redirect exited
16:14:31 |Info| Android tun started
16:14:31 |Info| Listen TCP redirect 39587
16:14:31 |Info| Start initial compatible provider Proxy
16:14:31 |Info| Start initial compatible provider Domestic
16:14:31 |Info| Start initial compatible provider GlobalTV
16:14:31 |Info| Start initial compatible provider AsianTV
16:14:31 |Info| Start initial compatible provider Others
16:14:31 |Info| [DNS] Main 223.5.5.5:53
16:14:31 |Info| [DNS] Main 119.29.29.29:53
16:14:31 |Info| [DNS] Main 8.8.8.8:53
16:14:31 |Info| [DNS] Main 1.1.1.1:53
16:14:31 |Info| [DNS] Fallback https://dns.google/dns-query
16:14:31 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
16:14:31 |Info| [DNS] Fallback https://doh.pub/dns-query
16:14:31 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
16:14:31 |Info| HTTP proxy listening at: :7890
16:14:31 |Info| SOCKS proxy listening at: :7891
16:14:31 |Warning| Failed to start Redir UDP Listener: operation not permitted
16:14:31 |Info| Redir proxy listening at: :7892
16:14:31 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/1.yaml loaded
16:14:31 |Info| Set Proxy -> VIP节点-香港D
16:14:32 |Info| [UDP] 172.31.255.253:19096 --> 112.60.1.241 using GLOBAL
16:14:32 |Info| Start initial compatible provider GlobalTV
16:14:32 |Info| Start initial compatible provider AsianTV
16:14:32 |Info| Start initial compatible provider Proxy
16:14:32 |Info| Start initial compatible provider Domestic
16:14:32 |Info| Start initial compatible provider Others
16:14:32 |Info| [DNS] Main 223.5.5.5:53
16:14:32 |Info| [DNS] Main 119.29.29.29:53
16:14:32 |Info| [DNS] Main 8.8.8.8:53
16:14:32 |Info| [DNS] Main 1.1.1.1:53
16:14:32 |Info| [DNS] Main 192.168.2.1:53
16:14:32 |Info| [DNS] Fallback https://dns.google/dns-query
16:14:32 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
16:14:32 |Info| [DNS] Fallback https://doh.pub/dns-query
16:14:32 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
16:14:32 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/1.yaml loaded
16:14:32 |Info| Set Proxy -> VIP节点-香港D
16:14:32 |Info| [TCP] 172.31.255.253:37374 --> 109.244.23.190 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43072 --> 111.13.141.202 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43595 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43603 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43066 --> 111.13.141.202 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43605 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43080 --> 111.13.141.202 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43601 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:46656 --> 118.26.252.225 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43096 --> 111.13.141.202 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43583 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:37389 --> 111.30.169.50 using GLOBAL
16:14:33 |Info| [TCP] 172.31.255.253:49177 --> data.mistat.xiaomi.com using GLOBAL
16:14:33 |Info| [TCP] 172.31.255.253:45429 --> pdc.micloud.xiaomi.net using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:43005 --> cnac.account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:43009 --> cnac.account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:48681 --> data.mistat.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:49299 --> account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:49303 --> account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:49307 --> account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:43171 --> api.micloud.xiaomi.net using GLOBAL
16:14:34 |Info| [UDP] 172.31.255.253:1863 --> 221.181.80.158 using GLOBAL
16:14:35 |Info| [TCP] 172.31.255.253:43175 --> api.micloud.xiaomi.net using GLOBAL
16:14:35 |Info| [TCP] 172.31.255.253:43179 --> api.micloud.xiaomi.net using GLOBAL
16:14:35 |Info| [TCP] 172.31.255.253:45483 --> phonecallapi.micloud.xiaomi.net using GLOBAL
16:14:35 |Info| [TCP] 172.31.255.253:45489 --> smsapi.micloud.xiaomi.net using GLOBAL
16:14:36 |Info| [TCP] 172.31.255.253:45493 --> smsapi.micloud.xiaomi.net using GLOBAL
16:14:36 |Info| [TCP] 172.31.255.253:45497 --> smsapi.micloud.xiaomi.net using GLOBAL
16:14:36 |Info| [TCP] 172.31.255.253:42141 --> beacon-api.aliyuncs.com using GLOBAL
16:14:36 |Info| [TCP] 172.31.255.253:40821 --> adash.man.aliyuncs.com using GLOBAL
16:14:37 |Info| [TCP] 172.31.255.253:48745 --> data.mistat.xiaomi.com using GLOBAL
16:14:37 |Warning| dial GLOBAL error: dial tcp4 198.18.0.1:853: i/o timeout
16:14:37 |Warning| dial GLOBAL error: dial tcp4 114.114.114.114:853: i/o timeout
16:14:39 |Warning| dial GLOBAL error: dial tcp4 172.217.160.106:443: i/o timeout
16:14:43 |Warning| dial GLOBAL error: dial tcp4 108.160.170.39:443: i/o timeout
16:14:43 |Info| [TCP] 172.31.255.253:42701 --> www.google.com using GLOBAL
16:14:45 |Info| [TCP] 172.31.255.253:48765 --> data.mistat.xiaomi.com using GLOBAL
16:14:46 |Warning| dial GLOBAL error: dial tcp4 69.171.235.64:443: i/o timeout
16:14:51 |Warning| dial GLOBAL error: dial tcp4 69.171.235.64:443: i/o timeout
16:14:57 |Info| [TCP] 172.31.255.253:41218 --> 183.192.164.178 using GLOBAL
16:15:06 |Info| [TCP] 172.31.255.253:44476 --> 36.155.202.15 using GLOBAL
16:15:06 |Info| [TCP] 172.31.255.253:44480 --> 36.155.202.15 using GLOBAL
16:15:07 |Info| [TCP] 172.31.255.253:45553 --> smsapi.micloud.xiaomi.net using GLOBAL
16:15:07 |Info| [TCP] 172.31.255.253:45557 --> smsapi.micloud.xiaomi.net using GLOBAL
16:15:07 |Info| [TCP] 172.31.255.253:45561 --> smsapi.micloud.xiaomi.net using GLOBAL

**Comment by Kr328** [comment]
贴日志请

**Comment by damengzhu** [comment]
> 贴日志请

# Logcat on 2021-03-17 13:39:51

**Comment by damengzhu** [comment]
> 贴日志请

没显示日志

**Comment by Kr328** [comment]
打开日志捕捉开关

启动开关

尝试复现问题

关掉日志开关

复制日志内容

粘贴在网页上

提交

**Comment by damengzhu** [comment]
> ：日志捕捉开关
> 
> 启动开关
> 
> 尝试复现问题
> 
> 关掉日志开关
> 
> 复制日志内容
> 
> 张贴在网页上
> 
> 提交
# Logcat on 2021-03-17 13:48:40
13:48:44 |Info| Android tun started
13:48:44 |Info| Listen TCP redirect 42329
13:48:44 |Info| Start initial compatible provider AsianTV
13:48:44 |Info| Start initial compatible provider GlobalTV

**Comment by damengzhu** [comment]
> ：日志捕捉开关
> 
> 启动开关
> 
> 尝试复现问题
> 
> 关掉日志开关
> 
> 复制日志内容
> 
> 张贴在网页上
> 
> 提交

# Logcat on 2021-03-17 16:14:26
16:14:30 |Info| Android tun started
16:14:30 |Info| Listen TCP redirect 37154
16:14:30 |Info| Start initial compatible provider Proxy
16:14:30 |Info| Start initial compatible provider Domestic
16:14:30 |Info| Start initial compatible provider GlobalTV
16:14:30 |Info| Start initial compatible provider AsianTV
16:14:30 |Info| Start initial compatible provider Others
16:14:30 |Info| [DNS] Main 223.5.5.5:53
16:14:30 |Info| [DNS] Main 119.29.29.29:53
16:14:30 |Info| [DNS] Main 8.8.8.8:53
16:14:30 |Info| [DNS] Main 1.1.1.1:53
16:14:30 |Info| [DNS] Fallback https://dns.google/dns-query
16:14:30 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
16:14:30 |Info| [DNS] Fallback https://doh.pub/dns-query
16:14:30 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
16:14:30 |Warning| Failed to start Redir UDP Listener: operation not permitted
16:14:30 |Info| HTTP proxy listening at: :7890
16:14:30 |Info| SOCKS proxy listening at: :7891
16:14:30 |Info| Redir proxy listening at: :7892
16:14:30 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/1.yaml loaded
16:14:30 |Info| Set Proxy -> VIP节点-香港D
16:14:30 |Info| Start initial compatible provider Others
16:14:30 |Info| Start initial compatible provider GlobalTV
16:14:30 |Info| Start initial compatible provider AsianTV
16:14:30 |Info| Start initial compatible provider Proxy
16:14:30 |Info| Start initial compatible provider Domestic
16:14:30 |Info| [DNS] Main 223.5.5.5:53
16:14:30 |Info| [DNS] Main 119.29.29.29:53
16:14:30 |Info| [DNS] Main 8.8.8.8:53
16:14:30 |Info| [DNS] Main 1.1.1.1:53
16:14:30 |Info| [DNS] Main 192.168.2.1:53
16:14:30 |Info| [DNS] Fallback https://dns.google/dns-query
16:14:30 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
16:14:30 |Info| [DNS] Fallback https://doh.pub/dns-query
16:14:30 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
16:14:30 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/1.yaml loaded
16:14:30 |Info| Set Proxy -> VIP节点-香港D
16:14:30 |Info| [TCP] 172.31.255.253:46612 --> 118.26.252.225 using GLOBAL
16:14:30 |Debug| [DNS] response msg empty: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0xf1c2, Response:true, Opcode:0, Authoritative:true, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:3}, Compress:false, Question:[]dns.Question{dns.Question{Name:"253.255.31.172.in-addr.arpa.", Qtype:0xc, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)}
16:14:30 |Info| [TCP] 172.31.255.253:47756 --> aeventlog.beacon.qq.com using GLOBAL
16:14:31 |Warning| TCP Redirect receive error: accept tcp4 0.0.0.0:37154: use of closed network connection
16:14:31 |Info| TCP redirect exited
16:14:31 |Info| Android tun stopped
16:14:31 |Info| Packet redirect exited
16:14:31 |Info| Android tun started
16:14:31 |Info| Listen TCP redirect 39587
16:14:31 |Info| Start initial compatible provider Proxy
16:14:31 |Info| Start initial compatible provider Domestic
16:14:31 |Info| Start initial compatible provider GlobalTV
16:14:31 |Info| Start initial compatible provider AsianTV
16:14:31 |Info| Start initial compatible provider Others
16:14:31 |Info| [DNS] Main 223.5.5.5:53
16:14:31 |Info| [DNS] Main 119.29.29.29:53
16:14:31 |Info| [DNS] Main 8.8.8.8:53
16:14:31 |Info| [DNS] Main 1.1.1.1:53
16:14:31 |Info| [DNS] Fallback https://dns.google/dns-query
16:14:31 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
16:14:31 |Info| [DNS] Fallback https://doh.pub/dns-query
16:14:31 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
16:14:31 |Info| HTTP proxy listening at: :7890
16:14:31 |Info| SOCKS proxy listening at: :7891
16:14:31 |Warning| Failed to start Redir UDP Listener: operation not permitted
16:14:31 |Info| Redir proxy listening at: :7892
16:14:31 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/1.yaml loaded
16:14:31 |Info| Set Proxy -> VIP节点-香港D
16:14:32 |Info| [UDP] 172.31.255.253:19096 --> 112.60.1.241 using GLOBAL
16:14:32 |Info| Start initial compatible provider GlobalTV
16:14:32 |Info| Start initial compatible provider AsianTV
16:14:32 |Info| Start initial compatible provider Proxy
16:14:32 |Info| Start initial compatible provider Domestic
16:14:32 |Info| Start initial compatible provider Others
16:14:32 |Info| [DNS] Main 223.5.5.5:53
16:14:32 |Info| [DNS] Main 119.29.29.29:53
16:14:32 |Info| [DNS] Main 8.8.8.8:53
16:14:32 |Info| [DNS] Main 1.1.1.1:53
16:14:32 |Info| [DNS] Main 192.168.2.1:53
16:14:32 |Info| [DNS] Fallback https://dns.google/dns-query
16:14:32 |Info| [DNS] Fallback https://cloudflare-dns.com/dns-query
16:14:32 |Info| [DNS] Fallback https://doh.pub/dns-query
16:14:32 |Info| [DNS] Fallback https://dns.alidns.com/dns-query
16:14:32 |Info| Profile /data/user/0/com.github.kr328.clash/files/profiles/1.yaml loaded
16:14:32 |Info| Set Proxy -> VIP节点-香港D
16:14:32 |Info| [TCP] 172.31.255.253:37374 --> 109.244.23.190 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43072 --> 111.13.141.202 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43595 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43603 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43066 --> 111.13.141.202 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43605 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43080 --> 111.13.141.202 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43601 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:46656 --> 118.26.252.225 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43096 --> 111.13.141.202 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:43583 --> 39.156.82.240 using GLOBAL
16:14:32 |Info| [TCP] 172.31.255.253:37389 --> 111.30.169.50 using GLOBAL
16:14:33 |Info| [TCP] 172.31.255.253:49177 --> data.mistat.xiaomi.com using GLOBAL
16:14:33 |Info| [TCP] 172.31.255.253:45429 --> pdc.micloud.xiaomi.net using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:43005 --> cnac.account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:43009 --> cnac.account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:48681 --> data.mistat.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:49299 --> account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:49303 --> account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:49307 --> account.xiaomi.com using GLOBAL
16:14:34 |Info| [TCP] 172.31.255.253:43171 --> api.micloud.xiaomi.net using GLOBAL
16:14:34 |Info| [UDP] 172.31.255.253:1863 --> 221.181.80.158 using GLOBAL
16:14:35 |Info| [TCP] 172.31.255.253:43175 --> api.micloud.xiaomi.net using GLOBAL
16:14:35 |Info| [TCP] 172.31.255.253:43179 --> api.micloud.xiaomi.net using GLOBAL
16:14:35 |Info| [TCP] 172.31.255.253:45483 --> phonecallapi.micloud.xiaomi.net using GLOBAL
16:14:35 |Info| [TCP] 172.31.255.253:45489 --> smsapi.micloud.xiaomi.net using GLOBAL
16:14:36 |Info| [TCP] 172.31.255.253:45493 --> smsapi.micloud.xiaomi.net using GLOBAL
16:14:36 |Info| [TCP] 172.31.255.253:45497 --> smsapi.micloud.xiaomi.net using GLOBAL
16:14:36 |Info| [TCP] 172.31.255.253:42141 --> beacon-api.aliyuncs.com using GLOBAL
16:14:36 |Info| [TCP] 172.31.255.253:40821 --> adash.man.aliyuncs.com using GLOBAL
16:14:37 |Info| [TCP] 172.31.255.253:48745 --> data.mistat.xiaomi.com using GLOBAL
16:14:37 |Warning| dial GLOBAL error: dial tcp4 198.18.0.1:853: i/o timeout
16:14:37 |Warning| dial GLOBAL error: dial tcp4 114.114.114.114:853: i/o timeout
16:14:39 |Warning| dial GLOBAL error: dial tcp4 172.217.160.106:443: i/o timeout
16:14:43 |Warning| dial GLOBAL error: dial tcp4 108.160.170.39:443: i/o timeout
16:14:43 |Info| [TCP] 172.31.255.253:42701 --> www.google.com using GLOBAL
16:14:45 |Info| [TCP] 172.31.255.253:48765 --> data.mistat.xiaomi.com using GLOBAL
16:14:46 |Warning| dial GLOBAL error: dial tcp4 69.171.235.64:443: i/o timeout
16:14:51 |Warning| dial GLOBAL error: dial tcp4 69.171.235.64:443: i/o timeout
16:14:57 |Info| [TCP] 172.31.255.253:41218 --> 183.192.164.178 using GLOBAL
16:15:06 |Info| [TCP] 172.31.255.253:44476 --> 36.155.202.15 using GLOBAL
16:15:06 |Info| [TCP] 172.31.255.253:44480 --> 36.155.202.15 using GLOBAL
16:15:07 |Info| [TCP] 172.31.255.253:45553 --> smsapi.micloud.xiaomi.net using GLOBAL
16:15:07 |Info| [TCP] 172.31.255.253:45557 --> smsapi.micloud.xiaomi.net using GLOBAL
16:15:07 |Info| [TCP] 172.31.255.253:45561 --> smsapi.micloud.xiaomi.net using GLOBAL

**Comment by damengzhu** [comment]
> ：日志捕捉开关
> 
> 启动开关
> 
> 尝试复现问题
> 
> 关掉日志开关
> 
> 复制日志内容
> 
> 张贴在网页上
> 
> 提交

解决了，要在GLOBAL选择节点才可以，在PROXY选择节点不行😓
