### ISSUE TITLE
[Feature Request] 请大佬能不能添加SSR的订阅支持，我们很需要。

### ISSUE THREAD

**Issue by co11ector** [Kr328/ClashForAndroid#848]
**功能描述**
请清晰的描述你想要的功能
请大佬能不能添加SSR的订阅支持，我们很需要。
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
请大佬能不能添加SSR的订阅支持，我们很需要。
**附加信息**
其他的与改功能相关的附加信息
请大佬能不能添加SSR的订阅支持，我们很需要。

**Comment by Roiyaru** [comment]
@co11ector 请去上游反馈

**Comment by EKyero** [comment]
@co11ector https://github.com/Kr328/ClashForAndroid/issues/295#issuecomment-616258969

**Comment by becausemadoka** [comment]
尝试使用订阅转换（我猜可以

**Comment by Kr328** [comment]
不做

应用只做和 clash 本身有关的事 订阅转换参见 [subconverter}(https://github.com/tindy2013/subconverter)
