### ISSUE TITLE
[Feature Request] 希望增加切换模式的快捷方式

### ISSUE THREAD

**Issue by HOMHOG** [Kr328/ClashForAndroid#851]
**功能描述**
请清晰的描述你想要的功能
希望在首页增加切换全局和规则模式的快捷按钮，每次都去改复写有点麻烦
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
#831
