### ISSUE TITLE
[Feature Request] update the app to the new cores and features

### ISSUE THREAD

**Issue by fsheidaiee** [Kr328/ClashForAndroid#862]
**Is your feature request related to a problem? Please describe.**
there is no update in a long time on the app and there are many bugs in the current app please update the app.

**Describe the solution you'd like**
updating core and features.

**Describe alternatives you've considered**
using v2rayng
**Additional context**
nothing

**Comment by luoxiao-xy** [comment]
一年没更新了，希望作者大大更新一版，适配新android版本，合并一下新核心。重点解决一下已知bug。
要求不多，一年更新一版就可以！

**Comment by akw5454521** [comment]
> 一年没更新了，希望作者大大更新一版，适配新android版本，合并一下新核心。重点解决一下已知bug。
> 要求不多，一年更新一版就可以！ @Kr328

Kr328 released this on 4 Sep 2020

没一年呢吧

**Comment by XinSSS** [comment]
@luoxiao-xy 感觉更新不要抱期望了, ssr可以使用HMBSbige的ssr修改版加上ACL4SSR的规则文件

**Comment by elvisw** [comment]
https://github.com/Kr328/ClashForAndroid/issues/730

**Comment by Shangbaize-Daoye** [comment]
太可惜了，最近新的clash core开始支持vmess AEAD了，想在安卓上也用上新功能，但现在看来无望了。安卓还是得换客户端了

**Comment by DockerCS** [comment]
> 一年没更新了，希望作者大大更新一版，适配新android版本，合并一下新核心。重点解决一下已知bug。
> 
> 要求不多，一年更新一版就可以！ @Kr328 

不出意外，明天更新（明天是指2021年4月9号）

**Comment by xuhaoyang** [comment]
@Shangbaize-Daoye 想换就换，还说出来，想得到谁的关注？小孩子吗

**Comment by Shangbaize-Daoye** [comment]
> @Shangbaize-Daoye 想换就换，还说出来，想得到谁的关注？小孩子吗

？表示惋惜，也喷？换，也是别人自由。你，很成熟？

**Comment by xuhaoyang** [comment]
@Shangbaize-Daoye ？表惋惜，也说？说，你幼儿园也是别人自由。你，很厉害？指导人生？

**Comment by Shangbaize-Daoye** [comment]
> @Shangbaize-Daoye ？表惋惜，也说？说，你幼儿园也是别人自由。你，很厉害？指导人生？

@xuhaoyang 有病？

**Comment by xuhaoyang** [comment]
@Shangbaize-Daoye 你承认你有病？
