### ISSUE TITLE
[BUG] 从2.0.16升级到最新版后，DNS模式疑似卡在了redir-host模式

### ISSUE THREAD

**Issue by akw5454521** [Kr328/ClashForAndroid#867]
**描述出现的错误**
之前一直用的2.0.16版本，虽然有点老但也足够用了，也没想过升到2.1.x系列。后来突然遇到了耗电增加问题，于是升到了2.1.6版看看有没有什么变化(后来找到了耗电增加原因，跟CFA无关，不过纵向对比好像新版是比2.0.16耗电多点，跑题了不多说了)。在使用过程中，通过观察日志，发现似乎DNS模式有些问题：
我把配置贴在了下边，日志是debug，dns是false，之前用2.0.16版一直是这个配置，平时日志输出的情况是：对于域名匹配的规则，直接一条[info]，根据匹配的规则走代理或走direct。对于域名没匹配的，先出一条[debug]的日志，为DNS解析的结果，之后紧跟一条[info]，根据ip位置走Match规则或走direct。这个跟我对DNS关闭功能理解是一致的
但是在新版里，没有DNS解析这类的debug日志了，对于域名没匹配的，直接是一条[info]，走Match规则或走direct(GeoIP(CN))。日志确实还是debug级别，因为会输出其他类型的debug日志，比如不支持UDP这类
覆写选项那里，全都选的是"根据配置文件"，DNS一项，"根据配置文件"和内置(false)全都试过，但日志结果都是一样的
之前在用2.0.16版时，我曾经试过把配置文件里的DNS改为true，想看看日志输出啥样(因为听说redir-host模式无论如何都会解析DNS)，结果在日志里看不到任何DNS解析(跟我现在遇到的情况一样)，估计是上游的设置(因为太频繁了怕溢出，纯个人猜测)
因为我现在的日志输出情况和之前老版开启DNS redir-host模式的情况一样(没DNS解析)，所以我推测DNS卡在了redir-host这里，而没有按照配置文件的false来关闭内置DNS功能。当然这只是个人推测，如果有其他情况还请告知
另外我去看了下update notice，发现2.0.17版本更新事项是"use redir-host as default dns enhanced-mode"，推测问题是从这里开始的，于是我删掉2.1.6版装了2.0.18版，果然复现了(都用的同一配置文件)，因此应该是从2.0.17开始的

**如何复现该错误**
复现步骤:
1. 安装2.0.17之后的版本
2. 覆写选项(如可用)选为根据配置文件
3. 打开日志观察

**预期行为**
对于域名没匹配的连接，先输出 [debug] [DNS] www.dangdang.com --> 120.133.46.42 这种

**设备信息 (请完成以下信息):**
 - 机型: Xperia 1
 - 系统/ROM: 接近原生系统
 - Android 10

**应用信息**
 - 版本: 2.0.16 / 2.1.6 / 2.0.18
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: 本仓库

**附加信息**
我在其他平台上试过了同一配置文件，内核是比CFA2.1.6版的内核更新一点的内核(1.2.0)，日志输出情况跟之前2.0.16类似，所以应该排除了1.1.0版本的内核改变了日志输出的情况

**配置文件**
port: 7890
socks-port: 7891
# redir-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
ipv6: false
external-controller: '0.0.0.0:9090'
secret: ''

dns:
  enable: false
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 1.2.4.8
    - 114.114.114.114
    - 223.5.5.5
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.0.0.1:853
    - tls://dns.google:853

proxies:
proxy-groups:
- MATCH

**日志**
日志都挺正常的，就不贴完整了，只是跟之前相比缺少了
2021-04-03 23:27:51[debug] [DNS] www.dangdang.com --> 120.133.46.42
这种

**Comment by Kr328** [comment]
应用会强制启用内置 DNS 以防止出现 DNS 流量回环

**Comment by akw5454521** [comment]
> 应用会强制启用内置 DNS 以防止出现 DNS 流量回环

明白了。那覆写设置里的false选项是不是没用呀

**Comment by Kr328** [comment]
false == 强制使用内置预设
true == 使用配置文件 DNS 配置

上面的文本应该不难读懂才对
