### ISSUE TITLE
[Feature Request] 请问如何让所有ipv6流量直连？

### ISSUE THREAD

**Issue by Student414** [Kr328/ClashForAndroid#868]
请教大佬，
目前服务器节点仅支持ipv4，手机端开启了cfa后，ipv4正常，ipv6显示ERR_NAME_NOT_RESOLVED，想要的效果是ipv4正常使用，ipv6直连即可，无需代理。还请大佬给个思路，谢谢~
目前linux上我是直接没给ipv6设置iptables规则，只给了ipv4的规则，所以可以实现这个需求，cfa上目测是所有流量都走核心了吧？
实在感谢！

**Comment by Student414** [comment]
![Screenshot_2021-04-05-20-21-45-288_com estrongs android pop](https://user-images.githubusercontent.com/14970752/113573362-94057a80-964c-11eb-8f83-f54dedbf3703.jpg)
这是目前的dns配置，开启了ipv6特性，浏览器中解析不到ipv6网站的ip。关闭cfa一切正常。

**Comment by Student414** [comment]
![IMG_20210405_203117](https://user-images.githubusercontent.com/14970752/113574060-ef843800-964d-11eb-80ff-eebc751c7389.jpg)
开启cfa，ipv6域名貌似正常解析，但是没ipv6的路由😷😷😷

**Comment by Kr328** [comment]
IPv6 没有路由 因为一旦存在 v6 路由 某些设计极差的应用会认为 v6 可用而不会尝试 v4 导致网络无连接

**Comment by xuhaoyang** [comment]
@Kr328 关闭v6
