### ISSUE TITLE
无法更新子模块 “core/src/main/golang/clash”

### ISSUE THREAD

**Issue by Joehaivo** [Kr328/ClashForAndroid#87]
> error: Server does not allow request for unadvertised object 7767f1554c6813b51e165732b85e5820b34ee9e9
> Fetched in submodule path 'core/src/main/golang/clash', but it did not contain 7767f1554c6813b51e165732b85e5820b34ee9e9. Direct fetching of that commit failed.

项目中的子模块指向clash@7767f1（tree/7767f1554c6813b51e165732b85e5820b34ee9e9），但是似乎无法更新该模块，配置文件.gitmodules中配置为url = https://github.com/Kr328/Clash，但是该分支为rm，无法更新，请问该如何解决

**Comment by Kr328** [comment]
@Joehaivo 暂时不能解决

**Comment by Kr328** [comment]
FIXED in 1.1.0
