### ISSUE TITLE
[BUG] v1.3.10版本中有关于hosts域名和规则的问题

### ISSUE THREAD

**Issue by hepingsicilia** [Kr328/ClashForAndroid#871]
**描述出现的错误**
再最新版本中，自定义hosts字段的域名并不会以域名去match自定义规则，而是通过域名对应的IP

**如何复现该错误**
复现步骤:
1. 开启Clash
2. 观察log
3. 自定义hosts的mtalk.google.com映射的108.177.125.188走了最后一条的"MATCH,MATCH"规则(即代理)

**预期行为**
在之前版本中自定义hosts中域名会遵循规则，即走DIRECT

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Galaxy S21 Ultra
 - 系统/ROM: OneUI 3.1
 - Android 版本: 11
 - ROM版本: G998NKSU2AUC8

**应用信息**
 - 版本: `v1.3.10`
 - 安装包文件名: `app-universal-release.apk`
 - 应用来源: GitHub release

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
配置为加入自己节点配置的神机规则:    
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/Outbound.yaml

**日志**
如果适用, 粘贴日志以帮助侦测错误
如果直接使用配置:
```
[TCP] 172.31.255.253:42460 --> 108.177.125.188 match Match() using MATCH[XXX]
```
在配置中最下方MATCH前面加入`  - IP-CIDR,108.177.125.188/32,DIRECT`后:
```
[TCP] 172.31.255.253:48228 --> 108.177.125.188 match IPCIDR(108.177.125.188/32) using DIRECT
```

**Comment by akw5454521** [comment]
你不是解决了吗……

**Comment by hepingsicilia** [comment]
> 你不是解决了吗……

恩，是找到了解决办法，但不是预期行为😂

**Comment by Kr328** [comment]
是预期的 

自从 https://github.com/Dreamacro/clash/commit/558ac6b96576e1c06d53219e022a5392048a99c5 以来

DNS 服务匹配到 hosts 时 
会立即返回 hosts 的内容 
并不会保存 IP -> 域名 的映射 
导致通过 tun 的流量无法推断出域名

你可以关掉 DNS 服务的 使用 hosts 或者 打开系统代理

觉得不合理的 也可以向上游反馈
