### ISSUE TITLE
[BUG] 2.3.10 打开clash观看爱奇艺和腾讯视频，发现通告栏有明显的流量下载

### ISSUE THREAD

**Issue by Faramitas** [Kr328/ClashForAndroid#872]
![Screenshot_20210409_122121_com qiyi video](https://user-images.githubusercontent.com/29322214/114128084-27c99600-992e-11eb-9d58-28c6d7b33e34.jpg)
![Screenshot_20210409_122041_com qiyi video](https://user-images.githubusercontent.com/29322214/114128087-2a2bf000-992e-11eb-9fa2-2f56bc10c43a.jpg)

看图规则指向直连，之前版本貌似直连的并不会在通知栏计算在流量中

**设备信息 (请完成以下信息):**
 - 机型: HUAWEI MATE20PRO
 - 系统/ROM: EMUI11
 - Android 版本 11
**应用信息**
 - 版本: 2.3.10

**Comment by Ariesly** [comment]
把貌似去掉，之前也统计在里面.

**Comment by Faramitas** [comment]
> 把貌似去掉，之前也统计在里面.

应该只是统计了，但应该没有走代理，不知道什么原因

**Comment by yanlihu** [comment]
> > 把貌似去掉，之前也统计在里面.
> 
> 应该只是统计了，但应该没有走代理，不知道什么原因

你可以在访问控制里设置，直接让应用不走cfa，这样也就不会看到流量了

**Comment by Kr328** [comment]
填完 请
