### ISSUE TITLE
[Feature Request] 对于暗黑模式下的颜色请求

### ISSUE THREAD

**Issue by Nothing460** [Kr328/ClashForAndroid#878]
更新了最新版本之后，发现暗黑模式下的颜色比较偏向灰色，而上个版本的暗黑模式更加偏向黑色，希望在这个模式下颜色能恢复到上个版本的暗黑模式。

**Comment by Kr328** [comment]
根据 Material Design 调整的 背景色 #121212 
从视觉上辨识度高很多 
而且也能降低很多开发上的心智负担 
未来也会继续遵循这套规范

**Comment by AkariiinMKII** [comment]
@Nothing460 Material Design 的 dark theme 规范明确要求使用深灰代替纯黑，不爽请去骂Luke
