### ISSUE TITLE
通知栏显示总流量

### ISSUE THREAD

**Issue by neteroster** [Kr328/ClashForAndroid#88]
在应用主界面中，会显示总转发的流量。希望可以在通知栏 "Clash for Android" 后增加总流量的显示（参考 shadowsocks-android）。这样不会产生明显的冗杂感，也能让用户快速了解流量情况。

**Comment by Kr328** [comment]
![image](https://user-images.githubusercontent.com/39107975/73269322-8f0e9500-4217-11ea-8784-1dcc7706bdfa.png)

**Comment by Kr328** [comment]
从 clash core 拿 转发总量 开销不小

**Comment by sensen1** [comment]
感觉 必要性不那么大，一般手机系统都提供通知栏显示流量功能，而常用来看，clash一般是工作在全局模式的，那么上面的总流量也就能表征clash的流量了。

**Comment by wbmins** [comment]
app关闭，然后再开启🐱使用的流量就重置了。可以把使用的流量保存在app的配置文件或sqllite里么，然后一个月一重置，或者可以设置定时重置么
