### ISSUE TITLE
[BUG] 网页时不时打不开，出现error:i/o timeout错误

### ISSUE THREAD

**Issue by jarod360** [Kr328/ClashForAndroid#880]
**描述出现的错误**
请简洁的描述你遇到的错误
更新到2.3.10后网页是不是需要刷新多次才能打开，抓包日志后发现很多链接出现error:i/o timeout错误
**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![Screenshot_20210409_211947_com github kr328 clash](https://user-images.githubusercontent.com/32123167/114191591-28d6e380-997f-11eb-841b-922c003b4a14.jpg)
![Screenshot_20210409_211657_com github kr328 clash](https://user-images.githubusercontent.com/32123167/114191602-2aa0a700-997f-11eb-8054-3bab825007ba.jpg)
![Screenshot_20210409_210308_com github kr328 clash](https://user-images.githubusercontent.com/32123167/114191606-2bd1d400-997f-11eb-8d4e-64c6e72cdd6e.jpg)

**设备信息 (请完成以下信息):**
 - 机型: [华为Mate40pro]
 - 系统/ROM: [EMUI 11]
 - Android 版本 [10]
 - ROM版本 [最新]

**应用信息**
 - 版本: [2.3.10]
 - 安装包文件名: [app-release-arm64-v8a.apk]
 - 应用来源: [Github]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
尝试 1.3.11

**Comment by jarod360** [comment]
已正常，谢谢大佬。
