### ISSUE TITLE
[Feature Request] 请求适配VLESS及Trojan-go协议

### ISSUE THREAD

**Issue by GeorgeXie2333** [Kr328/ClashForAndroid#881]
如题

**Comment by NevadaCities** [comment]
@GeorgeXie2333 隔壁Clash-core的事情关我们Clash for Android啥事，而且Trojan早就已经支持了。

**Comment by GeorgeXie2333** [comment]
> @GeorgeXie2333 隔壁Clash-core的事情关我们Clash for Android啥事，而且Trojan早就已经支持了。

Trojan-go XTLS。。。

**Comment by AkariiinMKII** [comment]
@GeorgeXie2333 https://github.com/Dreamacro/clash/pull/946
