### ISSUE TITLE
[BUG] 当节点更新订阅失败时，订阅节点会一直卡在更新失败订阅的节点配置，无法更换成更新成功订阅配置上上

### ISSUE THREAD

**Issue by 22hello** [Kr328/ClashForAndroid#884]
**描述出现的错误**
当节点更新订阅失败时，订阅节点会一直卡在更新失败订阅的节点配置，无法更换成更新成功订阅配置上上
**如何复现该错误**
复现步骤:
1.快速更新订阅
2. 当出现订阅失败时，切换成更新成功的订阅配置

**预期行为**
应该切换成功

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 小米8UD
 - 系统/ROM: MIUI 12
 - Android 版本 10
 - ROM版本 12.0.5

**应用信息**
 - 版本: 2.3.11
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: githhub

**附加信息**
要重新更新订阅才能成功

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
#887
