### ISSUE TITLE
[BUG] 覆写中 “追加系统 DNS” 为 不修改 但仍然启用，日志中没有列出所使用的 DNS Server

### ISSUE THREAD

**Issue by zoi50a6j** [Kr328/ClashForAndroid#886]
**描述出现的错误**
1. 覆写中 “追加系统 DNS” 为 不修改，但是仍然启用。
2. 2.3.11版的日志中没有列出所使用的 DNS Server 。

**如何复现该错误**
复现步骤:
1. 配置文件中随便添加一个海外 DNS ，不要添加系统 DNS 。
2. 在覆写中设置 ”DNS 策略“ 为 不修改 ，“追加系统 DNS” 默认为 不修改。
3. 由于新版的日志中看不到使用的 DNS Server，访问 https://browserleaks.com/dns 。
4. 结果中有本地 DNS ，即 “追加系统 DNS” 已启用。

**预期行为**
1. 不修改 默认应该是 禁用。
2. 日志应列出使用的 DNS Server 。

**应用信息**
 - 版本: v2.3.11
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: Github

**Comment by Kr328** [comment]
默认是启用 重构的时候没有加上日志 也不需要
