### ISSUE TITLE
[BUG] 开启CFA时，打开其他代理软件，CFA无法再打开

### ISSUE THREAD

**Issue by returnL** [Kr328/ClashForAndroid#892]
**描述出现的错误**
开启CFA时，运行其他代理软件，比如Shadowsocks，CFA会被顶下去，再去CFA界面点击“点此开启”无法开启CFA（多次点开启后，偶尔CFA会崩溃），同时Shadowsocks会被顶下去。只能清除CFA后台才能再次启动

**如何复现该错误**
复现步骤:
1. 启动CFA
2. CFA开启的状态下，启动Shadowsocks
3. 再启动CFA

**预期行为**
CFA被其他代理软件顶下去后，再启动能正常运行

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息:**
 - 机型: 一加9 Pro
 - 系统/ROM: ColorOS
 - Android 版本 11
 - ROM版本 11.2

**应用信息**
 - 版本: 2.3.11
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GitHub

**Comment by xuhaoyang** [comment]
@returnL 你反过来操作，shadowsocks一样得杀了，才能再开

**Comment by returnL** [comment]
> @returnL 你反过来操作，shadowsocks一样得杀了，才能再开

我两台手机测下来Shadowsocks都不用杀后台再开，被CFA顶掉之后能直接打开。同时2.1.6版本的CFA也不用杀了再开，能直接打开

**Comment by pianai217** [comment]
我也试过，使用clash再打开ssrray，然后进clash点不了启动，连着点两次就直接提示应用崩溃，反过来先用ssr再用clash没这个情况，
