### ISSUE TITLE
[BUG] 动画明显比之前的版本多了很多拖影

### ISSUE THREAD

**Issue by shopkeeperV** [Kr328/ClashForAndroid#895]
**描述出现的错误**
代理按钮，providers按钮的消失动画似乎是淡入淡出，看起拖影很严重

**设备信息 (请完成以下信息):**
 - 机型: 小米xim2s
 - 系统/ROM: miui12
 - Android 版本 安卓10

**应用信息**
 - 版本: v2.3.11
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: release

**Comment by Kr328** [comment]
全都采用系统默认动画 没有任何额外配置
