### ISSUE TITLE
DOMAIN-SUFFIX 规则未能按预期运行

### ISSUE THREAD

**Issue by AzunyanDaisuki** [Kr328/ClashForAndroid#90]
我在 Windows 和 Android 上使用的是同一个规则文件，其中有添加一条规则：
`DOMAIN-SUFFIX,dnsleaktest.com,DIRECT`
希望能够将 "dnsleaktest.com" 域名的网址直连
但我发现，分别使用 Clash for Windows 和 ClashForAndroid 访问 [https://www.dnsleaktest.com/](url)
在 Windows 上，域名被正确识别并直连了，记录如图
![image](https://user-images.githubusercontent.com/18110400/73424540-07856b00-436a-11ea-84f3-555a3a2fc8be.png)
而在 Android 上，域名没有被识别，进入了 "final"，记录如图
![Screenshot_20200130-140141_Mosaic_14_13_42](https://user-images.githubusercontent.com/18110400/73424866-f9841a00-436a-11ea-96dd-b082d3769cd7.png)
请问这样的现象正常吗，有什么办法能够让该域名直连吗？

**Comment by Kr328** [comment]
检查 DNS 配置
没有 fakeip 或者 redir-host 的话
这样 是 预期行为

具体 Google
