### ISSUE TITLE
[Feature Request] 請問可以增加「關鍵字不加入節點」的功能嗎？

### ISSUE THREAD

**Issue by HeaKa** [Kr328/ClashForAndroid#907]
**功能描述**
關鍵字不加入節點：就是祇想載入非關鍵字的節點

**描述你希望的实现方式**
有見過像路由器的OW固件内就有這個功能

**附加信息**
我就小白一個，想到一個功能就想來問問作者有無可能可以加入CFA而已，感謝再次更新。

**Comment by AkariiinMKII** [comment]
@HeaKa https://github.com/tindy2013/subconverter 请

**Comment by Kr328** [comment]
反馈上游 请
