### ISSUE TITLE
[Feature Request] 最强大的客户端，但有一点不便，关于订阅传输中介

### ISSUE THREAD

**Issue by OG-C** [Kr328/ClashForAndroid#910]
**功能描述**
多设备间订阅链接的分享非常麻烦，只能复制链接使用微信QQ等来发送，出于隐私考虑始终心里有疙瘩。能否添加扫码和生成二维码分享的功能？万分感谢。这是困扰我使用clash最大的问题了，几次都要差点放弃了。万分期望。爱之深责之切。

**描述你希望的实现方式**
添加生成二维码分享、以及扫码功能

**附加信息**
现有的场景，必须要借助第三方IM来传达订阅，而二维码解决了中间传输介质，可以离线完成，更保证隐私。殷切希望添加该功能。

**Comment by Kr328** [comment]
@OG-C 不能 不做

**Comment by OG-C** [comment]
> @OG-C 不能 不做

K大，cfw也支持二维码了，这个功能是刚需，尤其是手机端，太需要了

**Comment by Kr328** [comment]
@OG-C 不在内部做

不为了一个不常用功能引入大量不必要的依赖

用系统的二维码扫描器扫描又不是不行

**Comment by OG-C** [comment]
> @OG-C 不在内部做
> 
> 不为了一个不常用功能引入大量不必要的依赖
> 
> 用系统的二维码扫描器扫描又不是不行

不只是扫码，移动设备间的分享，生成和扫码。常用功能

**Comment by Kr328** [comment]
@OG-C 你常用 不代表大部分人常用 有多少人会频繁更换手机?

要有时间折腾手机 还不如学学怎么写自定义配置 provider 自动管理规则和代理更新 比这订阅方便多了

**Comment by xuhaoyang** [comment]
@Kr328

**Comment by OG-C** [comment]
> @OG-C 你常用 不代表大部分人常用 有多少人会频繁更换手机?
> 
> 要有时间折腾手机 还不如学学怎么写自定义配置 provider 自动管理规则和代理更新 比这订阅方便多了

![Snipaste_2021-04-18_14-05-06](https://user-images.githubusercontent.com/82382147/115136013-758d7f00-a04f-11eb-8fad-1affa2f9b769.png)
![Snipaste_2021-04-18_14-06-47](https://user-images.githubusercontent.com/82382147/115136054-bd140b00-a04f-11eb-9768-a57ed56ec77f.png)
