### ISSUE TITLE
[BUG] 一直显示“更新配置中”

### ISSUE THREAD

**Issue by OG-C** [Kr328/ClashForAndroid#911]
**描述出现的错误**
更新2.3.13版本后，点更新配置，通知栏持续显示更新中

**如何复现该错误**
复现步骤:
1. 配置
2. 三点选项
3. 更新
4. 通知栏持续不消失

**预期行为**
更新后通知栏自动消失

**屏幕截图**
![IMG_20210414_120953.jpg](https://user-images.githubusercontent.com/82382147/114653578-f6462700-9cad-11eb-9dd4-7b256d81058a.jpg)

**设备信息 (请完成以下信息):**
 - 机型：mi11
 - 系统/ROM:  MIUI 12
 - Android 版本  10
 - ROM版本 12.0.4

**应用信息**
 - 版本: 2.3.13
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源:github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
#882

**Comment by OG-C** [comment]
> #882 

2.3.14依然存在这个bug
