### ISSUE TITLE
[BUG] 连上节点无法使用

### ISSUE THREAD

**Issue by hyt-allen-xu** [Kr328/ClashForAndroid#917]
**描述出现的错误**
Clash连上节点无法科学上网

**如何复现该错误**
复现步骤:
1. 打开clash
2. 选择配置
3. 连上节点
（节点在其他客户端测试过了，没有问题，ping也是ok的）

**预期行为**
可以科学上网

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Mate 10 Pro HUAWEI
 - 系统/ROM: 未知
 - Android 版本 10
 - ROM版本 4.14.116

**应用信息**
 - 版本: 2.3.16
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: github

**附加信息**
希望增加功能

**Comment by Kr328** [comment]
模板填完

**Comment by hyt-allen-xu** [comment]
[TCP] dial ✈️ 节点选择 (match DomainKeyword/github) to alive.github.com error: 01.HKG.ASIA.BIGAIRPORT.NET:80 connect error: all DNS requests failed, first error: Post "https://cloudflare-dns.com/dns-query": dial tcp4 104.16.248.249:443: i/o timeout

**Comment by hyt-allen-xu** [comment]
这个

**Comment by hyt-allen-xu** [comment]
日志

**Comment by AkariiinMKII** [comment]
@hyt-allen-xu DNS错误
