### ISSUE TITLE
[BUG] 使用移动网络时异常的待机耗电

### ISSUE THREAD

**Issue by zszeng** [Kr328/ClashForAndroid#918]
CFA2.3.16 AndroidP MIUI12
使用移动网络网络休眠待机时莫名其妙的耗电
无reject规则 使用应用白名单模式 且无任何白名单应用在后台运行
似乎只有使用移动网络 且系统doze时才会触发
日志没有捕获到任何异常内容
![Screenshot_2021-04-17-16-08-49-484_com miui securitycenter](https://user-images.githubusercontent.com/12959626/115106586-3f40f880-9f98-11eb-9880-6c0207b2a1a7.jpg)
![Screenshot_2021-04-17-16-10-33-245_com miui securitycenter](https://user-images.githubusercontent.com/12959626/115106590-4405ac80-9f98-11eb-9dfa-b6bf3913c535.jpg)
![Screenshot_2021-04-17-16-11-54-791_com miui securitycenter](https://user-images.githubusercontent.com/12959626/115106593-46680680-9f98-11eb-8a42-3daee79bde4e.jpg)

**Comment by zszeng** [comment]
补充 未勾选dns劫持，且规则里所有ip均有no-resolve

**Comment by nameless3721** [comment]
因为cfa会帮微信等应用省电导致的 可以访问控制里面把那些被cfa省电的应用绕过应该就好了

**Comment by Kr328** [comment]
#505

**Comment by zszeng** [comment]
> 因为cfa会帮微信等应用省电导致的 可以访问控制里面把那些被cfa省电的应用绕过应该就好了

请认真阅读 我使用了白名单模式 即仅代理数个需要外网的应用，微信等应用均不通过cfa

**Comment by xuhaoyang** [comment]
miui这个耗电并不准

**Comment by xuhaoyang** [comment]
![Screenshot_2021-04-09-09-57-47-174_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/1927125/115115071-fc494a00-9fc4-11eb-8b5b-3eef18a7dd39.jpg)

**Comment by Ghostssswind** [comment]
> miui这个耗电并不准

魅族手机也是类似的情况，不过没有90%，但经常在60%-70%上下
