### ISSUE TITLE
关于UI上的一些建议

### ISSUE THREAD

**Issue by sceraser** [Kr328/ClashForAndroid#92]
ID:d4cf50e5fffbd72f55a4e69a1572aa68
![Screenshot_2020-02-03-14-30-06-031_com github kr328 clash](https://user-images.githubusercontent.com/42718757/73630812-28afc980-4692-11ea-8ce5-c945997d54ba.jpg)
双栏显示在手机上太过拥挤，建议改成单栏显示
![OP3UX@~4Q)O({QGBUD22JIS](https://user-images.githubusercontent.com/42718757/73631013-ab388900-4692-11ea-99b7-d5019b7a864d.png)
由于Clash规则的特殊性，一个节点会多次重复显示，能否参照Clash For Windows支持规则折叠，否则要修改底部的规则需要大量翻页操作，对手机来说体验很差

**Comment by Kr328** [comment]
#21 
#15
