### ISSUE TITLE
[Feature Request] 请问目前clashforandroid可以实现透明代理吗

### ISSUE THREAD

**Issue by boghit** [Kr328/ClashForAndroid#920]
**功能描述**
请清晰的描述你想要的功能

请问目前clashforandroid可以实现透明代理吗？

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
可以 但是需要自己用 ROOT 设置 iptables
