### ISSUE TITLE
[BUG] playStore更新的v2.3.16无法连接vmess

### ISSUE THREAD

**Issue by sidazhang123** [Kr328/ClashForAndroid#921]
**描述出现的错误**
在playstore更新v2.3.16后,发现原cfg中的vmess配置虽然识别但ping不通, ss正常. 只得手动重装2.3.10使用(更准确来讲可以认为你们推送store的上一个版本无此问题)
为JMS的老配置, 手机电脑很久没动过:
proxies:
- {name: xxx, server: xxx, port:xxx ,type: vmess, uuid: xxx, alterId: 0, cipher: auto, tls: false}

手机为oneplus 7pro

**Comment by Kr328** [comment]
模板全部填完 请

**Comment by akw5454521** [comment]
你确定JMS的alterId是"0"？
