### ISSUE TITLE
[BUG] 使用proxy-providers功能无法保存profile

### ISSUE THREAD

**Issue by ghgds** [Kr328/ClashForAndroid#925]
**描述出现的错误**
使用proxy-providers功能无法保存本地profile

**如何复现该错误**
新建本地profile，选择上传配置文件，配置文件中包含了proxy-providers区，保存时提示错误无法保存。

**屏幕截图**
本地配置文件如下：
`port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
cfw-latency-url: 'http://cp.cloudflare.com/generate_204'

proxy-providers:
	hk:
		type: http
		path: ./hk.yaml
		url: http://remote.lancelinked.icu/files/hk.yaml
		interval: 3600
		health-check:
			enable: true
			url: http://www.gstatic.com/generate_204
			interval: 300`

同时我也尝试在provider目录上传文件，命名为hk.yaml ，保存也一样提示错误。

保存时提示如图：
![Screenshot_20210418_224555_com github kr328 clash](https://user-images.githubusercontent.com/31283292/115149987-10f71200-a099-11eb-9c2e-fb8fce17b6dc.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Huawei Mate20
 - 系统/ROM: EMUI11
 - Android 版本 10

**Comment by Kr328** [comment]
你这个缩进就不像是正常的缩进

**Comment by ghgds** [comment]
感谢大佬亲自回复，刚刚贴的格式不齐，缩进是没问题的，我参考https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider写的
![image](https://user-images.githubusercontent.com/31283292/115150954-5289bc00-a09d-11eb-95d8-89e3e16a4b14.png)

**Comment by ghgds** [comment]
感谢大佬回复，确实是配置文件缩进用了tab而非空格，已经搞定了，谢谢谢
