### ISSUE TITLE
[Feature Request] 我想请教一个问题，规则模式能自己编辑吗？

### ISSUE THREAD

**Issue by One010101** [Kr328/ClashForAndroid#933]
我想请教一些问题，
1. 规则模式是软件自带的吗，可以自己编辑吗?
2. 规则模式工作流程大概是怎样的，是获取手机所有的请求域名然后解析吗？当然，我不是想学技术，我是关心手机的功耗，如果每次请求都要解析，这样会不会比全局模式耗电

**Comment by Kr328** [comment]
![IMG_20210419_022402](https://user-images.githubusercontent.com/39107975/115156341-56760800-a0b6-11eb-8758-4c35401a6a95.jpg)
