### ISSUE TITLE
[Feature Request] 请问规则模式比全局模式更耗电吗？规则模式是不是每个请求都要解析一次？

### ISSUE THREAD

**Issue by One010101** [Kr328/ClashForAndroid#935]
请问规则模式比全局模式更耗电吗？规则模式是不是每个请求都要解析一次

**Comment by Kr328** [comment]
@One010101 自己读逻辑 请

https://github.com/Dreamacro/clash/blob/master/tunnel/tunnel.go

**Comment by akw5454521** [comment]
能不能一次把问题问完了
