### ISSUE TITLE
[Feature Request] WebSocket 0-RTT

### ISSUE THREAD

**Issue by chuan01** [Kr328/ClashForAndroid#937]
**功能描述**
请清晰的描述你想要的功能
支持xray 0-RTT
**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能
https://github.com/XTLS/Xray-core/pull/375
**附加信息**
其他的与改功能相关的附加信息
无

**Comment by xuhaoyang** [comment]
去上游提
