### ISSUE TITLE
[BUG] Automatic profile update does not start until the user open the app once

### ISSUE THREAD

**Issue by v20coeur** [Kr328/ClashForAndroid#940]
**Describe the bug**
Since version 2.0.3 the automatic profile update does not start until the user have opened the application once.
It works on v2.0.2 and on the SSR fork ClashR v1.3.4R by @naicfeng

**To Reproduce**

1. Set Auto Restart in settings/app
2. Set Auto Update in profile (ex : 15 min)
3. Restart the device

The VPN service start Clash but the auto update doesn't start.

**Expected behavior**
The automatic profile update should start when the system starts Clash.

**Device Info (please complete the following information):**

Tested on : 

 - Device: Sony Xperia Z5 Compact
 - ROM: OEM
 - Android Version 7

Tested on : 

 - Device: Motorola Moto G4
 - ROM: OEM
 - Android Version 7

Tested on : 

 - Device: Amazon Fire Stick 2019
 - ROM: OEM
 - Based on Android TV Version 5

Tested on : 

 - Device: Amazon Fire Stick 4K 2020
 - ROM: OEM
 - Based on Android TV Version 7
 - (on v2.3.16 the auto start doesn't work too)

Tested on : 

 - Device: Nokia 1
 - ROM: OEM
 - Android GO Version 10

**Application Info (please complete the following information):**
 - Version: 2.0.3-2.3.16 (tested on all versions)
 - Apk File Name: app-armeabi-v7a-release.apk/app-arm64-v8a-release.apk
 - Distribution Channel: github

**Comment by Kr328** [comment]
@v20coeur try latest version

**Comment by v20coeur** [comment]
@Kr328 the v2.3.17 solve the problem, good job. Would it be possible to have a unique notification rather than a new one for each update ? if I put 15 min that makes 96 notifications over the last 24 hours.
