### ISSUE TITLE
[BUG] 一直显示配置更新服务

### ISSUE THREAD

**Issue by 22hello** [Kr328/ClashForAndroid#941]
**描述出现的错误**
通知栏一直显示配置更新服务

**如何复现该错误**
复现步骤:
1. 更新订阅配置
2. 查看通知栏
3. 
4. 

**预期行为**
很快消失

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 小米8UD
 - 系统/ROM: MIUI12
 - Android 版本 10
 - ROM版本 12.0.5

**应用信息**
 - 版本: 2.1.7
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GITHUB

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by 22hello** [comment]
2.1.6没有问题

**Comment by Kr328** [comment]
日志 截图 系统崩溃报告 请

**Comment by 22hello** [comment]
> 日志 截图 系统崩溃报告 请
刚才又试了一下，发现通知栏并没有一直显示配置更新服务，而是停留很久才消失
日志只有这个
[APP] Logcat level: silent
