### ISSUE TITLE
[BUG] 配置更新服务正在运行中在通知栏显示时间较长

### ISSUE THREAD

**Issue by 22hello** [Kr328/ClashForAndroid#942]
**描述出现的错误**
配置更新服务正在运行中在通知栏显示时间较长

**如何复现该错误**
复现步骤:
1. 更新订阅
2. 查看通知栏

**预期行为**
配置更新服务应该很快小石

**屏幕截图**
![IMG_20210420_202327](https://user-images.githubusercontent.com/69850337/115395284-48d79400-a216-11eb-88ac-f5101a0ec201.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米8UD
 - 系统/ROM:  MIUI 12
 - Android 版本 10
 - ROM版本 12.0.5

**应用信息**
 - 版本: 2.1.7
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GITHUB

**附加信息**
2.1.6版没有出现此问题，并且试过重装

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```

[APP] Logcat level: silent

**Comment by Kr328** [comment]
Android 系统限制了前台服务的通知展示时间 小于限制展示时间的通知 不会被清除

**Comment by 22hello** [comment]
谢谢，明白了
