### ISSUE TITLE
[BUG] 黑暗模式下进入app会有白色闪屏

### ISSUE THREAD

**Issue by cliuff** [Kr328/ClashForAndroid#943]
应该是主题样式切换问题，manifest里面设置的主题应该跟随系统。比如使用values-night的styles.xml定义黑暗模式的主题，或者使用material components的daynight主题，这样启动时的背景色才会跟随系统变化。可以随后在进入app了之后再切换自定义主题。

**Comment by Kr328** [comment]
都 不 是 你 猜 的 哦

**Comment by Kr328** [comment]
DayNight 组件不好用 并不比自己控制的要好

而且 你认为为什么 DayNight 能够切换颜色 一样也需要在 onCreate 里修改主题的 DayNight 也不能逃离 Android 的那套生命周期管理 还难以定制

这个问题绝大部分是由于系统引起 测试过的机型里 没有能够复现的 (真是包括 MIUI

**Comment by cliuff** [comment]
![Screenshot_20210421-003751.png](https://user-images.githubusercontent.com/35420834/115433560-4be47b80-a23a-11eb-9e75-aa784f1990a3.png)
![Screenshot_20210421-003832.png](https://user-images.githubusercontent.com/35420834/115433597-543cb680-a23a-11eb-9bce-14dc838e5c84.png)
![Screenshot_20210421-003842.png](https://user-images.githubusercontent.com/35420834/115433648-5ef74b80-a23a-11eb-8175-4b5ede5cbc09.png)
![Screenshot_20210421-003853.png](https://user-images.githubusercontent.com/35420834/115433708-6c143a80-a23a-11eb-8421-7ea3934e1892.png)

**Comment by cliuff** [comment]
@Kr328 我注意到最近的更新支持了edge to edge，非常棒，希望能够改善这个问题，有完美的体验

**Comment by Kr328** [comment]
不能复现 无法改善 night 资源不好用 创建 theme 很麻烦 不想带来低版本适配成本

**Comment by Kr328** [comment]
@Kr328 低版本 night 并不能正常使用 大量的使用 night 会带来低版本兼容问题

曾经的 2.0.x 版本 就曾经因为这个带来大量的问题 以及成倍的资源

**Comment by cliuff** [comment]
@Kr328 我说的是：只在开始屏幕这段时间使用night，以解决白屏问题，一进入主activity后就切换回你自己定义的style，这样不会出现啥问题吧

**Comment by Kr328** [comment]
@cliuff 应用点击的时候 就是 主 Activity 没有加任何的其他 Activity 我也不喜欢所谓的 开屏 Activity

**Comment by cliuff** [comment]
@Kr328 在onCreate之前就展示了一个window background

**Comment by cliuff** [comment]
@Kr328 

https://github.com/cliuff/boundo/blob/master/app/src/main/res/values/styles.xml
styles，第48行。定义一个LaunchScreen，我这里是直接继承的DayNight，用这个就能跟随系统变色。或者使用night来定义，那么就得自己设置才能跟随系统变色，好像是windowBackgroundColor吧。

https://github.com/cliuff/boundo/blob/master/app/src/main/AndroidManifest.xml
AndroidManifest，第77行。设置application的theme为LaunchScreen。

https://github.com/cliuff/boundo/blob/master/app/src/main/kotlin/com/madness/collision/main/MainActivity.kt
MainActivity，第164行。切换主题。

**Comment by Kr328** [comment]
@cliuff 我已经找到更适合我的解法了 不需要要去使用难以定制的 DayNight

https://github.com/RikkaApps/Shizuku/blob/cbe04446daad261fe50a4daea278aa0a8e214ae2/manager/src/main/res/values-night/styles.xml#L3

https://github.com/RikkaApps/Shizuku/blob/cbe04446daad261fe50a4daea278aa0a8e214ae2/manager/src/main/res/values/styles.xml#L3
