### ISSUE TITLE
[BUG] DNS Override failure

### ISSUE THREAD

**Issue by bakamosokyo** [Kr328/ClashForAndroid#945]
**Describe the bug**
DNS Override doesn't work with enhanced mode disabled. It shows error 'Name Server can't be empty' which is not true.

**To Reproduce**
1. Go to Override, Set DNS to force enable, disable enhanced mode, add name servers.
2. Nothing works anyone. Tap to start, update profile, add profile, etc.

**Expected behavior**
DNS Override works exactly as 2.1.6/5

**Screenshots**
Not today

**Device Info (please complete the following information):**

 - Device: Xperia XZ2
 - ROM: Sony stock fw
 - ROM Version: dk
 - Android Version: 10

**Application Info (please complete the following information):**

 - Version: 2.3.17
 - Apk File Name: arm-v8
 - Distribution Channel: right here

**Additional context**

**Configure**
Doesn't matter, happens before actually doing anything.

**Logs**
Iater, If you can't reproduce.

**Comment by Kr328** [comment]
intended behavior

**Comment by bakamosokyo** [comment]
> intended behavior

So you're saying we can't disable enhanced mode any more.
Only 'built-in' and 'force enable+enhanced mode' are allowed.
Is that correct?

**Comment by Kr328** [comment]
@bakamosokyo you should add some dns server to nameservers

**Comment by bakamosokyo** [comment]
> @bakamosokyo you should add some dns server to nameservers

Quote:
"To Reproduce

1. Go to Override, Set DNS to force enable, disable enhanced mode, _ADD NAME SERVERS_."

YES I DID ADD NAME SERVERS.

**Comment by Kr328** [comment]
@bakamosokyo it will be fixed next release
