### ISSUE TITLE
[Feature Request]希望在增加节点列表中删除选定节点的功能

### ISSUE THREAD

**Issue by wangjianpro** [Kr328/ClashForAndroid#946]
**功能描述**
希望在增加节点列表中删除选定节点的功能。
**描述你希望的实现方式**
希望在增加节点列表中删除选定节点的功能。或节点筛选功能。

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
https://github.com/Kr328/ClashForAndroid/issues/295#issuecomment-616258969
