### ISSUE TITLE
读取本地配置文件问题

### ISSUE THREAD

**Issue by Forty-nine** [Kr328/ClashForAndroid#95]
![Screenshot_2020-02-06-16-15-55-879_com github kr328 clash](https://user-images.githubusercontent.com/14026156/73918635-f2c24d80-48fc-11ea-9b3e-a52c3a0bab43.jpg)
读取本地配置文件出错

**Comment by Kr328** [comment]
检查你的配置
删除 `external-ui` 段

**Comment by Forty-nine** [comment]
确实是 这个 问题……
