### ISSUE TITLE
[BUG] 更新订阅报错

### ISSUE THREAD

**Issue by 22hello** [Kr328/ClashForAndroid#950]
**描述出现的错误**
一键更新订阅报错

**如何复现该错误**
复现步骤:
1. 导入两个及以上订阅
2. 一键更新订阅
3. ...
4. ...

**预期行为**
更新订阅成功

**屏幕截图**
![IMG_20210421_172952](https://user-images.githubusercontent.com/69850337/115534009-eb048400-a2c9-11eb-9f47-999d3c5a13f9.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米8UD
 - 系统/ROM: MIUI 12
 - Android 版本 10
 - ROM版本 12.0.5

**应用信息**
 - 版本: 2.3.17
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GITHUB

**附加信息**
配置更新服务正在运行在通知栏的时间比2.3.16长太多了，即使更新订阅成功了，还在显示配置更新服务正在运行中

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```
[APP] Logcat level: info
[TCP] 127.0.0.1:44774 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]

[TCP] 172.31.255.253:37974 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 127.0.0.1:44778 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 172.31.255.253:37978 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 127.0.0.1:44782 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 172.31.255.253:37982 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 172.31.255.253:43094 --> subcon.dlj.tf match Match() using 🐟 漏网之鱼[🇭🇰 动态BGP+IPLC|广港01(原生)|3x]
Start initial compatible provider 📢 谷歌FCM
Start initial compatible provider Ⓜ️ 微软服务
Start initial compatible provider 🐟 漏网之鱼
Start initial compatible provider 🛑 全球拦截
Start initial compatible provider 🌍 国外媒体
Start initial compatible provider ♻️ 自动选择
Start initial compatible provider 🚀 节点选择
Start initial compatible provider 🎯 全球直连
Start initial compatible provider 📲 电报信息
Start initial compatible provider 📢 谷歌FCM
Start initial compatible provider Ⓜ️ 微软服务
Start initial compatible provider 🐟 漏网之鱼
Start initial compatible provider 🛑 全球拦截
Start initial compatible provider 🌍 国外媒体
Start initial compatible provider ♻️ 自动选择
Start initial compatible provider 🚀 节点选择
Start initial compatible provider 🎯 全球直连
Start initial compatible provider 📲 电报信息
dns:
  enable: true
  use-hosts: true
  nameserver:
  - 223.5.5.5
   - 119.29.29.29
   -   - 8.8.8.8
   -   - 1.1.1.1
   -   - 192.168.31.1:53
   -   fallback: []
   -   fallback-filter:
   -     geoip: false
   -     ipcidr:
   -     - 0.0.0.0/32
   -     - 127.0.0.0/8
   -     domain: []
   -   listen: ""
   -   enhanced-mode: fake-ip
   - 

**描述出现的错误**
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```
[APP] Logcat level: info
[TCP] 127.0.0.1:44774 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]

[TCP] 172.31.255.253:37974 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 127.0.0.1:44778 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 172.31.255.253:37978 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 127.0.0.1:44782 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 172.31.255.253:37982 --> data.mistat.xiaomi.com match DomainSuffix(data.mistat.xiaomi.com) using 🍃 应用净化[REJECT]
[TCP] 172.31.255.253:43094 --> subcon.dlj.tf match Match() using 🐟 漏网之鱼[🇭🇰 动态BGP+IPLC|广港01(原生)|3x]
Start initial compatible provider 📢 谷歌FCM
Start initial compatible provider Ⓜ️ 微软服务
Start initial compatible provider 🐟 漏网之鱼
Start initial compatible provider 🛑 全球拦截
Start initial compatible provider 🌍 国外媒体
Start initial compatible provider ♻️ 自动选择
Start initial compatible provider 🚀 节点选择
Start initial compatible provider 🎯 全球直连
Start initial compatible provider 📲 电报信息
Start initial compatible provider 📢 谷歌FCM
Start initial compatible provider Ⓜ️ 微软服务
Start initial compatible provider 🐟 漏网之鱼
Start initial compatible provider 🛑 全球拦截
Start initial compatible provider 🌍 国外媒体
Start initial compatible provider ♻️ 自动选择
Start initial compatible provider 🚀 节点选择
Start initial compatible provider 🎯 全球直连
Start initial compatible provider 📲 电报信息
dns:
  enable: true
  use-hosts: true
  nameserver:
  - 223.5.5.5
   - 119.29.29.29
   -   - 8.8.8.8
   -   - 1.1.1.1
   -   - 192.168.31.1:53
   -   fallback: []
   -   fallback-filter:
   -     geoip: false
   -     ipcidr:
   -     - 0.0.0.0/32
   -     - 127.0.0.0/8
   -     domain: []
   -   listen: ""
   -   enhanced-mode: fake-ip
   -   fake-ip-range: 198.18.0.0/16
   -   fake-ip-filter:
   -   - +.stun.*.*
   -   - +.stun.*.*.*
   -   - +.stun.*.*.*.*
   -   - lens.l.google.com
   -   - stun.l.google.com
   -   - '*.n.n.srv.nintendo.net'
   -   default-nameserver:
   -   - 223.5.5.5
   -   - 119.29.29.29
   -   - 8.8.8.8
   -   - 1.1.1.1

**Comment by 22hello** [comment]
就看上面的就行，不用看下面的

**Comment by Kr328** [comment]
很典型的网络问题

**Comment by Kr328** [comment]
无论是代理服务器连接不稳定 亦或是某些代理协议实现不佳 都可能引起这个问题

**Comment by 22hello** [comment]
我在试试看看
