### ISSUE TITLE
[Feature Request] 关于改进配置更新服务的小意见

### ISSUE THREAD

**Issue by 22hello** [Kr328/ClashForAndroid#953]
**功能描述**
配置更新服务虽然改进了，但是在通知栏停留时间比2.3.16要长的多

**描述你希望的实现方式**
希望能和2.3.16版本一样，能够配置更新完后迅速消失
而不是停留在通知栏上

**附加信息**
关于小米的通知栏问题

**Comment by Kr328** [comment]
@22hello 系统启动会等待 30s 防止如果有配置文件立即更新 导致的服务频繁启动问题

每次启动服务 也会等待 10s 理由同上

**Comment by 22hello** [comment]
OK，知道了，谢谢，主要还是有疑问
