### ISSUE TITLE
[Feature Request] 氧OS10.0.1Play商店一直没有收到更新

### ISSUE THREAD

**Issue by willaytoun** [Kr328/ClashForAndroid#956]
**功能描述**
一加5T氧OS10.0.1Play商店一直没收到更新通知不知道什么原因，所以请问一下

**描述你希望的实现方式**
清晰的描述应用应该如何实现该功能

**附加信息**
其他的与改功能相关的附加信息

**Comment by Kr328** [comment]
没收到就等
