### ISSUE TITLE
[Feature Request] 增加dns over quic支持

### ISSUE THREAD

**Issue by Tenderness-Miao** [Kr328/ClashForAndroid#960]
**功能描述**
请求在clash for Android 中增加 dns over quic的功能

**描述你希望的实现方式**
可以在设置-覆写-nameservers 或fallback选项中直接添加dns over quic的地址

**附加信息**

**Comment by NevadaCities** [comment]
@Tenderness-Miao 国内UDP直连环境过差，QUIC是基于UDP

**Comment by NevadaCities** [comment]
@Tenderness-Miao 所以我觉得不会支持DNS over QUIC

**Comment by NevadaCities** [comment]
@Tenderness-Miao 而且Clash for Android的职责是做一个GUI，功能是Dreamacro的Clash-core的事情。
