### ISSUE TITLE
[BUG] 小米盒子国际版使用V2.3.17无法导入本地文件

### ISSUE THREAD

**Issue by ben-august** [Kr328/ClashForAndroid#963]
**描述出现的错误**
无法显示表示“本地导入”的符号，安卓手机上能显示右上角的导入标志，小米盒子上无法显示，故没办法导入本地配置。V2.3.16可以正常导入，但是还是没有2.1.16版本方便，可以的话建议导入方式恢复成原来2.1.16版本。

**如何复现该错误**
复现步骤:
1. 运行软件
2. 选择配置
3. 选择本地文件导入

**预期行为**
可以正常通过本地文件导入功能选择本地的配置文件

**屏幕截图**
![IMG_4935](https://user-images.githubusercontent.com/36500518/115942348-6fc6ec00-a4dc-11eb-90d5-b5f2eced6fd6.jpg)

**设备信息 (请完成以下信息):**
 - 机型: [例如: MIBOS4]
 - 系统/ROM: [例如:原厂系统]
 - Android 版本 [例如: 9]
 - ROM版本 [例如: 安卓9]

**应用信息**
 - 版本: [例如: 2.3.17]
 - 安装包文件名: [例如: app-universal-release.apk]
 - 应用来源: [例如: GitHub release]

**附加信息**
2.1.16版本的本地导入方式最简单明了，建议回退到2.1.16版本的导入方式。

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
配置文件.yaml 
右边三个点 
点击 
导入 
请

**Comment by ben-august** [comment]
> 配置文件.yaml
> 右边三个点
> 点击
> 导入
> 请

我试了，导入的是空白文件！

**Comment by Kr328** [comment]
文件呢 截图呢 录屏呢 **日志呢**

**Comment by ben-august** [comment]
> 文件呢 截图呢 录屏呢 **日志呢**

解决了 但是导入的文件需要重命名很不方便

**Comment by Kr328** [comment]
@ben-august -呢 -呢 -呢 -呢

我这从来没有设置需要重命名的逻辑

**Comment by ben-august** [comment]
> @ben-august -呢 -呢 -呢 -呢
> 
> 我这从来没有设置需要重命名的逻辑

就是导入的文件名字不修改的话默认名字“配置.yaml”
