### ISSUE TITLE
[Feature Request] CFW已支持二维码，求CFA也支持

### ISSUE THREAD

**Issue by OG-C** [Kr328/ClashForAndroid#964]
求K大支持下二维码功能。谢谢
![Snipaste_2021-04-24_11-05-17](https://user-images.githubusercontent.com/82382147/115945495-b291bf80-a4ee-11eb-9573-0eff8f34aed0.png)
![Uploading 115136013-758d7f00-a04f-11eb-8fad-1affa2f9b769.png…]()
![115136054-bd140b00-a04f-11eb-9768-a57ed56ec77f](https://user-images.githubusercontent.com/82382147/115945512-b9b8cd80-a4ee-11eb-8703-3ae427e26fcc.png)

**Comment by Kr328** [comment]
@OG-C “Barcode Scanner” 请

https://play.google.com/store/apps/details?id=com.google.zxing.client.android

**Comment by OG-C** [comment]
> @OG-C “Barcode Scanner” 请
> 
> https://play.google.com/store/apps/details?id=com.google.zxing.client.android

这个只有扫码功能，没有生成功能

**Comment by OG-C** [comment]
![115136013-758d7f00-a04f-11eb-8fad-1affa2f9b769](https://user-images.githubusercontent.com/82382147/115946544-85e0a680-a4f4-11eb-8e81-7a40c26481dd.png)

**Comment by Kr328** [comment]
![IMG_20210424_120607](https://user-images.githubusercontent.com/39107975/115946682-7f066380-a4f5-11eb-9c93-070474d1757c.jpg)

不用发 CFW 怎么样 

CFW 怎么样和 CFA 怎么处理没有任何关系

**Comment by OG-C** [comment]
> ![IMG_20210424_120607](https://user-images.githubusercontent.com/39107975/115946682-7f066380-a4f5-11eb-9c93-070474d1757c.jpg)
> 
> 不用发 CFW 怎么样
> 
> CFW 怎么样和 CFA 怎么处理没有任何关系

如果能集成这个功能，就不用再单独去下个APP那么麻烦了

**Comment by Kr328** [comment]
@OG-C 如果集成这个功能 绝大部分用户就需要为不常用的功能 额外付出 2M 存储 以及 不必要的 Google 追踪服务

**Comment by OG-C** [comment]
> 不必要的 Google 追踪

2M存储可以忽略不计，GOOGLE追踪是怎么回事？没集成该功能就不会追踪，添加该功能后会被GOOGLE追踪吗？是调用相机会被追踪吗？

**Comment by Kr328** [comment]
@OG-C 2M 已经是 1/4 现在的体积 你说忽略不计 其他人呢

追踪指的是 Google 的 SDK 自带的使用信息收集服务 有隐私洁癖的人对这类服务很抗拒

**Comment by OG-C** [comment]
> @OG-C 2M 已经是 1/4 现在的体积 你说忽略不计 其他人呢
> 
> 追踪指的是 Google 的 SDK 自带的使用信息收集服务 有隐私洁癖的人对这类服务很抗拒

(╯▽╰)

**Comment by gtang8** [comment]
虽然已经closed，但是还是觉得扫描二维码的功能方便很多，没有必要用第三方的扫描工具复制粘贴到CFA里面。
