### ISSUE TITLE
[BUG] 最新版2.3.17手机右上角VPN标志无法消失

### ISSUE THREAD

**Issue by ForestL18** [Kr328/ClashForAndroid#966]
**描述出现的错误**
最新版2.3.17在手机长时间息屏后，关闭clash，手机右上角的VPN标志无法消失，只有重启手机才能解决
**如何复现该错误**
复现步骤:
多次出现该情况

**预期行为**
关闭clash后，VPN标志随之消失

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Redmi K40
 - 系统/ROM:MIUI12
 - Android 版本11
 - ROM版本 12.0.8

**应用信息**
 - 版本: 2.3.17
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源:  Google Play

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
然后呢 网络正常吗

**Comment by yi-Xu-0100** [comment]
@Kr328 以前的小米6（MIUI11）有过，网络状态随CFA变换，但是 VPN 图标一直在，然后我重启了，变化为图标一直不显示。

两种状况下的网络状态和 CFA 状态一致，但是图标显示无法更改。在使用一段时间的状况下，前者（一直有 VPN）未确认是否有改善（重启了），后者（一直无图标）有自动更改为正常状态过来。

**Comment by ForestL18** [comment]
> 然后呢 网络正常吗
> 
> 指关掉 Clash 之后 网络是否回到没有开 Clash 的状态

关掉clash以后网络状态回到没有开clash状态了（即可以正常上国内网，无法上国外网），但是手机VPN的图标一直无法消失，使用其他需要VPN连接的软件没有发现这种情况，故推测是clash的问题

**Comment by Kr328** [comment]
然而 应用并不能控制图标状态 全部由系统控制

既然系统路由已经恢复正常 那么应用的 Vpn 服务已经被停止 剩下来的任何行为 都由系统控制
