### ISSUE TITLE
[BUG] 节点数量较多时会卡死

### ISSUE THREAD

**Issue by Rosabis** [Kr328/ClashForAndroid#967]
**描述出现的错误**
如果单组节点数量超过300时候会出现卡死情况
**如何复现该错误**
复现步骤:
1. ...使用链接添加节点
2. ...启动服务
3. ...代理
4. ...选节点

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
可以正常测速，选节点
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
这个没办法，软件导致手机也卡挂了，截不了图
**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]Xiaomi mi6
 - 系统/ROM: [例如: MIUI 11]MIUI 9
 - Android 版本 [例如: 10]8
 - ROM版本 [例如: 20.3.19]9.2.11

**应用信息**
 - 版本: [例如: 1.1.10]2.3.18
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]app-release-arm64-v8a.apk
 - 应用来源: [例如: Google Play]Github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
系统也没了的话 我也没办法知道为什么

**Comment by Rosabis** [comment]
> 系统也没了的话 我也没办法知道为什么

但是我截了一个logcat，虽然没有截图

**Comment by gonejack** [comment]
心疼作者，报bug真的是个技术活，但这里都是客服的活儿。
