### ISSUE TITLE
[BUG] 在 2.3.18 启用 允许来自局域网的连接 无效

### ISSUE THREAD

**Issue by lmnhe** [Kr328/ClashForAndroid#968]
**描述出现的错误**
在 2.3.18 的覆写中 启用 允许来自局域网的连接 无效，2.3.17 可以正常连接。

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![Screenshot_20210425084344](https://user-images.githubusercontent.com/49748345/115976629-74ee6e80-a5a2-11eb-8462-9355f53db934.png)

![Screenshot_20210425084415](https://user-images.githubusercontent.com/49748345/115976635-89326b80-a5a2-11eb-87a9-10f4254706cf.png)

**设备信息 (请完成以下信息):**
 - 系统/ROM: MIUI 11
 - Android 版本 ：9

**应用信息**
 - 版本: 2.3.18

**Comment by DearDeer7** [comment]
同问，我的clashforAndroid是在Googleplay下的最新版，代理局域网也不行，之前一直用的clashforwin代理挺好使的，突然要用手机给别人手机开个代理，发现无效，配置方法和楼上贴图是一样的。

**Comment by 582583241** [comment]
请问开这个有何作用？

**Comment by DearDeer7** [comment]
> 请问开这个有何作用？

比如在手机A上开一个热点，然后其他设备连A的热点，A可以代理其他设备的流量。一个简单应用就是A开了vpn，然后B设备连A的热点，B也可以享受A的vpn。

**Comment by av365app** [comment]
@lmnhe 
我只是看到你的 Android 系统版本居然还是 9 ……
我 11 都用完了，现在已经升到 12 了。@@
心疼你 1 秒钟。

**Comment by Happiness-in-Danger** [comment]
> 
> 
> 同问，我的clashforAndroid是在Googleplay下的最新版，代理局域网也不行，之前一直用的clashforwin代理挺好使的，突然要用手机给别人手机开个代理，发现无效，配置方法和楼上贴图是一样的。

我记得这个的流量走的是html 有些软件是用不了的,只有浏览器可用,cfw是用tun的让流量强制走udp的,不然也不行.我这边使用是这个情况

**Comment by xuhaoyang** [comment]
@Happiness-in-Danger html是什么

**Comment by Happiness-in-Danger** [comment]
写错了，是http

xuhaoyang ***@***.***> 于 2021年8月31日周二 15:33写道：

**Comment by xuhaoyang** [comment]
新版本挺正常 
![image](https://user-images.githubusercontent.com/1927125/131462944-5111f8e8-3ef2-4006-b5d2-030e24f0cf72.png)
