### ISSUE TITLE
[BUG] wifi设置静态IP, 不使用dhcp, 国内网站无法打开.

### ISSUE THREAD

**Issue by matianhe3** [Kr328/ClashForAndroid#970]
**Describe the bug**
wifi设置静态IP, 不使用dhcp, 国内网站无法打开. 国际网站正常, 关闭clash国内网站正常访问.
使用流量, 国内国外都正常.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**

 - Device: pixel4 oneplus7tpro redmi note8pro redmi k20pro
 - ROM: 
 - ROM Version: 
 - Android Version : 10

**Application Info (please complete the following information):**

 - Version: 2.3.17
 - Apk File Name: 
 - Distribution Channel: Google Play

**Additional context**

**Configure**
If applicable, paste **removed server info** configure
```yaml
# paste here
```

**Logs**
If applicable, paste logs to help detect problem

```
<paste here>
```

**Comment by Kr328** [comment]
@matianhe3 日志 日志 日志 请

**Comment by matianhe3** [comment]
![Screenshot_20210425-200845](https://user-images.githubusercontent.com/24929062/115992804-22dd3580-a602-11eb-8306-5dcaef24480e.jpg)
![Screenshot_20210425-200838](https://user-images.githubusercontent.com/24929062/115992808-27095300-a602-11eb-886e-0a8093ed2bac.jpg)
![Screenshot_20210425-200832](https://user-images.githubusercontent.com/24929062/115992810-283a8000-a602-11eb-8009-e8d58157a42a.jpg)
![Screenshot_20210425-200827](https://user-images.githubusercontent.com/24929062/115992811-28d31680-a602-11eb-8a25-92f2a6690935.jpg)
![Screenshot_20210425-200821](https://user-images.githubusercontent.com/24929062/115992813-2a044380-a602-11eb-9eb7-6f8739833184.jpg)
![Screenshot_20210425-200814](https://user-images.githubusercontent.com/24929062/115992815-2a9cda00-a602-11eb-8833-6875fdd60929.jpg)

**Comment by Kr328** [comment]
1. 关闭 Clash
2. 打开 Logcat
3. 复现问题
4. 关闭 Clash
5. 关闭 Logcat
6. 导出日志到文件
7. 传上来

**Comment by Rosabis** [comment]
>     1. 关闭 Clash
> 
>     2. 打开 Logcat
> 
>     3. 复现问题
> 
>     4. 关闭 Clash
> 
>     5. 关闭 Logcat
> 
>     6. 导出日志到文件
> 
>     7. 传上来

你可以看一下我发的日志吗？贴了十几小时了

**Comment by Kr328** [comment]
你的日志 **没有 DNS 没有 DNS 没有 DNS**

**Comment by Rosabis** [comment]
> 你的日志 **没有 DNS 没有 DNS 没有 DNS**

那不可能，里面有包含的，相当全，我看了你没有下载
https://pan.lanzous.com/iqP6pogum2j

**Comment by Kr328** [comment]
@Rosabis 不是 我就没有之前 除了图片之外的东西 

而且 不要发什么网盘 直接文件 拖动到输入框

**Comment by Rosabis** [comment]
> @Rosabis 不是 我之前就没有看到 除了图片之外的东西
> 
> 而且 不要发什么网盘 直接文件 拖动到输入框

手机发帖没有这个功能

**Comment by Kr328** [comment]
该问系统了 全是 io timeout 所有 Clash for Android 能控制的流程都走完了 剩下来的都是系统控制了

而且 我怎么知道你在另一个 Issue 里发了 一个 Issue 只发与一个问题相关的内容 没有那么多时间去其他地方找
