### ISSUE TITLE
[BUG] 访问控制应用包列表中没有谷歌商店的选项

### ISSUE THREAD

**Issue by DedicationTechnology** [Kr328/ClashForAndroid#971]
**描述出现的错误**
在设置访问控制模式为仅允许已选择的应用时，在访问控制应用包列表中没有谷歌商店的选项，导致在设置访问控制模式为仅允许已选择的应用时，谷歌商店无法代理

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
过滤 -> 系统应用 ->  关闭
