### ISSUE TITLE
[Feature Request] 增加选项在最近任务列表中隐藏

### ISSUE THREAD

**Issue by ShiYue368** [Kr328/ClashForAndroid#974]
**功能描述**
增加一个选项,开启后软件在后台运行,但是不显示在最近任务卡片上.

**描述你希望的实现方式**
可以参考轻启动App,它有这个选项,返回桌面时后台是没有卡片的 ,但是app在后台运行,

**附加信息**
cfa一般都是一天开到晚,在后台老是显示,容易划掉,也很多余,它就应该像是一个系统软件!

**Comment by Kr328** [comment]
Duplicate of #793

**Comment by akw5454521** [comment]
你划掉也不影响运行

**Comment by ShiYue368** [comment]
> 你划掉也不影响运行

影响，划掉就不运行了

**Comment by xuhaoyang** [comment]
@ShiYue368 国产rom

**Comment by ShiYue368** [comment]
> @ShiYue368 国产rom

k30U有推荐的外国rom么

**Comment by xuhaoyang** [comment]
@ShiYue368 用tile不是可以不在最近任务显示么

**Comment by ShiYue368** [comment]
> @ShiYue368 用tile不是可以不在最近任务显示么

这是个模块吗
