### ISSUE TITLE
[Feature Request] 根据网络状况（连接着WiFi/数据）切换配置文件

### ISSUE THREAD

**Issue by DBinK** [Kr328/ClashForAndroid#978]
**功能描述**
检测到网络变化后（WiFi/数据），切换到预设好的配置文件

**描述你希望的实现方式**

**附加信息**

因为宽带和移动数据的网络状况不同，我这边需要通过不同的配置文件来跟随网络切换🤣如果有这个功能也许就不用频繁手动切换了（

当然，这个功能应用面似乎也不算广，如果能丢进二级todolist就好了

**Comment by Kr328** [comment]
Duplicate of #319
