### ISSUE TITLE
测速 URL 貌似使用的 https 导致测速延迟较高

### ISSUE THREAD

**Issue by 0wQ** [Kr328/ClashForAndroid#98]
https://github.com/Kr328/ClashForAndroid/blob/5ddeaf278316d18253ef19541376f3eb22e91628/core/src/main/java/com/github/kr328/clash/core/Clash.kt#L40

在同一网络下
Clash for Windows 默认使用的 `http://www.gstatic.com/generate_204` , ` DIRECT` 测速 50ms 左右.
Clash for Android , ` DIRECT` 测速 180ms 左右.

希望可以在设置中添加修改 测速URL 的选项

**Comment by Kr328** [comment]
未来版本将参照 配置文件

**Comment by 0wQ** [comment]
@Kr328 
同一节点 Clash For Android 相比 SS, SSR 之类的 延迟显示要高的多。

Wireshark 抓包发现测速URL使用的是 https，https 链接比 https 链接要长3倍的时间，我觉得测速使用`http://www.gstatic.com/generate_204` 延迟会更准确些，避免https多次握手的影响。

**Comment by Kr328** [comment]
@0wQ https 更能代表使用体验 (0202 年有几个大网站不使用 https 的

**Comment by 0wQ** [comment]
原来是出于这样的考虑啊，不过看着延迟和CFW其他代理软件比明显高一截，使用时互相对比延迟 还是挺难受的。
我还是期待一下支持修改配置文件吧😂

**Comment by 0wQ** [comment]
> @0wQ https 更能代表使用体验 (0202 年有几个大网站不使用 https 的

原来是出于这样的考虑啊。不过看着延迟和CFW其他代理软件比明显高一截，使用时互相对比延迟 还是挺难受的。
我还是期待一下支持修改配置文件吧😂

**Comment by xqXQzzz1** [comment]
> @0wQ https 更能代表使用体验 (0202 年有几个大网站不使用 https 的

http://www.gstatic.com/generate_204和http://www.google.com/generate_204

那个链接好一点？因为gstatic里有大陆内的节点，如果节点通过gstatic可能会导致测速有速度，且不高，但是实际不能访问外网的问题

**Comment by Bitcion** [comment]
高延迟才是真实速度

**Comment by zjplab** [comment]
可以试试`http://www.youtube.com/generate_204`

**Comment by baichoulishang** [comment]
> > @0wQ https 更能代表使用体验 (0202 年有几个大网站不使用 https 的
> 
> [http://www.gstatic.com/generate_204和http://www.google.com/generate_204](http://www.gstatic.com/generate_204%E5%92%8Chttp://www.google.com/generate_204)
> 
> 那个链接好一点？因为gstatic里有大陆内的节点，如果节点通过gstatic可能会导致测速有速度，且不高，但是实际不能访问外网的问题

我测试了一下，还是使用后者会更准确一点。

**Comment by lankylonky22** [comment]
> 

为啥呀，节点测速都是走的国外服务器呀，访问的是国外的gstatic,所以如果机场没有劫持gstatic的话，显示的就是真实延迟呀

**Comment by lankylonky22** [comment]
> > @0wQ https 更能代表使用体验 (0202 年有几个大网站不使用 https 的
> 
> [http://www.gstatic.com/generate_204和http://www.google.com/generate_204](http://www.gstatic.com/generate_204%E5%92%8Chttp://www.google.com/generate_204)
> 
> 那个链接好一点？因为gstatic里有大陆内的节点，如果节点通过gstatic可能会导致测速有速度，且不高，但是实际不能访问外网的问题


为啥呀，节点测速都是走的国外服务器呀，访问的是国外的gstatic,所以如果机场没有劫持gstatic的话，显示的就是真实延迟呀
