### ISSUE TITLE
[BUG] 规则模式

### ISSUE THREAD

**Issue by 582583241** [Kr328/ClashForAndroid#981]
**描述出现的错误**在覆写下修改为规则模式，但是在代理处修改为规则模式过段时间会自动修改为不修改，但覆写下依旧为规则模式，请问这是什么原因？谢谢！
请简洁的描述你遇到的错误

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**![Screenshot_20210501-101543.jpg](https://user-images.githubusercontent.com/59405504/116768007-3ce5a080-aa66-11eb-9bc6-4d622ba8dbab.jpg)![Screenshot_20210501-101533.jpg](https://user-images.githubusercontent.com/59405504/116768010-4242eb00-aa66-11eb-8a06-e7dece368fd0.jpg)
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```

**Comment by Kr328** [comment]
![IMG_20210501_120805](https://user-images.githubusercontent.com/39107975/116770367-e6805e00-aa75-11eb-97c6-fbd42f71a44f.jpg)
