### ISSUE TITLE
[BUG] 未适配VMESS的zero加密

### ISSUE THREAD

**Issue by TheCGDF** [Kr328/ClashForAndroid#985]
**功能描述**

https://www.v2fly.org/config/protocols/vmess.html#outboundconfigurationobject

```
"zero" 伪加密方式不会加密消息也不会计算数据的校验数据，
因此理论上速度会高于其他任何加密方式。
实际速度可能受到其他因素影响。
```

**描述你希望的实现方式**

CFW、ClashX是支持该加密方式的所以可能只需要更新clash core

但是CFA的clash core似乎已经是最新了（好像也没地方看core版本？）那这大概算是BUG了

**Comment by Kr328** [comment]
反馈上游 请
