### ISSUE TITLE
[Feature Request] 可否像CFW一样，可以在设置里定义parser？

### ISSUE THREAD

**Issue by bug081624** [Kr328/ClashForAndroid#995]
**功能描述**
目前使用Clash for Android 订阅机场的配置文件，规则也是使用订阅链接定义的规则。修改规则yaml后，下次更新订阅会覆盖自定义添加的规则。可否增加clash for win中的parser功能，在每次更新订阅时，先执行parser，预添加规则到更新的订阅文件中？

**附加信息**
其他的与改功能相关的附加信息
![image](https://user-images.githubusercontent.com/66546940/117765767-12af9200-b261-11eb-80ec-48cf4071b795.png)

**Comment by Kr328** [comment]
不能
