### ISSUE TITLE
[Feature Request] Use local hosts by default

### ISSUE THREAD

**Issue by realdeveloperongithub** [Kr328/ClashForAndroid#998]
**Is your feature request related to a problem? Please describe.**
I'm using AdAway as my hosts manager, when clash is turned on, the hosts rules become unavailable.

**Describe the solution you'd like**
Is it possible to use local hosts to resolve domains? Or is it possible batch import hosts file in Override - Use hosts.

**Comment by Kr328** [comment]
feedback to upstream pls
